### ISSUE TITLE
Calling multiple queries in a test always returns the same result

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1000]
**Describe the bug**

When issuing a query through `MakesGraphQLRequests#graphQL()`, subsequent requests after the first ones always return the same result.

**Expected behavior/Solution**

Each query to be handled individually.

The `GraphQLController` always receives the same `GraphQLRequest` object. Since that is a singleton (and i think Laravel's `Request` too?), we need to clear that inbetween calls or architect Lighthouse in such a way that prevents this.

**Steps to reproduce**

1. Write a unit test using the `MakesGraphQLRequests` trait
2. Call `graphQL()` multiple times

**Environment**

Lighthouse Version: `master`
Laravel Version: `5.8`

**Comment by spawnia** [comment]
@enzonotario proposed the following fix:

```php
    protected function graphql(string $query)
    {
        $request = new Request(['query' => $query]);
        $lighthouseRequest = new LighthouseRequest($request);
        $response = app(GraphQLController::class, [
            'request' => $lighthouseRequest,
        ])->query($lighthouseRequest);
        return TestResponse::fromBaseResponse($response);
    }
```

I think we have to investigate if this only happens when using Laravel's `MakesHttpRequest` test helpers, or might also happen when issuing multiple queries in a single HTTP request, which might be a valid use case for some people.

**Comment by enzonotario** [comment]
Hi! This issue was solved in this commit: https://github.com/nuwave/lighthouse/commit/f3d4bc7b86f1acf73b4001e9cf4ab8f7ddb0f4d4

I have added this test to `AllDirectiveTest`:
```
public function testGetAllWithoutCache(): void
    {
        factory(User::class, 2)->create();

        factory(Post::class, 2)->create([
            // Do not create those, as they would create more users
            'task_id' => 1,
        ]);

        $this->schema = '
        type User {
            id: ID!
            posts: [Post!]! @all
        }

        type Post {
            id: ID!
        }

        type Query {
            users: [User!]! @all
            posts: [Post!]! @all
        }
        ';

        $this->graphQL('
        {
            users {
                id
            }
        }
        ')->assertJsonCount(4, 'data.users');

        $this->graphQL('
        {
            posts {
                id
            }
        }
        ')->assertJsonCount(2, 'data.posts');

        factory(User::class, 2)->create();

        factory(Post::class, 2)->create([
            // Do not create those, as they would create more users
            'task_id' => 1,
        ]);

        $this->graphQL('
        {
            users {
                id
            }
        }
        ')->assertJsonCount(8, 'data.users');

        $this->graphQL('
        {
            posts {
                id
            }
        }
        ')->assertJsonCount(4, 'data.posts');
    }
```

If you comment https://github.com/nuwave/lighthouse/blob/805708f901803eb9a90a244ebec0485612e419d0/src/Support/Http/Controllers/GraphQLController.php#L77 it won't work. But with that line everything works fine.

So, should we add that test? If so I think we need a way to disable the `forgotInstance` to be sure the test works well.

What do you think?

**Comment by spawnia** [comment]
@enzonotario great job on investigating that, i already forgot.

Adding the extra tests in #1030 is a great idea, let's go from there.

**Comment by spawnia** [comment]
Just wrote a bunch of tests that issue multiple queries and haven't hit this issue again. Closing until it happens again.
