### ISSUE TITLE
Possible BC 4.4: Failed model detection

### ISSUE THREAD

**Issue by stayallive** [nuwave/lighthouse#1001]
I am not 100% sure what is exactly causing the issue but on 4.3 we have the following schema:

```graphql
type SchoolGroup {
    children: [SchoolGroup!] @hasMany(type: "paginator")
}
```

However when we just tried updating to 4.4 the following error shows up:

```
No class 'SchoolGroup' was found for directive 'hasMany'
```

(which is true, `SchoolGroup` is not an actual class/model, it's namespaced in `...\Models\School\Group` in our app)

This can be fixed with adding the `@modelClass` directive it looks like, but this was never a problem before so I'm puzzled what happened and what the exact way to fix this is, it always just worked :tm: :slightly_smiling_face:

As far as I could tell a `4.3`->`4.4` is not supposed to break existing schema's so this might be a bug. I have tried reading through the PR's that seem to be causing them but they're massive, so I'm not able to determine the root cause exactly.

**Comment by budirec** [comment]
Happen to me too

`
type COMMON_Client {
    client_id: ID!

    contacts: [COMMON_Contact] @hasMany(type: "paginator")
}
`

this is also break with `No class 'SchoolGroup' was found for directive 'hasMany'`

**Comment by spawnia** [comment]
Fixed in https://github.com/nuwave/lighthouse/releases/tag/v4.4.1

**Comment by spawnia** [comment]
One part of the issue was indeed fixed, although this case still remains. Working on it.

**Comment by spawnia** [comment]
Fixed in `v4.4.2`. I am quite confident there should be no issue left, since i covered all instances where pagination was applied.

Can you double check and close the issue if it works for you?

**Comment by stayallive** [comment]
@spawnia it works just like it did before 😄 

It might be worth having a good upgrade path/docs once there is really a need for adding more indications for Lighthouse to know what's going on since I can see this requires a lot of schema changes to "fix" correctly for v5 and from what I've read so far it's not clear (to me at least) why this is needed and how to "resolve" this.

Thank you for the fixing the issue quickly, much appreciated!

**Comment by spawnia** [comment]
Automatic model detection will continue to work in v5.

We added a mechanism for overriding that mapping per type. It might replace mechanisms such as the `model` argument commonly found in field directives. 

The breakage was a result of assuming the need for a type to always map to a model.

**Comment by stayallive** [comment]
Thanks for the explanation, it all makes sense now 😄

Good addition!
