### ISSUE TITLE
Pass arguments fields to policy in @can directive

### ISSUE THREAD

**Issue by faiverson** [nuwave/lighthouse#1002]
Let's say we need to read an argument from the query in order to allow/deny something in a Policy. Currently, we have access to the User of course,  and a name of the argument that is used to find a specific model and we can pass extra args according to the definition:
```
"""
Additional arguments that are passed to `Gate::check`. 
"""
args: [String!]
```
So far I can understand, they are just strings. There is no way to send any extra arguments from the query.

My proposal is to add a new field definition (I called 'fields' in the example) in order to send the query arguments ($args):
```
public function handleField(FieldValue $fieldValue, Closure $next): FieldValue
    {
        $previousResolver = $fieldValue->getResolver();

        return $next(
            $fieldValue->setResolver(
                function ($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo) use ($previousResolver) {
                    $modelClass = $this->getModelClass();
                    $this->args = $args; // get the args to passthrough the gate
```
```
    protected function getAdditionalArguments(): array
    {
        $args = (array)  $this->directiveArgValue('args');
        $fields = $this->directiveArgValue('fields');
        if($fields) { // check if we need to add the args
            $args = array_merge([$this->args], $args);
        }

        return $args;
    }
```

Now we can do something like this in the policy now:
```
public function foo(User $user, $args)
    {
        $foo = Arr::get($args, 'my-integer');
        return $user->hasPermission('permission') && $foo > 400;
    }
```

**Comment by faiverson** [comment]
If this is a good approach I can create a PR

**Comment by spawnia** [comment]
@faiverson you should be able to overwrite the `@can` directive by extending the `CanDirective` class and placing it in your default directives namespace.

If you have a working solution, you can propose a PR. I can not guarantee inclusion in Lighthouse core, but i will consider it.

**Comment by faiverson** [comment]
For more references on [this topic](https://github.com/nuwave/lighthouse/pull/1043)
