### ISSUE TITLE
Enable partial errors

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1006]
**Is your feature request related to a problem? Please describe.**

I ended up having a problem similar to https://github.com/nuwave/lighthouse/issues/407 in our project.

We have a resolver that may return partially correct data, as well as some warnings. Right now, Lighthouse can either return `data` or `errors`, never both.

**Describe the solution you'd like**

I would like to be able to add errors to the result without stopping execution. We would have to add a mechanism that does not rely on Exceptions but rather allows to put errors in some kind of buffer that is collected before ending resolution.

**Comment by joskfg** [comment]
That happens to me too. I'm calling an external graphql server from a graphql server, so the call could return some errors that I'd like to put in the output. #865 would help too.

**Comment by spawnia** [comment]
Resolved through https://github.com/nuwave/lighthouse/pull/1420
