### ISSUE TITLE
Support for Query Complexity Analysis

### ISSUE THREAD

**Issue by TGNThump** [nuwave/lighthouse#101]
webonyx/graphql-php has support for query complexity analysis. It would be helpful if there was a `@complexity` directive that allowed you to set a individual field, and for the paginators to set the complexity to a function that returns the number of results its going to return multiplied by the child complexity, as shown in the example at https://webonyx.github.io/graphql-php/security/

**Comment by TGNThump** [comment]
It might also be nice to add native support for the other https://webonyx.github.io/graphql-php/security/ features too.

**Comment by olivernybroe** [comment]
What about a `@queryDepth(maxDepth: 10)` directive we can set on each query? :)

**Comment by TGNThump** [comment]
@olivernybroe Sounds good. I'm way more interested in the Query Complexity Analysis than Limiting Query Depth, but yeah, both features are definitely needed.

**Comment by olivernybroe** [comment]
@TGNThump Implementing them would be really similiar as they are both just Rules. But I am totally up for having Complexy, QueryDepth and prob. also Introspection disabling.

**Comment by chrissm79** [comment]
@olivernybroe All three of those are definitely items that should be available in Lighthouse... added to `v2.x` label. First beta of subscriptions is done, I need to add some initial docs for it then I'll cut `v2.1` of Lighthouse and I'll get started on new items (such as #101, #99, #98) for `v2.2`. I'll try to keep this issue updated as these items get added in. Thanks @TGNThump @olivernybroe!!

**Comment by spawnia** [comment]
Does the `SecurityDirective` resolve this issue or does it need anything else?

**Comment by spawnia** [comment]
Closing this, as `SecurityDirective` and the `ComplexityDirective` should cover it. @TGNThump if you are still missing something, let us know.
