### ISSUE TITLE
array_map(): Expected parameter 2 to be an array, object given when using @defer

### ISSUE THREAD

**Issue by georgeboot** [nuwave/lighthouse#1018]
**Describe the bug**
When the defer extension is installed and you cache the schema, an error happens:
`array_map(): Expected parameter 2 to be an array, object given`

The initial request (uncached schema) runs successful, but the following request will fail the the above mentioned error.

**Expected behavior/Solution**
No error.

**Steps to reproduce**

1. Activate the `DeferServiceProvider` in `config/app.php`
2. Enable schema caching
3. Clear the cache using `art lighthouse:clear-cache`
4. Do a request.
5. Do another request.

**Output/Logs**

<details><summary>Click to expand</summary>

```json
{
  "message": "array_map(): Expected parameter 2 to be an array, object given",
  "exception": "ErrorException",
  "file": "/Users/george/Sites/my-project/vendor/nuwave/lighthouse/src/Schema/Factories/ClientDirectiveFactory.php",
  "line": 64,
  "trace": [
    ...
  ]
}
```

</details></br>

**Environment**

Lighthouse Version: 4.5.0
Laravel Version: 6.3.0

Link: #1004

**Comment by spawnia** [comment]
The fix should be pretty simple, we just have to change the `array_map` to a `foreach`.

Can you make a PR?
