### ISSUE TITLE
No description in composer.json

### ISSUE THREAD

**Issue by emil-nasso** [nuwave/lighthouse#102]
There is no description for this package, making it hard to find on packagist. Doesn't show up if you search for graphql, for example.

![https://docs.google.com/uc?id=1yGPXYHKwVf1K1E5FqD9DQNjsV_IC5Wfy](https://docs.google.com/uc?id=1yGPXYHKwVf1K1E5FqD9DQNjsV_IC5Wfy)

**Comment by chrissm79** [comment]
@emil-nasso Thanks for bringing this to my attention, the description has been updated!
