### ISSUE TITLE
Correct way retrieve every nth record

### ISSUE THREAD

**Issue by sachaw** [nuwave/lighthouse#1020]
I am working with some large datasets and need to be able to make a query where it skips x out of every y records, so I can get a granular overview of the dataset. However the only thing I can find is laravel's nth collection method, and I cannot find a way to call it with any of the built in directives.

**Comment by spawnia** [comment]
The issue tracker is reserved for bug reports or feature requests. You can ask your question in StackOverflow or Slack.
