### ISSUE TITLE
Generator commands can not handle arrays with multiple namespaces

### ISSUE THREAD

**Issue by Amsterdamys** [nuwave/lighthouse#1029]
**Describe the bug**

I need to store resolvers split by subdirectories, like:

app
---> GraphQL
-----> Queries
--------> CustomFolder1
----------> MyResolver1.php
--------> CustomFolder2
----------> MyResolver2.php

To do that I had to change namespaces->queries param in lighthouse configs.

It was

`'queries' => 'App\\GraphQL\\Queries',`

It become

`'queries' => ['App\\GraphQL\\Queries', 'App\\GraphQL\\Queries\\CustomFolder2'],`

After I did it all resolvers became visible correctly.

But now when I run following command 

`php artisan lighthouse:query Cards/CallsWithCLM2`

I see the following error:

`QueryCommand::getDefaultNamespace() must be of the type string, array returned`

**Expected behavior/Solution**

I think It's better to support having an array as a value for that field.

**Steps to reproduce**

Described above

**Output/Logs**

<details><summary>Click to expand</summary>

```
  ?[41;1m Symfony\Component\Debug\Exception\FatalThrowableError ?[49;22m : ?[33mReturn value
of Nuwave\Lighthouse\Console\QueryCommand::getDefaultNamespace() must be of the type string,
array returned?[39m

  at ?[32mC:\OSPanel\domains\shaman-shamango-stats-api\vendor\nuwave\lighthouse\src\Console\Q
ueryCommand.php?[39m:?[32m36?[39m
    32|      * @return string
    33|      */
    34|     protected function getDefaultNamespace($rootNamespace): string
    35|     {
  > 36|         return config('lighthouse.namespaces.queries');
    37|     }
    38|
    39|     /**
    40|      * Get the stub file for the generator.

  ?[33mException trace:?[39m

  ?[36m1   ?[39m?[33mNuwave\Lighthouse\Console\QueryCommand::getDefaultNamespace("App")?[39m
      ?[32mC:\OSPanel\domains\shaman-shamango-stats-api\vendor\laravel\framework\src\Illumina
te\Console\GeneratorCommand.php?[39m:?[32m97?[39m

  ?[36m2   ?[39m?[33mIlluminate\Console\GeneratorCommand::qualifyClass("Cards\CallsWithCLM2")
?[39m
      ?[32mC:\OSPanel\domains\shaman-shamango-stats-api\vendor\laravel\framework\src\Illumina
te\Console\GeneratorCommand.php?[39m:?[32m53?[39m

  ?[32mPlease use the argument ?[39m?[31m-v?[39m?[32m to see more details.?[39m
```

</details></br>

**Environment**

Lighthouse Version: v4.5.3
Laravel Version: 6.4.0

**Comment by enzonotario** [comment]
I think you want to run `php artisan lighthouse:query Cards\\CallsWithCLM2`

**Comment by spawnia** [comment]
Right now our generator commands extends Laravel's built-in class, which only accounts for the possibility of having exactly one default namespace.

How should the command work when you have two namespaces and you pass a single name?

What we might do is find the common part of all registered namespaces and use that as the default. For example `['App\\Foo\\A', 'App\\Foo\\B']` would result in the default namespace `App\\Foo`.

**Comment by Amsterdamys** [comment]
> What we might do is find the common part of all registered namespaces and use that as the default.

Yes, even that would be much better. What can also be done is parsing this single name which is passes as an argument and deciding which folder should be used according to that.

Describing below:

1) Config has 2 namespaces: _'queries' => ['App\\GraphQL\\Queries', 'App\\GraphQL\\Queries\\Cards'],_
2) This is what's  passed to a command _php artisan lighthouse:query Cards/CallsWithCLM2_
3) As you said above first we determine the common part, which is _App\\GraphQL_
4) Extract a directory from the passed to an argument path which is _Cards_
5) Concat extracted part and the common namespace (App\\GraphQL + Cards) and try to find it in configs

----> if found - generate a new schema to there
----> if not found - just take the common part (App\\GraphQL)
