### ISSUE TITLE
Allow `update` related models on create mutation

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1038]
**Is your feature request related to a problem? Please describe.**

In my project I have one-to-one relation `Candidate`-`Person`. They linked via Person with an optional candidate_id column, so if it set, then person is a candidate.

Now I was implementing mutation for creating candidate. One of the situations - create new candidate with an existing person, so create candidate and link it to person.

I am using `@create` directive, so here is small excerpt of definitions:

```graphql
extend type Mutation {
    createCandidate(input: CreateCandidateInput! @spread): Candidate @create
}

input CreateCandidateInput {
    person: InputPersonRelation
}

input InputPersonRelation {
    create: CreatePersonInput
    update: UpdatePersonInput
}
``` 

Then I tried scenario described above:

```
mutation{
  createCandidate(
    input:{
    email: "test@asd.de",
    person:{
      update: {
        id:838891795,
        firstname:"Tester",
        lastname:"Son"
      }
    }
  }) {
    id
    email
    person {
      id
      firstname
      lastname
    }
  }
}
```

Result - new candidate was created, but it wasn't linked to person. Person input was simply ignored.

Then I looked into code and noticed, that `update` properties are recognised and executed ONLY on update mutation executor.  

**Describe the solution you'd like**

Actually there are two possible solutions for my problem:

1. (What I was thinking of) - allow `update` in such case. The change is not hard - we should simply copy code that is executed if `update` property is defined from `MutationExecutor::executeUpdateWithLoadedModel()` to `MutationExecutor::executeCreate()`.
2. I have to redefine my mutation with changing the side of view. I would have to start with person. Then my situation will not take place. If Person exists, then I would simply update person and it would work.
3. (Just noticed...) use `upsert` function of `update`/`insert`.

Anyway I wanted to discuss it with you. Do you think this is a good thing to be able to update relations why creation of model?

Do I need  insert/update at all, if we upsert is possible?

**Comment by spawnia** [comment]
I previously thought that there is no use case for that, so i left it out of nested mutations. However, it seems easier and more flexible for us to not restrict what can or can't be done in nested mutations. Through the schema definition, the developer is still able to control that.

Nested mutations are totally reworked in https://github.com/nuwave/lighthouse/pull/899 and what you are suggesting should be possible. Looking forward to your feedback and review.
