### ISSUE TITLE
Error when uploaded to server

### ISSUE THREAD

**Issue by PJijin** [nuwave/lighthouse#1039]
```
"No class 'App\\Http\\Graphql\\Mutations\\ProductsMutator' was found for directive 'field'",
```

Works fine on localhost. When uploaded to server this error is shown. ProductsMutator file is there at App\Http\Grpahql\Mutations folder. Not sure any server requirements are needed for Graphql. (Laravel requirements are met.)

**Comment by enzonotario** [comment]
Hi! Please follow the issue template. Make questions in StackOverflow/Slack.
So far you could try to remove the cache: `php artisan lighthouse:clear-cache`.

**Comment by PJijin** [comment]
@enzonotario  Tried. Not working. Added cache false on env too. No luck. Any way to fix this.?

**Comment by enzonotario** [comment]
Well I have to see a bit more of your schema to help you... please come to slack with some code so we all could help you
