### ISSUE TITLE
[4.6] @belongsToMany(type: "paginator")

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#1040]
**Describe the bug**

When using `@belongsToMany(type: "paginator")` only items from `page: 1` are loaded. Next pages won't return items.

Just checked and i have many items to be returned per page.

**Expected behavior/Solution**

Pagination should work for next pages.

**Steps to reproduce**

1.Just define a relationship as `@belongsToMany(type: "paginator")`
2. Query data with  `page: 1`
3.Change to `page: 2`  and no items will be returned.

**Environment**

Lighthouse Version: 4.6
Laravel Version: 6.5

**Comment by robsontenorio** [comment]
I am using it with custom intermediate table, and custom fks, like described on Laravel docs.

https://laravel.com/docs/6.x/eloquent-relationships#many-to-many

```php
return $this->belongsToMany('App\Role', 'role_user', 'user_id', 'role_id');
```

**Comment by robsontenorio** [comment]
I cant paginate over all pages by using REST API endpoint with `->paginate($pageNumber)`

**Comment by enzonotario** [comment]
Hey! I don't really know why you are having problem, just note that the `paginate` signature is like:
```
public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
```
so you should paginate it with: `->paginate(null, ['*'], 'page', $pageNumber)`.

Btw, how is your schema? what query are you doing?

**Comment by robsontenorio** [comment]
Sorry. It has todo with a legacy database driver (Intersystem Caché DB).

**Comment by spawnia** [comment]
Hey @robsontenorio congrats on finding the error.
