### ISSUE TITLE
Fix naming conventions such as 'GraphQL' to 'GraphQl'

### ISSUE THREAD

**Issue by pedzed** [nuwave/lighthouse#1041]
In the PHP world and especially in Laravel, it is the convention to write abbreviations like 'HTTP' in namespaces (and by extension classes) as `Http`. E.g. `App\Http\Requests\MyRequest`, not `App\HTTP\Requests\MyRequest`.

I hate to suggest a breaking change, but `GraphQL` should be renamed to `GraphQl`. The same applies to methods. So `$this->graphQL()` in unit tests should become `$this->graphQl()`. 

It might not look pretty, but naming standards should be followed. Literally every package I use at the moment follows the PHP standards, but at the moment Lighthouse does not.

**Comment by enzonotario** [comment]
I'm with you, but I think most of those naming becomes from `webonyx/graphql-php`, so Lighthouse has to be consistent with that package (I THINK!)
Anyways, in the case of namespaces you can configure them in the config, and for tests I just have an alias, so there is no problem at all.

**Comment by spawnia** [comment]
Wouldn't `Graphql` be better? Looks a bit less ugly.

**Comment by pedzed** [comment]
The official name is GraphQL. 

![image](https://user-images.githubusercontent.com/8146593/68549202-f0cc1980-03f5-11ea-9ddd-d3721dbb6858.png)

If we want to call it Graphql we might as well just keep it as is. However, if we take naming conventions strictly, it's GraphQl.

On the other hand, one could argue that because 'GraphQL' is the name, it is wrong to change the casing. I just don't think that tools such as linters would like it...

**Comment by lorado** [comment]
Well if we change it, I would prefer 'Graphql'. 

In fact - `webonyx/graphql-php` uses 'GraphQL', and I would let it as is.

Are there any linters that are blaming?

**Comment by enzonotario** [comment]
If we are open to change it, I also would prefer `Graphql`. So far I already have this naming in my projects without problems.

**Comment by SirLamer** [comment]
It's referencing SQL and all of the languages build around that like MySQL, PostgreSQL, etc.

**Comment by spawnia** [comment]
Let's keep it as is, consistency with `webonyx/graphql-php` and the overall ecosystem is good.
