### ISSUE TITLE
@whereConstraints not working

### ISSUE THREAD

**Issue by jhoanborges** [nuwave/lighthouse#1044]
I'm using laravel 5.8 with lighthouse 4.6. 
App.php
`'providers' => [
    \Nuwave\Lighthouse\WhereConstraints\WhereConstraintsServiceProvider::class,
],`

Also, i installed this dependency:  composer require mll-lab/graphql-php-scalars

Schema 

```
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")
scalar Date @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Date")
scalar Mixed @scalar(class: "MLL\\GraphQLScalars\\Mixed")

enum Operator {
    EQ @enum(value: "=")
    NEQ @enum(value: "!=")
    GT @enum(value: ">")
    GTE @enum(value: ">=")
    LT @enum(value: "<")
    LTE @enum(value: "<=")
    LIKE @enum(value: "LIKE")
    NOT_LIKE @enum(value: "NOT_LIKE")
}

type Product {
    id: ID!
    name: String!
    description: String!
    slug: String!
    price: Int!
    qty: Int!
    status: Boolean!
}

type Query {
      product(id: ID @eq): Product @find(model: "App\\Product")
    products(
        where: WhereConstraints @whereConstraints(columns: ["qty"])
    ): [Product!]!
}
```

But everytime i copy this  line 

` products(
        where: WhereConstraints @whereConstraints(columns: ["qty"])
    ): [Product!]!`

and refresh graphql-playground, i get this error 
`{
  "error": "Unexpected token < in JSON at position 0"
}`

I'm following the documentation, but i can't see what is wrong.

**Comment by jhoanborges** [comment]
I was trying to show products where quantity is major than zero. So i made this workaround, but i'm pretty sure it's not the best one.

` products(excludeCategory: Int @neq(key: "qty")): [Product!]! @all`

and the query
`query{
	products(excludeCategory:0){
		id
		name
		price
    qty
		images{
			id
			url
		}
	}
}`

**Comment by spawnia** [comment]
Please use proper codeblocks in the issue description.

You won't get the full error in GraphQL Playground itself. Check the network tab or your error logs for the full error message.

**Comment by jhoanborges** [comment]
I checked the console and i'm having this error :
![image](https://user-images.githubusercontent.com/32471957/68786920-33fcd700-0606-11ea-85d8-912f42826d08.png)

and yes `\Nuwave\Lighthouse\WhereConstraints\WhereConstraintsServiceProvider::class` is present in my providers list.

#839

**Comment by spawnia** [comment]
I clarified the error message, see https://github.com/nuwave/lighthouse/pull/1045

Does that help?

**Comment by jhoanborges** [comment]
Oh. It's solved. That should be part of the documentation as well.

I was able to filter by quantities.  This is my final schema and query


` productos(
        where: WhereConstraints @whereConstraints(columns: ["qty"])
    ): [Product!]! @all`


`query{
  productos(
      where:{ column: QTY, operator: GT value: 0}    
  ) {
    name
    qty
  }
}`
