### ISSUE TITLE
Order of expressions in OR should not affect SQL query

### ISSUE THREAD

**Issue by drtheuns** [nuwave/lighthouse#1047]
**Describe the bug**

When passing an `OR` query, the order of the sub-expressions seem to matter. For example, when passing something like `OR(expr1, AND(expr2, expr3))` it will result in the SQL: `(expr1 AND (expr2 AND expr3))`, while `OR(AND(expr2, expr3), expr1)` will result in the correct SQL: `((expr2 AND expr3) or expr1)`. See the example queries below for a more detailed example.

**Expected behavior/Solution**

The order of the expressions passed to OR should not matter.

**Steps to reproduce**

1. Setup project with some models and a database.
2. Add the query to the graphql file:
```
extend type Query {
    clients(filter: WhereConstraints @whereConstraints orderBy: [OrderByClause!] @orderBy): [Client!]! @paginate(type: "paginator" model: "App\\Models\\Client")
}
```
3. Execute the query:
```graphql
query {
  clients(
    filter: {
      OR: [
        {
          column: "name",
          operator: LIKE,
          value: "Victor%"
        },
        {
          AND: [
            {
              column: "first_name",
              operator: EQ,
              value: "Joy"
            },
            {
              column: "last_name",
              value: EQ,
              value: "Cummings"
            }
          ]
        }
      ]
    }
    count: 10
  ) {
    data {
      id,
      name
    }
  }
}
```

4. Observe the SQL: 
```sql
select count(*) as aggregate from `clients` where (`name` LIKE 'Victor%' and (`first_name` = 'Joy' and `last_name` = 'Cummings'));
--                                            expected this to be "or"   ^^^

```

5. Switch the order of the OR expressions:
```graphql
query {
  clients(
    filter: {
      OR: [
        {
          AND: [
            {
              column: "first_name",
              operator: EQ,
              value: "Joy"
            },
            {
              column: "last_name",
              value: EQ,
              value: "Cummings"
            }
          ]
        },
        {
          column: "name",
          operator: LIKE,
          value: "Victor%"
        }
      ]
    }
    count: 10
  ) {
    data {
      id,
      name
    }
  }
}
```
6. Observe the correct SQL:
```sql
select * from `clients` where ((`first_name` = 'Joy' and `last_name` = 'Cummings') or `name` LIKE 'Victor%') limit 10 offset 0
```

**Environment**

Lighthouse Version: 4.6
Laravel Version: v5.7.28

**Comment by spawnia** [comment]
Thanks for the detailed report, i totally agree.

The solution will encompass fixing the implementation in https://github.com/nuwave/lighthouse/blob/master/src/WhereConstraints/WhereConstraintsDirective.php and adding a test to https://github.com/nuwave/lighthouse/blob/master/tests/Integration/WhereConstraints/WhereConstraintsDirectiveTest.php. Accepting PRs.
