### ISSUE TITLE
orderBy Directive Location in Documentation / ide-helper

### ISSUE THREAD

**Issue by omacranger** [nuwave/lighthouse#1048]
**Describe the bug**

`@orderBy` directive location doesn't seem to include all locations where the directive can be applied. It appears `INPUT_FIELD_DEFINITION` should be included in cases where someone is using an `input` type and the `@spread` directive.

**Expected behavior/Solution**

Directive location should be updated to include all valid locations. It would also be nice to have the documentation for this directive updated to include some examples on how to use them in conjunction with input types since filters / inputs are likely a common use case.

**Steps to reproduce**

1. Apply `orderBy` directive on input type where `@spread` is being applied. OrderBy works as expected but isn't listed as a 'valid' location in the schema output of the ide-helper command.

**Environment**

Lighthouse Version: 4.6
Laravel Version: 5.8.35

**Comment by spawnia** [comment]
Can you create a PR to the [docs](https://github.com/nuwave/lighthouse/tree/master/docs) and the [`OrderByDirective`](https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/OrderByDirective.php) ?

**Comment by omacranger** [comment]
Will do.
