### ISSUE TITLE
Event Broadcasted, but no any message received in Pusher Dashboard

### ISSUE THREAD

**Issue by kunaldodiya** [nuwave/lighthouse#1054]
[Event Details - Telescope 2.pdf](https://github.com/nuwave/lighthouse/files/3873226/Event.Details.-.Telescope.2.pdf)
[Job Details - Telescope.pdf](https://github.com/nuwave/lighthouse/files/3873227/Job.Details.-.Telescope.pdf)

Am i doing something wrong ?
I have created latest laravel app and integrated lighthouse to test subscription using pusher, I also installed telescope to debug subscription, now after firing query, I am broadcasting event and It's been broadcasted and processed successfully, also I can confirm php artisan queue:listen shows 

``
[2019-11-21 06:55:59][mjL65RbTlHDZu4pcyOgn4AtNGpCVMQ9H] Processing: Nuwave\Lighthouse\Subscriptions\Events\BroadcastSubscriptionListener
[2019-11-21 06:55:59][mjL65RbTlHDZu4pcyOgn4AtNGpCVMQ9H] Processed:  Nuwave\Lighthouse\Subscriptions\Events\BroadcastSubscriptionListener
``

but when i check pusher dashboard, no message or activities are visible, please help, try to find stackoverflow but there are almost few to no answer related to lighthouse subscrition, if you can give an example app into lighthouse package it would be helpful

**Comment by enzonotario** [comment]
Hi! Lighthouse will not emit that event if there is no subscriber. So, to try it, you will have to have a client subscribed to that subscription.
I have an example with `laravel-webssockets`, but would be easy to switch to pusher (the hard is to use with `laravel-websockets`): https://github.com/enzonotario/lighthouse-laravel-websockets

**Comment by kunaldodiya** [comment]
Thanks, I will check it out and let you know

**Comment by enzonotario** [comment]
sorry I don't know anything about Live Query
