### ISSUE TITLE
No directive found for `softDeletes`

### ISSUE THREAD

**Issue by IronSinew** [nuwave/lighthouse#1057]
**Describe the bug**

When attempting to use the `@softDeletes` directive, it throws this error.

**Expected behavior/Solution**

**Steps to reproduce**

1. Use `@softDeletes` directive
2. ie, `contacts: [Contact!]! @paginate(defaultCount:30) @softDeletes`

**Output/Logs**

Diving into the DirectiveFactory.php it seems as though the `directiveNamespacer->gather()` returns an array of namespaces to attempt to see if it exists as used in the `createOrFail` method.

```
# Add in log output/error messages here 

0 => "App\GraphQL\Directives"
1 => "Nuwave\Lighthouse\Tracing"
2 => "Nuwave\Lighthouse\Schema\Directives"
```

However, it seems that the SoftDeletes (and Restore / Trashed / ForceDelete) directives exist in the Nuwave\Lighthouse\Softdeletes namespace, so that won't ever resolve a class name. 

</br>

**Environment**

Lighthouse Version: 4.6.0
Laravel Version: 6.5.2

**Comment by lorado** [comment]
SoftDeletes are enabled by `Nuwave\Lighthouse\SoftDeletes\SoftDeletesServiceProvider` that should be initiated by laravels package discovery. Try to run `php artisan package:discover`.

**Comment by IronSinew** [comment]
Yes, there was something I missed in the laravel upgrade path for auto discovery. Thanks! Closing.
