### ISSUE TITLE
[Docs] How would I...

### ISSUE THREAD

**Issue by hailwood** [nuwave/lighthouse#106]
This issue exists as a bit of a dumping ground of "How would I do this" questions that we could potentially answer and add to the docs in a specific section.

As any answers are posted the original asker should add them to their question to keep things easy to read. I've provided a few below to give us some structure.

**Comment by hailwood** [comment]
**Question:**
How would I define an external validation rule provider.

**Example Use case**
the simplest example I can see right now is for editing a post, assuming the `slug` needs to be unique across all posts, I need to be able to provide the `id` field from the arguments to the ignore section.

Or conditionally adding rules based on whether another field is present.

**Comment by hailwood** [comment]
Question:
How would I allow a user to only query certain fields **or relations** in a query based on a role (assume $user->role returns 'admin' or 'user') **without breaking eager loading**.

Example Use case:
An admin should be able to query for all products, and all sales related to that product.
A normal user should only be able to query for the product and should not be able to see sales.

Or, a wholesaler should be able to query for the `wholesale_price` of a product, a normal user should be returned `null` if they ask for this field.

**Comment by hailwood** [comment]
**Question:**
How would I add additional fields to a paginated relationship?

**Example Use case:**
Any additional information on a pivot table e.g. Imagine we have `Users` and `Companies` which are related through a many_many relationship. On the pivot table we have an additional column `role` as well as the default timestamp columns `created_at`, `updated_at`.

We want to be able to gain access to this additional information when querying for users of a given company.

**Comment by chrissm79** [comment]
@hailwood A lot of great questions here and I'll try to get to them after work! 

Regarding the following question:

*How would I allow a user to only query certain fields or relations in a query based on a role (assume $user->role returns 'admin', 'user', or 'wholesaler') without breaking eager loading.*

This sounds like a great spot for a directive! So let's create one real quick:

```php
namespace App\Http\GraphQL\Directives;

use Nuwave\Lighthouse\Support\Traits\HandlesDirectives;
use Nuwave\Lighthouse\Support\Contracts\FieldMiddleware;
use Nuwave\Lighthouse\Schema\Values\FieldValue;

class RoleDirective implements FieldMiddleware
{
    use HandlesDirectives;

    /**
     * Name of the directive.
     *
     * @return string
     */
    public function name()
    {
        return 'role';
    }

    /**
     * Resolve the field directive.
     *
     * @param FieldValue $value
     *
     * @return FieldValue
     */
    public function handleField(FieldValue $value)
    {
        $resolver = $value->getResolver();
        $roles = $this->directiveArgValue(
            $this->fieldDirective($value->getField(), $this->name()),
            'includes',
            []
        );

        return $value->setResolver(function ($root, $args, $context, $info) use ($roles, $resolver) {
            if (!in_array($context->user->role, $roles)) {
                return null;
            }

            return $resolver($root, $args, $context, $info);
        });
    }
}

```

And then place it in our schema:

```graphql
type Product {
    price: Float
    wholesale_price: Float @role(includes: ["admin"])
    orders: [Order] @role(includes: ["admin", "wholesaler"])
}
```

In the directive, we're first getting a reference to the original resolver (which in this example handles either returns the `wholesale_price` or returns the `hasMany` relationship for `orders`). We're then running a check to see if the user (provided by the `$context`) has a role that's listed in the schema and if not it returns `null`, otherwise it will call the original resolver and everything will continue down the chain as normal!

**Comment by chrissm79** [comment]
Alright, next question

**Question:**
*How would I define an external validation rule provider.*

With the current beta (`v2.1-beta.9`), the `@validate` directive can be used on both and argument w/ `rules` or a field w/ a `validator`. What you're asking about is the perfect use-case for a `validator`, but just as a refresher, here's how you would define rules for simple arguments:

```graphql
extend type Mutation {
  createUser(
    name: String @validate(rules: ["required", "min:5"])
    email: String @validate(rules: ["required", "email", "unique:users,email"])
  ): Post
}
```

This is great for mutations that have flat arguments. However, you'll likely run into scenarios where your mutation requires nested or more complex data like so:

```graphql
input OrderAddressInput {
  address: String
  city: String
  state: String
  zip: String
}

extend type Mutation {
  placeOrder(
    products: [Int]
    coupons: [Int]
    different_shipping: Boolean
    shipping_address: OrderAddressInput
    billing_address: OrderAddressInput
  ): Post @validate(validator: "App\\Http\\GraphQL\\Validators\\PlaceOrderValidator")
}
```

So all we need to do now is create our validator class. I originally wanted to re-purpose the `RequestForm` provided by Laravel but it's not very straightforward without passing it through the controller so Lighthouse provides a `Validator` you can extend:

```php
namespace App\Http\GraphQL\Validators\Form;

use Nuwave\Lighthouse\Support\Validator\Validator;

class PlaceOrderValidator extends Validator
{
    /**
     * Get rules for field.
     *
     * @return array
     */
    protected function rules()
    {
        $rules = [
            // ...
            'shipping_address.address' => ['required']
            // ...
            'billing_address.address' => ['required_if:different_shipping:1']
        ];
    }

    /**
     * Get validator messages.
     *
     * @return array
     */
    protected function messages()
    {
        return [];
    }
}
```

**Comment by chrissm79** [comment]
Next Question

**Question:**
*How would I allow a user to only update certain fields in a mutation based on a role (assume $user->role returns 'admin' or 'user').*

This one is a bit difficult because there's several ways to attack this problem. 

First, you could just extract the arguments you need based on the user's role inside the resolver function. Not the most elegant solution since you'd have to do that in multiple places if you need to reuse that logic.

Second, you could use the `@can` directive to check a policy on the authenticated user. You would need to create 2 mutations, but you could use the same resolver for both (this is probably the way I'd go):

```graphql
extend type Mutation {
  updateSubscription(
    account: Int
  ): Subscription @field(resolver: "App\\Http\\GraphQL\\Mutations\\SubscriptionMutator@update")

  updateSubscriptionBilling(
    account: Int
    next_bill_on: String
  ) Subscription 
    @field(resolver: "App\\Http\\GraphQL\\Mutations\\SubscriptionMutator@update")
    @con(if: "updateBilling", model: "App\\Subscription")
}
```

Third, you could create another schema to handle a different endpoint (such as `/admin/graphql`) and use an environment variable to point to the correct entry point in the Lighthouse config. I personally try to avoid multiple schemas at all costs, but this is a scenario where I could see the benefits. In you `admin` schema, you could import the base schema and then extend your `Mutation` type to add some additional fields that regular user's wouldn't see.

**Comment by hailwood** [comment]
Hey @chrissm79 Sorry to bug you, just checking you are aware the first question was there - "How would I add additional fields to a paginated relationship?" I imagine this is going to be quite a common one so would be good to get a canonical answer :)

--
Matt

**Comment by chrissm79** [comment]
@hailwood Sorry this one took awhile! Take a look at the answer here:
https://github.com/nuwave/lighthouse/issues/113#issuecomment-389010479

**Comment by hailwood** [comment]
**Question:**
How would I apply different middleware to different queries?

**Example Use case:**
Imagine we have some "catalog" type methods that list things such as categories, these should be accessible by anyone, then we have other queries e.g. listing contacts which should only be accessible by authenticated users.

**Answer:**
```
# no middleware required to query the `categories` field
type Query {
    categories: [Category!]!
}

# "auth:api" middleware required to query `contacts` field
extend type Query @group(middleware: ["auth:api"]) {
    contacts: [Contact]!
}
```

**Comment by panchhithakkar** [comment]
I am really new to using Laravel + GraphQL, I have my project set up - Lighthouse V2, with basic queries running, can you please guide me to query by a specific field I mean something like a where clause with equals or like. Thanks for all the help and support, managed till here with all your documentation and videos for Lighthouse V2. If you could guide me to the proper documentation on this.

**Comment by spawnia** [comment]
Arguments in GraphQL are optional by default, so you could easily just add more arguments to the same field and just add filters to the query for the ones you provided.

```graphql
type Query {
  systems(sku: String, name: String): [System!]! @field(resolver: "App\\Http\\GraphQL\\Query@systems")
}
```

You can also skip writing a custom resolver altogether and use a combination of the `@paginate` directive and the custom filter directives. Take a look at https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/Args/QueryFilterDirectiveTest.php

**Comment by panchhithakkar** [comment]
@spawnia thanks a ton for the reply , those test cases are in toomuvh detail, really helpful for a rookie like me. The issue I have now is that, none of the directives like @where, @include, @search are working in my case except @paginaste. 

Look below:
     type Query {
            systems: [System!]! @paginate(model: "App\\System") 
     }

![image](https://user-images.githubusercontent.com/10554438/42063265-a5fe3248-7ae5-11e8-8c50-3ccaac6347be.png)

**Comment by panchhithakkar** [comment]
I have issues using any type of directives like @where, @neq, @eq as I just described in my previous comment with the screenshots, I just get error when GraphiQL tries to read the schema.graph to show the shema, do I need to activate the directives or anything that I am really missing, my questions may be too basic but I am kind of really struggling to get there for directives, any help would really be appreciated. Thanks in advance.

**Comment by chrissm79** [comment]
@panchhithakkar So the first thing I see is that you need to add double slashes to your schema like so:

```graphql
type Query {
    # the `model` argument should have double slashes for the namespace
    systems(psu: Int @where(operator: ">")): [System!]! @paginate(model: "App\\System")
}
```

Other than that your schema look fine and I tested this out locally and everything seems to be working. If you're still getting the error (after adding double slashes) can you do me a favor and open up the developer tools in your browser and go to your network tab to take a look at the error that you're getting when you try to load the schema?

**Comment by panchhithakkar** [comment]
Hey @chrissm79 , thank you so much for your reply, actually I did have the '\\', somehow did not show up in the copy paste in my comments, none the less, I was able to find out that I am using lighthouse V2 and it does not come with the WhereFilterDirective.php (when i do "composer require nuwave/lighthouse") and I need to create one in order to use a @where directive. I tried to reference the V1 but am stuck in one place where it complains about the type of argument. I added the WhereFilterDirective.php under vendor\nuwave\lighthouse\src\Schema\Directives\Args\

Here is my php file:

      <?php
     namespace Nuwave\Lighthouse\Schema\Directives\Args;
     use GraphQL\Language\AST\ArgumentNode;
     use GraphQL\Language\AST\DirectiveNode;
     use Nuwave\Lighthouse\Schema\Values\ArgumentValue;
     use Nuwave\Lighthouse\Support\Contracts\ArgMiddleware;
     use Nuwave\Lighthouse\Support\Traits\HandlesDirectives;

     class WhereFilterDirective  implements ArgMiddleware
     {
         use HandlesDirectives;

         public function name()
         {
             return 'where';
          }

         public function handleArgument(ArgumentValue $argument)
         {
             $arg = $argument->getArgName();
             $operator = $this->directiveArgValue('operator', '=');
             $clause = $this->directiveArgValue('clause');
             $argument = $this->injectFilter($argument, [
                 'resolve' => function ($query, $key, array $args) use ($arg, $operator, $clause) {
                     $value = array_get($args, $arg);
                      return $clause
                         ? call_user_func_array([$query, $clause], [$key, $operator, $value])
                          : $query->where($key, $operator, $value);
                     },
             ]);
              return $argument;
          }
     }

This is the error that is thrown --> stack-trace

```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Nuwave\Lighthouse\Schema\Directives\Args\WhereFilterDirective::directiveArgValue() must be an instance of GraphQL\Language\AST\DirectiveNode, string given, called in /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Directives/Args/WhereFilterDirective.php on line 37 in file /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Support/Traits/HandlesDirectives.php on line 51
Stack trace:
  1. Symfony\Component\Debug\Exception\FatalThrowableError-&gt;() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Support/Traits/HandlesDirectives.php:51
  2. Nuwave\Lighthouse\Schema\Directives\Args\WhereFilterDirective-&gt;directiveArgValue() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Directives/Args/WhereFilterDirective.php:37
  3. Nuwave\Lighthouse\Schema\Directives\Args\WhereFilterDirective-&gt;handleArgument() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/ArgumentFactory.php:36
  4. Nuwave\Lighthouse\Schema\Factories\ArgumentFactory-&gt;Nuwave\Lighthouse\Schema\Factories\{closure}() [internal]:0
  5. array_reduce() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1313
  6. Illuminate\Support\Collection-&gt;reduce() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/ArgumentFactory.php:38
  7. Nuwave\Lighthouse\Schema\Factories\ArgumentFactory-&gt;applyMiddleware() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/ArgumentFactory.php:21
  8. Nuwave\Lighthouse\Schema\Factories\ArgumentFactory-&gt;handle() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php:163
  9. Nuwave\Lighthouse\Schema\Factories\FieldFactory-&gt;Nuwave\Lighthouse\Schema\Factories\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1009
 10. Illuminate\Support\Collection-&gt;mapWithKeys() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php:164
 11. Nuwave\Lighthouse\Schema\Factories\FieldFactory-&gt;getArgs() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php:42
 12. Nuwave\Lighthouse\Schema\Factories\FieldFactory-&gt;handle() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Support/Traits/HandlesTypes.php:185
 13. Nuwave\Lighthouse\Schema\Factories\NodeFactory-&gt;Nuwave\Lighthouse\Support\Traits\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1009
 14. Illuminate\Support\Collection-&gt;mapWithKeys() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Support/Traits/HandlesTypes.php:187
 15. Nuwave\Lighthouse\Schema\Factories\NodeFactory-&gt;getFields() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php:165
 16. Nuwave\Lighthouse\Schema\Factories\NodeFactory-&gt;Nuwave\Lighthouse\Schema\Factories\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Support/helpers.php:1151
 17. value() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php:205
 18. Nuwave\Lighthouse\Schema\Factories\NodeFactory-&gt;extend() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php:89
 19. Nuwave\Lighthouse\Schema\Factories\NodeFactory-&gt;transform() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php:37
 20. Nuwave\Lighthouse\Schema\Factories\NodeFactory-&gt;handle() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php:183
 21. Nuwave\Lighthouse\Schema\SchemaBuilder-&gt;Nuwave\Lighthouse\Schema\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Support/Collection.php:397
 22. Illuminate\Support\Collection-&gt;each() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php:185
 23. Nuwave\Lighthouse\Schema\SchemaBuilder-&gt;extendTypes() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php:201
 24. Nuwave\Lighthouse\Schema\SchemaBuilder-&gt;injectNodeField() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php:76
 25. Nuwave\Lighthouse\Schema\SchemaBuilder-&gt;register() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php:46
 26. Nuwave\Lighthouse\Schema\SchemaBuilder-&gt;build() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/GraphQL.php:140
 27. Nuwave\Lighthouse\GraphQL-&gt;buildSchema() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/GraphQL.php:66
 28. Nuwave\Lighthouse\GraphQL-&gt;prepSchema() /home/vagrant/code/todo-graphql/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php:18
 29. Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController-&gt;__construct() [internal]:0
 30. ReflectionClass-&gt;newInstanceArgs() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Container/Container.php:800
 31. Illuminate\Container\Container-&gt;build() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Container/Container.php:646
 32. Illuminate\Container\Container-&gt;resolve() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Container/Container.php:601
 33. Illuminate\Container\Container-&gt;make() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:734
 34. Illuminate\Foundation\Application-&gt;make() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Route.php:226
 35. Illuminate\Routing\Route-&gt;getController() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Route.php:796
 36. Illuminate\Routing\Route-&gt;controllerMiddleware() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Route.php:757
 37. Illuminate\Routing\Route-&gt;gatherMiddleware() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Router.php:678
 38. Illuminate\Routing\Router-&gt;gatherRouteMiddleware() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
 39. Illuminate\Routing\Router-&gt;runRouteWithinStack() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Router.php:642
 40. Illuminate\Routing\Router-&gt;runRoute() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Router.php:608
 41. Illuminate\Routing\Router-&gt;dispatchToRoute() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Router.php:597
 42. Illuminate\Routing\Router-&gt;dispatch() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 43. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 44. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/vagrant/code/todo-graphql/vendor/fideloper/proxy/src/TrustProxies.php:57
 45. Fideloper\Proxy\TrustProxies-&gt;handle() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 46. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 47. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
 48. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 49. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 50. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
 51. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 52. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 53. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 54. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 55. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 56. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:51
 57. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
 58. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 59. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 60. Illuminate\Pipeline\Pipeline-&gt;then() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 61. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /home/vagrant/code/todo-graphql/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 62. Illuminate\Foundation\Http\Kernel-&gt;handle() /home/vagrant/code/todo-graphql/public/index.php:55


```

**Comment by spawnia** [comment]
I really like the format of these "How would i" questions. Would be nice to get them worked in to the docs.

@hailwood you could really help improve the docs by adding some those in to the https://github.com/nuwave/lighthouse-docs repo

If you need help on getting started there, feel free to hit us up on Slack

**Comment by panchhithakkar** [comment]
I have a schema where my system table has a many to many relationship with applications table and I maintain the data in a third table system_application. I use hasmany and belongsToMany to achieve the relationship between them and it works out well while pulling data. 

This is how my schema.graphql looks like now: 

`   type query{
    systems
    (
      family: [String] @in(key: "product_family"),  drive: [Int] ,
      orderbycolumn: [String] , 
    ): [System!]! @paginate(model: "App\\System" scopes: ["filterByArgs"])`
   }

I am using a mix of  filter directives and scope. This is my scope function in system.php 

`       public function scopeFilterByArgs($query, array $args){              
            $drive=array_get($args,'drive');
            $dimm=array_get($args,'dimm');
            $cputype=array_get($args,'cputype');                  
            
           return $query->when(sizeOf($args), function($q) 
           use($drive, $dimm, $orderBy, $orderByDirection){  
                 
               if(!empty($drive)){
                   $q->WhereIn('drive_size_25', array_flatten($drive));
                   $q->orWhereIn('drive_size_35', array_flatten($drive));
               }
                           
            });   `

**Comment by oschade** [comment]
Question:
How would I generate content on the server while a mutation.

Example Use case:
I want to generate a random slug for a page.

**Comment by snezhkoigor** [comment]
Hi. i has this code

`type Query @middleware(
    checks: [
        "App\\Http\\Middleware\\Cors"
    ]
) {
    files: [File!]! @paginate(model: "App\\Models\\File")

    fileGetById(
        id: ID! @globalId @eq
    ): File @find(model: "App\\Models\\File")
}

type Mutation @middleware(
    namespace: "App\\Http\\GraphQL\\Mutations"
    checks: [
        "App\\Http\\Middleware\\Cors"
    ]
) {
    # Upload file to server
    filesUpload(storage: String!): [File]
    @field(resolver: "FileMutator@upload")
}

type File @model(class: "App\\Models\\File")
{
    id: ID! @globalId
    storage_name: String!
    storage: String!
    origin_name: String!
    extension: String!
    mime: String
    is_deleted: Boolean
    created_at: DateTime!
    updated_at: DateTime!
}`

And when i trying execute 

`query {
  fileGetById(id: "RmlsZTox"){
    origin_name
  }
}`

i see 

`Illuminate\Database\QueryException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined (SQL: select count(*) as aggregate from &quot;files&quot; where &quot;id&quot; = File) in file /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664`

i understand that RmlsZTox === File:1 but how i can use @globalId in my GraphQL?

Thanks

**Comment by spawnia** [comment]
Closing this issue, as it become less and less useful as it grows larger and gets outdated. Happily accepting PR's to the docs that add a guide for some of the issues in here.

New questions can be added as seperate issues or asked in Slack. Thanks everybody for participating.

**Comment by akkhan20** [comment]
Any example for Union custom resolver?
