### ISSUE TITLE
Recursively merge rules

### ISSUE THREAD

**Issue by markwalet** [nuwave/lighthouse#1061]
**Is your feature request related to a problem? Please describe.**
I've created a custom directive that extends the rule directive. It is a directive that mutates the incoming data before I validate it. For example:

```graphql

input ManageContractTermsRelation {
  create: [CreatePaymentTerm]  # With percentage attribute
  update: [UpdatePaymentTerm] # With percentage attribute
}

input CreateContract {
  terms: ManageContractTermsRelation @relationRules(apply: ["custom_sum:percentage,100"])
}
```
This `@relationRules` directive combines the `create` and `update` values of the input and merges them with the current state of the database. This makes it easier to validate complicated requests:

```php
public function passes($attribute, Collection $value, string $column, string $expected): bool
{
    return $value->sum($column) === $expected;
}
```

The problem I encountered was when I tried to add normal rules to the same attribute:

```graphql
# ...

input CreateContract {
  terms: ManageContractTermsRelation @rules(apply: ["required"]) @relationRules(apply: ["custom_sum:percentage,100"])
}
```

When I do this, the `custom_sum` rule does not get applied to the rules array. After some research I found the cause of the problem in the `FieldFactory::class`. This class merges new rules with the existing ones. But doesn't do it recursively. This makes it impossible to have multiple instances of a `RulesDirective` on the same attribute.

**Describe the solution you'd like**
The fix I suggest is a small one. If we change lines 324 and 325 at `src/Schema/Factories/FieldFactor` to use the `array_merge_recursive` method, my problem is solved.

```php
$rulesA = [
  'terms' => [
    'required',
  ],
];

$rulesB = [
  'terms' => [
    'relation:custom_rule,percentage,100',
  ],
];

// Wrong
array_merge($rulesA, $rulesB);
/*
[
  "terms" => [
    "relation:custom_rule,percentage,100",
  ],
]
*/

// Correct
array_merge_recursive($rulesA, $rulesB);
/*
[
  "terms" => [
    "required",
    "relation:custom_rule,percentage,100",
  ],
]
*/

```
**Describe alternatives you've considered**
I tried to refactor my custom rules directive to a generic one that I could use to insert all rules at the same time. But because some of my rules require data formatting before validating. This isn't going to work without some workarounds or hacks. The proposed solution is (in my opinion) the most clean one.

I am willing to create a PR when this issue is accepted. I will create one for master, and one for older versions that can have this update without breaking anything. I will also write tests for this.

**Comment by spawnia** [comment]
This sounds like a good idea, i would be happy about a PR.

**Comment by markwalet** [comment]
I'm trying to write a test for this. But I don't know how I should register a testing directive for combining rule sets. Can you help me?

**Comment by spawnia** [comment]
If it is just a dummy directive meant for testing, it goes in https://github.com/nuwave/lighthouse/tree/master/tests/Utils/Directives

Actual implementations go in https://github.com/nuwave/lighthouse/tree/master/src/Schema/Directives
