### ISSUE TITLE
[Request] Field And Argument Directives - Applicable To Array Elements

### ISSUE THREAD

**Issue by ievgenklymenko** [nuwave/lighthouse#1063]
Currently you can only apply field and argument directives to a single element. For example there is in-built "trim" transformer, and you cannot use it like this:
`myquery(stringlist: [String! @trim]!): Int!`

To do this, you need to create custom directive, "trimStringOrStringS", and put an 'if' inside which will apply transform logic to every array element incase argument was an array. Then it could be used like:
`myquery(stringlist: [String!]! @trimStringOrStringS): Int!`
`myquery2(string: String! @trimStringOrStringS): Int!`
...and both will work. But this way, it doesn't look good because it confuses with other directives which apply to array as a whole, (not to every element), like @rulesForArray

Same about field directives.

Currently, I'm doing this for almost all of my custom directives, (because it makes sense - directive being usable in array cases too, neglects the need to change its code when there will be such case), and it's pretty much same code every time:
`x = closure()`
`return value = array`
     `    ? array_map(x, value)`
     `    : x(value)`

So I wonder if this could be a built-in feature (e.g. transform@ArgTransformerDirective method would automatically apply its logic to array, or another contract/method specifically for this case), then we would be able to use it as simple as:
`myquery(stringlist: [String! @trim]!): Int!`

**Comment by spawnia** [comment]
While it is a quite elegant solution, the example you are proposing is not valid in GraphQL, you can only place directives after the complete argument definition:

```diff
type Query {
  foo(
-   bar: [ID @trim]
+   bar: [ID] @trim
  )
}
```

There might be argument transformers which want to work on the complete argument array. That is why we can not automatically apply the transformation to the contained elements.

The directives would have to handle that themselves, either automagically or through an extra configuration argument. For transformers such as `@trim`, handling arrays automatically might make sense. Open to PR's.

**Comment by ievgenklymenko** [comment]
Ah, I see. I didn't know that directives exist in actual GraphQL specification - I thought this is a specific to Lighthouse schema feature.

Then maybe, it is better to make additional directive, specifically for arrays, named like 'elementTransform' (or some more clear), which could take a directive name(s) as an argument and apply it to every element like this? :
`myquery(stringlist: [String!]! @elementTransform(directives: ["trim", "customDirective"])): Int!`

This way, when making custom directive, you would only need to write code for singular value - and then use it with inbuilt elementTransform when you need it for arrays.

I can work on PR on free time yes, but steadfast review will be needed :)

**Comment by spawnia** [comment]
That doesn't really work either, considering you could require arguments passed to a directive, e.g. `@leftPad(length: 10)`.

Transformer directives could have a standardized argument, such as `@trim(unpackArray: true)` that applies the transformation on the contents of the array.

You could also just solve the problem by abstracting the code for magically determining if an array is passed, we have such a function in Lighthouse:

```php

    /**
     * Apply a callback to a value or each value in an array.
     *
     * @param  \Closure  $callback
     * @param  mixed|mixed[]  $valueOrValues
     * @return mixed|mixed[]
     */
    public static function applyEach(\Closure $callback, $valueOrValues)
    {
        if (! is_array($valueOrValues)) {
            return $callback($valueOrValues);
        }

        return array_map($callback, $valueOrValues);
    }
```

Here is how you use it:

```php
        return Utils::applyEach(
            static function (string $value): string {
                return trim($value);
            },
            $valueOrValues
        );
```

I think that the custom directives provided by Lighthouse should provide sufficient building blocks for achieving higher levels of abstractions for what you need. Do you think there is something that can be done from a library perspective?

**Comment by spawnia** [comment]
If something actionable helps with this issue in the future, feel free to pick up another discussion.
