### ISSUE TITLE
Allow for composite primary key

### ISSUE THREAD

**Issue by abibby** [nuwave/lighthouse#1064]
I don't know if this is within the scope of the project but I am using a library to add versioning to models, this package adds a `version` column to the primary key of a model. If I get 2 versions of the same model in a request with relationships it will use all of the relationships from one of the versions. 

The following is an example of what happens.

```json
"data": [
    {
        "id": 1,
        "version": 1,
        "relationship_id": 1,
        "relationship": { "id": 1 }
    },
    {
        "id": 1,
        "version": 2,
        "relationship_id": 2,
        "relationship": { "id": 1 }
    }
}
```
The `relationship_id` is different on each version but the relationship it gets is the same.

The way I have found to fix this is by overriding the `getKey` method on models to return a unique value but this can cause issues if it gets used other places where it is expected to be the value of the primary key on the model.

Currently, I am using this abomination, but I know there must be a better way.
```php
public function getKey() {
    if (str_contains(debug_backtrace()[0]['file'], 'vendor/nuwave/lighthouse')) {
        return parent::getKey().'-'.$this->{$this->getVersionColumn()};
    }

    return parent::getKey();
}
```

**Comment by spawnia** [comment]
You can try and update to `dev-master` and set the configuration option `'batchload_relations' => false`.

The issue is that Lighthouse tries to eagerly load the relationships through the BatchLoader and assumes there is a singular key.

Recently, a lot of issues have come up around the relation batch loader, i wonder if it would be better to make it pluggable.

**Comment by spawnia** [comment]
Laravel does not properly support composite primary keys in Eloquent, which we rely heavily upon. We might revisit this once Laravel supports it.

**Comment by ryancwalsh** [comment]
@spawnia Thank you for [this tip in Nov 2019](https://github.com/nuwave/lighthouse/issues/1064#issuecomment-559231449) about `batchload_relations`.

One of my tables uses a composite key, and so while using Lighthouse I was getting an error: 
> "Return value of Nuwave\\Lighthouse\\Execution\\DataLoader\\BatchLoader::buildKey() must be of the type string, null returned"

Now that I set `'batchload_relations' => false`, it seems to work.

**Does this mean that eager loading (directives like @hasMany or @belongsTo) is now completely ignored, and I'm now if I have deeply nested queries, they are much more expensive to run?**

Should I recreate my table with a primary key (even though it's just a simple 2-column joiner table)?

It seems like Laravel Eloquent will [never support composite keys](https://github.com/laravel/framework/issues/5355#issuecomment-72261848).

Thanks so much for  your thoughts :-)

**Comment by spawnia** [comment]
If you need to access the data within your pivot table, it is generally a good idea to give it a primary key. Plays much better with Eloquent and other database tools.
