### ISSUE TITLE
.gitignore schema-directives.graphql

### ISSUE THREAD

**Issue by sweet-greg** [nuwave/lighthouse#1072]
**Describe the bug**

Not really a bug, more of a question tbh.
I noticed the file generated by php artisan lighthouse:ide-helper is encourages to be ignored by git. I'm unsure as to why that is. It seems to me it would be quite handy the file would be added to git. 

Could someone explain why that is?

**Comment by enzonotario** [comment]
Hi! Please follow the issue template and use StackOverflow/Slack to make questions.

I think that file is just for dev, so no need to be in the repo (like many other dev things). But if you want to has that file in git, just remove it from `.gitignore`.

If you still need a better answer, please go to StackOverflow/Slack.
