### ISSUE TITLE
@rename only works on queries, not on mutations

### ISSUE THREAD

**Issue by DJAxel** [nuwave/lighthouse#1073]
The @rename attribute ([documentation](https://lighthouse-php.com/4.6/api-reference/directives.html#rename)) can be defined on any GraphQL Type, but seems to only work on queries and not on mutations.

Firing a mutation for creating an object with a given attribute name in camelCase, the @rename directive declaring the server side property name in snake_case is being ignored and the database gives an SQL error in my case.

Since the documentation describes the directive as "Rename a field on the server side", I feel like it should work both ways. Furthermore, I can't think of a siyuation where it is useful to rename properties one way (download), but not the other way (upload) since the property names in GraphQL and server will differ in both cases.

**Example:**
```GraphQL
# schema.graphql
type Query {
  # Budget
  budgets: [Budget!]! @paginate(type: "paginator" model: "App\\Models\\Budget\\Budget")
}

type Mutation {
  createBudget(
    revenue: Float!
    hours: Int!
    projectId: Int!
  ): Budget @create(model: "App\\Models\\Budget\\Budget")

type Budget {
  id: ID! @rename(attribute: "id")
  revenue: Float! @rename(attribute: "revenue")
  hours: Int! @rename(attribute: "hours")
  projectId: Int! @rename(attribute: "project_id")
  project: Project! @belongsTo
  created_at: DateTime
  updated_at: DateTime
}

type Project {
  id: ID! @rename(attribute: "id")
  name: String! @rename(attribute: "name")
  active: Boolean! @rename(attribute: "active")
  created_at: DateTime
  updated_at: DateTime
}
```

The query/mutation:
```GraphQL
#works as expected
query GetBudgets {
  budgets(count: 10) {
    data {
      id,
      revenue,
      hours,
      project {
        id,
        displayField: name,
      }
    }
  }
}

#Fails, @rename doesn't work
mutation CreateBudget(
  $revenue: Float!,
  $hours: Int!,
  $projectId: Int!,
) {
  createBudget(
    revenue: $revenue,
    hours: $hours,
    projectId: $projectId,
  ) {
    id
  }
}
```

<details><summary>Click to expand</summary>

Output:
`SQLSTATE[HY000]: General error: 1364 Field 'project_id' doesn't have a default value (SQL: insert into `budgets` (`revenue`, `hours`, `updated_at`, `created_at`) values (6600, 66, 2019-12-04 09:18:41, 2019-12-04 09:18:41))`

</details></br>

**Environment**

Lighthouse Version: 4.6
Laravel Version: 6.0.4

**Comment by enzonotario** [comment]
Can you please try with `master` and putting the `@rename` in the mutation argument, as I already told you in StackOverflow?

**Comment by spawnia** [comment]
This only works from versions including and above `v4.7` (which i just released).

You will still have to change your schema definition like so:

```diff
type Mutation {
  createBudget(
    revenue: Float!
    hours: Int!
-   projectId: Int!
+   projectId: Int! @rename(attribute: "project_id")
  ): Budget @create(model: "App\\Models\\Budget\\Budget")
```

**Comment by DJAxel** [comment]
Thanks @spawnia, that worked!

I do need to question the fact that the @rename directive can be set on Types and work out of the box with queries, but when using mutations I have to rewrite the @rename directive for each one. That doesn't seem very intuitive and unneccesary since I believe the @rename directive is meant to convert between the difference in naming and/or casing of front- and backend and whether I'm up- or downloading information shouldn't matter.

So my proposal would be to enable setting the @rename directive on a type, then have all queries and mutations adopt this behaviour except when overwritten by a @rename directive on the query or mutation itself.

**Comment by spawnia** [comment]
The issue with that proposal is that there is no clear mapping between a `type` and field arguments or `input`, they are totally separate in GraphQL.

You can improve reuse by defining an `input` type that contains the arguments that are used for mutating a model.
