### ISSUE TITLE
How to multiple insert on same mutation?

### ISSUE THREAD

**Issue by wjdrnrdlekt** [nuwave/lighthouse#1076]
Hello. 

I know you guys will close this question but i wonder multiple insert is available or not.

**Can i insert multi on same mutation?**

This is my Schema

```
type Test {
    id: ID
    name: String
    msg: String
}

input testInput {
    name: String
    msg: String
}

type Mutation {
    createTest(input: [testInput]): [Test] @create
}
```

This is my mutation query 

```
mutation{
    createTest(input: [
        {id:1,  name: "test", msg:"hahaha",},
        {id:2, name: "test2", msg:"hahahaa" }
    ]) {
        id
        name
        msg
    }
}
```

**Comment by spawnia** [comment]
You can ask questions in Stackoverflow or Slack.

**Comment by let-aurn** [comment]
I think bulk CRUD is very useful and should be provided by the framework.
I'll try to implement it.
