### ISSUE TITLE
@belongsToMany broken in v4.7

### ISSUE THREAD

**Issue by DJAxel** [nuwave/lighthouse#1080]
Using the `@belongsToMany` directive, my application breaks when upgrading from `v4.6` to `v4.7` or `v4.7.1`.

I've already taken a look at the docs of both versions and the `src/Schema/Directives/BelongsToManyDirective.php`, but neither have changed. I guess this is some kind of side effect of another change between the two releases.

</details></br>

**What's happening?**
These are my type definitions in `schema.graphql`:
```GraphQL
type Customer {
  id: ID! @rename(attribute: "id")
  name: String @rename(attribute: "name")
}

type Product {
  id: ID! @rename(attribute: "id")
  description: String! @rename(attribute: "description")
  orders: [Order!] @belongsToMany(relation: "order")
}

type Order {
  id: ID! @rename(attribute: "id")
  name: String! @rename(attribute: "name")
  customerId: Int @rename(attribute: "customer_id")
  customer: Customer! @belongsTo(relation: "customer")
  products: [Product!] @belongsToMany(relation: "product")
  created_at: DateTime
  updated_at: DateTime
}
```

The following query is run in `v4.6`:
```GraphQL
{
  orders(count: 10) {
    data {
      id
      name
      customer {
        id
        name
      }
      products {
        id
        description
      }
    }
  }
}
```

The response is as described below. Note that the products are returned as an array, since there are no products in my database. If there were, they would be returned.
```JSON
{
  "data": {
    "orders": {
      "data": [
        {
          "id": "1",
          "name": "furniture",
          "customer": {
            "id": "1",
            "name": "Linus Torvalds"
          },
          "products": []
        }
      ]
    }
  },
  "extensions": {
    "lighthouse_subscriptions": {
      "version": 1,
      "channels": []
    }
  }
}
```

Then, I upgrade to `v4.7`:

![image](https://user-images.githubusercontent.com/4944158/70536643-6e9f5400-1b5f-11ea-9e44-03a0b193bf27.png)

The same exact query is run again, with this result:
```JSON
{
  "data": {
    "orders": {
      "data": [
        {
          "id": "1",
          "name": "furniture",
          "customer": {
            "id": "1",
            "name": "Linus Torvalds"
          },
          "products": null
        }
      ]
    }
  },
  "extensions": {
    "lighthouse_subscriptions": {
      "version": 1,
      "channels": []
    }
  }
}
```

Note that `products` is now `null`, wheather there are products in the database or not. On one hand it looks like Lighthouse can't find the relation, but on the other hand, the error given should be `"debugMessage": "Call to undefined relationship [productt] on model [App\\Models\\Order\\Order]."`, which is what happens if I enter a faulty relationship name on purpose. See [this pastebin](https://pastebin.com/mjmV8AYw) for the full stacktrace.

**Environment**

Lighthouse Version: `4.7` and `4.7.1`
Laravel Version: `6.0.4`

**Comment by spawnia** [comment]
Thanks for the detailed report. To get the ball rolling, can you try and add a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/BelongsToManyDirectiveTest.php ?

**Comment by HendrikJan** [comment]
I think that what you describe is correct behaviour. You defined

    products: [Product!]

I think that this means that the result is allowed to be null.
If you want to be sure to get an array, you would write

    products: [Product!]!

So the "!" at the end is important.
Could you try your query with th extra "!" at the end?

**Comment by spawnia** [comment]
@HendrikJan adding the `!` is very sensible, i almost always do that when using the to many relations.

@DJAxel i attempted to reproduce your issue but couldn't find a way to trigger the condition you are describing. Did you have any success at nailing down what is happening?

You can check https://github.com/nuwave/lighthouse/pull/1126 for a hint on how you could get started on adding a failing test to Lighthouse.
