### ISSUE TITLE
Using @globalId with @update results in "No query results for model" error

### ISSUE THREAD

**Issue by sinusforce** [nuwave/lighthouse#1081]
I currently try to implement @globalId with my GraphQL schema and everything works fine except for updating a resource (e.g. delete works like a charm!). Maybe I am just missing something?

Here's my schema (excerpt):

```
type Run @node {
    _id: ID! @rename(attribute: "id") @globalId
    id: Int
    identifier: String!
    ...
    created_at: DateTime
    updated_at: DateTime
}

input UpdateRunInput {
    id: ID! @globalId @rules(apply: ["required"])
    identifier: String @rules(apply: ["string"])
    ...
}

extend type Query @protect(guards: ["api"]) {
    "Show by ID"
    run(id: ID @globalId @eq): Run @find
    @can(ability: "view")
}

extend type Mutation @protect(guards: ["api"]) {
    "Update run"
    updateRun(data: UpdateRunInput! @spread): Run
    @can(ability: "update")
    @update

    "Delete run"
    deleteRun(
        id: ID! @globalId @rules(apply: ["required"])
    ): Run
    @can(ability: "delete")
    @delete
}
```

**Expected behavior/Solution**

So querying the resource using __node__ works as expected, as well as deleting the resource works (just with a regular mutation ```mutation { deleteRun(id:"UnVu0jc"){ id } ```) 

But when I try to use ```updateRun``` like so: 
```
mutation {
  updateRun(data: {
    id: "UnVuOjc="
    checkin_type: "changed"
  }) {
    id
    
  }
}
```

it runs into a server error saying 
```
"No query results for model [Innovationmecom\\SimplParticipantManagement\\Models\\Run] Run, 7" 
```
where ```7``` is the correct id of the database entry! So this confuses me as I would think everything seems to be correct?

I read all issues about @globalId and this already helped my making the above work but now I am really stuck and I don't find any other hints somewhere.

**Environment**

Lighthouse Version: ^4.3
Laravel Version: ^6.0

**Comment by spawnia** [comment]
You need to use `@globalId(decode: "ID")`, see https://lighthouse-php.com/master/api-reference/directives.html#globalid
