### ISSUE TITLE
Lighthouse requires Laravel's auth layer even when all endpoints are public

### ISSUE THREAD

**Issue by palypster** [nuwave/lighthouse#1084]
**Describe the bug**

Lightouse ending up with:
"Argument 2 passed to Illuminate\\Auth\\SessionGuard::__construct() must be an instance of Illuminate\\Contracts\\Auth\\UserProvider, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 125",

in case I don't have any auth guard set up (in `config/auth.php` and I even deleted Laravel's default User model. If this is expected, than it should be written somewhere in the documentation.

**Expected behavior/Solution**

Lighthouse shouldn't be dependent on Laravel's Auth layer (default guard) until querying authenticated/authorized endpoint.

**Steps to reproduce**

1. update config/auth.php to disable default guard
2. query any Lighthouse endpoint
3. you see the error

**Environment**

Lighthouse Version: v4.7.1
Laravel Version: v6.2

**Comment by spawnia** [comment]
I would be happy to see a PR for this. If it can be done in a non-breaking manner, i am all for it. If not, we can queue it for the next major version.

**Comment by spawnia** [comment]
You can create a custom `GraphQLContext`, see https://github.com/nuwave/lighthouse/pull/1105 and remove the dependence on guards.
