### ISSUE TITLE
Nested mutations with pivot data 

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1088]
**Is your feature request related to a problem? Please describe.**

In my project I have some pivot tables with additional data. In Laravel while using sync it is possible to define simply array with IDs, but also optional value for specific key with data, that will be stored in pivot data. As example:

```php
$person->jobs()->sync([
  1,
  2 => [
    'from' => '...',
    'till' => '...'
  ]
]);
```

After executing `$person` becomes linked job ID 1 with empty extra pivot data and job ID 2 with given `from` and `till` additional data, that are stored in pivot tables.

Currently in Lighthouse it is possible to define only simple ID array for sync.

And here is my first question - do we need such a feature in lighthouse core? Solution is actually pretty simple, but we have to define structure, that can be accepted by sync resolver.  

**Describe the solution you'd like**

As I know it is not possible to use kind of dictionaries in gql. So we probably need to define an input object, that have kinda "hidden" attribute for ID, like `_id` or kind of. All other values would then be treated like pivot extra data. 

As example, to be able to achive the php code above:

```gql
type Mutation {
  updatePerson(id: ID!, input: UpdatePersonInput! @spread): Person @update
}

input UpdatePersonInput {
  jobs: UpdateJobRelation
}

input UpdateJobRelation {
  sync: [JobSyncInput!]
}

input JobSyncInput {
  _id: ID!
  from: Date
  till: Date
}
```

So mutation would look like this:
```gql
mutation {
  updatePerson(
    id: 1, 
    jobs: {
      sync: [
        {
          _id: 1
        },
        {
          _id: 2,
          from: "...",
          till: "..."
        }
      ]
    }
  ) {
    ...
  }
}
```

Resolver code could look like this:

```php
// $object and $relationName should be calculated before from scheme types. 
// In this example:
// $object = App\Person::find(1);
// $relationName = 'jobs';
$syncArr = [];
foreach ($input['sync'] as $syncInput) {
  $id = $syncInput['_id'];
  unset($syncInput['_id']);
  $syncArr[ $id ] = $syncInput;
}
$object->$relationName()->sync($syncArr);
```

So anyway, just a question - do we need this? Or just don't care, as new input resolver will be possible soon?

**Comment by spawnia** [comment]
Hey @lorado thanks for the great proposal.

It is certainly possible to implement a nested `@sync` resolver - i plan for us to do so eventually: https://github.com/nuwave/lighthouse/issues/1085

Still, i think the solution you propose could be something that can go into the core. It can be done in a backwards compatible manner and should be quite easy from an implementation standpoint.

We can simply detect if the passed in value is an input object and act accordingly. Documentation for this kind of magic is key though.

I think we can just use `id` for the input field and be consistent with the other parts of Lighthouse.

**Comment by lorado** [comment]
Hi @spawnia 

I decided to implement my proposal. I guess it is possible to use it in #1085 later.

By now `sync`, `syncWithoutDetach` and `connect` becomes ability to feed pivot tables.
