### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by mg98** [nuwave/lighthouse#1089]
I do not get subscriptions to work with lighthouse php.

I am using **lighthouse ^4.7** with **laravel/framework ^6.0** and if it matters: Vue.js with ApolloVue on the client-side.

I have followed exactly the tutorial on the official lighthouse documentation on the website and connected it with the pusher api. The connection fails. From the DevTools I can read:

```
WebSocket connection to 'ws://localhost/graphql' failed: WebSocket is closed before the connection is established.
WebSocket connection to 'ws://localhost/graphql' failed: Error during WebSocket handshake: Unexpected response code: 200
```

I have no idea what to do and cannot find any resources on the internet that help.

**Comment by enzonotario** [comment]
Hi! Please follow the issue template, make questions in StackOverflow/Slack.

So far, I think you should point to `localhost:PORT`, not `localhost` (if you're using `laravel-websockets`, or the Pusher's host otherwise).
