### ISSUE TITLE
Add support in @whereConstraints for IN, IS NULL and BETWEEN

### ISSUE THREAD

**Issue by faiverson** [nuwave/lighthouse#1093]
Right now in the @whereConstraints directive we have support for this:
```
enum Operator {
  EQ @enum(value: "=")
  NEQ @enum(value: "!=")
  GT @enum(value: ">")
  GTE @enum(value: ">=")
  LT @enum(value: "<")
  LTE @enum(value: "<=")
  LIKE @enum(value: "LIKE")
  NOT_LIKE @enum(value: "NOT_LIKE")
```
I'm proposing to add more operator and be able to have these:
```
enum Operator {
  EQ @enum(value: "=")
  NEQ @enum(value: "!=")
  GT @enum(value: ">")
  GTE @enum(value: ">=")
  LT @enum(value: "<")
  LTE @enum(value: "<=")
  LIKE @enum(value: "LIKE")
  NOT_LIKE @enum(value: "NOT_LIKE")
  IN @enum(value: "In")
  NOT_IN @enum(value: "NotIn")
  BETWEEN @enum(value: "Between")
  NOT_BETWEEN @enum(value: "NotBetween")
  NULL @enum(value: "Null")
  NOT_NULL @enum(value: "NotNull")**
}
```
There is no way to ask if something is NULL or if an ID is IN(1,2,3,4)
it will be a very easy change:
Since Eloquent support shortcuts like whereNot, whereNull, whereIn, whereNotIn, etc
The change should be at the end of the **handleBuilder** method changing the **$where** dynamically to accept these shortcuts and probably the parameters too:
```
$where = 'whereNull';
$builder->{$where}(
                $column,
                $whereConstraints['value']
            );
```

let me know your thoughts!

**Comment by spawnia** [comment]
The reason why we have not done those operators yet is that their *arity* is different from the ones we have right now. This can be solved, but we have to make a few design decisions.

## `IN`

Requires a list of values. Should null be allowed as values within this list?

## `BETWEEN`

Requires exactly two values. I would tend to use an input object for that, as that would ensure that valid values are passed by design. How should the fields be named? `start` and `end`? `from` and `to`?


## `NULL` and `NOT_NULL`

Require no value, but GraphQL forces us to pass one. We might merge them into one operator and use a boolean value to decide between them.

**Comment by faiverson** [comment]
I imagine it is an open question, so there I go with my opinion :)
**IN**
Null and empty string should not be allowed as values. I think it is not the point of IN clause

BETWEEN
I'd use the same input ("values") that it is a mixed field sending an array with 2 values. We can check that later and we generate an exception if it is wrong. That way you don't need to worry about new stuff.

NULL and NOT_NULL
I think you don't want to ignore the value field. (easy solution because it doesn't require new effort)

Btw: about naming, we use **field** in other directives like @orderBy and in whereConstraints we use **columns**.
Shouldn't be the same word in all the directives?

**Comment by lorado** [comment]
### `IN`

How does Laravel behave, if you gives some `null` values into array? Are they ignored? I think we have to try to make the same, as Laravel do, so it is expected.

### `BETWEEN`

How about simply array with exactly two values? Same as in Laravel.

### `NULL` and `NOT_NULL`

How about to define something like `nullable`, where we can puss an enum, that can be either `NULL` or `NOT_NULL`?

**Comment by faiverson** [comment]
#1099
