### ISSUE TITLE
Test in Lumen

### ISSUE THREAD

**Issue by rafaelmarcelino19** [nuwave/lighthouse#1094]
I am using lumen 6.0 and php 7.2 added MakesGraphQLRequests to TestCase and when I try $this->postGraphQL() this returns an error: Call to undefined method ExampleTest::postJson()

So I override the methods in TestCase and changed the return to Response and not TestResponse because lumen doesn't have Illuminate\Foundation

In place of $this->postJson() I made $this->post()

And now Work

**Comment by spawnia** [comment]
Using `TestResponse` seems really useful, is it not available at all in Lumen?

**Comment by spawnia** [comment]
`MakesGraphQLRequestsLumen` has been around for a while now.
