### ISSUE TITLE
route middleware not work on lumen but global middleware  work

### ISSUE THREAD

**Issue by amirhossein320** [nuwave/lighthouse#1095]
**when my code like below **it`s not work****
**but when I comment the route middleware and uncomment the global middleware its work**

```
type Query {
    me: User! @middleware(checks:["auth"]) @auth
}

type User {
    id: ID!
    name: String!
    api_token: String !
    updated_at: DateTime!
    profile: User! @hasOne
}
```

**and this is my app file** 
bootstrap/app.php

```

$app->middleware([
//    'auth' => App\Http\Middleware\Authenticate::class,
]);

$app->routeMiddleware([
     'auth' => App\Http\Middleware\Authenticate::class,
]);

/*
|--------------------------------------------------------------------------
| Register Service Providers
|--------------------------------------------------------------------------
|
| Here we will register all of the application's service providers which
| are used to bind services into the container. Service providers are
| totally optional, so you are not required to uncomment this line.
|
*/

$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\AuthServiceProvider::class);
// $app->register(App\Providers\EventServiceProvider::class);
```
**when my code like above **it`s not work****
**but when I comment the route middleware and uncomment the global middleware its work**

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
