### ISSUE TITLE
How to 'orderBy' the related model?

### ISSUE THREAD

**Issue by boogiebug** [nuwave/lighthouse#1096]
How can I order the result by the value of related model?

Suppose I have following schema:

```graphql
type MainModel {
  id: ID!
  title: String!
  other: OtherModel! @belongsTo
}

type OtherModel {
  id: ID!
  name: String!
}

type Query {
  main_models(
    orderBy: [OrderByClause!] @orderBy
  )
}
```

When I order the `main_models` query result using the field `other.id`, I'll got the table-missing error in my query. Please suggest.

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
