### ISSUE TITLE
Is there a way to get the schema.json output like lighthouse v1 had? 

### ISSUE THREAD

**Issue by alexwhb** [nuwave/lighthouse#110]
So first off lighthouse v2 is awesome!!!! great work! It's so much more simple than v1. I'm currently working on upgrading a project to using lighthouse v2 and I'm getting stuck updating to Relay Modern, because it requires either the schema.graphql or schema.json file to compile the static files from, but it does not recognize the fields when you do things like this `someFeild: [Type!]! @paginate(type:"relay" model: "SomeModel")` because it does not know that translates to `someFeild(first: Int! after: String):`

So am I missing something obvious? Or is this something that's not currently supported?

**Comment by kikoseijo** [comment]
The power of a single schema its awesome, 
I think you missing a query with relationships,
What about the example projects? 
https://github.com/nuwave/lighthouse-example

**Comment by kikoseijo** [comment]
Just another tip, on the React side with Relay Modern, im using commands like:

`yarn db`

```json
"scripts": {
  "db": "yarn schema && yarn relay",
  "schema": "graphql get-schema -i -e dev",
  "relay": "relay-compiler --src ./src --schema ./schema.graphql",
}
```

**Comment by alexwhb** [comment]
@kikoseijo Thank you so much for your detailed explanation. This is soooo helpful. 👍
