### ISSUE TITLE
Return a nicer error after sending a GET request without a (valid) body

### ISSUE THREAD

**Issue by Ilyes512** [nuwave/lighthouse#1101]
**Is your feature proposal related to a problem? Please describe.**

When you hit the `/graphql` endpoint (with a Browser - `/GET`-request) of a new Laravel installation with of course lighthouse itself installed, you get the fallowing response:

```json
[
  {
    "errors": [
      {
        "message": "Syntax Error: Unexpected <EOF>",
        "extensions": {
          "category": "graphql"
        },
        "locations": [
          {
            "line": 1,
            "column": 1
          }
        ]
      }
    ]
  }
]
```

**Describe the solution you'd like**

Without going into the code, I guess this is because no body was send. I think this can easily be detected. I think a nicer error message could be returned (i.e. `invalid graphql query`, `no body received`, ...?).

**Describe alternatives you've considered**

I could write a middleware to fetch such empty requests and return a valid Graphql error response with a better message, but I think this should be handled within lighthouse it self.

I am willing to make a PR, but I first wanted to know if this is something that should be solved.

**Comment by spawnia** [comment]
Thanks for the issue, i like the idea. Good point.

I started working on improving the basic validation for such errors in a branch, you could pick up on that and make a PR. See https://github.com/nuwave/lighthouse/tree/proper-basic-validation

**Comment by spawnia** [comment]
Resolved through https://github.com/nuwave/lighthouse/pull/1424
