### ISSUE TITLE
Adding key-value shows in array instead of Object

### ISSUE THREAD

**Issue by Palak28** [nuwave/lighthouse#1103]
I am using Lumen and Lighthouse graphql. When I want to add extra key-value with the eloquent model result, it shows the response in array format where I want the additional response as an Object. Can anyone help me how I can solve it

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
