### ISSUE TITLE
Implement connect for hasOne and hasMany relation

### ISSUE THREAD

**Issue by HendrikJan** [nuwave/lighthouse#1109]
**Is your feature proposal related to a problem? Please describe.**

I have an ```account``` that has one ```employee```. (the employee table has an ```account_id```).  
I want to update the ```account``` so that another ```employee``` becomes connected to the ```account```.  
This means that the current ```employee``` gets the ```account_id``` set to ```null``` and another ```employee``` gets the ```account_id``` set to the id of the ```account``` in question.

I've asked a question on stack-overflow here: https://stackoverflow.com/questions/59546687

**Describe the solution you'd like**

It would be possible to use ```connect: ID!``` on an hasOne relation and ```connect: [ID!]``` on an hasMany relation.

Also the documentation for nested relation hasMany would change the list of possible mutations from

```
input UpdatePostsRelation {
  create: [CreatePostInput!]
  update: [UpdatePostInput!]
  upsert: [UpsertPostInput!]
  delete: [ID!]
}
```

to 

```
input UpdatePostsRelation {
  create: [CreatePostInput!]
  update: [UpdatePostInput!]
  upsert: [UpsertPostInput!]
  delete: [ID!]
  connect: [ID!]
  sync: [ID!]
}
```

**Describe alternatives you've considered**

The alternative for me is to change the relation from the ```belongsTo``` side.  
In stead of using
```
mutation {
  updateAccount(input: {
    id: 12
    employee: {
      connect: 2
    }
  }) {
    id
    employee {
      id
    }
  }
}
```

I can update the employees:

```
mutation {
  updateEmployee(input: {
    id: 1
    account: {
      delete: 12
    }
  }) {
    id
    account: {
        id
    }
}

mutation {
  updateEmployee(input: {
    id: 2
    account: {
      connect: 12
    }
  }) {
    id
    account: {
        id
    }
}
```

**Comment by lorado** [comment]
Im am a little bit confused... The idea is interesting, but it is kinda not a laravel way =\ And as we try to mirror laravel functionality with directives, your proposal probably will never take a place in lighthouse...

Respecting [laravel docs (Belongs To Relationships section)](https://laravel.com/docs/6.x/eloquent-relationships#updating-belongs-to-relationships) you have to use `associate()` and `dissociate()` on belongs-to relations, so it means even in Laravel (without lighthouse) you have to fetch your both employees and dissociate one from user, and associate another one with user. In short - act from the belongs-to side. I don't know other possible way to achieve this.

In Lighthouse it is already implemented with `connect` and `disconnect` keywords, also from the belongs-to side. You can read more in the [lighthouse documentation (belongs to section)](https://lighthouse-php.com/master/eloquent/nested-mutations.html#belongs-to). I didn't try it, but it should work

What you can also do in your project, if you don't want to update your data from belongs-to side:
1. Use custom field resolver for you mutation
2. Create custom directive that implements `ArgResolver`, so you can reuse created directive along your input types. Using `ArgResolver` ist a new feature and by the time not released, but it is merged in master and will be released soon. So if you want to try it out, checkout master branch

**Comment by HendrikJan** [comment]
Thank you.  
I did not realize that this is not Laravel functionality or that you try to mirror Laravel functionality.

Thank you for suggesting a solution.
I'll give it a try.
