### ISSUE TITLE
Argument filters are not optional

### ISSUE THREAD

**Issue by hailwood** [nuwave/lighthouse#111]
Take the following schema

```gql
type Query {
    me: User @auth
    users(
        name: String @where(operator: "like")
        id: ID @eq
    ): [User!]! @paginate(model: "App\\User")
}
```

I'd expect to be able to query

```gql
{
    users(name: "Dr%") {
        id
        name
    }
}
```

To be able to get all the users whose names start with "Dr".
Unfortunately due to `id` not being passed the query gets `AND "id" IS NULL" appended, Which obviously isn't what we want! We need to be able to query via just name or just id

**Comment by kikoseijo** [comment]
You are right @hailwood , probably your example isn't the best, because by the id you will only be able to get 1 record, right?

 ill change it to `email` instead of `id`, and you will get same results, when you try to search for name like `Dr%` and email its null.

We probably need some filtering similar to:

`$request->filled('email')` 

And then if its not present on request we can avoid it.

Does this sound right?

**Comment by hailwood** [comment]
@kikoseijo yeah you're right, the example isn't the greatest, I just wanted to add two filters, probably could have gone with `@in` instead but oh well.

That idea almost sounds right, I'm just not sure how to deal with if the user actuallys wants null..
I wonder if we need to do some special processing and look for the strings `IS NULL` or `IS NOT NULL` and apply a `whereNull` or `whereNotNull` respectively?

Not sure, just tossing ideas out there.Perhaps I'm overthinking it and we don't need the user to be able to say is null/is not null...

**Comment by kikoseijo** [comment]
Ill go for checking the existence of a field even if its empty, if it exists on query vars then process, otherwise skip-
I have done some hardcoded `(string) "NULL"`, but, you know, this isn't Laravelish!

**Comment by chrissm79** [comment]
@hailwood In my mind, the way that it would work should be if the `id` and the `name` is passed in the query (or variables) then process it, whether it be `null` or not. If the argument is excluded then skip it. So:

```graphql
{
    users(name: "Dr%") {
        id
        name
    }
}
```

would skip the `id` query, but if `null` where provided as a variable then it would include it in the query. Regardless, right now it is processing everything so I'll get it updated!

**Comment by chrissm79** [comment]
@hailwood The latest commits to master should resolve your issue. Give it a try and let me know!

https://github.com/nuwave/lighthouse/blob/master/src/Support/Database/QueryFilter.php#L64-L67

**Comment by hailwood** [comment]
Thanks @chrissm79 ,

Will give this a go this evening and report back.

**Comment by crisu83** [comment]
@hailwood I'm not sure I understand the underlying issue, is it a bug? If so, could you please provide some more information on how it works now and how it should work? We can take a look at this once I have some more information.

**Comment by hailwood** [comment]
Great job @chrissm79,

Everything is working perfectly :+1:
