### ISSUE TITLE
@upsert directive fails if there is no id

### ISSUE THREAD

**Issue by enzonotario** [nuwave/lighthouse#1113]
**Describe the bug**

In `master`, `@upsert` directive is not working without an `id` in the input.

**Expected behavior/Solution**

`@upsert` directive should work whether there is an `id` or not in the input. (It was working in this way before the amazing #899 PR).

**Steps to reproduce**

1. Write a mutation with the `@upsert` directive like:
```graphql
type Mutation {
    upsertTask(input: UpsertTaskInput! @spread): Task @upsert
}

input UpsertTaskInput {
    id: ID
    name: String
}
```
2. Execute it like:
```graphql
mutation {
    upsertTask(input: {
        name: "foo"
    }) {
        id
        name
    }
}
```
3. It will fails since there is no `id` in the input. But I think `@upsert` should falls to create a task, instead of try to update one (as it is working in Lighthouse 4.7).

**Output/Logs**

<details><summary>Click to expand</summary>

```
ErrorException : Undefined index: id
```

</details></br>

**Environment**

Lighthouse Version: `master`
Laravel Version: `6.4.1`

**Comment by lorado** [comment]
That is funny... I thought always, that you have to define an ID for `upsert`. And I always asked myself - how the heck I should know new ID on the entry... and didn't even tried it out. I got this thought from docs... so maybe update docs also?

Read this section: https://lighthouse-php.com/4.7/eloquent/getting-started.html#update

> Since upsert can create or update your data you must have all the minimum fields for a creation as required. The `id` is always required and must be marked as fillable in the model. 

And also here: https://lighthouse-php.com/4.7/api-reference/directives.html#upsert

> Lighthouse will try to to fetch the model by its primary key, just like `@update`. If the model doesn't exist, it will be created using the given `id`. 

Huh?
