### ISSUE TITLE
@whereConstraints Documentation Issues

### ISSUE THREAD

**Issue by CPSibo** [nuwave/lighthouse#1115]
I want to make sure I'm not just doing something wrong with the @whereConstraints directive before making a pull request to amend the documentation. If you can answer my questions below, I'd be happy to make the documentation for this directive correct and more user-friendly.

**Describe the bug**

The example code gives this for the schema:
```graphql
type Query {
    people(
        where: WhereConstraints @whereConstraints(columns: ["age", "type", "haircolour", "height"])
    ): [Person!]!
}
```
and this for the actual query:
```graphql
{
  people(
    filter: {
      where: [
        {
          AND: [
            { column: AGE, operator: GT value: 37 }
            { column: TYPE, value: "Actor" }
            {
              OR: [
                { column: HAIRCOLOUR, value: "red" }
                { column: HEIGHT, operator: GTE, value: 150 }
              ]
            }
          ]
        }
      ]
    }
  ) {
    name
  }
}
```
However, doing so produces 
`"Unknown argument "filter" on field "people" of type "Query"."`

Having looked at others' code, I'm guessing nesting `filter:` and `where:` is a typo and it should only be 
```graphql
{
  people(
      where: ...
```

Further, I can't find any combination of the default `WhereConstraints` type that allows for `AND` or `OR` arrays, as the example does. A schema like:
```graphql
type Person{
    id: ID!
    name: String!
    age: Int!
}

type Query {
    people(
        where: WhereConstraints @whereConstraints
    ): [Person!]!
}
```
seems to only allow queries like:
```graphql
{
    people(
         where: { column: "name", operator: EQ, value: "whatever" }
    ){
        id
    }
}
```

If I include the `PersonWhereConstraints` and `PersonWhereColumn` types in my schema and change `PersonWhereColumn` to use the `Operator` enum, rather than a `String`, for the `operator` field, the code finally runs using a query more like the example given.

So, is the following correct:
1. The example should not be using `filter: where:` as a nested parameter.
2. The example query will only work if the `PersonWhereConstraints` and `PersonWhereColumn` types are defined.
3. The example query will only work if `PersonWhereColumn` uses the `Operator` enum, rather than a `String` type.
4. The example schema for the query should include something like `@all` at the end.

Also, there appears to be a typo where you're using `PersonWhereWhereConstraints` rather than `PersonWhereConstraints`. As well, there's an unterminated string for the comment above the `PeopleWhereWhereConstraints` definition.

**Environment**

Lighthouse Version: 4.7
Laravel Version: 6.2

**Comment by CPSibo** [comment]
Ah, I answered my question #2 and #3. The correct query shape should be as follows when using the default `WhereConstraints` type:
```graphql
{
    people(
        where: {
             AND: [
                 { column: "name", ... }
                 { column: "age", ... }
             ]
        }
    )
}
```

So the example in the docs will only work if all types are defined and the query itself is much more flattened.

**Comment by spawnia** [comment]
@CPSibo Thanks for bringing this up, you make some really good points. Can you review the docs changes in https://github.com/nuwave/lighthouse/pull/1099?

**Comment by CPSibo** [comment]
I added my comments to your PR. 

Did I misunderstand that people should define their own input and enum to customize the behavior of the directive? From your version of the docs, it sounds like people are expected to use the `WhereConstraints` input and just define the `columns` for `@whereConstraints` to let Lighthouse make the input and enum for them.

If so, it might be worth pointing out that you showing the input and enum is not meant to encourage people to define their own implementations of it all over their schema. 

And again, I think it's worth explicitly saying that not defining the `columns` parameter  means the client must query with strings and not column enums since it's a change in behavior that will throw errors if disregarded.
