### ISSUE TITLE
Add support for specifying column names with `@orderBy`

### ISSUE THREAD

**Issue by chescos** [nuwave/lighthouse#1117]
As far as I am aware, it's currently not possible to specify validation rules for the `@orderBy` directive. When the user supplies an invalid column, an exception is thrown because the SQL query results in an error. Shouldn't there be a way to specify an array of allowed columns through the `@orderBy` directive?

**Comment by enzonotario** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

**Comment by spawnia** [comment]
This already works in `@whereConstraints`. I recently ran into this as well and started implementing it for `@orderBy` as well, good catch. Check https://github.com/nuwave/lighthouse/pull/1118 for progress.

**Comment by chescos** [comment]
Awesome, thanks for the quick response!
