### ISSUE TITLE
The input created by the `@whereConstraints` directive is missing a description

### ISSUE THREAD

**Issue by chescos** [nuwave/lighthouse#1120]
The [createWhereConstraintsInputType](https://github.com/nuwave/lighthouse/blob/master/src/WhereConstraints/WhereConstraintsServiceProvider.php#L51) method of the `WhereConstraintsServiceProvider` has a `$description` argument, it's just not used when sending the input to the AST.

I guess that was a simple oversight because the method does receive a valid description from the [WhereConstraintsDirective](https://github.com/nuwave/lighthouse/blob/master/src/WhereConstraints/WhereConstraintsDirective.php#L148) class.

**Comment by spawnia** [comment]
Good find, thank you.
