### ISSUE TITLE
Some inputs and types are missing descriptions

### ISSUE THREAD

**Issue by chescos** [nuwave/lighthouse#1123]
I've noticed that some inputs and types don't have descriptions, for example, the [PageInfo](https://github.com/nuwave/lighthouse/blob/ced6496c4cdb4aea422c4cca4d875244c5837697/src/Schema/AST/ASTBuilder.php#L286) type or the [OrderBy](https://github.com/nuwave/lighthouse/blob/ced6496c4cdb4aea422c4cca4d875244c5837697/src/Schema/AST/ASTBuilder.php#L392) input.

Is this intentional? Otherwise, I'd be happy to submit a PR that adds the missing descriptions.

**Comment by spawnia** [comment]
I would be quite happy about seeing them improved, sure.
