### ISSUE TITLE
Add upgrading guide to web document

### ISSUE THREAD

**Issue by axe-me** [nuwave/lighthouse#1128]
We are a early user of lighthouse. Thanks for the great work first.

But now we are too behind from latest version of this package. So we decided upgrade it, however we didn't see any upgrading guide in the official website. It will be great if you can sync the change logs to the web.

**Comment by spawnia** [comment]
The complete changelog is present at https://github.com/nuwave/lighthouse/blob/master/CHANGELOG.md

How can this be improved?

**Comment by lorado** [comment]
I think small upgrade guide with breaking changes is helpful and is probably easier and faster to use, as to read all the changelogs. So I am definitely for writing such a guide

**Comment by spawnia** [comment]
> I think small upgrade guide with breaking changes is helpful and is probably easier and faster to use, as to read all the changelogs. So I am definitely for writing such a guide

Sure, that is what https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md is for. I guess we could try and add a menu item to the website that contains both the changelog and the upgrade guide.

**Comment by axe-me** [comment]
Sorry, didn't notice that UPGRADE.MD file. I feel the laravel upgrade guide format is quite clear, prob lighthouse can do something similar to that https://laravel.com/docs/6.x/upgrade .
