### ISSUE TITLE
Define field middleware directive execution order

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1136]
**Is your feature proposal related to a problem? Please describe.**

Relates to https://github.com/nuwave/lighthouse/issues/894, https://github.com/nuwave/lighthouse/issues/854

The execution of certain field middleware directives should always happen in a certain order, since some may depend upon others. While in principle, ordering the definitions in the schema can be used to define this correctly, it is not always practical to do so.

When using directives on a type that are automatically placed on its fields, the order cannot be controlled. Also, it can easily be done wrong by accident.

**Describe the solution you'd like**

Ensure a particular execution order for well-known directives. It would be nice to expose this configuration to the user. This idea is inspired by how Laravel handles middleware execution order.

**Describe alternatives you've considered**

Document the fact that directive order is significant. This should be useful regardless.

**Comment by lorado** [comment]
I like the idea. Don't know how it is implemented in Laravel (didn't take a look yet), but do you have some ideas how to implement it? I think it has to take a place in `BaseDirective`.

**Comment by spawnia** [comment]
I think we can add a configuration option to `lighthouse.php`, maybe something like this:

```php
'field_middleware_order' => [
    BuiltInDirective::class,
    CustomDirective::class,
]
```

Then, before applying the middleware, we can sort them: https://github.com/nuwave/lighthouse/blob/master/src/Schema/Factories/FieldFactory.php#L127

**Comment by lorado** [comment]
So it is then possible to sort FieldMiddleware directives. How about other directives? If we take #1116 e.g., the main issue is there that `@restore` should be executed before `@softDeletes`, one is `FieldResolver` + `FieldManipulator`, and the other is `FieldManipulator`.

**Comment by spawnia** [comment]
@lorado i don't think we can generalize this configuration across all directive types, since their execution happens at different, discrete steps of the query execution. I corrected my assessment there (https://github.com/nuwave/lighthouse/issues/1116#issuecomment-573456561) , i don't think that particular issue is caused by execution order.

On a side note, i started https://github.com/nuwave/lighthouse/pull/1139 as an attempt to describe the steps that happen during an incoming GraphQL request and offer insight into the execution order of directives.

There are still cases like https://github.com/nuwave/lighthouse/issues/894 which this change would solve.

**Comment by lorado** [comment]
Ok. This solution seems to be most acceptable. Would you like to implement PR for ordering middlewares?

Describing a lifecycle will definitely help in some cases. Go for it 👍

**Comment by spawnia** [comment]
I am going back and forth if this should be done through directive class names or short names (e.g. `can`).

A benefit of class names would be type safety and little ambiguity.

Using the short names would allow the ordering to work regardless of directive overwrites. I am not sure if people are actually doing that though, and if so, i think they should be capable of adding their custom directives in the ordering, too.
