### ISSUE TITLE
How do you resolve global id's in v2? 

### ISSUE THREAD

**Issue by alexwhb** [nuwave/lighthouse#115]
So I'm currently upgrading an old project from lighthouse v1 to v2 and the seemingly last thing I am getting stuck on is resolving global ID's for data types. I'm implementing Node on my type like this: 

```
type User implements Node {
    id: ID!
    email: String!
    name: String!
    gravitarUrl: String
}
```

but then when I go to query _id which is defined on the node I get this error: `Cannot query field \"_id\" on type \"User\".`

I looked at the tests and saw the @node directive, but I could not figure out how to use that. I also could not tell if that is for resolving the nodes from the node query or for resolving the global ID. I also have tried defining the _id: ID field on the User. I'm pretty stumped. Any help with this would be greatly appreciated. I can get the DB ID to resolve, but that causes uniqueness issues with Relay.

**Comment by chrissm79** [comment]
Hey @alexwhb, so you just need to add the following to your schema file:

```graphql
type User implements Node {
    _id: ID! @rename(attribute: "id") @globalId
    id: Int
    # ...
}
```

We're using 2 directives here. The first one is `rename` which will return whatever `attribute` you provide it (in this case it will use the `id` on the `User` model). The second directive `globalId` will convert the `id` to a Global ID that Relay should understand.

That's it! Let me know if you have any other questions!

**Comment by alexwhb** [comment]
@chrissm79 Thank you so much!! This worked like a dream! Seriously v2 is by far the best graphQL library I've used!

**Comment by chrissm79** [comment]
Thanks @alexwhb, I'm really happy with the way it turned out too 😄

**Comment by kikoseijo** [comment]
I just use the id, but change it on the lighthouse configuration file, it defaults to `_id`,
