### ISSUE TITLE
Registering custom Operator for @whereConditions is not well documented and probably may be done easier

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1151]
**Is your feature proposal related to a problem? Please describe.**

I was trying out `@whereConditions` also before 4.8 release, and it was actually pretty easy to extend Operator enum. As I use PostgreSQL, I need ILIKE operator for my conditions. 

Currently to extend the list of allowed operators I had to create a class and modify generated enum. I solved it like this:

```php
class PSQLOperator extends SQLOperator
{
    public function enumDefinition(): string
    {
        $originalDefinition = parent::enumDefinition();
        $additionOperators = '
    "Simple pattern matching (`ILIKE`)"
    ILIKE @enum(value: "ILIKE")
';
        $pos = strrpos($originalDefinition, '}');
        return substr_replace($originalDefinition, $additionOperators, $pos, 0);
    }
}
```

And then I bound my implementation in a service provider, that comes after `WhereConditionsServiceProvider` like this:

```php
$this->app->bind(Operator::class, PSQLOperator::class);
```

I am kinda new to Laravel, and this was my first time I came to binding in laravel. And as I didn't knew the concept, it took me some time to achieve the expected result.

**Possible solutions I'd like**

Either let us improve the [documentations custom-operator section](https://lighthouse-php.com/master/eloquent/complex-where-conditions.html#custom-operator) (I could create a PR).

OR maybe let's implement the way, where extending enum with new operator (like in my case) can be made easier? Like use a string from config, that will be injected into `SQLOperator::enumDefinition()`

OR maybe let's include ILIKE by default into enum definition?

**Comment by chescos** [comment]
I wouldn't include the `ILIKE` operator by default as it's specific to PostgreSQL and not part of the SQL spec.

But I agree that adding custom SQL operators could be made easier and better documented. We could define the default operators as an array, like so:

```php
$operators = [
    [
        'description' => 'Simple pattern matching (`LIKE`)',
        'operator' => 'LIKE',
        'value' => 'LIKE',
    ],
    ...
];
```

And then we implement a method that converts the array into the enum definition. Then we could also offer a public method that merges an array of custom operators with the default operators before converting them into the enum.

**Comment by spawnia** [comment]
@chescos The issue with that is that simply defining plain operator values is not enough, the way the query builder is called depends upon their arity, so that would have to be another field in the configuration array. I don't love array based configuration for type safety, we could use a class like this instead:

```php
<?php

namespace Nuwave\Lighthouse\WhereConditions;

class OperatorValue
{
    /** @var string */
    public $description;

    /** @var string */
    public $key;

    /** @var string */
    public $value;

    /** @var int */
    public $arity = 1;
}
```

A concern that i have is that those approaches are generally pretty fragile, as they depend heavily upon the implementation details of the `SQLOperator`. The interface `\Nuwave\Lighthouse\WhereConditions\Operator` is what users should extend, as it decouples things.

How about we just add specialized operators such as `PostgreSQLOperator` or `MySQLOperator`?

**Comment by spawnia** [comment]
We should absolutely improve the docs though, some example code or links to using service providers could help.

**Comment by lorado** [comment]
> How about we just add specialized operators such as `PostgreSQLOperator` or `MySQLOperator` as part of Lighthouse core?
 
That would be pretty awesome. But I am not really good at postgres, first time using it, so I couldn't implement such `PostgreSQLOperator` with full coverage of possible functionality. Dunno how good you guys are at postgres.

Anyway I'm gonna try to make a better customization description in the docs

**Comment by spawnia** [comment]
The docs update covers this well enough.
