### ISSUE TITLE
Allow cleaner names for automatically generated input objects

### ISSUE THREAD

**Issue by chescos** [nuwave/lighthouse#1159]
**What problem does this feature proposal attempt to solve?**

The default naming convention that is used to automatically generate input objects by the `@orderBy` directive and `@whereConditions` directive often results in redundant names. Here's a common way to define your schema:

```graphql
type Query {
    users(
        where: _ @whereConditions(columns: ["id", "name"])
        orderBy: _ @orderBy(columns: ["id", "name"])
    ): [User!]! @paginate
}
```

This schema automatically generates a `UsersOrderByOrderByClause` input and a `UsersWhereWhereConditions` input.

**Which possible solutions should be considered?**

I could imagine two possible solutions:

1. Recommend a default naming convention for the query arguments (e.g `orderBy` and `where`) and if the arguments match that naming convention, remove the redundant suffix so that the input names result in `UsersOrderByClause` and `UsersWhereConditions`
2. Add an optional argument to the directive which allows the user to specify a custom name for the input that will be generated

Both solutions could also be combined.

**Comment by chescos** [comment]
Regarding the second proposed solution - I just noticed that there might be a second use-case for the specification of a custom input name.

The input objects are generated through the [setTypeDefinition](https://github.com/nuwave/lighthouse/blob/master/src/Schema/AST/DocumentAST.php#L139) method on the `\Nuwave\Lighthouse\Schema\AST\DocumentAST` class. This method overwrites existing definitions with the same name. In certain scenarios, this can be a problem with the current naming convention of the discussed input objects.

Let's take this schema definition as an example:

```graphql
type Query {
    users(
        # This orderBy directive generates a duplicate input named `UsersOrderByOrderByClause`
        orderBy: _ @orderBy(columns: ["id", "name"])
    ): [User!]! @all
    
    roles(
        orderBy: _ @orderBy(columns: ["id", "name"])
    ): [Role!]! @all
}

type User {
    id: ID!
    name: String!
}

type Role {
    id: ID!
    name: String!
    # This orderBy directive generates a duplicate input named `UsersOrderByOrderByClause`
    users(orderBy: _ @orderBy(columns: "id")): [User!]! @hasMany
}
```

As described in the comments, there are two `@orderBy` directives which will generate an input with the same name and one will overwrite the other. That means you can't specify different allowed columns, even though it's probably a rare case that you'd want to specify different columns for those 2 directives. Specifying a custom input name would allow you to do that though.

There's another case where currently the opposite happens - 2 input types are generated but you might only need 1.

Here's an example schema:

```graphql
type Query {
    users(
        # This whereConditions directive generates an input named `UsersWhereWhereConditions`
        where: _ @whereConditions(columns: ["id", "name"])
    ): [User!]! @all
    
    roles(
        # This whereHasConditions directive generates an input named `RolesHasUsersWhereConditions`
        hasUsers: _ @whereHasConditions(columns: ["id", "name"])
    ): [Role!]! @all
}
```

Each directive generates its own separate input, even though you do only need a shared one. Specifying a custom input name could therefore allow you to share inputs among different fields.

**Comment by spawnia** [comment]
I would like to hold back on configuration options where it is not functionally necessary, to keep things simple.

The case you describe where the name of the generated input collides is problematic though. We can easily solve that by prefixing the type name. Since this is a breaking change, we can do it in v5.
