### ISSUE TITLE
[Feat] Schema validation constraints

### ISSUE THREAD

**Issue by morpheus7CS** [nuwave/lighthouse#117]
Hey,

just noticed this tweet by Sashko Stubailo, about using schema validation constraints. It seems that with your extensible directive system, it could be something that could be implemented in future versions of Lighthouse 2.x:

Link to tweet: https://twitter.com/stubailo/status/996825793660571648?s=21

Great work by everyone on this so far, amazing to watch from the sidelines.

**Comment by alexwhb** [comment]
@morpheus7CS I think this is already a part of light house if I understand what you are saying with the `@validate()` directive. see issue #106 for an example.

**Comment by morpheus7CS** [comment]
Amazing, totally missed that!
