### ISSUE TITLE
Add option to pass headers to multipartGraphQL method.

### ISSUE THREAD

**Issue by miczed** [nuwave/lighthouse#1173]
**What problem does this feature proposal attempt to solve?**

When testing a file upload using the method described in the docs under [Simulating File Uploads](https://lighthouse-php.com/master/testing/phpunit.html#simulating-file-uploads) I don't see an option to pass any headers to the `multipartGraphQL` method of the `MakesGraphQLRequests` class. In my use case the file upload should only be possible when an `Authorization` header is present. Since I think this is a pretty common use case it would be helpful to pass additional headers to the method.

**Which possible solutions should be considered?**
I ended up adding an optional `array $headers` parameter to the `multipartGraphQL` method that is then combined with the `Content-Type` header passed to the `call` method using `array_merge`.

```php
protected function multipartGraphQL(array $parameters, array $files, array $headers = []): TestResponse
    {
        return $this->call(
            'POST',
            $this->graphQLEndpointUrl(),
            $parameters,
            [],
            $files,
            $this->transformHeadersToServerVars(array_merge([
                'Content-Type' => 'multipart/form-data',
            ],$headers))
        );
    }
```

I think it's a pretty straightforward solution, however I might also have missed something since I'm pretty new to lighthouse. Is there another option to pass the headers that I didn't consider? 

I'm happy to create a pull request and update the docs accordingly. 😄

**Comment by spawnia** [comment]
The change you proposed seems reasonable and straightforward.
