### ISSUE TITLE
How to use full query cache with model directive and other relations?

### ISSUE THREAD

**Issue by academici** [nuwave/lighthouse#1175]
```
type Query {
  carBrand(id: ID @eq): CarBrand @find(model: "App\\Models\\CarBrand") @cache(maxAge: 600)
}

type CarBrand {
    id: ID! @cacheKey
    name: String!
    slug: String!
    logo: Media!
    cars: [Car] @hasMany
}

type Car {
    id: ID! @cacheKey
    name: String!
    slug: String!
    photo: Media!
    price: Int! @rename(attribute: "final_price")
}
```

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
