### ISSUE TITLE
Ability to mutate currently authenticated user?

### ISSUE THREAD

**Issue by subotkevic** [nuwave/lighthouse#1178]
I'm trying to achieve something similar to this:
`updateProfile(input: UpdateProfileInput! @spread): User @updateProfileValidation @auth @update`

Without providing the user ID, as the mutation should work for currently authenticated user.

But it is impossible to use more than one directive of type `Nuwave\\Lighthouse\\Support\\Contracts\\FieldResolver`.

Any ideas?

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
