### ISSUE TITLE
Custom Client Directive Example?

### ISSUE THREAD

**Issue by ryanscherler** [nuwave/lighthouse#1179]
Is there documentation that outlines how to create a custom client directive. All I can find is the brief information such a directive here: https://lighthouse-php.com/4.8/digging-deeper/client-directives.html#client-directives - but cannot understand how to implement a custom one. The idea is to create a client side directive to transform an asset. E.g.

```graphql
{
  me {
    name
    avatar @transform(size: 200)
  }
}
```

I tried to create a directive called `TransformDirective` and resolve it, but get the error `"Unknown directive \"transform\".",`

**Comment by spawnia** [comment]
I tried to write a little guide on how to deal with client directives correctly, and found that it is actually deceptively hard. We are doing it wrong currently, so i am reworking that and plan to offer a simplified solution as i get there.

**Comment by ryanscherler** [comment]
Sounds good. After posting this issue, I did realize how to make it work, first defining the directive in the schema, then I had to dig into where in the $resolverInfo these params were and I think I can make it work. I'm excited to see how you re-work this into a more simplified solution. Thanks for all your hard work - Lighthouse is amazing!
