### ISSUE TITLE
#import not working when schema is called from BuildSchemaString::class

### ISSUE THREAD

**Issue by Owchzzz** [nuwave/lighthouse#1181]
Whilst trying to write a package that uses lighthouse, I found a bug (or possibly missing feature) in the package.

I have written my own package and basically it is calling a .graphql schema file from inside of this package using this event listener:

```php
        app('events')->listen(
            BuildSchemaString::class,
            function(): string {
                
                return file_get_contents(__DIR__.'/GraphQL/Schema/schema.graphql');

            }
        );
```
this is what my graphql file looks like:
```graphql
extend type Query {
    me: User @auth
    asdf: User @auth
}

#import users.graphql
#import payments.graphql
#import roles.graphql
```
 However users.graphql, payments.graphql and roles.graphql does not get "imported into the schema"

I solved this problem by scanning the entire directory and inserting each file, however, I would love it if we can have the functionality to import files like this using the #import  statement and not have to come up with hacky solutions like recursivedirectory looping

I expect that lighthouse be able to read these files appropriately. and import the graphql files

**Steps to reproduce**

1. create a composer package that requires lighthouse
2. Create a service provider (laravel) and require it
3. Import graphql using the build schema event
4. try to use `#import` statement
5. print out schema string = no schema imported

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Environment**

Lighthouse Version: 4.8
Laravel Version: 6.2

**Comment by spawnia** [comment]
Imports only work when the location of a source file is known, as they are relative paths. There is no way for Lighthouse to know from where you got the additional schema string.

That said, you can use the schema stitcher to gather a file and resolve imports before adding it through the event. I documented that here: https://github.com/nuwave/lighthouse/pull/1183

**Comment by Owchzzz** [comment]
thanks @spawnia ! :) much appreciated
