### ISSUE TITLE
 `$context->user()` is null

### ISSUE THREAD

**Issue by omarusman** [nuwave/lighthouse#1191]
**Is this a normal behavior?**

I'm trying to do this `Mutation` query:
<img width="480" alt="step1" src="https://user-images.githubusercontent.com/2807969/74530080-2be56800-4f64-11ea-98a2-73935a172058.png">

When `@can` is executed, it seems it can't find (null) the current user in `$context->user()`, thus, it throws invalid permission (policy).

So I tried debugging, the `CanDirective`, 

<img width="1063" alt="step2" src="https://user-images.githubusercontent.com/2807969/74530348-c47be800-4f64-11ea-94d6-6a5325d3053d.png">

The result says 
```
$context->user() => null
```
but 
```
$context->request()->user() => **the current user**
```
<img width="215" alt="step 3" src="https://user-images.githubusercontent.com/2807969/74530421-ed9c7880-4f64-11ea-9c66-d0a2690a10e5.png">

**Comment by spawnia** [comment]
This can now be solved by using the new `AttemptAuthenticate` middleware, see https://github.com/nuwave/lighthouse/pull/1197

**Comment by mrcrg** [comment]
@spawnia if I have multiple guards (OAuth2 and BasicAuth) `AttemptAuthenticate` doesn't work because it only uses `config("lighthouse.guard")` value.

It is possible to remove `AuthServiceProvider::guard()` from `$context->user()` ?

**Comment by spawnia** [comment]
@mrcrg feel free to experiment and open a pull request.
