### ISSUE TITLE
Unit testing with MakesGraphQLRequests in laravel package project fails if subscriptions are used

### ISSUE THREAD

**Issue by sinusforce** [nuwave/lighthouse#1195]
**Describe the bug**

When trying to unit test graphQL mutations which use subscriptions within a laravel package, I get the error ```Add the SubscriptionServiceProvider to your config/app.php to enable subscriptions.``` for any ```postGraphQL``` requests. As I make use of the ```MakesGraphQLRequests``` trait I thought this should work.

**Expected behavior/Solution**

I would expect the testing request to work as a 'regular real world' request where the ```SubscriptionServiceProvider``` is found as I added it to the ```app.providers``` array on boot up of the laravel package (within the package service provider) and using the endpoint works e.g. testing with the playground.

I tracked the error down to the ```Illuminate\Foundation\Testing\Concerns\MakesHttpRequest``` class where the ```call```method creates a new kernel for doing the request. It seems as this new kernel misses the entry of ```SubscriptionServiceProvider``` but this is hard to debug. 

I am really stuck here as I don't get it to work and it also is quiet hard to reproduce I guess, as one would need to have a laravel package with a schema file including subscriptions and having at least one test requesting this graphQL endpoint.

**Environment**

Lighthouse Version: 4.7.2
Laravel Version: ^6.0
Testing: Orchestra Testbench ^4.0 / PHPUnit ^8.3

**Comment by sinusforce** [comment]
Upgraded to Lighthouse Version 4.9.0 just to be sure: same problem

**Comment by spawnia** [comment]
The test trait `MakesGraphQLRequests` does not do anything to set up your environment. It only provides helpers for making GraphQL requests, using the standard test helpers that Laravel provides.

I think that the usage of `orchestra/testbench` is causing that issue, it is not meant to test Laravel applications - it is used for package development. Thus, it does not include your application config but requires you to set up the config completely in your test case, using methods such as `getPackageProviders()`.
