### ISSUE TITLE
Laravel Getters issue

### ISSUE THREAD

**Issue by mits87** [nuwave/lighthouse#120]
Hi,

I have two models Account and User. 
The relation is: account has many users

My type definitions:

```graphql
type Account {
  id: ID!
  limits: Array
}

type User {
  id: ID!
  account: Account @belongsTo
}

type Query {
  me: User @auth
}
```

and I make a query:

```graphql
query User {
  me {
    email
    account {
      id
      limits
    }
  }
}
```

After execute I got an error:

> Argument 1 passed to GraphQL\\Executor\\Executor::completeValueCatchingError() must be an instance of GraphQL\\Type\\Definition\\Type, null given, called in /var/www/app/vendor/webonyx/graphql-php/src/Executor/Executor.php on line 721

because the limits is a getter in Account model. 
Do you have a solution for use getters?

**Comment by alexwhb** [comment]
@mits87 did you define that relationship resolver on your eloquent model?

**Comment by 4levels** [comment]
Hi @mits87,

I'm not sure how to help here, but there seems something wrong with the getter return data from your previous comment as I've never seen array keys being arrays themselves, are you sure your previous code sample is correct?
Or should it be written as below?
```php
[
    [ 'key1' => 'v1' ],
    [ 'key2' => 'v2' ]
]
```

**Comment by chrissm79** [comment]
@mits87 Are we able to close this issue or are you still experiencing some problems? Let me know if you have any questions!!

**Comment by mits87** [comment]
yes, you can close the issue
