### ISSUE TITLE
Extending input types

### ISSUE THREAD

**Issue by faiverson** [nuwave/lighthouse#1202]
Following this requirement from Apollo:
https://github.com/apollographql/graphql-tools/issues/641

At this moment, we can extend a type (including Query/Mutations). It'd be great to add the same functionality for input types.
```
type Query {
  getFoo: Foo
}
type Foo {
  foo: String
}
extend type Foo {
  bar: String
}

type Mutation {
  updateFoo(input: FooInput): Foo
}
input FooInput {
  foo: String
}
extend input FooInput {
  bar: String
}
```
Bonus track, add exteding for everything interface, enums, etc. When we use schema stitching it is a great feature to have.

**Comment by faiverson** [comment]
I figured out that this is already implement in the webonyx/graphql-php library, so I've added the changes to be able to use that in lighthouse :)

**Comment by spawnia** [comment]
Thanks @faiverson, great contribution!
