### ISSUE TITLE
@delete directive does not return error when delete has failed through observer.

### ISSUE THREAD

**Issue by ashwin0003** [nuwave/lighthouse#1204]
**Describe the bug**

@delete directive does not return error when delete has failed through observer.

**Expected behavior/Solution**

My mutation in graphql-schema

```graphql
extend Type Mutation {
  deleteUser(id: Int! @eq): User @delete
}
```
Note: Im using `Int! @eq` instead of `ID!` as my database has id as a incrementing integer.

My observer

```php
    public function deleting(User $user)
    {
        return false;
        ...
        try {
            ...
        } catch (Exception $e) {
            ...
            return false;
        }
    }
```
Note: The first `return false` in the `deleting` method is there for testing purposes.

Expected behaviour.
1. When observer's deleting method(event-handler) returns false, delete actions fails.
2. GraphQL should consider that as a fail and return a error message.

First step is happening as in my test-case delete is not happening as expected.
But GraphQL is not considering that be a failure and is behaving as if it was a successful deletion.

**Steps to reproduce**

1.
2.
3.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Environment**

Lighthouse Version: v4.8.1
Laravel Version: v6.9.0

**Comment by spawnia** [comment]
I think that the case where a model is not being deleted is not necessarily an error. If an exception is thrown during a callback, Lighthouse will abort execution - but just returning `false` might have other reasons.

How about we just return the result of calling `delete()` as the result of the mutation?

```graphql
type Mutation {
	deleteUser(id: ID!): Boolean @delete(model: "User")
}
```

**Comment by olivernybroe** [comment]
You could also add the `exist` field on your `User` class.
Then after running the delete query, you can check the returned user if `exists` is `false` client side, to make sure it was actually deleted.

**Comment by spawnia** [comment]
@olivernybroe throwing is a perfectly fine way to bubble up errors and will produce a proper error in the response. I don't want to support the old PHP pattern of returning `false` on error.

**Comment by ashwin0003** [comment]
@spawnia I have started throwing exceptions instead of returning false in my observers, which responds with the thrown exception's message as `debugMessage` with category `internal`. This is allowing me to handle the failed deletion using the response. But I don't feel like its the way it should be done.

The ideas of returning `Boolean` and adding new `exists` field seem like bad ideas.
I like the idea of throwing a error when CRUD method on models return false.

And I also apologize for the delayed response and my incomplete replies due to lack of knowledge regarding internal specs.

**Comment by spawnia** [comment]
The solution for a single deletion is simple, but i struggle with what we should do when multiple models are deleted at once. We might buffer the exceptions and throw a list of errors for all ID's where deletion failed.
