### ISSUE TITLE
Add support to suppress errors and exceptions

### ISSUE THREAD

**Issue by Nohac** [nuwave/lighthouse#1209]
**What problem does this feature proposal attempt to solve?**

Since I'm using the `permissions` middleware on individual fields using https://github.com/spatie/laravel-permission, I see that for each field that is not accessible, lighthouse adds a new error which quickly piles up. For my use case, it's enough that the field returns null, so I would like to just suppress/ignore the exceptions being thrown by `laravel-permissions`.

Following https://lighthouse-php.com/4.9/digging-deeper/error-handling.html, I've implemented my own `ErrorHandler` and catch `UnauthorizedException`, from here, there is no way to just "ignore" the error, I'm forced to give the `$next` function a valid error object. It would be nice if I could just give it `null` or something.

**Comment by enzonotario** [comment]
I think you could use the [`all` Error Policy](https://www.apollographql.com/docs/react/data/error-handling/#error-policies) from your client side.

**Comment by Nohac** [comment]
@enzonotario The point is that I don't need the errors, they just add unnecessary overhead. If the query returns a thousand fields that the user does not have access to, I also get the error repeated a thousand times in the response..

**Comment by spawnia** [comment]
Returning `null` to ignore an error seems reasonable.

@Nohac can you try and add a PR for that? The responsible code can be found in https://github.com/nuwave/lighthouse/blob/master/src/Execution/ErrorHandler.php and https://github.com/nuwave/lighthouse/blob/master/src/GraphQL.php#L185-L203

**Comment by lorado** [comment]
I like the idea, and I am ready to help with PR.

**Comment by spawnia** [comment]
This requires breaking changes to the `ErrorHandler` interface, we can tackle that in the upcoming v5
