### ISSUE TITLE
Appendable items querying

### ISSUE THREAD

**Issue by Christophvh** [nuwave/lighthouse#1211]
Hi,

In Laravel it is possible to add items to the Array/Json output with Appends. 
https://laravel.com/docs/6.x/eloquent-serialization#appending-values-to-json

Example code: 

```
Class Phase  extends Model {

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['is_current'];

    public function getIsCurrentAttribute()
    {
        $startDate = $this->attributes['start_date'];
        $endDate = $this->attributes['end_date'];

        return  now()->isBetween($startDate, $endDate);
    }

}

```

When we do this we can already fetch these values in the schema:

```
type Phase {
    isCurrent: Boolean! @rename(attribute: "is_current")
}

```

Works very nice!

But there is currently no simple way tho check for this value in a graphQL query, because all the current directives will do a check for a database column.

So I currently have to resort to a custom method which simply does `return $this->is_current`

**Comment by spawnia** [comment]
I am not i understand the issue fully.

> But there is currently no simple way tho check for this value in a graphQL query, because all the current directives will do a check for a database column.

Can you give an example for a query that would not work?

**Comment by Christophvh** [comment]
> I am not i understand the issue fully.
> 
> > But there is currently no simple way tho check for this value in a graphQL query, because all the current directives will do a check for a database column.
> 
> Can you give an example for a query that would not work?

Building further on the example in the original post.
```
type Query {
    currentPhase(is_current: Boolean! @where(key: "is_current")): Phase! @first
}
```

**Comment by spawnia** [comment]
You can use `@scope`.
