### ISSUE TITLE
Support Laravel 7

### ISSUE THREAD

**Issue by tlaverdure** [nuwave/lighthouse#1218]
**What problem does this feature proposal attempt to solve?**
Can't install with Laravel 7.

**Which possible solutions should be considered?**
Release a version that supports Laravel 7

**Comment by lorado** [comment]
Thank you for you issue report.
But come on, Laravel 7 was just released today. There seems to be some big changes, so please... be patient...

**Comment by tlaverdure** [comment]
I'm patient. Just opening and issue and subscribing for updates...

**Comment by yoosuf** [comment]
> Thank you for your issue report.
> But come on, Laravel 7 was just released today. There seems to be some big changes, so please... be patient...

Better to be alighted with the major versions

**Comment by spawnia** [comment]
From a package development perspective, there was quite a bit of severe breakage. The jump to Symfony 5 components is probably the biggest underpinning change.

With a few tweaks (hacks?) i just got it running and released. Everything but the support for `bensampo/laravel-enum` works.

**Comment by lorado** [comment]
@spawnia why `bensampo/laravel-enum` don't work? Should we wait for their new release? I use them, and we probably have to add a notice to currently documentation, that `bensampo/laravel-enum` is not supported with current version of lighthouse?

**Comment by SuddenlyRust** [comment]
The new version 1.33 of `bensampo/laravel-enum` is now supporting Laravel 7. See [pull request 124](https://github.com/BenSampo/laravel-enum/pull/124)

**Comment by spawnia** [comment]
@lorado They were not compatible with Laravel 7 yet. Since it could not even be installed, there is nothing that Lighthouse can do.
