### ISSUE TITLE
Error in Nuwave\Lighthouse\Support\AppVersion causing the entire Lumen app to crash

### ISSUE THREAD

**Issue by julesmons** [nuwave/lighthouse#1223]
**Describe the bug**

On Lumen, `Nuwave\Lighthouse\Support\AppVersion::below(5.6);` always returns false because `self::versionNumber();` returns 0. This is because the `Str::after` doesn't return the correct value.

`self::version();` returns 
> Lumen (6.3.3) (Laravel Components ^6.0)

But the functionality inside `self::versionNumber();` `(float) Str::after('(', self::version())` returns "0" because the method is used wrong.

**Expected behavior/Solution**

`Nuwave\Lighthouse\Support\AppVersion::versionNumber();` should return 6.3 because the version is "Lumen (6.3.3) (Laravel Components ^6.0)".

**The issue could be resolved by swapping the arguments.
The laravel docs specify that the actual string has to be passed as the first argument, and the search as the second argument.
[Laravel 5.8 docs](https://laravel.com/docs/5.8/helpers#method-str-after)
[Laravel 6.x docs](https://laravel.com/docs/6.x/helpers#method-str-after)**

The code should be: 
`return (float) Str::after(self::version(), '(');`

**Steps to reproduce**

1. Create a lumen project
2. Add nuwave/ligthouse version "^4.10"
3. Serve the app and visit it in the browser. You'll be presented with an exception page. The error is copy-pasted in the spoiler below. I've traced it back to this AppVersion class. I've implemented my solution (the flipping of the arguments) and the app seems to work again.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```
[2020-03-05 21:12:49] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Routing\Router::match() in **APP DIRECTORY**\vendor\nuwave\lighthouse\src\Support\Http\routes.php:31
Stack trace:
#0 **APP DIRECTORY**\vendor\nuwave\lighthouse\src\LighthouseServiceProvider.php(94): require()
#1 **APP DIRECTORY**\vendor\nuwave\lighthouse\src\LighthouseServiceProvider.php(73): Nuwave\Lighthouse\LighthouseServiceProvider->loadRoutesFrom('C:\\Users\\Jules ...')
#2 [internal function]: Nuwave\Lighthouse\LighthouseServiceProvider->boot(Object(Illuminate\Validation\Factory), Object(Illuminate\Config\Repository))
#3 **APP DIRECTORY**\vendor\illuminate\container\BoundMethod.php(32): call_user_func_array(Array, Array)
#4 **APP DIRECTORY**\vendor\illuminate\container\Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 **APP DIRECTORY**\vendor\illuminate\container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#6 **APP DIRECTORY**\vendor\illuminate\container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#7 **APP DIRECTORY**\vendor\illuminate\container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#8 **APP DIRECTORY**\vendor\laravel\lumen-framework\src\Application.php(250): Illuminate\Container\Container->call(Array)
#9 **APP DIRECTORY**\vendor\laravel\lumen-framework\src\Application.php(235): Laravel\Lumen\Application->bootProvider(Object(Nuwave\Lighthouse\LighthouseServiceProvider))
#10 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Nuwave\Lighthouse\LighthouseServiceProvider), 'Nuwave\\Lighthou...')
#11 **APP DIRECTORY**\vendor\laravel\lumen-framework\src\Application.php(236): array_walk(Array, Object(Closure))
#12 **APP DIRECTORY**\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(159): Laravel\Lumen\Application->boot()
#13 **APP DIRECTORY**\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#14 **APP DIRECTORY**\public\index.php(28): Laravel\Lumen\Application->run()
#15 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Lumen\\Routing\\Router::match() at **APP DIRECTORY**\\vendor\
uwave\\lighthouse\\src\\Support\\Http\
outes.php:31)
[stacktrace]
#0 **APP DIRECTORY**\\vendor\
uwave\\lighthouse\\src\\LighthouseServiceProvider.php(94): require()
#1 **APP DIRECTORY**\\vendor\
uwave\\lighthouse\\src\\LighthouseServiceProvider.php(73): Nuwave\\Lighthouse\\LighthouseServiceProvider->loadRoutesFrom('C:\\\\Users\\\\Jules ...')
#2 [internal function]: Nuwave\\Lighthouse\\LighthouseServiceProvider->boot(Object(Illuminate\\Validation\\Factory), Object(Illuminate\\Config\\Repository))
#3 **APP DIRECTORY**\\vendor\\illuminate\\container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#4 **APP DIRECTORY**\\vendor\\illuminate\\container\\Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 **APP DIRECTORY**\\vendor\\illuminate\\container\\BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#6 **APP DIRECTORY**\\vendor\\illuminate\\container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#7 **APP DIRECTORY**\\vendor\\illuminate\\container\\Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#8 **APP DIRECTORY**\\vendor\\laravel\\lumen-framework\\src\\Application.php(250): Illuminate\\Container\\Container->call(Array)
#9 **APP DIRECTORY**\\vendor\\laravel\\lumen-framework\\src\\Application.php(235): Laravel\\Lumen\\Application->bootProvider(Object(Nuwave\\Lighthouse\\LighthouseServiceProvider))
#10 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}(Object(Nuwave\\Lighthouse\\LighthouseServiceProvider), 'Nuwave\\\\Lighthou...')
#11 **APP DIRECTORY**\\vendor\\laravel\\lumen-framework\\src\\Application.php(236): array_walk(Array, Object(Closure))
#12 **APP DIRECTORY**\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(159): Laravel\\Lumen\\Application->boot()
#13 **APP DIRECTORY**\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)
#14 **APP DIRECTORY**\\public\\index.php(28): Laravel\\Lumen\\Application->run()
#15 {main}
"} 

</details></br>

**Environment**

Lighthouse Version: ^4.10
Lumen Version: "Lumen (6.3.3) (Laravel Components ^6.0)"

**Comment by spawnia** [comment]
A PR would be great.
