### ISSUE TITLE
on /graphql after installing lighthouse I am getting syntax error

### ISSUE THREAD

**Issue by amarnegi92** [nuwave/lighthouse#1226]
syntax error: Unexpected <EOF>","extensions":{"category":"graphql"}
I am using firefox browser, I think the same issue is resolved in 
https://github.com/leocavalcante/siler/issues/181

**Comment by enzonotario** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
