### ISSUE TITLE
Another route has already been assigned name

### ISSUE THREAD

**Issue by MrRobu** [nuwave/lighthouse#1230]
**Describe the bug**

When I run `php artisan optimize` I got an error saying there are duplicate route name _lighthouse.subscriptions.auth_

**Expected behavior/Solution**

Routes to be cached successfully!

**Steps to reproduce**

1. set LIGHTHOUSE_BROADCASTER=pusher
2. run `php artisan optimize`
3. The error is from `src/Subscriptions/SubscriptionRouter.php`. These two routes has same name: 
```
       $router->post('graphql/subscriptions/auth', [
            'as' => 'lighthouse.subscriptions.auth',
            'uses' => SubscriptionController::class.'@authorize',
        ]);

        $router->post('graphql/subscriptions/webhook', [
            'as' => 'lighthouse.subscriptions.auth',
            'uses' => SubscriptionController::class.'@webhook',
        ]);
```
**Output/Logs**

<details><summary>Click to expand</summary>

```
Unable to prepare route [graphql/subscriptions/webhook] for serialization. Another route has already been assigned name [lighthouse.subscriptions.auth]
```

</details></br>

**Environment**

Lighthouse Version: 4.10.1
Laravel Version: 7

**Comment by spawnia** [comment]
Released a fix in v4.10.2
