### ISSUE TITLE
Documentation for Custom Builders is out of date or incorrect

### ISSUE THREAD

**Issue by omacranger** [nuwave/lighthouse#1238]
**Describe the bug**

The documentation for [custom builders](https://lighthouse-php.com/4.10/api-reference/directives.html#custom-builder) says to import and use `Illuminate\Database\Query\Builder` but utilizing the example listed in that document throws an error that the system is looking for an instance of a Model.

The fallback for the `builder` arg when it is not provided is a `\Illuminate\Database\Eloquent\Builder`, seen [here](https://github.com/nuwave/lighthouse/blob/65552b4cc951b24d7f57e1c4f2191df0873fd2a9/src/Schema/Directives/PaginateDirective.php#L114), instantiated by `$this->getModelClass()::query()`. I assume the documentation should be updated to reflect the correct return type for that class instead, and perhaps update the example with `Posts::query()`?

**Expected behavior/Solution**

The documentation should provide an up to date example.

**Steps to reproduce**

1. Create custom builder using instructions
2. Create a GraphQL Query that queries that builder and requests a relationship, ex, `Posts -> Author -> name`

**Output/Logs**

<details><summary>Click to expand</summary>

```
Argument 1 passed to Nuwave\Lighthouse\Schema\Directives\RelationDirective::Nuwave\Lighthouse\Schema\Directives\{closure}() must be an instance of Illuminate\Database\Eloquent\Model, instance of stdClass given, called in /mnt/c/www/officedot/backend/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php on line 174
```

</details></br>

**Environment**

Lighthouse Version: 4.10.1
Laravel Version: 6.x

**Comment by spawnia** [comment]
Can i see your schema definition? From what your describing, it seems like you are using `@paginate` on a non-root field.

**Comment by omacranger** [comment]
Sorry for the delay, I was able to replicate it with a fresh install. Could very well be doing something dumb here, but this is basically the same issue I ran into on a bigger project. 

Schema: 

```graphql
type User {
    id: ID!
    name: String!
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
}

type Query {
    postsWithoutContent(input: PostFilter @spread): [Post!]!
        @paginate(builder:"App\\Post@postsWithoutContent", defaultCount: 20)
}

type Post {
    title: String!
    content: String
    author_id: ID!
    author: User @belongsTo
}

input PostFilter {
    author_id: ID @where
}
```

Custom builder: 
```php
class Post extends Model
{
    function postsWithoutContent($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo): Builder
    {
        return DB::table('posts')
                 ->whereNull('content');
    }

    function author(): BelongsTo
    {
        return $this->belongsTo(User::class, 'author_id');
    }
}
```

Example query:
```graphql
query {
    postsWithoutContent {
        data {
            title
            author_id
            # This is important. Without accessing a relation, it works fine.
            author {
                name
            }
        }
    }
}
```

<details>
<summary>Error</summary>
Argument 1 passed to Nuwave\Lighthouse\Schema\Directives\RelationDirective::Nuwave\Lighthouse\Schema\Directives\{closure}() must be an instance of Illuminate\Database\Eloquent\Model, instance of stdClass given, called in /mnt/c/www/lighthouse-bug-test/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php on line 174
</details>

Changing the custom builder to the following lets it work as expected: 
```php
use Illuminate\Database\Eloquent\Builder;
...
function postsWithoutContent($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo): Builder
    {
        return Post::query()
                 ->whereNull('content');
    }
```

Provided you don't see something really obvious right away I can turn this into a small test repo to reproduce.

**Comment by spawnia** [comment]
Thanks for clarifying. The issue is quite clear now: when accesssing a relation, Lighthouse expects a model builder. That's a hard requirement, we can not "fix" that part.

What we can and should do is make the docs more clear. The example for custom builders should use something like `Post::query()`, as you do. We might add an extra paragraph after that with an example of a non-Eloquent builder, clarifying the limitations. Basically, when using Eloquent features you need an Eloquent query builder.

Can you try and add a PR to the docs?

**Comment by stevebauman** [comment]
If anyone else runs into this (I was scratching my head for hours), make your sure you return an instance of `Illuminate\Database\Eloquent\Builder`, **not** `Illuminate\Database\Query\Builder` from the builder class you specify in the `@paginate` directive:

```graphql
extend type Query @guard {
    posts: [Post!]! @paginate(builder: "App\\Queries\\PostQuery")
}
```

```diff
public function __invoke($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
{
-    return Post::query()->getQuery(); // Illuminate\Database\Query\Builder
+    return Post::query(); // Illuminate\Database\Eloquent\Builder
}
```
