### ISSUE TITLE
Is there an easy way to make a relay friendly create Mutation? 

### ISSUE THREAD

**Issue by alexwhb** [nuwave/lighthouse#124]
So currently I'm trying to make a create mutation that has the edge and a client mutation ID so that my mutations are easy to manage on the Relay side.. is there a somewhat easy way to do this? I am getting errors when just using the `@create()` directive, which is not too surprising. I was thinking of doing a `@field(resolver: "some resolver")` but I'm not really sure how you resolve multiple unrelated fields with data types that are not simple like a single modle. Any help with this would be greatly appreciated. 

and I currently have a `relayCreate()` custom directive in there... this currently is exactly the same as the `@create()` directive.... but I would like to maybe create a directive that automates this pattern, since I will be using it every time I make a new record. 

here's what this looks like in my schema currently: 

```graphql

type AddLibraryPayload {
    viewer: User!
    libraryEdge: UserLibraryEdge!
    clientMutationId: String!
}

#currently this has to be redefined because
#lighthouse does not recognize it from the automatic 
#@hasMany generation of this type unfortunately.
type UserLibraryEdge {
    node: Library
    cursor: String!
}

input AddLibraryInput {
    name:String
    clientMutationId:String
}

type Mutation @group(namespace: "App\\Http\\GraphQL\\Mutations") {
    addLibrary(input:AddLibraryInput): AddLibraryPayload @relayCreate(model:"App\\Models\\DB\\Library")
}

```

**Comment by kikoseijo** [comment]
Isn't UserLibraryEdge defined in User?

you payload should just be viewer: User!

then your query response you just do something like:

```graphql
 viewer{
  libraries{
   name
  }
 }
}

**Comment by alexwhb** [comment]
@kikoseijo First off thanks for the quick response. Oh really?? don't I need to send back the `clientMutationId` too? And ya UserLibraryEdge is defined in User.

**Comment by kikoseijo** [comment]
YEs, the client mutation you should need to update your mutation,
But you do that by hand if you want, by `md5(modelNAME:id)`

**Comment by alexwhb** [comment]
@kikoseijo won't that ID cause problems if I ever do an update mutation, since relay will then receive the same clientMutationId? From what I've read the point of the clientMutationId is to have a unique identifier for relay to flush it's local cache, but in this case if you where to say add a new record then update that record with the same client mutation id since `md5(modelNAME:id)` will be the same assuming your ID does not change it will probibly not update the local data store right? Or is my understanding off?

**Comment by kikoseijo** [comment]
You only need to add the id when creating a new record.
If you pulling that record after the update im not sure if relay will update from que query, but ir should.

**Comment by alexwhb** [comment]
@kikoseijo very good to know. Hey thanks for your help. I so appreciate it.

**Comment by kikoseijo** [comment]
BTW: if you responses are not right, relay will let you know, don't you worry about it.
This is the reason im starting with Relay before move to Apollo.

**Comment by alexwhb** [comment]
@kikoseijo that's very true... it complains a lot. lol Apollo is much more lax. I use Apollo on a Node stack for a side project I have, and I have to say... I think Relay is better. Vuex or Redux or what ever data store you end up with end up being a lot more manual and difficult to manage in my opinion.
