### ISSUE TITLE
@guard() + @can directive doesn't work

### ISSUE THREAD

**Issue by Christophvh** [nuwave/lighthouse#1242]
Given following code:

The below code uses the old middleware directive + can directive. This works.
```
extend type Query @middleware(checks: ["auth:api"]){
    exercise(id: Int! @eq): Exercise @can(ability: "show" find: "id") @find
}
```
New code with guard directive
```
extend type Query @guard(with: ["api"]){
    exercise(id: Int! @eq): Exercise @can(ability: "show" find: "id") @find
}
```

When using the guard directive the policy never passes. It also never even reaches the policy method. When switching to middleware it works instantly.

**Environment**

Lighthouse Version: 4.10
Laravel Version: 6.18

**Comment by spawnia** [comment]
Thanks for the report.

This is fixed in `master` through the new `AttemptAuthenticate` middleware, see https://lighthouse-php.com/master/security/authentication.html.
