### ISSUE TITLE
@method Directive with Parameter Fails when Model Function has Typehint

### ISSUE THREAD

**Issue by benxmy** [nuwave/lighthouse#1248]
**Describe the bug**
In my type object, I'm using the @method directive to call a model function. I'm passing a parameter to the function which is an integer. If the function on the model typehints, I'll get an error that the function is expecting an integer but an object was given.

Here's my Lighthouse object: 
```
type Stuff {
	id: ID!
	user: User! @belongsTo
	
	getUrlForSize(size: Int!): String @method

	created_at: DateTime
	updated_at: DateTime
}
```
The Model function:
```
public function getUrlForSize(int $size)
{
    return $this->size($size)->url();
}
```
The query: 
```
myTopMedia(first:15) {
    data{
      downloadable_type
      count
      downloadable{
          id
          name
          artwork {
            getUrlForSize(size: 50)
          }
      }
  }
}
```
If I take the typehint out of the model function, everything works.

**Expected behavior/Solution**
According to the documentation, I should be able to pass the parameter to the function with the typehinting in the model function. 

**Output/Logs**

<details><summary>Click to expand</summary>

```
{
  "errors": [
    {
      "debugMessage": "Argument 1 passed to App\\Artwork::getUrlForSize() must be of the type integer, object given",
      "message": "Internal server error",
...
```

</details></br>

**Environment**

Lighthouse Version: 4.10
Laravel Version: 5.8

**Comment by spawnia** [comment]
How about you comment your findings?
