### ISSUE TITLE
Hello, Can I translate the project's documentation into Chinese and provide it to Chinese developers for free?

### ISSUE THREAD

**Issue by PBK-B** [nuwave/lighthouse#1250]

**Comment by Owchzzz** [comment]
This is open source i dont see why that would be a problem

**Comment by PBK-B** [comment]
> This is open source i dont see why that would be a problem

Sorry, I should try to contact via email, but I could n’t find a contact method, so I used this terrible method to keep in touch with the organization. I am very sorry for the consequences of my bad behavior

**Comment by Owchzzz** [comment]
oh @PBK-B im not a contributor here i just use this a lot and i saw this comment of yours. its really no problem. have a great day :) @spawnia is the author of this plugin if you need to get in contact with him try and email him

**Comment by spawnia** [comment]
@PBK-B creating an issue is the perfect way to get in touch.

I am not sure how that would work on a technical level. The docs are currently not structured in a way that would allow adding docs easily.

**Comment by PBK-B** [comment]
> @PBK-B creating an issue is the perfect way to get in touch.
> 
> I am not sure how that would work on a technical level. The docs are currently not structured in a way that would allow adding docs easily.
> 
> Also i am a bit worried about maintaining the docs. I just ran some statistics - the docs currently have over 9000 lines of code. Keeping them up to date is quite a bit of work as is.

@spawnia My partner and I will try to translate the latest documents. We are currently translating version 4.10. We need to finish it first, and then sync the latest. Now, I can first clone the new repository located at https://github.com/haxibiao/lighthouse. This translation processing method also directly covers the original document. In the future, I will optimize compatibility with the original document. Thanks again, please allow me to use Chinese to convene more friends to join us.

lighthouse-php 中文网已经上线：http://lighthouse-php.cn
我们第一次参加翻译工作，还有很多地方做的不专业不够好，欢迎指点建议和纠正，希望志同道合的小伙伴也能加入我们一起努力！！！

**Comment by spawnia** [comment]
@PBK-B looks like you are making great progress! I am wondering why https://github.com/haxibiao/lighthouse is not created as a fork of Lighthouse, though. I recommend you recreate the repository, as having a fork makes the relationship between the projects clear and eases updates between the projects.

**Comment by PBK-B** [comment]
> @PBK-B looks like you are making great progress! I am wondering why https://github.com/haxibiao/lighthouse is not created as a fork of Lighthouse, though. I recommend you recreate the repository, as having a fork makes the relationship between the projects clear and eases updates between the projects.

Sorry, because I didn't notice this when I started the project, I will complete the adjustment as soon as you suggest

**Comment by spawnia** [comment]
I linked your translation in the projects `README.md`, people should be able to find it from there. Thank you!
