### ISSUE TITLE
Ignore validation on unset fields

### ISSUE THREAD

**Issue by mg98** [nuwave/lighthouse#1256]
**What problem does this feature proposal attempt to solve?**

Example schema:
```
type Mutation {
    updateClient(
        id: ID!
        first_name: String
        last_name: String @rules(apply: ["required"])
    ): Client @update
}
```

The following query will fail because of the violation against the "required" rule.
```
mutation {
    updateClient(id: 1, first_name: "John") { ... }
}
```

Fields that do not get passed to a mutation get ignored by Lighthouse, they are not getting updated and so the validation rules should be ignored too!

In my opinion, either I require the field in the schema with the `!` annotation and check if it's null: `last_name: String! @rules(apply: ["required])` or I let users omit the field completely.

**Which possible solutions should be considered?**

I am not sure if I'm proposing a feature or if I discovered a bug. But in my opinion, validation rules should not apply if the field does not get updated anyway.

**Comment by spawnia** [comment]
Thanks for your interest.

I think that having `required` not validate that a field is present is very unintuitive. Many users rely on that behaviour and i do not want to break them. Here is what the Laravel docs say about what this rule does:

> The field under validation must be present in the input data and not empty.

If you want to have a non-null check, you can use something like `sometimes|string` or `sometimes|required`, see https://laravel.com/docs/7.x/validation#conditionally-adding-rules

**Comment by mg98** [comment]
Hmm I see, I guess you are right about that :) Thanks for the reference to alternative rules.
