### ISSUE TITLE
how to extend lighthouse graphql server though custome laravel package

### ISSUE THREAD

**Issue by suleodu** [nuwave/lighthouse#1258]
I will like to know how I can extend my normal laravel installation with lighthouse using my custom develop package

**Comment by spawnia** [comment]
https://lighthouse-php.com/master/digging-deeper/extending-lighthouse.html

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
