### ISSUE TITLE
Opening https://lighthouse-php.com/docs/latest.html leads to 404

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1260]
**Describe the bug**

When opening https://lighthouse-php.com/docs/latest.html, the URL changes to the correct location, but the page shows a 404.

**Expected behavior/Solution**

Display the **Getting Started** section of the latest stable docs.

**Steps to reproduce**

1. Visit https://lighthouse-php.com/
2. Open **Get Started** link in a new tab

**Output/Logs**

![image](https://user-images.githubusercontent.com/12158000/77847174-607f4d00-71bb-11ea-857b-a56a2ee33ffa.png)

**Comment by spawnia** [comment]
Thanks to @yanzhen0610 for spotting this issue in https://github.com/nuwave/lighthouse-docs/issues/91

**Comment by crThiago** [comment]
In [@guard](https://lighthouse-php.com/4.12/api-reference/directives.html#guard), the link [default config](https://lighthouse-php.com/4.12/api-reference/src/lighthouse.php) also return 404

**Comment by spawnia** [comment]
> In [@guard](https://lighthouse-php.com/4.12/api-reference/directives.html#guard), the link [default config](https://lighthouse-php.com/4.12/api-reference/src/lighthouse.php) also return 404

Fixed that, thanks.

**Comment by spawnia** [comment]
We are updating VuePress from time to time, if that fixes this that would be great. Not putting more effort into this though.
