### ISSUE TITLE
schema.graphql won't visibly/usably update

### ISSUE THREAD

**Issue by Jofairden** [nuwave/lighthouse#1263]
### Description
Somehow, on a fresh install, my graphql schema seems 'stuck' on its initial version with just a User type and query for User (following the tutorials).

I've now updated my schema with 3 new types and queries (the same queries as for User in the tutorials), using # imports. For reference my graphql.schema file looks like this:

<details><summary>Click to expand</summary>

```graphql
"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-01-01 13:00:00`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"A date string with format `Y-m-d`, e.g. `2011-05-23`"
scalar Date @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Date")

type Query

#import user.graphql
#import file1.graphql
#import file2.graphql
#import file3.graphql
```
The imported files are inside the graphql folder alongside the schema.graphql file
</details></br>

When I use the command
`php artisan lighthouse:print-schema`
I can visually see the types and queries there. When I write the file they're also there. Yet when I go to my graphql-playground, they're not found or queryable. I also tried using a locally running graphiql app, and calling my endpoint would still only work for the User type.

The only related issue I can find is: https://github.com/nuwave/lighthouse/issues/925
However, the provided solution there does not work for me.
I tried clearing the cache and manually setting cache use to false, but that is not a fix.
Restarting laravel or my pc also did not fix the issue.
My APP_ENV is local anyways so it shouldn't cache by default.

In the config file I also tried pointing to the written schema file in the storage folder, but to no avail. It is still stuck with only the User type.

### In what way is Lighthouse behaving incorrectly or unexpectedly? 
Lighthouse seems stuck at my initial version of the graphql.schema file.

### Output/Logs

I do not get specific logs that indicate an error/warning

### Environment

Lighthouse Version: master (^4.11)
Laravel Version: ^7.0

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

**Comment by Jofairden** [comment]
Maybe you should consider removing a template for support questions then ;-)

**Comment by spawnia** [comment]
That template says exactly what I just responded.
