### ISSUE TITLE
[GraphQL] folder as child of Http

### ISSUE THREAD

**Issue by andrewmclagan** [nuwave/lighthouse#1265]
**What problem does this feature proposal attempt to solve?**

GraphQL is served via the HTTP protocol. It's confusing to have the `GraphQL` folder in the Laravel `app` folder rather than a child of the `Http` folder.

**Which possible solutions should be considered?**

Move the folder. There are two options...

`app/Http/GraphQL/...`

OR

`app/Http/Controllers`
`app/Http/Mutations`
`app/Http/Queries`
`app/Http/Subscriptions`
`app/Http/Unions`
`app/Http/...`

**Comment by spawnia** [comment]
You can change that through the config file.

**Comment by andrewmclagan** [comment]
Yep, already done that. Just a thought on standard implementation? Happy to have this closed although wanted to spark a discussion on the merits of the idea.

**Comment by spawnia** [comment]
GraphQL can actually be used outside of HTTP, it is explicitly transport agnostic. That is why the default in Lighthouse actually changed *away* from nesting it under HTTP.

There is actually an HTTP component to Lighthouse, but that part is really small and does not need user code. Once you cross that threshold, you are firmly in GraphQL territory, which is distinct from HTTP. You do not have to deal with HTTP semantics in your schema or your Query/Mutation classes.

You can apply the same logic to the handling of database queries/SQL within your application. While also a part in the request lifecycle of handling HTTP requests, it is distinct and thus placed separately.

**Comment by andrewmclagan** [comment]
You have just enlightened me..! Had no idea it was (transport agnostic)[https://www.prisma.io/blog/graphql-server-basics-the-network-layer-51d97d21861].

Very happy to close, end the discussion (and re-arrange my folders)
