### ISSUE TITLE
Post to endpoint returns 404

### ISSUE THREAD

**Issue by robov** [nuwave/lighthouse#1269]
I am trying to use the hasura api-explorer. This POSTS a request to my endpoint https://example.com/graphql
But my endpoint returns a 404
When I call this endpoint in postman with POST I also get a 404
When I call this endpoint in postman with GET and a query  I also get a proper response from data from my database

What am I doing wrong here.
Any Ideas ?

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
