### ISSUE TITLE
Middleware advice

### ISSUE THREAD

**Issue by t2thec** [nuwave/lighthouse#127]
Hey,

Firstly, thanks so much for lighthouse 2. Really epic package. Nice job.

I am just working through the lighthouse-example repo and can't seem to get the middleware working as expected...

```
// This bugs out with: Middleware can only be placed on a Query or Mutation [Job] in file 
type Job @group(middleware: ["auth:api"]) {
  title: String!
  user: User @belongsTo
  tasks: [Task!]! @hasMany(type: "paginator")
}

// This works with: InvalidArgumentException: Route [login] not defined which should be an easy fix
type Query  @group(middleware: ["auth:api"]) {
  me: User @auth
  jobs: [Job!]! @paginate(model: "App\\Job")
  job(id: ID!): Job @field(resolver: "App\\Http\\GraphQL\\Queries\\Job@resolve")
}
```

Am I right in thinking the first example should work? I'd expect that you could add middleware per `route/query`? That way you could check on scopes etc.

I have also tried
```
// This works with: InvalidArgumentException: Route [login] not defined which should be an easy fix
type Query  {
  job(id: ID!): Job @group(middleware: ["auth:api"])
}
```

Have I got the wrong end of the stick here?

Thanks again - REALLY nice!

**Comment by chrissm79** [comment]
Hey @t2thec, @hailwood nailed the response. Currently, the `@group` directive can only be placed on the `Query` or `Mutation` types. If you want to wrap authorization around other types, you would have to add it to a field with the `@can` directive like so:

```graphql
type User {
  jobs: [Job] @hasMany @can(if: ["view"], model: "App\\Job")
}
```

However, for your case I think extending the `Query` type would work best like so:

```graphql
# no middleware required to query the `me` field
type Query {
    me: User
}

# "auth:api" middleware required to query `job` field
extend type Query @group(middleware: ["auth:api"]) {
    job(id: ID!): Job
}
```

Let me know if you're still running into issues!

**Comment by t2thec** [comment]
LEGENDARY!! Thanks so much @chrissm79 and @hailwood. I had not seen the `@can` directive. A combo of both your suggestions @chrissm79 is exactly what I need. So powerful.

I love this package! Thanks again.
