### ISSUE TITLE
Pass Args direct to rules

### ISSUE THREAD

**Issue by canhkieu** [nuwave/lighthouse#1271]
Any way to add direct args params to rules. In this case, I need to pass page id into unique rule to make sure slug is unique. Is it nessary to create a custom by this case.

```
  createPage(
    title: String! @rules(apply: ["required"])
    slug: String @rules(apply: ["unique:pages,slug"])
  ): Page! @create @inject(context: "user.id", name: "user_id")

  updatePage(
    id: ID!
    title: String! @rules(apply: ["required"])
    slug: String @rules(apply: ["unique:pages,slug, @args('id') ]) <=== example like this
  ): Page! @update @can(ability: "update", find: "id")
```

**Comment by spawnia** [comment]
For complex validation, use custom validation directives https://lighthouse-php.com/master/security/validation.html#validate-fields

Heads up, this will become change (but become easier) in the upcoming v5, see https://github.com/nuwave/lighthouse/pull/1185

**Comment by sooxt98** [comment]
Hi @spawnia is there any workaround to make it work, it would be nice if i can control all the validation rules within schema
![image](https://user-images.githubusercontent.com/13378059/92404994-446ad900-f167-11ea-829f-4d97edbeea11.png)
