### ISSUE TITLE
@middleware() with throttle always got error messages, but actually throttle works

### ISSUE THREAD

**Issue by krisnieh** [nuwave/lighthouse#1291]
**Describe the bug**
This problem happened when using `@middleware(checks: ["throttle:3,1"])`. If keep trying to test the  throttle will get a correct result `"debugMessage": "Too Many Attempts."`
If trying to use `return Response::make("123456", 200);`  in the resolver file, It works well. 

```
type Query {
    users: [User!]! @middleware(checks: ["throttle:3,1"]) @all
}
```
**Expected behavior/Solution**

1. fix or give a solution, Thanks

**Output/Logs**

<details><summary>Click to expand</summary>

```
"debugMessage": "Argument 1 passed to Illuminate\\Routing\\Middleware\\ThrottleRequests::addHeaders() must be an instance of Symfony\\Component\\HttpFoundation\\Response, instance of App\\User given, called in /Users/kris/app/moon/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php on line 63"
```

</details></br>

**Environment**

Lighthouse Version:4.11
Laravel Version:7.5.2

**Comment by spawnia** [comment]
`@middleware` is deprecated because of errors like yours. The semantics of HTTP middleware mostly do not work on the GraphQL field level.

You can use a custom field middleware directive for throttling. If you come up with a good implementation, feel free to open a PR to Lighthouse.

**Comment by krisnieh** [comment]
oh~~ Thanks for your time!

**Comment by yormy** [comment]
I hope the middleware is not really being removed as I use it for some security stuff. However I did notice the problems with the standard laravel throttle (on the addHeaders). The throttling middleware https://github.com/GrahamCampbell/Laravel-Throttle has a different implemetation of the throttleing which makes it work with lighthouse (does not modify the headers of the request)
