### ISSUE TITLE
"The given data was invalid." - text is not overridden

### ISSUE THREAD

**Issue by cecilymiller** [nuwave/lighthouse#1292]
`The given data was invalid.` validation text is not overriden.

I have tried to do the following in the `Handler.php` file:
```php
if ($exception instanceof ValidationException) {
            return response()->json([
                'message' => __('The given data was invalid'),
                'errors' => $exception->validator->getMessageBag(),
            ], 422);
        }
```

And
```php
if ($exception instanceof \Nuwave\Lighthouse\Exceptions\ValidationException) {
            return response()->json([
                'message' => __('The given data was invalid'),
                'errors' => $exception->validator->getMessageBag(),
            ], 422);
        }
```

The text is overridden elsewhere but not during lighthouse graphql calls.

**Steps to reproduce**

1. Run any mutation which triggers validation exception

**Environment**

Lighthouse Version: ^4.5
Laravel Version: 6.18.3

**Comment by spawnia** [comment]
That's expected behaviour. Errors that occur in the GraphQL execution phase are handled solely through Lighthouse, which has it's own Exception handler.

Keep in mind that requests that are syntactically correct should always return a status code of `200`.

**Comment by cecilymiller** [comment]
> That's expected behaviour. Errors that occur in the GraphQL execution phase are handled solely through Lighthouse, which has it's own Exception handler.

So, how you'd translate or override the `The given data was invalid.` string?

**Comment by spawnia** [comment]
The docs about error handling cover that.

**Comment by cecilymiller** [comment]
I've read it but didn't catch anything. Do you mind to share a link or quote?

**Comment by spawnia** [comment]
> You can use the config to register error handlers that receive the Errors that occur during execution and handle them. You may use this to log, filter or format the errors. The classes must implement \Nuwave\Lighthouse\Execution\ErrorHandler

**Comment by cecilymiller** [comment]
There you go! Thanks a lot for you time & help.
