### ISSUE TITLE
@can directive cannot be used to hide attributes

### ISSUE THREAD

**Issue by cecilymiller** [nuwave/lighthouse#1293]
`@can` directive cannot be used to hide attributes

Usign `@can` directive on non-relationship attributes throws an error.

```javascript
type User {
    secret_attr: Int @can('view-secret-attr')
}
```

if `@can` directive is not designed to hide attributes, how to do so then?

**Output/Logs**

`Type 'Int' on 'secret_attr' can not be found in the schema.`

**Environment**

Lighthouse Version: ^4.5
Laravel Version: 6.18.3

**Comment by spawnia** [comment]
> @can directive cannot be used to hide attributes

Correct, it enables access control.

> `Type 'Int' on 'secret_attr' can not be found in the schema.`

Does that error occur without `@can`, too?

**Comment by cecilymiller** [comment]
> Does that error occur without @can, too?

No

> Correct, it enables access control.

So, how we can hide attributes for specific users? Isn't access control pretty much the same thing?

**Comment by spawnia** [comment]
> So, how we can hide attributes for specific users?

How does Laravel do it? `@can` works with policies, on the Model level.

**Comment by cecilymiller** [comment]
Ok, I was wondering is there a `lighthouse` way to do it.

Do you know a better way to do it than writing `getSecretAttribute` getters one by on on each model?

**Comment by spawnia** [comment]
I would look for a method that Laravel already uses and thus can be reused for different kinds of Model access. If there is nothing else, the getters you describe seem fine.

A custom field middleware directive is another option.

**Comment by cecilymiller** [comment]
Thanks for your suggestions!

> A custom field middleware directive is another option.

That's something I was looking for. Perfect

**Comment by lorado** [comment]
@spawnia I think this is a common problem. I currently also have to implement protection of some fields, depending on user role. As user roles may be implemented in tons of ways, the logic should be defined on the app-side. 

Should I write a guide (with example), how people can achieve filed/attribute protection (without throwing an error, and instead simply return null, e.g.)?

**Comment by spawnia** [comment]
@lorado That seems like a great idea, maybe an additional section to `Security -> Authorization`.

**Comment by spawnia** [comment]
> @spawnia Why exactly can't `@can` be use on fields on a type?
> From a GQL perspective, this seems odd as access control on query fields is no different than for type fields…

It is just not implemented. What is GQL?

**Comment by trm217** [comment]
GQL is just a abbreviation for graphql. Ah too bad, wouldl've been very intuitive if that worked. Unfortunatly I have to little insight on how this could be added to this lib to do it myself.
