### ISSUE TITLE
Remove Fluent

### ISSUE THREAD

**Issue by Zn4rK** [nuwave/lighthouse#13]
This is an opinionated issue, but I would like to test the waters.

I really like the Service Container and the dependency injection Laravel offers. Lighthouse currently resolves classes that inherits from either `GraphQLField` and `GraphQLType` via the service container, but both of these classes extends `Illuminate\Support\Fluent`, which in turn takes the argument $attributes in the constructor.

I've gone through the code, and can't really see why we are extending Fluent in the above mentioned classes. There's a few others that need it, but not those two specifically. If we remove the parent, we don't have to call the parent constructor if we need to use the dependency injection (we don't actually have to call the parent-constructor as it is right now, but my code inspector complains if I leave it out).

```php
class GameType {
    protected $gameRepository;

    public function __construct(GameRepositoryInterface $gameRepository) {
        $this->gameRepository = $gameRepository;
    }
    ...
```

Instead of 

```php
class GameType {
    protected $gameRepository;

    public function __construct(GameRepositoryInterface $gameRepository) {
        parent::__construct();
        $this->gameRepository = $gameRepository;
    }
    ...
```

Thoughts? I'd be happy to provide a PR doing this.

**Comment by chrissm79** [comment]
@Zn4rK Very much agree with this! I used `laravel-graphql-relay` as a base for this package and just brought over the Fluent `GraphQLField` but I agree that this wasn't necessary.

If you would like to create a PR for this I'd be more than happy to merge it in! Otherwise, I will put this on my list. Thanks for the feedback!

**Comment by Zn4rK** [comment]
If it is as easy as removing the extends-call and the parent call in the other constructors (which it looks like), I could probably find time to send a PR this week.

**Comment by chrissm79** [comment]
Fields are now just regular classes in v2.0 so no more extending from Fluent!
