### ISSUE TITLE
Create and Update directive not using overridden create method on model 

### ISSUE THREAD

**Issue by lukadriel7** [nuwave/lighthouse#1309]
### Problem

Lighthouse directive @create doesn't call Model overriden create method while it works with REST api. instead it calls the default one. Doesn't work with update either.

### Expected behaviour
Create and update directive should call overriden create and update method on model
**Steps to reproduce**

1. Make new model
2. Override create and update method and add functionalities
3. add mutation which uses the create and another th update directive

### Code

`

    public static function create(array $attributes = [])
    {
        $newSynopsis = json_decode($attributes['synopsis'], true);
        unset($attributes['synopsis']);
        $model = static::query()->create($attributes);
        $model->addMedia($attributes['poster'])->toMediaCollection('poster');
        $model->setTranslations('synopsis', $newSynopsis);
        $model->save();
        $model->authors()->attach(auth()->user()->id);
        return $model;
    }

    public function update(array $attributes = [], array $options = [])
    {
        if ($attributes['synopsis']) {
            $newSynopsis = json_decode($attributes['synopsis'], true);
            $this->setTranslations('synopsis', $newSynopsis);
            unset($attributes['synopsis']);
        }
        parent::update($attributes);
        if ($attributes['poster'] instanceof UploadedFile) {
            $this->addMedia($attributes['poster'])->toMediaCollection('poster');
        }
        return $this;
    }

`

Lighthouse Version:  4.11
Laravel Version: 6.18.8

**Comment by spawnia** [comment]
Thanks for the report.

The `create` and `update` methods are not the only way to interact with models. For instance, the very first example in the Laravel docs on how to insert a new model does not use `::create()`: https://laravel.com/docs/7.x/eloquent#inserts

Unfortunately, we can not change Lighthouse to use them because of nested mutations. For example, we might need to fill a model's attribute and then save it through it's parent relation:

```php
        if ($this->parentRelation instanceof HasOneOrMany) {
            // If we are already resolving a nested create, we might
            // already have an instance of the parent relation available.
            // In that case, use it to set the current model as a child.
            $this->parentRelation->save($model);

            return $model;
        }

        $model->save();
```

I recommend you stick to standard ways of extending your models, such as hooking into the `creating` lifecycle event or adding getters/setters for your attributes.

**Comment by lukadriel7** [comment]
@spawnia thank you for the quick response. I have a question though, using observers, is there a way to access the arguments passed to the create method ? I would like to access files sent but simply using the Request facade gives the files as UploadedFile with the object name as a number.
I need to differentiate the files by their names. Thank you again

**Comment by spawnia** [comment]
That is outside of Lighthouse's scope.
