### ISSUE TITLE
Global Scope not properly applied to models in ModelRelationFetcher 

### ISSUE THREAD

**Issue by ryangroth5** [nuwave/lighthouse#1313]
**Describe the bug**

A parent model that has a scope on it (in my case a roll-your-own soft delete) with a child will more parents than intended in the function "reloadModelsWithRelationCount" due to the global scope not being properly applied to the parent relationship. This will cause downstream request for the children to union all the (duplicate) "parents" of the children. The children will be reported for each duplicate parent. 

e.g. 
```php
class Parent extends Model
{
	static const table_name = "Parent";

	function getKey()
	{
		return("id")
	}

	function boot()
	{
        static::addGlobalScope("current", function (Builder $builder) {
            $builder->where(static::table_name.".is_final", "=", true);
        });
	}

	function children()
	{
    	return($this->hasMany(Child::class)
	}

	// ...
}
```

```gql
{
  parent(id: 123) { 
    children(first:2, page:0) { data { id } } 
  }
}
```

Create two parents, one with is_final set to false, the other set to true. 

No unique constraint on "id", sequence or nothing for PK. Unique constraint on is_final = true and id. 

e.g.
```sql
CREATE TABLE "parent" (
  "revision" int8 NOT NULL DEFAULT nextval('parent_revision_seq'::regclass),
  "is_final" bool,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "id" varchar(21) COLLATE "pg_catalog"."default" NOT NULL,
  CONSTRAINT "parent_pkey" PRIMARY KEY ("revision")
);
```

The following patch fixes the problem. 

```diff
--- src/Execution/DataLoader/ModelRelationFetcher.php	2020-04-21 18:29:03.277277087 +0000
+++ src/Execution/DataLoader/ModelRelationFetcher.php~	2020-04-21 18:14:03.000000000 +0000
@@ -134,7 +134,7 @@
     {
         return $this->models
             ->first()
-            ->newQuery();
+            ->newModelQuery();
     }
 
     /**
```

**Environment**

Lighthouse Version: 4.3
Laravel Version: 5.5

**Comment by spawnia** [comment]
Thanks for the report. Can you provide a PR with a failing test case, probably in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/HasManyDirectiveTest.php?

**Comment by ryangroth5** [comment]
Yes. I'm putting this on my task list. Might be a sec to turn around with
some of the other priorities I am balancing, but will get it to you.

**Comment by spawnia** [comment]
This should be fixed, we are only using `newModelQuery()` in the current version of `ModelRelationFetcher`. Feel free to reopen if the issue persists.
