### ISSUE TITLE
Paginator with Custom Builder - error with types

### ISSUE THREAD

**Issue by aibarra11** [nuwave/lighthouse#1314]
Sorry, i'm fairly new to graphQL and lighthouse. I'm not sure if this is a bug, or if i missed something in the docs. 
I used the default paginator resolver and queries worked fine. However i needed to add some parameters, so followed the documentation to build my own... builder. Two of my fields have custom types. There is no problem when using the default paginator, but using my custom one, i get errors like this

```
Expected a value of type "ViewingRequestStatus" but received: 3
```

**Schema**
```
type ViewingRequest @model(class: "\\AppViewingRequestRead"){
    uuid: String!
    requestorUuid: String!
    scheduleUuid: String!
    districtUuid: String!
    congregationUuid: String!
    siteUuid: String
    status: ViewingRequestStatus
    language: Languages
    user_uuid: String
    streamEventUuid: String!
}

type Languages{
    name: String
    id: Int
}

extend type Query {
    viewingRequests(
        streamEventUuid: String, 
        scheduleUuid: String, 
        requestorUuid: String
    ): [ViewingRequest!]! @paginate(model: "App\\ViewingRequestRead", builder: "App\\ViewingRequestRead@showRequests")
}
```

**App\ViewingRequestRead**
```
class ViewingRequestRead extends IncRead
{
    protected $enumCasts = [
        'status' => ViewingRequestStatus::class,
        'language' => Languages::class,

    ];

    protected $casts = [
        'status' => 'int',
        'language' => 'int'
    ];

```
```
    public function showRequests($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo): Builder
    {
        return DB::table('viewing_requests')
        ->when(key_exists("streamEventUuid", $args), function ($q) use ($args) {
            return $q->where('streamEventUuid', '=', $args["streamEventUuid"]);
        })->when(key_exists("scheduleUuid", $args), function ($q) use ($args) {
            return $q->where('scheduleUuid', '=', $args["scheduleUuid"]);
        })->when(key_exists("requestorUuid", $args), function ($q) use ($args) {
            return $q->where('requestorUuid', '=', $args["requestorUuid"]);
        });
```

**ViewingRequestEnum**
```
<?php

namespace App\Enums;

use App\Enums\IncEnum;


final class ViewingRequestStatus extends IncEnum
{
    const Archived = 0;
    const New =   1;
    const LocaleSubmitted =   2;
    const DistrictSubmitted = 3;
    const LocaleApproved =   4;
    const DistrictApproved = 5;
    const CentralApproved = 6;
    const Cancelled = 7;
    const Denied = 8;
    const Draft = 9;
}
```
This is registered via GraphQlServiceProvider.

**Output/Logs**

<details><summary>Click to expand</summary>

```
"debugMessage" => "Expected a value of type "Languages" but received: 1"
      "message" => "Internal server error"
      "extensions" => array:1 [
        "category" => "internal"
      ]
      "locations" => array:1 [
        0 => array:2 [
          "line" => 8
          "column" => 21
        ]
      ]
      "path" => array:4 [
        0 => "viewingRequests"
        1 => "data"
        2 => 2
        3 => "language"
```

</details></br>

**Environment**

Lighthouse Version: 4.11.0
Laravel Version: 7.5.1

**Comment by stayallive** [comment]
I'm not seeing your schema definitions for the enum values but it's possible you are going wrong there: https://lighthouse-php.com/4.11/the-basics/types.html#enum.

Assuming you did the above correct (with the `@enum(value: 1)` for example) it might be you are passing the number to the query while GraphQL expects an named value from the enum.

For example if we take this schema:

```graphql
enum EmploymentStatus {
  INTERN @enum(value: 0)
  EMPLOYEE @enum(value: 1)
  TERMINATED @enum(value: 2)
}

type Employee {
  id: ID!
}

extend type Query {
  employees(status: EmploymentStatus): [Employee!]!
}
```

GraphQL expects your query to read like this:

```graphql
query {
  employees(status: EMPLOYEE) {
    id
  }
}
```

But I suspect you are executing this query causing the error:

```graphql
query {
  employees(status: 1) {
    id
  }
}
```

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

**Comment by aibarra11** [comment]
Sorry, My Enum is defined there. I'm using the BenSampo/laravel-enum package. 
My Enums work fine when using the default paginate directive. When I add the custom builder - showRequests, i get there error.
