### ISSUE TITLE
AuthFactory not bound to container

### ISSUE THREAD

**Issue by armycoder** [nuwave/lighthouse#1318]
**Describe the bug**

AuthFactory not bound to container

**Expected behavior/Solution**

PR will be posted soon

**Environment**

Lighthouse Version: latest
Laravel Version: 6.0

**Comment by spawnia** [comment]
Can you please be more specific in your issue? Which Lighthouse version are you using? What error are you getting?

**Comment by armycoder** [comment]
Latest version of lighthouse(4.11 i think). And it says Factory class not instantiable. I believe this issue is OctoberCMS specific

**Comment by spawnia** [comment]
Lighthouse works fine with a default Laravel install. I think it is out of scope for us to fix compatiblity when Laravel is modified in fundamental ways.

**Comment by armycoder** [comment]
It's three lines of code. You're really going to shut out the lesser laravel community?

**Comment by spawnia** [comment]
The proposed fix was not even working properly. It's also something that can be easily done outside of Lighthouse.

It is not Lighthouse's responsibility to fix incompatibilities that other packages introduce. OctoberCMS seems to mess with core Laravel functionality here, so it is up to them to fix it.
