### ISSUE TITLE
Add 4.12 version to docs

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1322]
@spawnia I don't know how docs generating works, and I don't want to mess it up. So I wanted just to ping you to create docs for 4.12

**Comment by spawnia** [comment]
I did the usual preparation, i guess the recent GitHub outage has caused the deployment to abort.

**Comment by spawnia** [comment]
@chrissm79 it seems like the deployment stopped working, can you take a look?

**Comment by spawnia** [comment]
It's up and running now, the addition of Prettier caused an error with the Netlify deployment.
