### ISSUE TITLE
Using sync on Nested mutations with pivot data saves only the last entry

### ISSUE THREAD

**Issue by krisee99** [nuwave/lighthouse#1332]
***A bit of context***
I'm making an E-commerce application where the total amount of the Order needs to be calculated based on the value and quantity of the ordered products.
I'm using two Models and a Pivot to accomplish this:
The relation between the two models, Order and Product is belongsToMany

Here is the Pivot that calculates the total Order amount:

```PHP
<?php

namespace Extension\Shop\Models\Pivots;

use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Database\Eloquent\Model;

use Extension\Shop\Models\Product;

class OrderProductPivot extends Pivot
{
    protected $table = 'order_product';

    public static function boot()
    {
        parent::boot();

        self::created(function(Model $model) {
            $product = Product::find($model->product_catalog_id);
            if (!$product) {
                return $model;
            }
            $parent = $model->pivotParent;
            
            $parent->net_value += $product->net_price;
            $parent->value += ($product->net_price * (1 + ($product->vat / 100))) * $model->quantity;
            $parent->order_quantity = $model->quantity;
            $parent->save();
            return $model;
        });
    }
}
```

**Describe the bug**

Using the sync method in a nested Mutation with pivot data doesn't save all inputs.

***Order.graphql***
```GraphQL
extend type Mutation {
    createOrder(input: CreateOrderInput! @spread): Order 
        @create
}

input CreateOrderInput {
    customer: UpdateCustomerRelation!
    products: syncProductsRelation!
    extra_information: String
}

input UpdateCustomerRelation {
    connect: ID
    create: CreateCustomerInput
}

input syncProductsRelation {
    sync: [syncProductPivotRelationData!]
}

input syncProductPivotRelationData {
    product_catalog_id: ID!
    quantity: Int!
}

type Order @modelClass(class: "\\Extension\\Shop\\Models\\Order") {
    id: ID!
    customer: Customer @belongsTo
    order_token: String!
    products: [Product!]! @belongsToMany
    order_volume: Int!
    net_amount: Float!
    amount: Float!
    discount_percentage: Float
    total_amount: Float!
    extra_information: String
}

```
***Product.graphql***
```GraphQL
type OrderProductPivot {
    "Ordered quantity of a product"
    quantity: Int!
}

type Product @modelClass(class: "\\Extension\\Shop\\Models\\Product") {
    catalog_id: ID!
    name: String!
    description: String
    net_price: Float
    vat: Float
    in_stock: Int
    out_of_stock_text: String
    sale: Boolean
    sale_percentage: Float
    technical_specs: ObjectScalar
    pivot: OrderProductPivot
}
```

The relations are set up just fine, because if I make the relations manually in the DB, I can query it:
```GraphQL
{
  
  listOrder(first: 50) {
    data {
      products {
      	catalog_id
      }
    }
  }
  
}
```
produces:
```JSON
{
  "data": {
    "listOrder": {
      "data": [
        {
          "products": [
            {
              "catalog_id": "prdct_87102409"
            },
            {
              "catalog_id": "prdct_63154058"
            }
          ]
        }
      ]
    }
  }
}
```

**Expected behavior/Solution**

Given the following mutation:
```GraphQL
mutation {
    createOrder(input: {
      extra_information: "DELIVERIT PLS"
      products: {
        sync: [
          {product_catalog_id: "prdct_87102409" quantity:10}
          {product_catalog_id: "prdct_63154058" quantity:20}
        ]
      }
      customer: {
        create: {
          first_name:"asd"
          last_name:"asd"
          email:"asd"
          country:"asd"
          city:"asd"
          zip_code:"asd"
          address:"asd"
          house_nr:"asd"
        }
      }
      
      
    }) {
    customer {
      first_name
      last_name
    }
    products {
      catalog_id
      name
      net_price
      vat
      pivot {
        quantity
      }
    }
    order_token
  }
}
```

I expect that all products are saved and returned in the response, however, only the last one is saved:
```JSON
{
  "data": {
    "createOrder": {
      "customer": {
        "first_name": "asd",
        "last_name": "asd"
      },
      "products": [
        {
          "catalog_id": "prdct_63154058",
          "name": "Autem ut perspiciatis ut in.",
          "net_price": 3848,
          "vat": 17,
          "pivot": {
            "quantity": 20
          }
        }
      ],
      "order_token": "BdWciJ0wKMJHcUUvAKO7gUBeUfDTIuT3xWA1Jk4i"
    }
  }
}
```

**Environment**

Lighthouse Version: 4.11
Laravel Version: 7

**Comment by spawnia** [comment]
Can you try v4.12.1?

**Comment by krisee99** [comment]
Dear @spawnia 

Unluckily it doesn't solve the issue. Also, I've edited the Order.graphql in my original description as it contained a deprecated id field what is not used anymore. The catalog_id is the primary key on the Product model, but this doesn't change the problem

**Comment by krisee99** [comment]
Also, I may have found the source of the problem:
In the class ```Nuwave\Lighthouse\Execution\Arguments\NestedManyToMany``` the method ```generateRelationArray``` the foreach overwrites the $values variable, and this breaks the sync relationArray.

**Comment by krisee99** [comment]
I think a good solution would be to use the $relation->relatedPivotKey as it describes the actual key on the pivot table, not some hard coded value:
![image](https://user-images.githubusercontent.com/20201094/80321575-5d10cd00-881e-11ea-88e6-69f21e4a6f61.png)

**Comment by krisee99** [comment]
On another tought, the relatedPivotKey may not be suitable for everyone, as some may use an id column on pivot tables, where I use composite primary keys as I hardly ever query a pivot table by it's own id column.

**Comment by lorado** [comment]
Have you tried to use `id` instead of `product_catalog_id` in your input? So try this:

```graphql
input syncProductPivotRelationData {
    id: ID!
    quantity: Int!
}
```

This should work, I guess. 

It doesn't matter how your key is actually named, because we don't process it. Instead laravels `sync` is used, where you define ids of the related model as array key, and pivot values as array value. When we implemented it, there was a question, what field name on input we should use, to grab id of the related model. We simplified it to be a fixed `id`. Think of this mutation like you are using typical `->sync()`, array key goes to `id` input field, pivot data (items of array value) go into the same input with corresponding fields.

You also can read https://github.com/nuwave/lighthouse/issues/1088 for more details how implementation was made

**Comment by krisee99** [comment]
Dear @lorado,

Yes you are right, this approach did solve the issue. Either I skimmed over this in the documentation, or it just wasn't clear for me what the id field meant in this case, but it's clear now.

Thank you for your help, and sorry to lead you on!
Best regards!
