### ISSUE TITLE
How to provide an alias for a filed in lighthouse

### ISSUE THREAD

**Issue by anoop151** [nuwave/lighthouse#1333]
**What problem does this feature proposal attempt to solve?**

**Which possible solutions should be considered?**

Hi is there any to specify an alias for field better than this nuwave/lighthouse  schema.graphql
data {
      firstName: firstname
      roomNumber: room_number
}
Do we have the alias feature same as like basic graphql, i have achived the alias feture like graphql. But there is a problem i have to query with this alias name again and again and for different query. Do this feature to alias a field in type or any other method is available in light house

**Comment by spawnia** [comment]
`@rename`

**Comment by anoop151** [comment]
Wow thanks spawnia , its worked
