### ISSUE TITLE
Protecting input fields

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1334]
**Current state and the problem**
In my app I have different user roles, for example *Candidate* and *Admin*. There is `CandidateProfile` with many fields and relations. *Admin* can access all fields of `CandidateProfile`, but *Candidate* role has some restrictions, e.g. only *Admin* may access field `admin_notes`.

I was able to restrict access to this fields with a custom directive, like described [in docs](https://lighthouse-php.com/master/security/authorization.html#custom-field-restrictions)    

But now I am facing the situation - how could I restrict mutation access to such fields? I am happy to be able to use `@create`, `@update` or `@upsert` built-in directives, as they are well tested, and they just works. So I don't want to create an extra resolver for this use case.

**Possible solutions and ideas**

- **_Solution:_** Use two different mutations with different Input types (simply don't define fields, that user should not be able to write), and control access for mutation via `@can` directive. 
A huge disadvantage of this purpose - if model becomes new fields, I partially have to duplicate input definitions, because as I know it is not possible in GraphQL to extend an input type. So code isn't DRY and is prone to errors.
- _**Idea:**_ What I was thinking about - It would be nice, if I could use something like the custom field restrictions above, but for input fields. But sure we can't return null or any kind of value, as it will be then inserted into the DB via `@create`, `@upsert` etc. The input should simply disapear, e.g. via `unset()`
Actually I think it should work, if I could completely remove/unset the input field depending on user role, even if it was sent in client request. If there is no input field, it will be not modified. But how can I do this? All ArgDirectives haven't that much power...

Do you have any suggestions, how to implement it? Is it something good to implement in lighthouse? Or should it be in application scope? If so, I think we still need something new to introduce in lighthouse, to be able to achieve it.

**Comment by spawnia** [comment]
I have been working towards making use cases such as yours way easier. Previously, iterating through the raw user input in sync with the associated types and schema directives was a huge pain. The current implementation of `FieldFactory` is a testament to that - because it is so hard, we shoved all of that stuff in there.

The introduction of the `ArgumentSet` class made that process way easier. It provides a convenient data structure that contains both concrete values and schema definitions.

You can take a look at the work done in https://github.com/nuwave/lighthouse/pull/1185 to get an idea of how you could implement something that fits your need. (Btw a review on there would be great, too). A modified version of https://github.com/megawubs/lighthouse/blob/allow-complex-validation-of-input-types/src/Schema/Directives/ArgTraversalDirective.php could be what you need.

**Comment by lorado** [comment]
Lol.. I knew I saw somewhere that `ArgumentSet` (didn't know anymore how it was called) but I thought it was used in combination with some of `ArgDirective`s, therefore I wasn't able to find something.

That is actually a totally different point of view. You have to think one abstraction level higher, and from field perspective and not from argument perspective. I was simply limiting myself...
I didn't know `FieldMiddleware` is able to modify input arguments. That is awesome! Though I got it, I think it would be good to mention that capability in the docs. 

#1185 has very much changes, I'll try to review it this weekend.

For those who is trying to solve similar problem:
I created `CanModifyDirective` that just extends `BaseDirective` without implementation of any interface. `CanModifyDirective` has no code at all. `@canModify` takes `role` argument, where I can define, which roles can modify this input field.
Then I created `ApplyCanModifyDirective` which implements `FieldMiddleware` and used it on the mutation field.
Here is code listing (simplified)

```php
class CanModifyDirective extends BaseDirective implements DefinedDirective
{
    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'SDL'
"""
If user has not required role, this input field will be omitted
"""
directive @canModify(
  """
  The user roles that are allowed to modify the field.
  """
  role: String!
) on INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION
SDL;
    }
}
```

```php
class ApplyCanModifyDirective extends BaseDirective implements FieldMiddleware, DefinedDirective
{
    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'SDL'
"""
Omit attributes in first level, if user is not authorized to modify the field
"""
directive @applyCanModify on FIELD_DEFINITION
SDL;
    }

    public function handleField(FieldValue $fieldValue, Closure $next): FieldValue
    {
        $originalResolver = $fieldValue->getResolver();

        return $next(
            $fieldValue->setResolver(
                function ($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo) use ($originalResolver) {
                    foreach ($resolveInfo->argumentSet->arguments as $key => $argument) {
                        $filteredDirectives = $argument->directives->filter(
                            function ($object): bool {
                                return $object instanceof CanModifyDirective;
                            }
                        );

                        if ($filteredDirectives->count() === 1) {
                            // check if user is authorized and has a required role
                            $user = $context->user();
                            if (!$user || $user->role !== $filteredDirectives->first()->directiveArgValue('role', null)) {
                                unset($resolveInfo->argumentSet[$key]);
                            }
                        }
                    }

                    return $originalResolver(
                        $root,
                        $resolveInfo->argumentSet->toArray(),
                        $context,
                        $resolveInfo
                    );
                }
            )
        );
    }
}
```

```graphql

extend type Mutation {
    updateCandidate(id: ObfId!, input: UpdateCandidateInput! @spread): Candidate @applyCanModify @update @can(ability: "update", find: "id")
}

input UpdateCandidateInput {
    admin_notes: String @canModify(role: "Admin")
}
```

I'll close this ticket, as your direction tip actually solved my problem.

**Comment by spawnia** [comment]
@lorado nice! I would not mind some extra information in the docs.

In your implementation, you might want to consider recursing down in case of nested inputs.
