### ISSUE TITLE
Add global defaultCount for pagination directive

### ISSUE THREAD

**Issue by BenHeimberg** [nuwave/lighthouse#1339]
### Add global defaultCount value for pagination directive

When working on big projects with a lot of queries that returns paginated results, it would be nice to be able to set the default count outside of the paginate directive.

It would save time, and simplify development of systems that requires the same pagination counts on almost every query.

### Current implementation
```
type Query {
     queryOne: @paginate(defaultCount: 15)
     queryTwo: @paginate(defaultCount: 15)
}
```

### Proposed change
```
type Query {
     queryOne: @paginate
     queryTwo: @paginate
}
```

### Solution
Add `pagination_default_count` property to the config file.

I would love to implement it, if you guys think its reasonable.

_Ps. This is my first ever proposal :)
Great library!_

**Comment by spawnia** [comment]
That sounds very reasonable. In order to be backwards compatible, the setting will have to default to `null`, we might add another default in v5

See https://github.com/nuwave/lighthouse/blob/master/CONTRIBUTING.md for how you can prepare a PR.
