### ISSUE TITLE
morphTo in mutation not syncing/connecting?

### ISSUE THREAD

**Issue by krisee99** [nuwave/lighthouse#1346]
**Describe the bug**

Okay, so this might not be the best platform, but I can't seem to determine wheter this is a bug or not, so I'll give it a shot here [as well](https://stackoverflow.com/questions/61533260/how-does-one-define-a-polymorphic-one-to-many-relation-for-mutations-in-laravel).

The problem is that when I created a fresh, crispy Laravel project, added lighthouse to it then followed the documentation on polymorphic relationships, made every modifcation exactly(almost) like the docs stated, and I just couldn't make it work.

Schema
```GraphQL
type Query {
    posts: [Post!]! @paginate(defaultCount: 10)
}

type Mutation {
  createPost(input: CreatePostInput! @spread): Post @create
}

input CreatePostInput {
  title: String!
  content: String
  images: CreateImageMorphToMany
}

input CreateImageMorphToMany {
  sync: [ID!]
  connect: [ID!]
}

type User {
    id: ID!
    name: String!
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
    images: [Image]! @morphMany
}

type Post {
    id: ID!
    title: String
    content: String
    images: [Image]! @morphMany
}

type Image {
    id: ID!
    src: String
    name: String
    imageable: Imageable @morphTo
}

union Imageable = Post | User

```

Post Model
```PHP
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;

class Post extends Model
{

    protected $fillable = [
        'title', 'content'
    ];

    public function images(): MorphMany
    {
        return $this->morphMany('App\Image', 'imageable');
    }
}
```

Image Model
```PHP
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;

class Image extends Model
{
    public function imageable(): MorphTo
    {
        return $this->morphTo();
    }
}
```

Migrations
```PHP
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('content');
            $table->timestamps();
        });
        // This is only here for the sake of simplicity
        Schema::create('images', function (Blueprint $table) {
           $table->id();
            $table->string('src');
            $table->string('name');
            $table->integer('imageable_id')->nullable();
            $table->string('imageable_type')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('posts');
        Schema::dropIfExists('images');
    }
}
```

The mutation
```GraphQL
mutation {
  createPost(input: {
    title: "asd2", 
    content: "asd2",
    images: {
      sync: [1]
    }

  }) {
    title
    images {
      src
    }
  }
}
```

Result:
```JSON
{
  "data": {
    "createPost": {
      "title": "asd2",
      "images": []
    }
  }
}
```

**Expected behavior/Solution**
Lighthouse connects the polymorphic relation in the given table and returns the result of the queried data.

**Steps to reproduce**

1. Create a Fresh Laravel project & install lighthouse
2. Make a polymorphic relation according to both [Laravels](https://laravel.com/docs/7.x/eloquent-relationships#one-to-many-polymorphic-relations) and [Lighthouses](https://lighthouse-php.com/4.12/eloquent/polymorphic-relationships.html#one-to-many) documentaion
3. Seed the db with random comments
4. Try to create a new post and attach one of the existing comments to it in the same(nested) mutation

**Lighthouse Version**
4.12

**Comment by spawnia** [comment]
`MorphMany` is equivalent to a monomorphic `HasMany`, so `sync` is not an available operation.

**Comment by krisee99** [comment]
Dear @spawnia ,

That makes sense, but then what type of operation should I use in this case? I mean it's not like connect works either.

**Comment by spawnia** [comment]
`create`, `update`, `upsert` and `delete`.

**Comment by krisee99** [comment]
Ahh I see, so I can't directly connect the two, but rather I need to manually update the relation.

Thanks a lot!
