### ISSUE TITLE
Add headers to config file

### ISSUE THREAD

**Issue by immeyti** [nuwave/lighthouse#1359]
Hi. can I add headers to the config file and then open a PR?
https://github.com/nuwave/lighthouse/blob/53b46a64fc96a242efaf7053d5c3324689bdf4d2/src/Defer/Defer.php#L198

**Comment by spawnia** [comment]
Generally yes. Can you elaborate on why that would be useful?

**Comment by immeyti** [comment]
Actually I don't know, just I want to learn more and contribute in open source.

**Comment by spawnia** [comment]
@immeyti i appreciate it, great idea. I just went through the `TODO` items in the repository and couldn't find something actionable in there.

A great starting point would be the open issues, i marked some that are great for getting started: https://github.com/nuwave/lighthouse/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22

**Comment by spawnia** [comment]
Closing this issue, as there seems to be no real need for configurable headers in the `@defer` implementation.
