### ISSUE TITLE
Laravel's "different" validation rule doesn't seem to work

### ISSUE THREAD

**Issue by SereiPonna** [nuwave/lighthouse#1362]
**Describe the bug**

I am using Laravel's validation "different" to validate 2 fields preventing them from having the same value. But whenever I put it, even though the 2 fields don't have the same value, validation always failed.
(This problem may happen on other fields comparison validation rules. I haven't tried them all but I have tried using "after:other_field" or "before:other_field" and the validation also didn't work correctly.)

**Expected behavior/Solution**

I expect the validation to pass if those 2 fields have different value.

**Steps to reproduce**

1. Having a mutation with the following input:
```
type mutation {
    replaceWorkShift(input: ReplaceWorkShiftInput @spread): WorkShift @update
}

input ReplaceWorkShiftInput {
    id: ID!
    current_date: Date! @rules(apply: ["required", "date", "different:replaced_date"])
    replaced_date: Date! @rules(apply: ["required", "date", "different:current_date"])
}
```
2. Try executing the mutation from the client
```
mutation {
    replaceWorkShift(
        input: {
            id: 1
            current_date: "2020-05-09"
            replaced_date: "2020-05-19"
        }
    ) {
        id
        current_date
        replaced_date
    }
}
```
3. No matter what value you input in current_date and replaced_date, the validation will always return fail.

**Output/Logs**

<details><summary>Click to expand</summary>

```
{
    "errors": [
        {
            "message": "Validation failed for the field [replaceWorkShift].",
            "extensions": {
                "validation": {
                    "input.current_date": [
                        "The input.current date and replaced date must be different."
                    ],
                    "input.replaced_date": [
                        "The input.replaced date and current date must be different."
                    ]
                },
                "category": "validation"
            },
...
```

</details></br>

**Lighthouse Version**

4.12.4

**Comment by spawnia** [comment]
I think this happens because your two fields are `Date` scalars. They are represented as `\Carbon\Carbon` instances internally, which will fail an equality check by nature of being different objects. You can try to change the arguments to `String` temporarily, validation should work as expected.

Scalar conversion is a fundamental part of GraphQL execution and is the first thing that happens when accepting user inputs. Many other parts of Lighthouse depend on the fact that it happens right away. We can not change that without severe breakage in other use cases.

I think a clean solution would be to add a custom validation rule that compares two date instances for equality.

**Comment by SereiPonna** [comment]
Ok, so I have tried changing Date to String and the same problem occurred. How about other date comparison rules such as "after", "before", "after_or_equal" and "before_or_equal"? Because they don't seem to work correctly too.

**Comment by spawnia** [comment]
I am surprised the issue persists when using `String`, we will have to look into what those rules actually do internally.

**Comment by spawnia** [comment]
@SereiPonna i tested `different` with `String` and `after` with `Date`, both worked. I could reproduce the failure with `different` and `Date` though.

**Comment by spawnia** [comment]
I reformulated the root cause of this issue, as it has come up multiple times now and opened https://github.com/nuwave/lighthouse/issues/1376 to track possible solutions.
