### ISSUE TITLE
Error that say nestedArgResolvers() must be an instance of Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet, int given

### ISSUE THREAD

**Issue by NaungYeHtet** [nuwave/lighthouse#1363]
I have a mutation that create Resume for a particular user that require user and seeker id as foreign fields

```
mutation {
  createResume (
    title:"Web Developer"
    user: 1
    seeker: 1
  ){
    title
  }
}
```

And the type of each instances

```
type Resume {
    id: ID!
    title: String
    user: BackpackUser! @belongsTo
    seeker: Seeker! @belongsTo
}

type BackpackUser {
    id: ID!
    name: String!
    resumes: [Resume!]! @hasMany
}

type Seeker {
    id: ID!
    name: String!
    user: BackpackUser! @belongsTo
    resumes: [Resume!]! @hasMany
}
```

After i saved the resume from Graphql playground, this error shows

**"debugMessage": "Argument 1 passed to Nuwave\\Lighthouse\\Execution\\Arguments\\ArgPartitioner::nestedArgResolvers() must be an instance of Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet, int given, called in C:\\xampp\\htdocs\\my-project-lighthouse\\vendor\\nuwave\\lighthouse\\src\\Execution\\Arguments\\ResolveNested.php on line 33",**

**Lighthouse Version ^4.12**

**Comment by spawnia** [comment]
https://lighthouse-php.com/master/eloquent/nested-mutations.html#belongsto
