### ISSUE TITLE
Extend empty root type causes Syntax Error

### ISSUE THREAD

**Issue by RyotaBannai** [nuwave/lighthouse#1364]
**What problem does this feature proposal attempt to solve?**

I really love the Schema Organisation feature so that I can define any root type wherever with `extend`. Unfortunately, I found it a little unuseful that I can't `extend`  an empty root type such as `mutation`. When I did so there is an exception saying 
```
{
  "message": "Syntax Error: Expected Name, found }",
  "exception": "Nuwave\\Lighthouse\\Exceptions\\ParseException",
  ...
}
```
 
So tried not to define `mutation` first of all, and to do `extend` in other files, however, it's also an error.

```
{
  "message": "Undefined index: Mutation",
  "exception": "ErrorException",
  ...
}
```
**Which possible solutions should be considered?**

It'll be convenient Lighthosue allows it so I don't need to add at least one field to avoid the error, and if so I'd keep the file clearer:)

Thanks :)

**Comment by spawnia** [comment]
Today is your lucky day. I removed the requirement to define empty base types for `Query`, `Mutation` und `Subscription` in a recent PR: https://github.com/nuwave/lighthouse/pull/1347

Just released: https://github.com/nuwave/lighthouse/releases/tag/v4.13.0

**Comment by RyotaBannai** [comment]
@spawnia Thank you for committing on this new version! It's working now:) 
With v4.13.0, `input` type (I used it with `mutation` root type) doesn't seem work with previous version operations, although it works well when passing variables without `input` type debug Message says,
```json
"errors": [
    {
      "debugMessage": "Object of class stdClass could not be converted to string",
      ...
    }
    ...
]
```
My codes is just as simple as like this: 
```graphql
input CreateUserInputs {
    name: String!
    email: String!
    password: String!
    active: Boolean = 1
}

extend type Mutation {
    updateUser(id: ID!, name: String): User @update
    createUser(input: CreateUserInputs! @spread): User @create
}
`
``

Is there another update regarding the usage of `input` type, so my operations are incorrect?

Thanks :)

**Comment by spawnia** [comment]
`Boolean = 1` is wrong.

Apart from that, there is too little information in the error message. A stacktrace would help.

**Comment by RyotaBannai** [comment]
@spawnia 
Right, the default value was incorrect and now all works great again:) `v4.12.0` still allows it so I thought it was correct to set Boolean.
Will definitely try out other improvements!

Thanks a lot!
