### ISSUE TITLE
Get data of authenticate user

### ISSUE THREAD

**Issue by NicolaRamazzotti** [nuwave/lighthouse#1367]
im tring to implement a simple login with lighthouse and this plugin joselfonseca/lighthouse-graphql-passport-auth
#.

The login and registration system working well and when i try to login te response of server give me the access_token of user, now when i try to get the user data when user is logged with this query

` me: User @auth`

then return null, but when i change the query to this

` me: User @auth(guard: "api")`

return the data of user logged.

i dont say where is my problem, yesterday i have clean my pc because is have low memory, and when im tried to start server of laravel this gave me an error and i solve this error with composer update.

any one can help me?

**Comment by BenHeimberg** [comment]
Try adding `protected $guard = 'api':` to you Users model, or set default auth guard to api in Kernel.php

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
