### ISSUE TITLE
Add programmatically registered types to generated file via 'ide-helper'

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1369]
**What problem does this feature proposal attempt to solve?**

At the moment I have only one small "issue" - I use enums with `BenSampo\Enum\Enum`, and they are sure added to the schema with `$typeRegistry->register(new LaravelEnumType($enum))`.

But lighthouse is focused more in defining SDL directly, so the most time I am defining schema in `.graphql`-files. But my IDE don't know about existing of enums, that are defined in PHP, like I described above. The code works, schema is valid, but while writing schema IDE says something like: "The type '...' is not present ...". 

I tried to add enum definition to autogenerated `schema-directives.graphql`, and it works. IDE knows enum, and it isn't a part of schema, so schema stays unchanged, valid, without double definitions of enums. 

**Which possible solutions should be considered?**

I think it would be good, if we could add at least enum definitions to autogenerated file via `lighthouse:ide-helper`.

The better solution - add all of types to that file, which are registered with `$typeRegistry->register()`

So let us discuss, which solution you think is good, and do we need it at all? I would like to write a PR, when the direction of solution is clear.

**Comment by spawnia** [comment]
@lorado great idea, haven't thought of that yet.

I find the lack of proper autocompletion and IDE support unsettling when working with programmatic types. Generating them through the `ide-helper` command should be a pretty good solution.
