### ISSUE TITLE
Can't create/reuse variable in Input

### ISSUE THREAD

**Issue by PheakOmi** [nuwave/lighthouse#1374]
**Describe Issue**
I have defined an input in my schema _trip.graphql_. The input looks like:
`input createTripInput {`
       `name: String!`
       `from: Date! @rules(apply: ["required", "date"])`
       `to: Date! @rules(apply: ["required", "date", "after:from"])`
`}`

**My question** 
The validation on `to` doesn't work. I wonder how do I reuse my `from` field as a validation input for my next field?

PS: I tried changing from `to: Date! @rules(apply: ["required", "date", "after:from"])` to some static value like `to: Date! @rules(apply: ["required", "date", "after:2020-02-15"])` and it works perfectly.

**Lighthouse Version v4.13.0**

**Comment by andershagbard** [comment]
You may have to make a custom Validate directive. https://lighthouse-php.com/4.12/security/validation.html#validate-fields

**Comment by spawnia** [comment]
I reformulated the root cause of this issue, as it has come up multiple times now and opened https://github.com/nuwave/lighthouse/issues/1376 to track possible solutions.
