### ISSUE TITLE
Queries in App\GraphQL\Queries not found in schema.graphql

### ISSUE THREAD

**Issue by M-P-programing** [nuwave/lighthouse#1375]
**Describe the bug**
When I try to access 
```
type Query{
    families: [Family!]! @field(resolver: "FamilyQuery@all")
    family(id: ID @eq): Family @find
}

```

in playground doesn't find the class FamilyQuery. I have GraphQL/Queries folder inside App and FamilyQuery inside Queries, I also cleared cache to make sure but nothing happens.

Error in playground:

"error": {
    "message": "No class 'FamilyQuery' was found for directive 'field'",

I am using Lighthouse latest version.

**Comment by BenHeimberg** [comment]
Please refer to https://lighthouse-php.com/4.12/api-reference/directives.html#field, as the `@field` directive's `resolver` argument expects the full namespace of the class.

**Comment by M-P-programing** [comment]
In the example literally says "If your field is defined on the root types Query or Mutation, you can take advantage of the default namespaces that are defined in the configuration. The following will look for a class in App\GraphQL\Queries by default."  

which is where I have defined my FamilyQuery class and I checked my lighthouse.php and I have 'queries'       => 'App\\GraphQL\\Queries', which is also correct.

**Comment by BenHeimberg** [comment]
It will look for a class named by the name of the query, in your example `FamiliesQuery` **if you remove the directive.**

**Comment by lorado** [comment]
so the simplest solution would be to simply remove `@field` directive, as @BenHeimberg says. So for you field `families` in type `Query`, lighthouse will look for class `App\Graphql\Queries\Families`.

But you mention it right,  `@field` docs should also work. What is in your `config('lighthouse.namespaces.queries')`? Try to execute it/configure. Take a look at default lighthouse configuration file

**Comment by M-P-programing** [comment]
@lorado I have this in my config:
```
'namespaces'                 => [
    'models'        => [
      'App',
      'App\\Models\\Ranges',
      'App\\Models',
      'App\\Models\\Families',
      'App\\Models\\Systems',
    ],
    'queries'       => 'App\\GraphQL\\Queries',
    'mutations'     => 'App\\GraphQL\\Mutations',
    'subscriptions' => 'App\\GraphQL\\Subscriptions',
    'interfaces'    => 'App\\GraphQL\\Interfaces',
    'unions'        => 'App\\GraphQL\\Unions',
    'scalars'       => 'App\\GraphQL\\Scalars',
    'directives'    => ['App\\GraphQL\\Directives'],
  ],
```
Another thing that was strange to me was the models which I have to define each folder inside Models so it works but at least it works.

My family query is in:
App
|--GrapQL
   |--Queries
      |--FamilyQuery.php

So, accordingly to docs it should actually work I also tried @BenHeimberg approach with full namespace of the class but still get the error.

**Comment by spawnia** [comment]
> "error": {
"message": "Cannot declare class App\GrahpQL\Queries\FamilyQuery, because the name is already
> class App\GrahpQL\Queries\FamilyQuery
> GrahpQL

:thinking:

**Comment by M-P-programing** [comment]
@spawnia weird right? I only have one file there so I am not declaring any other class with that name anywhere...

**Comment by spawnia** [comment]
You have a typo in there, i thought that would be obvious.

**Comment by M-P-programing** [comment]
Well maybe obvious to you but not to me...

**Comment by M-P-programing** [comment]
By the way it wasn't a typo problem as you mentioned @spawnia somehow if you create the file manually doesn't work, after I used the command php artisan lighthouse:query FamilyQuery it works and the the only thing that changes beetween files is the _invoke function which I didn't have in the file I created manually...

**Comment by spawnia** [comment]
I see. The process by which Lighthouse finds default resolvers is described in https://lighthouse-php.com/master/the-basics/fields.html
