### ISSUE TITLE
Class 'Nuwave\Lighthouse\WhereConstraints\WhereConstraintsServiceProvider' not found

### ISSUE THREAD

**Issue by jcorpuz1999** [nuwave/lighthouse#1378]
Laravel Version : 5.7

I cant composer update due to this error, i google the error but no solutions found
![Screen Shot 2020-05-24 at 11 33 48 AM](https://user-images.githubusercontent.com/43026362/82745085-d0bce000-9db2-11ea-8956-5073ca136fa5.png)

**Comment by spawnia** [comment]
Remove the class from your `config/app.php`. In the process of stabilizing that experimental feature, we renamed it to `@whereConditions` and include it by default.
