### ISSUE TITLE
Null data on subscription

### ISSUE THREAD

**Issue by vaimeo** [nuwave/lighthouse#1379]
I have a simple subscription 

**Schema**

    type Mutation {
    insertMessage(
            text: String!
            image: String!
            audio: String!
            user_id: Int!
            channel_id: Int!
    ): Message @create 
    @broadcast(subscription: "messageInserted" , shouldQueue: false)
             }

      type Subscription {
        messageInserted(channel_id: Int!): Message @subscription(class: 
       "App\\GraphQL\\Subscriptions\\MessageInserted")
         }

**Expected behavior/Solution**

When i call mutation

![image](https://user-images.githubusercontent.com/3579069/82766085-0bfbf500-9e2d-11ea-9084-169e5e4a0eb8.png)
 

When i test subscription in graphiQL it should listen wait until data is available but it returns null as below

![image](https://user-images.githubusercontent.com/3579069/82766057-dfe07400-9e2c-11ea-82fa-8d17adfc0243.png)

**Lighthouse Version 4.12**

Thanks in advance please let me know whats wrong with my code

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by SirLamer** [comment]
I am troubleshooting this same issue. It only is a problem if GraphQL broadcast events are queued. If they are run on the main processed (not queued) it returns the expected data.

I'm using https://github.com/thekonz/lighthouse-redis-broadcaster
