### ISSUE TITLE
Related with same names returns null [Bug?]

### ISSUE THREAD

**Issue by BlackMix** [nuwave/lighthouse#138]
Hi. 
First I would like to say that I really enjoyed the project :)

I do not know this is a bug, but it seems that yes, when we put to list a post and if we want to list a related post to it with names of equal fields returns null, but when we change the names "prefix" it returns

Images about: https://imgur.com/a/kkBOAHs

I could change their name, but I do not know if this is a bug, so I'm asking and showing them.

**Comment by BlackMix** [comment]
```php
type OtherSeason {
  title: String
  slug: Slug @belongsTo
  images: Images @belongsTo
  cat: Category @belongsTo(relation: "category")
}
```
well, it fixed with tag: relation in category.. but why cant use same names?
never had this problem with eloquent, hmm.

**Comment by spawnia** [comment]
Anyways, if the relation is not explicitely set, it defaults to the name of the field. So in your case, it would look for a relation called `cat` (unless you set it to `category` as in your second example.

This distinction is made to enable giving semantic names to fields, for example:
````graphql
type Post {
  title: String
  author: User @belongsTo(relation: "user")
}
````

I hope that resolves your issue. If not, feel free to post the faulty schema definition.

**Comment by BlackMix** [comment]
@spawnia I showed in the first post what is happening

**Comment by spawnia** [comment]
Oh, i did not see that third image - my bad.

Actually, it seems like the first example should work fine. Take a look at `BelongsToDirective.php` to see what is going on under the hood, maybe try adding a debug statement to check if the value of `$relation` changes between your first and second example.

**Comment by kikoseijo** [comment]
Hi @BlackMix 

Can you post the Category schema?
Is there a category category?

**Comment by BlackMix** [comment]
Hi @kikoseijo 

```php
type Category {
  id: ID!
  category: String!
  name: String!
  type: String!
  type_name: String!
  active: Int!
}
```

I'm going to take a deeper look shortly, I'm redoing all my table relationships more clearly with GraphQL, I really liked it

**Comment by kikoseijo** [comment]
@BlackMix 

try with this: I think your Category its anti-pattern

```graphql
type Category {
  id: ID!
  sub_category: String! # problem could be here.
  name: String!
  type: String!
  type_name: String!
  active: Int!
}
```

Or,  make the query without the` category { category` , use `category { name`, 

This library its very young, could be a bug, or you, twisting the curve,  further investigations will be welcome, :-P

Best part its that you found a fix by using directives...

**Comment by BlackMix** [comment]
with elloquent work fine like:

```php
Serie::with([
            'images', 
            'category',
            'previous:id,title,category',
            'next:id,title,category',
            'genres'
        ])->find($id);
```

next amd previous is some season from this serie, and with relations in same table..
then I'll take a closer look at this.

**Comment by kikoseijo** [comment]
I can imagine you doing all in the magic, I mean, you letting lighthouse to build your eloquent.

Why don't you try to build the query using a resolver and provide your eloquent results.

I wonder where the problem its:

- lighthouse level on eloquent, 
- lighthouse level on schema builder,
- webonyx/graphql-php resolving the data needed for request. 


...

**Comment by BlackMix** [comment]
@kikoseijo 
I've just shown the eloquent example, I'm not using it, it would be more interesting using the maximum of the Lighthouse, so I'm here, at least everything is working, I get a list of series with several genres, categories, images without problems, only I wanted to show this part myself :)
