### ISSUE TITLE
Schema not updating after DB Reconnection

### ISSUE THREAD

**Issue by locent217** [nuwave/lighthouse#1381]
Schema is not updating after I change DB or using DB::reconnect(). I am using a mutation custom resolver to change DB. After reconnecting, the mutation itself throws the right data but when I switch to other mutation it is still connected to the previous DB and is throwing data from previous DB. 

I have this SelectDatabase.php custom resolver:
```
<?php

namespace App\GraphQL\Mutations;

use GraphQL\Type\Definition\ResolveInfo;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use App\Helpers\DatabaseConnection;

class SelectDatabase
{
    /**
     * Return a value for the field.
     *
     * @param  null  $rootValue Usually contains the result returned from the parent field. In this case, it is always `null`.
     * @param  mixed[]  $args The arguments that were passed into the field.
     * @param  \Nuwave\Lighthouse\Support\Contracts\GraphQLContext  $context Arbitrary data that is shared between all fields of a single query.
     * @param  \GraphQL\Type\Definition\ResolveInfo  $resolveInfo Information about the query itself, such as the execution state, the field name, path to the field from the root, and more.
     * @return mixed
     */
    public function __invoke($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
        // TODO implement the resolver
        $connection = DatabaseConnection::setConnection($args["db_name"]);
        return $connection;
    }
}

```

The DatabaseConnection.php for reconnecting:
```
<?php

namespace App\Helpers;
use App\StaffMember;
use Config;
use DB;

class DatabaseConnection
{

    public static function setConnection($params){
        Config::set('database.connections.mysql.database', $params);
        DB::purge('mysql');
        DB::reconnect('mysql');
        return StaffMember::all();
    }
}
```

Ofcourse it is added on the Schema file, after running it on graphiql app it throws the data from the reconnected DB because the DB that it reconnected has 5 StaffMembers and the previous one has four.

I dont know how to refresh all of the schema content to have values from the new connected DB.

**Comment by spawnia** [comment]
That issue does not seem specific to Lighthouse at all. Consider that PHP shares nothing between request, so you have to use mechanisms like caches or the file system.
