### ISSUE TITLE
Node [Blah] can only have one directive of type [Nuwave\\Lighthouse\\Support\\Contracts\\FieldResolver] but found []

### ISSUE THREAD

**Issue by ElvenSpellmaker** [nuwave/lighthouse#1382]
https://github.com/nuwave/lighthouse/blob/d035d7a8e0bb0c4593c223ad1ccc36e4d5faa2b2/src/Schema/Factories/DirectiveFactory.php#L199

It seems this line isn't working I get the following error message:
> Node [Blah] can only have one directive of type [Nuwave\\Lighthouse\\Support\\Contracts\\FieldResolver] but found []

It should be showing the resolvers that it finds rather than an empty array?

**Comment by ElvenSpellmaker** [comment]
(BTW I'm trying to use two resolvers but you can't do that with lighthouse, I'm not sure of the best way around this)

I'd like to use the `@create` resolver, _and_ then do something with the output before returning (log the user in).

**Comment by lorado** [comment]
Dunno why your error comes, but for your described task you can create a custom `FieldMiddleware` directive, [mentioned here in docs](https://lighthouse-php.com/master/custom-directives/field-directives.html#fieldmiddleware)

Take a look at some builtin directives, that implement defined contract (e.g. `CanDirective`). You can execute your custom code before or after field resolving.

**Comment by lorado** [comment]
And I mean this is not possible at all, to use multiple resolvers in graphql? It makes to me no sense... therefore there are middleware directives

**Comment by ElvenSpellmaker** [comment]
Hey, I'll take a look at the `FieldMiddleware`, thanks!

The bug is an odd one because it should list the classes that are found but doesn't!

**Comment by spawnia** [comment]
Thanks for the report, fixed the message.
