### ISSUE TITLE
Schema cache not working

### ISSUE THREAD

**Issue by tushar-inno** [nuwave/lighthouse#1389]
**Describe the bug**
When I set true for cache schema in lighthouse.php file. After updating some changes in my code when I try to deploy new code. It still uses cache schema but not updated. Not even working use of **php artisan lighthouse:clear-cache**

**Expected behavior/Solution**

```
When I run php artisan lighthouse:clear-cache it needs to clear cache and again store as cache
```

</details></br>

**Lighthouse Version**
4.13.0

**Comment by spawnia** [comment]
Please list the exact steps you are doing.

**Comment by tushar-inno** [comment]
Thanks for the quick reply.

Below is my lighthouse.php file:
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Route Configuration
    |--------------------------------------------------------------------------
    |
    | Controls the HTTP route that your GraphQL server responds to.
    | You may set `route` => false, to disable the default route
    | registration and take full control.
    |
    */

    'route' => [
        /*
         * The URI the endpoint responds to, e.g. mydomain.com/graphql.
         */
        'uri' => '/endpoint',

        /*
         * Lighthouse creates a named route for convenient URL generation and redirects.
         */
        'name' => 'endpoint',

        /*
         *
         * Beware that middleware defined here runs before the GraphQL execution phase,
         * so you have to take extra care to return spec-compliant error responses.
         * To apply middleware on a field level, use the @middleware directive.
         */
        'middleware' => [
            "api",
            \Nuwave\Lighthouse\Support\Http\Middleware\AcceptJson::class,
        ],

        /*
         * The `prefix` and `domain` configuration options are optional.
         */
        //'prefix' => '',
        //'domain' => '',
    ],

    /*
    |--------------------------------------------------------------------------
    | Schema Location
    |--------------------------------------------------------------------------
    |
    | This is a path that points to where your GraphQL schema is located
    | relative to the app path. You should define your entire GraphQL
    | schema in this file (additional files may be imported).
    |
    */

    'schema' => [
        'register' => base_path('graphql/schema.graphql'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Schema Cache
    |--------------------------------------------------------------------------
    |
    | A large part of schema generation consists of parsing and AST manipulation.
    | This operation is very expensive, so it is highly recommended to enable
    | caching of the final schema to optimize performance of large schemas.
    |
    */

    'cache' => [
        'enable' => env('LIGHTHOUSE_CACHE_ENABLE', false), //env('APP_ENV') !== 'local'
        'key' => env('LIGHTHOUSE_CACHE_KEY', 'lighthouse-schema'),
        'ttl' => env('LIGHTHOUSE_CACHE_TTL', null),
    ],

    /*
    |--------------------------------------------------------------------------
    | Namespaces
    |--------------------------------------------------------------------------
    |
    | These are the default namespaces where Lighthouse looks for classes to
    | extend functionality of the schema. You may pass in either a string
    | or an array, they are tried in order and the first match is used.
    |
    */

    'namespaces' => [
        'models' => [
            'App',
            'App\\Models'
        ],
        'queries' => \App\GraphQL\Queries\QueryHelper::getAllNamespaces(),
        'mutations' => \App\GraphQL\Mutations\MutationHelper::getAllNamespaces(),
        'subscriptions' => 'App\\GraphQL\\Subscriptions',
        'interfaces' => 'App\\GraphQL\\Interfaces',
        'unions' => 'App\\GraphQL\\Unions',
        'scalars' => 'App\\GraphQL\\Scalars',
        'directives' => ['App\\GraphQL\\Directives'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Security
    |--------------------------------------------------------------------------
    |
    | Control how Lighthouse handles security related query validation.
    | Read more at http://webonyx.github.io/graphql-php/security/
    |
    */

    'security' => [
        'max_query_complexity' => \GraphQL\Validator\Rules\QueryComplexity::DISABLED,
        'max_query_depth' => \GraphQL\Validator\Rules\QueryDepth::DISABLED,
        'disable_introspection' => \GraphQL\Validator\Rules\DisableIntrospection::DISABLED,
    ],

    /*
    |--------------------------------------------------------------------------
    | Pagination
    |--------------------------------------------------------------------------
    |
    | Limits the maximum "count" that users may pass as an argument
    | to fields that are paginated with the @paginate directive.
    | A setting of "null" means the count is unrestricted.
    |
    */

    'paginate_max_count' => null,

    /*
    |--------------------------------------------------------------------------
    | Pagination Amount Argument
    |--------------------------------------------------------------------------
    |
    | Set the name to use for the generated argument on paginated fields
    | that controls how many results are returned.
    |
    | DEPRECATED This setting will be removed in v5.
    |
    */

    'pagination_amount_argument' => 'first',

    /*
    |--------------------------------------------------------------------------
    | @orderBy input name
    |--------------------------------------------------------------------------
    |
    | Set the name to use for the generated argument on the
    | OrderByClause used for the @orderBy directive.
    |
    | DEPRECATED This setting will be removed in v5.
    |
    */

    'orderBy' => 'field',

    /*
    |--------------------------------------------------------------------------
    | Debug
    |--------------------------------------------------------------------------
    |
    | Control the debug level as described in http://webonyx.github.io/graphql-php/error-handling/
    | Debugging is only applied if the global Laravel debug config is set to true.
    |
    */

    'debug' => \GraphQL\Error\Debug::INCLUDE_DEBUG_MESSAGE | \GraphQL\Error\Debug::INCLUDE_TRACE,

    /*
    |--------------------------------------------------------------------------
    | Error Handlers
    |--------------------------------------------------------------------------
    |
    | Register error handlers that receive the Errors that occur during execution
    | and handle them. You may use this to log, filter or format the errors.
    | The classes must implement \Nuwave\Lighthouse\Execution\ErrorHandler
    |
    */

    'error_handlers' => [
        \Nuwave\Lighthouse\Execution\ExtensionErrorHandler::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Global ID
    |--------------------------------------------------------------------------
    |
    | The name that is used for the global id field on the Node interface.
    | When creating a Relay compliant server, this must be named "id".
    |
    */

    'global_id_field' => 'id',

    /*
    |--------------------------------------------------------------------------
    | Batched Queries
    |--------------------------------------------------------------------------
    |
    | GraphQL query batching means sending multiple queries to the server in one request,
    | You may set this flag to either process or deny batched queries.
    |
    */

    'batched_queries' => true,

    /*
    |--------------------------------------------------------------------------
    | Transactional Mutations
    |--------------------------------------------------------------------------
    |
    | If set to true, mutations such as @create or @update will be
    | wrapped in a transaction to ensure atomicity.
    |
    */

    'transactional_mutations' => true,

    /*
    |--------------------------------------------------------------------------
    | Batchload Relations
    |--------------------------------------------------------------------------
    |
    | If set to true, relations marked with directives like @hasMany or @belongsTo
    | will be optimized by combining the queries through the BatchLoader.
    |
    */

    'batchload_relations' => true,

    /*
    |--------------------------------------------------------------------------
    | GraphQL Subscriptions
    |--------------------------------------------------------------------------
    |
    | Here you can define GraphQL subscription "broadcasters" and "storage" drivers
    | as well their required configuration options.
    |
    */

    'subscriptions' => [
        /*
         * Determines if broadcasts should be queued by default.
         */
        'queue_broadcasts' => env('LIGHTHOUSE_QUEUE_BROADCASTS', true),

        /*
         * Default subscription storage.
         *
         * Any Laravel supported cache driver options are available here.
         */
        'storage' => env('LIGHTHOUSE_SUBSCRIPTION_STORAGE', 'redis'),

        /*
         * Default subscription broadcaster.
         */
        'broadcaster' => env('LIGHTHOUSE_BROADCASTER', 'pusher'),

        /*
         * Subscription broadcasting drivers with config options.
         */
        'broadcasters' => [
            'log' => [
                'driver' => 'log',
            ],
            'pusher' => [
                'driver' => 'pusher',
                'routes' => \Nuwave\Lighthouse\Subscriptions\SubscriptionRouter::class . '@pusher',
                'connection' => 'pusher',
            ],
        ],
    ],

];
`

When I put code as below is working fine:

    'cache' => [
        'enable' => env('LIGHTHOUSE_CACHE_ENABLE', false), //env('APP_ENV') !== 'local'
        'key' => env('LIGHTHOUSE_CACHE_KEY', 'lighthouse-schema'),
        'ttl' => env('LIGHTHOUSE_CACHE_TTL', null),
    ],

But when I change code to enable cache as mentioned code below:
    'cache' => [
        'enable' => env('LIGHTHOUSE_CACHE_ENABLE', env('APP_ENV') !== 'local'),
        'key' => env('LIGHTHOUSE_CACHE_KEY', 'lighthouse-schema'),
        'ttl' => env('LIGHTHOUSE_CACHE_TTL', null),
    ],

And When I change the schema.graphql file and try to delpoy code it won't reflect changes that I did in schema.graphql file.

**Comment by spawnia** [comment]
How are you clearing the cache on your production server?

**Comment by tushar-inno** [comment]
Running below comment using CI/CD to the production server.

`php artisan lighthouse:clear-cache`

**Comment by spawnia** [comment]
That does seem like it should work.

Can you dig in to what actually happens with the cache? Here you can find the actual code in Lighthouse that deals with it: https://github.com/nuwave/lighthouse/blob/7dae89a80891290e453e184bd32b24955c1a7ab2/src/Schema/AST/ASTBuilder.php#L96

Depending on what cache you are using, you can check if the command actually removes the cache entry.

**Comment by tushar-inno** [comment]
Let me check and debug the code.
And I am using default `CACHE_DRIVER=file` in production server

**Comment by tushar-inno** [comment]
When I tried below code:

`public function documentAST(): DocumentAST
    {
        if ( isset($this->documentAST) ) {
            return $this->documentAST;
        }

        $cacheConfig = $this->configRepository->get('lighthouse.cache');
        info($cacheConfig);
        if ( $cacheConfig['enable'] ) {
            /** @var \Illuminate\Contracts\Cache\Repository $cache */
            $cache = app('cache');
            $this->documentAST = $cache->remember(
                $cacheConfig['key'],
                // TODO remove this fallback in v5
                $cacheConfig['ttl'] ?? null,
                function (): DocumentAST {
                    return $this->build();
                }
            );
        } else {
            $this->documentAST = $this->build();
        }

        $cache = app('cache');
        info(json_encode($cache->get("lighthouse-schema")));
      
        return $this->documentAST;
    }`

It gives me below output log
[2020-05-29 15:47:52] local.INFO: array (
  'enable' => true,
  'key' => 'lighthouse-schema',
  'ttl' => NULL,
)  
[2020-05-29 15:47:52] local.INFO: {"types":{},"typeExtensions":[],"directives":{}}

**Comment by tushar-inno** [comment]
I played little more with cache and I check as CACHE_DRIVER file is stored as a file in storage/framework/cache/data/c4/6c. But when I try to get only get [2020-05-29 15:47:52] local.INFO: {"types":{},"typeExtensions":[],"directives":{}}

**Comment by spawnia** [comment]
Does the artisan command actually delete that file?

**Comment by tushar-inno** [comment]
Yes,

When I run **php artisan lighthouse:clear-cache**, It will delete the cache file.

**Comment by spawnia** [comment]
Does `php artisan lighthouse:print-schema` reflect the changes?

**Comment by tushar-inno** [comment]
No, 

It won't reflect the changes. When the cache is enabled.

**Comment by robsontenorio** [comment]
I am facing same issue when deploy on production.

As i am using a docker build, this is my startup command:


```
CMD ["/bin/sh", "-c", ".docker/deploy.sh && /usr/local/bin/start"] 
```
Here is my `deploy.sh`

```sh
#!/bin/sh
set -e

echo '------ Deploy tasks  ------'

php artisan key:generate
php artisan cache:clear
php artisan lighthouse:clear-cache
php artisan config:cache

echo '------ Done! ------'
```

It keeps previous schema instead new one.

But, on production console i execute again same command it does work. 

I was expecting it works through `deploy.sh`.

**Comment by robsontenorio** [comment]
Maybe are we runing a race condition?

https://laravel.com/docs/7.x/cache#managing-locks

**Comment by robsontenorio** [comment]
Ok, i am really suspecting on race condition. I am using redis driver for web sessions too. 

So on  deploing my script runs `php artisan cache:clear`, so all keys related to user session are cleared.

I can confirm it throgh
```
redis-cli
select 1
keys *
```

Just added a double command. But i think it won't ensure issue will be solved. 
```
php artisan lighthouse:clear-cache
php artisan lighthouse:clear-cache
```

**Comment by spawnia** [comment]
@tushar-inno are you sure that `php artisan lighthouse:print-schema` actually gives you an old schema? That would be quite weird, since it clears the cache itself https://github.com/nuwave/lighthouse/blob/b0d1766036da6a54b3ffaaa5d72b87f2519e61c8/src/Console/PrintSchemaCommand.php#L41-L42

**Comment by spawnia** [comment]
What could we possibly change within Lighthouse? We only interact with the cache once through the single call to `$cache->remember()`, is that too simplistic?

**Comment by tushar-inno** [comment]
`php artisan lighthouse:print-schema` it gives me the updated schema

**Comment by tushar-inno** [comment]
What I found is $cache-remember() function return value is not equal to $this->build().
Is it because of the cache driver? I have tried Redis driver too. But not working.

**Comment by tushar-inno** [comment]
Is it because of schema size is about 10 MB?

**Comment by robsontenorio** [comment]
Ok, a think my issue is related to docker containers. 

When deploying a new app there is a timeout for health check to determine if it should replace previous version deployed. 

So, my scripts already cleared the cache, but previous app still handle request, before the new one replaces it. What means a new schema was generated with previous codebase.

I will rethink the deployment strategy.

**Comment by tushar-inno** [comment]
@robsontenorio Is lighthouse cache working on your project?

**Comment by robsontenorio** [comment]
Yes. It was about concurrency between deploys. As I am using Openshift to manage containers deployment I have changed the deploy strategy.

**Comment by tushar-inno** [comment]
I am closing this issue as Cache is working using Redis driver now for me. But because of the huge schema, I am facing a performance issue.

@spawnia and @robsontenorio Thank you for the support

**Comment by tushar-inno** [comment]
@spawnia 
How to override below function using laravel?
https://github.com/nuwave/lighthouse/blob/7dae89a80891290e453e184bd32b24955c1a7ab2/src/Schema/AST/ASTBuilder.php#L90-L113

**Comment by spawnia** [comment]
You could extend the `ASTBuilder` and register your modified version as a replacement.

How would you like to change it? Maybe that will be beneficial for others, feel free to propose a PR.

**Comment by PJijin** [comment]
I have a similar issue. Any way to use CACHE_DRIVER as file and enable LIGHTHOUSE_CACHE_ENABLE . Works fine when I disable lighthouse cache.

**Comment by muhsinzyne** [comment]
> I have a similar issue. Any way to use CACHE_DRIVER as file and enable LIGHTHOUSE_CACHE_ENABLE . Works fine when I disable lighthouse cache.

enthaan cheyyandee ..? onnoode para.. production il pain kitti nikkaan :P

**Comment by swapneal-dev** [comment]
'cache' => [
    'enable' => env('LIGHTHOUSE_CACHE_ENABLE', false), //env('APP_ENV') !== 'local'
    'key' => env('LIGHTHOUSE_CACHE_KEY', 'lighthouse-schema'),
    'ttl' => env('LIGHTHOUSE_CACHE_TTL', null),
],

I had similar issue, This solved my problem
