### ISSUE TITLE
Rules run before ArgManipulator

### ISSUE THREAD

**Issue by Nohac** [nuwave/lighthouse#1391]
**Describe the bug**

This may or may not be a bug, but I thought I'd report it anyways.

It looks like the `manipulateArgDefinition` method in the `RulesDirective.php` is meant to throw an exception if the provided argument is not an array.
```php
public function manipulateArgDefinition(
    DocumentAST &$documentAST,
    InputValueDefinitionNode &$argDefinition,
    FieldDefinitionNode &$parentField,
    ObjectTypeDefinitionNode &$parentType
) {
    $rules = $this->directiveArgValue('apply');

    if (!is_array($rules)) {
        throw new DefinitionException(
            "The apply argument of @rules on has to be an array, got: {$rules}"
        );
    }
}
```

The problem I'm facing is that the `rules` method runs first, so I end up getting `Invalid argument supplied for foreach()` instead of `The apply argument of @rules on has to be an array, got: {$rules}`

**Expected behavior/Solution**

I'm expecting `manipulateArgDefinition` to throw an exception before `rules` run.

**Steps to reproduce**

Add a rule directive to a field without wrapping it in an array:
`@rules(apply: "not_an_array")`

**Lighthouse Version**
Tested with 4.10 and the newest version, 4.13.

**Comment by spawnia** [comment]
AST manipulation runs only once if schema caching is enabled. Try

	php artisan lighthouse:validate-schema

**Comment by Nohac** [comment]
You're right. Wasn't sure if it was a bug or not. Thanks for the quick reply.
