### ISSUE TITLE
Grouping exception

### ISSUE THREAD

**Issue by yormy** [nuwave/lighthouse#1397]
When I try to logically group my queries like this I get an exception that the resolver for Account is not found. How can I logically group queries ?

type Account {
  customer(id: ID): Customer
  order(id: ID): Order
}

type Retail {
  products: [Product]
}

type Query {
  account: Account
  retail: Retail
}

**Comment by spawnia** [comment]
Read about the basics.

https://lighthouse-php.com/master/the-basics/schema.html
