### ISSUE TITLE
Unable to get user authenticated by non-default guard

### ISSUE THREAD

**Issue by yh1224** [nuwave/lighthouse#1399]
I can get user from GraphQLContext when authenticated by default guard (specified by config/lighthouse.php), but cannot get user authenticated by other guard.

Because I'm using multiple guards for APIs, I want to get user for each guard.

ex)

```graphql
type Query {
    listUsers: [User!]! @guard(with: ["api"])
    listUsers2: [User!]! @guard(with: ["api2"])
}
```

**Lighthouse Version**

v4.13.1

**Comment by spawnia** [comment]
`@guard` does not log users in, it just checks if they are authenticated.

Authentication should happen on the request level through something like the `AttemptAuthentication` middleware. Consider that a user might query both of your fields in a single request.

**Comment by yh1224** [comment]
@spawnia Thanks for your answer.
I'm sorry for misundrstood.
