### ISSUE TITLE
Laravel validation required_without not working within lighthouse @rules directive.

### ISSUE THREAD

**Issue by madmages** [nuwave/lighthouse#1404]
**Describe the bug**
Got this in graphql schema
```
id: ID @rules(apply: ["required_without:input.positions.*.is_new"])
is_new: Boolean @rules(apply: ["required_without:input.positions.*.id"])
```
it should fail if one of this fields is omitted, but it`s fails always

**Expected behavior/Solution**
Lighthouse should provide rules to laravel validator with asterisk in field name  at this point 
https://github.com/nuwave/lighthouse/blob/793f412531275d5573265d9318321d0e76196ae7/src/LighthouseServiceProvider.php#L77
but array indexes are present.

If lighthouse provide array indexes insted of asterisks, laravel cant resolve what index of array should be validated at this point 
https://github.com/laravel/framework/blob/d3e486cc588ae4b30b3f3bfb49a5a455530849d6/src/Illuminate/Validation/Validator.php#L996

Laravel expects
`input.positions.*.id`
`input.positions.*.is_new`

Lighthouse provide
`input.positions.0.id`
`input.positions.0.is_new`

**Output/Logs**
<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**
v4.13.1

**Comment by spawnia** [comment]
The first step to resolve this issue is a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/ValidationTest.php

**Comment by madmages** [comment]
Reproduction https://github.com/nuwave/lighthouse/pull/1431

**Comment by spawnia** [comment]
Thanks for the report and the PR.

Turns out there is a reason why Lighthouse passes the concrete indices within validation rules, see https://github.com/nuwave/lighthouse/pull/1431/checks?check_run_id=773740551

https://github.com/nuwave/lighthouse/blob/50a6b714c40766ac308dc7e25d5b64291963ce3f/tests/Integration/ValidationTest.php#L103-L134

Looking for ideas how we can fix both, tricky one.

**Comment by madmages** [comment]
Seems to be issue of laravel validator.
just open issue of it https://github.com/laravel/framework/issues/33225

**Comment by spawnia** [comment]
We could try and split each nested level of input into it's own subtree and run validation separately.

That would solve both the issue of individual rules for diverging array paths and the reference of fields through `*`. Rules that reference other fields would only be able to see those that are on the same level, e.g.:

```graphql
type Query {
  field(
    # This will not work, since input has its own validation context
    id: ID @rules(apply: "required_with:input.new")
    # Nested inputs are where we split the args
    input: Input
    # Each input in the array gets its own context
    list: [Input]
  )
}

input Input {
  # This reference works, because Input is at the root of its validation context
  new: ID @rules(apply: "required_without:name")
  name: String
}
```

That probably comes with its own set of problems, but i think it is worth exploring. The constraints on field referencing might inconvience some that depend on complex references in multi-level input structures. On the other hand, having the references resolve locally makes them easier to work with and enables better reuse of input objects.

**Comment by MrJmpl3** [comment]
🤔 I think for that, the validation distincs in array don't works. But in custom directive validation, works.

**Comment by spawnia** [comment]
This issue was also recognized and framed more precisely in https://github.com/nuwave/lighthouse/issues/1404
