### ISSUE TITLE
unlink(~/weather.com/programmatic-types.graphql): No such file or directory

### ISSUE THREAD

**Issue by haxifang-aircos** [nuwave/lighthouse#1407]
我按照官方文档引入lighthourse后，执行命令 
php artisan lighthouse:ide-helper
抛出了标题那样的错误，请问有人遇到过这个问题吗？

**Comment by spawnia** [comment]
Can you post your question in English please?

**Comment by haxifang-aircos** [comment]
> Can you post your question in English please?

OK.My English is not good.I try to init lighthourse in owner project. 
Threw an error
![截屏2020-06-05下午4 22 59](https://user-images.githubusercontent.com/61681123/83854506-64929280-a749-11ea-94ad-40ddec8375ec.png)

**Comment by lorado** [comment]
Google translater says:

> After introducing lighthourse according to the official document, execute the command
php artisan lighthouse:ide-helper
An error like the title is thrown. Has anyone encountered this problem?

I guess we have to check, if file exists or not in `IdeHelperComman` line 171

**Comment by lorado** [comment]
@spawnia wanna fix? :D

```php
if (file_exists($filePath)) {
    unlink($filePath);
}
```

**Comment by haxifang-aircos** [comment]
> @spawnia wanna fix? :D
> https://github.com/nuwave/lighthouse/blob/853f89aaddb1bb02a11aab446ae0f2b4c4020ed5/src/Console/IdeHelperCommand.php#L170
> 
> to this one
> 
> ```
> if (file_exists($filePath)) {
>     unlink($filePath);
> }
> ```

hi, I found no such file. Where did this file come from?

![image](https://user-images.githubusercontent.com/61681123/83855688-0797dc00-a74b-11ea-9f80-32bc2b0b2392.png)

By the way, I found that when I successfully introduced it before, there was no 171 lines of code.

**Comment by lorado** [comment]
>hi, I found no such file. Where did this file come from?

this file is actually generated by the command you try to run (`lighthouse:ide-helper`). And if you have no programmatically registered types, the command tries to remove that helper file, which actually don't exist at all.

**Comment by haxifang-aircos** [comment]
> > hi, I found no such file. Where did this file come from?
> 
> this file is actually generated by the command you try to run (`lighthouse:ide-helper`). And if you have no programmatically registered types, the command tries to remove that helper file, which don't exist at all.

thank you very much!  :)

**Comment by spawnia** [comment]
Reopening because we can fix this.

**Comment by haxifang-aircos** [comment]
> Reopening because we can fix this.

ok, please help me : )

**Comment by haxifang-aircos** [comment]
> Reopening because we can fix this.

Looking forward to your reply

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v4.14.1

**Comment by haxifang-aircos** [comment]
> Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v4.14.1

thank you very much! 大拇指
