### ISSUE TITLE
how to do the following graphql query with nodes?

### ISSUE THREAD

**Issue by tonipepperoni** [nuwave/lighthouse#141]
Hi everyone, I'm trying to implement the following query with connection type

`query Beacons {
  beacons {
    nodes {
      id
      name
      description
      identity_key
    }
  }
}`

How is this possible with lighthouse?

**Comment by spawnia** [comment]
Hi! Can you please post your question in Slack instead? https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWI1ZDQ1YWM1NmM2MmQ0NTU0NGNjZWFkMTJhY2VjMDAwZmMyZDFlZTc1Mjc3ZGY0MWM1Y2Q5MWNjYmJmYWJkYmU

**Comment by spawnia** [comment]
@tonipepperoni If your question is answered, can you please close the Issue?

**Comment by tonipepperoni** [comment]
@spawnia thanks, will do.
