### ISSUE TITLE
Connecting relationship made simple

### ISSUE THREAD

**Issue by wolfiton** [nuwave/lighthouse#1414]
Hi everyone

Can we have both ways to define relationships?

$category: { connect: Int! }

and also $category: categoryID

Because i can't figure out how to use this in my vue apollo no matter how hard I try

Given the following example:

```js
mutation (
      $title: String!
      $image: String!
      $author: String!
      $description: String!
      $link: String!
      $featured: Boolean
      $category: { connect: Int! }
)
{
  createBook(
    input: {
      title: $title
      image: $image
      author: $author
      description: $description
      link: $link
      featured: $featured
      category: $category
    }
  ) {
    id
    title
    author
  }
}

```

And when defining my form data I can't find a reliable way to use this
```js
variables: {

        $category: { connect: this.categoryId },
      },
```

This doesn't work

So I would like to have the possibility to use this
```js
variables: {

        $category: this.categoryId,
      },
```

Thank you for looking over my request

**Comment by TeNNoX** [comment]
@spawnia Okay, it's not a bug that he didn't get it to work - but I still find the ticket relevant:

> Can we have both ways to define relationships?
> 
> `$category: { connect: Int! }`
> 
> and also `$category: categoryID`

Because it would result in a lot simpler schema in many cases
