### ISSUE TITLE
Soft deletes scope not applied on union all relation queries

### ISSUE THREAD

**Issue by bjornvoesten** [nuwave/lighthouse#1440]
**Describe the bug**

In our application we have some nested relations.

`Group` morphMany `Post` morphMany `Comment`.

The problem occurs when querying comments through posts and groups.

<details><summary>Click to expand queries</summary>

Shows the post and comments, excluding soft deleted comments, as expected:

```
query CommentsThroughPost {
  post(id: "") {
    id
    comments {
      data {
        id
      }
    }
  }
}
```

Shows no comment, as expected:

```
query Comment {
  comment(id: "") {
    id
  }
}
```

Shows the groups, posts and comments including soft deleted comments, which is not expected:

```
query CommentsThroughPostsThroughGroup {
  group(id: "") {
    id
    posts {
      data {
        id
        comments {
          data {
            id
          }
        }
      }
    }
  }
}
```

</details>

**Expected behavior/Solution**

See: https://github.com/nuwave/lighthouse/blob/a5f7dd3e9dde289d94e23ad3ee64c96a7713270e/src/Execution/DataLoader/ModelRelationFetcher.php#L216

In commit `a5f7dd3e9dde289d94e23ad3ee64c96a7713270e` the `$relation->getQuery` was changed to `$relation->getBaseQuery`. 

Changing this back fixed the problem for us.

**Steps to reproduce**

1. Create Group
2. Create Group Post
3. Create Post Comment
4. Create Group Post
5. Create Post Comment
6. Soft delete second Comment

**Output/Logs**

<details><summary>Click to expand</summary>

When using `Relation::getBaseQuery`  the query is as following:

```
[
    "query" => "(select * from "comments" where "comments"."commentable_id" in (?) and "comments"."commentable_type" = ? and "comments"."deleted_at" is null limit 15 offset 0) union all (select * from "comments" where "comments"."commentable_id" in (?) and "comments"."commentable_type" = ? limit 15 offset 0)"
    "bindings" => array:4 [
      0 => "23ffac51-6091-4864-9830-3f6aceee3587"
      1 => "Post"
      2 => "2278d01b-e0db-40c1-91da-0d3cfaa5d798"
      3 => "Post"
    ]
  ]
```

When using `Relation::getQuery`  the query is as following:

```
[
    "query" => "(select * from "comments" where "comments"."commentable_id" in (?) and "comments"."commentable_type" = ? and "comments"."deleted_at" is null limit 15 offset 0) union all (select * from "comments" where "comments"."commentable_id" in (?) and "comments"."commentable_type" = ? and "comments"."deleted_at" is null limit 15 offset 0)"
    "bindings" => array:4 [
      0 => "23ffac51-6091-4864-9830-3f6aceee3587"
      1 => "Post"
      2 => "2278d01b-e0db-40c1-91da-0d3cfaa5d798"
      3 => "Post"
    ]
  ]
```

</details></br>

**Lighthouse Version**

4.14.1

**Comment by spawnia** [comment]
Thanks for the detailed report, it was a great aid in implementing a proper test case. Your proposed fix did indeed work.
