### ISSUE TITLE
Unclear documentation for `defer extension`(enhancement)

### ISSUE THREAD

**Issue by wolfiton** [nuwave/lighthouse#1441]
Unclear documentation for `defer extension` and the external link lead to nowhere  or 404 [external link](https://www.apollographql.com/docs/react/features/defer-support.html)

The documentation link to [defer extension](https://lighthouse-php.com/3.1/extensions/deferred.html#deferred-fields)

Thank you in advance

**Comment by spawnia** [comment]
Feel free to provide a PR.
