### ISSUE TITLE
Can I use @paginate with custom resolver?

### ISSUE THREAD

**Issue by PheakOmi** [nuwave/lighthouse#1445]
My code:
`myPurchaseRequests: [PurchaseRequest!]!
    @paginate @field(resolver: "PurchaseRequestQuery@myPurchaseRequests")`

There is an error shows up when running this query:
> "Node [myPurchaseRequests] can only have one directive of type [Nuwave\\Lighthouse\\Support\\Contracts\\FieldResolver] but found []",

I know i could not use 2 directives here. So, i would like to know if there is a way to utilize the functionality of @paginate in situation like this?

PS: My custom resolver return just the collection ( E, g: PurchaseRequest::all() ) and I need to paginate these data the way @paginate does.

**Comment by spawnia** [comment]
Please follow the issue template.
