### ISSUE TITLE
Artisan command `lighthouse:ide-helper` is very slow

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1449]
Starting from https://github.com/nuwave/lighthouse/releases/tag/v4.14.0, running

    php artisan lighthouse:ide-helper

has become very slow. Some profiling should help to uncover what is taking so long.

**Comment by spawnia** [comment]
Trying https://www.christianroessler.net/tech/2015/php-xdebug-profile-single-cli-application-without-enabling-globally.html for starters, other options:

- https://github.com/NoiseByNorthwest/php-spx
- https://blackfire.io/docs/up-and-running/installation

**Comment by mathieu-bour** [comment]
What do you mean by "very slow"? In my project, it's something like two seconds for something like 50 queries, mutations and types.

**Comment by spawnia** [comment]
It takes about 2 minutes.

I am running in WSL2 with the project on a Windows filesystem, which probably explains the difference. The bottleneck definitely seems to be filesystem access.

We use `haydenpierce/class-finder` to look for schema directive classes. It accesses the filesystem a whole lot, probably more than necessary. See https://gitlab.com/hpierce1102/ClassFinder/-/issues/14.

**Comment by mathieu-bour** [comment]
I just remembered that I also had severe issues while exploring filesystem on WSL 2. I'll definitely join the discussion on ClassFinder.

**Comment by mathieu-bour** [comment]
@spawnia I cannot reproduce the slowness on WSL2, even with a "quite big" schema...
Could you detail your PHP setup and the slow schema?

**Comment by spawnia** [comment]
- WSL2 running Ubuntu 16.04
- Using docker-desktop
- Run PHP 7.3 inside a container
- Project is located within windows filesystem
- F-Secure antivirus is running, might have an impact?

Anyways, while profiling i found that `ClassFinder` generates a lot of filesystem accesses (functions such as `scandir`, `file_exists`, `file_get_contents`). The slowness in my system is definitely related to that, but I am sure it can be optimized.

**Comment by Jofairden** [comment]
If it is of any help, the command took me 16.22 seconds running in a Vagrant box, I have 1 schema, 41 types along with 1-2 queries per type and at least one enum (sometimes more). I setup my box to use NFS sync which should improve speed, I don't actually know if it does though.

**Comment by mathieu-bour** [comment]
Ok, I guess that my native setup PHP in WSL2 has definitely a perform impact. But is it really a problem? I mean, class finder can be optimized but I guess that the slowness is due to the setup itself.

**Comment by thekonz** [comment]
I am running on WSL 2 aswell. Any file system operation on `/mnt/c` is extremely slow and the official recommendation is to put your code in the linux file system.

see https://docs.docker.com/docker-for-windows/wsl/
> Store source code and other data that is bind-mounted into Linux containers 
> Performance is much higher when files are bind-mounted from the Linux filesystem

https://github.com/microsoft/WSL/issues/5622
https://github.com/microsoft/WSL/issues/4197
https://github.com/microsoft/WSL/issues/5079

I suggest closing this issue.

**Comment by spawnia** [comment]
@thekonz thanks, running from the linux file system is much faster indeed.

Agree with closing, will invest some time into https://gitlab.com/hpierce1102/ClassFinder/-/issues/14 though to get some speed ups. There are some optimizations to be had there.
