### ISSUE TITLE
@nest directive missing "on"

### ISSUE THREAD

**Issue by brunobg** [nuwave/lighthouse#1450]
**Describe the bug**

ide:helper generates an invalid graphql file. The bug is here:

```
# Directive class: Nuwave\Lighthouse\Schema\Directives\NestDirective
# Add a proper definition by implementing Nuwave\Lighthouse\Support\Contracts\DefinedDirective
directive @nest
```

Error: `Syntax Error: Expected "on", found BlockString`

**Expected behavior/Solution**

The correct on, as written in the docs:

```
# Directive class: Nuwave\Lighthouse\Schema\Directives\NestDirective
# Add a proper definition by implementing Nuwave\Lighthouse\Support\Contracts\DefinedDirective
directive @nest on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
```

**Lighthouse Version**

4.15

**Comment by spawnia** [comment]
Accepting PRs.

**Comment by brunobg** [comment]
I think https://github.com/webonyx/graphql-php/issues/719#event-3686943769 was the same bug and this was fixed by https://github.com/nuwave/lighthouse/commit/6009ed20ea87a523a29dcd4f79c1b8ec5a116356, so closing this.
