### ISSUE TITLE
Convert empty strings to null in multipart-form request 

### ISSUE THREAD

**Issue by lorado** [nuwave/lighthouse#1459]
**Describe the bug**

Dunno if it is a bug, but this was for me very unexpected, and it may be so to other people...

The situation: I have an input with a field of type `Float`. In my frontend I send by mistake an empty string. While I was sending a JSON request, everything worked fine. But when I add a file to the request, request becomes a `multipart-form` request, and then I got an error, that empty string can't be a float number, what is sure true. But I was really confused, because without file it works without a problem.

After long debugging I found out, that when request is sent as json, input gets sanitized by middleware `\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull`, that was there by default, after laravel installation. As the middleware name says, empty strings becomes null. So my empty string variable becomes value null (actually what I was expected from my frontend), and FloatType convertion happens without a problem (because the value is `null`)   

For a multipart-form request, middlewares are executed on whole GraphQL operation is encoded JSON, because decoding happens way later in `Nuwave\Lighthouse\Execution\MultipartFormRequest`. As result sent empty string stay an empty string, because after JSON decoding of `operations` values are not going through the request pipeline defined  in `App\Http\Kernel`. When FloatType then tries to parse float value, it throws an error, because an empty string is not a float number. 

For me that was very unexpected.

**Expected behavior/Solution**

So for me to solve the problem I actually have to disable that `\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull` middleware, because I don't need it at all. 

Anyway, I thought there might be other people, that could face same issue. The question is - should we mention it an docs, e.g. in installation as a note? Like "be aware of..." hint/advice?

**Comment by spawnia** [comment]
Just recently i also had an issue related to that middleware and disabled it.

I think usually it is included in Laravel's global middleware and used for the entire application. Can it be disabled only for Lighthouse?

**Comment by lorado** [comment]
Well as option we could provide our own `ConvertEmptyStringsToNull` implementation, that extends laravels one, and in `handle()` method we could check the `$request->pathinfo` equals `/graphql`. If so - simply return `$next($request)` so we ignore modifying of request, otherwise return `parent::handle($request, $next)`. In the installation guide we could write a note, that if user still need this middleware, he should remove laravels one, and include ours, as ours ignores `graphql` route.

**Comment by spawnia** [comment]
@lorado I don't like it, but it seems like our best option. The convencience features of Laravel really bite back sometimes, it is like we are fighting the framework to not get in our way.

**Comment by lorado** [comment]
Yes, it feels weird... But at the moment I guess there is no better solution. So... should I implement it?

**Comment by spawnia** [comment]
Yeah, why not.

> we could check the $request->pathinfo equals /graphql

That path is configurable, so we will have to take the config into account at least.
It seems like there should be a more idiomatic way, maybe we can utilize the fact that the `GraphQLController` will be called?

**Comment by lorado** [comment]
> maybe we can utilize the fact that the GraphQLController will be called
Good idea, got to check it, if it is possible. I will try it next week.

**Comment by ThisIsJustARandomGuy** [comment]
Is the route already known when the middleware runs? To me it would seem a better idea to check for the route name or, as spawnia suggested, the used controller instead of comparing the path. We use parameters (the locale) in the route (/{locale}/graphql) in one of our applications, so a simple `$request->pathinfo === config('lighthouse.route.uri')` would fail in our use case.

**Comment by spawnia** [comment]
> Is the route already known when the middleware runs?

Yes, but neither we nor a default Laravel install "own" the `ConvertEmptyStringsToNull` middleware.

Given that an ugly fix is better than no fix at all: How about we just add docs to the file upload section and mention that this middleware must either be disabled or modified to not run on GraphQL routes?

**Comment by pasloc** [comment]
I'm using lighthouse v5.0 with ConvertEmptyStringsToNull Middleware enabled (default config from laravel 8). I have a simple mutation request with a json body. No form request. But my empty strings stay empty and are not converted to null. The empty string is saved to the database even though the column is nullable. If I understood the original description my empty string should be converted to null, but that's not the case for me. I'll fix it in my frontend for now, but some lighthouse solution would be great.

**Comment by spawnia** [comment]
Depending on what kind of HTTP request is used to call GraphQL, the contents of variables as well as the values passed as part of the query string may be opaque to Laravel's middleware.

In order to still apply the `'' -> null` transformation in such cases, we can implement a global `FieldMiddleware` directive. Consider https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/TrimDirective.php, it is registered in `lighthouse.php` by default. We can add a similar implementation for a `ConvertEmptyStringsToNullDirective` and include that within `lighthouse.php`.

**Comment by pasloc** [comment]
In my case the request body contains the query string and a separate json with the variables.
```
{
query: "mutation .... ($myVar: String) ..."
variables: {
    myVar: ""
}
```

**Comment by spawnia** [comment]
@pasloc if this is a pressing issue for you, consider providing a pull request with an implementation as described in https://github.com/nuwave/lighthouse/issues/1459#issuecomment-765236571

**Comment by JoaoHamerski** [comment]
Any solution for this? The default Laravel behavior of converting empty strings to null would be great.

**Comment by JoaoHamerski** [comment]
Any solution for this?

**Comment by LastDragon-ru** [comment]
The main problem with empty strings:

> [By default](![image](https://user-images.githubusercontent.com/1329824/163776508-d0aefdf2-806b-4db3-b7ba-a36f53077007.png)), when an attribute being validated is not present or **contains an empty string**, normal validation rules, including custom rules, **are not run**.

![image](https://user-images.githubusercontent.com/1329824/163776777-bfd12449-3e2f-4d8f-b6b0-3f7a485eb16c.png)

So without `required` rule, the `` (empty string) will pass all checks - very unexpected compared with Laravel validation. 

Possible workaround: 

1. extend `TrimDirective` to return `null` if string empty 
2. add/set it into `config/lighthouse.php/field_middleware`

```php
<?php declare(strict_types = 1);

namespace App\GraphQL\Extensions\Lighthouse\Directives;

use Nuwave\Lighthouse\Schema\Directives\TrimDirective as LighthouseTrimDirective;

class TrimDirective extends LighthouseTrimDirective {
    protected function transformLeaf(mixed $value): mixed {
        $value = parent::transformLeaf($value);

        if ($value === '') {
            $value = null;
        }

        return $value;
    }
}
```

**Comment by spawnia** [comment]
> very unexpected compared with Laravel validation.

What do you consider unexpected, you just reiterated how Laravel validation works?

Your proposed extension of the `TrimDirective` seems to unnecessary conflate it with an unrelated concept. I typically propose composition over inheritance, and thus already proposed a solution for this in https://github.com/nuwave/lighthouse/issues/1459#issuecomment-765236571

**Comment by LastDragon-ru** [comment]
> What do you consider unexpected, you just reiterated how Laravel validation works?

1. Laravel out the box converts empty strings to `null` -> when we use `["string", "size:2"]` it will fail because value actually `null` 

```php
Validator::make(['value' => null], ['value' => ["string", "size:2"]])->passes(); // false
```

2. Lighthouse doesn't -> empty string will pass validation

```php
Validator::make(['value' => ''], ['value' => ["string", "size:2"]])->passes(); // true
```

```graphql
test(value: String @rules(apply: ["string", "size:2"])): String
@field(
    resolver: "App\\GraphQL\\Queries\\TestField"
)
```

```php
<?php declare(strict_types = 1);

namespace App\GraphQL\Queries;

class TestField {
    public function __invoke(mixed $root, array $args): ?string {
        return $args['value'] ?? '';
    }
}
```

> Your proposed extension of the TrimDirective seems to unnecessary conflate it with an unrelated concept.

And it is also will be inconsistent between json and other requests...

**Comment by spawnia** [comment]
Got it. Validation working different in that case is a symptom that follows from empty strings not being converted in all cases. I did describe a solution for this in https://github.com/nuwave/lighthouse/issues/1459#issuecomment-765236571, which will work regardless of the serialization format - and most importantly also for GraphQL string literals. Would you like to help in improving Lighthouse by providing a pull request?

**Comment by LastDragon-ru** [comment]
> Would you like to help in improving Lighthouse by providing a pull request?

I can try to create a new directive like `TrimDirective`, but not sure when, maybe after 1 or 2 weeks (I'm in a middle of https://github.com/LastDragon-ru/lara-asp/issues/18 ... I'm also remember about #2041 😅)

**Comment by LastDragon-ru** [comment]
@spawnia while testing I've found one very unwanted sideeffect - it is allows `null` where they are not expected :( 

One actual issue for us:  the query used `Scout`  builder before, but will not use it after the fix
```graphql
// Schema
search(search: String! @search): Model

// Query
search(search: "") { ... }
```

So on next week I will dig into laravel validation and will try to find a way to run validation for empty strings.

**Comment by spawnia** [comment]
@LastDragon-ru fixed with https://github.com/nuwave/lighthouse/releases/tag/v5.48.1

**Comment by LastDragon-ru** [comment]
> So on next week I will dig into laravel validation and will try to find a way to run validation for empty strings.

Seems there is only one good fix - patch the Validator to not ignore empty strings. 

```php
<?php declare(strict_types = 1);

namespace App\Utils\Validation;

use Illuminate\Support\Arr;
use Illuminate\Validation\Validator as IlluminateValidator;

use function is_string;
use function mb_strtolower;

/**
 * According to Laravel documentation:
 *
 * > By default, when an attribute being validated is not present or
 * > contains an empty string, normal validation rules, including
 * > custom rules, are not run
 *
 * The problems are:
 * 1. In GraphQL the empty string this is a valid value, and it is not possible
 *    to convert it to `null` safely, e.g. when `Type!` because it will allow
 *    `null` where it is unexpected; Without converting empty strings will pass
 *    all (non-explicit) validation rules;
 * 2. There is no way to allow `nullable|required` that is useful for GraphQL
 *    to avoid adding custom "required" rule;
 *
 * Differences with Laravel:
 * * Empty strings will be validated
 *      ```php
 *      Validator::make(['value' => ''], ['value' => ['size:2']])->passes();
 *          // `true` in Laravel
 *          // `false` in App
 *      ```
 * * Nullable + Required is allowed
 *      ```php
 *      Validator::make(['value' => null], ['value' => ['nullable', 'required']])->passes();
 *          // `false` in Laravel
 *          // `true` in App
 *      ```
 * * Validation will be stopped for `null` after `nullable` rule
 *
 * @see https://laravel.com/docs/validation#implicit-rules
 * @see https://github.com/nuwave/lighthouse/issues/1459#issuecomment-1102248865
 * @see Validator::presentOrRuleIsImplicit()
 */
class Validator extends IlluminateValidator {
    protected function presentOrRuleIsImplicit(mixed $rule, mixed $attribute, mixed $value): bool {
        // (1) Empty strings should process like non-empty
        return $this->validatePresent($attribute, $value)
            || $this->isImplicit($rule);
    }

    protected function shouldStopValidating(mixed $attribute): bool {
        // (2) If value is `null` and it is allowed, validation can be stopped.
        $value = Arr::get($this->data, $attribute, 0);
        $rule  = isset($this->currentRule) && is_string($this->currentRule)
            ? mb_strtolower($this->currentRule)
            : null;

        return parent::shouldStopValidating($attribute)
            || ($rule === 'nullable' && $value === null);
    }
}
```

```php
<?php declare(strict_types = 1);

namespace App\Providers;

use App\Utils\Validation\Validator;
use Illuminate\Contracts\Validation\Factory as ValidatorFactoryContract;
use Illuminate\Contracts\Validation\Validator as ValidatorContract;
use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\Factory as ValidatorFactory;

use function func_get_args;

class AppServiceProvider extends ServiceProvider {
    /**
     * Register any application services.
     */
    public function register(): void {
        $this->registerValidator();
    }

    protected function registerValidator(): void {
        $this->app->afterResolving(
            ValidatorFactoryContract::class,
            static function (ValidatorFactoryContract $factory): void {
                if ($factory instanceof ValidatorFactory) {
                    $factory->resolver(static function (): ValidatorContract {
                        return new Validator(...func_get_args());
                    });
                }
            },
        );
    }
}
```

**Comment by baonguyen212002** [comment]
```
query userAttendanceStatistics($dateRange: DateRange, $userId: ID, $blockType: AttendanceBlockType) {
  userAttendanceStatistics(
    dateRange: $dateRange
    userId: $userId
    blockType: $blockType
  ) {
    user {
      id
      name
      avatar
      position
      name
      nickname
      email
      phone
      __typename
    }
    checkin
    checkout
    totalWorkingHours
    status
    __typename
  }
}
============
Variables:

{
  "dateRange": {
    "from": "2024-10-25",
    "to": "2024-10-25"
  },
  "userId": "9",
  "blockType": ""
}
==
response:

{
  "errors": [
    {
      "message": "Variable \"$blockType\" got invalid value (empty string); Expected type AttendanceBlockType.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 68
        }
      ]
    }
  ]
}
```
