### ISSUE TITLE
Bug using enum type as column in @whereConditions

### ISSUE THREAD

**Issue by faiverson** [nuwave/lighthouse#1460]
When we have the follow schema example:
```graphql
type User {
        id: ID!
        name: String
        email: String
        hair_color: HairColorEnum!
    }

    type Query {
        users(
            where: _ @whereConditions(columnsEnum: "UserColumn")
        ): [User!]! @all
    }

    enum UserColumn {
        ID @enum(value: "id")
        NAME @enum(value: "name")
        HAIR @enum(value: "hair_color")
    }

    enum HairColorEnum {
        RED @enum(value: 0)
        BROWN @enum(value: 1)
        BLONDE @enum(value: 2)
    }
```

If we want to make a filter using @whereConditions like this, it is not going to find any value:
```graphql
users(
    where: {
        AND: [
            {
                column: HAIR
                operator: IN
                value: ["BLONDE", "WHITE"]
            }
        ]
    }
) {
    id
    hair_color
}
```

It is not casting the enum type, in order to make it work we need to do instead:
```graphql
{
  column: HAIR
  operator: IN
  value: [0, 1]
 }
```

Is this the correct behaviour? 
Since these conditions are made in the client side, I'd expect to use the enum type in order to keep the abstraction away from the client. Am I wrong?
It would be great if @whereConditions checks if the column is a enum type in GQL and parse the right value in the query builder.

A test example in this [fork](https://github.com/faiverson/lighthouse/commit/33d35b01c8cbc7a6725ac5962037fd0001a55849)

**Comment by faiverson** [comment]
No comments on this? Is it not clear enough?

**Comment by spawnia** [comment]
I understand what you are trying to do and it would be nice if the definition in `type User` somehow carried over to the used input, but that would involve a lot of guesswork. Lighthouse can not magically know that you meant to pass instances of your Enum. All it sees is that `value` can be any type, and you passed a bunch of strings.

The type of the `value` argument can be anything in the general case. Polymorphic inputs are not really possible in GraphQL. "a fix" would involve solving that first. If you are interested, you can dive right in to the RFC, going on for a few years now, meant to add input unions: https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md

Conceptually, it might be possible to make the type of `value` dependent on the value of `column`. Such ideas have been forming in research languages such as Agda, it's called dependent typing. Fascinating subject, but GraphQL and PHP are lightyears away from it.

So, a fully type safe solution is not really possible with pure GraphQL semantics. Next best thing would be to have runtime checks. I don't quite see how we could generalize that, i would wager there are a lot of tricky edge cases and pitfalls of complexity to solve. A good starting point might be to handwrite a bunch of handlers for such inputs and look for commonalitities.

If you want to stay typesafe, you can go with a simple `@eq`.

**Comment by faiverson** [comment]
What a quality answer! 
My solution then it is going to be create a new directive extending @whereConditions adding a new argument "enum" with an array of enum type. If the column involved is in the array I get the value from an Enum objec  (something like that).
Thanks for the reply!
