### ISSUE TITLE
buildKey function affecting Eloquent relationships

### ISSUE THREAD

**Issue by mentamarindos** [nuwave/lighthouse#1469]
**Describe the bug**

I struggle for two days  trying to figure out why my query with the relationships  `@hasOne` `@belongsTo` wasn't working for me, and after looking into the source code I found [THIS](https://github.com/nuwave/lighthouse/blob/master/src/Execution/DataLoader/BatchLoader.php#L145) function `buildKey()` in the `BatchLoader.php` file that has the description: `Build a key out of one or more given keys, supporting composite keys.` which receives the parameter `$key`, so the problem (in my case) is that this `$key` variable is always `NULL` so I change it to:

**Edited:**
```
protected function buildKey($key): string
    {
        return true;
    }
```
**Original:**
```
protected function buildKey($key): string
    {
        return is_array($key) ? implode('___', $key) : $key;
    }
```

and Voilà, now my query works perfectly :D

**The question is why?**
because it's still not entirely clear to me how that actually works, could you please explain? maybe I'm doing it wrong and haven't noticed. Thank you ♥

---
Lighthouse Version
```
"require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "firebase/php-jwt": "^5.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "mll-lab/graphql-php-scalars": "^3.1",
        "mll-lab/laravel-graphql-playground": "^2.1",
        "nuwave/lighthouse": "^4.14"
    }
```

**Comment by spawnia** [comment]
Looks like your model might miss the primary key or it is wrongly configured?

Also, we changed some bits around the `buildKey()` function, can you try latest `dev-master`?

**Comment by mentamarindos** [comment]
@spawnia I already tried it and now it's working fine, thank you :D

**Comment by spawnia** [comment]
The latest https://github.com/nuwave/lighthouse/releases/tag/v4.16.0 fixes it, then.
