### ISSUE TITLE
Instalation Instructions do not work.

### ISSUE THREAD

**Issue by sprov03** [nuwave/lighthouse#1474]
Issues Installing Lighthouse in an existing Laravel project.
After 4 Attempts and 3 hours of trying to get the inital setup following the installation instructions, im going to give up.

**Expected behavior/Solution**
The installation instructions are not complete, And Cause hours of frustration, Hello world should work out of the box.

**Steps to reproduce**

1. composer require nuwave/lighthouse
2. php artisan vendor:publish --provider="Nuwave\Lighthouse\LighthouseServiceProvider" --tag=schema
3. when you go to /graphql

**Output/Logs**

<details><summary></summary>

```
`[{"errors":[{"message":"Syntax Error: Unexpected <EOF>","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}]`
```

</details></br>

**Lighthouse Version**
"nuwave/lighthouse": "^4.15"

**Comment by spawnia** [comment]
The error message is telling you: You are not sending a query. What you are trying to do is the equivalent of connecting to a SQL database and expecting results to pop out magically.

Read https://graphql.org/learn/serving-over-http/
