### ISSUE TITLE
How to create mutation with 3 or more nested relationships?

### ISSUE THREAD

**Issue by subhankhalid402** [nuwave/lighthouse#1475]
Hello,
I am trying nested mutation for three levels of depth in the relationship. 
The flow is:

- user has one to one relationship with lead

- lead has many to many relationship with task

when i try to create user with lead, it works fine. but when i try to create task, it doesn't work. it puts 0 for newly created id to table agent_task which is pivot table for lead and task. 

it's giving me this error. 
![image](https://user-images.githubusercontent.com/17280158/87635769-0cdc4380-c759-11ea-986a-22d434fc3ba8.png)

Here is sample code

```
input CreateUserInput {
    parent_id: Int!
    firstname: String!
    lastname: String
    email: String
    phone: String
    notes: String
    source: UserSource!
    is_test: Boolean
    lead: CreateLeadHasOne!
}
input CreateLeadInput {
    abid: String
    relation: LeadRelation
    referral_name: String
    first_touch_type: LeadFirstTouchType
    tasks: CreateTaskBelongsToMany
}
input CreateLeadHasOne {
    create: CreateLeadInput
}
input CreateTaskBelongsToMany {
    connect: [CreateTaskInput]
}
input CreateTaskInput {
    agent_id: Int!
    task_id: Int!
    started_at: DateTime
    notes: String
}
```
And here is the mutation call
```
mutation
{
  createUser(input: {
  parent_id: 1
    firstname: "last"
    email: "abc@gmaiol.com"
    source: ADMIN
    lead:
    {
      create: { 
     	 relation: FAMILY_FRIEND
       tasks:
        {
          connect:
          {
            agent_id: 1
            task_id: 1
          }
        } 
      }
    } 
  })
  {
    id
  }
}
```

**Comment by spawnia** [comment]
Denote codeblocks with

```
```graphql
```

to ensure they are readable.

**Comment by subhankhalid402** [comment]
> Denote codeblocks with
> 
> ```
> ```graphql
> ```
> 
> to ensure they are readable.

done

**Comment by spawnia** [comment]
Needs a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php

**Comment by subhankhalid402** [comment]
> Needs a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php

in the reference link, type Role has defined pivot in it. but in my case, there are more than 5 pivot tables for same type Lead.

**Comment by subhankhalid402** [comment]
> Needs a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php

My issue is little different, i want to insert data in different tables in nested mutation. Like, first user creation, then add lead data of that user that is created. And then add entry in pivot table of agent_task, in which i want to put lead_id that is recently created. And then i want to add row to another table where i want to use the id of agent_task that is recently created. 

so there are almost 4 nested relationships that depend on their parent created id. there may be more in future. Let me know if any confution

**Comment by subhankhalid402** [comment]
> Needs a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php

Let me know what else needed from my side, i will provide.

**Comment by spawnia** [comment]
> Let me know what else needed from my side, i will provide.

A PR is *exactly* what is needed and helps much more than any textual description of the issue. Try to find an equivalent case or add to the test setup as needed to reproduce your specific failure case.

**Comment by subhankhalid402** [comment]
> Needs a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php

there are only 3 tables and in this link only 2 level of nested mutation tests are there. 
My issue is somewhat like this one. 
[https://stackoverflow.com/questions/57896248/how-to-create-mutation-with-3-or-more-nested-relationships](https://stackoverflow.com/questions/57896248/how-to-create-mutation-with-3-or-more-nested-relationships)

**Comment by subhankhalid402** [comment]
> > Needs a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/MutationExecutor/BelongsToManyTest.php
> 
> there are only 3 tables and in this link only 2 level of nested mutation tests are there.
> My issue is somewhat like this one.
> https://stackoverflow.com/questions/57896248/how-to-create-mutation-with-3-or-more-nested-relationships

@spawnia any luck? if you have confusion, ask me question, i will try to explain.

**Comment by spawnia** [comment]
I need working test code, not explanations.

**Comment by subhankhalid402** [comment]
> I need working test code, not explanations.

I have added the code in post. complete flow of graphql inputs. and also added screenshot of what error i am facing. 
i have added mutation call structure as well. what else more i need to put???

**Comment by subhankhalid402** [comment]
> I need working test code, not explanations.

code isn't working brother, therefore i created thread. nested mutation of 3rd level isn't working.

**Comment by lorado** [comment]
To be able to help you further it is much better and simpler, if you provide a failing test case via PR. This is what spawnia means by "working test code" - a test that fails. You are the one, who is facing the problem, so at the moment only you know, in what particular situation the problem occur.

Also, if this should really be a bug in lighthouse, you would help the project by providing at least a failing test case, so contributors are able to fix it

**Comment by spawnia** [comment]
Thanks @lorado 

@subhankhalid402 https://github.com/nuwave/lighthouse/blob/master/CONTRIBUTING.md#the-process describes how you can create a PR. In order for us to recognize, debug and fix the issue we need to have a test case that triggers it as a part of this project.

**Comment by lucaslenz** [comment]
I am currently running in somewhat similar problems like @subhankhalid402. However I just want to create models with a depth of 3.

Here is an example mutation:

```graphql
mutation {
   createEntity(
      input: {
         depthTwo_1: {
            create: [{
               id: "someId"
            }]
         }
         depthTwo_2: {
            create: [{
               id: "someId"
	       depthThree_1: {
                  connect: "someId"
               }
               depthThree:_2 {
                  create: [{
                     someAttributes: "someValue"
                  }]
               }
            }]
         }
      }
   }
) {
   id
}
```


The problem I am facing with this mutation is that the ID of `creationEntity` should be injected into `depthThree_2`. This is not happening. The insert for entity `depthThree_2` is failing because the ID of `createEntity` is missing. I am not quiet sure why.

@subhankhalid402 just closed this Issue but without a solution to the problem? What is the status of this? I am willing to provide a failing test case!
