### ISSUE TITLE
A `assertGraphQLValidationKeys` assertion method throws `Undefined class constant` error

### ISSUE THREAD

**Issue by konradkalemba** [nuwave/lighthouse#1483]
**Describe the bug**
As the title states, using `assertGraphQLValidationKeys` throws a PHP error when running tests via `php artisan test` command.

**Expected behavior/Solution**
Changing `self` to `TestResponseMixin` in [`assertGraphQLValidationKeys` method](https://github.com/nuwave/lighthouse/blob/master/src/Testing/TestResponseMixin.php#L36)  solves the problem, but I don't know if it's a desired solution. I haven't checked if the bug exists in a different environment so it might be as well a problem with my project.

**Steps to reproduce**

1. Use `assertGraphQLValidationKeys` assertion in a test case
2. Run tests

**Output/Logs**

<details><summary>Click to expand</summary>

```
  Error

  Undefined class constant 'EXPECTED_VALIDATION_KEYS'

  at vendor/nuwave/lighthouse/src/Testing/TestResponseMixin.php:41
    37|     {
    38|         return function (array $keys) {
    39|             $validation = TestResponseUtils::extractValidationErrors($this);
    40|
  > 41|             Assert::assertNotNull($validation, self::EXPECTED_VALIDATION_KEYS);
    42|             /** @var array<string, mixed> $validation */
    43|             Assert::assertArrayHasKey('extensions', $validation);
    44|             $extensions = $validation['extensions'];
    45|

      +2 vendor frames
  3   tests/Feature/AuthTest.php:161
      Illuminate\Testing\TestResponse::__call("assertGraphQLValidationKeys")
```

</details></br>

**Lighthouse Version**
4.15

**PHP Version**
7.2.24

**Comment by spawnia** [comment]
I guess we have not hit that error, as Lighthouse's tests all pass 😉 

Thanks for the report, fixed.
