### ISSUE TITLE
Document a way to dismiss certain errors

### ISSUE THREAD

**Issue by genesiscz** [nuwave/lighthouse#1486]
So I'd like to have an option to dismiss certain errors/rules, such as NoUnusedFragments, but I found no way to do so. The static variables are private and I even tried to implement my own ErrorHandler to dismiss them, because I've read you can "filter" the errors, but I found not a single way to do that. 

Either this is not possible, which is kinda a feature request then, or there should be a better documentation regarding this.

Could you, please, point me in the right direction?

Thanks

**Comment by spawnia** [comment]
This is where we add the default rules: https://github.com/nuwave/lighthouse/blob/43e82ddd7dd9e94e26365424b79e6a81dd45f725/src/GraphQL.php#L156

I would like to know more about why you would want to disable them. This is the first time I heard of something like this.

**Comment by genesiscz** [comment]
I know, I've seen that line but there's no way I can override that.

In the development process there's a lot of moving around, playing with fragments, destroying the queries in smaller parts and it would be fine to just have a more easier (less strict) way to  look at these things. 

I know it might not be the best to suppress them but sometimes I just want to quickly try something or decide which solution is better and this makes it slower.  

I understand that graphQL itself is a lot about strictness and minimalism, but still, from a developer perspective (when I know what I am doing and that I will make it right in the end), would be nice to have  such an option.
