### ISSUE TITLE
Request: Creating an example folder in the main repo and main menu request in the docs

### ISSUE THREAD

**Issue by wolfiton** [nuwave/lighthouse#1488]
Hard to find examples with real code
**Which possible solutions should be considered?**
Creating a common examples folder where to store each example using frontend and backend implementations

Comunity effort to bring everything up to date and offer starting points to busy developers.

Thanks in advance

**Comment by spawnia** [comment]
That is what https://github.com/nuwave/lighthouse-example is meant to do. We might add a more visible link to it.
