### ISSUE TITLE
Publish a configuration with different tag

### ISSUE THREAD

**Issue by ssi-anik** [nuwave/lighthouse#1489]
I'd suggest to publish the configuration under different tag. As the package name is lighthouse, so it'd be great to have a tag something llike `lighthouse.config` or just `lighthouse`. I was searching to publish the configuration and I had to look into your codebase to find the configuration file.
That's my suggestion. Thanks.

![Screen Shot 2020-07-17 at 2 12 26 PM](https://user-images.githubusercontent.com/2676602/87764293-f527bc80-c837-11ea-960a-091fbb53b99f.png)

Why I am suggesting this?
Because a different package also publishes under the same tag, what if I don't want to extract that configuration? just only yours?

**Comment by spawnia** [comment]
Great suggestion, thank you. I namespaced the tags.
