### ISSUE TITLE
Can we change/alter nested mutation using Laravel events??

### ISSUE THREAD

**Issue by subhankhalid402** [nuwave/lighthouse#1490]
I want to alter the mutation using Laravel Creating event. I want to fetch task ID from **key** that is coming from front end. And then i want to add this ID in replace of key so that my task will be create automatically using lighthouse structure.  Here is sample mutation
```
mutation
{
  createUser(input: {
    firstname: "last"
    email: "abc@gmaiol.com"
    task:
    {
      create: { 
     	 key: 'reminder'
      }
    }
  })
  {
    id
  }
}
```

**Comment by spawnia** [comment]
You can do anything you want in a custom mutation.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
