### ISSUE TITLE
While reporting error to Laravel's ExceptionHandler::handle, doesn't satisfy the Exception type

### ISSUE THREAD

**Issue by ssi-anik** [nuwave/lighthouse#1491]
Laravel Version: `6.18.25`
Lighthouse version: `^4.15 `
PHP version: `7.4.7`

Laravel configuration: `Default configuration`
Lighthouse configuration: `Default configuration`

I created my own mutation resolver, and I used the arguments to my function like `$rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo`. I forgot to import the `ResolveInfo` class. Thus, the compiler thought the class resides in `App\GraphQL\Mutations` namespace. Which it doesn't.

So, when I executed the mutation, it showed the error like below.
<img width="579" alt="Screen Shot 2020-07-18 at 2 32 51 PM" src="https://user-images.githubusercontent.com/2676602/87848593-9760a680-c903-11ea-8b0d-a437e5ec092f.png">

I ran `dd(get_class($error), class_implements($error), get_class($error->getPrevious()), class_implements($error->getPrevious()));`  in `Nuwave\Lighthouse\Execution\ReportingErrorHandler`::20 and found

![Screen Shot 2020-07-18 at 2 26 14 PM](https://user-images.githubusercontent.com/2676602/87848649-f4f4f300-c903-11ea-88ae-5a5590b9ec6a.png)

So, I changed `$error->getPrevious()` to `$error` in `Nuwave\Lighthouse\Execution\ReportingErrorHandler`::25 and found the following which I think should be the actual behavior.
![Screen Shot 2020-07-18 at 2 37 13 PM](https://user-images.githubusercontent.com/2676602/87848677-3d141580-c904-11ea-9753-f85fc38fa1ba.png)

---
- In my server, 
```
type Mutation {
    jwtLogin(input: LoginInput @spread): AuthPayload! @field(resolver: "AuthMutation@jwtLogin")
}
```
- In my mutation
```php
<?php

namespace App\GraphQL\Mutations;

use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;

class AuthMutation 
{
    public function jwtLogin ($rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo) {
        // login goes here
    }
}
```
- In my client
```
mutation {
  jwtLogin(input: {
    username:"admin@example.com"
    password: "12345"
  }) {
    access_token
    refresh_token
    expires_in
    token_type
    user{
      id
      name
      email
    }
  }
}
```

**Comment by spawnia** [comment]
Thanks for the detailed report and really digging into this.

The real issue is Laravel's `ExceptionHandler`, which is not equipped to deal with subclasses of `\Error`. In this case, the underlying `TypeError` is produced by PHP itself.

I recommend to upgrade to Laravel 7, where they fixed their error handler.

**Comment by spawnia** [comment]
Oh and another tip how you can save boilerplate when declaring your mutation:

```graphql
type Mutation {
    jwtLogin(input: LoginInput @spread): AuthPayload!
}
```

```php
<?php

namespace App\GraphQL\Mutations;

use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;

class JwtLogin
{
    public function __invoke($_, array $args) {
        // login goes here
    }
}
```

**Comment by ssi-anik** [comment]
@spawnia, thanks man for the suggestion. I was actually trying to get my hand dirty. Want to know how things are done and work. And the purpose behind that was to reuse the same class as we do in controllers.

Thanks anyway. <3

**Comment by spawnia** [comment]
Resolver classes - just like controllers - are only meant to be glue code. Reusable logic should go somewhere else.

**Comment by ssi-anik** [comment]
One more point I'd like to share, as Laravel internally handles the `\Throwable` type and processes according to it, why don't you follow it? Because you can't just stop people from using L6 and to switch to L7.
I had thrown a `\TypeError` and Laravel internally managed it. 

Just a suggestion.

---
<img width="1280" alt="Screen Shot 2020-07-20 at 11 07 29 PM" src="https://user-images.githubusercontent.com/2676602/87966009-7607e200-cade-11ea-91b0-3a148ac31099.png">

---
<img width="1280" alt="Screen Shot 2020-07-20 at 11 10 20 PM" src="https://user-images.githubusercontent.com/2676602/87966249-d3039800-cade-11ea-9937-733fbff3402d.png">

**Comment by spawnia** [comment]
There is more important work to do. Basic static analysis will prevent `TypeError` from occuring, so I don't see much need to validate this at runtime.

GraphQL is all about static validation, so that philosophy extends to its usage.
