### ISSUE TITLE
@can directive isn't working anymore after update from v4.12.2 to v4.16.0

### ISSUE THREAD

**Issue by maximeb97** [nuwave/lighthouse#1493]
**Describe the bug**

Queries and mutations with @can directive always says "You are not allowed to access xxx" after upgrading package version from v4.12.2 to v4.16.0.

I'm using `laravel-permission` package to manage permissions through roles.

**Expected behavior/Solution**

The queries and mutations should be accessible if the user has the permission.
When coming back to previous version, it's working as expected.

**Steps to reproduce**

1. Create query/mutation with @can directive
2. Create Role with the permission to access to the query
3. Create a User with the Role
4. Try to access the query

<details><summary>Graphql Schema</summary>

```
extend type Query @guard(with: ["api"]) @middleware(checks: ["admin"]) {
    carts: [Cart!]!
        @paginate(type: "paginator", builder: "\\App\\Models\\Cart@getOrdered")
        @can(
            ability: "admin-manage-cart"
            model: "\\App\\User"
        )
}
```

</details></br>

**Output/Logs**

I verified user has permission to access to the query:

<details><summary>Click to expand</summary>

```
$ php artisan tinker
>>> $u = User::where('email', 'admin@local.local')->first()->can('admin-manage-cart');
=> true
```

</details></br>

**Lighthouse Version**

4.16.0

**Comment by spawnia** [comment]
A PR with a failing test case is a great first step towards solving this issue.

Can you check https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/CanDirective.php for a change that might be the cause of your issue?

**Comment by maximeb97** [comment]
Thank you for your quick answer,
I will have a look about the class history as soon as I can.

**Comment by sicsol** [comment]
I'm having a similar issue with the @can directive as well. I'm using sanctum and it appears that the context->user is null

**Comment by sooxt98** [comment]
It works on v4.16.3 tho, im using sanctum too

**Comment by sicsol** [comment]
@sooxt98 I'm on 4.16 and still having issues would you mind sharing your sanctum configuration/setup for lighthouse with me

**Comment by sooxt98** [comment]
@sicsol did u try 4.16.3 instead of 4.16?

**Comment by sooxt98** [comment]
And what and where is the context user is null ?

**Comment by sicsol** [comment]
@sooxt98 I will try 4.16.3 and see. The context was null in the handleField resolver for the can directive

**Comment by spawnia** [comment]
Given the lack of activity, I am closing this issue. PRs with failing test cases are still welcome.
