### ISSUE TITLE
@globalId decodes arguments after validation

### ISSUE THREAD

**Issue by hosmelq** [nuwave/lighthouse#1495]
**Describe the bug**

The `@globalId` directive is not working in inputs with the `@validator` directive.

**Expected behavior/Solution**

`@globalId` directive works as expected.

**Example code**

```gql
input UpdateChildInput @validator {
  childId: ID! @globalId(decode: "ID")
  color: String
  firstName: String
  lastName: String
}
```

**Log**

```
[
  'childId' => 'VXNlcjoyMDg4OA==',
  'color' => '#e27300',
  'firstName' => '...',
  'lastName' => '...',
]
```

**Lighthouse Version**

`dev-master`

**Comment by spawnia** [comment]
> The @globalId directive is not working in inputs with the @validator directive.

How is not working?

> `@globalId` directive works as expected.

What is expected?

**Comment by hosmelq** [comment]
@spawnia i use the decode param and you can see in the log that the childId is still encoded.

**Comment by spawnia** [comment]
Lighthouse applies arg directives (such as `@globalId`) in 3 phases, see https://lighthouse-php.com/master/custom-directives/argument-directives.html#evaluation-order

As of now, the `@globalId` directive is an `ArgTransformerDirective`, and thus runs after validation.

**Comment by hosmelq** [comment]
With the old validation was working very well I thought it was I issue 😅. Thank you for your reply.

**Comment by spawnia** [comment]
I would like to keep this open for discussion. The behaviour for this changed, now that `dev-master` departed from v4 compatibility, but since v5 is not out, we can still change stuff around.

**Comment by hosmelq** [comment]
Yes, at the moment I have to find a way to decode de id to validate because I am using the `exists` rule.

```php
'childId' => ['required', Rule::exists('users', 'userId')],
```

**Comment by spawnia** [comment]
Changed the order around, try updating to the latest version. Your validator should work now.

Off-topic: How is the upgrade to (pre-)v5 going for you?
