### ISSUE TITLE
Middleware before to resolver

### ISSUE THREAD

**Issue by MrJmpl3** [nuwave/lighthouse#1502]
**What problem does this feature proposal attempt to solve?**

I look the authorization: https://lighthouse-php.com/4.16/security/authorization.html#custom-field-restrictions

This hide the fields, but the request and consult to database is already done, sometimes some middleware are required before to resolver like permissions autentification

or I am misunderstanding the code?

**Which possible solutions should be considered?**

Any form to execute middleware before to resolver

**Comment by spawnia** [comment]
https://lighthouse-php.com/4.16/security/authentication.html

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by MrJmpl3** [comment]
@spawnia This apply to all graph schema, but If a want only to some types and execute before?
