### ISSUE TITLE
Complex authorisation requirements

### ISSUE THREAD

**Issue by no0by5** [nuwave/lighthouse#1513]
**What problem does this feature proposal attempt to solve?**
In my API I have to authorize requests to fields by two different factors. Whether the user is authorized to access the data or whether the data belongs to the user. For example, the user should be able to see its own user data and all users with admin rights should be able to see this data too.<br>
I was able to create a directive to check for permissions as its described in the [docs](https://lighthouse-php.com/master/security/authorization.html#custom-field-restrictions). But I didn't find a solution to give the user access to its own fields with this directive. `@can` only works for queries and can't be applied to fields. Even if `@can` would work on fields, it somehow would have to communicate to the other directive so it doesn't cancel the query.

**Which possible solutions should be considered?**
A more complex directive than to authoize fields.

**Comment by spawnia** [comment]
`@can` works on any field, including those nested within a type.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
