### ISSUE TITLE
lighthouse:validator listed in Docs but not defined

### ISSUE THREAD

**Issue by theovier** [nuwave/lighthouse#1514]
**Describe the bug**
The documentation suggests to add custom validators by executing `php artisan lighthouse:validator UpdateUserInputValidator` (https://lighthouse-php.com/master/security/validation.html#validator-classes). However, the `Command "lighthouse:validator" is not defined. `

**Expected behavior/Solution**
Either a custom validator should be created or the documentation should offer a modern alternative for creating a custom validator.

**Steps to reproduce**

1. run `php artisan lighthouse:validator CreateLikeValidator`

**Output/Logs**

<details><summary>Click to expand</summary>

```
Command "lighthouse:validator" is not defined.  
                                                  
  Did you mean one of these?                      
      lighthouse:cache                            
      lighthouse:clear-cache                      
      lighthouse:directive                        
      lighthouse:ide-helper                       
      lighthouse:interface                        
      lighthouse:mutation                         
      lighthouse:print-schema                     
      lighthouse:query                            
      lighthouse:scalar                           
      lighthouse:subscription                     
      lighthouse:union                            
      lighthouse:validate-schema  
```

</details></br>

**Lighthouse Version**
v4.16.0

**Comment by spawnia** [comment]
Only available in `dev-master`

**Comment by sebastiansson** [comment]
@spawnia Why is it in the 4.18 docs then? Really hard to keep track of what is in the docs vs what's in the code. Would be happy to create a PR but hard to know without being part of the development/knowing the code base.

**Comment by spawnia** [comment]
@sebastiansson thanks for bringing that to my attention. That was a mistake during the docs publishing, reverted that to ensure 4.17 and 4.18 are accurate.
