### ISSUE TITLE
Expose the data of ValidationDirective

### ISSUE THREAD

**Issue by MrJmpl3** [nuwave/lighthouse#1524]
**What problem does this feature proposal attempt to solve?**

Some validation like 'unique' need access to the data when you can use ignore field

https://laravel.com/docs/7.x/validation#rule-unique

**Which possible solutions should be considered?**

Expose the args (data to validate) in a variable
The extend validation middleware can access to the variable.

**Comment by spawnia** [comment]
Does https://github.com/nuwave/lighthouse/blob/7876def6f0a5558e77eb2dbca8f89335346888d8/src/Validation/Validator.php#L49 solve your need. Available in `dev-master` now, will be in the uipcoming v5.

**Comment by MrJmpl3** [comment]
> 
> 
> Does
> 
> https://github.com/nuwave/lighthouse/blob/7876def6f0a5558e77eb2dbca8f89335346888d8/src/Validation/Validator.php#L49
> solve your need? Available in `dev-master` now, will be in the upcoming v5.

Oh, Is that. Solved, I wait for the new version 🧐

**Comment by MrJmpl3** [comment]
Anotation to the V4 version, use `$this->args` and 'Arr' facade
