### ISSUE TITLE
Validation rules and changes for 5.x

### ISSUE THREAD

**Issue by brunobg** [nuwave/lighthouse#1525]
I was going to post this on SO or slack, but I found https://github.com/nuwave/lighthouse/pull/1185 so I'm asking here. If not appropriate close this and I'll post there. I can summarize the responses given here and send a PR appropriate documentation for 5.x with examples.

Actual question: how to write arbitrary validation directives currently without resorting to Laravel rules? I have implemented a simple class that extends FieldMiddleware:

```
class MyFancyDirective extends BaseDirective implements FieldMiddleware, DefinedDirective
```

but the resolver set in `handleField()` is not called for an upsert mutation call. It is called for a basic query, though. Shouldn't it be called?

Apparently `ValidationDirective` is set to be deprecated on 5.x (which is apparently coming out soon), so I'd rather avoid using it at this point. 

Thanks!

**Comment by spawnia** [comment]
We have docs on:

- Validator classes: https://lighthouse-php.com/master/security/validation.html#validator-classes
- Field middleware: https://lighthouse-php.com/master/custom-directives/field-directives.html#fieldmiddleware

The migration path to 5.x is described in https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#replace-custom-validation-directives-with-validator-classes

**Comment by spawnia** [comment]
Open for improvements to the docs, though.
