### ISSUE TITLE
Change return type of user() method in GraphQLContext from class User to interface Authenticatable

### ISSUE THREAD

**Issue by mahpooya** [nuwave/lighthouse#1538]
**Describe the bug**

In interface GraphQLContext in namespace Nuwave\Lighthouse\Support\Contracts there is a method user() for getting user.
It is currencty set to return class \Illuminate\Foundation\Auth\User (in php docs)
But I think better implementation is to return interface \Illuminate\Contracts\Auth\Authenticatable instead of class User.

Note that in lighthouse default context (Nuwave\Lighthouse\Schema\Context) this method is returning Authenticatable interface
So i think its another reason to return interface Authenticatable  in interface GraphQLContext

**Lighthouse Version**
4.16.1

**Comment by spawnia** [comment]
Thanks for the report, changed as of v4.16.3
