### ISSUE TITLE
Imports not working right

### ISSUE THREAD

**Issue by FranciscoCaldeira** [nuwave/lighthouse#1546]
**Describe the bug**
When having two imports like this example in schema.graphql file:

#import user.graphql
#import car.graphql

And then using Postman/ Firecamp to use the graphql querys/mutations only the last import can do the query and mutation.
I've done the folder solution(https://lighthouse-php.com/4.16/digging-deeper/schema-organisation.html#schema-imports) like this: 

graphql/
  |-- schema.graphql
  |-- test/
    |-- car.graphql
    |-- user.graphql

and the in schema.graphql file like:

#import test/*.graphql 

But the same way, inside the /test folder, only apply the last file querys/mutations.

**Expected behavior/Solution**

The expected should be using the queries/mutations done in the car and in the user.

**Steps to reproduce**

1.I've done a small repo to this problem and there you have steps.. This was done for the firecamp devs because I thought It was their problem not fetching the schema.. but when I tryed on the Postman it was the same problem (couldn't use the  other imports, just the last one).
Link here: https://github.com/FranciscoCaldeira/laravel_lighthouse_firecamp

**Output/Logs**
The output is only queries/mutations on the last #import and when I try the queries/mutations from the first #import says like for example: "Cannot query field \"cars\" on type \"Query\".",

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

Master

**Comment by liza-nt** [comment]
i have same issue what did you do to fix this??
