### ISSUE TITLE
[DOC]

### ISSUE THREAD

**Issue by henzeb** [nuwave/lighthouse#1552]
The website is very slow and will not ever load.

The website is not loading at this point. 

Just go to lighthouse-php.com 

**Output/Logs**

I am using chrome (version 85.0.4183.83). The problem is mysteriously not there in Firefox. So that could be used as a workaround.

**Comment by henzeb** [comment]
Never mind. after a whole day waiting it suddenly works.

**Comment by spawnia** [comment]
![image](https://user-images.githubusercontent.com/12158000/92385010-66d20780-f111-11ea-8f99-4605d21fbf1b.png)
