### ISSUE TITLE
[v5.0-alpha.2] Target class [Laragraph\\LaravelGraphQLUtils\\RequestParser] does not exist.

### ISSUE THREAD

**Issue by sooxt98** [nuwave/lighthouse#1553]
![image](https://user-images.githubusercontent.com/13378059/92408854-476ac700-f171-11ea-9a2b-8a1eb4e289ab.png)

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.0-alpha.3
