### ISSUE TITLE
Relations get reloaded even when they are already present.

### ISSUE THREAD

**Issue by cradigan** [nuwave/lighthouse#1555]
**Describe the bug**
Not 100% sure if this is a bug. But for me it is unexpected behaviour with large performance implications.

RelationFetcher always reloads a relation even when it is already present on the parent model. 

**Expected behavior/Solution**

I think if a relation is already present on the parent model it should not have to be reloaded.
What appears to fix the issue is updating line 39 of RelationFetcher.php (in function loadedParentModels) from:

`$modelsOfSameClass->load($relation);`

to

`$modelsOfSameClass->loadMissing($relation);`

This fix appears to be working, but i'm curious as to if there is a reason for load to be used over loadMissing in the first place.

**Steps to reproduce**

1.  Create an Eloquent Model with a relationship.
2. Force relationship to always load with the model.
`protected $with = [ 'contacts'];`
3. Create a type in your graphql schema to match your new model and add your relationship with relationship direcive (eg. @hasOne)
3. Create a query that will return your new type
4. Add code to the boot() of your AppServiceProvider to dump DB events
`        DB::listen(function ($event) {
                dump($event->sql);
                dump($event->bindings);
        });
`
5. Run new query
6. Check the dumped data. You will notice that your relationship is loaded twice from the DB.

**Lighthouse Version**

v4.16.2

**Comment by spawnia** [comment]
As I suspected, using `loadMissing` breaks conditions on relations. See https://github.com/nuwave/lighthouse/pull/1560

**Comment by cradigan** [comment]
Hmm. I think i understand the issue. However, there is a lot I don't understand yet about the inner workings of lighthouse and the field resolvers, so i apologize if any of these thoughts are wildly off the mark.

The actual problem i'm having is a bit more complicated than the simplified example above.  In the above example it's probably  fair just to restrain from defining the $with variable directly on a model class and defer the eager loading logic to Lighthouse.  However,  the real problem i'm running into is that I have a numerous  fields on a type that resolve using the same relationship (one example: roles relation that returns isAnAdmin: Boolean, isAPublisher: Boolean). These call a method using @method and eager load the relation using @with to return the dersired output.  **Perhaps this is a bad pattern to begin with? I would be interested in anyone's insight.**

Seems like a fix would be tricky.  I'm seeing 2 big problems here:

1) loadMissing doesn’t reload the relationship when it already exists regardless of whether the new relationship has a decorated builder. A potential fix here would be to check the decorated builder, and try to determine if it’s altering the query of not. If it is, then don’t use load over loadMissing.

2) If the checks in problem 1 determine it is ok to use loadMissing, the reverse issue could still be a problem.  How would we know whether the existing relation data has all the  items we want or was somehow scoped to filter out specific results. Maybe it would be possible to group relations based on unique decorated builders, apply load on new group and loadMissing within group, and resolve fields in order related to those groups.

**Comment by spawnia** [comment]
What about some kind aliasing to give Lighthouse enough information to determine the "sameness" of relations?

```
type User {
  isAdmin: Boolean @with(relation: "roles", as "roles-without-conditions")
  isAPublisher: Boolean @with(relation: "roles", as "roles-without-conditions")
  roles(someArg: String): [Roles!]! @hasMany
}
```
