### ISSUE TITLE
Support Laravel 8

### ISSUE THREAD

**Issue by caizhigang97** [nuwave/lighthouse#1556]
Laravel 8.0 just released, any idea when this package will support it?
![image](https://user-images.githubusercontent.com/21142662/92562550-bd257e80-f2a8-11ea-9856-8ac7de43adbe.png)
Thanks~

**Comment by henzeb** [comment]
There is a pull requet about this: #1547

**Comment by spawnia** [comment]
The relevant pull request is https://github.com/nuwave/lighthouse/pull/1549

We are currently awaiting the release of `lumen-framework` v8

**Comment by spawnia** [comment]
Supported as of https://github.com/nuwave/lighthouse/releases/tag/v5.0-alpha.4
