### ISSUE TITLE
Cannot pass null as value for "@in" arguments

### ISSUE THREAD

**Issue by FreekVR** [nuwave/lighthouse#1557]
Passing a "null" value to a query argument using the `@in` directive yields an Eloquent error. 
`Argument 1 passed to Illuminate\\Database\\Query\\Builder::cleanBindings() must be of the type array, null given`.

My use case is that in my frontend app, I'm using variables to set various conditions on a single query. It might be that this variable is empty, in which case the attached query constraint should not be applied.

See schema and query examples further down.

**Expected Behaviour**
When null is passed, no conditions are applied. Similar to how this works for `@whereConditions`

**Steps to reproduce**

Schema:
```
type Query {
    updates(
        "Provide a list update types. Returns Updates with *any* of the types in the list"
        types: [UpdateType] @in(key: "update_type")
        orderBy: _ @orderBy(columns: ["created_at", "updated_at"])
    ): [Update!]! @paginate
}


enum UpdateType {
    news, event, request, opportunity, project
}
```

Query:
```
query UpdateIndex($page: Int = 1, $amount: Int = 10, $types: [UpdateType!] = null) {
    updates(
        first: $amount
        page: $page
        types: $types
        orderBy: [{ column: CREATED_AT, order: DESC }]
    ) {
        data {
            id, title, message, slug, update_type, comment_count, created_at
        }
        paginatorInfo {
            count, lastPage
        }
    }
}

```

**Output/Logs**

<details><summary>Click to expand</summary>
[2020-09-09 14:30:24] local.ERROR: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 919 {"userId":1,"exception":"[object] (TypeError(code: 0): Argument 1 passed to Illuminate\\Database\\Query\\Builder::cleanBindings() must be of the type array, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 919 at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3078)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(919): Illuminate\\Database\\Query\\Builder->cleanBindings(NULL)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Query\\Builder->whereIn('update_type', NULL)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1414): Illuminate\\Database\\Eloquent\\Builder->forwardCallTo(Object(Illuminate\\Database\\Query\\Builder), 'whereIn', Array)
#3 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/InDirective.php(32): Illuminate\\Database\\Eloquent\\Builder->__call('whereIn', Array)
#4 /var/www/html/vendor/nuwave/lighthouse/src/Execution/Arguments/ArgumentSet.php(185): Nuwave\\Lighthouse\\Schema\\Directives\\InDirective->handleBuilder(Object(Illuminate\\Database\\Eloquent\\Builder), NULL)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet::Nuwave\\Lighthouse\\Execution\\Arguments\\{closure}(Object(Nuwave\\Lighthouse\\Schema\\Directives\\InDirective), 0)
#6 /var/www/html/vendor/nuwave/lighthouse/src/Execution/Arguments/ArgumentSet.php(186): Illuminate\\Support\\Collection->each(Object(Closure))
#7 /var/www/html/vendor/nuwave/lighthouse/src/Execution/Arguments/ArgumentSet.php(147): Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet::applyArgBuilderDirectives(Object(Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet), Object(Illuminate\\Database\\Eloquent\\Builder), NULL)
#8 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/PaginateDirective.php(113): Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet->enhanceBuilder(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#9 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php(166): Nuwave\\Lighthouse\\Schema\\Directives\\PaginateDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#10 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(632): Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory->Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#11 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(555): GraphQL\\Executor\\ReferenceExecutor->resolveOrError(Object(GraphQL\\Type\\Definition\\FieldDefinition), Object(GraphQL\\Language\\AST\\FieldNode), Object(Closure), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#12 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1247): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#13 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(257): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Object(ArrayObject))
#14 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(208): GraphQL\\Executor\\ReferenceExecutor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#15 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Executor.php(155): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#16 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(158): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL)
#17 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(90): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), 'query UpdateInd...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL, Array)
#18 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(156): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), 'query UpdateInd...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL, Array)
#19 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(99): Nuwave\\Lighthouse\\GraphQL->executeQuery('query UpdateInd...', Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL)
#20 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(59): Nuwave\\Lighthouse\\GraphQL->executeRequest(Object(Nuwave\\Lighthouse\\Execution\\LighthouseRequest))
#21 [internal function]: Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->query(Object(Nuwave\\Lighthouse\\Execution\\LighthouseRequest))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('query', Array)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController), 'query')
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AttemptAuthentication.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/html/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#56 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#57 {main}
"} 
`Argument 1 passed to Illuminate\\Database\\Query\\Builder::cleanBindings() must be of the type array, null given`.
</details></br>

**Lighthouse Version**
4.16.3

**Comment by spawnia** [comment]
As shown in https://github.com/nuwave/lighthouse/commit/6b5bd42dc1889b539d40764a1ba98e9824c683de, defining a variable but not passing a value for it works fine.

The issue is that you defined your query to pass the default value of `null` if the argument is not given. Same as in queries without variables, there is a difference between not passing the argument and passing `null`.
