### ISSUE TITLE
get user context in ArgSanitizerDirective's sanitize method?

### ISSUE THREAD

**Issue by sooxt98** [nuwave/lighthouse#1558]
The context could speed up the performance instead of repeating calling Auth::user() for each restricted mutation attribute

https://github.com/nuwave/lighthouse/issues/1544
https://stackoverflow.com/questions/63778328/laravel-lighthouse-restrict-mutation-field/63812873#63812873

**Comment by spawnia** [comment]
Please follow the issue template.
