### ISSUE TITLE
Able to get user context directly within ArgSanitizerDirective's sanitize method

### ISSUE THREAD

**Issue by sooxt98** [nuwave/lighthouse#1559]
**What problem does this feature proposal attempt to solve?**

Able to get user context directly within ArgSanitizerDirective's sanitize method. I'm currently using it to restrict mutation input field as in https://stackoverflow.com/questions/63778328/laravel-lighthouse-restrict-mutation-field/63812873#63812873

**Which possible solutions should be considered?**

Could try to use concept of FieldMiddleware's setResolver callback approach to pass in the GraphQLContext

Currently I'm using the `Auth::user()` but it adds extra overhead with extra user db query

**Comment by spawnia** [comment]
> Currently I'm using the Auth::user() but it adds extra overhead with extra user db query

That depends upon the implementation of your guard. Laravel defaults are smart enough to cache and just return the user without hitting the database on calls after the first one.

What you are proposing is an overly specific extension of a focused interface. Following that logic, nearly every interface in Lighthouse - or Laravel in general - should be extended to provide access to the authenticated user.

**Comment by sooxt98** [comment]
@spawnia thanks for the quick reply, i just tried it and yep it did cache the user's query; but i just curious why user context is exists in GraphQLContext

**Comment by spawnia** [comment]
I think that `GraphQLContext` is unnecessary, given that Laravel provides other mechanisms for dependency injection
