### ISSUE TITLE
@paginate directive used on relationships behaves like used without relationship

### ISSUE THREAD

**Issue by dimitri-koenig** [nuwave/lighthouse#156]
Hi guys

The `@paginate` directive uses $model::query() for resolvement. That means that one cannot use it on relationships of a model. And the tests for this directive do not uncover that issue.

Before I start a full blown PR I want to start a short discussion in which direction to move because my case is not everyone's case.

Current solution:
Change this line in the paginate class:
```php
$query = $this->applyFilters($model::query(), $args);
```

to this one:
```php
$fieldName = $value->getFieldName();
$query = $root && method_exists($root, $fieldName) ? $root->$fieldName() : $model::query();
```

The model requirement would be obsolete if a $root object exists. Would need to check for that.

Any thoughts on this?

Best
Dimitri

**Comment by spawnia** [comment]
There are two particular directives for relationships, `@hasMany` and `@belongsTo`.

`@hasMany` handles the relationship (it even batches the request), and allows to access it either as a raw list or paginated. Does that solve the issue you are having?
