### ISSUE TITLE
Can not change test schema in a single test method with UsesSchemaTest trait

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#1569]
**Describe the bug**

https://lighthouse-php.com/4.16/testing/extensions.htm

Cant override schema as described on docs, when using sucessive graphql requests.

**Expected behavior/Solution**

It should override schema.

**Steps to reproduce**

See PR https://github.com/nuwave/lighthouse/pull/1568

**Lighthouse Version**

v5.alpha4

**Comment by spawnia** [comment]
The approach described in the docs actually works, but we might clarify that changing after initialization does not work.

We could make it so the test schema is recompiled on every call to `$this->graphQL()`, but I am worried that might be costly in terms of performance.

**Comment by robsontenorio** [comment]
@spawnia can you give some directions to achieve that?

I am considering to create my own trait. Once i am working on Lighthouse Dashboard package i need exactly this behavior on my testing case. Because i need detect changes on schema on sucessive requests.

**Comment by spawnia** [comment]
How about splitting your test methods so they are focused and do one thing? Dynamically changing a schema in the lifecycle of a request has not come up as a real world use case, so I am hesitant to support it.

**Comment by robsontenorio** [comment]
What I have tried, but no lucky:

- disable cache 
- call again “setupTestSchema” before every call.

**Comment by robsontenorio** [comment]
Solved by adding this to my `TestCase.php`

```php
protected function rebuildTestSchema() {
        $this->app->extend(SchemaSourceProvider::class, fn () => new TestSchemaProvider($this->schema));
}
```

Now i can switch schemas on single test method.
