### ISSUE TITLE
Introduce snapshot testing

### ISSUE THREAD

**Issue by dimitri-koenig** [nuwave/lighthouse#157]
Hi guys

I've got current big project where using traditional testing of json output just doesn't work for that huge scale. So I started to use snapshot testing using Stapie's awesome package for that: https://github.com/spatie/phpunit-snapshot-assertions

That's where I, for example, discovered that the `@paginate` directive has some tests but they only have a mini mini fraction of assertions and did not uncover a huge issue about using it on relationships (see #156).

What do you think about replacing some test assertions with snapshot tests where one could deal with a huge bunch of different assertions with one shot?

Best
Dimitri

**Comment by dimitri-koenig** [comment]
Hm, when dealing with integration tests then we are dealing with a lot of data with so many variations that "pretty small and focused" cannot capture all different angles.

**Comment by spawnia** [comment]
Can you give a few examples? I am not against trying this package, i would just like to avoid adding another dependency and more complexity if it is not really needed.

**Comment by spawnia** [comment]
Closing this for now. Should a use case come up, i am open for accepting PR's that use Snapshot Testing.
