### ISSUE TITLE
Are there any plans for adding `validator` directive to 4 version?

### ISSUE THREAD

**Issue by erayaydin** [nuwave/lighthouse#1570]
**What problem does this feature proposal attempt to solve?**

v5 is currently in alpha. Because of this, most people using the 4.16 version. `@validator` directive is a useful built-in directive and 4. version need that directive.

**Which possible solutions should be considered?**

Adding `@validator` directive support to the 4 version. I think its can't break current 4 version, so we can add as minor patch.

**Comment by spawnia** [comment]
Thanks for the suggestion.

I will have to pass on this, because:
- I generally don't have the time to backport features
- this feature requires some big changes which in turn risks breakage
