### ISSUE TITLE
ExceptionHandler does not handle exceptions thrown from directive

### ISSUE THREAD

**Issue by kanidjar** [nuwave/lighthouse#1571]
**Describe the bug**

ExceptionHandler does not handle exceptions thrown from directive

AuthenticationException thrown from directive gives:

````
{
    "message": "Server Error"
}
`````

Exception is handled by Laravel's ExceptionHandler.

From resolver:

`````
"{"errors":[{"message":"Unauthenticated.","extensions":{"guards":[],"category":"authentication"},"locations":[{"line":3,"column":17}],"path":["authenticatedUsersByCountry"]}]}"
`````

**Expected behavior/Solution**

The exception should be handled like from the resolver.

**Lighthouse Version**

5.0-alpha.4

**Comment by kanidjar** [comment]
Workaround: extends from GraphQL\Error\Error;

Not a durable solution though.

**Comment by spawnia** [comment]
From https://lighthouse-php.com/master/digging-deeper/error-handling.html

> webonyx/graphql-php offers the GraphQL\Error\ClientAware interface, that can be implemented by Exceptions to control how they are rendered to the client.
