### ISSUE TITLE
How Can I execute a GraphQL query programmatically?

### ISSUE THREAD

**Issue by wovosoft** [nuwave/lighthouse#1572]
Hello 
I am working on a SSR project using https://github.com/spatie/server-side-rendering , where I need to put the queried data to the context variable. Previously I was doing it by querying data first and then send it to the ssr object. But now after migrating to lighthouse I am not able to execute a graphql request programmatically . 
Thank you

**Comment by olivernybroe** [comment]
Either just make a request to your graphql endpoint like you normally would to any other endpoint programmatically.

Or request `Nuwave\Lighthouse\GraphQL` class from the service container and run `executeRequest` or `executeQuery` directly.

**Comment by spawnia** [comment]
@olivernybroe good suggestions, thanks. I wonder if we should document that usage and commit to offering a stable interface.

**Comment by olivernybroe** [comment]
Hmm, I think that makes sense. Don't see an issue with officially supporting that in the docs.

**Comment by wovosoft** [comment]
@olivernybroe Thank You Very Much Dear
