### ISSUE TITLE
stdClass given

### ISSUE THREAD

**Issue by dmitrydrynov** [nuwave/lighthouse#1573]
Hi everyone,
I have this error on a query

> Argument 1 passed to Nuwave\Lighthouse\Schema\Directives\RelationDirective::Nuwave\Lighthouse\Schema\Directives\{closure}() must be an instance of Illuminate\Database\Eloquent\Model, instance of stdClass given, called in E:\OpenServer\domains\cab\vendor\nuwave\lighthouse\src\Schema\Factories\FieldFactory.php on line 166

I have this type
> type Account@modelClass(class: "\\App\\User") {
> 	id: ID!
> 	name: String!
> 	email: String!
> 	created_at: DateTime!
> 	updated_at: DateTime!
> 	profile: Member @belongsTo(relation: "member")
> }

for return accounts list I use current query

> accounts(start: Int, length: Int, sortField: String, sortOrder: String): AccountDatatableResponse @field(resolver: "App\\GraphQL\\Mutations\\AccountMutator@getList")

AccountDatatableResponse is

> type AccountDatatableResponse {
> 	draw: Int
> 	recordsTotal: Int
> 	recordsFiltered: Int
> 	data: [Account]
> }

I am getting actual data but the relationship is null
![image](https://user-images.githubusercontent.com/4089575/94142580-301d2080-fe77-11ea-9522-8c4033dd3ce2.png)

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
