### ISSUE TITLE
CSRF protection for Lighthouse

### ISSUE THREAD

**Issue by k0ka** [nuwave/lighthouse#1582]
**Are you willing to provide a PR for this issue or aid in developing it?**
------
Yes

**What problem does this feature proposal attempt to solve?**
------
CSRF is a widely known type of attacks that occurs when a malicious web site causes a user's web browser to perform an unwanted action on a trusted site when the user is authenticated.

The rule of the thumb is that modern frameworks include and enable CSRF protection by default.

Right now the default Lighthouse installation allows CSRF. For example, the attacker may insert the following simple code in a blog comment:

```html
<img src="/graphql?query={EvilMutation{}}" />
```

When the victim opens this comment, it will cause the browser to make a request to the graphql endpoint with all authentication cookies. And execute the EvilMutation.

Though clean Lighthouse installation doesn't create this vulnerability by itself (the user has to write some code that enables this vulnerability), I suppose it should encourage applying right practices and warn users about possible caveats.

**Which possible solutions should be considered?**
------

The simplest solution I've found is to enforce the "Content-type" request header to be "application/json" and reject any requests that have an invalid or missing header.

Here is why it would work. The attacker may forge "Content-type" only with POST form or XHR:
1) the POST form content type is limited to only three formats: "application/x-www-form-urlencoded", "multipart/form-data" and "text/plain".
2) if the attacker can execute an arbitrary XHR from your site, it means they can execute any javascript, so the site is already vulnerable to XSS.

So by enforcing the "Content-type" request header to be "application/json", we ensure, that request is either legitimate or the  attacker already has gained full control over the client. 

How we can achieve it:
1) removing the AcceptJson middleware from the default lighthouse config. Add a warning, that enabling this middleware may cause your application to be vulnerable to CSRF attacks.
2) accepting only POST requests
3) adding the "EnforceJsonContentType" middleware, which rejects any request that doesn't have a "Content-type" request header set to "application/json".
4) adding an explanation to the documentation why these middlewares should be changed very cautiously or with understanding of the possible caveats.

Some more features may be added, these are the most important ones.

Further reading
------
https://stackoverflow.com/questions/11008469/are-json-web-services-vulnerable-to-csrf-attacks
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

**Comment by faiverson** [comment]
This can be done easily in Laravel with a middleware and then you can add that middleware to Lighthouse in the config file. I don't see any reason to add this functionality to Lighthouse and I'm not sure if this is the Lighthouse's goal.

Anyway, in case this is consider as a valid choice, I'd suggest to make this optional in a service provider, something similar to the @whereConditions directive.

**Comment by faiverson** [comment]
Furthermore, there are other valid types to considerer like `application/graphql` that might be valid too.

**Comment by k0ka** [comment]
If that can be done easily, it doesn't mean it shouldn't be done in Lighthouse to encourage best practices. Right now Lighthouse has the AcceptJson middleware enabled by default. I consider it's harmful as it makes the CSRF attack easier.

Of course, this protection should be removable, but it's better if it's enabled by default. If the user decides to remove it, they should understand possible consequences.

I agree it's a good idea to add `application/graphql` as valid too.

**Comment by spawnia** [comment]
Thank you so much for this issue and great discussion, you really thought this one through. Nice job.

> 1) removing the AcceptJson middleware from the default lighthouse config. Add a warning, that enabling this middleware may cause your application to be vulnerable to CSRF attacks.

We should either disable it by commenting out the inclusion, so it can be easily enabled, or remove entirely. Not sure yet.

2) accepting only POST requests

That will have to be configurable, for instance we use GET as part of our application (for queries only).

3) adding the "EnforceJsonContentType" middleware, which rejects any request that doesn't have a "Content-type" request header set to "application/json".

As mentioned, support for `"application/graphql"` would be great, too. I am planning to use https://github.com/laragraph/utils/blob/master/src/RequestParser.php in the upcoming v5 of Lighthouse, you can poke around in there.

4) adding an explanation to the documentation why these middlewares should be changed very cautiously or with understanding of the possible caveats.

That's a great idea regardless of implementation changes.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v5.32.0
