### ISSUE TITLE
Lumen - Ligh

### ISSUE THREAD

**Issue by Mihai-github** [nuwave/lighthouse#1586]
Hi,

    I'm working on a project with Lumen as backend server and i am using lighthouse as graphql support. I'm currently facing a issue with the directive for @create and i don't really know why it does not work... even if i am trying to use the @create directive that is in the documentation and for some kind of reason does not work..
    I hope someone can help me, Thanks
   This is the error i get :
 "Target [Nuwave\Lighthouse\Support\Contracts\GlobalId] is not instantiable while building [Nuwave\Lighthouse\Schema\Directives\CreateDirective]."

------------------------------------------------------------------
type Mutation{
 createUser(name: String!): User! @create}

type User {
    id: ID!
    name: String!
    email: String!
    cnp: String!
}

**Comment by rares-lupascu** [comment]
same here ... btw the version i am using is: lumen v8 and lighthouse v5.0-alpha.4

**Comment by rares-lupascu** [comment]
same on v4.17

**Comment by spawnia** [comment]
You will have to register the `GlobalIdServiceProvider`.
