### ISSUE TITLE
Method signature issues in LighthouseServiceProvider#loadRoutesFrom

### ISSUE THREAD

**Issue by voydz** [nuwave/lighthouse#1590]
**Describe the bug**

Lighthouse is not able to fire up its service provider in Laravel 8.11.x due to https://github.com/laravel/framework/pull/34866

For example running `php artisan` results in an ErrorException with message `Declaration of Nuwave\Lighthouse\LighthouseServiceProvider::loadRoutesFrom($path): void should be compatible with Illuminate\Support\ServiceProvider::loadRoutesFrom($path, array $attributes = Array)`

**Expected behavior/Solution**

Running `php artisan` or any other way of booting a Laravel application running fine.

**Steps to reproduce**

1. Install Laravel 8.11.x
2. `php artisan`
3. get an `ErrorException`

**Output/Logs**

<details><summary>Click to expand</summary>

```
 ErrorException 

  Declaration of Nuwave\Lighthouse\LighthouseServiceProvider::loadRoutesFrom($path): void should be compatible with Illuminate\Support\ServiceProvider::loadRoutesFrom($path, array $attributes = Array)

  at vendor/nuwave/lighthouse/src/LighthouseServiceProvider.php:193
```

</details></br>

**Lighthouse Version**

using the latest version 4.17.0

Note: PR is incomming.

best regards

**Comment by voydz** [comment]
It seems the change was reverted in laravel/framework@7fff6ea.

**Comment by spawnia** [comment]
@voydz thanks for looking into this and notifying the Laravel team about the breakage. Looks like we are good for now, let's close the issue then?

**Comment by voydz** [comment]
@spawnia Sounds fine to me ;)
