### ISSUE TITLE
"@guard" directive is fired, fails on queued subscription broadcast

### ISSUE THREAD

**Issue by GregPeden** [nuwave/lighthouse#1607]
**Describe the bug**

The @guard directive requires general login auth to use the GraphQL services within its scope. When a Subscription is guarded with @guard with a Redis broadcaster set up to handle the broadcasting service, the Guard directive is run on the job queue instance which is processing the broadcast event, at which point the context has changed. An application using the "api" auth guard will not fail the @guard test because the authorization header is missing, but there's no reason for @guard to run in this context because it amounts to the application guarding against itself.

If the broadcaster is configured to not queue, the task completes as expected, because it is fulfilled in the main thread.

**Expected behavior/Solution**

Guard directive should not be applied to Laravel job queue instances or some other method of disabling on subscription events should be provided.

**Steps to reproduce**

1. Set up subscription with Redis-based broadcaster such as https://github.com/thekonz/lighthouse-redis-broadcaster/pulls
2. Broadcast an event on a subscription with "@guard" directive.
3. Check the event contents and see it will always be "null" value. The auth error is stripped from the data set before packaging for broadcast.

**Output/Logs**

See description

**Lighthouse Version**

Latest

**References**

Past issue regarding auth on subscription: https://github.com/nuwave/lighthouse/issues/1302
PR which provides the user in context without actually performing authentication, thus auth checks still fail. https://github.com/nuwave/lighthouse/pull/1306

**Comment by SirLamer** [comment]
For now I am addressing this by having taken the guard directive off my subscriptions. The authorization test in the Subscription class will stand in for this, however I still like having the guard directive on top as it acts as an additional authorization gate which has consistent expectations and behavior across all uses so I can trust it more than the per-case auth test being written for each subscription.

**Comment by Mihai-github** [comment]
hi, have you made lighthouse subscriptions work like they suppose to work? I'm asking because i've tried also to make use on subscriptions for the project i'm working on and something does not work like it supposed to work and there is not too much info about this topic..

**Comment by SirLamer** [comment]
Yes but that broad issue is really outside of the scope of this issue discussion. Try the slack channel here: https://app.slack.com/client/TB351UQ6A/CB28A070S

**Comment by stayallive** [comment]
There is a partial solution for this already in place although it's currently broken...

There is a `Nuwave\Lighthouse\Subscriptions\Iterators\AuthenticatingSyncIterator` which is supposed to fix this exact issue but with the latest changes to Lighthouse this is no longer working but should be the solution to your issue.

I believe this PR should solve the issue if you use the `AuthenticatingSyncIterator`: #1768.

**Comment by spawnia** [comment]
I added a failing test case here https://github.com/nuwave/lighthouse/pull/1769, does that reflect your scenario?

**Comment by stayallive** [comment]
Yes and no. 

I think it's testing the right thing _but_ the `@guard(with: "api")` will mess it up anyway.

This PR does not solve that, just the `@guard` without a selected guard name (so using the default guard).

Although this does point out that that case is still a bug that remains even with this PR.

**Comment by spawnia** [comment]
The test passes with just `@guard` though.

**Comment by stayallive** [comment]
In my case I have the `@guard` on the subscription itself too:

```
extend type Subscription @guard {
    updatePost: Post
}
```

Possibly I mistaken 2 things.

The actual problem is that the subscription is registered just fine but once you broadcast an event to the subscription it broadcasts an `Unauthorized` response and closes the websocket connection.

Although I must admit I would have thought `@guard` on a field in the response should fail too...
