### ISSUE TITLE
@search directive is used on first level field in query

### ISSUE THREAD

**Issue by alireza-a2f** [nuwave/lighthouse#1612]
Here is my graphql schema:

```graphql
type User {
  id: ID!
  username: String
  certificates(q: String @search): [Certificate]
}

type Certificate {
  id: ID!
  subject: String
}

extend type Query {
  users(q: String @search): [User]
  @paginate(type: "paginator" defaultCount: 10 maxCount: 100 model: "App\\Models\\User")
}
```

I have properly defined Laravel's relations (User->certificates) and the `certificates` function gets a `q` to do the search.

When I use `q` in `certificates` on `User` type while running a query, it calls the search function on the user model instead of certificate. I guess it should have a parameter called `model` or understand it somehow to call the child's search function.

**Comment by spawnia** [comment]
Please provide a PR with a failing test case. https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/SearchDirectiveTest.php

**Comment by olivernybroe** [comment]
When testing out with the provided example, I was not able to reproduce this. 

So we would need a failing test case or a demo app for reproducing, if that is supplied I will reopen this issue.

**Comment by spawnia** [comment]
Also, `@search` was recently completely reworked. Try `dev-master`.
