### ISSUE TITLE
DateTimeTz parses and formats differently

### ISSUE THREAD

**Issue by petecoop** [nuwave/lighthouse#1619]
**Describe the bug**

`DateTimeTz` formats and parses with different formats as Carbon's `toIso8601String()` is an alias to `DateTime::ATOM` but formats with `DateTime::ISO8601`

[See this note in the PHP docs](https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601)

**Expected behavior/Solution**

Parses and formats in the same way

**Comment by spawnia** [comment]
Please provide a PR with a failing test case.

**Comment by petecoop** [comment]
I don't have a failing test case, it was mainly an observation that in the code these are different. It appears that both `DateTime::ISO8601` and `DateTime::ATOM` when used as a format in `DateTime::createFromFormat` both produce the same result when using either format.

One place where the docs don't match the output is [here](https://github.com/nuwave/lighthouse/blob/d926acd45573a758bbddc0c11321f8fa18740ce2/docs/4.12/api-reference/scalars.md#datetimetz) the output is formatted as `Y-m-dTH:i:sP` rather than `Y-m-dTH:i:sO`

**Comment by spawnia** [comment]
Thanks for the report and 🤦 for PHP.
