### ISSUE TITLE
@scope directive is not behaving as it should be

### ISSUE THREAD

**Issue by canatufkansu** [nuwave/lighthouse#1621]
**Describe the bug**

@scope directive is not working as it should be. Even when client sets the related variable FALSE, Lighthouse still applies the scope. It only removes the scope when variable not exists at all in the client query.

**Expected behavior/Solution**

Directive should add the the scope when when client sets the related boolean variable TRUE and remove the scope when client sets the variable to FALSE.

I have already open a issue on Stackoverflow about this topic, someone defined the solution.
https://stackoverflow.com/questions/64915622/what-is-the-correct-way-of-using-scope-directive

Following fixes the problem:

```
public function handleBuilder($builder, $value)
    {
        $scope = $this->directiveArgValue('name');

        try {
            if ($value === true) {
                return $builder->{$scope}();
            }
            return $builder;
        } catch (BadMethodCallException $exception) {
            throw new DefinitionException(
                $exception->getMessage()." in {$this->name()} directive on {$this->nodeName()} argument.",
                $exception->getCode(),
                $exception->getPrevious()
            );
        }
    }
```

**Steps to reproduce**

1. Define a simple query
2. Define a scope in the related model
3. Use @scope directive to define the scope into the query
4. From the client set the variable to false
5. You will see directive still applies the scope even variable is false

**Lighthouse Version**

4.18.0

**Comment by spawnia** [comment]
You are misunderstanding. See https://lighthouse-php.com/master/api-reference/directives.html#scope

> The scope method will receive the client-given value of the argument as the second parameter.

Your scope should react to the argument the client passes.
