### ISSUE TITLE
No directive found for "validator"

### ISSUE THREAD

**Issue by DavidSprauel** [nuwave/lighthouse#1625]
I'm trying to create a project with lighthouse and as I'm creating my mutation i'd like to bind an input to a validator but the directive doesn't seems to exists.
Although it is documented in the doc as well as the command `php artisan lighthouse:validator UpdateUserInputValidator`

My lighthouse version `4.18`

**Comment by spawnia** [comment]
Please link the relevant docs.

**Comment by DavidSprauel** [comment]
Ok I've followed the link in the tutorial tab to get the doc `Validate the inputs that are sent to your server` which redirect to `https://lighthouse-php.com/master/security/validation.html` and yes it is master, which I believe is alpha 5. version.

After checking the 4.18 doc. There is another way to do it. My bad.

Shouldn't the tutorial links assume that we are running the last stable version ?

**Comment by spawnia** [comment]
> Shouldn't the tutorial links assume that we are running the last stable version ?

That would be nice, yeah.
