### ISSUE TITLE
Regression: Mutation input object is not @spread before running field @rules

### ISSUE THREAD

**Issue by arrisar** [nuwave/lighthouse#1631]
**Version:** 5.0-beta1

In version 4, the following input would be spread and then the validation rules applied, so that the error messages would come back as such e.g. `The new_password must be at least 6 characters.`, but is now returning as `input.new_password`.

Is this an intentional regression? 

```
input UpdatePasswordInput {
    id: ID!
    old_password: String! @rules(apply: ["password"])
    new_password: String! @rules(apply: ["confirmed", "min:6"])
    new_password_confirmation: String!
}

extend type Mutation {
    updatePassword(input: UpdatePasswordInput! @spread): User
        @field(resolver: "Users@updatePassword")
        @can(ability: "update", find: "id")
        @guard
}
```

Please let me know if there is any more information I could provide to help identify the cause/describe the issue better.

**Comment by spawnia** [comment]
Yes, this is intentional - but we should definitely mention it in the CHANGELOG.

Whereas previously the server leaked implementation details, now the validation error comes in the exact shape that an unaware client would expect. They do not know about `@spread`.
