### ISSUE TITLE
Extending type with a interface does not add interface

### ISSUE THREAD

**Issue by olivernybroe** [nuwave/lighthouse#1634]
**Describe the bug**

When extending a type and adding an interface in that extension, the interface is not added to the type in the final schema

**Expected behavior/Solution**

The expected behavior is that the type is now part of the interface.

**Steps to reproduce**

```gql
interface Card {
    name: String
    picture: String
}

extend type User implements Card
```

**Lighthouse Version**

`v5.0-beta.1`

**Comment by olivernybroe** [comment]
@spawnia This might be an issue at https://github.com/webonyx/graphql-php/ ?

**Comment by olivernybroe** [comment]
According to specs, this should be supported http://spec.graphql.org/June2018/#sec-Object-Extensions

**Comment by spawnia** [comment]
We need to implement this in Lighthouse. Object type extensions are applied at https://github.com/nuwave/lighthouse/blob/cd6392c0305601ffae71a0390d15cf17057924b9/src/Schema/AST/ASTBuilder.php#L202

**Comment by spawnia** [comment]
@olivernybroe can you give this a go?

**Comment by olivernybroe** [comment]
@spawnia of course! 

Been a while since I contributed 👍
