### ISSUE TITLE
namespaceClassName() must be of the type string, null given

### ISSUE THREAD

**Issue by tevva** [nuwave/lighthouse#1643]
### Argument 1 passed to Nuwave\\Lighthouse\\Schema\\Directives\\BaseDirective::namespaceClassName() must be of the type string, null given, called in .../vendor/nuwave/lighthouse/src/Schema/Directives/EventDirective.php on line 46".

All mutations are giving this error back after upgrading to v4.18.0, whereas queries working fine.

this method $eventBaseName = $this->directiveArgValue('dispatch') returns null instead of some string.

Laravel 8.0
Lighthouse 4.18.0

**Comment by spawnia** [comment]
I suspect you were running v3 before where the two aliases `fire` and `class` were supported. Just check all your usages of `@event` and rename the argument to `dispatch`.

**Comment by tevva** [comment]
yes, it helped, thank you.
