### ISSUE TITLE
Policy method not beeing called

### ISSUE THREAD

**Issue by Mihai-github** [nuwave/lighthouse#1652]
Hi,
    
    Using @can directive for authorize queries and mutation does not work. The method inside the policy class created for the model is not called, but in the constructor of the policy class I can use dd() and i get it. So from my understanding the class is recognized by Lighthouse, but the method not.
 
Mutation -> createAttribute(input: IAttributeCreate! @spread): Attribute
                    @can(ability: "create")
                    @guard(with: ["luceer"])
                    @upsert

PolicyClass -> 
public function create(User $user): bool
    {
        dd('here');
        // return $user->is_admin;
    }
Hope someone can explain why the create() method is not called

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
