### ISSUE TITLE
Cannot publish schema on fresh install.

### ISSUE THREAD

**Issue by pvk-dev-env** [nuwave/lighthouse#1654]
Fresh install using Lighthouse 5.0 does not allow publishing schema when following the docs.

I have an existing 8.x Laravel project. According to the 5.0 docs, i need to require trough composer and publish the schema. Whenever i try to publish the schema, i receive an ErrorException. It seems the makeDirectory is called within Filesystem with an empty string. 

In `LighthouseServiceProvider.php` it tries to load using the config key: `lighthouse.schema.register`. It might have to do something with this.

**Steps to reproduce**

1. Fresh project ( I'm using an existing one).
2. run  `composer require nuwave/lighthouse`.
3. run `php artisan vendor:publish --tag=lighthouse-schema`.

**Output/Logs**

```
$ php artisan vendor:publish --tag=lighthouse-schema

   ErrorException

  mkdir(): Invalid path

  at F:\xxxxx\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:581
    577▕         if ($force) {
    578▕             return @mkdir($path, $mode, $recursive);
    579▕         }
    580▕
  ➜ 581▕         return mkdir($path, $mode, $recursive);
    582▕     }
    583▕
    584▕     /**
    585▕      * Move a directory.

  1   F:\xxxxx\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:581
      mkdir("")

  2   F:\xxxxx\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:263
      Illuminate\Filesystem\Filesystem::makeDirectory("")
```

</details></br>

**Laravel Version** : 8.7
**Lighthouse Version** : 5.0

**Comment by spawnia** [comment]
The following worked for me without any issue:

```sh
curl -s https://laravel.build/example-app | bash
cd example-app
./vendor/bin/sail up -d
./vendor/bin/sail composer require nuwave/lighthouse
./vendor/bin/sail artisan vendor:publish --tag=lighthouse-schema
```

If you can pinpoint a bug that we can solve - perhaps in the `LighthouseServiceProvider` - feel free to reopen or provide a PR.
