### ISSUE TITLE
Combine eager-loads that are the same together

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1665]
**What problem does this feature proposal attempt to solve?**

In queries that involve multiple eager-loads on the same model, multiple database calls are made.

```graphql
type Post {
  comments: [Comment!]! @hasMany
  someFieldInvolvingComments: Int @with(relation: "comments")
  anotherField: String @with(relation: "comments")
}
```

This query would cause the same eager-load on `comments` to be done 3 times.

```graphql
{
  posts {
    comments
    someFieldInvolvingComments
    anotherField
  }
}
```

Lighthouse does not recognize that eager-loading `comments` once suffices when the different fields are called.

**Which possible solutions should be considered?**

On a given model, eager-loads of the same relation should be combined.

There can be some tricky edge-cases, for instance if one of the eager-loads imposes query conditions on the relation:

```graphql
{
  posts {
    comments(last: 20)
    someFieldInvolvingComments
  }
}
```

@ipalaus

**Comment by mrjandejong** [comment]
This would definitely be an improvement. It's a bit unfortunate the same query is repeated per field, although it's still miles better than n+1.

Maybe it could be "fixed" with the following syntax?

```
type Post @with(relation: "comments") {
  comments: [Comment!]! @hasMany
  someFieldInvolvingComments: Int
  anotherField: String
}
```

Although I'm not sure this is "correct" graphql syntax.

**Comment by cradigan** [comment]
Put in a pull request as a more detailed example of what I'm thinking. A couple tests are failing that have to do with creating custom batch loaders using the BatchLoaderRegistry. But i only see BatchLoaderRegistry being used in 2 places which have been updated.  We should be able to fix the tests by just adding the additional data required.

**Comment by spawnia** [comment]
Thanks @cradigan, I incorporated your idea into #1849
