### ISSUE TITLE
OR conditions behaving like AND when using for conditions with HAS for nested relations

### ISSUE THREAD

**Issue by clayzar** [nuwave/lighthouse#1677]
**Describe the bug**

I'm trying to query for products that are in a category or its subcategories. Categories can have one `parent`, and products can `belongToMany` `categories`. When using an array of `OR` conditions to apply to the relationship `categories` for for the `product` type, the query generated uses `AND` instead of `OR`. See the graphql query here and the SQL output further below.

```graphql
query ($where: WhereConditions) {		
  products(where: $where) {
    data {
      id
      title
    }
  }
} 

variables: {
  "where": {
    "HAS": {
      "relation": "categories",
      "condition": {
        "OR": [   // Currently both of these conditions must be met, which is incorrect and never returns products
          {
            "column": "categories.id",
            "value": 375          
          },
          {
            "HAS": {
              "relation": "parent",
              "condition": {
                "column": "id",
                "value": 375
              }
            }
          }
        ]
      }
    }
  }
}
```

If I remove one of the conditions in the `OR` array above, two different sets of products are returned, but I need the `OR` to properly apply these conditions so that I retrieve both sets of products together.

**Expected behavior/Solution**

I'd imagine this would be an update to use one of the Laravel query builder `orWhere..` clauses, but I haven't yet traced the code in lighthouse to see where the exact issue is. 

**Steps to Reproduce**

Run newly added test `Tests\Integration\WhereConditions\WhereHasConditionsDirectiveTest::testWhereHasBelongsToManyOrNestedConditions`

**Output/Logs**

<details><summary>Click to expand</summary>
  
  
The 2nd `AND` below should be an `OR` operator

```sql
SELECT count(*) AS AGGREGATE 
FROM `products` 
WHERE (EXISTS (
	SELECT * FROM `categories` 
	INNER JOIN `category_product` ON `categories`.`id` = `category_product`.`category_id` 
	WHERE `products`.`id` = `category_product`.`product_id` 
	AND (
		`categories`.`id` = 375 
		AND (EXISTS (
			SELECT * FROM `categories` AS `laravel_reserved_0` WHERE `laravel_reserved_0`.`id` = `categories`.`parent_id` AND `categories`.`id` = 375
		))
	)
))
```

</details></br>

**Lighthouse Version**

Lighthouse v5

**Comment by spawnia** [comment]
A PR with a failing test would be great. You can just add to the existing tests for `@whereHas`

**Comment by spawnia** [comment]
Fixed in https://github.com/nuwave/lighthouse/releases/tag/v5.2.0
