### ISSUE TITLE
Custom resolver throw Laravel Error

### ISSUE THREAD

**Issue by Mihai-github** [nuwave/lighthouse#1680]
hi,
   How can i throw errors that are send to the client inside a custom resolver for  a mutation or query, because I've checked Laravel docs about handling errors and nothing works like I think should be.
Ex: 
1. sending with like a json response not working 
2. try{}catch(){} same thing

Maybe someone can explain me how to do it, I hope :).

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
