### ISSUE TITLE
Events to be able to perform high level query profiling

### ISSUE THREAD

**Issue by stayallive** [nuwave/lighthouse#1688]
**What problem does this feature proposal attempt to solve?**

For implementing query profiling like for [Sentry performance](https://sentry.io/for/performance/) features and other profiling applications some information should be surfaced from Lighthouse.

**Which possible solutions should be considered?**

This was shortly discussed in the Lighthouse Slack, and the following was surfaced that should be enough to get started.

4 types of events should be triggered on a GraphQL request (the transport doesn't matter):

- [x] `StartRequest`: Marks the start of handling a GraphQL request
- [x] `StartQuery`: Marks the start of handling a GraphQL query/mutation/subscription
- [x] `EndQuery`: Marks the end of handling the last started query
- [x] `EndRequest`: Marks the end of handling the last GraphQL request

Requests should not be nested so a start and end event should be sufficient.

The start and end query could be triggered multiple times per request because of batch requests.

The `StartQuery` event should at least carry the name of the current operation (if set).

---

Feel free to expand on this if needed and or suggest better event naming.

It should also be noted that profiling of individual resolvers should not be done with events but can already be implemented like [tracing](https://github.com/nuwave/lighthouse/tree/464ae4c4228c9b3d7542ca236c2cc8a7b27b0af4/src/Tracing) is currently implemented.

**Comment by spawnia** [comment]
`StartQuery` should contain the AST of the query string, so Sentry can easily get a hold of the requested root fields.

Those can then be sorted and be added to the transaction name. The relatively meaningless transaction name `graphql` can then be added to, for `query { foo, bar }` it would become `graphql.query{bar,foo}`.

**Comment by spawnia** [comment]
Released in https://github.com/nuwave/lighthouse/releases/tag/v5.3.0
