### ISSUE TITLE
Allow magic __get method to return data

### ISSUE THREAD

**Issue by jordyvanderhaegen** [nuwave/lighthouse#1693]
**What problem does this feature proposal attempt to solve?**
Currently it does not seem possible to return data using PHP's magic __get method. This comes in handy when you want to call properties on your model based on some logic involving the key. E.g. when returning localized fields ```return parent::__get($key . '_' . app()->getLocale());```

**Which possible solutions should be considered?**
I've gone ahead and created a [failing PR](https://github.com/nuwave/lighthouse/pull/1692). Not sure where I'd have to start on this, so any advice is welcome!

**Comment by spawnia** [comment]
It is considered best practice to use `isset()` before accessing magic properties. The default field resolver works: https://github.com/webonyx/graphql-php/blob/115a20e419439a27092788cdf36f1ac5f0fa429b/src/Executor/Executor.php#L180-L184

Given a proper implementation: https://github.com/webonyx/graphql-php/blob/115a20e419439a27092788cdf36f1ac5f0fa429b/tests/Executor/ExecutorTest.php#L1329-L1351

**Comment by jordyvanderhaegen** [comment]
Thanks for sharing, models implement the `ArrayAccess` interface so they will never reach the `is_object()` check, hence why `__get` does not work. You could solve this by overwriting the `toArray` method if you wanted. In the end it made more sense to use a custom field resolver.
