### ISSUE TITLE
How to disable the extensions section?

### ISSUE THREAD

**Issue by martio** [nuwave/lighthouse#1702]
How to disable the extensions section?

```
{
  "data": {
    "users": {
      "data": [
        {
          "id": "1",
          "name": "martio"
        }
      ],
      "paginatorInfo": {
        "currentPage": 1,
        "lastPage": 4
      }
    }
  },
  "extensions": {
    "lighthouse_subscriptions": {
      "version": 1,
      "channels": []
    }
  }
}
```

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
