### ISSUE TITLE
Form validation fails when referencing any other input field

### ISSUE THREAD

**Issue by ssi-anik** [nuwave/lighthouse#1712]
**Describe the bug**
I was checking the `required_without` validation rule for two fields. And it failed when referencing each other.
![image](https://user-images.githubusercontent.com/2676602/106356574-e5cb1500-632a-11eb-99c0-ac94ec17edd0.png)

**Expected behavior/Solution**
If referencing to any other fields, then it should mention the input argument and dot notation. like `myInput.form_field`. And this is nowhere mentioned in the documentation. Then it's a suggestion to add in the documentation. If it's expected to behave like laravel form validation, it is a bug I guess.

**Lighthouse Version**
**5.1.0**

**Comment by spawnia** [comment]
I don't see how this could work any other way, Laravel also requires you to pass in the path if you are comparing nested attributes.
