### ISSUE TITLE
Echo subscription driver: Bug, Inconsistency, Missing documentation

### ISSUE THREAD

**Issue by ssi-anik** [nuwave/lighthouse#1724]
**Describe the bug**
I was trying to figure out the subscription with the `echo` driver. I found the following things are wrongly done. 

- Package generates a unique **private** channel to listen to as named `private-*`
https://github.com/nuwave/lighthouse/blob/dba839e85631f2262c12d7e5c96b8b25048001f6/src/Subscriptions/Subscriber.php#L170-L173

But when broadcasting, it then broadcasts to a presence channel. which prepends `presensce-` to the channel making `presence-private-lighthouse-*`. So, it should always be handled as a presence channel? https://github.com/nuwave/lighthouse/blob/dba839e85631f2262c12d7e5c96b8b25048001f6/src/Subscriptions/Events/EchoSubscriptionEvent.php#L29-L32

- Is it intentional to keep separate event names?
https://github.com/nuwave/lighthouse/blob/dba839e85631f2262c12d7e5c96b8b25048001f6/src/Subscriptions/Events/EchoSubscriptionEvent.php#L41
https://github.com/nuwave/lighthouse/blob/dba839e85631f2262c12d7e5c96b8b25048001f6/src/Subscriptions/Broadcasters/PusherBroadcaster.php#L14

- Even if user wants to publish the subscription data in `sync`, it gets pushed to the queue.
https://github.com/nuwave/lighthouse/blob/dba839e85631f2262c12d7e5c96b8b25048001f6/src/lighthouse.php#L313
Because, it uses `ShouldBroadcast`, which is pushed to the queue. It should be [`ShouldBroadcastNow`](https://github.com/illuminate/broadcasting/blob/feb1cb1da7e7670d8fa02220e42581ff99a42d78/BroadcastManager.php#L115-L117) to send it in sync manner.
https://github.com/nuwave/lighthouse/blob/dba839e85631f2262c12d7e5c96b8b25048001f6/src/Subscriptions/Events/EchoSubscriptionEvent.php#L8

- To broadcast a message through the `echo` driver, it requires to install `illuminate/broadcasting` package when using Laravel. If using pusher, it's not required. It's not mentioned in the documentation.

**Lighthouse Version**: * v5.1.0

**Comment by spawnia** [comment]
@stayallive @alberthaff what do you think?

**Comment by ssi-anik** [comment]
Implemented the echo driver here: https://github.com/ssi-anik/confession-wall/blob/graphql/graphql/schema.graphql#L22
and here: https://github.com/ssi-anik/lighthouse-laravel-websockets/blob/master/resources/js/echo.link.js

**Comment by stayallive** [comment]
It looks like there are some things going wrong in the Echo driver indeed.

The channel name and it using a presence channel are from what I can tell wrong indeed (the channel name with a private channel would also not work because it will prepand another `private-` to it so that needs some changing).

And the `ShouldBroadcast` causes the broadcast to be queued again basically double queuing Laravel Echo messages.

The event name is confusing but not a bug but would be nice to keep them in sync.

> To broadcast a message through the echo driver, it requires to install illuminate/broadcasting package when using Laravel. If using pusher, it's not required. It's not mentioned in the documentation.

This one I'm not sure, because for Pusher you also need that package for it to register `Pusher` in the container, but you could do that manually I guess. But this is a Lumen "issue".

@ssi-anik I think we could all agree we'd be happy to get a PR solving the issues since you seem to be actively using it with Laravel Echo, would you be up for that?

**Comment by ssi-anik** [comment]
@stayallive Yes, I can help with it. But I lack the knowledge of testing. So, I can send a PR but if you're looking for testing, then you'll have to help me out.

**Comment by spawnia** [comment]
Just look at the existing tests related to subscriptions and consider https://github.com/nuwave/lighthouse/blob/master/CONTRIBUTING.md.

**Comment by ssi-anik** [comment]
I'm interested in working on this issue. I need some time to start working on it. If someone starts before me, then please give a heads-up here. And, the slack invitation has expired. I Will ask a few questions when I start working.
Thanks.
![image](https://user-images.githubusercontent.com/2676602/107114462-275e4180-6890-11eb-9213-80abdc9b8e5e.png)

**Comment by stayallive** [comment]
This invite link should work: [Slack invite](https://join.slack.com/t/lighthouse-php/shared_invite/zt-4sm280w1-wu21r94f3kLRRtBXRbXVfw).

Where did you find that expired link? The on in the readme works fine.

**Comment by spawnia** [comment]
> Where did you find that expired link? The on in the readme works fine.

That is because i just updated it 😉

**Comment by alberthaff** [comment]
Sorry for the late reply. 
I have no experience with the echo driver. But something definitely seems wrong with the channel names and queuing.

Regarding the docs - i actually can't find anything about the echo driver, except the client implementation. If we are supporting multiple drivers, maybe we should add a section about the individual drivers, their requirements and client-implementations.
