### ISSUE TITLE
[Feat] Add @all field directive to query all models

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#173]
At the moment, if you want to the query filter arguments, you have to have a field directive like `@paginate` or `@hasMany`.

There are cases where i want to have a list of models without pagination. Can we just extend the `@model` directive to work with fields, too?

**Comment by chrissm79** [comment]
Do you mean off the root query? You can already define a relationship w/ `@hasMany` and just ignore the `type` and it will provide you with a list of related models w/out pagination.

**Comment by chrissm79** [comment]
I guess we could do that for convenience. I'm wondering if we should force it to be used on the `Query` or `Mutation` type to prevent people from defining on a field that should be a relationship and they fall into an N+1 issue?

**Comment by spawnia** [comment]
I think that mentioning it in the docs will suffice. Who knows, maybe there is a use case where you want to query some model that is not actually a relation, or you specifically want to the different queries. The other model might reside in a different database. I think it is best to keep the options open.

**Comment by spawnia** [comment]
Hey @robsontenorio 

We will have to expand the functionality of the `@model` directive. I am not sure when we will get to implement this, but i plan to do it.

If you want this issue to move along a bit quicker, feel free to dig into the code and submit a PR. I suggest to look at `PaginateDirective` or `HasManyDirective` an go from there. Now that you have mentioned it, `@all` seems like the best name, it is most closest to what Laravel is doing.

**Comment by spawnia** [comment]
@robsontenorio this is now implemented, feel free to try it on `dev-master`

**Comment by robsontenorio** [comment]
Thank you very much!

—
Robson Tenório

Em 13 de jul de 2018, à(s) 10:33, Benedikt Franke <notifications@github.com> escreveu:
