### ISSUE TITLE
@whereraw directive

### ISSUE THREAD

**Issue by wvffle** [nuwave/lighthouse#1731]
**What problem does this feature proposal attempt to solve?**
I'm trying to match both `name` and `lastname` columns against a single string. 

As far as I know, in SQL query I could do 
```sql
... where concat(name, " ", lastname) like "John Sm%"
``` 

I saw that laravel query builder has `whereRaw()`, so why don't add such directive?

**Which possible solutions should be considered?**
Using @whereConditions with an enum:
```gql
enum ClientName {
  FIRSTNAME @enum(value: "name")
  LASTNAME @enum(value: "lastname")
  FULLNAME @enum(value: "CONCAT(name, ' ', lastname)")
}

``` 
though an error occurs: `Column names may contain only alphanumerics or underscores, and may not begin with a digit, got: CONCAT(name, ' ', lastname)`

**Comment by spawnia** [comment]
> why don't add such directive?

Because it would create a massive security hole.

**Comment by spawnia** [comment]
You can use `@builder` for more exotic needs such as yours, see https://lighthouse-php.com/master/api-reference/directives.html#builder. When grabbing the value off of an Enum you defined yourself, it should be safe, but in the general case I think offering such a directive could encourage bad practices.

**Comment by wvffle** [comment]
Great! Totally understood. I somehow missed this directive. Works like a charm :)
