### ISSUE TITLE
 Lighthouse debug flag does not apply internally because the error formatter is never set

### ISSUE THREAD

**Issue by sudo-rm-rf-star** [nuwave/lighthouse#1737]
**Describe the bug**

Lighthouse debug flag does not apply internally. I've set the debug flag to `DebugFlag::RETHROW_INTERNAL_EXCEPTIONS | DebugFlag::RETHROW_UNSAFE_EXCEPTIONS` but errors are still caught and returned by a formatted GraphQL response rather than thrown. I've validated that `config('app.debug')` evaluates to true and `config('lighthouse.debug')` evaluates to 12 when running the code.

Diving deeper I find that [`setErrorFormatter`](https://github.com/webonyx/graphql-php/blob/master/src/Server/Helper.php#L327) is never called so that the error formatter is always `null` (This statement is never reached). Because of this  `null` is passed as `$formatter` to [`prepareFormatter`](https://github.com/webonyx/graphql-php/blob/master/src/Error/FormattedError.php#L282) and therefore [`addDebugEntries`](https://github.com/webonyx/graphql-php/blob/master/src/Error/FormattedError.php#L230) is never called

**Expected behavior/Solution**

The error should be thrown rather than handled and returned as a GraphQL response.

**Steps to reproduce**

1. Set the `debug` variable in `config/lighthouse.php` to `    'env('LIGHTHOUSE_DEBUG', DebugFlag::RETHROW_INTERNAL_EXCEPTIONS | DebugFlag::RETHROW_UNSAFE_EXCEPTIONS),
`

2. In `.env` set `APP_DEBUG=true`

**Lighthouse Version**

Latest version (5.2)

**Comment by spawnia** [comment]
Can you try `dev-master`? I just added a change that moves the application of the error handlers, see https://github.com/nuwave/lighthouse/commit/0700b852f5254d935bf4ca0de1fb2860515c6305#diff-b5058d60785844bf987a9224b3ad1af86e5b23e2f979395a4e1f9262d2dea92b

**Comment by sudo-rm-rf-star** [comment]
Thanks for the response. This did not resolve the issue.

**Comment by spawnia** [comment]
What error are you throwing?

**Comment by sudo-rm-rf-star** [comment]
Any unexpected error when resolving the request. E.g. I have the following resolver: 

```
<?php

namespace App\Checkout\Http\GraphQL\Mutations;

use App\Checkout\Application\Repositories\CheckoutRepository;
use App\Checkout\Domain\Entities\Checkout;

class CheckoutCreateOrUpdate
{
    /**
     * @var CheckoutRepository
     */
    private $checkoutRepository;

    public function __construct(CheckoutRepository $checkoutRepository)
    {
        $this->checkoutRepository = $checkoutRepository;
    }

    /**
     * @param null $_
     * @param array<string, mixed> $args
     * @return Checkout
     */
    public function __invoke($_, array $args): Checkout
    {
        throw new \Exception();
        return $this->checkoutRepository->updateOrCreateCheckout($args['input']);
    }
}
```

In this case, I would like the exception to be thrown rather than returned as a response for debugging purposes.

**Comment by spawnia** [comment]
I added a test case in https://github.com/nuwave/lighthouse/pull/1738. Please try and add a test that recreates what happens in your app.

**Comment by sudo-rm-rf-star** [comment]
Thanks for the test case. This helped a lot trying to figure out the difference between both environments. 

In my environment I was using the [default render method](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/Handler.php#L309-L340). In the test suite for lighthouse, you've overriden the default behaviour with: 

```
    public function render($request, Throwable $e)
    {
        throw $e;
    }
```

So that the result is not converted into a response, but just thrown.

**Comment by spawnia** [comment]
Given the exception reaches `ExceptionHandler::render()`, Lighthouse behaves as expected.
