### ISSUE TITLE
Validation rule `required_without` on input values requires full path

### ISSUE THREAD

**Issue by sudo-rm-rf-star** [nuwave/lighthouse#1740]
**Describe the bug**

For the keyword `required_without` to work within the validator of an input type, we need to add the name of the validator part of the `required_with` statement. Please see the example under **steps to reproduce**

**Expected behavior/Solution**
See the first test case under steps to reproduce. We need to be able to pass the root fields of the input object to `required_without`

**Steps to reproduce**
Reproduced part of this draft pull request: https://github.com/nuwave/lighthouse/pull/1739

**Lighthouse Version**
Master

**Comment by spawnia** [comment]
Thanks for the issue and especially the PR. It is not like the rule does not work at all, but rather that it requires hardcoding the full input path. I think that Lighthouse should take care of the nested input paths to enable reuse of `input` types with validation rules in multiple places.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/pull/1739

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/pull/1739
