### ISSUE TITLE
@whereConditions: impossible to limit relation name

### ISSUE THREAD

**Issue by LastDragon-ru** [nuwave/lighthouse#1754]
**Describe the bug**

Currently `@whereConditions HAS` defined as:

```
input QueryWhereWhereConditionsRelation {
  # The relation that is checked.
  relation: String!

  # The comparision operator to test against the amount.
  operator: SQLOperator = GTE

  # The amount to test.
  amount: Int = 1

  # Additional condition logic.
  condition: QueryWhereWhereConditions
}
```  

so you can pass **any** method and it will be executed.

**Expected behavior/Solution**

Should be a way to define allowed relations and their properties.

**Steps to reproduce**

1. Create any query with `@whereConditions`

**Lighthouse Version**

v5.3.0

**Comment by spawnia** [comment]
Reformulate as a feature request and I might consider it.

**Comment by LastDragon-ru** [comment]
@spawnia probably this is a security issue because everyone can do something like this

```graphql
query {
  users(page: 1, where: {HAS: {relation: "markEmailAsVerified"}}) {
    data {
      id
    }
  }
}
```

**Comment by spawnia** [comment]
My point stands.

**Comment by LastDragon-ru** [comment]
@spawnia, I will not create a new issue because from my point of view this is a vulnerability and it must not be public. I think it was an error to post it... Could you please remove this issue?

Anyway, unfortunately, I'm not very familiar with the package and have no time to fix it now (I guess removing `HAS` is not a solution...).
