### ISSUE TITLE
@with directive - method argument for customizing the query

### ISSUE THREAD

**Issue by mrjandejong** [nuwave/lighthouse#1755]
**What problem does this feature proposal attempt to solve?**

Sometimes I want eager load a relation to prevent the N+1 issue. However, I want to add additional where clauses or order-by clauses  to the eager loaded relation. Laravel has an easy method of achieving this with a closure:

```
Post::with(["tags" => function($query){
    $query->where('tags.some_column', '=', 1);
}])
```
Sadly this laravel functionality is not made available for use in lighthouse. For the `@where` directive I can only pass a scope. 

**Which possible solutions should be considered?**

It would be really neat If I could pass 3rd argument to the `@with` directive: a class@function (like with `@field`). That get's the query  `$query` as it's first (only?) argument. So that the eager loading query can be modified. Like this:
```
@with(relation: "relation_name", modifier: "App\\GraphQL\\WithClosures\\relation_name@method_name")
```

**Comment by spawnia** [comment]
Sounds useful. That functionality would probably go here: https://github.com/nuwave/lighthouse/blob/45d837f78735b9bf1f38f3e0ee0663423d1f8ced/src/Schema/Directives/WithRelationDirective.php#L66

**Comment by mrjandejong** [comment]
> Sounds useful. That functionality would probably go here:
> 
> https://github.com/nuwave/lighthouse/blob/45d837f78735b9bf1f38f3e0ee0663423d1f8ced/src/Schema/Directives/WithRelationDirective.php#L66

Yes, I'm currently trying to develop this feature, but the level of code seperation of lighthouse-php is a bit more then I'm used too, so I am progressing slowly. I'll post back if a succeed / get stuck.

**Comment by mrjandejong** [comment]
I got the functionality working. But I don't understand Git well enough to commit it, sorry for that. I edited these two files:


**`Nuwave\Lighthouse\Schema\Directives\WithRelationDirective` @ `decorateBuilder` to:**
```
    protected function decorateBuilder(ResolveInfo $resolveInfo): Closure
    {
        return function (object $builder) use ($resolveInfo): void {
            if ($builder instanceof Relation) {
                $builder = $builder->getQuery();
            }
            
            $resolveInfo->argumentSet->enhanceBuilder(
                $builder,
                $this->directiveArgValue('scopes', []),
                null,
                $this->directiveArgValue('modifier', null)
            );
        };
    }
```



**`Nuwave\Lighthouse\Execution\Arguments\ArgumentSet` @ `enhanceBuilder` to:**
```
    public function enhanceBuilder(object $builder, array $scopes, Closure $directiveFilter = null, string $modifier = null): object
    {
        $scoutEnhancer = new ScoutEnhancer($this, $builder);
        if ($scoutEnhancer->hasSearchArguments()) {
            return $scoutEnhancer->enhanceBuilder();
        }

        self::applyArgBuilderDirectives($this, $builder, $directiveFilter);
        self::applyFieldBuilderDirectives($this, $builder);

        foreach ($scopes as $scope) {
            $builder->{$scope}($this->toArray());
        }
        
        if (!empty($modifier)) {
            $class = '\\'. $modifier;
            $method = '__invoke';
            
            if (strpos($modifier, '@') !== false) {
                $modifier = explode('@', $modifier);
                
                $class = '\\'. $modifier[0];
                $method = $modifier[1];
            }
            
            $modifier = new $class;
            $builder = $modifier->{$method}($builder);
        }

        return $builder;
    }
```

// Usage:


**After which I can use `@with` like this:**

```
@with(relation: "translations", modifier: "App\\GraphQL\\Modifiers\\Class@method")
```

**With this being an example `...\modifiers\Class@method`:**

```
<?php

namespace App\GraphQL\Modifiers;

use App\Models\Product;

class Translation
{
	public function product($builder)
	{
                // Dumb example:
		$builder
			->where('id', 777)
			->orderBy('id');
			
		
		return $builder;
	}
}
```

**Comment by spawnia** [comment]
Thanks for giving it a go! I just enhanced our contributing docs, see https://github.com/nuwave/lighthouse/blob/master/CONTRIBUTING.md#the-process for how you can propose a proper PR.

**Comment by spawnia** [comment]
You can use `@with(relation: "Bar", scopes: ["foo"])`, where `foo` is a scope on the related model `Bar`.
