### ISSUE TITLE
No access to parent pivot in relationship method

### ISSUE THREAD

**Issue by waldorllc** [nuwave/lighthouse#1756]
There are 3 models: Order, Product and Price

Each Order has many Products, each Product has a Price which depends on the Order's price_group_id field.

```
class Order extends Model
{
    public function products() {
        return $this->belongsToMany(Product::class)->withPivot(['quantity']);
    }
}

class Product extends Model
{
    public function price() {
        return $this->hasOne(Price::class)->where('price_group_id', '=', $this->pivot->pivotParent->price_group_id);
    }
}
```

Price model has id, product_id, price_group_id and value fields.

I retreive Order's price_group_id attribute in Product model with _$this->pivot->pivotParent_ and it works fine in plain Laravel, but it doesn't work with Lighthouse queries: _"Trying to get property 'pivotParent' of non-object"_. It seems like there is no pivot and pivotParent at all.

Is there any way to get a parent pivot attributes or maybe some other way to implement such relationships?

A part of GraphQL schema:

```
type Query {
    orders: [Order!]! @all
    order(id: ID! @eq): Order @find
}

type Order {
    id: ID!
    price_group_id: ID!
}

type Product {
    id: ID!
    price: Price @hasOne
}

type Price {
    id: ID!
    value: Float!
    price_group_id: ID!
}

```

**Comment by spawnia** [comment]
Can you try to set `'batchload_relations' => false` in `lighthouse.php`?

**Comment by waldorllc** [comment]
> Can you try to set `'batchload_relations' => false` in `lighthouse.php`?

Yep, I've just tried – no effect.

**Comment by spawnia** [comment]
One more thing to try would be to remove the `@hasOne` directive from `price`. In that case, Lighthouse will just do a plain property access for the relation. It might be necessary to cut out the optimization here.

**Comment by waldorllc** [comment]
I've tried some other ways to solve this, including accessor instead of relationship method. pivotParent returns null, but I got an access to pivot! So I could get the price_group_id and relative price this way:
```
public function getPriceAttribute() {
    return $this->hasOne(Price::class)->where('price_group_id', Order::find($this->pivot->order_id)->price_group_id)->first()->value;
}
```

@spawnia Thanks for your help!
