### ISSUE TITLE
ERR wrong number of arguments for 'mget' command

### ISSUE THREAD

**Issue by krunaldodiya** [nuwave/lighthouse#1757]
Laravel 8
Php 8
Postgresql 13

I am trying to implement subscription as specified in docs but after setup, when i try to run mutation

```

<?php

namespace App\GraphQL\Mutations;

use App\Models\GroupMessage;
use Nuwave\Lighthouse\Execution\Utils\Subscription;

class SendGroupMessage
{
    /**
     * @param  null  $_
     * @param  array<string, mixed>  $args
     */
    public function __invoke($_, array $args)
    {
        extract($args);

        $message =  GroupMessage::create([
            'sender_id' => auth()->id(),
            'poll_id' => $poll_id,
            'message' => $message
        ]);

        Subscription::broadcast('groupMessageCreated', $message);

        return $message;
    }
}
```

I am getting this error:-

![2021-03-09_16-07](https://user-images.githubusercontent.com/7272013/110458234-8a423300-80f1-11eb-8298-4ac6407a5120.png)

**Comment by spawnia** [comment]
Can you expand the stacktrace, where is Lighthouse involved?

@thekonz have you seen this before?

**Comment by krunaldodiya** [comment]
i can share my github repo, if it can help, you can spin the local server and check if the error happen, will it work ???

**Comment by krunaldodiya** [comment]
[Horizon - Failed Jobs.pdf](https://github.com/nuwave/lighthouse/files/6107967/Horizon.-.Failed.Jobs.pdf)

**Comment by spawnia** [comment]
Looks like the offending code is indeed within Lighthouse: https://github.com/nuwave/lighthouse/blob/71cbd5e21eb1d51bf72fe7f679af2162095938e2/src/Subscriptions/Storage/RedisStorageManager.php#L70

@krunaldodiya can you try changing how that call is made and get a working version?

**Comment by krunaldodiya** [comment]
> can you try changing how that call is made and get a working version?

I didn't understand you, can you please explain what actually need to be done ?

**Comment by spawnia** [comment]
I do not know what needs to be done, I just identified that this line of code is where the call to `MGET` is made. Apparantly it is wrong, but I do not have an example project set up. I would like you to try and change that code and see if you can fix it.

**Comment by krunaldodiya** [comment]
let me upload all files related to subscription:- 


1) Subscription

```
extend type Subscription {
    groupMessageCreated: GroupMessage! @guard
}
```

2) Subscription Resolver
```
<?php

namespace App\GraphQL\Subscriptions;

use Illuminate\Http\Request;
use Nuwave\Lighthouse\Schema\Types\GraphQLSubscription;
use Nuwave\Lighthouse\Subscriptions\Subscriber;

class GroupMessageCreated extends GraphQLSubscription
{
    public function authorize(Subscriber $subscriber, Request $request): bool
    {
        return true;
    }

    public function filter(Subscriber $subscriber, $root): bool
    {
        return true;
    }
}
```
3) Mutation that trigger subscription
```
extend type Mutation {
    sendGroupMessage(poll_id: ID!, message: String!): GroupMessage!
        @guard
        @field(resolver: "App\\GraphQL\\Mutations\\SendGroupMessage")
}
```

4) Mutation Resolver
```
<?php

namespace App\GraphQL\Mutations;

use App\Models\GroupMessage;
use Nuwave\Lighthouse\Execution\Utils\Subscription;

class SendGroupMessage
{
    /**
     * @param  null  $_
     * @param  array<string, mixed>  $args
     */
    public function __invoke($_, array $args)
    {
        extract($args);

        $message =  GroupMessage::create([
            'sender_id' => auth()->id(),
            'poll_id' => $poll_id,
            'message' => $message
        ]);

        Subscription::broadcast('groupMessageCreated', $message);

        return $message;
    }
}
```

**Comment by krunaldodiya** [comment]
I understand that but the problem is I am not sure what i suppose to change with what inside the file you link, let me do one thing, remove this line completely, may be then it start working :)

**Comment by spawnia** [comment]
Me neither. Try things. Be creative. Think.

**Comment by thekonz** [comment]
Hm I think maybe when there is no subscriber on a topic, the mget call would be called with an empty list.

**Comment by thekonz** [comment]
Thanks for the report @krunaldodiya
