### ISSUE TITLE
$context->user() always returns null in production

### ISSUE THREAD

**Issue by newtoniumx3** [nuwave/lighthouse#1761]
Always $context->user() returns null in production

I'm at a complete loss at what could be wrong on the production server.
My code works flawlessly on my localhost and I just don't know what to debug given that I've already confirmed the header token does reach the production server in the middleware.

<img width="797" alt="123" src="https://user-images.githubusercontent.com/43615639/110944429-745b8a80-830a-11eb-9204-ef2f5b5ade49.PNG">

**The process is rather simple.** 
1. Send a login graphql request and receive back an access_token
3. Send a second request with the access_token in the header as: Authorization: Bearer ...

**In production**
- Step 1 works I receive back the access_token. 
- Step 2, I always get back a null user session. I checked in production and the Authorization header does arrive intact and the value is also correct. But then why would it not process this properly like in localhost?

Development/Production Config:
- laravel .env: SESSION_SECURE_COOKIE=false
- laravel config: disabled EncryptCookies

Production Only Config:
- https

**App\\GraphQL\\Queries\\User\\Session.php**
```
class UserSession extends LoginBase
{
    public function resolve($rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo)
    {
        return [
            'user' => $context->user()
        ];
    }
}
```

**graphql/schema.graphql**
```
type Query {
    userSession: SessionResponse! @field(resolver: "App\\GraphQL\\Queries\\User\\Session@resolve")
}

type Mutation {
    login(input: LoginInput @spread): AuthPayloadWrapped! @field(resolver: "App\\GraphQL\\Mutations\\@resolve")    
}

```

**Comment by spawnia** [comment]
Consider https://github.com/nuwave/lighthouse/blob/master/src/Schema/Context.php.

**Comment by newtoniumx3** [comment]
> Consider https://github.com/nuwave/lighthouse/blob/master/src/Schema/Context.php.

Thank you, I'm debugging deep right now. Here is what I got so far, moving upwards.
Session seems to be established in 

`src/server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php`

![123](https://user-images.githubusercontent.com/43615639/110947941-c30b2380-830e-11eb-8f2b-e9db13408d5a.jpg)

**Comment by spawnia** [comment]
Unless you are able to pinpoint an issue within Lighthouse, I will have to assume this is an issue with your project configuration.
