### ISSUE TITLE
Proposal: use Illuminate\Contracts\Debug\ExceptionHandler instead \Nuwave\Lighthouse\Execution\ErrorHandler

### ISSUE THREAD

**Issue by 4n70w4** [nuwave/lighthouse#1762]
**What problem does this feature proposal attempt to solve?**

The Laravel already has an interface for handling errors. `Illuminate\Contracts\Debug\ExceptionHandler`

Creating 2 exception handlers for the laravel-application and lighthouse-library is very tedious and takes twice as long.

`\Illuminate\Foundation\Exceptions\Handler::shouldReport` - very useful method.

But `\Nuwave\Lighthouse\Execution\ErrorHandler` has nothing of the kind.

**Which possible solutions should be considered?**

**Comment by spawnia** [comment]
The signature of those interfaces is quite different, and they do different things. Also, `ReportingErrorHandler` is enabled by default - it passes appropriate errors along to your applications `ExceptionHandler`.

Btw, peeking at your profile and seeing *Opensource Hater* does not exactly motivate me to give extra consideration to your request.

**Comment by 4n70w4** [comment]
LOL! =))))))

**Comment by 4n70w4** [comment]
Laravel kernel exception handler interface provides more processing options.
There is also a very powerful implementation https://github.com/GrahamCampbell/Laravel-Exceptions
It would be very cool to be able to completely disable lighthouse error handling.
`ReportingErrorHandler` cannot delegate response rendering of a to an application handler.

**Comment by spawnia** [comment]
This project is open for pull requests.
