### ISSUE TITLE
Get graphql query as json

### ISSUE THREAD

**Issue by newtoniumx3** [nuwave/lighthouse#1765]
**What problem does this feature proposal attempt to solve?**
Within the resolve handler method, it would be handy to get a nested array format of the graphql query for eager loading purposes and optimizations. Right now from within the resolve, only the raw graphql query is available.

**Which possible solutions should be considered?**
Could we (or is there already) a built in method to obtain the graphql in nested array or dotted format.
```
query {
    user {
        group1 {
            field1
            field2
        }
        group2 {
            field1
        }       
    }
}
```

```
user.group1.field1
user.group1.field2
user.group2.field1
```

https://gist.github.com/titpetric/e1414880099e0e5a90d87d56736bd87f

**Comment by spawnia** [comment]
There is https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/QueryPlan.php and its accompanying test https://github.com/webonyx/graphql-php/blob/master/tests/Type/QueryPlanTest.php

**Comment by newtoniumx3** [comment]
Awesome thanks!
