### ISSUE TITLE
Cannot query field created_at on type User

### ISSUE THREAD

**Issue by tienluckyfor** [nuwave/lighthouse#1770]
I've already set created_at on User type but when query at /graphql-playground I got a message "Cannot query field \"created_at\" on type \"User\"."
```
{
    "errors": [
        {
            "message": "Cannot query field \"created_at\" on type \"User\".",
```
graphql/schema.graphql
```
type User {
    id: ID!
    name: String!
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
}
```
These images bellow will clarify what problem I meet, 
[https://imgur.com/2dey46d](https://imgur.com/2dey46d)
[https://imgur.com/D31YYEs](https://imgur.com/D31YYEs)

Thanks for your time read my issue

**Comment by FranciscoCaldeira** [comment]
1. Do you have the latest lighthouse?
2. I suggest you do `lighthouse:clear-cache` and restart the playground to do it again.
3. Do you have in the User model the `created_at` field?
4. I saw that you are doing `users` query and that have the type `UserPaginator`, that one has the ` created_at: DateTime!`?

**Comment by tienluckyfor** [comment]
@FranciscoCaldeira 

I was check and that field still didn't appearance in my playground,
So I post my code on github, can you check for me. 
[https://github.com/tiennv-fireapps/debug-lighthouse](https://github.com/tiennv-fireapps/debug-lighthouse)

Thank you for your time!!

**Comment by enzonotario** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

So far, you don´t have any created_at field in your [User type](https://github.com/tiennv-fireapps/debug-lighthouse/blob/5df56b37a3775f59bedd61ef7e72b8c798682229/graphql/auth.graphql#L10)

**Comment by sumvee** [comment]
explain:     protected $fillable = [
        'name',
        'email',
        'password',
    ];
