### ISSUE TITLE
Please add a feature to @count Get Trashed

### ISSUE THREAD

**Issue by Rasool-deldar** [nuwave/lighthouse#1774]
**What problem does this feature proposal attempt to solve?**

This property is to get the values of a table with or without Trashed or only Trashed

![image](https://user-images.githubusercontent.com/58503211/112945298-5a62da00-9149-11eb-9187-1e2e93dbc9c0.png)

As you can see in the picture, set the number of returns based on a condition and also the return value if trashed with the following bad return

{
 count: 15,
 countTrashed: 10,
}

**Comment by Rasool-deldar** [comment]
> You indicate this is an error? If so, please add a failing test case to https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/CountDirectiveDBTest.php
> 
> I don't see what's the missing feature here - you can combine `@count` and soft deletes as you described.

Hi, I mean using @softDeletes we can count only deleted numbers or number with deleted numbers or no deleted number


![image](https://user-images.githubusercontent.com/58503211/113101860-77171480-9212-11eb-8142-fb92ff1ab284.png)

**Comment by spawnia** [comment]
I still do not understand your issue fully but I will take another guess: Perhaps you are looking to query multiple different counts in the same query? Use aliases for that:

```graphql
withTrashedCount: count(trashed: WITH)
onlyTrashedCount: count(trashed: ONLY)
```
