### ISSUE TITLE
Upload FIles/Image

### ISSUE THREAD

**Issue by Mihai-github** [nuwave/lighthouse#1775]
Hi,
   I read the documentation about uploading a file, but I am curios about if there is a way to simulate the process from the
graphql-playground, because it can make the process much easier if we can test it in out "backend environment" rather then testing it on the frontend and making making sure it works and if not why...

**Comment by spawnia** [comment]
https://github.com/nuwave/lighthouse/blob/20067b223db5f1e43e222f98895e4a00bb10e2e8/tests/Integration/FileUploadTest.php
