### ISSUE TITLE
Validation rule `required_without` within arrays

### ISSUE THREAD

**Issue by wimski** [nuwave/lighthouse#1778]
**Describe the bug**
I have an input with a field which contains an array of items. Each item consists of an input object with two fields: `id` and `data`. Either you input an ID of an existing model or you supply data to create a new model on-the-fly. I've tried to use the `required_without` rule to require each of those field if the other doesn't exist, but that doesn't seem to work.

**Steps to reproduce**
See the following PR for a demonstration:
https://github.com/nuwave/lighthouse/pull/1777

**Lighthouse Version**
5.3.0

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/pull/1739
