### ISSUE TITLE
Please add the Automatic persisted queries feature to the package 

### ISSUE THREAD

**Issue by Rasool-deldar** [nuwave/lighthouse#1801]
**What problem does this feature proposal attempt to solve?**

 reducing request sizes

**Which possible solutions should be considered?**

Hello . Please add a feature to Automatic persisted queries This feature is very useful

[Automatic persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq/)

**Comment by spawnia** [comment]
Duplicate of https://github.com/nuwave/lighthouse/issues/651

**Comment by Rasool-deldar** [comment]
D
