### ISSUE TITLE
@trim does not sanitize user input

### ISSUE THREAD

**Issue by Rasool-deldar** [nuwave/lighthouse#1805]
I wanted to clean the user input using @trim, it does not work, the user can enter a single HTML

![image](https://user-images.githubusercontent.com/58503211/114997634-4d6a1880-9eb5-11eb-84db-c09382a526d0.png)

![image](https://user-images.githubusercontent.com/58503211/114997666-55c25380-9eb5-11eb-8381-b8ea6dde2ffc.png)

![image](https://user-images.githubusercontent.com/58503211/114997702-607ce880-9eb5-11eb-8d75-0aa67713b096.png)

**Comment by nikitanp** [comment]
Because under the hood @trim directive using trim function :)
Maybe you want create StripTags directive? In my way it's seems like a this code:

```php
class StripTagsDirective extends BaseDirective implements
    ArgSanitizerDirective,
    ArgDirective
{
    private ?array $allowedTags;

    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'GRAPHQL'
"""
Remove unallowed tags from the given input.

This can be used on:
- a single argument or input field to sanitize that subtree
- a field to strip tags for all strings
"""
directive @stripTags (
    """
    Array of allowed tags for strip_tags function
    """
    allowed:[String!]
)on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION | FIELD_DEFINITION
GRAPHQL;
    }

    /**
     * Remove not allowed tags from the given input.
     * @param $argumentValue
     * @return array|mixed
     */
    public function sanitize($argumentValue)
    {
        $this->setAllowedTags();

        return Utils::applyEach(
            function ($value) {
                return $value instanceof ArgumentSet
                    ? $this->transformArgumentSet($value)
                    : $this->transformLeaf($value);
            },
            $argumentValue
        );
    }

    private function setAllowedTags()
    {
        $this->allowedTags = $this->allowedTags ?? $this->directiveArgValue('allowed', []);
    }

    public function transformArgumentSet(ArgumentSet $argumentSet): ArgumentSet
    {
        foreach ($argumentSet->arguments as $argument) {
            $argument->value = $this->sanitize($argument->value);
        }

        return $argumentSet;
    }

    /**
     * @param mixed $value The client given value
     * @return mixed The transformed value
     */
    protected function transformLeaf($value)
    {
        if (is_string($value)) {
            return strip_tags($value, $this->allowedTags);
        }

        return $value;
    }
}
```

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
