### ISSUE TITLE
Add a new feature to the package

### ISSUE THREAD

**Issue by Rasool-deldar** [nuwave/lighthouse#1811]
Hi, I want to add some new features to the package so that I can use it again later and others can use it.

Two of the features are [Persisted Queries](https://www.apollographql.com/docs/react/api/link/persisted-queries/) and [Batching](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/), but I do not know how to add these features to the package kernel @spawnia Can you help me how to do this and can you help in the development process of this feature?

Please let me know if you have a suggestion or roadmap for new features

**Comment by spawnia** [comment]
Batching is supported, for persisted queries see https://github.com/nuwave/lighthouse/issues/651. Please consider the docs and existing issues before creating new issues.
