### ISSUE TITLE
Add @withSum @withMin, @withMax, @withAvg directive

### ISSUE THREAD

**Issue by P-Shakibafar** [nuwave/lighthouse#1817]
**What problem does this feature proposal attempt to solve?**

There is currently a directive @withCount:

`type User {
  activityStatistics: ActivityStatistics! @withCount(relation: "posts")
}`

In the last few months, new methods have been added to Laravel that make it easier to work with models, such as:

`$posts = Post::withSum('comments', 'votes')->get();‍‍`

`‍$posts = Post::withAvg('comments', 'votes')->get();`

`$posts = Post::withMin('comments', 'votes')->get();`

`$posts = Post::withMax('comments', 'votes')->get();`

We can have this help method.

**Which possible solutions should be considered?**

A solution similar to @withCount directive may be used.

**Comment by spawnia** [comment]
Please use the issue template and add a description.

**Comment by spawnia** [comment]
That would be a Laravel 8+ only feature then?

**Comment by P-Shakibafar** [comment]
yes, and laravel 8 lts

**Comment by spawnia** [comment]
Ok. I am accepting merge requests for this. The implementation will probably look very similar to `@withCount`, but should abstract appropriate to keep it DRY. Tests should also be added.

**Comment by spawnia** [comment]
With the newly implemented `@aggregate` directive, I see little use for a non-resolving version. If more people are interested, we might implement something like `@withAggregate`, but I am closing this for now.
