### ISSUE TITLE
Support Laravel Octane

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1818]
**What problem does this feature proposal attempt to solve?**

Laravel Octane promises great performance, but poses some restrictions on dependency injection and usage of global state: https://laravel.com/docs/octane#dependency-injection-and-octane

**Which possible solutions should be considered?**

Check for problematic dependency injection patterns within Lighthouse and fix them.

**Comment by olivernybroe** [comment]
We could use larastan to do a big chunk of the work here and have static analysis checking for this. 
https://github.com/nunomaduro/larastan/blob/master/docs/rules.md#octanecompatibilityrule

**Comment by spawnia** [comment]
Thanks @olivernybroe for the tip, I used that plus some manual auditing. There were a few fixes to be made, released as of https://github.com/nuwave/lighthouse/releases/tag/v5.10.0

I am looking to try this out myself soon and am happy for feedback from others. Memory leaks are a particular concern I still have, there is some global state in Lighthouse which I am not too sure about. The Defer module seems particularly suspicious.

**Comment by olivernybroe** [comment]
Wauw, that was a lot more changes then I thought we would need 😮 

Great job! Hopefully I will have time to test it out soon also.

**Comment by spawnia** [comment]
https://github.com/nuwave/lighthouse/pull/1854 only had 3 substantial changes actually, the rest was cleanup 😉
