### ISSUE TITLE
Type placeholder '_' should be defined by the ide-helper Command

### ISSUE THREAD

**Issue by tminich** [nuwave/lighthouse#1822]
**What problem does this feature proposal attempt to solve?**

If you use `_` as a placeholder for certain directives (e.g. `@orderBy`) the PHPStrom plugin complains about it being undefined. Defining it manually in one of you schemas leads to an error.

**Which possible solutions should be considered?**

The ide-helper command should define it as a scalar in `schema-directives.graphql`

**Comment by spawnia** [comment]
> Defining it manually in one of you schemas leads to an error.

Is that any different when placing it in `schema-directives.graphql`?

**Comment by tminich** [comment]
That works fine for me. I should have been more specific, if you define it in one of your actual schemas the plugin is fine with it, but the lighthouse/graphql framework errors out. As the framework ignores the helper files putting it there is ok with both the plugin and the framework.

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.5.1
