### ISSUE TITLE
Add builder support to @all directive

### ISSUE THREAD

**Issue by wimski** [nuwave/lighthouse#1825]
Please add `builder` support to the `@all` directive. The `@paginate` directive has this. Shouldn't these directives be the same other than the specific pagination options? They also both already support `scopes` for example.

**Comment by spawnia** [comment]
This should be pretty easy to do, see https://github.com/nuwave/lighthouse/blob/ba530a7ec289a9b18e18880e039c63e69e108560/tests/Integration/Pagination/PaginateDirectiveDBTest.php#L56 and https://github.com/nuwave/lighthouse/blob/ba530a7ec289a9b18e18880e039c63e69e108560/src/Pagination/PaginateDirective.php#L104. Lookinf forward to a PR.

**Comment by wimski** [comment]
Same applies regarding making a PR as [here](https://github.com/nuwave/lighthouse/pull/1819#issuecomment-825607320) 😢

**Comment by wimski** [comment]
I did a blind PR https://github.com/nuwave/lighthouse/pull/1826 🙈
