### ISSUE TITLE
Return Laravel validation errors for matching schema restrictions

### ISSUE THREAD

**Issue by wimski** [nuwave/lighthouse#1830]
## Problem

I've encountered the following problems regarding consistency in validation.

### Schema definitions hijack validation

Schema definitions can carry some inherent validation which therefore can't be validated with rules anymore. In the following example both `required` rules are made redundant by the use of `!` and the `string` rule is made redundant by the `String` definition.

```graphql
input MyInput {
    name: String! @rules(apply: ["required", "string"])
    email: String! @rules(apply: ["required", "email"])
}
```

### Validation error messages are unclear

The validation messages returned for errors in schema definitions/restrictions are unclear. In the following example the field name is missing in the error message which makes it unclear if the `name` or `email` field is invalid.

#### Schema
```graphql
input MyInput {
    name: String!
    email: String! @rules(apply: ["email"])
}

extend type Mutation {
    doStuff(input: MyInput): SomeResponse
}
```

#### Request
```graphql
mutation {
    doStuff(input: {
        name: "Foo Bar",
        email: 12345
    }) {
        id
    }
}
```

#### Response
```json
{
    "errors": [
        {
            "message": "Field \"doStuff\" argument \"input\" requires type String!, found 12345.",
            "extensions": {
                "category": "graphql"
            }
        }
    ]
}
```

## Solution

As far as I can tell both problems can be solved by using Laravel's validation rules/errors for certain schema definitions/restrictions. See the following example.

#### Schema
```graphql
input MyInput {
    name: String!
    email: String! @rules(apply: ["email"])
}

extend type Mutation {
    doStuff(input: MyInput): SomeResponse
}
```

#### Request
```graphql
mutation {
    doStuff(input: {
        name: "Foo Bar",
        email: 12345
    }) {
        id
    }
}
```

#### Response
```json
{
    "errors": [
        {
            "message": "Validation failed for the field [doStuff].",
            "extensions": {
                "category": "validation",
                "validation": {
                    "input.email": [
                        "The input.email must be a valid email address."
                    ]
                }
            }
        }
    ]
}
```

Below is a list with rules that could be used (I might have missed some). Is this something that is possible to implement?

| Schema | Rule |
| :--- | :--- |
| `!` | `required` |
| `String` | `string` |
| `Int` | `integer` |
| `Float` | `numeric` |
| `Boolean` | `boolean` |
| `Date` | `date` |

**Comment by spawnia** [comment]
Valid points and good summary. There is an issue to discuss this already, see https://github.com/nuwave/lighthouse/issues/1751
