### ISSUE TITLE
Slack invite link doesn't work

### ISSUE THREAD

**Issue by wimski** [nuwave/lighthouse#1832]
I'm not sure if this is an issue with Slack, but the invite link doesn't work. It says the following:

> There’s been a glitch…
We’re not quite sure what went wrong. You can go back, or try looking on our Help Center if you need a hand.

**Comment by spawnia** [comment]
Which link, where?

**Comment by wimski** [comment]
`README.md:45`
```markdown
- Talk to other users? [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/https://join.slack.com/t/lighthouse-php/shared_invite/zt-4sm280w1-wu21r94f3kLRRtBXRbXVfw)
```

**Comment by spawnia** [comment]
Fixed, thank you
