### ISSUE TITLE
Add @sum @min, @max, @avg directive

### ISSUE THREAD

**Issue by P-Shakibafar** [nuwave/lighthouse#1835]
**What problem does this feature proposal attempt to solve?**

`type Query {
  booksPriceSum: Int! @sum(model: "Book", column: "price")
}`

`type Query {
  booksPriceAvg: Int! @avg(model: "Book", column: "price")
}`

`type Query {
  booksPriceMax: Int! @max(model: "Book", column: "price")
}`

`type Query {
  booksPriceMin: Int! @min(model: "Book", column: "price")
}`

**Which possible solutions should be considered?**

The solution may be similar to the instructions for use @count.

**Comment by spawnia** [comment]
I was unsatisfied with the current abstractions and did a rewrite of large parts of the relation and batch loader handling. See https://github.com/nuwave/lighthouse/pull/1849. This also includes a new `@aggregate` directive.
