### ISSUE TITLE
Add arguments during validation

### ISSUE THREAD

**Issue by michellealbefore** [nuwave/lighthouse#1839]
I'm using @validator. I need to check the condition of a field, but it is not at the entrance. I need to insert it in the arguments to be able to validate it.

```
 'cli_ie_tipo' => [
                'prohibited_unless:cli_tipo,1',
                'prohibited_unless:cli_ie_tipo,9'
            ],
``` 
cli_tipo is in the input, but as it doesn't come from the form, there's no way to access it in the validator and to be able to validate it in this way, I need to insert it.
Is it possible to leave it with a default value in the input and receive it in the validator?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
