### ISSUE TITLE
Treat InputObjectValues as InputValueDefinitions, not as FieldDefinitions

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#184]
**Is your feature request related to a problem? Please describe.**

The way input types are currently handled is mixed up between other types and fields. The fields of InputObjects are actually not FieldDefinitionNode but rather InputValueDefinitionNode.

This leads to cases where directives might be applied at a place where they do not actually make sense. Also, it prevents us adding strict types to the methods that deal with fields/arguments, because they might recieve different DefinitionNodes.

**Describe the solution you'd like**

Change the NodeFactory/FieldFactory and related Directives so that they cleanly seperate Input objects and treat them seperately.

By distinguishing between them, our code becomes more clear in intent and more logical. We can add strong type hints to ensure we always know the exact type of data we are dealing with.

**Comment by chrissm79** [comment]
Hey @spawnia, could you do me a favor and provide some insight into how you intend to change the NodeFactory/FieldFactory and Directives? i.e., is it just separating the input types out and pushing them through a different process (in the NodeFactory) w/ new directive interface(s) or are you making changes to the current directive interfaces? Thanks!!

**Comment by spawnia** [comment]
The spec describes six types:

```
ScalarTypeDefinition
ObjectTypeDefinition
InterfaceTypeDefinition
UnionTypeDefinition
EnumTypeDefinition
InputObjectTypeDefinition
```

First, i would rename the classes that deal with types to reflect that. Right now, they are all kind of lumped together as `Nodes`. I found this confusing when initially coming to the project, and i still feel it is not quite right. The term `Node` is in this weird place where it is overly general on the one side (a node in the SDL could also mean a field, an arg ...) and very specific on the other side (Relay uses it to specify the globally unique entities)

I think we might delegate to specific factories from the SchemaBuilder, and have a seperate `ScalarTypeFactory`, `ObjectTypeFactory` and so on.

Second, i would seperate the directive interfaces to make it clear what exact type they apply to. I guess we might try to preserve compatibility with the `NodeXXX` interfaces, but i really feel like we would be shoe-horning this into an abstraction that is not quite right.

The process for dealing with the different types looks vastly different, so i think it makes sense to fully seperate them. While `Interface|Union|Object` types are pretty similar, `Scalar|Enum|InputObject` are vastly different.

There might be some overlap where you would want a directive with the same name to apply to different types. By having seperate interfaces, it becomes really straightforward to differentiate that behaviour.

**Comment by yaquawa** [comment]
@spawnia I guess this is THE right way to dealing with difference types…

**Comment by yaquawa** [comment]
Really, directive definition is the key feature of Lighthouse, I think it's very rewarding for refining the architecture of how to write a directive!!
