### ISSUE TITLE
@scout directive unnecessarily constrains supported Eloquent directives

### ISSUE THREAD

**Issue by GregPeden** [nuwave/lighthouse#1846]
**Describe the bug**

A change to Lighthouse in the past few months has introduced an unnecessary validation check on the `@search` directive use which throws an exception whenever one of several other denoted argument directives are included in a query. This is likely intended to order to perform a validation check to best support the Algolia search driver, which indeed provides a very narrow feature set on account of searches being processed by a remote server.

I see this is as an error in execution to presuppose the appropriate argument set. For example the [laravel-tntsearch](https://github.com/teamtnt/laravel-scout-tntsearch-driver) driver supports most of the Eloquent query methods, because it executes locally and can afford to filter down indexed search results with an SQL query when so desired.

The relevant validation check is here: https://github.com/nuwave/lighthouse/blob/d6944386e2020dec767f236025e0d80704638ef2/src/Scout/ScoutEnhancer.php#L70

I suggest that Lighthouse should not be applying this validation check as it breaks support for some Scout search drivers.

**Expected behavior/Solution**

Don't apply/presume this validation check; make the app developer responsible for this.

**Steps to reproduce**

1. Set up Lighthouse with TNTSearch Scout driver
2. Build a query which mixes the `@search` directive with other Eloquent-based directives such as query scopes
3. Run query and observe error in response

**Lighthouse Version**

5.x - Using 5.3.0 at the moment myself.

**Comment by spawnia** [comment]
Consider the difference between the `ArgBuilderDirective` and `ScoutBuilderDirective` interfaces. Using the TNTSearch driver, what would a call to `Model::search()` return?

**Comment by GregPeden** [comment]
Oops I totally derped with this, I just totally forgot how I solved this before. My bad. :( Thanks for your patience.

**Comment by GregPeden** [comment]
NOPE, I was wrong, this totally breaks TNTsearch.

So I was implementing this using a (crude) builder method like this:

```php
  /**
   * Add a limit constrained upon the query.
   *
   * @param  \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder  $builder
   * @param  mixed $value
   * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
   */
  public function projectTeamMember($builder, array $value)
  {
    $user = $value['user'];
    $role = $value['role'] ?? null;

    if ($builder instanceof ScoutBuilder) {
      return $builder->constrain(Project::whereTeamWithUser($user, $role));
    } else {
      return $builder->whereTeamWithUser($user, $role);
    }
  }
```

This totally works and will be fine except Lighthouse just blocks it because it decides scopes are not okay.

**Comment by spawnia** [comment]
Nit: Your code is inconsistently typed, the condition `$builder instanceof ScoutBuilder` will never be `true` if the PHPDoc is correct. This is precisely the reason why I separated the directive interfaces.

I agree that your use case should indeed work. I guess you are using `@scope`? We might open up some directives that implement `ArgBuilderDirective` to also implement `ScoutBuilderDirective`.

![image](https://user-images.githubusercontent.com/12158000/118114086-6946d880-b3e7-11eb-9415-19f7d9c44363.png)

Out of those, only `@eq` and `@trashed` also implement `ScoutBuilderDirective`. Given that they defer to user defined code, which may or may not work, we should probably open up `@scope` and `@builder`. Any other directive that would also work or we could make work?

**Comment by GregPeden** [comment]
Re typing, true, I basically copied and pasted the docblock from documentation and haven't fussed with that too much. I personally prefer to use typing in the method declaration whenever that is practical.

I'm not using `@scope` here because of the need to check for the ScoutBuilder and then make use of the constrain() method. This is using the `@builder` directive.

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.8.2
