### ISSUE TITLE
@builder directive arguments type changes with/without @search

### ISSUE THREAD

**Issue by GregPeden** [nuwave/lighthouse#1852]
**Describe the bug**

Arguments passed to a Builder are presented different depending on if `@search` is used in the same query.

Without a complimentary `@search`, builder arguments are provided as an array.

With a `@search` they are provided as an ArgumentSet object.

**Expected behavior/Solution**

augments should be provided with a consistent type, though I'd vote for a total migration to ArgumentSet.

**Lighthouse Version**

v5.8.2

**Comment by spawnia** [comment]
Fixed in https://github.com/nuwave/lighthouse/releases/tag/v5.9.1
