### ISSUE TITLE
Suggested method for supporting "hasMorePages" on simple pagination

### ISSUE THREAD

**Issue by GregPeden** [nuwave/lighthouse#1855]
**What problem does this feature proposal attempt to solve?**

Referencing: https://github.com/nuwave/lighthouse/pull/1816

The new simple pagination solution is a great addition, but to provide that the "hasMorePages" property is excluded. This could still be provided with simple pagination while sticking to the core philosophy of running with one query.

**Which possible solutions should be considered?**

When "hasMorePages" is requested by the client, query for one more row than the client requested, then check for the extra row. If provided by the database, "hasMorePages" is true then just drop the extra row from the API response.

If "hasMorePages" is not requested, then a small optimization would be to not query for an extra row.

Of course there are also pretty clean ways to check for this client-side, this proposal is just about remaining flexible to accommodating a broader set of client solutions.

**Comment by GregPeden** [comment]
@thekonz pinging you since this concerns your contribution.

**Comment by thekonz** [comment]
It's not like we can simply tell `simplePaginate` of the laravel query builder to query for an additional row, right?
At least that's not a feature I am aware of.

**Comment by GregPeden** [comment]
Okay if that's not easy to implement I totally understand - easy to say, hard to do. ;)

**Comment by spawnia** [comment]
@GregPeden I really like the idea and think it could be something that is useful for Laravel in general. If you can get it into core, I am happy to include it in Lighthouse.

**Comment by thekonz** [comment]
closing, because this has been implemented in laravel and our simple pagination supports it as well :)
