### ISSUE TITLE
Cannot use @globalId on nullable arguments/input fields

### ISSUE THREAD

**Issue by MaartenStaa** [nuwave/lighthouse#1861]
**Describe the bug**

When passing null to an input field defined as:

```graphql
someId: ID @globalId(decode: "ID")
```

The server returns an error: `Argument 1 passed to Nuwave\Lighthouse\Execution\Utils\GlobalId::decodeID() must be of the type string, null given, called in vendor/nuwave/lighthouse/src/Schema/Directives/GlobalIdDirective.php on line 81`

Note that omitting the `someID` variable altogether in the payload _does_ work.

**Expected behavior/Solution**

The `@globalId` directive should ignore `null` values and pass on the null to the actual resolver.

**Steps to reproduce**

1. Define a mutation or query with an argument as described above. 
2. Call the mutation or query from a client, passing null as the argument.
3. Lighthouse returns an error.

**Output/Logs**

```
`Argument 1 passed to Nuwave\Lighthouse\Execution\Utils\GlobalId::decodeID() must be of the type string, null given, called in vendor/nuwave/lighthouse/src/Schema/Directives/GlobalIdDirective.php on line 81`
```

**Lighthouse Version**

Version 4.18.0, but it looks like [the most recent version](https://github.com/nuwave/lighthouse/blob/master/src/GlobalId/GlobalId.php#L38) has the same type restrictions.

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.12.2
