### ISSUE TITLE
Query JSON column in whereConditions

### ISSUE THREAD

**Issue by akyrey** [nuwave/lighthouse#1863]
**Describe the bug**
If a database column is defined as JSON, it's currently not possible to query using whereConditions, since method `assertValidColumnReference` doesn't allow symbols `->` used as column name

**Expected behavior/Solution**
Having a table with a column of type JSON, it should be possible to define such column with JSON notation `->`

**Steps to reproduce**

1. Create a migration to add a table with a JSON column
2. Add related model and define a query to retrieve all models in that table using `@all` directive
3. Define an enum that has a value to query one JSON field (for example `enum ExampleColumn { VALUE @enum(value: "json_column->json_key") }`)
4. Add an argument to that query as `where: _ @whereConditions(columnsEnum: "ExampleColumn")`
5. Perform a query on that table after creating some mock data

**Additional info**
I think it should be possible to fix this changing the regex used with this one:  
`/^(?![0-9.-])([A-Za-z0-9_.-]|->)*$/`  
I'm opening related PR #1864 

**Lighthouse Version**
5.12.1

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.12.3
