### ISSUE TITLE
@with should only load the same relationship one time

### ISSUE THREAD

**Issue by BoiteBeet** [nuwave/lighthouse#1876]
**What problem does this feature proposal attempt to solve?**
I have multiple custom property on a model that use the same relationship to format the response. I would like the eager load that relationship on the model if I request one or more of these custom properties but @with loads the relationship for each field I request. 

**Which possible solutions should be considered?**
1. Add an option on @with to only apply if the relation is not already there.
2. Add a new directive that can be applied on the type where we specify the relation and the corresponding fields.

**Comment by spawnia** [comment]
Lighthouse version?

**Comment by BoiteBeet** [comment]
> Lighthouse version?

5.7.2

**Comment by BoiteBeet** [comment]
I just update to 5.12.7 and the problem is gone. Sorry

**Comment by spawnia** [comment]
Always update first. v5.9.0 has what you want https://github.com/nuwave/lighthouse/pull/1849
