### ISSUE TITLE
Clean up pagination generated type optionality

### ISSUE THREAD

**Issue by pyrou** [nuwave/lighthouse#1877]
When using `@paginate` directive, lighthouse auto generate types (like. ModelEdge, ModelConnection, ModelPaginator or ModelSimplePaginator)

Within these types, multiple fields : 

| Field | Requirement |
| - | - |
| `models: ModelPaginator` | optional |
| `models: ModelSimplePaginator` | optional |
| `models: ModelConnection` | optional |
| `ModelPaginator.paginatorInfo: PaginatorInfo!` | required |
| `ModelPaginator.data: [Model!]!` | required array of required Model |
| `ModelSimplePaginator.paginatorInfo: PaginatorInfo!` | required |
| `ModelSimplePaginator.data: [Model!]!` | required array of required Model |
| `ModelConnection.paginatorInfo: PaginatorInfo!` | required |
| `ModelConnection.edges: [ModelEdge]` | optional array of optional ModelEdge |
| `ModelEdge.cursor: String!` | required |
| `ModelEdge.node: Model` | optional |

This inconsistency across all those fields could be solved by moving all types to required.

**Comment by spawnia** [comment]
The first 3 types are only made non-nullable behind a new config setting, as it may otherwise break some applications. The rest is now non-nullable, and everything will be in v6.
