### ISSUE TITLE
Disable exception handling in tests

### ISSUE THREAD

**Issue by denniskoster** [nuwave/lighthouse#1884]
Laravel comes with some very handy methods to disable all or some exception handling in the `InteractsWithExceptionHandling` trait. Especially the `$this->withoutExceptionHandling()` is particularly useful when writing end-to-end tests by making HTTP calls with  `$this->json()` for instance. Using this, you can inspect the actual exception that is thrown, rather than a rendered version of it.

For example:
```php
/**
 * @test
 */
public function it_should_login_a_user(): void
{
    $this->withoutExceptionHandling();

    try {
        $this->json('POST', '/login', [
            'username' => 'johndoe',
            'password' => 'secret',
        ]);
    } catch (AuthenticationException $exception) {
        dump($exception->getMessage());
    }        
}
```

Currently, it appears that there is no way of disabling exception handling altogether for calls being made using the Lighthouse `$this->graphql()` helper from the `MakesGraphQLRequests` trait.

It would be great if Lighthouse would also stop handling exceptions when `$this->withoutExceptionHandling()` is called, or potentially ship with a separate method to temporarily disable exception handling.

I am willing to submit a PR if you think this feature request is indeed useful and can point me in the right direction.

Thanks!

**Comment by spawnia** [comment]
Please review https://github.com/nuwave/lighthouse/pull/1885 and tell me if it solves your problem. If I could help you, please consider sponsoring.
