### ISSUE TITLE
Should I manually register Broadcast channel for lighthouse-*?

### ISSUE THREAD

**Issue by mowses** [nuwave/lighthouse#1887]
Using GraphQL subscriptions I came in an issue that forces my app to implement the following code:

`routes/channels.php`
```
Broadcast::channel('lighthouse-{id}', function ($user) {
    return true;  // app auth check rules here
}, ['guards' => ['api']]);
```

But I find nothing about it in any documentation I read. Should not be the library the responsible to do that?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
