### ISSUE TITLE
v5 Rule::exists() problems

### ISSUE THREAD

**Issue by odziomkova-brackets** [nuwave/lighthouse#1889]
Recently I have updated my project from Laravel 7 to 8 and Lighthouse from v4 to v5 (currently v5.15). 
I updated all of my old validation directives to the new Validator classes and all works well, except for the Rule::exists(). Of course this might be a Laravel bug and not Lighthouse bug, but my guess was that if it was in Laravel 8, someone would have noticed it by now.

My old rule (before upgrade it would catch the incorrect data, now it just let's them pass):
```
'input.billing_entity_id' => [
       'required',
        Rule::exists('billing_entities', 'id')->where(function ($query) use ($clientId) {
              return $query
                   ->where('client_id', $clientId)
                   ->whereNull('deleted_at');
        })
 ],
```
If I rewrite it without the closure:
```
'input.billing_entity_id' => [
      'required',
      Rule::exists('billing_entities', 'id')
            ->where('client_id', $clientId)
            ->whereNull('deleted_at')
      ],
```
it works as expected.
In this one case, rewriting it is not a problem. But when using e.g. whereIn(), it cannot be rewritten this way, since method whereIn() on the Rule object doesn't accept a subquery, only array.

Is there any possibility that this is a Lighthouse problem?
 

**Lighthouse Version**

5.15

**Comment by spawnia** [comment]
Can you try and check if your rule works with plain Laravel? A pull request with a failing test case would also be great starting point.

**Comment by odziomkova-brackets** [comment]
I tried, on the same project, through Tinker, this:
```
        $clientId = 2;
        $response1 = Validator::make([
            'billing_entity_id' => 1
        ], [
            'billing_entity_id' => [
                'required',
                \Illuminate\Validation\Rule::exists('billing_entities', 'id')
                    ->where(function ($query) use ($clientId) {
                        return $query->where('client_id', $clientId)
                            ->whereNull('deleted_at');
                    })
            ]]
        )->validate();
        
        $response2 = Validator::make([
            'billing_entity_id' => 1
        ], [
                'billing_entity_id' => [
                    'required',
                    \Illuminate\Validation\Rule::exists('billing_entities', 'id')
                        ->where('client_id', $clientId)
                        ->whereNull('deleted_at')
                ]]
        )->validate();
```
For the correct $clientId, both passed. For the incorrect $clientId, both threw a validation error, as expected.

As for the failing test PR, I will look into it.

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.15.2. Thanks for the report and the test case.
