### ISSUE TITLE
Nested Models

### ISSUE THREAD

**Issue by wovosoft** [nuwave/lighthouse#1891]
Hello My Models are structured in following way: 
App/Models/
 -------------/Hrm/Employee
 -------------/Hrm/Student
 -------------/Hrm/Teacher

My Question is when Models are placed inside the default App/Models folder, everything is fine. But when Models are inside sub folders, how can I use them?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by timyourivh** [comment]
I faced the same problem, apparently it does not "search" the models directory.
But after going through the docs there I found there are multiple ways to tackle this issue.

### Method 1: Config

You can add the namespace in the lighthouse config. Here's an example in the context of your issue:
```diff
// config/lighthouse.php

'namespaces' => [
-       'models' => ['App', 'App\\Models'],
+       'models' => ['App', 'App\\Models', 'App\\Models\\Hrm'],
        'queries' => 'App\\GraphQL\\Queries',
```

### Method 2: Using the @namespace directive

There's a directive that can set the namespace for a directive on a type called [@namespace](https://lighthouse-php.com/6/api-reference/directives.html#namespace). In your `schema.graphql`:

```graphql
# The @namespace directive below sets the namespace for the @all directive within that type.
type Query @namespace(all: "App\\Models\\Hrm") { 
  employees: [Employee!]! @all
  students: [Student!]! @all
  teacher: [Teacher!]! @all
}
```

I'm not aware of setting multiple directive namespaces at once, so unfortunately you'll have to add all the directives you'd like to overwrite in the namespace directive:
(if anyone knows how to do this please @ me to let me know)

```graphql
type Query @namespace(all: "App\\Models\\Hrm", find: "App\\Models\\Hrm") {
  employees: [Employee!]! @all
  employee(id: ID! @eq): Employee @find
}
```
