### ISSUE TITLE
Allow custom validation to use field reference arguments

### ISSUE THREAD

**Issue by ChrisExP** [nuwave/lighthouse#1901]
**Lighthouse has no way of knowing when a custom validation rule wants to reference another field.**

I have a custom validation rule called `MaxDifference` which ensures that one date field cannot be more or less than a specified interval from another field in the request.  
Because of the way graphQL works the path to the field in the request is ambiguous and cannot be guaranteed at the point the validation rule is defined.  
Lighthouse works around this for the default validation fields by injecting the path when it gathers up the rules that need it, but there is no equivalent logic for custom rules.

**Possible solutions**
- The `rules` method on the `ArgumentSetValidation` and `ArgumentValidation` interfaces could accept an optional argument that provides the path to the fields being validated so the developer could create a custom directive that injects the path into the rule themselves.
> This would allow anyone to use references in any custom rules however it does put the work on the developer and I don't know if this would include any breaking changes.

- Have an interface, something like `ReferencesOtherFields`, which defines a method `updateReferencePath` which the developer can use in the custom rule class. The `RulesGatherer` class can then check for this interface and call the method with the absolute path to the fields, then the rule can store that and use it when validating.
> This would definitely have no breaking changes however it would only work for custom `Rule` classes and not for closures or extending the `Validator` class.

I am happy to create a pull request for this but I wanted to start a discussion if someone has any better ideas?

**Comment by spawnia** [comment]
Your first solution could be doable through an enhanced version of `@rules` and `@rulesForArray`, perhaps some kind of extra syntax for a path on rules? To work with `@validator`, which basically only points to a validator class and does not specify the rules itself, we would have to extend the specific syntax to work there as well.

Your second solution seems like it should work, but requires changing the rules to make them work with Lighthouse.

Perhaps we can combine both approaches and use composition. We could define a custom rule such as `WithReference` and also register it through `Validator::extend()` to have it available in short string form. It would work by wrapping your own custom rule, something like this:

```graphql
@rules(apply: ["with_reference:max_difference,0,foo,5"])
```

Its arguments are:
1. Wrapped rule
2. Index of which argument of the wrapped rule is a reference
3. Arguments of the wrapped rule (any number)

**Comment by ChrisExP** [comment]
I like that. Ok I will make the PR tomorrow.
