### ISSUE TITLE
issue when use @group

### ISSUE THREAD

**Issue by engsamar** [nuwave/lighthouse#1906]
`extend type Query @group(middleware: ["locale"]){
    locations:[ Location!] !@all( model: "App\\Models\\Location\\Location")
}`

<img width="1672" alt="Screen Shot 2021-08-04 at 3 13 17 PM" src="https://user-images.githubusercontent.com/16509556/128187121-4661165e-4b7a-450e-b075-83d0941755b0.png">

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
