### ISSUE TITLE
Repeated use of `@guard` on type extensions marked as incorrect

### ISSUE THREAD

**Issue by SimBig** [nuwave/lighthouse#1907]
**Describe the bug**

The @guard directive does not get recognized correctly by phpStrom-IDE. The executable code is working as expected. 

**Expected behavior/Solution**

The Guard-Directive should be recognized correctly by the PhpStorm-IDE

**Steps to reproduce**

1. set a guard directive on a Query

**Output/Logs**

![image](https://user-images.githubusercontent.com/26680884/128214403-bf3a01b1-11b3-4753-a0cb-9e3ae0ef2b3a.png)

**Lighthouse Version**

^5.12

**Comment by spawnia** [comment]
I am assuming you are using the JS GraphQL plugin version 3.x. It appears the plugin understands type extensions and handles them strictly according to the spec http://spec.graphql.org/draft/#sec-Object-Extensions.Type-Validation:

> Any non-repeatable directives provided must not already apply to the original Object type.

`@guard` is somewhat special when used on an object type extension: It is applied to the fields that are in lexical scope and erased before the types are merged. Thus, it is effectively not repeated in the final schema.

That said, the definition and prescribed is technically against the spec. Thus, I am labeling this as a bug. I think there is little harm for us to mark the directive as `repeatable`. Perhaps there is even a use case for it in the case of `@guard`?
