### ISSUE TITLE
Lighthouse no works on production server

### ISSUE THREAD

**Issue by micke-paredes** [nuwave/lighthouse#1909]
Hi everyone.

Today did the deployment a server with laravel and lighthouse on ubuntu server, well, all my pages works good but my playground cannot be reach the lighthouse server.

My CORS config is open for anyone http://xxx.xxxx.xxx.xxx/graphql  but when I set this route on the url appear graphql folder with the file schema inside.

I cannot sent request because the /graphql server no works, and i try config paths like this: 

return [
    'paths' => ['api/*', 'graphql'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => false,
    'max_age' => false,
    'supports_credentials' => false,
];

and like this:

return [
    'paths' => ['api/*', /'graphql'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => false,
    'max_age' => false,
    'supports_credentials' => false,
];

but no works, someone knows how can i run the lighthouse server production?

Help me please

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
