### ISSUE TITLE
Testing graphql request with header attributes

### ISSUE THREAD

**Issue by williamhenry94** [nuwave/lighthouse#1914]
Hi Guys,

How to make use custom header field such as `Authorization` when testing graphql request because this method `graphQL` seems not accepting headers parameter. Please advise.

https://github.com/nuwave/lighthouse/blob/d7093cc435f9d3c33a02250a6809d1363408f052/src/Testing/MakesGraphQLRequests.php#L56

**Comment by spawnia** [comment]
https://github.com/nuwave/lighthouse/blob/d7093cc435f9d3c33a02250a6809d1363408f052/src/Testing/MakesGraphQLRequests.php#L59-L69

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
