### ISSUE TITLE
Add a `field` argument to the @can directive to resolve models by custom key

### ISSUE THREAD

**Issue by SylvesterNielsen** [nuwave/lighthouse#1916]
**What problem does this feature proposal attempt to solve?**
It's not possible to resolve the model in a query like this where the primary key is the uuid property and not the id. `articleByUUID(uuid: String @eq): Article @can(ability: "view", find: "uuid") @find @softDeletes`

The above code will try to resolve the Article model by the id property and return an error.
`No query results for model [App\\Models\\Article]`

Adding a field argument will allow us to make the query like this and resolve the model as expected.
`articleByUUID(uuid: String @eq): Article @can(ability: "view", find: "uuid", field: "uuid") @find @softDeletes`

**Which possible solutions should be considered?**
A custom directive, but i believe this addition is the correct approach.

**Comment by spawnia** [comment]
Currently `findOrFail()` is used to query the model. It actually uses the primary key of the model, but does not work for different keys.

Your suggestion of allowing to specify the field to compare against would work. I think `column` would be a better name for it though.

As an alternative, how about an option that allows you to say that the builder arguments should be used? In your example, `@eq` already specifies the correct field. Something like `findByArgs: Boolean`?

**Comment by SylvesterNielsen** [comment]
Naming is always a hard one. :) 
`column` could be fine alternative to my `field` idea. 

The `findByArgs` is a great idea, but i would still argue that the `field/column` should be an option if you don't wish to apply all directives.

I'm a bit unsure how the existing arguments should interact with a `findByArgs` option though.
I mean the `find` and `field/column` option would not really make sense as these would be resolved by e.g. the `@eq` directive.
The `scope` argument should probably be added as well in this case, so the `@can` directive would follow the same specs and behavior as the `@find` directive.

I just made a small test and it seems to be an easy addition, but it would act like a switch, to either use the findByArgs or the current arguments. Default behavior would be the current, so no breaking changes. 

@spawnia what do you think?

**Comment by spawnia** [comment]
> but it would act like a switch, to either use the findByArgs or the current arguments

Can you clarify what you mean by this?

> i would still argue that the field/column should be an option if you don't wish to apply all directives.

I have always been hesitant to just use all arguments, given that `@can` should run before the actual query. There is still this lingering fear that this might somehow be a security problem? I tend to think that it should be fine as long as its opt-in.

Introducing additional options for how to find the Model seems like a slippery slope.
I can easily imagine a more complex scenario that is not covered by a single `column` argument, e.g. a query
that looks for a model by two fields.

> I'm a bit unsure how the existing arguments should interact with a findByArgs option though.

`findByArgs` would be mutually exclusive with `find`.

Indeed, `@can(findByArgs: true)` should behave just like `@find`. By leveraging existing query mechanisms, we don't introduce much more complexity beyond a single directive argument.

**Comment by SylvesterNielsen** [comment]
My thought is to keep the directive backwards compatible, but introduce new arguments.

1. The `field/column` argument which is used to select the primary key to query the model. This argument is an addition to the existing arguments.
2. the `findByArgs` which uses the directives from the query just like the @find directive. Setting the `findByArgs` to true will make the directive ignore any value set in the `find` and `field/column` argument. Also i want to add a `scope` argument to make it compatible with the `@find`directive. 

I hope that clarify what i meant? 😄 
Do you see this as a viable solution or do you think I need to make more changes?

The code I used to test this can be seen here.
```php
public function handleField(FieldValue $fieldValue, \Closure $next): FieldValue
    {
        $previousResolver = $fieldValue->getResolver();
        $ability = $this->directiveArgValue('ability');

        $fieldValue->setResolver(
            function ($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo) use ($ability, $previousResolver) {
                $gate = $this->gate->forUser($context->user());
                $checkArguments = $this->buildCheckArguments($args);

                if ($this->directiveArgValue('findByArgs') === true) {
                    $models = $resolveInfo
                        ->argumentSet
                        ->enhanceBuilder(
                            $this->getModelClass()::query(),
                            $this->directiveArgValue('scopes', [])
                        )->get();
                    if (!$models->count()) {
                        throw (new ModelNotFoundException)->setModel($this->getModelClass());
                    }
                } else {
                    $models = $this->modelsToCheck($resolveInfo->argumentSet, $args);
                }

                foreach ($models as $model) {
                    $this->authorize($gate, $ability, $model, $checkArguments);
                }

                return $previousResolver($root, $args, $context, $resolveInfo);
            }
        );

        return $next($fieldValue);
    }
```

Here's two examples of the `@can` directives being used with the new argument. Both options are working.
```graphql
""" New `field` directive being used """
articleByUUID(uuid: String @eq): Article @can(ability: "view", find: "uuid", field: "uuid") @find @softDeletes
""" New `findByArgs` directive being used """
articleByUUID(uuid: String @eq): Article @can(ability: "view", findByArgs: true) @find @softDeletes
```

**Comment by spawnia** [comment]
Let's only add `findByArgs` and `scopes` and see how far that gets us.

`CanDirective` should implement `FieldManipulator` and throw a `DefinitionException` if `find` and `findByArgs` are both used (or used wrong in other ways).

**Comment by SylvesterNielsen** [comment]
@spawnia Got ya. I will prepare a new PR for this.

**Comment by SylvesterNielsen** [comment]
@spawnia I created a new PR with the updated code, tests and documentation.
https://github.com/nuwave/lighthouse/pull/1919
