### ISSUE TITLE
Date scalars should support \Carbon\CarbonImmutable

### ISSUE THREAD

**Issue by tminich** [nuwave/lighthouse#1923]
**Describe the bug**

If you are using dates wrapped as \Carbon\CarbonImmutable Lighthouse considers them invalid for its date scalars

**Expected behavior/Solution**

DateScalar->tryParsingDate() should check for (and allow) both \Carbon\Carbon and \Carbon\CarbonImmutable

**Steps to reproduce**

1. Define a proptery as DateTimeUtc
2. Property resolves to a \Carbon\CarbonImmuable

**Output/Logs**

<details><summary>Click to expand</summary>

```
debugMessage: Expected a value of type "DateTimeUtc" but received: 2022-03-09 19:25:34
```

</details></br>

**Lighthouse Version**

5.21.0

**Comment by spawnia** [comment]
Can you provide a pull request?

**Comment by tminich** [comment]
Yeah, should be able to.
