### ISSUE TITLE
Using sync in a 1 is to 1 relationship like belongsTo

### ISSUE THREAD

**Issue by stephenjason89** [nuwave/lighthouse#1929]
Upserting a record together with sync works well with a many to many relationship
but for a belongsto relationship it doesn't work. I believe connect is the right one to be used here; however, docs didn't say anything about sync not working in a 1 to 1 relationship.

Here is a working many to many relationship query
![image](https://user-images.githubusercontent.com/3810177/131388999-2b388253-ebec-4d9e-80af-a533ad608ee0.png)

And here is the 1 is to 1 relationship that doesn't work
![image](https://user-images.githubusercontent.com/3810177/131389090-fc574ce5-908a-4410-ab9d-305485106225.png)

However, if the record is already connected to something, then sync works as expected.

lighthouse v5.22.3

Thank you

**Comment by spawnia** [comment]
> docs didn't say anything about sync not working in a 1 to 1 relationship

They also never specify that it should work. The default is that a feature does not exist, unless documented 😉 

`sync` only works for `BelongsToMany`.

**Comment by stephenjason89** [comment]
@spawnia Thank you, i just assumed it did. Because it is working after being connected with something 😂 My bad ☺️
