### ISSUE TITLE
Default to field type when no model argument is given

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#193]
**Is your feature request related to a problem? Please describe.**
Most of the time, when defining CRUD directives like `@create` i end up putting in the
return type as the `model`

Also, the docs have display a case where the model arg is ommitted: https://lighthouse-php.netlify.com/docs/directives-crud.html#delete

**Describe the solution you'd like**

Currently, the CRUD directives require a model arg to be set and then check for the existence of such a model.

How about when no model is set, we first try to infer the model from the return type of the field and throw if nothing is found?

````graphql
type Mutation {
	# used model: Foo
	foo: Foo @create
	# used model: Foo
	bar: Foo @create(model: "Foo")
	# used model: Bar
	baz: Foo @create(model: "Bar")
}
````

**Comment by chrissm79** [comment]
Looks good, that would be a great default to use!
