### ISSUE TITLE
The @requiresProduct directive may only be placed on fields or object types

### ISSUE THREAD

**Issue by AnthoniG** [nuwave/lighthouse#1933]
I am trying to create a directive that will only allow users who have a particular product to interact with it. This is called `RequiresProductDirective`

I have written another directive called RequiredRoleDirective that does something similar but with roles instead.
I have included links to both Gists.

I have gone through the documentation and even the source code for the `@guard` directive, but I can not get it to work. It keeps telling me that that it can only be placed on fields or object types. I know I need it to be an object type because this allows me to wrap `extend type Query` etc.

Here are my gists.
What am I doing wrong ?

[RequiresRoleDirective](https://gist.github.com/AnthoniG/438b9bdf970a594d06bf8fc99e4cd29a)
[RequiresProductDirective](https://gist.github.com/AnthoniG/ef47c4008eaff7b1c1509da07b651a62)

Regards
Anthoni

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
