### ISSUE TITLE
query with HasRelation and HasCondition in ManyToMany [@belongsToMany] relations drop some values

### ISSUE THREAD

**Issue by MuhmdRaouf** [nuwave/lighthouse#1940]
**Describe the bug**
When trying to list ManyToMany relation and list all the objects with all the relation except for just one type
it didn't return all the Object with empty relationship

eg. Trying  to list all `Users` including all the `Roles` expect for the Role with ID 2

it should list all users including users with no roles at all except for users with roles with ID 2

**Expected behavior**
It should list all users including users with no roles at all except for users with roles with ID 2

**Actual behavior**
It lists all users except for users with roles with ID 2 AND users with no roles.

**Steps to reproduce**
```php
<?php

namespace Tests\Integration\WhereConditions;

use Tests\DBTestCase;
use Tests\Utils\Models\Role;
use Tests\Utils\Models\User;
use Nuwave\Lighthouse\WhereConditions\WhereConditionsServiceProvider;

class WhereConditionsDirectiveTest extends DBTestCase
{
    protected $schema = /** @lang GraphQL */ '
    type User {
        id: ID!
        name: String
        email: String
        roles: [Role!]! @belongsToMany
    }

    type Role {
        id: ID!
        users: [User!]! @belongsToMany
    }

    type Query {
        users(
            where: _ @whereConditions
            hasRoles: _ @whereHasConditions(relation: "roles")
        ): [User!]! @all
    }
    ';

    protected function getPackageProviders($app): array
    {
        return array_merge(
            parent::getPackageProviders($app),
            [WhereConditionsServiceProvider::class]
        );
    }

    public function testHasRelationWithHasCondition(): void {
        $users = factory(User::class, 3)->create();
        $roles = factory(Role::class, 2)->create();
        $users[0]->roles()->attach($roles[0]);
        $users[1]->roles()->attach($roles[1]);
        $role2_id = $roles[1]->id;

        $this->graphQL(/** @lang GraphQL */ "
        {
            users(
                where: {
                    HAS: {
                        relation: \"roles\"
                        operator: GTE
                        amount: 0
                    }
                }
                hasRoles: {
                    column: \"id\"
                    operator: NEQ
                    value: $role2_id
                }
            ) {
                id
                roles {
                    id
                }
            }
        }
        ")->assertExactJson([
            'data' => [
                'users' => [
                    [
                        'id' => $users[0]->id,
                        'roles' => [
                            'id' => $roles[0]->id,
                        ]
                    ],
                    [
                        'id' => $users[2]->id,
                        'roles' => []
                    ],
                ],
            ],
        ]);
    }
}

```
**Lighthouse Version**
Lighthouse: v5.23.0

**Comment by thekonz** [comment]
But isn't that just how sql works?
http://sqlfiddle.com/#!9/19d7fd/2

I hope that fiddle works. If not, here are the queries:
```sql
create table foo(
  id int auto_increment primary key,
  val int null
);

insert into foo(val) values (1),(2),(1),(null);

select * from foo where val != 1;
```
There are 4 entries: 1, 2, 1, and null.
A query with `val != 1` returns only the entry with `2`, because null has to be checked with `is null` or `is not null` and cannot be selected using `=`.

**Comment by MuhmdRaouf** [comment]
In your example yes the behavior is totally normal, the thing is whenever you use Where Condiction with WhereHasCondiction it will always eliminate the object that doesn't have a relation

the query in the above test result this query 
```SQL
select * from `users` where 
((select count(*) from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `users`.`id` = `role_user`.`user_id`) >= 0)
and 
(exists (select * from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `users`.`id` = `role_user`.`user_id` and `roles`.`id` != 2))
```

if you can see the first part:
```SQL
where: {
  HAS: {
    relation: \"roles\"
    operator: GTE
    amount: 0
  }
}

((select count(*) from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `users`.`id` = `role_user`.`user_id`) >= 0)
```
which is fine and will return all the users with no roles too as the count of 0 will satisfy the condition.


for the second part:

```SQL
hasRoles: {
  column: \"id\"
  operator: NEQ
  value: $role2_id
}

(exists (select * from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `users`.`id` = `role_user`.`user_id` and `roles`.`id` != 2))
```
the problem here is using exists as it will always eliminate the users with no roles as the select will return nothing so it will felter those users out as the relation does not exist and will not satisfy the condition.

Hope that was informative for you to see my point.

**Comment by thekonz** [comment]
So what is your expected resulting sql query?

**Comment by MuhmdRaouf** [comment]
Umm... I was manipulating the query a bit and it seems we won't be able to achieve this behavior easily or we will be needing to add a parameter to generate a different query in order to get the data like the following.

basically,  to achieve that I switch the operators in the second query which will fetch all the users 
http://sqlfiddle.com/#!9/09ab14/26

IDK if that makes sense but it returns the needed data.

also if you have another idea of how to get the data like the above with the current Where/WhereHas condition I would be glad to hear it.

**Comment by thekonz** [comment]
I recommend using the [@scope](https://lighthouse-php.com/5/api-reference/directives.html#scope) directive.
Full query flexibility, very lightweight schema. Try if that works better.
