### ISSUE TITLE
Renaming relations  when used  Nested Mutations is error  "Array to string conversion"

### ISSUE THREAD

**Issue by phamducthang1004** [nuwave/lighthouse#1942]
I have :
  + file graphql
![error-1](https://user-images.githubusercontent.com/58019392/134840445-95e3797c-422d-4f6b-b1ff-90f0f5d9fc28.JPG)
  + file model 
![error-2](https://user-images.githubusercontent.com/58019392/134840503-12cc8692-0f4b-4662-a292-fcd941d33923.JPG)
Run in  graphql-playground
![error-3](https://user-images.githubusercontent.com/58019392/134840692-9a4eb14d-a81c-4fd3-adba-d84b3ed26b80.JPG)

When i not used  Renaming relations ,  field  like name relation in model 
![error-4](https://user-images.githubusercontent.com/58019392/134841204-cb46a24c-5e9b-405e-91ec-9e6d21103199.JPG)
![error-5](https://user-images.githubusercontent.com/58019392/134841262-05b98814-8052-42c5-a552-e9c094a5a388.JPG)

Run success  in  graphql-playground
![error-6](https://user-images.githubusercontent.com/58019392/134841474-57e67629-a4fc-4c99-9748-63410834aeb2.JPG)
I used : "nuwave/lighthouse": "^5.18"
Why used  renaming relations for  nested mutations had error ?
Please help me solve this problem!

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
