### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by ctf0** [nuwave/lighthouse#196]
thanx so dam much for this package, having the same schema syntax in both front & end is just heaven 😍.

still could someone pleaaaaaaaaaaaaaase for the love of god, do something with the documentation ?

i have to keep at least 10 tabs opened from "examples, issues, the official doc, the src files" just to understand how things works 😭.

**Comment by spawnia** [comment]
Thanks for the praise, we hope to deliver the best dev experience possible with the library.

I do agree that the documentation can be a bit spotty in parts. So, i invite you to contribute your findings to https://github.com/nuwave/lighthouse-docs

The docs are open source and free for everyone to improve!

**Comment by ctf0** [comment]
the problem is am still learning it, and the docs in its current form is a big wall in front of anyone wants to get involved.

i believe the more experienced/veteran users like you would do much more than a newbie like myself + it would avoid tickets like https://github.com/nuwave/lighthouse/issues/106

**Comment by spawnia** [comment]
I would love to hear some concrete suggestions on what we can put in the docs to make it easier.

What parts in particular where hard for you to? What information did aid you in understanding?

**Comment by spawnia** [comment]
> how to create custom directives

We are planning some substantial changes to the interfaces for custom directives. Once those are through, we will add docs for that!

> transforming from rest

https://github.com/nuwave/lighthouse-docs/issues/12 you can add ideas/comments there

> namespaces in @group

https://github.com/nuwave/lighthouse-docs/issues/13

> work with lumen

https://github.com/nuwave/lighthouse/issues/123 would be a necessity, the docs should not require much of a mention once everything is compatible

> general GraphQL syntax

https://github.com/nuwave/lighthouse-docs/issues/14

> input validation

https://github.com/nuwave/lighthouse-docs/issues/15

Thank you for your input, it is really valuable. We are always open for new suggestions/questions.

It is preferrable to keep them focused, do not hesitate to open seperate issues here or in the docs repo if anything else comes up. Thanks!

**Comment by ctf0** [comment]
will do, thanx
