### ISSUE TITLE
The @validator directive on Mutation can not find the class

### ISSUE THREAD

**Issue by tevva** [nuwave/lighthouse#1960]
lighthouse version: 5.2.4
php 7.4

extend type Mutation {
    createUser(
        name: String!
        email: String!
        password: String! @hash
    ): User
    @validator
    @field(resolver: "UserMutator@create")
}

The validator class is App\GraphQL\Validators\Mutation\CreateUserValidator 
The file CreateUserValidator.php is in the folder App\GraphQL\Validators\Mutation

The error:

 "message": "No class `Mutation\\CreateUserValidator` was found for directive `@validator`",
 "exception": "Nuwave\\Lighthouse\\Exceptions\\DefinitionException"

Any help is appreciated.

**Comment by tevva** [comment]
I think it is an advanced development if you have a bug in your code and i'm trying to report this bug.

Let me do this way. The @validator directive doesn't work properly on Mutation, it returns the error message that the validator class not found.

**Comment by spawnia** [comment]
They are the same in terms of namespace resolution.
