### ISSUE TITLE
Not working on production server

### ISSUE THREAD

**Issue by syn6UK** [nuwave/lighthouse#1970]
Hi There,

I have an app that I've inherited from another developer, they are using lighthouse with laravel.

It runs fine through the docker image. Yet when trying to deploy to an Azure Web App Service, the requests no longer return the desired repsonse but return the following error.

`{
    "errors": [
        {
            "message": "GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"",
            "extensions": {
                "category": "request"
            }
        }
    ]
}`

Making the exact same request on the docker server, returns the desired response.

I've checked all of the config and it seems fine, database connection is good, redis cache is connected fine. I've also tried clearing the cache using artisan console.

I'm on the verge of pulling my hair out if anyone can advise or assist on where to look next?

Thanks,
Rob

**Comment by enzonotario** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

**Comment by enzonotario** [comment]
So far, try to put `APP_DEBUG=true` on your `.env` to see more info about the error.
