### ISSUE TITLE
 Laravel GraphQl getting Could not connect to websocket endpoint error

### ISSUE THREAD

**Issue by pishguy** [nuwave/lighthouse#1973]
After implementing a simple `GraphQl` query such as a simple `Mutation` and `Subscription` I get this error when I try to run this `subscription` into `graphql-playground`:

```gql
subscription {
   userCreated{
     name
     username
     password
   }
}
```

I get this error on `graphql-playground`:

```
{
  "error": "Could not connect to websocket endpoint ws://127.0.0.1:8000/graphql. 
Please check if the endpoint url is correct."
}
```

GraphQl Schema:

```gql
#...
type User {
    id: Int!
    name: String
    email: String
    product : [Product!]
}

type Mutation {
 createUser(
    name: String!
    password: String!
    email : String!
  ): User @field(resolver:"UserMutator@create") @broadcast(subscription: "userCreated")
}

type Subscription {
  userCreated: User
}

```

`UserMutator` class:

```dart
class UserMutator{
    public function create($_ , array $args){
        $user =  User::create($args);
        Subscription::broadcast('userCreated',$user);
        //return $user;
    }
```

`UserCreated` Subscription

```dart
class UserCreated extends GraphQLSubscription
{
    public function authorize(Subscriber $subscriber, Request $request): bool
    {
          return true;
    }

    public function filter(Subscriber $subscriber, $root): bool
    {
        return true;
    }
}
```

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
