### ISSUE TITLE
Target [Nuwave\Lighthouse\Subscriptions\Contracts\ContextSerializer] is not instantiable while building [Nuwave\Lighthouse\Subscriptions\SubscriptionRegistry]. 

### ISSUE THREAD

**Issue by burasuk** [nuwave/lighthouse#1974]
When i run:

`\Nuwave\Lighthouse\Execution\Utils\Subscription::broadcast('newOrder',$order);`

i'm having error:

```
Illuminate\Contracts\Container\BindingResolutionException 

Target [Nuwave\Lighthouse\Subscriptions\Contracts\ContextSerializer] is not instantiable while building [Nuwave\Lighthouse\Subscriptions\SubscriptionRegistry]. 
```

**Expected behavior/Solution**

Broadcast event.

**Steps to reproduce**

1. Add subscription schema

```graphql
type Subscription {
  newOrder: Order
}
```

2. Add the service provider to `config/app.php`
3. Defining fields

`php artisan lighthouse:subscription PostUpdated`

4. Starting the WebSocket server

I'm using Laravel Websockets:

`php artisan websockets:serve`

**Lighthouse Version**

5.18

**Laravel version**

7.11

**Comment by spawnia** [comment]
Are you sure you registered the `SubscriptionServiceProvider`? It binds an implementation for `ContextSerializer`.

**Comment by burasuk** [comment]
Yes i'm sure.
![image](https://user-images.githubusercontent.com/7629077/141738612-1927afc8-660a-4be8-9d41-78fd9b81bc76.png)

**Comment by spawnia** [comment]
Perhaps `php artisan websockets:serve` does not bind the usual service providers? Can you check if `SubscriptionServiceProvider::register()` is run at all? Just edit it in your project and include something like `die('hard');`.

**Comment by burasuk** [comment]
No, `SubscriptionServiceProvider::register()` didn't run.

**Comment by spawnia** [comment]
Alright. I don't think there is anything we can do then.

You will have to figure out how to set up Laravel to include the service provider when running `php artisan websockets:serve`. If you do, I would be happy about a pull request that enhances the docs about this topic, something such as:

```
## Usage with laravel-websockets

In order for service providers to register properly, do xyz.
```

**Comment by burasuk** [comment]
I found solution for this issue.
Just **clear laravel cache**. 
I found that list of providers(in cache) doesn't contain `SubscriptionServiceProvider` in `bootstrap\cache\services.php`.
