### ISSUE TITLE
response static data wihtout query

### ISSUE THREAD

**Issue by baravak** [nuwave/lighthouse#1976]
response static data wihtout any database query ex: server time, last android version and somthing else
```
{
server_time:....
server_uptime:....
android{
        last_version:1.6.0
        force_version: 1.5.0
   }
}
```

**Comment by enzonotario** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
