### ISSUE TITLE
[PHP 8.1] DocumentAST implements the Serializable interface, which is deprecated

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#1985]
**What problem does this feature proposal attempt to solve?**

```bash
PHP: 8.1
nuwave/lighthouse: 5.26
```

PHP message: PHP Deprecated:  Nuwave\Lighthouse\Schema\AST\DocumentAST implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary). 

**Which possible solutions should be considered?**

As described on warning those methods should be implemented. But, I really have no idea about impacts on current Lighthouse codebase.

**Comment by olivernybroe** [comment]
You could try and implement it and see if tests fails? ;)

**Comment by olivernybroe** [comment]
There are a lot of development happening for PHP 8.1 in this pr #1954

**Comment by robsontenorio** [comment]
@olivernybroe Thanks , but I am late , @spawnia already did it 😄

I will check it.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v5.27.0

**Comment by robsontenorio** [comment]
@spawnia @olivernybroe  Just for future reference. I upgraded to 5.27

Right after deploy got this error. Is that expected? 


```
Erroneous data format for unserializing 'Nuwave\Lighthouse\Schema\AST\DocumentAST'

```

Here is my deploy workflow
```
php artisan key:generate
php artisan lighthouse:clear-cache
php artisan config:cache
php artisan lighthouse:cache
```

**Comment by spawnia** [comment]
@robsontenorio I recommend you to upgrade to https://github.com/nuwave/lighthouse/releases/tag/v5.27.1. It improves the behaviour of `lighthouse:cache` and allows you to remove `lighthouse:clear-cache` from your deployment steps.

Also, you must ensure that Lighthouse upgrades and cache regeneration are deployed atomically. I described this in the updated docs for schema caching: https://github.com/nuwave/lighthouse/commit/8872570ec724fe3e2a59930e44927b7ff9c1d094
