### ISSUE TITLE
The returned "channel_data" property type is inconsistent with Pusher Channels documentation 

### ISSUE THREAD

**Issue by bozhidarc** [nuwave/lighthouse#1991]
According to Pusher [auth documentation](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#pushersubscribe-client-greater-pusher-channels)  on authentification the returned `channel_data` property should be encoded as string.

> data.channel_data (String) [optional]
> This property should be populated with additional information about the channel if the channel is a presence channel. The JSON for the channel_data will be generated on the application server and should be encoded as a string and assigned to this property. The format of the object is as follows:

This is a problem because if you try to use Lighthouse with  Laravel WebSockets as Pusher replacement it expects the `channel_data` to be string.

**Expected behavior/Solution**

The `channel_data` property to be returned encoded as string.

nuwave/lighthouse = v5.25.0
beyondcode/laravel-websockets = 1.12.0

**Comment by bozhidarc** [comment]
Sorry, my bad!

**Comment by orlandoxnica** [comment]
I have the same error, what did you do to fix it?
