### ISSUE TITLE
Simple pagination is wrong scenario of original simple pagination

### ISSUE THREAD

**Issue by baravak** [nuwave/lighthouse#1993]
**Describe the bug**
We use `simple pagination` to optimize queries and resources;
In order to send only one query and also in millions of database records we do not need to find the desired range
for exmalpe

### true scenario

```
select * from users where id > 19587566987 limit 3 order By ID DESC
```
results:
```
19587566988
19587566989
19587566990
```
and next query is
```
select * from users where id > 19587566990/*(last resut id in prev query)*/ limit 3 order By id ASC
```

### current scenario in lighthouse
just remove count query

```
select * from users limit 9875569,3
// and next query
select * from users limit 9875572,3
```

**Expected behavior/Solution**

**Steps to reproduce**

1.
2.
3.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

**Comment by spawnia** [comment]
I don't understand your issue and how it relates to Lighthouse. Please add an example schema definition and query.

**Comment by baravak** [comment]
```
query{
   users: [Post!]! @paginate(type: SIMPLE){
      id
   }
}
```
in laravel `simple paginate` work as:
```
select * from users where id > 19587566987 limit 3 order By ID DESC
```

and lighthouse work as:
```
select * from users limit 9875569,3
```

ligthouse scenario for `simple paginate` is wrong and is not as `laravel simple paginate`

**Comment by spawnia** [comment]
Lighthouse is using `Builder::simplePaginate()`, and it is working fine. We have tests that cover this functionality.

Your Laravel example seems to be using cursor pagination, which is a different thing. I think what you are asking is the same as this feature request: https://github.com/nuwave/lighthouse/issues/311#issuecomment-838396479

For the future: If you are inclined to open any further issues in Lighthouse, please think about what constitutes a bug and what is a feature request. If something does not behave the way you want it to, it is not necessarily a bug.

**Comment by baravak** [comment]
ok tanks dear
