### ISSUE TITLE
additional where calauses (whereIn, whereNotIn) errors

### ISSUE THREAD

**Issue by mostafa-rouzbahani** [nuwave/lighthouse#2003]
**Describe the bug**

In the [documents ](https://lighthouse-php.com/master/api-reference/directives.html#where) provide that you can use other where clauses from Laravel providers. In these cases `whereIn` and `whereNotIn`, I got an error. 

**Expected behavior/Solution**

_Current solution_: Using `@in` directive.
_Expected behavior_: Have the data with `whereIn` or `whereNotIn` filter.
_Reason_: [This line](https://github.com/nuwave/lighthouse/blob/3ba2353a9c3f83ab1e6cc152455625054455708a/src/Schema/Directives/WhereDirective.php#L42) must be the value for these clauses, not the operator.

**Steps to reproduce**

1. create a query and use `@where` directive with `clause: "whereIn"` attribiute.
```graphql
type Query {
    dog(
        id: ID @where(clause: "whereIn", key: "id")
    )}
```
2. run the query.

**Output/Logs**

<details><summary>Click to expand</summary>

```
"debugMessage": "Illuminate\\Database\\Query\\Builder::cleanBindings(): Argument #1 ($bindings) must be of type array, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 972"
```

</details></br>

**Lighthouse Version**

v5.25.0

**Comment by spawnia** [comment]
Clarified in https://github.com/nuwave/lighthouse/commit/fc0cf78b26c7d4556e2158018c6ba1a8ec5f764b
