### ISSUE TITLE
Error in mutation nuwave/lighthouse:^5.0 and input

### ISSUE THREAD

**Issue by ascott-main** [nuwave/lighthouse#2010]
I am using nuwave/lighthouse:^5.0, and I am trying to create a mutation for an entity which have a belongsTo relationship. The thing is that in my input I am using a sanitizer directive to transform from string to id, but after that when Laravel gets the properties, it shows errors with the validation of the class. In addition, I debug the directive code and it works correctly.

**The record should be created since the data is present and valid**

**Steps to reproduce**

1.
```
input CreateContentInput {
    content_type: CreateContentTypeBelongsTo!
    name: String
}

input CreateContentTypeBelongsTo {
    connect: ID! @typeuuid(model: "App\\ContentType")
    create: CreateContentTypeInput
    update: UpdateContentTypeInput
}
```
2.
```
class Content extends Model
{
    protected $rules = [
        'content_type_id' => 'required|integer|is_main_content_type',
    ];

    /**
     * @return BelongsTo
     */
    public function contentType(): BelongsTo
    {
        return $this->belongsTo(ContentType::class);
    }
}

class TypeUuidDirective extends BaseDirective implements ArgSanitizerDirective, ArgDirective, FieldMiddleware
{
    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'SDL'
"""
Convert string to id of input value.
"""
directive @typeuuid(
  """
  Specify the class name of the model to use.
  This is only needed when the default model detection does not work.
  """
  model: String
) on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION | FIELD_DEFINITION
SDL;
    }

    /**
     * Remove whitespace from the beginning and end of a given input.
     */
    public function sanitize($argumentValue)
    {
        $entity = Content::find(3);
        return $entity->id;
    }
}

```
3.
```
mutation {
  createContent(
    input: {
      name: "Test name GraphQL 3"
      content_type: { connect: "0e0e70c4-ccfb-4cfd-959f-a9452e78367a" }
    }
  ) {
    id
    name
  }
}
```

**Output/Logs**

<details>
{
    "errors": [
        {
            "message": "The given data was invalid.",
            "extensions": {
                "validation": {
                    "content_type_id": [
                        "The content type id field is required."
                    ]
                },
                "category": "validation"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createContent"
            ],
            <summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version: 5.24**

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
