### ISSUE TITLE
RequestError with latest version

### ISSUE THREAD

**Issue by Ferikl** [nuwave/lighthouse#2015]
with latest version I`ve notice 500 error:

**GraphQL\Server\RequestError**
Unexpected content type: "application/json;charset=UTF-8"

In version v5.31.3  all works fine

**Steps to reproduce**

1. Send standsrd GraphQL request with header Content-Type: application/json;charset=UTF-8

GraphQL\Server\RequestError
Unexpected content type: "application/json;charset=UTF-8"

v5.33.0

**Comment by spawnia** [comment]
I added proper regression tests and fixed this for all content types, released with https://github.com/laragraph/utils/releases/tag/v1.1.1

**Comment by Ferikl** [comment]
Thank you!
