### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by vantuanprimelabo** [nuwave/lighthouse#202]
I want to you help me, I can't install lighthouse.
It's Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
No message when i press url : http://127.0.0.1:8000/public/graphql
 protected function methodNotAllowed(array $others)
    {
        throw new MethodNotAllowedHttpException($others);
    }

**Comment by vantuanprimelabo** [comment]
how to define route url?

**Comment by hailwood** [comment]
It's great to see you getting involved with Lighthouse!
The github issues are for bug reports, feature requests, and issues related to the development **of** Lighthouse.

For support related questions please join the Lighthouse Slack Community as outlined in the ["get involved" section of the readme.](https://github.com/nuwave/lighthouse#get-involved).

You'll receive a faster and more helpful response there :)
