### ISSUE TITLE
From v.5.40: "Call to undefined function Safe\substr()" when run `php artisan lighthouse:ide-helper`

### ISSUE THREAD

**Issue by jBernavaPrah** [nuwave/lighthouse#2027]
Hi,

Starting from v5.40 I receive the error when I try to run `php artisan lighthouse:ide-helper`. 
This is because the function `Safe/substr`  (on file `src/Schema/Types/LaravelEnumType.php`) is not anymore present on the package `thecodingmachine/safe@v2`. 

Using specifically v1 on my composer is fixing the error. 

Happy to help further if needed.
JBP

**Comment by spawnia** [comment]
In order for us to constinually ensure we are compatible with v2, we need https://github.com/thecodingmachine/phpstan-safe-rule/pull/28 to be merged.

I installed the fork locally and fixed the errors - including the one you reported - and will release a fixed Lighthouse version soon. Please leave this issue open until for now though, I plan to update the fix with a continuous solution.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v5.35.2

**Comment by olivernybroe** [comment]
It looks like this issue has been fixed, if my assumption is wrong I'll reopen 👍
