### ISSUE TITLE
`@rename` directive not satisfied in relationship shortcut

### ISSUE THREAD

**Issue by pyrou** [nuwave/lighthouse#2033]
Lighthouse [v5.35.0](https://github.com/nuwave/lighthouse/releases/tag/v5.35.0) introduced a feature that shortcut `@belongsTo` and `@morphTo` if the client only selects the `id` of the relation. This detection is performed within the [RelationDirective.php#L42](https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/RelationDirective.php#L42).

However, the field lookup doesn't take in consideration a possible `@rename` directive if present.

**Expected behavior/Solution**

RelationDirective shortcut should satisfy `@rename` directive if any, or, alternatively, a way to not perform the shortcut should be offered (directive on `User.id` field ? directive on `User` type ? argument on `@belongsTo` directive ?) 

**Step to reproduce**

Considering the following schema : 

```graphql
type Query {
    posts: [Post!]! @all
}
type Post {
    ...
    # user is linked to post using the `id` field of the user model) 
    author: User! @belongsTo(relation: "user")
}
type User {    
    # a `uuid` column exists on user model, we decide to use that one as the `id`.
    id: ID! @rename(attribute: "uuid") 
    ...
}
```

if, as a client, I perform the query `posts { author { id } }`, lighthouse will shortcut the `@belongsTo` directive. But `@rename` directive still apply and will lookup for an `uuid` property on a `['id' => 123]` object. In this particular use-case, this would lead to the following error :

> Cannot return null for non-nullable field "User.id". 

On the same manner, with the following User schema :

```graphql
type User {
    identifier: ID! @rename(attribute: "id") 
    ...
}
```

querying `posts { author { identifier } }` wont benefit shortcut optimization.

**Lighthouse Version**

[v5.35.0](https://github.com/nuwave/lighthouse/releases/tag/v5.35.0) and newest

**Comment by spawnia** [comment]
Do you think returning a proxy object that returns the ID for every possible key would be sufficient to resolve this error? Can you think of any problems with that?

```php
return new class($id) {
    protected $id;
    public function __construct($id) { $this->id = $id; }
    public function __isset() { return true; }
    public function __get() { return $this->id; }
}
```

I guess to be really safe we have to check if there are resolvers on the field - which could in theory do anything. I just wonder how many additional checks we can add before the shortcut is no longer worth it. My guess is we have quite a large budget to go with, considering the relative speed of PHP execution and a database call.

**Comment by pyrou** [comment]
I'm not sure how this would resolve this error, by using the proxy you are proposing, certainly the error "Cannot return null for non-nullable field "User.id"." will disappear BUT you'll get the $user->id instead of expected $user->uuid.

Maybe a PR with a failing unit test would clarify the issue for anyone ?
I'll do it tomorrow.

**Comment by spawnia** [comment]
Thanks @pyrou. I disabled the shortcut by default in https://github.com/nuwave/lighthouse/releases/tag/v5.38.2
