### ISSUE TITLE
Add GraphQL Fragment Support

### ISSUE THREAD

**Issue by NickStallman** [nuwave/lighthouse#2034]
**What problem does this feature proposal attempt to solve?**

I'm looking in to GraphQL Fragments to improve query reusability. This is a standard GraphQL feature and it's also fully supported by webonyx/graphql-php so implementing it shouldn't be too involved.

**Which possible solutions should be considered?**

Currently using a fragment throws the following error:

```
  Unknown definition type: GraphQL\Language\AST\FragmentDefinitionNode
  at vendor/nuwave/lighthouse/src/Schema/AST/DocumentAST.php:135
```

It looks like another branch is needed to handle instanceof ExecutableDefinitionNode.
I'm not sure if Fragments can functionally be included with DocumentAST->types[] or whether a new DocumentAST property would be required to track fragments.

**Comment by k0ka** [comment]
What is your query? 

This one works without any problems

```graphql
query test{
  ...testFragment
}

fragment testFragment on Query {
	__typename
}
```

**Comment by pyrou** [comment]
According to exception location you are pointing, it turns out you tried to use fragment in the graphql schema.

Fragments is something on query side (so for API client-side), not schema (server-side)

**Comment by NickStallman** [comment]
Ahhh my mistake, thanks for the quick clarification!

**Comment by JoaoHamerski** [comment]
@pyrou What do you mean? So how can i reuse fields in different queries on server side? I have to rewrite every single field in every single query?

**Comment by NickStallman** [comment]
@JoaoHamerski I made the same incorrect assumption, the Fragments are a client side feature, so you can define the fragment once in your client side and use it in many queries. It's not defined server side.

Server side would have been cool, if there are multiple apps doing very similar queries, but that's not the way GraphQL defined it.

**Comment by pyrou** [comment]
Do you have a concrete example of what you are trying to achieve with a fragment server side ?

Union and/or interface might meet your need.

**Comment by JoaoHamerski** [comment]
@pyrou @NickStallman 
I have this query on my schema `orders.graphql`:
```
extend type Query {
  orders(
    orderBy: _ @orderBy(columns: ["created_at", "delivery_date", "production_date"])
    where: String @whereConditions(columns: ["code", "closed_at", "delivery_date"])
    hasCity: String @whereConditions(columns: ["name"])
    hasStatus: Int @whereConditions(columns: ["id"])
  ): [Order!] @paginate
}
```

And as lighthouse provide relationships i have the type client with a relation `a client has many orders`, so on my `Client` type i want to query all the orders again so i do that on `client.graphql`:

```
type Client @guard {
  id: ID!
  orders (
    orderBy: _ @orderBy(columns: ["created_at", "delivery_date", "production_date"])
    where: String @whereConditions(columns: ["code", "closed_at", "delivery_date"])
    hasCity: String @whereConditions(columns: ["name"])
    hasStatus: Int @whereConditions(columns: ["id"])
  ): [Order]  @hasMany(type: "paginator")
}
```

As you can see the `orders` field repeat the exactly same arguments for the `Client type` and `Order query`, and probably i'll need to reuse the exactly same arguments in other queries, so do graphql provide any way to make it reusable? Or i have to rewrite every time in situations like that?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
