### ISSUE TITLE
How to use custom handler for where conditions extending the default handler?

### ISSUE THREAD

**Issue by JoaoHamerski** [nuwave/lighthouse#2037]
That's the way i'm currently doing:

```lang-php
class ClientHandler extends WhereConditionsHandler
{
    /**
     * @param  \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder  $builder
     * @param  array<string, mixed>  $whereConditions
     */
    public function handler(object $builder, array $whereConditions): void
    {
        $column = $whereConditions['column'];
        $value = $whereConditions['value'];

        if ($column === 'phone') {
            if (Str::startsWith($value, '(') && Str::endsWith($value, ')')) {
                $builder->where('phone', 'like', Formatter::stripNonDigits($value) . '%');
                return;
            }
        }
        

        // If none of my custom conditions is satisfied, it applies the default handler __invoke
        $this->__invoke($builder, $whereConditions);
    }
}
```

I couldn't find anywhere else on the internet or documentation talking about that.

Here is the problem: I want to apply some addition rules for the `builder`, but i don't want to lose all the default logic or recreate all of it, i just want to make some additional conditions i need, is there any right way to do it? The workaround i made is working but i wounder if there is something official about that.

Obs.: I know that channel should not be used to questions like "how to use" but that's not a popular lib on stackoverflow, i could find a answer here faster.

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by JoaoHamerski** [comment]
@spawnia 
> Obs.: I know that channel should not be used to questions like "how to use" but that's not a popular lib on stackoverflow, i could find a answer here faster.

**Comment by spawnia** [comment]
You acknowledging this policy and blatantly stating that you disregard it does not improve your case.
