### ISSUE TITLE
How to add orderBy directive to relationship in a query?

### ISSUE THREAD

**Issue by JoaoHamerski** [nuwave/lighthouse#2039]
I have this:
```
type Client @guard {
  id: ID!
  name: String!
  phone: String
  orders: [Order!]! @hasMany # How do i make it possible to order this array?
}

```

```
extend type Query {
  client (
    id: ID! @eq
  ): Client @find
}
```

I would like to do something like that:

```
{
  client (id: 10) {
    orders (orderBy: ....) {
    }
  }
}

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
