### ISSUE TITLE
Use of method not available.

### ISSUE THREAD

**Issue by hosmelq** [nuwave/lighthouse#204]
**Describe the bug**

Throw exception for the usage of [fromSub](https://github.com/nuwave/lighthouse/blob/46f9b8745e351d05754da530d9fc5590d6bbdb9a/src/Support/DataLoader/QueryBuilder.php#L118) method of the query builder, this method was added in [v5.6.12](https://github.com/laravel/framework/blob/5.6/CHANGELOG-5.6.md#v5612-2018-03-14).

**Environment**

Lighthouse Version: v2.2-alpha.1
Laravel Version: 5.5

**Comment by spawnia** [comment]
Thanks for reaching out and for the excellent bug report!

I would still like to support Laravel 5.5 if possible. Do you think this can be worked around?

**Comment by spawnia** [comment]
Resolved by #209

**Comment by hosmelq** [comment]
Hello @spawnia, sorry for late.

We have the same problem, `fromRaw` was added in the same version.

**Comment by spawnia** [comment]
Any ideas how we can fix this in a nice way?

**Comment by hosmelq** [comment]
This is the method we need.

```php
public function fromRaw($expression, $bindings = [])
{
    $this->from = new Expression($expression);
    
    $this->addBinding($bindings, 'from');
    
    return $this;
}
```

What to you think about to monkeypatch with a macro ?

**Comment by chrissm79** [comment]
I'll have a PR for this shortly, found another method

**Comment by chrissm79** [comment]
@hosmelq Go ahead and pull down the latest from master and let me know if that last merged fixes things for you.

**Comment by hosmelq** [comment]
Thank you, it is working 😄
