### ISSUE TITLE
Content-Type:application/json;charset=utf-8 not recognized

### ISSUE THREAD

**Issue by guillaumeboussion** [nuwave/lighthouse#2054]
Hi,

Using GraphQL on a Flutter app, a HTTP Request being made by the native dart httpclient automatically specifies the encoding type of the json data. I can't use the GraphQL plugin because of the lack of support on batched queries.

On the server side, the "application/json;charset=utf-8" is not recognized in the RequestParser::parseRequest() and is throwing RequestError. Would a ";charset=utf-8" portion support be possible ?

Otherwise, it would mean some client have to override the http request handler just to avoid the encoding portion.

**Comment by k0ka** [comment]
What version of `laragprah/util` are you using? The latest one should parse it without problems

https://github.com/k0ka/utils/blob/master/src/RequestParser.php#L52

**Comment by guillaumeboussion** [comment]
My bad! I was still on the 1.1.0. I've just updated it and it fixed the issue (I should have take a look to the `laragraph/util` package and its issue : https://github.com/laragraph/utils/issues/5)

Thanks guys for the package btw :)
