### ISSUE TITLE
@clearCache directive does not clear the cache of a type

### ISSUE THREAD

**Issue by oscar-ol** [nuwave/lighthouse#2055]
The clearCache directive does not clear the cache of a type, p.ex. the User type.
$parentName in CacheDirective.php is set to "Query" and ClearCacheDirective.php is searching for "User".

**Steps to reproduce**
- 'tags' => true in lighthouse.php
- cache driver: Redis
- schema:
```graphql
type Query {
    user(id: ID @eq): User @cache @find
}

type Mutation {
    deleteUser(id: ID!): User @delete @clearCache(type: "User")
}

type User {
    id: ID!
}
```
```
- get user 1 => Redis sets the key lighthouse:Query::user:id:1
- delete user 1 =>  Redis tries to delete key lighthouse:User::user:id:1
- get user 1 => it still returns the deleted user.
```
Setting $parentName = "User", it works.

**Comment by spawnia** [comment]
Read https://lighthouse-php.com/master/performance/caching.html#clear-cache

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
