### ISSUE TITLE
Cannot return null for non-nullable field \"User.id\".",

### ISSUE THREAD

**Issue by JoaoHamerski** [nuwave/lighthouse#2058]
When i'm using a custom builder `@paginate(builder: '...')` returning some custom data where it might have a null foreign key, lighthouse returns this error:

```
"debugMessage": "Cannot return null for non-nullable field \"User.id\".",
```

In the type `User` i have the `id`  field as required, but if the relation foreign key is null, why is it trying to query the type User, instead of just returning null?

```
type User @guard {
    id: ID!
    name: String!
    email: String!
    email_verified_at: DateTime
    created_at: DateTime!
    updated_at: DateTime!
    role: Role! @belongsTo
}

type CashFlowEntry @guard {
  id: ID
  user: User @rename(attribute: "user_id") # Sometimes it can be null
  value: Float
  date: Date
  description: String
  created_at: DateTime
}

extend type Query {
  cashFlowEntries: [CashFlowEntry] @paginate(builder: "App\\GraphQL\\Builders\\CashFlowEntriesBuilder")
}
```

The query
```
{
  cashFlowEntries (first: 100){
    data {
      id
      order { #If the order_id is null, why try to get id? Just return null to order field instead of throw an error. 
        id
      }
    }
  }
}
```
**Lighthouse Version**
5.39

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by JoaoHamerski** [comment]
@spawnia My dude, slack is just dead, i asked for support there 2 weeks ago, this library isn't so popular for people to be in an exclusive channel just to answer questions. This is also valid for stackoverflow.

If you want to see this library growing up just make the same thing as Vue in the begging and stop being an asshole, allow people share knowledge anywhere, not even Laravel repository is so strict about questions.
