### ISSUE TITLE
GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\

### ISSUE THREAD

**Issue by hktom** [nuwave/lighthouse#2060]
**Describe the bug**
I m getting this error message after all configuration on a live Laravel server: GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\. In the same project it works fine on localhost.

**Steps to reproduce**

1.
2.
3.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**
"mll-lab/laravel-graphql-playground": "^2.5",
"nuwave/lighthouse": "^5.39",
"php": "^7.3|^8.0",
"laravel/framework": "^8.12",

**Comment by k0ka** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by hktom** [comment]
After many research, I have found the problem. I was missing a slash at the end of my URL. 
I changed https://my-url/graphql 
to 
https://wkz.moringapp.com/graphql/ 
and it worked!

**Comment by Tanzaverse** [comment]
@hktom can you please show me what you did? Where did you add "/"
