### ISSUE TITLE
Allow renaming attribute only on serialization

### ISSUE THREAD

**Issue by guillaumeboussion** [nuwave/lighthouse#2062]
**What problem does this feature proposal attempt to solve?**

We can have multiple different named attributes for a single type. For example, I can have : 
```graphQL
type Brand {
    id: Int!,
    name: String!,
    slug: String!,
    logo: String!,
    image: String,
    description: HtmlToArray,
    comments: String,
    state: String!,
    important: Boolean!,
    categories: [Category] @belongsTo,
    offers: [Offer] @belongsTo
    ordered_offers(
        hasProducts:_ @whereHasConditions(columns:["id"])
    ): [Offer] @scope(name: "available") @belongsTo(relation: "offers") @builder(method: "App\\GraphQL\\Builders\\Offer@setIsNullOrderByClause")
}
```

So I do have 2 attributes returning the same `Offer` relation. The thing is, I can't have 2 `offers` attributes. And in my client, I'd like to always use the `offers` attribute, whether I call `offers` or `ordered_offers`. 

**Which possible solutions should be considered?**

So I thought of a `@renameFront` directive, which would allow a schema to specify the attribute name returned like

```graphQL
ordered_offers: [Offer]! @belongsTo(relation: "offers") @renameFront(name: "offers")
```

so that on serialization, it would return an `offers` json key

Do you think it's possible ? I began to look for handling this by myself, but I'm not able to see if I can do it with a simple custom field directive

**Comment by spawnia** [comment]
You can use GraphQL aliases.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by guillaumeboussion** [comment]
Sorry, didn't know that such feature already exists! I've been looking into lighthouse docs for a long time so I considered relevant to make it a feature request. Thanks for the answer tho :)
