### ISSUE TITLE
Introspection should return federation schema if corresponding Service Provider is enabled

### ISSUE THREAD

**Issue by renepardon** [nuwave/lighthouse#2065]
**What problem does this feature proposal attempt to solve?**

When using rover CLI to create a supergraph SQL for GraphQL Federation, it requests the service with an introspection query. The problem here is that the full schema including federation fields are returned resulting in errors like: 

```bash
error[E029]: Encountered 1 build error while trying to build a supergraph.

Caused by:
    Encountered 1 build error while trying to build the supergraph.
    UNKNOWN: Field "Query.node" can only be defined once.
    
        The subgraph schemas you provided are incompatible with each other. See https://www.apollographql.com/docs/federation/errors/ for more information on resolving build errors.
```

You can also manually trigger it:

```bash
rover graph introspect http://localhost:8020/graphql | grep node
```

You will see `node(id: ID!): Node` as query field within stdout. 

Maybe I'm wrong but the output should not contain this additional query for federation.

Testing the same two nuwave/lighthouse provided services with GraphQL mesh results in different errors:

```bash
🕸️: An error occured while writing the schema file: Unknown directive "@extends".
🕸️: An error occurred while building the mesh artifacts: Unknown directive "@extends".
```

The errors appear as soon as I add this to one of my services:

```graphql

""" Federation specific adjustments """
type User @key(fields: "id") @extends {
    id: ID! @external
    tenant(filters: TenantOptions @spread): Tenant!
        @belongsTo(scopes: ["filters"])
        @can(ability: "tenant.show")
}
```

**Which possible solutions should be considered?**

The introspection query should return the federation specific schema if federation service provider is enabled. The node query should not appear in the query.

**Comment by spawnia** [comment]
According to https://www.apollographql.com/docs/federation/federation-spec/#fetch-service-capabilities:

> It is important to preserve the type extensions and directive locations and to omit the federation types.

This does not mention the exclusion of fields or types that have nothing to do with federation. If that is a requirement, how would we even know which fields should be kept?

GraphQL Mesh complaining about `@extends` seems like a problem on their side, again I think Lighthouse complies with the federation spec:

> Apollo Federation supports using an @extends directive in place of extend type to annotate type references

**Comment by renepardon** [comment]
@spawnia I researched a lot and I really couldn't find any Query.node definition. The only thing I had was this common interface I use in my services:

```graphql
interface Node {
    _id: ID @globalId
    id: ID!
}
```

All types implement this interface and removing the interface but keeping the implementation on types resolves the problem with duplicate Query.node error. So there must be a problem with @globalId being used on an interface. For now I just ensure the types implement **_id** and **id** properly without the interface. For the @extends error I will ask at Graphql-Mesh repository because Apollo Gateway starts without problems after executing rover CLI.

**Comment by spawnia** [comment]
`Query.node` is added when a field implements an interface `Node` - given you defined this interface yourself, perhaps Lighthouse should not do this. See https://github.com/nuwave/lighthouse/blob/8ce9d15d829bf096a32ae3a1a630d59ab168227e/src/GlobalId/GlobalIdServiceProvider.php#L36-L38

**Comment by renepardon** [comment]
So we could improve lighthouse to not add the Node interface, if it’s already present within the custom Schema Definition?
