### ISSUE TITLE
unable to install laravel 9.0.1

### ISSUE THREAD

**Issue by oaktreecode** [nuwave/lighthouse#2066]
**Describe the bug**
composer require nuwave/lighthouse

Using version ^5.39 for nuwave/lighthouse
./composer.json has been updated
Running composer update nuwave/lighthouse
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nuwave/lighthouse[v5.39.0, ..., v5.39.2] require illuminate/auth 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 || ^8 -> found illuminate/auth[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires nuwave/lighthouse ^5.39 -> satisfiable by nuwave/lighthouse[v5.39.0, v5.39.1, v5.39.2].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Expected behavior/Solution**

**Steps to reproduce**

1.
2.
3.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

**Comment by spawnia** [comment]
https://github.com/nuwave/lighthouse/pull/2052
