### ISSUE TITLE
Validation with "regex:pattern" may break depending on the regex pattern

### ISSUE THREAD

**Issue by PenguinDetective** [nuwave/lighthouse#2072]
I would like to apply the `@rule` directive to a field.
E.g.
```gql
phone: String @rules(apply: ["regex:/^\+[1-9]\d{1,14}$/i"], messages:[{rule:"regex", message:"The phone field does not follow E.164 standards"}])
```
**Describe the bug**
Using a `regex:pattern` may create an internal server error, depending on the pattern.
```
{
  "errors": [
    {
      "debugMessage": "Syntax Error: Invalid character escape sequence: \\+, near: 255\"])\n    phone: String @rules(apply: [\"regex:/^\\+[1-9]\\d{1,14}$/i\"], messages:[{rule:\"regex\", mess",
      "message": "Internal server error",
      "extensions": {
        "category": "schema"
      },
```
**Expected behavior/Solution**
Lighthouse states that it uses Laravel Validation under the hood (Source: https://lighthouse-php.com/5/security/validation.html). Therefore, a [regex validation](https://laravel.com/docs/9.x/validation#rule-regex) should not create an internal server error.
It should be possible without creating a custom [Validator class](https://lighthouse-php.com/5/security/validation.html#validator-classes), or creating a [custom validation rule](https://laravel.com/docs/9.x/validation#using-rule-objects) and using it [in the `@rule` directive](https://lighthouse-php.com/5/security/validation.html#single-arguments).

**Lighthouse Version**
5.24

**Comment by spawnia** [comment]
You are using an invalid GraphQL string literal and thus trigger a syntax error.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by PenguinDetective** [comment]
After moving this question to the Slack channel, @spawnia linked [to this GraphQL specification](https://spec.graphql.org/June2018/#sec-String-Value). Some values, e.g. `/`, `\`, `"` in the GraphQL rule string need to be escaped with a backward slash.

I.e., my back-/ and forward slashes need to be escaped.

The now working rule looks like
```gql
phone: String @rules(apply: ["regex:\/^\\+[1-9]\\d{1,14}$\/"])
```
Thanks!
