### ISSUE TITLE
@search directive with orderby

### ISSUE THREAD

**Issue by ercanilbars** [nuwave/lighthouse#2074]
I using scout with meilisearch but search directive not working with orderBy

Error
`Found arg builder arguments that do not work with @search`
Graphql
`input OrderByClause {
           column: String!
           order: DESC
}
type Query {
    users(search: String @search orderBy: [OrderByClause!] @orderBy): [User!]! @paginate

`
Query 
` 
users(first:10, search: "test", orderBy: [ {column: "id", order: DESC}])
`
Working In Controller
`$users = User::search('test')->orderBy('id','desc')->paginate()

Anyone have any ideas?

**Comment by spawnia** [comment]
I don't get the point of this issue. The error message is clear and explicit, what you are trying does not work.
