### ISSUE TITLE
@can directive can't detect model from Type when relation @hasmany on field is paginator. 

### ISSUE THREAD

**Issue by webard** [nuwave/lighthouse#2078]
**Describe the bug**

@can directive can't detect model from Type when relation @hasMany on field  is paginator. I have schema:

```gql
type Product @model(class: "App\\Product\\Product") {
    id: ID
    name: String
    reviews: [ProductReview!] @hasMany(type: PAGINATOR) @can(ability: "list reviews")
}

type ProductReview @model(class: "App\\Product\\Reviews") {
    id: ID!
    author: ID!
}

query {
    products: [Product] @paginate
}
```

As you see, I define @model in type, so @can directive and other directives should read proper model from Type. Everything works fine with @can on fields, until field is not paginated relation. In example above, error is:

```
Failed to find class ReviewsPaginator in namespaces [App\\Models] for directive @can.
```

but when we delete `type: PAGINATOR` from @hasMany, everything works fine and @can directive can detect proper model.
I know I can declare `model` argument in @can directive, but using @model on type simplifies life, so detecting paginated relation should works.

**Output/Logs**

<details><summary>Click to expand</summary>

```
Failed to find class ReviewsPaginator in namespaces [App\\Models] for directive @can.
```

</details></br>

**Lighthouse Version**

5.42.0, Laravel 9.3.0

**Comment by spawnia** [comment]
Can you add a failing test case to https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/HasManyDirectiveTest.php? I think we can then fix this by adding `@model` to the generated `type ReviewsPaginator`.

**Comment by webard** [comment]
Ok it will be ready soon.
