### ISSUE TITLE
Extend support for `@deprecated` directive

### ISSUE THREAD

**Issue by wimski** [nuwave/lighthouse#2081]
The `@deprecated` directive currently is only allowed on `FIELD_DEFINITION` and `ENUM_VALUE`:

```graphql
"""
Marks an element of a GraphQL schema as no longer supported.
"""
directive @deprecated(
  """
  Explains why this element was deprecated, usually also including a
  suggestion for how to access supported similar data. Formatted
  in [Markdown](https://daringfireball.net/projects/markdown/).
  """
  reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE
```

However any schema element could become deprecated at some point, like an obsolete/unused input field for example. Would it be possible to add the following to the supported types of the `@deprecated` directive?

* `ARGUMENT_DEFINITION`
* `INPUT_FIELD_DEFINITION`

**Comment by spawnia** [comment]
Looks like this will be possible in an upcoming version of the GraphQL specification - see https://github.com/graphql/graphql-spec/pull/805#issuecomment-1029319320

We have to implement this in the base library first though, see https://github.com/webonyx/graphql-php/issues/110

**Comment by owenvoke** [comment]
@spawnia, is this now ok to implement for Lighthouse? 👀

**Comment by spawnia** [comment]
It is already possible to use `@deprecated` as described, given https://github.com/webonyx/graphql-php/releases/tag/v15.4.0 is installed. I updated our definition of the directive in https://github.com/nuwave/lighthouse/pull/2607.

**Comment by spawnia** [comment]
Released the updated definition with https://github.com/nuwave/lighthouse/releases/tag/v6.44.0.

**Comment by owenvoke** [comment]
@spawnia, interestingly, when dumping the schema with `php artisan lighthouse:print-schema`, it strips the `@deprecated` tag from the output for both of these. When looking into it, it seems like the `deprecationReason` property never gets added for arguments.

I've opened https://github.com/nuwave/lighthouse/pull/2609 to fix the issue, but please let me know if I'm missing something.
