### ISSUE TITLE
Method Illuminate\Http\Response::assertGraphQLErrorMessage does not exist while testing with PHPUnit

### ISSUE THREAD

**Issue by mfissehaye** [nuwave/lighthouse#2082]
This is the feature test that I wrote.

```
$this->graphQL($this->campaignByIdQuery)->assertGraphQLErrorMessage(
            "Unauthenticated."
        );
```

I have run `php artisan lighthouse:ide-helper` and `php artisan optimize` and the classes can be referenced in my IDE. But the test suite is throwing this error.
```
BadMethodCallException : Method Illuminate\Http\Response::assertGraphQLErrorMessage does not exist.
 /path/to/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
 /path/to/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:1606
 /path/to/project/tests/GraphQL/Queries/CampaignQueryTest.php:49
 ```

**Comment by spawnia** [comment]
https://lighthouse-php.com/master/testing/phpunit.html#setup

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
