### ISSUE TITLE
expired redis entries causes error

### ISSUE THREAD

**Issue by majchrosoft** [nuwave/lighthouse#2085]
**Describe the bug**

depending on setup, redis mget command can return 
`(nil)`
for expired items. Then unserialize returns false, because it's not valid serialized object. Subscrption returns error

**Expected behavior/Solution**
just ignore expired entries
Here is the fork:
https://github.com/nuwave/lighthouse/pull/2084/files

**Steps to reproduce**

1.
2.
3.

**Output/Logs**

<details><summary>Click to expand</summary>

```
 Nuwave\Lighthouse\Subscriptions\Storage\RedisStorageManager::Nuwave\Lighthouse\Subscriptions\Storage
{closure}(): Return value must be of type ?Nuwave\Lighthouse\Subscriptions\Subscriber, bool returned
```

</details></br>

**Lighthouse Version**
5.42.0

this commit causes error:
https://github.com/nuwave/lighthouse/commit/7821e150bb014baed16e38e7922e9db46bd70e0a

**Comment by majchrosoft** [comment]
Hi @spawnia ,

Sorry for the chaotic way of proceeding, but unfortunately, that code
which was merged still have an issue

right now it works only for default setup from laravel for handling warnings
`vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php`

as You can see in above file
`set_error_handler($this->forwardsTo('handleError'));`
```

    public function handleError($level, $message, $file = '', $line = 0, $context = [])
    {
        if ($this->isDeprecation($level)) {
            return $this->handleDeprecation($message, $file, $line);
        }

        if (error_reporting() & $level) {
            throw new ErrorException($message, 0, $level, $file, $line);
        }
    }
```
exactly that part 
 ```
       if (error_reporting() & $level) {
            throw new ErrorException($message, 0, $level, $file, $line);
        }
```
is responsible for throwing ErrorException when the Warning is introduced,

In case somebody will overwrite this logic and will rely on function unserialize behavior - which returns FALSE
the actual hotfix will not work anymore.

**Comment by majchrosoft** [comment]
Let me know if i should expose another merge request with one more if, or U will just handle that.

Best Regards,

**Comment by spawnia** [comment]
If someone messes with Laravel core behaviour, that is on them.

**Comment by sytzez** [comment]
It will also not work if `error_reporting(E_NOTICE)` is not enabled. I suggest something like:

```
                try {
                    $unserialized = unserialize($subscriber);
                    return $unserialized instanceof Subscriber 
                        ? $unserialized 
                        : null;
                } catch (\ErrorException $e) {
                    return null;
                }
```

**Comment by majchrosoft** [comment]
@sytzez i am not 100% sure, but still i agree
that there is  probably the error_reporting setting in which the condition will be not met

having
error_reporting(0)


 0 & E_NOTICE gives 0

in condition
```
      if (error_reporting() & $level) {
           throw new ErrorException($message, 0, $level, $file, $line);
       }
```
if is not met. exception is never thrown

**Comment by majchrosoft** [comment]
but the application error_reporting is still forced by laravel in the same file

**Comment by majchrosoft** [comment]
anyway, the strange thing is, that i cannot reproduce my bug anymore locally

but i still have this bug on development environment on project in which i am working now 

i am trying to find the cause but without a success

**Comment by sytzez** [comment]
@majchrosoft I'm in the same situation. The bug occurs on our staging server but not on production

**Comment by majchrosoft** [comment]
@sytzez @spawnia 

ok, debugged
So, the situation is quite interetning

1) first mget queries for not existing values - for some reason smember  still returns these values, when they are not exist anymore
```
>>> $subscribers = $asd->connection->command('mget', [['sadf','dasda','vdfb']]);
=> [
     false,
     false,
     false,
   ]

```


then the magic happens - due to declared `?string` in anonymouse function argument
```
>>> collect($subscribers)->map(function(?string $asdd){var_dump($asdd);});
string(0) ""
string(0) ""
string(0) ""
=> Illuminate\Support\Collection {#5171
     all: [
       null,
       null,
       null,
     ],
   }
```
now we can see that the `null` values are being casted to empty string

but having unserialized just an empty string 
```
>>> collect($subscribers)->map(function(?string $asdd){var_dump(unserialize($asdd));});
bool(false)
bool(false)
bool(false)
=> Illuminate\Support\Collection {#5196
     all: [
       null,
       null,
       null,
     ],
   }
```
causes taht unserialize still returns FALSE. In this case - without E_NOTICE - it's just usual  behavior of unserialize

**Comment by majchrosoft** [comment]
@spawnia 
here is new pull request (includes new test case)
https://github.com/nuwave/lighthouse/pull/2095/files

**Comment by majchrosoft** [comment]
@spawnia 
Hi,

I would want to Ask You is there a reason that this file 
src/Subscriptions/Storage/RedisStorageManager.php

Don't have declareed strict types ?

I think with strict types, the code would be much better maintainable. No implicit casts then.

**Comment by spawnia** [comment]
I plan to switch to strict types in the entire project in v6.
