### ISSUE TITLE
Multiple @aggregate fields on same column with wrong values

### ISSUE THREAD

**Issue by ivanwitzke** [nuwave/lighthouse#2087]
**Describe the bug**

When using `@aggregate` on same relation and column with different scopes, the value of the last queried field is returned for both values when querying both fields.

I have the following type definition, where `conversions_amount` should return the sum of all conversions for a campaign, and `conversions_pending_amount` should return the sum of those conversions which are still pending for payment (the `pending` scope)

    type AppUserCampaign {
        id: ID!
        title: String!
        ...
        conversions: [Conversion] @hasMany(scopes: ["ofUser"])
        conversions_amount: Int @aggregate(relation: "conversions", column:"commission_amount", scopes: ["ofUser"], function: SUM)
        conversions_pending_amount: Int @aggregate(relation: "conversions", column:"commission_amount", scopes: ["ofUser", "pending"], function: SUM)
    }

When querying with:

    {
        me {
            uid
            campaigns {
                id
                conversions_amount
                conversions_pending_amount
            }
        }
    }

it returns 

    {
        "data": {
            "me": {
                "uid": "rLkpFc774xayeRZqUgV7xh0M7hu2",
                "campaigns": [
                    ...
                    {
                        "id": "4",
                        "conversions_amount": 10000,
                        "conversions_pending_amount": 10000
                    }
                ]
            }
        }
    }

When the `conversions_amount` is queried last, both fields will return the value of the `conversions_amount`, and when omiting the `conversions_pending_amount` from the query, it returns, with the correct value for the remaining field

    {
        "data": {
            "me": {
                "uid": "rLkpFc774xayeRZqUgV7xh0M7hu2",
                "campaigns": [
                    ...
                    {
                        "id": "4",
                        "conversions_amount": 11500,
                    }
                ]
            }
        }
    }

**Expected behavior/Solution**

After some debugging, I believe that the problem is that when resolving the fields relationships (inside `Illuminate\Database\Eloquent\Collection::loadAggregate`), both queries will have the same relationship name ("conversions_sum_commission_amount" in my case), so when the `$model->forceFill()` method in that function is called, it overrides the previous value

**Steps to reproduce**

1. Create a type with at least two `@aggregate` on a relationship, one of them with a scope limiting some results
2. Run a query with only one field at a time
3. Run a query with both fields, check that the value returned is the same for both (it will return the value of the last field for both of them)
4. Invert the order of the fields and check the values again. The same behaviour of item 3 should occur

**Lighthouse Version**:  5.26.1
**Laravel version**: 8.73.0

**Comment by spawnia** [comment]
Thanks for the detailed report. Please try and check if using the latest version of Lighthouse solves your issue. If not, please add a pull request with a failing test case to https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/AggregateDirectiveTest.php

**Comment by ivanwitzke** [comment]
Updated to v5.43.0 and the issue is gone
