### ISSUE TITLE
@deprecated already defined in js-graphql plugin Specification.graphql

### ISSUE THREAD

**Issue by stephenjason89** [nuwave/lighthouse#2099]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/3810177/160077588-5921b568-583d-4d2f-8448-d814735a6f3e.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/3810177/160077616-8fd7b636-2feb-4bf0-a752-600074d7edf3.png">
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/3810177/160077662-2fac61e2-a699-4fa5-abe2-c100c8f9d5d2.png">

I tried to add Specification.graphql to my excludes in .graphqlconfig but it didn't work
For now, i just delete the one in schema-directives.graphql

**Comment by spawnia** [comment]
How about we add an option to `php artisan lighthouse:ide-helper` that allows not generating built-in directives?

**Comment by stephenjason89** [comment]
I think that would be perfect. Thank you @spawnia

**Comment by d-fischer** [comment]
This is still a problem that needs fixing. A parameter to the ide-helper commands sounds good to me.
