### ISSUE TITLE
Directive @guard doesnt work properly with authentication methods

### ISSUE THREAD

**Issue by Subwaytime** [nuwave/lighthouse#2102]
**Describe the bug**

`@guard` changes Guard from `SessionGuard` to `RequestGuard` eventhough its configurated differently.
I am not 100% sure, if this is intended behavior or even considered a Bug! Might be a configuration Issue..

**Expected behavior/Solution**

When using the `@guard` directive on a mutation, it is not possible to call the `logout` function on the default Auth Guard.
`Auth::logout()` and `auth()->logout()` will both throw `Method Illuminate\\Auth\\RequestGuard::logout does not exist`

NOTE: Both logout functions work totally fine without  the `@guard` directive and its also using the `SessionGuard` then. It also worked before updating to Laravel 9 and the newest Lighthouse Version.

**Steps to reproduce**

1. Setup Lighthouse with Sanctum

`auth.php`
```
   'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ]
```

`sanctum.php`
```
    'guard' => ['web'],
```

`lighthouse.php`
```
     'middleware' => [
            
        // Nuwave\Lighthouse\Support\Http\Middleware\EnsureXHR::class,
        \Nuwave\Lighthouse\Support\Http\Middleware\AcceptJson::class,
            
            
         // Logs in a user if they are authenticated. In contrast to Laravel's 'auth'
         // middleware, this delegates auth and permission checks to the field level.
         \Nuwave\Lighthouse\Support\Http\Middleware\AttemptAuthentication::class,
            
         // Logs every incoming GraphQL query.
         // \Nuwave\Lighthouse\Support\Http\Middleware\LogGraphQLQueries::class,
            
         \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
      ],

      'guard' => 'sanctum',
```

2. Create a Mutation
`schema`

```
type Mutation {
    logout: User @guard
}
```

`logout.php`
```
<?php

namespace App\GraphQL\Mutations;

use Illuminate\Support\Facades\Auth;

class Logout {
    /**
     * @param  null  $_
     * @param  array<string, mixed>  $args
     */
    public function __invoke($_, array $args) {
        $user = auth()->user();
        auth()->logout();

        return $user;
    }
}
```

**Output/Logs**

`Method Illuminate\\Auth\\RequestGuard::logout does not exist`

**Lighthouse Version**

"laravel/sanctum": "^2.14.1"
"laravel/framework": "^9.5.1"
"nuwave/lighthouse": "^5.40"

**Comment by spawnia** [comment]
It should be `'guard' => 'web',` in `lighthouse.php`.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by Subwaytime** [comment]
Hmm thats interesting. Should the docs then be updated?
https://lighthouse-php.com/5/security/authentication.html#laravel-sanctum

It shows that to use `sanctum` here! 🤔 Might be missleading some Users!

**Comment by spawnia** [comment]
You are not using sanctum though, you are using session authentication.

**Comment by Subwaytime** [comment]
As far as the Laravel Documentation is written, Sanctum can be cookie/session based or token based.
Quote

> For this feature, Sanctum does not use tokens of any kind. Instead, Sanctum uses Laravel's built-in cookie based session authentication services.
> It is perfectly fine to use Sanctum only for API token authentication or only for SPA authentication. Just because you use Sanctum does not mean you are required to use both features it offers.

The Ligthhouse Docs dont really mention that Sanctum guard is only for the token based authentication.

Or do i missunderstand this?
