### ISSUE TITLE
Make it possible to use a @scope directive in a type declaration/ on a field definition

### ISSUE THREAD

**Issue by SuperDJ** [nuwave/lighthouse#2107]
**Are you willing to provide a PR for this issue or aid in developing it?**
Yes

**What problem does this feature proposal attempt to solve?**

I have a `users` table with the following fields: `first_name`, `insertion`, `last_name`. I quite often need to get the full name. Of course it is possible to select all fields individually and then use an if-statement to create the full name that way. Something like the following in blade: 
```blade
{{ $user->first_name }} @if($user->insertion){{ $user->insertion }}@endif {{ $user->last_name }}
```

But doing that each time a full name is required is quite cumbersome as well. Therefor I created the following scope method:
```php
public function scopeWithFullName( Builder $query ): Builder
{
   return $query->selectRaw("CONCAT_WS(' ', `first_name`, `insertion`, `last_name`) AS `full_name`");
}
```
This allows me to do the following and show the full name.

```php
$user = User::withFullName()->first();
$user->full_name;
```
So it would be nice if you could declare a graphql type like below:
```graphql
type User
{
  first_name: String
  insertion: String
  last_name: String!
  full_name: String @scope(name: "withFullName")
}
```

**Which possible solutions should be considered?**

Make it possible to use the [`@scope`](https://lighthouse-php.com/master/api-reference/directives.html#scope) directive on a field definition.

This might be similar or related to https://github.com/nuwave/lighthouse/issues/1888.

**Comment by spawnia** [comment]
I think this is actually the same as #1888, please comment there with your use case.
