### ISSUE TITLE
remove unsubscribed subscriptions

### ISSUE THREAD

**Issue by daichancorgi** [nuwave/lighthouse#2118]
I use subscription, pusher and redis.

So I have the question of unsubscribe.

server side => pusher => front side

[This doc part](https://lighthouse-php.com/5/subscriptions/client-implementations.html#apollo-for-pusher) means just stop **pusher => front side**. 
If I don't remove the redis, still server side working and push message to pusher, right?

```
  unsubscribeFromChannel(subscriptionChannel) {
    this.pusher.unsubscribe(subscriptionChannel);
  }
```

I want to know what options I have.

thanks

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
