### ISSUE TITLE
Set HTTP Cache-Control header for the response

### ISSUE THREAD

**Issue by mostafa-rz** [nuwave/lighthouse#2126]
**What problem does this feature proposal attempt to solve?**

The Cache-Control header for any response from Lighthouse is no-cache, private. This header can be used by CDN to set correct caches values for the response. Most of the CDNs have the option to ignore this header, so it is possible to use it as it is, but then it needs to set the invalidation rules manually in the CDN. It is possible to calculate the invalidation rules from the schema and send it by the response header.
[Apollo](https://www.apollographql.com/docs/apollo-server/performance/caching#calculating-cache-behavior) has some rules to calculate the final cache header values. The rules are based on the `@cacheControl` directive. We have the same information in the `@cache` directive.

- The response's maxAge equals the lowest maxAge among all fields. If that value is 0, the entire result is not cached.
- The response's scope is PRIVATE if any field's scope is PRIVATE.

**Which possible solutions should be considered?**

1. Add env variables to enable this feature and some default values for max-age and max-stale.
2. Calculate the final cache header values for the request based on the rules.
4. Pass the final cache values to the Nuwave\Lighthouse\Support\Http\Controllers: GraphQLController
5. Add the headers to the response by createResponse($result)->setCache()

**Comment by spawnia** [comment]
Seems like we can pretty much copy what Apollo does here, their approach seems to be battle-tested and proven.

@stayallive what do you think?

**Comment by spawnia** [comment]
Is `@cacheControl` a prerequisite for this feature request, or can they be implemented independently?

**Comment by stayallive** [comment]
IMO they can be totally separated, maybe even better because the plumbing to get the cache control header back to the controller can and should be re-used. So whichever is implemented first makes the second trivial.

Maybe it's even a good idea to start with `@cacheControl` since it's the cleanest (no config, no magic) and implement `@cache` auto-`@cacheControl` afterwards?

**Comment by mostafa-rouzbahani** [comment]
@stayallive Thanks for sharing your idea.
@spawnia I would like to contribute to implementing the issue. Is anyone working on this?

**Comment by spawnia** [comment]
@mostafa-rouzbahani Not that I know of. Feel free to go ahead with it. Starting with just `@cacheControl` seems good.

**Comment by mostafa-rouzbahani** [comment]
@stayallive To make it clear what I am going to do:

1. Add the `@cacheControl` directive.
2. The `@cacheControl` has nothing to do with server-side caching(at least for now).
3. The `@cacheControl` is used to collect client-side caching values(maxAge, scope).
4. The HTTP Cache-Control header is calculated from the collected values.

**Comment by stayallive** [comment]
Sounds great! Enjoy and let us know if you get stuck. Looking forward to this 🤘
