### ISSUE TITLE
Call to undefined method Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query()

### ISSUE THREAD

**Issue by IMingGarson** [nuwave/lighthouse#2128]
Hi, I am currently working on Lighthouse and I ran into the issue as title suggested.

The story is that I am trying to use `ClearCache` feature which is introduced on v.5.33.0.

However, the latest Lighthouse and its dependencies requires at least PHP 7.4 or PHP 8 or above while mine is PHP 7.3.

For now I can't update my PHP version,  therefore I decided to assign a fixed version in composer.json file. 

**version**
1. PHP: 7.3.32 
2. Laravel: 6.20.44
3. mll-lab/graphql-php-scalars: 3.1.0
4. nuwave/lighthouse: 5.33.0
5. thecodingmachine/safe: 1.3.3
6. composer 1.9.0

These are installable version in my composer.json

However, I realized that in this commit:
https://github.com/nuwave/lighthouse/commit/a4cca968f8ef8ecc3636568485982fd494b8a082 ```query``` method is removed and therefore causing the problem.

**Steps to reproduce**

1. Change dependencies versions mentioned above
2. Run any query on playground or with HTTP requests to see the result

How should I reconfigure it and make it work?
If not, is it possible for me to use some other mechanism that can clear GraphQL cache?

Thank you.

**Full error**
file: "/Users/iminghsu/Desktop/Sites/ec-gql/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php"
line: 48
message: "Call to undefined method Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query()"

**Comment by IMingGarson** [comment]
Update:
I have uninstalled whole folder in vendor and install 5.33.0 version again.
However, when I look into the `Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController`, the `query` method is already deleted.

It seems that my composer can't download version 5.33.0.
I logged the whole `$route` object in ControllerDispatcher dispatch function

```
{
  "Illuminate\\Routing\\Route":{
    "uri":"graphql",
    "methods":["GET","POST","HEAD"],
    "action":{
      "as":"graphql",
      "uses":"Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController**@query**",
      "middleware":["Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson"],
      "controller":"Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController@query"
    },
    "isFallback":false,
    "controller":[],
    "defaults":[],
    "wheres":[],
    "parameters":[],
    "parameterNames":[],
    "computedMiddleware":[
          "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson"
       ],
       "compiled":[]
    }
}

And I don't know why @query is still there while it has been removed in GraphQLController.

**Comment by spawnia** [comment]
> However, the latest Lighthouse and its dependencies requires at least PHP 7.4 or PHP 8 or above

Lighthouse itself does not require that: https://github.com/nuwave/lighthouse/blob/9ca44e4f91fd8ee0efc5532ec0cef62edd7c0d34/composer.json#L29, perhaps some dependency of it?

> install 5.33.0

I always recommend that latest stable release.

It looks like your application has an outdated route cache: https://laravel.com/docs/9.x/routing#route-caching

**Comment by IMingGarson** [comment]
@spawnia Big thanks for pointing it out!
I clear route cache and follow this page https://github.com/nuwave/lighthouse/blob/c00cc7e5de3ecfcc6ad3a50aa9c93b6b88f75ff7/UPGRADE.md

Everything works fine instead of `Replace custom validation directives with validator classes` part

Originally I have an `UpsertAuthorInputValidationDirective` and the Mutation.graphql looks like this:

```
upsertAuthor(id: ID, input: AuthorInput! @spread): Author!
    @upsert
    @upsertAuthorInputValidation
```

After I chagned my mutation to 
```
upsertAuthor(id: ID, input: AuthorInput! @spread): Author!
    @upsert
    @validator
```
And the class to 
```
namespace App\GraphQL\Validators;

use Illuminate\Validation\Rule;
use Nuwave\Lighthouse\Validation\Validator;

class UpsertAuthorInputValidationDirective extends Validator {
      public function rules(): array
          {
              return [
                  'name' => [
                      Rule::unique('authors', 'name')->ignore($this->arg('id'), 'id'),
                  ],
              ];
          }
}

```
I got this error:
`Failed to find class Mutation\\UpsertAuthorValidator in namespaces [] for directive @validator.`

How do I resolve it?

**Comment by IMingGarson** [comment]
Update

I think I figured it out, it turned out that I have to rename it to UpsertAuthorValidator and move it under `App\GraphQL\Validators\Mutation` folder.
