### ISSUE TITLE
Laravel 9 only_full_group_by

### ISSUE THREAD

**Issue by stephenjason89** [nuwave/lighthouse#2135]
"nuwave/lighthouse": "^v5.48.2",

on laravel 8 everything works as expected
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/3810177/166186749-39915c70-84ba-4c94-be50-16bb8e8804dd.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/3810177/166184656-a30bd8d6-ae3a-4e17-9cd8-f313b00419b7.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/3810177/166184673-793ca8e3-dc8a-464a-8c92-02f24b4a1566.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3810177/166184766-f141e2f7-d125-4a78-a9a5-273ffd803fc9.png">

However on laravel 9 it throws me errors
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/3810177/166184818-4dd261f1-0870-471b-9850-ab147dc10631.png">

any help is deeply appreciated

**Comment by spawnia** [comment]
It appears that upgrading to Laravel 9 changed the setting of [the SQL mode `ONLY_FULL_GROUP_BY`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by).

While the example query where you only select the field `tag` makes sense, consider that a query that includes additional fields not present in the aggregate will lead to nonsensical results, e.g. requesting field `id`. Generally, `GROUP BY` change the shape/semantics of the SQL result and should only be used in dedicated fields, not mixed with general purpose fields.

**Comment by stephenjason89** [comment]
Hello @spawnia ,
I have the 2 projects running
1 is using laravel 8
1 is using laravel 9

They both use the same mysql db and settings
However they yield different results.

I understand the use of ONLY_FULL_GROUP_BY and would like to keep on using it.
On my query only tag is selected and no other fields which can't be used like id

**Comment by spawnia** [comment]
The resulting SQL statement will have `SELECT *`.

The design problem is that the API allows misuse, you *could* query ID when using `groupByModel`, which would be nonsensical. You can avoid this misuse by just having a separate field that queries the group by.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

**Comment by stephenjason89** [comment]
@spawnia Thank you for the clarification.
However, why the difference in behavior between laravel 8 and laravel 9 project?
