### ISSUE TITLE
Issue when try to follow the documentation for Testing Extension

### ISSUE THREAD

**Issue by jBernavaPrah** [nuwave/lighthouse#2137]
Hi, I'm trying to mock the schema in one of my tests. 

I'm following the [documentation](https://lighthouse-php.com/master/testing/extensions.html#use-a-test-schema), but trying to execute the test I have this error: 
`Fatal error: Tests\Unit\MyTest and Nuwave\Lighthouse\Testing\UsesTestSchema define the same property ($schema) in the composition of Tests\Unit\MyTest. However, the definition differs and is considered incompatible. Class was composed in /var/www/html/tests/Unit/MyTest.php on line 10`

How can I mock the schema so I can test extensions without the need to rely on the current implementation of the schema?

I'm using PHP 8.1, Lumen v9 and lighthouse v5.48.

This is my test class: 

```php
<?php

namespace Tests\Unit;

use Nuwave\Lighthouse\Testing\MocksResolvers;
use Nuwave\Lighthouse\Testing\UsesTestSchema;
use Tests\TestCase;


class MyTest extends TestCase
{

    use UsesTestSchema;
    use MocksResolvers;

    protected $schema =  /** @lang GraphQL */ '
        type Query {
            foo: Int! @mock
        }
';

    protected function setUp(): void
    {

        parent::setUp();
        $this->setUpTestSchema();
    }

    public function testHandler()
    {

        $this->mockResolver('foo');

        $this->graphQL(/** @lang GraphQL */ '
    {
        foo
    }
    ')->seeJson([
            'data' => [
                'foo' => 'oof',
            ],
        ]);
    }
}


```

Thanks for the help.

**Comment by spawnia** [comment]
This error has not come up in Lighthouse because it uses `UsesTestSchema` in its base test class. Apparently, child classes are then allowed to redefine `protected $schema`.

I updated the documentation to only recommend setting `$this->schema` from within specific test cases, it is a better pattern anyways to have small and specific test schemas.
