### ISSUE TITLE
@event directive not returning "changes" on model

### ISSUE THREAD

**Issue by eNzyOfficial** [nuwave/lighthouse#2151]
**Describe the bug**

For some reason using `@event` directive with `@create` (and possibly `@update`) removes all the changes made in the model. 

For example if you `$model = User::create(...)` you can `$model->getRawOriginal()` and `$model->getAttributes()` (and other similar functions) to get the original and changed attributes.

This is missing and these 2 functions return the same data and `$model->getChanges()` is an empty array.

**Steps to reproduce**

Dispatch an event on `@create`

```
createCompany(input: CompanyCreateInput! @spread): Company!
        @create
        @event(dispatch: "App\\Events\\ModelCreated")
```

Inside the listener, check the model for changes:

`$model->getChanges()`

or compare `$model->getRawOriginal()` and `$model->getAttributes()`

**Comment by eNzyOfficial** [comment]
Ok, so after poking around a bit more, it seems like this is the intended functionality within Laravel.

The reason is that when `->save()` is called on the model, all changes are wiped from the model via `$this->syncOriginal()` replacing the originals with the new values.

Between `->save()` and `$this->syncOriginal()` the `saved` event is fired containing all the original attributes.

The obvious solution would be hooking into the `saved` event. The problem is that I only want to hook in to this event when a model is saved/created/updated via graphql and no where else in the codebase.

The simplest (but possibly a little hacky) solution I can think of is to send out events from graphql? `updated`, `graphql:saved`, etc.

**Comment by spawnia** [comment]
> The problem is that I only want to hook in to this event when a model is saved/created/updated via graphql

This seems like a very odd and specific use case. I don't think there is anything for Lighthouse to do here.
