### ISSUE TITLE
@cacheKey with @rename not working

### ISSUE THREAD

**Issue by mostafa-rz** [nuwave/lighthouse#2152]
**Describe the bug**

The `@cachekey` is not working with `@rename`.

**Expected behavior/Solution**

Work with it.

**Failure test**

```
public function testCacheKeyWithRenameDirective(): void
    {
        $this->mockResolver([
            'id' => 1,
            'name' => 'foobar',
            'email_name' => 'foo@bar.com',
        ]);

        $this->schema = /** @lang GraphQL */ '
        type User {
            id: ID!
            name: String @cache
            emailName: String @cacheKey @rename(attribute: "email_name")
        }

        type Query {
            user: User @mock
        }
        ';

        $response=$this->graphQL(/** @lang GraphQL */ '
        {
            user {
                name
            }
        }
        ')->assertJson([
            'data' => [
                'user' => [
                    'name' => 'foobar',
                ],
            ],
        ]);

        $this->assertSame('foobar', $this->cache->get('lighthouse:User:foo@bar.com:name'));
    }
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
Failed asserting that null is identical to 'foobar'.
```

</details></br>

**Lighthouse Version**

5.51.0

**Comment by spawnia** [comment]
Technically `@rename` is nothing special, it is a field resolver just like `@field` or `@method`. Maybe we can leverage that and just call the field resolver of whatever field has `@cacheKey` dynamically?

**Comment by mostafa-rz** [comment]
I didn't look deep inside it, but I know there is a cacheKey method inside the TypeValue class which is responsible for it. Is it possible to call the field resolver inside it?

**Comment by spawnia** [comment]
Unfortunately, it is not that easy. We would have to:
- grab a reference to the field resolver
- call it with the right arguments (root, client given args, context, `ResolveInfo` with correct path)

It might be easier to add in special treatment for `@rename` in this instance.

**Comment by mostafa-rz** [comment]
@spawnia Another fail test with `@field`. The resolved field value is not contained in the root array.
``` php
public function testCacheKeyWithFieldDirective(): void
    {
        $this->mockResolver([
            'id' => 1,
            'name' => 'foobar',
        ]);

        $this->schema = /** @lang GraphQL */ '
        type User {
            id: ID!
            name: String @cache
            email: String @field(resolver:"Tests\\\Utils\\\Resolvers\\\Foo@bar") @cacheKey
        }

        type Query {
            user: User @mock
        }
        ';

        $this->graphQL(/** @lang GraphQL */ '
        {
            user {
                name
            }
        }
        ')->assertJson([
            'data' => [
                'user' => [
                    'name' => 'foobar',
                ],
            ],
        ]);

        $this->assertSame('foobar', $this->cache->get('lighthouse:User:1:name'));
    }
```

**Comment by spawnia** [comment]
That is exactly a use case where calling the resolver is necessary. I am sure this is doable, but we might have to rework the current approach fundamentally.

**Comment by mostafa-rz** [comment]
I don't have any idea about calling the resolver outside the execution cycle. If u could give some examples maybe I could work on it.

**Comment by spawnia** [comment]
> I don't have any idea about calling the resolver outside the execution cycle.

I have never done it either. The most challenging aspect would probably be preparing the `ResolveInfo` object correctly. We would have to look into the execution engine of `webonyx/graphql-php` to replicate its behaviour.

Perhaps there are orthogonal solutions to the problem, maybe a way of letting the underlying resolver run as usual and somehow grabbing its result? I can't really help with a solution here without solving it myself, so if you really need this you will have to delve into the details yourself.

**Comment by mostafa-rz** [comment]
Thanks for the comment, right now I cant invest time on it but I will try to do it in the future.
