### ISSUE TITLE
Relay support for morphToMany directive

### ISSUE THREAD

**Issue by nrueckmann** [nuwave/lighthouse#2153]
**Describe the bug**

Lighthouse (as documented) supports morphToMany relations. Unfortunately, it does not support it when using Relay, because the morphToMany directive does not allow pagination types. 

**Expected behavior/Solution**

Lighthouse should support morphToMany relations in combination with Relay.

**Steps to reproduce**

1. Setup Laravel with a model using morphToMany relations (e.g. spatie/laravel-tags)
2. Try to use it with Relay.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

5.48

**Comment by spawnia** [comment]
This is clearly not a bug.
