### ISSUE TITLE
Add an option in security config to disable field name suggestions

### ISSUE THREAD

**Issue by webard** [nuwave/lighthouse#2163]
Hi,
I found the tool https://graphql.security/ and one of the points is:

> **Field suggestion enabled**
> Description
> If introspection is disabled on your target, Field Suggestion can allow users to still earn information on the GraphQL schema.
> By default, GraphQL backends have a feature for fields and operations suggestions.
> If you try to query a field but you have made a typo, GraphQL will attempt to suggest fields that are similar to the initial attempt.
> 
> Field suggestions is not a vulnerability, but from an attacker's point of view, this feature can be abused to gain more insight into GraphQL's schema, especially when Introspection is not allowed.

I think the field name suggestion option should be off by default when introspection is off, or there should be a separate setting for this.

I can help with PR, but looks like webonyx/graphql-php itself does not have option for disabling field name suggestion.

**Comment by spawnia** [comment]
I think this change should happen in webonyx/graphql-php and be coupled with `\GraphQL\Validator\Rules\DisableIntrospection::DISABLED`. Please open an issue there.
