### ISSUE TITLE
Change in documentation example

### ISSUE THREAD

**Issue by laminekalinko2** [nuwave/lighthouse#2165]
the example on this example might be too sensitive to people of color. thanks
<img width="944" alt="Screen Shot 2022-06-15 at 9 43 46 PM" src="https://user-images.githubusercontent.com/13538880/173973420-462c47f5-65b8-4310-b7e1-e86c832d49f2.png">

**Comment by spawnia** [comment]
I never saw it that way, but I appreciate you providing your perspective.
