### ISSUE TITLE
How to return array in query and mutation

### ISSUE THREAD

**Issue by Passupphp** [nuwave/lighthouse#2166]
Hello,

Please let me know guys, how can i give the images array result on my return.

**Query**
type GetAllProducts{
    id: ID!
    title: String
    description: String
    userId: Int
    featured: Int
    isFree: Boolean
    isBlocked: Boolean
    instantBuy: Boolean
    groupsId: String
}

**Expected Result** 
  "data": {
    "getAllProducts": [
      {
        "id": "10112",
        **"images": [
"https://res.cloudinary.com/deonpjx2g/image/upload/v1655384211/fileStorage/uploads/products/10112/i9gngghwzzmy9gthckxy.png"
        ],**
        "featured": null,
        "userId": 10018,
        "isFree": true,
        "instantBuy": false,
        "isBlocked": false,
        "title": "etgre",
        "description": "ete",
        "groupsId": null
      },

**Comment by Passupphp** [comment]
Hello @spawnia 
 
 Can you please give solution for this ?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
