### ISSUE TITLE
Support for Enum Attribute Casting

### ISSUE THREAD

**Issue by jed-lynch-vectorsolutions** [nuwave/lighthouse#2173]
As much as I can provide, also give perhaps some pointer on where I might be able to address this in my code.

**What problem does this feature proposal attempt to solve?**
https://laravel.com/docs/9.x/eloquent-mutators#enum-casting
Laravel 9 offers enum casting and lighthouse does not support it.

When casting an enum in Laravel's models it will return an enum instance.   Lighthouse then throws an exception.
```
Expected a value of type \"NameOfEnum\" but received: instance of App\\Models\\Enums\\ModelClassEnum",

```

**Which possible solutions should be considered?**
There is lot middleware that I don't understand here, but I would imagine somewhere you could inset conditional logic to fix this.

In my code I am going to create a custom cast class to address this.

**Comment by spawnia** [comment]
This will be supported through https://github.com/webonyx/graphql-php/pull/1058, but that will only be available in the upcoming `webonyx/graphql-php` v15 and Lighthouse v6.

For now you could copy the code from there and integrate it according to https://lighthouse-php.com/master/the-basics/types.html#enum for usage.

**Comment by jelle-bigbridge** [comment]
Should this be possible now? I cannot find the docs on it

**Comment by spawnia** [comment]
https://webonyx.github.io/graphql-php/type-definitions/enums/#construction-from-php-enum

**Comment by jelle-bigbridge** [comment]
> https://webonyx.github.io/graphql-php/type-definitions/enums/#construction-from-php-enum

Ah so graphql-php should be added as a direct dependency to use this?

**Comment by jelle-bigbridge** [comment]
yes but in my application I only have lighthouse as a direct dependency currently. so i will have to add graphql-php so that i will be able to import the PhpEnumType class

**Comment by jelle-bigbridge** [comment]
Never mind I was confused and was using version 5 of lighthouse
