### ISSUE TITLE
Dependency mll-lab/graphql-php-scalars^4 for complex where conditions

### ISSUE THREAD

**Issue by Deyjandi** [nuwave/lighthouse#2174]
**Describe the bug**

I've been following the [documentation](https://lighthouse-php.com/5/eloquent/complex-where-conditions.html#setup) for setting up complex where conditions.

In the setup section, it is specified to install the ```mll-lab/graphql-php-scalars^4``` which is incompatible with ```laravel/framework ^9.2``` due to a conflict in the common dependency ```egulias/email-validator```.

I installed the latest version of ```mll-lab/graphql-php-scalars``` (currently 5.4.0) and so far I faced no issues or errors.

Is there any reason requiring the v4 of ```mll-lab/graphql-php-scalars```? 
Are there any known issues using the **latest** version of ```mll-lab/graphql-php-scalars```?

**Output/Logs**

<details><summary>Click to expand</summary>

```
❯ composer require mll-lab/graphql-php-scalars:^4
./composer.json has been updated
Running composer update mll-lab/graphql-php-scalars
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mll-lab/graphql-php-scalars ^4 -> satisfiable by mll-lab/graphql-php-scalars[v4.0.0, v4.1.0, v4.1.1].
    - laravel/framework[v9.2.0, ..., 9.x-dev] require egulias/email-validator ^3.1 -> satisfiable by egulias/email-validator[3.1.0, ..., 3.x-dev].
    - You can only install one version of a package, so only one of these can be installed: egulias/email-validator[2.0.0, ..., 2.1.x-dev, 3.0.0, ..., 3.x-dev].
    - Conclusion: install egulias/email-validator 2.1.25 (conflict analysis result)
    - Root composer.json requires laravel/framework ^9.2 -> satisfiable by laravel/framework[v9.2.0, ..., 9.x-dev].


Installation failed, reverting ./composer.json to its original content.
```

</details></br>

**Lighthouse Version v5.55.1**

**Comment by spawnia** [comment]
Installing the latest version is fine, thanks for the report.
