### ISSUE TITLE
[Discussion] Require PHP >= 7.1

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#218]
`webonyx/graphql-php` requires PHP 7.1 in the newer version, so if we want to upgrade the library, we have to require it as well. This also means that we would cut cords with Laravel 5.5, since it only requires PHP 7.0

In the process of updating, we could work even more on the correctness and type safety of the code, by adding in nullable/optional types.

Should we wait on this until v3 or do you think it is reasonable to do it as part of a minor release?

**Comment by vladar** [comment]
Minor clarification: `webonyx/graphql-php` requires PHP7.1 in master dev and will require it for0.13.0. Version 0.12.0 still works for PHP5.6 and 7.0

**Comment by spawnia** [comment]
Right, i was confused by this error

    PHP Fatal error:  Declaration of Nuwave\Lighthouse\Schema\Types\Scalars\DateTime::parseLiteral($valueNode) must be compatible with GraphQL\Type\Definition\LeafType::parseLiteral($valueNode, ?array $variables = NULL) in /var/www/src/Schema/Types/Scalars/DateTime.php on line 45

This lead me to believe you were using PHP 7.1 already (as there is a ?array in the arguments), but now that i looked in the source code, i see that it is not actually in there with the question mark. Weird.

**Comment by spawnia** [comment]
Thanks @vladar for clearing this up! I was able to upgrade to `0.12.4` without major issues, just some edge cases and minor technicalities.

Nice to see you moving to 7.1, do you have some kind of Roadmap for v0.13?

**Comment by vladar** [comment]
There is no roadmap, but the following must be done for 0.13:

1. Port all commits from graphql-js from 0.12 till 0.13 (keeping close to their implementation allows us doing this trivial)
2. Fix code style along the way using Doctrine standard for phpcs.
3. Add PHP7.1 type hints everywhere

For this version it should be enough. 0.14 will probably contain more changes targeted for a more static approach.

For any steps above PRs are welcome %) ETA depends a lot on contributions, but we'll release it before autumn anyways.

**Comment by spawnia** [comment]
Switched to webonyx/graphql-php:0.12 in #220

**Comment by spawnia** [comment]
I do not see a strong need for 7.1 right now. Let's hold off until https://github.com/webonyx/graphql-php/releases releases a stable version which requires it. That will be a good reason for us to make the switch and also cut support for Laravel versions `< 5.6`
