### ISSUE TITLE
Validator throws after first invalid field

### ISSUE THREAD

**Issue by nrueckmann** [nuwave/lighthouse#2182]
It seems that using a custom validator the validation stops after hitting the first invalid field. 

My expectation would be that i will get a list of all invalid fields, not just the first one.

Example:

```graphql
type Mutation {
    foobar(input: FoobarInput! @spread): Boolean
}

input FoobarInput @validator {
    foo: String!
    bar: String!
}
```

```php
<?php
namespace App\GraphQL\Validators;

use Nuwave\Lighthouse\Validation\Validator;

final class FoobarInputValidator extends Validator
{
    public function rules(): array
    {
        return [
            'foo' => ['required'],
            'bar' => ['required'],
        ];
    }
}
```

Sending something like 
```
{
  "query": "mutation FoobarMutation($input: FoobarInput!) { foobar(input: $input) }",
  "variables": {"input": {"foo": "", "bar": ""}}
}
```
will answer with just one error. But i would expect an error for each field.

**Comment by spawnia** [comment]
It will be one GraphQL error with multiple validation errors in `extensions.validation` - see https://github.com/nuwave/lighthouse/blob/bd26804b6ca493235f0578e66eb39814ed53f4c2/tests/Integration/Validation/ValidatorDirectiveTest.php#L37-L65

**Comment by nrueckmann** [comment]
Thanks for looking this up. Issue seems to be on my end.
