### ISSUE TITLE
Error when using query_cache feature

### ISSUE THREAD

**Issue by leandrodiogenes** [nuwave/lighthouse#2186]
Hi guys, im with laravel **v8.83.22**, php **v7.4.5** and lighthouse **v5.57.0**.
Project created from laravel/laravel:8.x-dev

Im facing some issues when query_cache is enable on config/lighthouse.php.

Im receiving ERR_CONNECTION_RESET when sending the IntrospectionQuery
![image](https://user-images.githubusercontent.com/2463299/180895219-8105f889-deab-4adc-9046-e7e5d7aaa1dd.png)

I did a brief debug in the code and saw that there is a problem when serializing the item to be saved in the cache.
The php stops the execution after this part of the code:
![image](https://user-images.githubusercontent.com/2463299/180895236-060a5119-9338-48f6-93db-7436809a3cde.png)

The only way to avoid that error is disabling the query_cache.

Any help?

**Comment by k0ka** [comment]
Could you check your cache config? Does it really works?

**Comment by leandrodiogenes** [comment]
Hi @k0ka, my cache seems to work without no errors.

![image](https://user-images.githubusercontent.com/2463299/181000885-da7a8c54-1743-4241-a589-4140881c23a7.png)
![image](https://user-images.githubusercontent.com/2463299/181000987-b441828d-5f80-45be-9d46-be4f0914ebb7.png)

**Comment by leandrodiogenes** [comment]
The execution stops when serialize function is called.
![image](https://user-images.githubusercontent.com/2463299/181003163-d1e8c497-28df-4e60-bab3-1be9179982d4.png)

**Comment by leandrodiogenes** [comment]
Seems to be something related only with introspection query of graphql-playground.
I dont know why.

here is the query.
```graphql
# Write your query or mutation here
query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    subscriptionType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}```

**Comment by k0ka** [comment]
The introspection query looks ok. Your PHP version is quite old. Could you try to update it to the latest 7.4.29? Hanging on the `serialize()` looks pretty weird. 

Could you also check the real value of the `$value`? It should be AST - a tree-like structure without any loops.

**Comment by leandrodiogenes** [comment]
I just updated to 7.4.30 and still the same.

$value its on my first print. 
Here is another one.
![image](https://user-images.githubusercontent.com/2463299/181015999-8275600b-24c2-45fd-b9f0-9030e3e2616d.png)
![image](https://user-images.githubusercontent.com/2463299/181016112-35c6b326-db16-4433-8ba4-b70cd1a45c85.png)

**Comment by leandrodiogenes** [comment]
Works if i change the TypeRef on query to:
```graphql
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    }
  }
}

**Comment by leandrodiogenes** [comment]
I tried on another server and seems to work, maybe the problem its one of my servers.
