### ISSUE TITLE
`CONNECTION` pagination broken without `pageInfo`

### ISSUE THREAD

**Issue by pyrou** [nuwave/lighthouse#2189]
**Describe the bug**

CONNECTION pagination offset doesn't work as expected if no pageInfo is requested. Attribute `after` looks not being used, and page 1 is returned when asking for page 2

I added 2 similar unit tests is [this commit](https://github.com/pyrou/lighthouse/commit/c1609c4ecfe1a736b6a1dd328d3c273707e9a8bb), one with pageInfo, one without. Second test is failing, items for page one is returned.

**Lighthouse Version**

This issue introduced with PR #2170 (Lighthouse 5.55)

**Comment by spawnia** [comment]
Can you add a pull request with the failing test cases?

**Comment by stayallive** [comment]
I'm already working on it @spawnia, will be fixed shortly ;)
