### ISSUE TITLE
[FEATURE] Easy/optional integration for a GraphQL IDE

### ISSUE THREAD

**Issue by mfn** [nuwave/lighthouse#219]
I think this package could massively benefit from an optional/easy integration of a GraphQL Web IDE

There are a few contenders out there (please expand list):
- GraphiQL => https://github.com/graphql/graphiql
- GraphQL Playground => https://github.com/prismagraphql/graphql-playground

Any IDE is better then none.

The benefits:
- easy to use for ever developer on the same project
  They can but don't need to set up tools on their own.
- integrates well with special authorization cases (middlewares)
  External tools (e.g. GraphQL Playground as Desktop application) although allowing to send custom headers add a layer of friction if your graphql endpoint has special considerations (e.g. session based authentication) and it's much easier to simply have the local IDE configured with the correct middleware working out of the box

**Comment by spawnia** [comment]
https://github.com/mll-lab/laravel-graphql-playground

We should document how to add this in, since it is such a common requirement.

Is there anything you would add, any features/configuration you are missing? Feel free to open an issue in the project over there.

**Comment by mfn** [comment]
> We should document how to add this in, since it is such a common requirement.

:-( I honestly went through the issues but wasn't aware of this Laravel integration.

Makes of course totally sense to have these things separate 👍 

Opened an issue at https://github.com/nuwave/lighthouse-docs/issues/19 (didn't know their was a docs repo until now 😄 )

thanks!
