### ISSUE TITLE
Inconsistent results @orderBy directive

### ISSUE THREAD

**Issue by joelacin** [nuwave/lighthouse#2192]
**Describe the bug**
Hi!
Not sure if it’s related to laravel or lighthouse.
When using `@orderBy` directive the returned results aren’t the same as if the query was done with a database client (for ex. heidiSQL). The biggest problem is that they change per request leading to repeated results in different pages. We think, this happens because query is ordered by `created_at` column and there are multiple records with the same value. 

**Expected behavior/Solution**
The ordered results should be equal within the results from the database client.

**Steps to reproduce**

1. We defined this query in our schema
```
extend type Query {
    reviews(
        id: ID @eq
        notice_request: ID @whereHasConditions(relation:"noticeRequest" columns:["notice_id"])
        paramenter_type: ID @whereHasConditions(relation:"parameterReviews" columns:["parameter_type_id"])
        orderBy: _ @orderBy(
            columns: ["created_at"]
            relations: [
                {
                    relation: "parameterReviews", columns: ["evaluation"],
                }
            ]
        )
    ): [Review!] @paginate
}
```
2. We queried via lighthouse
```
query {
    reviews(
      paramenter_type: { column: PARAMETER_TYPE_ID, operator: EQ, value: 109 }
      notice_request: { column: NOTICE_ID, operator: EQ, value: 36 }
      orderBy: { column:CREATED_AT, order: DESC }
    ) {
      paginatorInfo {
        lastPage
      }
      data {
        id
        created_at
      }
    }
  }
```
4. We grabbed the resulted query build by lighthouse/laravel via clockwork plugin and compared the results 
```
SELECT
	*
FROM
	`reviews`
WHERE
	(EXISTS (
	SELECT
		*
	FROM
		`notice_request`
	WHERE
		`reviews`.`id` = `notice_request`.`review_id`
		and `notice_request`.`notice_id` = 36))
	and (EXISTS (
	SELECT
		*
	FROM
		`parameter_review`
	WHERE
		`reviews`.`id` = `parameter_review`.`review_id`
		and `parameter_review`.`parameter_type_id` = 109))
ORDER BY
	`created_at` DESC
```

**Output/Logs**
a) output log from lighthouse. They change by request after id 101
```
{
  "data": {
    "reviews": {
      "paginatorInfo": {
        "lastPage": 2
      },
      "data": [
        {
          "id": "103",
          "created_at": "2022-08-03"
        },
        {
          "id": "102",
          "created_at": "2022-08-02"
        },
        {
          "id": "101",
          "created_at": "2022-07-27"
        },
        {
          "id": "93",
          "created_at": "2022-06-27"
        },
        {
          "id": "95",
          "created_at": "2022-06-27"
        },
        {
          "id": "97",
          "created_at": "2022-06-27"
        },
        {
          "id": "99",
          "created_at": "2022-06-27"
        },
        {
          "id": "12",
          "created_at": "2022-06-27"
        },
        {
          "id": "91",
          "created_at": "2022-06-27"
        },
        {
          "id": "94",
          "created_at": "2022-06-27"
        }
      ]
    }
  }
}
```
a) output log from database client (HeidiSQL). They are consistent on all requests.
```
{
"SELECT\r\n\tid,\r\n\tcreated_at\r\nFROM\r\n\t`reviews`\r\nWHERE\r\n\t(EXISTS (\r\n\tSELECT\r\n\t\t*\r\n\tFROM\r\n\t\t`notice_request`\r\n\tWHERE\r\n\t\t`reviews`.`id` = `notice_request`.`review_id`\r\n\t\tand `notice_request`.`notice_id` = 36))\r\n\tand (EXISTS (\r\n\tSELECT\r\n\t\t*\r\n\tFROM\r\n\t\t`parameter_review`\r\n\tWHERE\r\n\t\t`reviews`.`id` = `parameter_review`.`review_id`\r\n\t\tand `parameter_review`.`parameter_type_id` = 109))\r\nORDER BY\r\n\t`created_at` DESC\r\nLIMIT 10 OFFSET 0:": [
	{
		"id" : 104,
		"created_at" : "2022-08-04T08:45:37.000Z"
	},
	{
		"id" : 102,
		"created_at" : "2022-08-02T13:59:52.000Z"
	},
	{
		"id" : 101,
		"created_at" : "2022-07-27T15:31:57.000Z"
	},
	{
		"id" : 12,
		"created_at" : "2022-06-27T08:17:13.000Z"
	},
	{
		"id" : 91,
		"created_at" : "2022-06-27T08:17:13.000Z"
	},
	{
		"id" : 92,
		"created_at" : "2022-06-27T08:17:13.000Z"
	},
	{
		"id" : 93,
		"created_at" : "2022-06-27T08:17:13.000Z"
	},
	{
		"id" : 94,
		"created_at" : "2022-06-27T08:17:13.000Z"
	},
	{
		"id" : 95,
		"created_at" : "2022-06-27T08:17:13.000Z"
	},
	{
		"id" : 96,
		"created_at" : "2022-06-27T08:17:13.000Z"
	}
]}
```

**Lighthouse Version**
5.57.3

**Comment by spawnia** [comment]
Perhaps HeidiSQL does some client side ordering. Without being more specific, you can not expect a consistent order between values that are the same, see https://dba.stackexchange.com/a/6053

**Comment by joelacin** [comment]
Hi, thanks for your response.
I also tested with dbeaver and the results are consistent.
Based on the link you provided it should be consistent when using `order by` clause

See this comment on the accepted answer from the link you provided:
_In the SQL world, order is not an inherent property of a set of data. Thus, you get no guarantees from your RDBMS that your data will come back in a certain order -- or even in a consistent order -- unless you query your data with an ORDER BY clause._

**Comment by spawnia** [comment]
You only order explicitly by `created_at`, which works. Any order beyond that is not guaranteed. Add an additional `order by` clause if you care about the order within the same day.

**Comment by joelacin** [comment]
Maybe i'm not being clearly. Theres a strange random behaviour. 
please see this video  (pay attention to record after id 101 ) - https://watch.screencastify.com/v/Wf4F84oVfN25w24HVZil

**Comment by spawnia** [comment]
This is expected behaviour.

I think you are reading this part wrong:

> unless you query your data with an ORDER BY clause.

Using `order by` does not guarantee that the order of the returned data will always be the same, it only guarantees the order of the fields you mention in the clause. If you need the order of other fields to be consistent, you must mention them in `order by`.

**Comment by joelacin** [comment]
Thanks again for your response.
This is a situation that i never experienced, and not being replicated by a client database software made me think is related to lighthouse/laravel.
I will add an order by id, it will make the results consistent.
Thank you.

**Comment by joelacin** [comment]
So, I decided to make the query via CLI  - https://mariadb.com/kb/en/mariadb-command-line-client/
The results were always consistent/same. 
I eventually solved the problem by adding an order by id, but this  suggests that there is some kind on order behaviour after the results are retrieved. 
I'm not saying I’m right but the only difference is with Laravel/lighhouse. HeidiSQL, DBeaver an CLI results are always consistent

**Comment by leandrodiogenes** [comment]
Hi @joelacin, 2 questions.

1. If you have you tried using eloquent, can you share the results?
2. Are you casting that field from timestamp to date format Y-m-d? (If yes, try without any cast)

**Comment by leandrodiogenes** [comment]
Just do something like and see the results.
```php
Review::orderBy('created_at')->get();
```

**Comment by joelacin** [comment]
Hi @leandrodiogenes 
You are correct. I was casting that field with the built in Date scalar. Removing it eliminated the randomess results.

**Comment by joelacin** [comment]
Hi @leandrodiogenes 
I'm casting the results with the built in `Date` scalar. Taking your suggestion of removing that cast at first glance seemed to eliminate the problem, but I eventually got the randomness behaviour.

Regarding your suggested query, `Review::orderBy('created_at')->get();` I made a resolver and didn’t encounter any problem. The results were consistent. But for the troubled query I’m not using any custom resolver.

**Comment by leandrodiogenes** [comment]
So, after change the scalar to DateTime, the results keeps the sames as before?

**Comment by joelacin** [comment]
@leandrodiogenes 
Yes, I tried Date, DateTime and String Scalars and the results were the same as before.
And we don’t have any caster for that field on the model.

**Comment by leandrodiogenes** [comment]
Yea, i cant replicate that issue.
Can you create an repository to replicate that problem?
I would be happy to try to help.
