### ISSUE TITLE
Built-in types are not found when directive is used

### ISSUE THREAD

**Issue by otzy** [nuwave/lighthouse#2194]
**Describe the bug**
If a node return type is one of built-in scalars, eg. String and a directive `@can` is used, exception is thrown "Type 'String' on 'nodeName' can not be found in the schema.'"

**Expected behavior/Solution**
Built-in type should not cause an exception

**Steps to reproduce**

I use a schema with permission check that looks like this:
```
getSomeString(param: Int!): String
@can (
     ability: "PERMISSION_NAME"
     model: "MyModel"
)
```
The model itself is irrelevant in my case, but since ability is always checked against model, it's necessary to put model parameter to the directive. I'm ok with that and this worked fine with the lighthouse version 5.57.0

Today I've run composer update and got a version 5.57.4.  
Now I'm getting error:

```
"debugMessage": "Type 'String' on 'getSomeString' can not be found in the schema.'",
```

I think the problem is in the new version of the function BaseDirective::getModelClass()  
Before the update it did not try to find the type in the schema if the model was provided in the directive parameter.

Also in general I think that if a built-in type is used, there should be no attempt to find this type in the schema AST

**Trace**

<details><summary>Click to expand</summary>

```
        {
          "file": "\/var\/www\/vendor\/nuwave\/lighthouse\/src\/Schema\/AST\/ASTHelper.php",
          "line": 405,
          "call": "Nuwave\\Lighthouse\\Schema\\AST\\ASTHelper::underlyingType(instance of GraphQL\\Language\\AST\\FieldDefinitionNode)"
        },
        {
          "file": "\/var\/www\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/BaseDirective.php",
          "line": 151,
          "call": "Nuwave\\Lighthouse\\Schema\\AST\\ASTHelper::modelName(instance of GraphQL\\Language\\AST\\FieldDefinitionNode)"
        },
        {
          "file": "\/var\/www\/vendor\/nuwave\/lighthouse\/src\/Auth\/CanDirective.php",
          "line": 221,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\BaseDirective::getModelClass()"
        },
        {
          "file": "\/var\/www\/vendor\/nuwave\/lighthouse\/src\/Auth\/CanDirective.php",
          "line": 147,
          "call": "Nuwave\\Lighthouse\\Auth\\CanDirective::modelsToCheck(instance of Nuwave\\Lighthouse\\Execution\\Arguments\\ArgumentSet, array(1))"
        },
```

</details></br>

**Lighthouse Version**
5.57.4

**Comment by otzy** [comment]
this seems to be the commit that broke stuff: 
https://github.com/nuwave/lighthouse/pull/2193/files#diff-1af7ae1274e698bd7c7c5736aaa00507101234720574ef5debd41ebadd8e658cR151

**Comment by spawnia** [comment]
Thanks for the detailed description. Can you create a pull request with a failing test case?

**Comment by otzy** [comment]
voila https://github.com/nuwave/lighthouse/pull/2195

**Comment by otzy** [comment]
thanks for fixing. But what's the point to try searching for a model by type name and pass it as a default to the directiveArgValue()? 
If the model is already passed as a parameter there is no need to define it by type. Only if the model class is missing in a directive,  the type should be used.

On other hand, it is very unlikely that a built-in type can be mapped to a model.

Honestly previous version seems more elegant to me
```
$model = $this->directiveArgValue($argumentName) ?? ASTHelper::modelName($this->definitionNode);
```

**Comment by spawnia** [comment]
See https://github.com/nuwave/lighthouse/pull/2193#discussion_r937889822 for why we always use `$default` over `??` with `directiveArgValue()`.

**Comment by spawnia** [comment]
Might be worth doing for the next major version of Lighthouse, not having to evaluate the expression that forms the default is a nice performance benefit indeed - although pretty small.
