### ISSUE TITLE
Validator directive is getting executed before auth

### ISSUE THREAD

**Issue by ayech0x2** [nuwave/lighthouse#2203]
Here my schema. 

`
createOrder(reference: String products:
  [OrderProduct]! client_id: ID ): Order 
@guard(with: ["user"]) 
@validator(class: "CreateOrderValidator") 
@field(resolver: "OrderMutator@createOrder")
`

The Guard directive is supposed to be a middleware, isn't it? It must therefore be executed before validation!

Thanks for the package by the way.

**Comment by spawnia** [comment]
Duplicate of https://github.com/nuwave/lighthouse/issues/1780
