### ISSUE TITLE
`@can` directive throws error for basic gate ability

### ISSUE THREAD

**Issue by 6XGate** [nuwave/lighthouse#2212]
**Describe the bug**

When running a query or mutation that does not return an Eloquent model with a basic gate ability for the `@can` directive, it throws a `DefinitionException` stating `Failed to find class ${graphQlType} in namespaces [...${modelNamspaces}] for directive @can.`.

**Expected behavior/Solution**

It should not fail without a model, but rather fallback to using any gates defined with `Gate::define` or similar methods.

**Steps to reproduce**

1. Create a mutation or query using a custom resolver. That resolver should not return an Eloquent model.
2. Define a basic gate in `app/Providers/AuthServiceProvider.php` using `Gate::define`. For example, it could be called `read`.
3. Add a `@can(ability: 'read')` directive to the operation in step 1.
4. Call the operation from a client.

**Output/Logs**

<details><summary>Click to expand</summary>

Entry truncated and tagged for readability.
```
[${timestamp}] local.ERROR: FFailed to find class ${graphQlType} in namespaces [...${modelNamspaces}] for directive @can. {...${context}, "exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): ${message} at /usr/share/nginx/html/vendor/nuwave/lighthouse/src/Schema/Directives/BaseDirective.php:197)
[stacktrace]
...${stacktrace}
```

</details></br>

**Lighthouse Version**

5.61.0

**Comment by spawnia** [comment]
`@can` deals with policies, not gates. Feel free to reformulate this issue as a feature request, I am open to pull requests.
