### ISSUE TITLE
Overwrite data in relationship when using @field custom resolver

### ISSUE THREAD

**Issue by fin-finaud** [nuwave/lighthouse#2213]
Modified data in relationship is not returned by the Query.

Ex:
extend type Query {
    quote(id: ID): Quote 
    @field(resolver: "FetchById") 
}

FetchById:
$quote = Quote::with('rows.children')->where('id', $payload->id)->first();

// The quotes has rows and I need to modify / parse them. I'm currently trying to do this:
$formatted_rows = $quote->rows->reject(function ($row)
{
    return $row->group_id !== null;
});

$quote->setRelation('rows', $formatted_rows);

Diyng the data right after works. I can see the data correctly formatted and the rows are as expected:
die(print_r($quote->rows->toArray()));

but if I return the quote, I only get the original data as if Lighthouse redoes the query before returning the data.

**Steps to reproduce**

1. Use a @field custom resolver
2. Query an db entry with a hasMany relation
3. Modify the data in the relation, die to see the expected result.
4. Return the entry to a client (Example Insomnia or Postman) and inspect the sent data, the modifications are not there and you will only see the original data.

**Comment by spawnia** [comment]
I am assuming you defined the `@hasMany` directive ont `Quote.rows`. It performs eager-loading on the relation, thus discards any previously loaded data.

Consider that there might be multiple ways to resolve a `Quote` in the graph described by your schema. As a client, I would expect the values for its fields to return a consistent result, no matter through which path I got to it. Thus, I suggest to add a filter or scope directly to `Quote.rows`. That also clearly splits the responsibilities, the root field is only responsible for resolving a `Quote`, the resolvers for `Quote` determine the values of its fields.

**Comment by fin-finaud** [comment]
@spawnia This is exactly what I needed. I thought I had to specify the @hasMany directive on quote.rows in the schema to make it work but I see that I can simply remove it and I get exactly what I want. Awesome! :-D Thanks for the quick reply!
