### ISSUE TITLE
Complex where conditions with nested mongodb documents

### ISSUE THREAD

**Issue by bladerik** [nuwave/lighthouse#2216]
**Describe the bug**
I'm using laravel-mongodb with lighthouse, and it is working great so far. One issue I encountered is when using @whereConditions with a nested object column.

If you define a column containing a dot, the GeneratesColumnsEnum trait generates an enum with a dot in its name and crashes with Syntax Error: Cannot parse the unexpected character \".\".

**Expected behavior/Solution**
GeneratesColumnsEnum trait should create allowed columns enum even if the column contains a dot to support filtering in nested MongoDB documents.

Simple fix is to replace `Str::snake($columnName)` with `Str::snake(str_replace(".", "__", $columnName))` in GeneratesColumnsEnum trait (line 87)

But this might produce conflicts if column names contain multiple underscores. 

**Steps to reproduce**
Simple reproduction steps don't even require MongoDB installation. 
Just add whereConditions to any query with column that contains dot, for example:
where: _ @whereConditions(columns: ["some.nested.property"])

To investigate with mongo:
1. Enable complex query as described here https://lighthouse-php.com/5/eloquent/complex-where-conditions.html#setup
2. Install laravel-mongodb https://github.com/jenssegers/laravel-mongodb
3. Define model MongoDB model
4. Add nested document to MongoDB collection
5. define type in schema as with classic eloquent model
6. create a new query for that model and add whereConditions to nested property, for example: 
where: _ @whereConditions(columns: ["some.nested.property"])

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
{
  "errors": [
    {
      "message": "Syntax Error: Cannot parse the unexpected character \".\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 4,
          "column": 10
        }
      ]
    }
  ]
}
```

</details></br>

**Lighthouse Version**
5.61

PS: This is my first report. Please excuse any shortcomings and thank you for your great work!

**Comment by spawnia** [comment]
I think this problem will occur with any column name that is not a valid [GraphQL name](https://spec.graphql.org/draft/#sec-Names). The GraphQL specification is very restrictive here, basically every database engine allows more - for example [MariaDB](https://mariadb.com/kb/en/identifier-names) allows `$` and places no restrictions on leading numerals. When quoted, the range for allowed column names is even further.

Any solution we adopt for this will influence the schema offered to clients, thus I think we should consider carefully and try to implement something that will hold up for most if not all use cases. I don't see a way to avoid naming conflicts, but given the relatively small namespace we deal with (the enum of column names for a single field), I foresee little actual problems with that.

How about we use Laravel's `Str::slug()` functionality or a modified/optimized version thereof? It should eliminate any extra special characters and just replace them with `_` and uppercase the string. Would you like to try and contribute a solution through a pull request?

**Comment by bladerik** [comment]
Sure, that might work. I'll do my best to contribute later today :)
