### ISSUE TITLE
`directiveNode` within a custom directive is null when used in `field_middleware` as well as in a schema.

### ISSUE THREAD

**Issue by madrussa** [nuwave/lighthouse#2217]
When you have a custom directive such as a field sanitiser directive with optional values, as well as having the directive added to `field_middleware` using the default values, the AST from the graphql definition is ignored including any arguments. This means that the `directiveNode` property on the field directive is null and you can't get access to any optional argument override. This results in an ErrorException being thrown as we cannot get the arguments for a directive when its node isn't populated.

### Expected
Able to access directive argument values when directive is used in a schema as well as in field_middleware. This should read the schema and prefer the schema definition of a field directive over those declared in the middleware.

### Actual
ErrorException thrown.

### Steps to recreate

Given we are using a custom trim directive with an option to change the trim characters:
```graphql
directive @customTrim(
    """
    Used to change what characters are trimmed from the value
    """
    characters: String
) on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION | FIELD_DEFINITION
```

and by default we want to use this everywhere with the defaults:
```php
[
    'field_middleware' => [
        \App\GraphQL\Schema\Directives\CustomTrimDirective::class,
        \Nuwave\Lighthouse\Schema\Directives\ConvertEmptyStringsToNullDirective::class,
        \Nuwave\Lighthouse\Schema\Directives\SanitizeDirective::class,
        \Nuwave\Lighthouse\Validation\ValidateDirective::class,
        \Nuwave\Lighthouse\Schema\Directives\TransformArgsDirective::class,
        \Nuwave\Lighthouse\Schema\Directives\SpreadDirective::class,
        \Nuwave\Lighthouse\Schema\Directives\RenameArgsDirective::class,
        \Nuwave\Lighthouse\Schema\Directives\DropArgsDirective::class,
    ]
]
```

Using the custom directive with the optional argument populated:
```graphql
extend type Query {
    search(
        """ Trim quotes but keep whitespace, whitespace is important here """
        query: String! @customTrim(characters: "'\"")
   ): SearchResult!
}
```

Attempt to get the directive argument value within our custom directive:
```php
public function handleField(FieldValue $fieldValue, Closure $next): FieldValue
{
    $characters = $this->directiveArgValue('characters'); // Exception
}
```

This results in an exception
```
exception: "ErrorException"
file: "/my-app/vendor/nuwave/lighthouse/src/Schema/Directives/BaseDirective.php"
line: 92
message: "Trying to get property 'arguments' of non-object"
```

This is because the node isn't loaded for directives that are added to the `field_middleware`.

### Lighthouse Version
`v5.31.2` (I didn't see any fix mentioned in the change log) 

### Workaround:

The current work around is to look through the arguments from the resolve info:
```php
function getCharacters(Argument $argument): ?string
{    
    // When this directive is not middleware, it will have the value defined and directiveNode should not be null
    if ($this->directiveNode) {
        return $this->directiveArgValue('characters');
    }

    // If the directiveNode was null then it means this is running as middleware and we need to lookup
    // the arguments to find the given characters.
    foreach ($argument->directives as $directive) {
        if ($directive instanceof self) {
            return $directive->directiveArgValue('characters');
        }
    }

    return null;
}
```
However this feels clunky and could be prone to error.

**Comment by spawnia** [comment]
Directives registered in `field_middleware` will never have arguments. This piece of code in your example only makes sense if the directive is actually defined in the schema:

```php
public function handleField(FieldValue $fieldValue, Closure $next): FieldValue
{
    $characters = $this->directiveArgValue('characters'); // Exception
}
```

Look at the actual implementation of `@trim` - it actually works as a global field directive, but applies directives defined on arguments - that is where you will need to read the argument value from.

There are a couple of fixes/improvements to be made here, but they are orthogonal to your problem. Your workaround actually looks like a proper solution to me.
