### ISSUE TITLE
`@can`: Properly support `denyAsNotFound` or equivalent Auth responses from Policies and Gates

### ISSUE THREAD

**Issue by 6XGate** [nuwave/lighthouse#2225]
**What problem does this feature proposal attempt to solve?**

This feature would be required to prevent model existence leakage security issues from the `@can` directive.

Currently, if a field is marked with `@can(resolve: true)`, the policy is not checked for `null` results from resolvers. This can actually be fine, but when they are checked for non-null results, Lighthouse has now leaked the models existence. It doesn't matter if the policy responded with a `Response::denyAsNotFound()`.

It is also likely `@can(query)` and `@can(find)` suffer from this issue as well.

**Which possible solutions should be considered?**

If a policy is checked against any model instance, the result should be replaced with `null` if the result of `Response::denyAsNotFound()` or the like is returned from the policy. It could also be appropriate to filter out any items from resolvers that return collections of items when this response is received for any given item.

The only work-around right now is to replace the `@can` directive with a local implementation aware of this type of response, but the complexity of the `@can` directive makes that an issue. Especially when upgrading to new version of Lighthouse and trying to keep things in sync with the root.

See this article for a discussion on this security issue:
https://larasec.substack.com/p/security-tip-leaking-model-existence

**Comment by spawnia** [comment]
Sounds reasonable, I am open for pull requests.

**Comment by spawnia** [comment]
@6XGate could you take a look at https://github.com/nuwave/lighthouse/pull/2220? I feel like it is trying to solve a related issue.

**Comment by 6XGate** [comment]
I might tackle that soon

**Comment by 6XGate** [comment]
> @6XGate could you take a look at #2220? I feel like it is trying to solve a related issue.
That seems more related to resolvers that throw model not found. Policies still use an Auth\Response.

I might tackle a pull request soon.
