### ISSUE TITLE
How can I manipulate the query builder with a field directive?

### ISSUE THREAD

**Issue by madforfame** [nuwave/lighthouse#2226]
I am currently trying to add a field to my Variant type that, if added to the query, will cause the query to use a cross join, multiplying the results. I also have a lot of other, very weird and specific fields for very specific uses that I need to implement, and the best way I figured would be to create a custom directive that can access to and manipulate the query builder.

From reading the documentation (which is pretty lackluster for custom directives honestly), I figured that the custom directive should implement the `FieldBuilderDirective` interface, and therefore have `handleFieldBuilder` function. However, I the execution simply doesn't go through the function, and I can't figure out why.

Here is my schema:
```php
extend type Query {
    Variants: [Variant!]! @paginate(defaultCount: 50, scopes: ["company"]) @guard @softDeletes
}

type Variant {
    id: ID!
    crossLocationId: Int @variantCrossLocation(argument:"a")
}
```

And here is my directive:
```php
<?php

namespace Nuwave\Lighthouse\Schema\Directives;

use Closure;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Language\AST\FieldDefinitionNode;
use Nuwave\Lighthouse\Schema\AST\DocumentAST;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use GraphQL\Language\AST\ObjectTypeDefinitionNode;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use Nuwave\Lighthouse\Support\Contracts\FieldMiddleware;
use Nuwave\Lighthouse\Support\Contracts\FieldManipulator;
use Nuwave\Lighthouse\Support\Contracts\ArgBuilderDirective;
use Nuwave\Lighthouse\Support\Contracts\FieldBuilderDirective;

class VariantCrossLocationDirective extends BaseDirective implements
    FieldBuilderDirective
    // ArgBuilderDirective
    // FieldManipulator,
    // FieldMiddleware
    // \Nuwave\Lighthouse\Support\Contracts\ArgBuilderDirective
{
    use RelationDirectiveHelpers;

    public static function definition(): string
    {
        return /* @lang GraphQL */ <<<'GRAPHQL'
directive @variantCrossLocation(
  argument: String
)repeatable on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
GRAPHQL;
    }

    public function handleField(FieldValue $fieldValue, Closure $next)
    {
        dump('a');
        $resolver = $fieldValue->getResolver();
        return $next(
            $fieldValue->setResolver(function (
                $root,
                array $args,
                GraphQLContext $context,
                ResolveInfo $resolveInfo
            ) use ($resolver) {
                $result = $resolver($root, $args, $context, $resolveInfo);
                return $result;
            })
        );
    }

    public function handleFieldBuilder(object $builder): object
    {
        dump('b');
        return $builder;
    }

    public function handleBuilder(object $builder): object
    {
        dump('c');
        return $builder;
    }

    public function manipulateFieldDefinition(DocumentAST &$documentAST, FieldDefinitionNode &$fieldDefinition, ObjectTypeDefinitionNode &$parentType)
    {
        dump('d');
    }
}
```

As you can see, there are more functions than the the `handleFieldBuilder`, because I tried implementing other interfaces, in hopes of making them work. Implementing the `FieldMiddleware` for exemple will trigger the `handleField`, but it doesn't have the informations or ressources I want in it. But `FieldBuilderDirective` doesn't trigger any of them, and I have no idea why.

Here is my graphQL query:
```graphql
{
  Variants{
    data{
      id
      crossLocationId
    }
  }
}
```

**Comment by spawnia** [comment]
I extended the docs for `FieldBuilderDirective` in https://github.com/nuwave/lighthouse/commit/b989b369c094a1c6a4285855aa53f03f037a24fb.

As it pertains to your example, `@variantCrossLocation` will only affect a query builder used to resolve `crossLocationId` specifically - not the query builder of the parent field `Variants`.
