### ISSUE TITLE
Define security options through the config

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#223]
**Is your feature request related to a problem? Please describe.**

I find the current way of defining security directives both confusing and impractical.

**Describe the solution you'd like**

The security configuration should be done via the config file in the future.
While we should generally aim to keep schema-first, i would not be dogmatic about it.

Adding in this config via the config file seems more logical to me, since the security config is global. It will also allow to control security options via env variables, which is very desirable, e.g. disable introspection in prod.

**Comment by olivernybroe** [comment]
Agreed. However I think having the option to do it with a directive also is not a bad idea. 
So a directive definition overrides a config definition.

**Comment by spawnia** [comment]
Do not agree with that. It is easier if there is only one way to do things. If anything, the dynamic PHP config should win over the static schema definition.

**Comment by olivernybroe** [comment]
Hmm then I would prefer to just remove the directive completely
