### ISSUE TITLE
Major Bug? @can executes the mutation before completing authorization.

### ISSUE THREAD

**Issue by chrispage1** [nuwave/lighthouse#2237]
**Describe the bug**

On mutations, when I attempt to apply multiple directives, e.g. `@can(ability: "update", resolved: true) @update`, the @can directive actually calls the `@update` directive and executes the mutation. My example mutation is below:

```graphql
type Mutation {
    updateDevice(
        id: ID!
        input: InputDevice!
    ): Device @can(ability: "update", resolved: true) @update
}
```

Looking into this I can see that it is the `resolved` flag triggering the issue - but I need the model to be resolved to perform our permissions checks. On `Nuwave\Lighthouse\Auth\CanDirective`, line 131 is executing the "previous resolver" which in this instance is the `UpdateDirective`. 

This to me seems like a pretty serious security flaw allowing execution logic to occur before authorization - or am I just misunderstanding the usage of @can or directives or mutations altogether?

**Lighthouse Version**: 5.66.0

**Comment by spawnia** [comment]
The docs clearly state this is the case: https://github.com/nuwave/lighthouse/blob/5127c9475c0ad0c1b2e11ee21935abf45f7f59c4/src/Auth/CanDirective.php#L57-L63

**Comment by chrispage1** [comment]
@spawnia ah right - that makes sense, thank you. Is there an alternative method you suggest to enforce permission or would I need to write a custom piece of middleware?

Thanks.

**Comment by spawnia** [comment]
Use `query` or `find`.

**Comment by chrispage1** [comment]
@spawnia thanks, but this resolves the field but doesn't allow me to enforce any kind of permission checks?

**Comment by spawnia** [comment]
I mean the arguments `query` or `find` for `@can`. Please read its documentation fully.

**Comment by chrispage1** [comment]
@spawnia thanks so much that has pointed me in the right direction. Using `@can(ability: "update", find: "id")`

Appreciate your help.
