### ISSUE TITLE
bcrypt helper function not available in Lumen

### ISSUE THREAD

**Issue by tcetin** [nuwave/lighthouse#224]
I am getting this error when try to create a user in grapiql at Lumen.

```
Call to undefined function Nuwave\\Lighthouse\\Schema\\Directives\\Args\\bcrypt()
```

It seems it doesn't resolve ```@bcrypt``` directive in the mutation.

```
type Mutation {
  createUser(name: String!, password: String! @bcrypt): User
    @field(resolver: "App\\GraphQL\\Mutations\\UserMutator@create")
}
```

Please help.

Thanks

**Comment by chrissm79** [comment]
@tcetin This is interesting... if you could fill out the bug report and list the version of PHP your using (along w/ the version of Lighthouse) we should be better equipped to debug. I'm using the `@brcypt` directive in my own project and it works as expected (along w/ the test that @spawnia created), so I'm currently assuming it's some sort of environment issue.

**Comment by spawnia** [comment]
Closing this. As i said, https://github.com/albertcht/lumen-helpers is the solution for this.
