### ISSUE TITLE
Wrong Cache invalidation when using tagged-cache

### ISSUE THREAD

**Issue by LrMiLoef** [nuwave/lighthouse#2240]
**Describe the bug**
I have enabled caching in one of my queries. This works so far also without any problems. But if I now want to clear the cache after a mutation based on the type, this unfortunately does not work. On running the query again, i'll receive the old, cached value.

**Expected behavior/Solution**
After clearing the cache by type, the next run of an query should return the fresh value instead of the old cached value.

After some debugging i think i found the issue in the class `CacheKeyAndTagGenerator`. The method `parentTag` produces one tailing `:` to many then `id` is set to `null`.

**Steps to reproduce**

1. Run query `visitorZones: [VisitorZone] @cache`
2. Run mutation `updateVisitorZone(input: UpdateVisitorZoneInput!): Boolean @clearCache(type: "Query::visitorZones")`
3. Run query `visitorZones: [VisitorZone] @cache` again. It will return the old cached value.

**Output/Logs**

**Lighthouse Version**
V 5.67.0

**Comment by spawnia** [comment]
> @clearCache(type: "Query::visitorZones")

This is a complete misuse of this directive, it should be `@clearCache(type: "Query", field: "visitorZones")`.

**Comment by LrMiLoef** [comment]
Ok, i see.. thank you.

**Comment by esistgut** [comment]
After reading the documentation I was trying to use the directive like this: `@clearCache(type: "VisitorZone")` but it was not working. The way described here is working `@clearCache(type: "Query", field: "visitorZones")`, am I missing something?
