### ISSUE TITLE
[Not Bug] Breaking changes in next version of webonyx/graphql-php

### ISSUE THREAD

**Issue by eslym** [nuwave/lighthouse#2241]
Please take note the next version of `webonyx/graphql-php` will have some breaking changes which making it not compatible with current lighthouse, quite lot of work might need to do for if what to update the dependencies

The most obvious breaking change is `GraphQL\Type\Definition\FieldArgument` has been renamed to `GraphQL\Type\Definition\Argument`
https://github.com/webonyx/graphql-php/releases/tag/v15.0.0-beta.1

**Comment by spawnia** [comment]
Thank you. I am aware, since I made that change myself and am steadily maintaining https://github.com/nuwave/lighthouse/pull/1898 😉
