### ISSUE TITLE
Null results in deep MorphTo

### ISSUE THREAD

**Issue by McManning** [nuwave/lighthouse#2246]
**Describe the bug**

I'm integrating Lighthouse with [Laravel Auditing](https://laravel-auditing.com/docs/13.0/introduction) and running into an issue with my queries not returning morphTo user data. 

I have a Submission model with a MorphMany to Audit:

```php
class Submission extends Model implements \OwenIt\Auditing\Contracts\Auditable
{
    public function audits(): MorphMany
    {
        return $this->morphMany(
            Audit::class,
            'auditable'
        );
    }
}

class Audit extends Model implements \OwenIt\Auditing\Contracts\Audit
{
    use \OwenIt\Auditing\Audit;

    public function user(): MorphTo
    {
        return $this->morphTo();
    }
}
```

With the GraphQL types:

```graphql
type User {
    id: ID!
    username: String!
    ...
}

union Userable = User | AnotherUserType

type Submission {
    audits: [Audit!]!   @morphMany
    ...
}

type Audit {
    user: Userable      @morphTo 
    ...
}

extend type Query {
    submission(
        id: ID!         @eq(key: "submissionId")

    ): Submission       @first
}
```

Running the `submission` query and fetching `submission.audits.user.*` will correctly batch and execute the SQL query to fetch user model data, but the `user` field will always return null.

**Lighthouse Version**

* Lighthouse: tested on both 5.67.0 and 5.34.0
* PHP 7.4
* Lumen (7.2.2) (Laravel Components ^7.0)

**Comment by spawnia** [comment]
In order to kickstart the work on a fix (if there is an issue with Lighthouse), please reproduce this problem in a test case. You can add it through a PR in either one of those files:
- https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/MorphToDirectiveTest.php
- https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/MorphManyDirectiveTest.php

**Comment by McManning** [comment]
I've narrowed this down to a conflict with a global scope in our `User` model to do a number of joins and normalization. For example:

```php
// Query executes as expected, but null results in morphTo response
class User extends Model implements AuthenticatableContract
{
    protected static function booted()
    {
        static::addGlobalScope(function (Builder $builder) {
            $builder
                ->select(['User.ID', 'User.Name'])
                ->join(...);
        });
    }
}

// Working example
class User extends Model implements AuthenticatableContract
{
    protected static function booted()
    {
        static::addGlobalScope(function (Builder $builder) {
            $builder
                ->select(['User.*'])
                ->join(...);
        });
    }
}
```

I'll play around some more and see if I can reproduce in a test case. I'm not super familiar with how Eloquent's polymorphism works under the hood so it's still up in the air whether this is a Lighthouse issue or not.

**Comment by McManning** [comment]
Closing this one out - I don't see a way to replicate the original reported issue in isolation.
