### ISSUE TITLE
deferred description in docs 404

### ISSUE THREAD

**Issue by Stevemoretz** [nuwave/lighthouse#2247]
Hi just wanted to let you know that the link of Read More about it here in https://lighthouse-php.com/5/performance/deferred.html#setup has been expired and gives 404. (https://www.apollographql.com/blog/introducing-defer-in-apollo-server-f6797c4e9d6e)

Was hoping to figure out how this actually works, does it need a websocket to work? Or is it via http somehow?

**Comment by spawnia** [comment]
I have never really used defer, so I do not know much about it. If you could dig up current documenation about it that would be great.

**Comment by Stevemoretz** [comment]
> I have never really used defer, so I do not know much about it. If you could dig up current documenation about it that would be great.

Thanks for the suggestion really appreciated, you can close this issue whenever you'd like
