### ISSUE TITLE
upload directive not found

### ISSUE THREAD

**Issue by metaversedataman** [nuwave/lighthouse#2249]
Why is it that in the Lighthouse Docs, upload directive is listed and explained, but trying to use it in the schema:

```
scalar Upload @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")


extend type Mutation {
    createImageList(
        id: ID!
        category_id: String!
        image_path: [Upload!]! @upload(disk: "public", path: "images/gallery", public: true)
        thumbnail: String!
        label: String
        description: String
        tags: JSON
        favorite_count: Int
    ): GalleryImageList @upsert
}
```

returns:
```
"debugMessage": "No directive found for upload"
```

I later checked the changelog of Lighthouse, and found out that upload directive was added in v5.6.
Using
```composer require nuwave/lighthouse```
added v5.58 of Lighthouse instead, which is an unexpected behavior.

I finally used:
```composer require nuwave/lighthouse dev-master```
Which updated Lighthouse to the latest version v5.68+

Now, I got a new error:
```
"debugMessage": "Array to string conversion",
            "message": "Internal server error"
```

I hope to find a way to upload files using upload directive soon.

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
