### ISSUE TITLE
Relay Compiler Complains About Schema

### ISSUE THREAD

**Issue by Jeckstart** [nuwave/lighthouse#225]
Hi, I'm trying to use Lighthouse with Relay, and I have a simple issue:

I'm using one schema file for both Lighthouse and Relay. But Relay compiler throws an error because it doesn't see Relay-related things in there (like edges and nodes). So, even though Lighthouse parses it good (generates schema with Relay-connections and everything), it won't work.

My schema:
```
type Query {
    crystals(first: Int!): [Crystal] @paginate(model: "App\\Crystal", type: "relay")
}

type Crystal {
    id: ID!
    name: String!
}
```

Relay compiler error:
> GraphQLParser: Unknown field `edges` on type `[Crystal]`.

What am I doing wrong?

---------------
I tried the solution from here:
https://github.com/nuwave/lighthouse/issues/110#issuecomment-388539496
Added IsRelayConnection trait to model and changed schema to:
```
type Query {
    crystals: [Crystal] @paginate(model: "App\\Crystal", type: "relay")
}

type Crystal @model(class: "App\\Crystal") {
    id: ID! @globalId
    name: String!
}
```

But error didn't change

**Comment by spawnia** [comment]
Since you closed this, seems like you solved the Issue. Mind sharing your findings?

**Comment by Jeckstart** [comment]
Yes, sorry ^^ the solution was right below that answer actually, I didn't see it first:

- install the graphql-cli;
- create .graphqlconfig in the root with something like:
```
{
  "schemaPath": "routes/graphql/__generated__/schema.graphql",
  "extensions": {
    "endpoints": {
      "dev": {
        "url": "http://......./graphql",
        "method": "post"
      }
    }
  }
}
```
- write your scripts in package.json like:
```
"db": "npm run schema && npm run relay",
"schema": "graphql get-schema -i -e dev",
"relay": "relay-compiler --src ./resources/assets/js --schema routes/graphql/__generated__/schema.graphql --extensions js jsx"
```
- run 'npm run db' instead of relay compiler

Then graphql get-schema will download generated schema each time to routes/graphql/__generated__/schema.graphql and voila ^^
