### ISSUE TITLE
Relation directives with paginator duplicates data with non-unique foreign keys

### ISSUE THREAD

**Issue by mostafa-rz** [nuwave/lighthouse#2251]
**Describe the bug**

When there is a custom FK in a relation that the FK is not unique, the data will be duplicated. Without a paginator the data is correct. 

**Expected behavior/Solution**

[The PaginatedModelsLoader](https://github.com/nuwave/lighthouse/blob/7f62dc9ed1a084be2ee697ba436aa71d24007eca/src/Execution/ModelsLoader/PaginatedModelsLoader.php#L89) union part, must be optimized.

**Steps to reproduce**

1. Run [testQueryPaginatedHasManyWithNonUniqueForeignKey().](https://github.com/mostafa-rz/lighthouse/tree/bug_2251)

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

latest

**Comment by spawnia** [comment]
Please add a pull request.

**Comment by mostafa-rz** [comment]
If in the `loadRelatedModels()` the unique values return, the problem will be solved. I think this is enough because later on in `associateRelationModels()` it is using the `match()` that just needs the existence of relation not multiple relations for each parent model.
