### ISSUE TITLE
`$argumentSet` is a dynamic property on the `ResolveInfo` class which is now a deprecated feature in PHP 8.2

### ISSUE THREAD

**Issue by ChrisExP** [nuwave/lighthouse#2254]
The `GraphQL\Type\Definition\ResolveInfo` class is modified and a dynamic property `$argumentSet` is added in a number of places within Lighthouse:
```
Nuwave\Lighthouse\Schema\Factories\FieldFactory::113
Nuwave\Lighthouse\Schema\Directives\ArgTraversalDirective::23
Nuwave\Lighthouse\Schema\Directives\ConvertEmptyStringsToNullDirective::44
Nuwave\Lighthouse\Schema\Directives\SpreadDirective::30
Nuwave\Lighthouse\Schema\Directives\TrimDirective::50
```

This behaviour is [deprecated in PHP 8.2](https://php.watch/versions/8.2/dynamic-properties-deprecated) and throws errors in static analysis tools.

I'm happy to create a pull request to fix this issue, but I'm not sure the best way to keep backwards compatibility or make upgrading as painless as possible, as the `$argumentSet` property is used a lot.

**Comment by stevebauman** [comment]
Hey @ChrisExP,

Either adding `#[AllowDynamicProperties]` onto the `ResolveInfo` class or adding the property `public $argumentSet` to it should be fine. I don't see any issues with that breaking backwards compatibility. 👍

**Comment by ChrisExP** [comment]
But that class isn't part of Lighthouse. It's in the webonyx graphql-php package. I could go and create a pull request to add that on their repository but I'm not sure if they would go for that.

**Comment by stevebauman** [comment]
Gotcha. I don't see why they wouldn't. They'll have to do one or the other to fix the PHP 8.2 deprecation error. Some members of this repository appear to be members of that repository (@spawnia may be -- correct me if I'm wrong).

**Comment by ChrisExP** [comment]
As I understand it `$argumentSet` is a workaround used by Lighthouse to make the arguments available to different parts of the code so they can be modified and used at different points in the request. It is never used in the webonyx repository. So it's not a bug for webonyx as they didn't intend `ResolveInfo` to be used that way.

**Comment by stevebauman** [comment]
I understand. The only other way to prevent any BC break is to extend the `ResolveInfo` class with our own implementation and add one of above mentioned patches. That is -- if webonyx GraphQL allows the `ResolveInfo` to be overridden (I do not know if this is the case).

Any other change is a BC break.

**Comment by ChrisExP** [comment]
Ok I'm starting a pull request.
The `ResolveInfo` class is instantiated in `ReferenceExecutor@resolveField`.
The best approach I can see is to extend `ReferenceExecutor` and override the `resolveField` method to create the extended `ResolveInfo` class, then tell GraphQL to use the new class with `Executor::setImplementationFactory()`.

**Comment by spawnia** [comment]
No need to reach into `webonyx/graphql-php`, just modify this part to pass a new, wrapped `ResolveInfo`: https://github.com/nuwave/lighthouse/blob/2b86311058c0b635f1aa484afe5a353877727e32/src/Schema/Factories/FieldFactory.php#L113-L115
