### ISSUE TITLE
Mismatch between ScoutDirectives class name and Directive name

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#226]
**Describe the bug**

The ScoutDirective is actually defined as `@search`

**Expected behavior**

The directive should have the same name as the class, as all other directives do.

**Proposal**

The class name and actual directive name should match. I would rename the class the SearchDirective, since that should not break compatibility and make it so we are independent of the actual underlying mechanism.

@olivernybroe Opinions?

**Comment by olivernybroe** [comment]
@spawnia hmm makes sense, it should still be easy to understand that it uses scout.
I am up for this change and yep, it's not a breaking change
