### ISSUE TITLE
Support Illuminate\Support\Collection parameter for $args in Custom Query and/or Mutation

### ISSUE THREAD

**Issue by crojasaragonez** [nuwave/lighthouse#2261]
**What problem does this feature proposal attempt to solve?**

Allow Laravel Collections in Custom Query || Mutation

Current:

```php
final class MyCustomQuery
{
    /**
     * @param  null  $_
     * @param  array{}  $args
     */
    public function __invoke($_, array $args)
    {
        // limited operations here with pure php array
        $args['key'];
    }
}
```

Proposal:

```php
final class MyCustomQuery
{
    /**
     * @param  null  $_
     * @param  array{}  $args
     */
    public function __invoke($_, array|Illuminate\Support\Collection $args)
    {
        //https://laravel.com/docs/9.x/collections#available-methods
        $args->get('key');
        $args->has('key');
    }
}
```
This will allow us to use any of the existing methods in laravel collections and use the fluent syntax in out mutations and queries.

**Comment by spawnia** [comment]
I will not make this change for the following reasons:

1. It would be a breaking change - or require reflection to determine the expected type, which is expensive.
2. Collections are not easily type annotated in the same way as array shapes (e.g. `array{foo: int, bar: string}`).
3. Index access is sufficiently convenient with arrays, I don't see much of a need for Collection methods such as `map` or `filter` for args.
4. You can do this yourself - either ad-hoc in your resolver or via a global field middleware directive.
