### ISSUE TITLE
Batch loading a paginated BelongsToMany relation omits non-unique related models

### ISSUE THREAD

**Issue by nrueckmann** [nuwave/lighthouse#2264]
It appears that Lighthouse is stripping duplicated entities when querying Relay connections. 

Example: Let's assume `User` has many `Roles`. We have 2 `Roles` and 2 `Users`. Each `User` has both `Roles`. When i now query all users only one user will have those roles.

**Expected behavior/Solution**

 I would expect Lighthouse to return all `Roles` on both `Users`.

**Steps to reproduce**

1. Add new test to `BelongsToManyDirectiveTest.php`:

```
final class BelongsToManyDirectiveTest extends DBTestCase
{

    public function testQueryAllBelongsToManyRelayConnection(): void
    {
        $this->schema = /** @lang GraphQL */ '
        type User {
            roles: [Role!]! @belongsToMany(type: CONNECTION)
        }

        type Role {
            id: ID!
        }

        type Query {
            users: [User]! @all
        }
        ';

        $user = factory(User::class)->create();
        $this->be($user);

        $roles = factory(Role::class, 3)->create();
        $user->roles()->attach($roles);

        $user2 = factory(User::class)->create();
        $user2->roles()->attach($roles);

        $this->graphQL(/** @lang GraphQL */ '
        {
            users {
                roles(first: 2) {
                    pageInfo {
                        hasNextPage
                    }
                    edges {
                        node {
                            id
                        }
                    }
                }
            }
        }
        ')->assertJsonCount(2, 'data.users.0.roles.edges')
            ->assertJsonCount(2, 'data.users.1.roles.edges');

        // JSON will be something like:
        // {"data":{"users":[{"roles":{"pageInfo":{"hasNextPage":true},"edges":[]}},{"roles":{"pageInfo":{"hasNextPage":true},"edges":[{"node":{"id":"1"}},{"node":{"id":"2"}}]}}]}}
    }
}
```

2. Run the test (e.g. `docker-compose exec php vendor/bin/phpunit --filter testQueryAllBelongsToManyRelayConnection`)

**Output/Logs**

```
There was 1 failure:

1) Tests\Integration\Schema\Directives\BelongsToManyDirectiveTest::testQueryAllBelongsToManyRelayConnection
Failed to assert that the response count matched the expected 2
Failed asserting that actual size 0 matches expected size 2.
```

**Lighthouse Version**

5.69.1

**Comment by nrueckmann** [comment]
Issue seems to be related to the usage of pivot tables. Simple relations do not seem to be an issue.

**Comment by spawnia** [comment]
Please try if the issue persists with `v5.68.0` or earlier, I think it might have been introduced with `v5.68.1`.

You can take a look at https://github.com/nuwave/lighthouse/pull/2252 and attempt a fix. Alternatively, a pull request with a failing test case would already help.

**Comment by nrueckmann** [comment]
thanks for your reply. i've added a PR with failing test.

**Comment by spawnia** [comment]
I can confirm the observation made by @TomatoPana in https://github.com/nuwave/lighthouse/issues/2272, removing `->unique()` from https://github.com/nuwave/lighthouse/blob/d8ce97e9f6feeb8e7fa7b7866ef38e92fbd94bf7/src/Execution/ModelsLoader/PaginatedModelsLoader.php#L102 fixes this issue, but causes https://github.com/nuwave/lighthouse/blob/d8ce97e9f6feeb8e7fa7b7866ef38e92fbd94bf7/tests/Integration/Schema/Directives/HasManyDirectiveTest.php#L300 to fail.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v5.70.1
