### ISSUE TITLE
columns and columnsEnum doesn't work with Predefined Ordering

### ISSUE THREAD

**Issue by SlyDave** [nuwave/lighthouse#2265]
When trying to use the columns or columnsEnum arguments for the @orderBy directive, they do not work when used in Predefined Ordering, but work fine when apply to a field's arguments.

example schema
```
enum DepartmentPositionSortableColumns {
    RANK @enum(value: "rank")
    NAME @enum(value: "name")
}

type DepartmentPosition {
    id: ID!
    departmentId: Int! @rename(attribute: "department_id")
    name: String!
    rank: Int
    createdAt: DateTime @rename(attribute: "created_at")
    updatedAt: DateTime @rename(attribute: "updated_at")
}

type Department {
    id: ID!
    name: String!
    shortName: String! @rename(attribute: "short_name")
    colour: String!
    isHidden: Boolean! @rename(attribute: "is_hidden")
    createdAt: DateTime @rename(attribute: "created_at")
    updatedAt: DateTime @rename(attribute: "updated_at")

    departmentPositions: [DepartmentPosition!]! @hasMany(relation: "positions") @orderBy(columnsEnum: "DepartmentPositionSortableColumns")
}

extend type Query {
    departments: [Department!]! @all
}
```

query:
```
{
	departments {
		name
		departmentPositions {
			name
			rank
		}
	}
}

```

This throws 
```
			"debugMessage": "SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `department_positions` where `department_positions`.`department_id` in (1, 2, 3, 4, 5, 6, 8, 10, 11, 12) order by `` asc)",
			"message": "Internal server error",
```

Same occurs if you use columns, but if you use `column "rank"`, it works just fine - but obviously only sorts by the single column.

**Expected behavior/Solution**

Sorting by multiple columns should be possible in Predefined Ordering.

**Steps to reproduce**

1. Create a schema
2. Add Predefined Ordering to a field, use a enum or columns to apply multiple sort columns
3. run a query against it

**Output/Logs**

<details><summary>Click to expand</summary>
{
	"errors": [
		{
			"debugMessage": "SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `department_positions` where `department_positions`.`department_id` in (1, 2, 3, 4, 5, 6, 8, 10, 11, 12) order by `` asc)",
			"message": "Internal server error",
			"extensions": {
				"category": "internal"
			},
			"locations": [
				{
					"line": 11,
					"column": 3
				}
			],
			"path": [
				"departments",
				0,
				"departmentPositions"
			],
			"trace": [
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php",
					"line": 672,
					"call": "Illuminate\\Database\\Connection::runQueryCallback()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php",
					"line": 376,
					"call": "Illuminate\\Database\\Connection::run()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
					"line": 2414,
					"call": "Illuminate\\Database\\Connection::select()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
					"line": 2402,
					"call": "Illuminate\\Database\\Query\\Builder::runSelect()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
					"line": 2936,
					"call": "Illuminate\\Database\\Query\\Builder::Illuminate\\Database\\Query\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php",
					"line": 2403,
					"call": "Illuminate\\Database\\Query\\Builder::onceWithColumns()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php",
					"line": 625,
					"call": "Illuminate\\Database\\Query\\Builder::get()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php",
					"line": 609,
					"call": "Illuminate\\Database\\Eloquent\\Builder::getModels()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php",
					"line": 195,
					"call": "Illuminate\\Database\\Eloquent\\Builder::get()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php",
					"line": 160,
					"call": "Illuminate\\Database\\Eloquent\\Relations\\Relation::get()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php",
					"line": 673,
					"call": "Illuminate\\Database\\Eloquent\\Relations\\Relation::getEager()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php",
					"line": 642,
					"call": "Illuminate\\Database\\Eloquent\\Builder::eagerLoadRelation()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Collection.php",
					"line": 60,
					"call": "Illuminate\\Database\\Eloquent\\Builder::eagerLoadRelations()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Execution\\ModelsLoader\\SimpleModelsLoader.php",
					"line": 28,
					"call": "Illuminate\\Database\\Eloquent\\Collection::load()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Execution\\BatchLoader\\RelationBatchLoader.php",
					"line": 84,
					"call": "Nuwave\\Lighthouse\\Execution\\ModelsLoader\\SimpleModelsLoader::load()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Execution\\BatchLoader\\RelationBatchLoader.php",
					"line": 59,
					"call": "Nuwave\\Lighthouse\\Execution\\BatchLoader\\RelationBatchLoader::resolve()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\webonyx\\graphql-php\\src\\Executor\\Promise\\Adapter\\SyncPromise.php",
					"line": 67,
					"call": "Nuwave\\Lighthouse\\Execution\\BatchLoader\\RelationBatchLoader::Nuwave\\Lighthouse\\Execution\\BatchLoader\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\webonyx\\graphql-php\\src\\Executor\\Promise\\Adapter\\SyncPromise.php",
					"line": 53,
					"call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::GraphQL\\Executor\\Promise\\Adapter\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\webonyx\\graphql-php\\src\\Executor\\Promise\\Adapter\\SyncPromiseAdapter.php",
					"line": 149,
					"call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\webonyx\\graphql-php\\src\\GraphQL.php",
					"line": 105,
					"call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter::wait()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
					"line": 270,
					"call": "GraphQL\\GraphQL::executeQuery()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
					"line": 204,
					"call": "Nuwave\\Lighthouse\\GraphQL::executeParsedQuery()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
					"line": 163,
					"call": "Nuwave\\Lighthouse\\GraphQL::parseAndExecuteQuery()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
					"line": 122,
					"call": "Nuwave\\Lighthouse\\GraphQL::executeOperation()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Support\\Utils.php",
					"line": 111,
					"call": "Nuwave\\Lighthouse\\GraphQL::Nuwave\\Lighthouse\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
					"line": 121,
					"call": "Nuwave\\Lighthouse\\Support\\Utils::mapEach()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Controllers\\GraphQLController.php",
					"line": 32,
					"call": "Nuwave\\Lighthouse\\GraphQL::executeOperationOrOperations()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
					"line": 48,
					"call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::__invoke()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
					"line": 262,
					"call": "Illuminate\\Routing\\ControllerDispatcher::dispatch()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
					"line": 205,
					"call": "Illuminate\\Routing\\Route::runController()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
					"line": 721,
					"call": "Illuminate\\Routing\\Route::run()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 128,
					"call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Middleware\\AttemptAuthentication.php",
					"line": 33,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Middleware\\AcceptJson.php",
					"line": 26,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 103,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
					"line": 723,
					"call": "Illuminate\\Pipeline\\Pipeline::then()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
					"line": 698,
					"call": "Illuminate\\Routing\\Router::runRouteWithinStack()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
					"line": 662,
					"call": "Illuminate\\Routing\\Router::runRoute()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
					"line": 651,
					"call": "Illuminate\\Routing\\Router::dispatchToRoute()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
					"line": 167,
					"call": "Illuminate\\Routing\\Router::dispatch()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 128,
					"call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\nova\\src\\Http\\Middleware\\ServeNova.php",
					"line": 23,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Laravel\\Nova\\Http\\Middleware\\ServeNova::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php",
					"line": 66,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Barryvdh\\Debugbar\\Middleware\\InjectDebugbar::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
					"line": 37,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Fruitcake\\Cors\\HandleCors::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
					"line": 57,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Fideloper\\Proxy\\TrustProxies::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
					"line": 21,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php",
					"line": 31,
					"call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
					"line": 21,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php",
					"line": 40,
					"call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
					"line": 27,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php",
					"line": 86,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 167,
					"call": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance::handle()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
					"line": 103,
					"call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
					"line": 142,
					"call": "Illuminate\\Pipeline\\Pipeline::then()"
				},
				{
					"file": "C:\\www\\workrest\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
					"line": 111,
					"call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter()"
				},
				{
					"file": "C:\\www\\workrest\\public\\index.php",
					"line": 52,
					"call": "Illuminate\\Foundation\\Http\\Kernel::handle()"
				},
				{
					"file": "C:\\www\\workrest\\server.php",
					"line": 21,
					"function": "require_once('C:\\www\\workrest\\public\\index.php')"
				}
			]
		}
	]
}

</details></br>

**Lighthouse Version**

nuwave/lighthouse (v5.69.1)

**Comment by SlyDave** [comment]
Just to confirm, this also occurs if it's applied to the query directly, rather than a field.


```
extend type Query {
    departmentPositions: [DepartmentPosition!]! @all @orderBy(columnsEnum : "DepartmentPositionSortableColumns")
    departmentPosition(id: ID @eq): DepartmentPosition @find @orderBy(columnsEnum : "DepartmentPositionSortableColumns")
}
```
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `department_positions` order by `` asc)
```

**Comment by spawnia** [comment]
What you are doing makes no sense, and that is even documented:

```
    """
    Use an existing enumeration type to restrict the allowed columns to a predefined list.
    This allows you to re-use the same enum for multiple fields.
    Mutually exclusive with `columns`.
    Only used when the directive is added on an argument.
    """
    columnsEnum: String
```

Use `column`.

**Comment by SlyDave** [comment]
Then I am clearly confused...

in Client Controlled Ordering
`@orderBy(columns: ["posted_at", "title"])`
and
```
enum PostColumn {
  # Another reason why you might want to have a custom enum is to
  # correct typos or bad naming in column names.
  POSTED_AT @enum(value: "postd_timestamp")
  TITLE @enum(value: "title")
}
@orderBy(columnsEnum: "PostColumn")
```
works as expected

in Predefined Ordering
`@orderBy(columns: ["posted_at", "title"]))`
and
```
enum PostColumn {
  # Another reason why you might want to have a custom enum is to
  # correct typos or bad naming in column names.
  POSTED_AT @enum(value: "postd_timestamp")
  TITLE @enum(value: "title")
}
@orderBy(columnsEnum: "PostColumn")
```
errors

As I'm clearly being dumb, how do I add secondary ordering to Predefined Ordering?

**Comment by SlyDave** [comment]
I guess my question isn't getting an answer then? or is the answer, it's not possible and it's not planned to be possible?
