### ISSUE TITLE
Pattern not working as domain name

### ISSUE THREAD

**Issue by Yannick-Bruening** [nuwave/lighthouse#2271]
Hi,

I'm trying to use a pattern from the `route.domain` option in the lighthouse configuration file. But it doesn't seem to be working.

This is the way I configured lighthouse to use the pattern.
```PHP
// lighthouse.php

return [
  'route' => [
    'domain' => '{graphql_host}'
  ]
]
```

This is the pattern definition.
```PHP
// RouteServiceProvider.php

Route::pattern('graphql_host', '(graphql\.[\w\.]+)');
```

Are patterns not working for domains in lighthouse?
Or is it the way we define the patterns that causes it to fail?

All my other routes work fine with that pattern as domain.
This is the way I use it with all other routes
```PHP
// RouteServiceProvider.php

Route::macro('graphql', function (string $group) {
    return Route::domain('{graphql_host}')
        ->as('graphql.')
        ->middleware(['graphql', 'forget:graphql_host'])
        ->group($group);
});
```

**Comment by spawnia** [comment]
Please point me to the relevant part of the Laravel documentation where this feature is described.

Lighthouse registers its route in https://github.com/nuwave/lighthouse/blob/master/src/Support/Http/routes.php - perhaps you can figure out an issue with that.

**Comment by Yannick-Bruening** [comment]
So as it seems Laravel does not pass Patterns defined in the RouteServiceProvider down to routes that are created from an external library.

The only possible way I found to make patterns work was by extending lighthouses `routes.php` with an option to include the `with` attribute to the `actions` array like this:

```PHP
// Support/Http/routes.php
<?php

use Illuminate\Container\Container;
use Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController;

if ($routeConfig = config('lighthouse.route')) {
    /**
     * Not using assert() as only one of those classes will actually be installed.
     *
     * @var \Illuminate\Contracts\Routing\Registrar|\Laravel\Lumen\Routing\Router $router
     */
    $router = Container::getInstance()->make('router');

    $actions = [
        'as' => $routeConfig['name'] ?? 'graphql',
        'uses' => GraphQLController::class,
    ];

    if (isset($routeConfig['middleware'])) {
        $actions['middleware'] = $routeConfig['middleware'];
    }

    if (isset($routeConfig['prefix'])) {
        $actions['prefix'] = $routeConfig['prefix'];
    }

    if (isset($routeConfig['domain'])) {
        $actions['domain'] = $routeConfig['domain'];
    }

   /* This had to be added to support custom patterns */
    if (isset($routeConfig['where'])) {
        $actions['where'] = $routeConfig['where'];
    }

    $router->addRoute(
        ['GET', 'POST'],
        $routeConfig['uri'] ?? 'graphql',
        $actions
    );
}
```
```PHP
'route' => [
        'domain' => '{graphql_host}',

        'where' => [
            'graphql_host' => '(graphql\.[\w\.]+)'
        ]
    ],
```

There might be another way that im not aware of but this was working.

Can this functionality be added to lighthouse directly or do I have to fork?

**Comment by spawnia** [comment]
> So as it seems Laravel does not pass Patterns defined in the RouteServiceProvider down to routes that are created from an external library.

I guess Lighthouse's routes are simply created before you define your pattern? Package service providers are run before your own.

The proposed change to the routes config seems fine to me.

**Comment by spawnia** [comment]
I added a configuration option in https://github.com/nuwave/lighthouse/commit/0a4280e4bba5db8de417f041ecf003f3e07bba2d.
