### ISSUE TITLE
Pagination with batch loading omits non-unique nested relationships

### ISSUE THREAD

**Issue by TomatoPana** [nuwave/lighthouse#2272]
**Describe the bug**
When accessing a Many-to-Many relationship from a One-to-Many relationship, with Batch Loading enabled, certain models are omitted from the result. Turning off batch loading gives the desired result, but impacts the performance of the request.

**Context**
This is the query which is being executed:
```graphql
query {
  product(uuid: "983547d2-5c6a-401f-bc48-f61ed3375105") {
    configurations {
      data {
        id
        modifierGroups {
          data {
            id
          }
        }
      }
    }
  }
}
```
And the schema of that query is:
```graphql
extend type Query {
    product(uuid: Uuid! @eq): Product @find
}
```
In the class  `App\Models\Product` is defined the relation `configurations`  as follows:
```php
public function configurations(): HasMany
{
    return $this->hasMany(ProductConfiguration::class);
}
```
And in the Graphql schema it is defined as follows:
```graphql
type Product {
  # ...
  configurations: [ProductConfiguration!]! @hasMany(type: SIMPLE)
  # ...
}
```
And in the model  `App\Models\ProductConfiguration.php`, this is the relation function:
```php
public function modifierGroups(): BelongsToMany
{
    return $this->belongsToMany(ModifierGroup::class, 'product_configuration_has_modifier_groups')
        ->using(ProductConfigurationHasModifierGroups::class)
        ->withPivot('id', 'quantity', 'max_replacements')
        ->withTimestamps();
}
```

**Steps to reproduce**
With that information in mind. In the Product table, we have a row with id For example `"983547d2-5c6a-401f-bc48-f61ed3375105"`, which have a relationship M:N with 3 rows of ProductConfigurations For example `["9835494a-2dd7-4b60-8016-f6a8da258af4","98354950-7e87-4d44-bf55-b4933abadf66","98354953-b827-4e1f-aa38-f6ae4875181c"]`. 
Every ProductConfiguration has a M:N relationship with the same ModifierGroup with id `"98354a23-5fd4-4282-a3bb-68fc128b59c7"`

**Output/Logs**
Executing the query gives the next result:

<details><summary>Click to expand</summary>

```json
{
  "data": {
    "product": {
      "configurations": {
        "data": [
          {
            "id": "9835494a-2dd7-4b60-8016-f6a8da258af4",
            "modifierGroups": {
              "data": []
            }
          },
          {
            "id": "98354950-7e87-4d44-bf55-b4933abadf66",
            "modifierGroups": {
              "data": []
            }
          },
          {
            "id": "98354953-b827-4e1f-aa38-f6ae4875181c",
            "modifierGroups": {
              "data": [
                {
                  "id": "98354a23-5fd4-4282-a3bb-68fc128b59c7"
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

</details></br>

But instead, the next result was expected:
<details><summary>Click to expand</summary>

```json
{
  "data": {
    "product": {
      "configurations": {
        "data": [
          {
            "id": "9835494a-2dd7-4b60-8016-f6a8da258af4",
            "modifierGroups": {
              "data": [
                {
                  "id": "98354a23-5fd4-4282-a3bb-68fc128b59c7"
                }
              ]
            }
          },
          {
            "id": "98354950-7e87-4d44-bf55-b4933abadf66",
            "modifierGroups": {
              "data": [
                {
                  "id": "98354a23-5fd4-4282-a3bb-68fc128b59c7"
                }
              ]
            }
          },
          {
            "id": "98354953-b827-4e1f-aa38-f6ae4875181c",
            "modifierGroups": {
              "data": [
                {
                  "id": "98354a23-5fd4-4282-a3bb-68fc128b59c7"
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

</details></br>

If I disabled batch loading, the result of the query is the expected, but with the caveat of being more slow.

**Lighthouse Version & environment**
Lighthouse: v5.70.0
PHP: v8.2
Laravel: v9.47.0

**Observations**
In `vendor/nuwave/lighthouse/src/Execution/ModelsLoader/Paginated/Models/Loader.php` at line 102 I found this sentence:
```php
return $relatedModels->unique();
```
Deleting `->unique()` fixes temporary the problem but no more testing were made, I do not know if something can be broken with that change.

**Comment by mostafa-rz** [comment]
I remember that I add this line because of another problem.
https://github.com/nuwave/lighthouse/issues/2251

**Comment by spawnia** [comment]
I can see how this issue relates to the changes made in https://github.com/nuwave/lighthouse/pull/2252. To start working on a fix, please create a pull request that adds a failing test case to https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/HasManyDirectiveTest.php.

**Comment by spawnia** [comment]
Thanks @MissaelAnda for adding https://github.com/nuwave/lighthouse/pull/2275. @mostafa-rz can you figure out if both tests are indeed valid and maybe think of a fix?

**Comment by spawnia** [comment]
Is this issue actually the same as https://github.com/nuwave/lighthouse/issues/2264?

**Comment by mostafa-rz** [comment]
> Thanks @MissaelAnda for adding #2275. @mostafa-rz can you figure out if both tests are indeed valid and maybe think of a fix?

The test is valid, i will check the logic again.
