### ISSUE TITLE
assert($type instanceof Type && $type instanceof InputType)

### ISSUE THREAD

**Issue by afeef-evm** [nuwave/lighthouse#2279]
**Describe the bug**
When opeing the graphql-playground or graphiql

**Expected behavior/Solution**

**Steps to reproduce**

1.When opeing the graphql-playground or graphiql

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```
{
  "errors": [
    {
      "debugMessage": "assert($type instanceof Type && $type instanceof InputType)",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 8,
          "column": 9
        }
      ],
      "path": [
        "__schema",
        "types"
      ],
      "trace": [
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Schema\\Factories\\ArgumentFactory.php",
          "line": 51,
          "function": "assert(false, 'assert($type instanceof Type && $type instanceof InputType)')"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Schema\\Factories\\ArgumentFactory.php",
          "line": 29,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\ArgumentFactory::convert(instance of GraphQL\\Language\\AST\\InputValueDefinitionNode)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Schema\\TypeRegistry.php",
          "line": 430,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\ArgumentFactory::toTypeMap(instance of GraphQL\\Language\\AST\\NodeList(4))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Type\\Definition\\InputObjectType.php",
          "line": 81,
          "call": "Nuwave\\Lighthouse\\Schema\\TypeRegistry::Nuwave\\Lighthouse\\Schema\\{closure}()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Type\\Definition\\InputObjectType.php",
          "line": 70,
          "call": "GraphQL\\Type\\Definition\\InputObjectType::initializeFields()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Utils\\TypeInfo.php",
          "line": 217,
          "call": "GraphQL\\Type\\Definition\\InputObjectType::getFields()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Utils\\TypeInfo.php",
          "line": 222,
          "call": "GraphQL\\Utils\\TypeInfo::extractTypes(GraphQLType: CreateGeneralSetting, array(385))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Type\\Schema.php",
          "line": 222,
          "call": "GraphQL\\Utils\\TypeInfo::extractTypes(GraphQLType: Mutation, array(384))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Type\\Schema.php",
          "line": 208,
          "call": "GraphQL\\Type\\Schema::collectAllTypes()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Type\\Introspection.php",
          "line": 240,
          "call": "GraphQL\\Type\\Schema::getTypeMap()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 623,
          "call": "GraphQL\\Type\\Introspection::GraphQL\\Type\\{closure}(instance of GraphQL\\Type\\Schema, array(0), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 1195,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: __Schema, instance of GraphQL\\Type\\Schema, instance of ArrayObject(1), array(2))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 1145,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: __Schema, instance of GraphQL\\Type\\Schema, array(1), instance of ArrayObject(4))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 1106,
          "call": "GraphQL\\Executor\\ReferenceExecutor::collectAndExecuteSubfields(GraphQLType: __Schema, instance of ArrayObject(1), array(1), instance of GraphQL\\Type\\Schema)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 793,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeObjectValue(GraphQLType: __Schema, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), instance of GraphQL\\Type\\Schema)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 741,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: __Schema, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), instance of GraphQL\\Type\\Schema)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 654,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: __Schema, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), instance of GraphQL\\Type\\Schema)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 557,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValueCatchingError(GraphQLType: __Schema, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), instance of GraphQL\\Type\\Schema)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 1195,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Query, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 264,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: Query, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 215,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php",
          "line": 156,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\GraphQL.php",
          "line": 162,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, null, 'IntrospectionQuery', null)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\webonyx\\graphql-php\\src\\GraphQL.php",
          "line": 94,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, null, 'IntrospectionQuery', null, array(29))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 270,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, null, 'IntrospectionQuery', null, array(29))"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 204,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeParsedQuery(instance of GraphQL\\Language\\AST\\DocumentNode, instance of Nuwave\\Lighthouse\\Schema\\Context, null, null, 'IntrospectionQuery')"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 163,
          "call": "Nuwave\\Lighthouse\\GraphQL::parseAndExecuteQuery('\n    query IntrospectionQuery {\n      __schema {\n        \n        queryType { name }\n        mutationType { name }\n        \n        types {\n          ...FullType\n        }\n        directives {\n          name\n          description\n          \n          locations\n          args {\n            ...InputValue\n          }\n        }\n      }\n    }\n\n    fragment FullType on __Type {\n      kind\n      name\n      description\n      \n      fields(includeDeprecated: true) {\n        name\n        description\n        args {\n          ...InputValue\n        }\n        type {\n          ...TypeRef\n        }\n        isDeprecated\n        deprecationReason\n      }\n      inputFields {\n        ...InputValue\n      }\n      interfaces {\n        ...TypeRef\n      }\n      enumValues(includeDeprecated: true) {\n        name\n        description\n        isDeprecated\n        deprecationReason\n      }\n      possibleTypes {\n        ...TypeRef\n      }\n    }\n\n    fragment InputValue on __InputValue {\n      name\n      description\n      type { ...TypeRef }\n      defaultValue\n      \n      \n    }\n\n    fragment TypeRef on __Type {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                  ofType {\n                    kind\n                    name\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ', instance of Nuwave\\Lighthouse\\Schema\\Context, null, null, 'IntrospectionQuery')"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 122,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeOperation(instance of GraphQL\\Server\\OperationParams, instance of Nuwave\\Lighthouse\\Schema\\Context)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Support\\Utils.php",
          "line": 114,
          "call": "Nuwave\\Lighthouse\\GraphQL::Nuwave\\Lighthouse\\{closure}(instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 121,
          "call": "Nuwave\\Lighthouse\\Support\\Utils::mapEach(instance of Closure, instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Controllers\\GraphQLController.php",
          "line": 32,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeOperationOrOperations(instance of GraphQL\\Server\\OperationParams, instance of Nuwave\\Lighthouse\\Schema\\Context)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
          "line": 48,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::__invoke(instance of Illuminate\\Http\\Request, instance of Nuwave\\Lighthouse\\GraphQL, instance of Illuminate\\Events\\Dispatcher, instance of Laragraph\\Utils\\RequestParser, instance of Nuwave\\Lighthouse\\Execution\\SingleResponse, instance of Nuwave\\Lighthouse\\Execution\\ContextFactory)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
          "line": 262,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, '__invoke')"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
          "line": 205,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 721,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 128,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
          "line": 52,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Fruitcake\\Cors\\HandleCors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Middleware\\AttemptAuthentication.php",
          "line": 33,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Middleware\\AcceptJson.php",
          "line": 26,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 103,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 723,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 698,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 662,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 651,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 167,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 128,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\livewire\\livewire\\src\\DisableBrowserCache.php",
          "line": 19,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Livewire\\DisableBrowserCache::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php",
          "line": 31,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php",
          "line": 40,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php",
          "line": 86,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
          "line": 52,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Fruitcake\\Cors\\HandleCors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 167,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 103,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 142,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 111,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\public\\index.php",
          "line": 52,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\xampp\\htdocs\\evm\\evm-backend\\server.php",
          "line": 21,
          "function": "require_once('C:\\xampp\\htdocs\\evm\\evm-backend\\public\\index.php')"
        }
      ]
    }
  ]
}
</details></br>

**5.70.3**

**Comment by guillaumeboussion** [comment]
@afeef-evm how did you handle this error ? I'm facing the same issue here, no way to understand the cause
