### ISSUE TITLE
Federated Entities resolver changes the order of results

### ISSUE THREAD

**Issue by kfc** [nuwave/lighthouse#2285]
**Describe the bug**

I'm using federated graph. One of my services receives the list of entities to resolve. It can accept multiple types of the same interface.
The example schema looks like this:
```
type Type1 @key(fields: "id") @extends {
  id: ID! @external
  subgraphField1: Int
}

type Type2 @key(fields: "id") @extends {
  id: ID! @external
  subgraphField2: Int
}
```

So the request to the service would look like this:
```graphql
query SubQuery($representations: [_Any!]!) {
	_entities(representations: $representations) {
		... on Type1 {
                         __typename
			subgraphField1
		}
		... on Type2 {
                         __typename
			subgraphField2
		}
	}
}
```
with the representations:
```json
{
	"representations": [
		{
			"__typename": "Type1",
			"id": "111",
		},
		{
			"__typename": "Type2",
			"id": "222",
		},
                {
			"__typename": "Type1",
			"id": "333",
		},
		{
			"__typename": "Type2",
			"id": "444",
		},
	]
}
```

In Entities resolver representations are grouped by type, making it:
```php
$groupedRepresentations = [
  'Type1' => [ ['id' => 111], ['id' => 333]],
  'Type2' => [ ['id' => 222], ['id' => 444]],
];
```
So after resoving these entites (with or without batch resolver), the result will have entities in the following order:
111, 333, 222, 444, which is different to original order. It leads to the incorrect data to be returned from the federated graph.

We're using apoolo federation v1.

**Expected behavior/Solution**

The order of entities in the response should be the same as in the requst.

**Steps to reproduce**

Described above

**Lighthouse Version**

Starting from 5.42.0.

**Comment by spawnia** [comment]
Thanks for the report. We investigated this issue before with https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/70, but have not encountered an actual problem in the wild.

@olivernybroe

**Comment by olivernybroe** [comment]
I have added a comments with a solution I can see we can do :) 

This should be a v6 solution only, as it is BC.
https://github.com/nuwave/lighthouse/pull/2286#issuecomment-1410254984
