### ISSUE TITLE
Cannot use @scope directive in conjunction with @delete

### ISSUE THREAD

**Issue by NickBourque** [nuwave/lighthouse#2288]
**Describe the bug**

When using the `@delete` directive to delete a model that has a global scope applied, you cannot use the `@scope` directive to override the global scope.

**Expected behavior/Solution**

You should be able to override global scopes at the same time as deleting a model.

**Steps to reproduce**

1. Create a `Post` model with a global scope that by default omits _archived_ posts.
```
public function apply(Builder $builder, Model $model)
{
    $builder->where('archived', false);
}
```
2. Add an override to your scope that removes the global scope.
```
protected function addWithArchived(Builder $builder)
{
    $builder->macro('withArchived', fn (Builder $builder) => $builder->withoutGlobalScope($this));
}
```
3. Try to delete an `archived` `Post` using `@delete` in conjunction with `@scope`, such as: 
```
deletePost(id: ID! @eq @scope(name: "withArchived")): Post! @delete(model: "App\\Models\\Post")
```

**Output/Logs**

```
Model Not Found exception
```

</details></br>

**Lighthouse Version**

`5.70.3`

**Comment by spawnia** [comment]
That is because `@delete` currently does not use a query builder in the same way as other directives like `@all` do. Instead, it uses `Model::find()` to retrieve the model.

Can scopes and `find()` be combined?

**Comment by NickBourque** [comment]
Yes, scopes and `find()` can be combined. In the above example, the query would look like `Post::withArchived()->find(1);`.
