### ISSUE TITLE
I get ERR_TIMED_OUT on lighthouse-php.com

### ISSUE THREAD

**Issue by Stevemoretz** [nuwave/lighthouse#2294]
Where is the document hosted ever since yesterday I get this error:
<img width="396" alt="Screen Shot 1401-11-23 at 13 28 50" src="https://user-images.githubusercontent.com/27680142/218304440-67e724ee-baa9-4e31-a2b5-59f5ddd47d6f.png">

Tried everything removing cache, a different browser but nothing helped, weird :(

**Comment by spawnia** [comment]
It is up now.
