### ISSUE TITLE
Where in Query? Possible?

### ISSUE THREAD

**Issue by exzib** [nuwave/lighthouse#2302]
Hey! I'm totally in love with this package and have recently decided to use it for a current large scale project im working on.
GraphQL is new to me but I am picking it up rather fast, really enjoying the process so far.

Something that I have noticed that I feel is missing, unless I missed it in the docs, is the possibility to chain a **where** into the queries.

Basically, I have a use case where my users has a model called a profile, this profile can have connected socials (Like Youtube, Twitter), and those can be tagged as private through a bool in the database.

So, when a visitor goes to their profile, any socials that are hidden should not be viewed to the average viewer, since they are private.

But when the owner of the profile goes to their settings for example, I don't want it to be hidden, because he owns it.

This is how my code for the query looks today:

`getProfileSocials(input: GetProfileSocialsPayload! @spread): [ProfileSocial]! @find(model: "App\\Models\\Core\\Profile")`

What I would want it the possibility to chain it like so:

`getProfileSocials(input: GetProfileSocialsPayload! @spread): [ProfileSocial]! @find(model: "App\\Models\\Core\\Profile") @where(name: "private", value: false)`

My solution today is that I have two relationships that are called based on the query that is being called:

```
    public function socials()
    {
        return $this->hasMany(ProfileSocial::class);
    }

    public function publicSocials()
    {
        return $this->hasMany(ProfileSocial::class)->where('private', 0);
    }
```

And im not sure that feels super clean.

Thanks!

**Comment by spawnia** [comment]
You can use `@eq` like this, but I am adding support for `@where` too in https://github.com/nuwave/lighthouse/pull/2306.

**Comment by exzib** [comment]
@spawnia Hey, appreciate the quick response!

And oh wow, yeah that worked for the query indeed, thanks for that!

How can I achieve this on type level? Say for example I have a Type like such:

```
type Profile {
    id: ID! @cacheKey

    "Display name of the profile"
    display_name: String!

    "Handle / Slug of the profile"
    handle: Handle

    "If the profile is private"
    private: Boolean!

    "Connected socials this profile has added"
    socials: [ProfileSocial!]! @hasMany(relation: "publicSocials") @cache
}
```

How can I achieve to make the socials null when the **private** field is false?

I assume I would need to make some type of custom type directive for this? Which one should I pick for this?

Thanks man, I really do appreciate you!

**Comment by exzib** [comment]
I managed to solve it by creating a FieldMiddleware like such:

```
    public function handleField(FieldValue $fieldValue, Closure $next)
    {
        $fieldValue = $next($fieldValue);
        $resolver = $fieldValue->getResolver();

        $fieldValue->setResolver(function ($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo) use ($resolver){
            $authenticated = auth()->check();

            if($root->private && !$authenticated || $root->private && $authenticated && auth()->id() !== $root->user_id) {
                return null;
            }

            if($root->private) {
                $authenticated = auth()->check();

                if($authenticated && auth()->id() !== $root->user_id || ! $authenticated) {
                    return null;
                }
            }

            return $resolver($root, $args, $context, $resolveInfo);
        });

        return $fieldValue;
    }
```

Do you see any problems with this approach?
