### ISSUE TITLE
@delete without @eq wipes whole table

### ISSUE THREAD

**Issue by DaLukasTI** [nuwave/lighthouse#2303]
**Describe the bug**
I had a mutation `deleteProduct(id: ID!): Product @delete @can(ability: "delete")`
I upgraded my project to laravel 10 and this mutation behaves very weird. (I'm on the dev-master)
When using the migration as is, and calling the endpoint it deletes ALL entities in the product table(4000 records in my case).
when I add `@eq` as in `deleteProduct(id: ID! @eq): Product @delete @can(ability: "delete")` it only deletes the one product as expected. This is nowhere to be found in the docs in the docs it is stated as

`
type Mutation {
  deletePost(id: ID!): Post @delete
}` 

Is this intended behaviour or a bug, I'm not sure :sweat_smile: 

</details></br>

**Lighthouse Version**
dev-master

**Comment by spawnia** [comment]
https://lighthouse-php.com/master/api-reference/directives.html#delete mentions using `@whereKey`, where were you looking? 

I could see adding a stronger warning against this error in the docs though, especially in the example with multiple optional filters to apply. We have to make sure that at least one filter is given.

**Comment by DaLukasTI** [comment]
I see where it went wrong, if you are for example on the master docs and use the searchbar on the top, you get booted to the /5/ page of the query you searched, must have missed that. 
Is there a reason to use the `@wherekey` over `@eq` in those queries?

**Comment by spawnia** [comment]
> I see where it went wrong, if you are for example on the master docs and use the searchbar on the top, you get redirected to the /5/ page of the query you searched, must have missed that.

Yeah, that is a known issue in https://github.com/nuwave/lighthouse/issues/1392.

> Is there a reason to use the @wherekey over @eq in those mutations?

`@whereKey` does not care about the name of the argument, it always uses the primary key of the model.

**Comment by DaLukasTI** [comment]
Okay thanks for clearing that out! Should I leave this ticket open for visibility?

**Comment by spawnia** [comment]
@DaLukasTI please review https://github.com/nuwave/lighthouse/pull/2304, it should at least guard against some potential issues.

The upgrade guide mentions the need to use filters in `@delete`, see https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#use-filters-in-delete-forcedelete-and-restore, but I could see how that can be forgotten. I wonder if we could add additional validation to ensure no mass deletions happen accidentally.
