### ISSUE TITLE
Cannot apply two where directives

### ISSUE THREAD

**Issue by hosmelq** [nuwave/lighthouse#231]
**Describe the bug**
I cannot apply two where directives when i use the same key.

**Expected behavior**
Apply two where clauses.

**Schema**

```graphql
type Campaign @model {
  id: ID! @globalId
  posts(
    since: Date @where(clause: "whereDate", key: "publish_at", operator: ">=")
    until: Date @where(clause: "whereDate", key: "publish_at", operator: "<=")
  ): [Post!]!
    @hasMany(type: "relay")
}
```

**Result query**

```sql
SELECT
    *
FROM (
    SELECT
        *
    FROM
        `shr_posts`
    WHERE
        date(`publish_at`) <= '2018-07-31'
    LIMIT 10 offset 0
) AS `posts`
```

**Environment**

Lighthouse Version: v2.2-beta.1
Laravel Version: 5.5
PHP Version: 7.2.7

**Comment by hosmelq** [comment]
I was looking into this and i found that the problem is in [setFilter](https://github.com/nuwave/lighthouse/blob/master/src/Support/Database/QueryFilter.php#L109) method called by [injectFilter](https://github.com/nuwave/lighthouse/blob/master/src/Support/Traits/HandlesQueryFilter.php#L18) that replace the old one.

**Comment by chrissm79** [comment]
@hosmelq Thanks for reporting this one!! I'll try to dig into tonight and I'll update when I have a fix!

**Comment by chrissm79** [comment]
@hosmelq Actually, you're mentioned fix may very well do it and seems like a logical solution. Did you want to create a PR for it? If not I'll likely use your suggestion in my fix.
