### ISSUE TITLE
v6 release feedback

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#2319]
I just released the first alpha for the upcoming major version 6 of Lighthouse: https://github.com/nuwave/lighthouse/releases/tag/v6.0.0-alpha.1.

Please try it (or following pre-releases) in your projects, follow https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#v5-to-v6,
and report any issues or shortcoming you can find in this issue or separate issues.

```sh
composer require nuwave/lighthouse:v6.0.0-beta.1
```

**Comment by adesugbaa** [comment]
I have an error as part of my post install steps.

I am not sure how to troubleshoot:

```
> @php artisan lighthouse:ide-helper
Wrote schema directive definitions to /var/www/app/schema-directives.graphql.

  TypeError 

 Nuwave\Lighthouse\Schema\Directives\BaseDirective::hydrate(): Argument #2 ($definitionNode) must be of type GraphQL\Language\AST\ScalarTypeDefinitionNode|GraphQL\Language\AST\ObjectTypeDefinitionNode|GraphQL\Language\AST\FieldDefinitionNode|GraphQL\Language\AST\InputValueDefinitionNode|GraphQL\Language\AST\InterfaceTypeDefinitionNode|GraphQL\Language\AST\UnionTypeDefinitionNode|GraphQL\Language\AST\EnumTypeDefinitionNode|GraphQL\Language\AST\EnumValueDefinitionNode|GraphQL\Language\AST\InputObjectTypeDefinitionNode, GraphQL\Language\AST\ObjectTypeExtensionNode given, called in /var/www/app/vendor/nuwave/lighthouse/src/Schema/DirectiveLocator.php on line 224

 at vendor/nuwave/lighthouse/src/Schema/Directives/BaseDirective.php:58
    54▕ 
    55▕     /**
    56▕      * The hydrate function is called when retrieving a directive from the directive registry.
    57▕      */
 ➜  58▕     public function hydrate(DirectiveNode $directiveNode, ScalarTypeDefinitionNode|ObjectTypeDefinitionNode|FieldDefinitionNode|InputValueDefinitionNode|InterfaceTypeDefinitionNode|UnionTypeDefinitionNode|EnumTypeDefinitionNode|EnumValueDefinitionNode|InputObjectTypeDefinitionNode $definitionNode): self
    59▕     {
    60▕         $this->directiveNode = $directiveNode;
    61▕         $this->definitionNode = $definitionNode;
    62▕ 

     +1 vendor frames 

 2   [internal]:0
     Nuwave\Lighthouse\Schema\DirectiveLocator::Nuwave\Lighthouse\Schema\{closure}(Object(GraphQL\Language\AST\DirectiveNode))
     +28 vendor frames 

 31  artisan:35
     Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))


Script @php artisan lighthouse:ide-helper handling the post-update-cmd event returned with error code 1
```

**Comment by eshimischi** [comment]
L10 support is only planned for v6?

**Comment by hfoletto** [comment]
I upgraded in a project of mine to the beta,  I went though the upgrade guide and tested the application, seemed to be working.
However a protected route throws unauthenticated even when correctly authenticated.

in `schema.graphql`
![image](https://user-images.githubusercontent.com/1384775/221048739-c394b650-540b-4ca3-956d-ea60400dfd4d.png)

in `config/lighthouse.php`
![image](https://user-images.githubusercontent.com/1384775/221048836-d625ecbb-ed57-4cb4-8a3a-b2c163caf134.png)

I'm using sanctum v3.2.1 in this application, which is compatible with Laravel 10.

**Comment by eshimischi** [comment]
@hfoletto there is [lighthouse-sanctum](https://github.com/daniel-de-wit/lighthouse-sanctum) but it doesn't support v6 so far, already made an issue there

**Comment by hfoletto** [comment]
> @hfoletto there is [lighthouse-sanctum](https://github.com/daniel-de-wit/lighthouse-sanctum) but it doesn't support v6 so far, already made an issue there

Ohhh, I wasn't aware of this package. I have been using lighthouse with sanctum without this package with great success on version 5, just followed what's here: https://lighthouse-php.com/5/security/authentication.html#laravel-sanctum

Actually, now that I'm reading it again, I realized that I have overwritten that configuration when copping the new one. I have added the `EnsureFrontendRequestsAreStateful` middleware back and it's working!

**Comment by wimski** [comment]
@spawnia I've got the same error as @adesugbaa with the following schema:

```graphql
extend type Query @guard {
    me: User! @auth
}
```

If I remove the `@guard` directive or move it to the `me` field, the error goes away. Is it no longer supported to have directives (or specifically the `@guard` directive) on type extensions?

**Comment by spawnia** [comment]
@wimski @adesugbaa I added a test and fixed the error you described in https://github.com/nuwave/lighthouse/pull/2323, released with https://github.com/nuwave/lighthouse/releases/tag/v6.0.0-alpha.2.

**Comment by adesugbaa** [comment]
@spawnia Thanks for the quick turnaround. I can verify that the error is gone.

**Comment by spawnia** [comment]
@wimski have you tried `UsesTestSchema` instead? It uses `bind()` over `singleton()´.

**Comment by wimski** [comment]
@spawnia that doesn't seem to make any difference.

```php
// ! Only showing changes in comparison to the initial example !
use Nuwave\Lighthouse\Testing\UsesTestSchema;

class FooTest
{
    use UsesTestSchema;

    protected function setUp(): void
    {
        parent::setUp();

        $this->setUpTestSchema();
    }

    protected function setSchema(string $schema): void
    {
        $this->schema = $schema;
    }
}
```

**Comment by LVMade01** [comment]
I also have trouble with custom schemas in PHPUnit tests. They seemed to be cached. However calling `$this->bootRefreshesSchemaCache();` (with `use RefreshesSchemaCache;`) helped.

**Comment by spawnia** [comment]
Hm, I might need to try this myself and review the docs in https://github.com/nuwave/lighthouse/blob/master/docs/master/testing/extensions.md#use-a-test-schema - it currently says:

> UsesTestSchema does not work with RefreshesSchemaCache, choose one.

**Comment by spawnia** [comment]
I just released https://github.com/nuwave/lighthouse/releases/tag/v6.0.0.
