### ISSUE TITLE
Integration with Laravel Pennant

### ISSUE THREAD

**Issue by binaryfire** [nuwave/lighthouse#2324]
Hi all

Laravel Pennant is a new core package for feature flags: https://laravel.com/docs/10.x/pennant. The ability to restrict features to certain users based on subscription level, beta tester status etc is really powerful. Good summary here: https://www.youtube.com/watch?v=xn7bRW_lbTE

Would it be possible to add a directive for this in v6?

**Comment by spawnia** [comment]
Please describe further what you would like to achieve. What would an example schema look like? How would it behave?

**Comment by binaryfire** [comment]
I imagine @feature would be similar to @can ? Except instead of checking an ability, it'd check whether the specified feature is enabled for the user: https://laravel.com/docs/10.x/pennant#checking-features

**Comment by binaryfire** [comment]
Features can be used for AB testing and to provide different behaviour, but the main use case is actually access. There are included blade directives and middleware for this. Here's an example: 

In `AppServiceProvider.php`:
```
public function boot(): void
{
    Feature::define( 'tasks-management', function (User $user) {
        return (bool)$user->is_premium;
}
```

Using the `@feature` blade directive:
```
@feature('tasks-management')
.........
@endfeature
```

Using the feature middleware:
```
->middleware( 'features:tasks-management')
```

Wouldn't it make sense to have the same functionality in a Lighthouse directive? It wouldn't be easy to achieve the same thing with @can since policies/permissions are used in a different context.

**Comment by spawnia** [comment]
> but the main use case is actually access

None of the examples in the Laravel documentation show this. It all seems to be centered around taking one or the other code path.

If you insist on using feature flags as access control and want to simplify that through a directive, you are free to do that with a custom directive. I do not want to encourage conflating features with policies, and I believe adding a directive `@feature` that acts just like `@can` sends the wrong message. From my understanding, you would be better served to just use the feature API in a custom resolver.

**Comment by binaryfire** [comment]
Ok no problems, makes sense
