### ISSUE TITLE
Tests failing when using pattern in domain field

### ISSUE THREAD

**Issue by Yannick-Bruening** [nuwave/lighthouse#2332]
**Describe the bug**
When a pattern is set within the domain field the tests will fail because they cannot resolve the pattern.

**Expected behavior/Solution**
It should be possible to define a value for the pattern which the tests can use.

**Steps to reproduce**

1. Set a pattern in the domain field in the config
2. Set a pattern in the where field in the config
3. Run the tests against that url

**Lighthouse Version**
5.71.0

**Comment by MichaelWillmer** [comment]
This should be resolved with this PR: #2333
