### ISSUE TITLE
Validation error messages when using @spread

### ISSUE THREAD

**Issue by andgith** [nuwave/lighthouse#2338]
This issue was brought up in #1631 but I wanted to follow it up.

I understand the the returned errors should be return in same structure as the client would expect e.g _input.name_. But the accompanying message also includes the prefix.

Does this not make it difficult to use the returned messages directly in the UI? The UX is strange when seeing 

`The input.description field is required.`

And adding a custom message for each fields seems like a lot of overhead for simple validation.

**Lighthouse Version**
v5.71.0

**Comment by spawnia** [comment]
I think the behaviour is fine as is, I would rather keep it consistent than to optimize for some use cases. If you want pretty messages for end users you will have to change them anyways in many cases. For example, the inputs could be nested further and use snake_case: `input.user.email_address`. I would not show that to users, even without `input.`.
