### ISSUE TITLE
Adding phpunit docs for subscription

### ISSUE THREAD

**Issue by Stevemoretz** [nuwave/lighthouse#2341]
**What problem does this feature proposal attempt to solve?**

In the docs, you get how to use phpunit with query and mutation but not subscription.

**Which possible solutions should be considered?**

It took me a couple of hours to debug and reverse-engineer some stuff, and since you told me that you didn't work with subscriptions yourself was thinking to share this with you so you might want to test them and add them to the docs. (I obviously have tested this myself)

So here's how I did it:

https://stackoverflow.com/questions/68402714/how-to-phpunit-subscriptions-in-laravel-lighthouse/75677090#75677090

**Comment by spawnia** [comment]
Looks like the code for this can be integrated partly in `MakesGraphQLRequests` and in `TestResponseMixin`, and an example can be added to the testing docs. Can you create a pull request?

**Comment by Stevemoretz** [comment]
> Looks like the code for this can be integrated partly in `MakesGraphQLRequests` and in `TestResponseMixin`, and an example can be added to the testing docs. Can you create a pull request?

Sure I think I could spare some time for this, one problem I have with this repository is that master branch gets stuck on this commit every time I try to do a PR.

<img width="717" alt="Screen Shot 1401-12-18 at 12 41 35" src="https://user-images.githubusercontent.com/27680142/223975699-aa7fc1f7-33ad-44c6-980f-1681aa7142f1.png">

When I pull from master it says it's up to date, I'm tired of cloning and setting up every time for every PR, do or did you have a similar problem with that commit? It just doesn't update I end up cloning and creating a complete new fork every time.

**Comment by spawnia** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by Stevemoretz** [comment]
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

Thanks :)

**Comment by spawnia** [comment]
> I'm working on this, is there any way to call ->postJson from inside TestResponseMixin?

I don't think so, I think the functions will have to composed in a different way.

**Comment by Stevemoretz** [comment]
> > I'm working on this, is there any way to call ->postJson from inside TestResponseMixin?
> 
> I don't think so, I think the functions will have to composed in a different way.

Thanks Is this acceptable?

```
public function assertGraphQLSubscriptionAuthorized($something): \Closure
```

so the user can pass in the instance of class? 

```
$this->assertGraphQLSubscriptionAuthorized($this)
```

Doesn't look that bad just wanted to check with you though

**Comment by spawnia** [comment]
I am assuming you mean `$testResponse->assertGraphQLSubscriptionAuthorized($this)`, in which case I would say that is unusual but seems fine.

**Comment by Stevemoretz** [comment]
> I am assuming you mean `$testResponse->assertGraphQLSubscriptionAuthorized($this)`, in which case I would say that is unusual but seems fine.

Thank you the PR is created https://github.com/nuwave/lighthouse/pull/2343
