### ISSUE TITLE
6.0.0-beta.3 lighthouse:ide-helper error

### ISSUE THREAD

**Issue by stephenjason89** [nuwave/lighthouse#2347]
**Describe the bug**

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/3810177/224533727-5d45a42c-6f9b-4419-a610-d4d4c2e74366.png">

**Expected behavior/Solution**
No errors

**Steps to reproduce**

1. upgrade a v5.71.0 lighthouse to v6.0.0-beta.3
2. run lighthouse:ide-helper

**Output/Logs**

<details><summary>Click to expand</summary>

```
 Nuwave\Lighthouse\Exceptions\DefinitionException 

  Failed to find class Return in namespaces [App, App\Models] for directive @create.
  ```

</details></br>

**Lighthouse Version**
6.0.0-beta.3

**Comment by spawnia** [comment]
`Return` is not a valid name for a class. I am wondering how this ever worked?

What is the relevant part of your schema? Did you sync your `config/lighthouse.php` with the changes from the new version?

**Comment by spawnia** [comment]
Closing due to lack of feedback.
