### ISSUE TITLE
Generate Tests Stubs

### ISSUE THREAD

**Issue by yondifon** [nuwave/lighthouse#2349]
**What problem does this feature proposal attempt to solve?**
Add Test Stubs to the package. 

When creating mutations and queries, It'd be nice to have the option to create a test class with maybe one test function even if it's empty.

**Which possible solutions should be considered?**
We could add `--test` option to `lighthouse:query` & `lighthouse:mutation` commands

 Something like: 
```bash
php artisan lighthouse:query UserQuery --test
```
should generate the query in Graphql queries Directory as well as

```php 

<?php

namespace Tests\Feature\GraphQL\Queries;

use Tests\Testcase;

class UserQueryTest extends TestCase
{
    /** @test */
    public function can_get_user_query()
    {
        $response = $this->graphQL(/* @lang GraphQL */ '
            query User {
                user
            }
        ');

        $response->assertJson([
            'data' => [
                'user' => [],
            ],
        ]);
    }
}

```
I think this will help 'standardize' the way the package is used and tested.

**Comment by spawnia** [comment]
I like the idea. I am not planning to work on this myself, but would accept pull requests that add such a feature. The commands are defined in https://github.com/nuwave/lighthouse/tree/master/src/Console.
