### ISSUE TITLE
@field namespace requirement is inconsistent

### ISSUE THREAD

**Issue by Yannick-Bruening** [nuwave/lighthouse#2350]
Hi,
we have an issue with our lighthouse powered GraphQL api.
Why do we need to specify the full namespace in an imported `.graphql` file but not in the `schema.graphql`.
It feels weird to define the full path with namespace in one `.graphql` file but not in the other.
Is this a bug or is this intended behaviour?

Versions in use
```
nuwave/lighthouse         5.71.0
nwidart/laravel-modules.  9.0.6
```

This is our file structure.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/69695342/225259962-010c8b5e-5b2c-4262-bbc8-a099ecc94d59.png">

Contents of `namespaces` of `lighthouse.php`
```php
<?php

...

/* resolve module paths is to get all Entities/Eloquent Models which are defined within the different modules */
'namespaces' => [
    'models' => ['App', 'App\\Models', ...resolveModulePaths('Entities')],
    'queries' => ['App\\GraphQL\\Queries', 'Modules\\GraphQL\\Queries'],
    'mutations' => ['App\\GraphQL\\Scalars', 'Modules\\GraphQL\\Mutations'],
    'subscriptions' => ['App\\GraphQL\\Subscriptions', 'Modules\\GraphQL\\Subscriptions'],
    'interfaces' => ['App\\GraphQL\\Interfaces', 'Modules\\GraphQL\\Interfaces'],
    'unions' => ['App\\GraphQL\\Unions', 'Modules\\GraphQL\\Unions'],
    'scalars' => ['App\\GraphQL\\Scalars', 'Modules\\GraphQL\\Scalars'],
    'directives' => ['App\\GraphQL\\Directives', 'Modules\\GraphQL\\Directives'],
    'validators' => ['App\\GraphQL\\Validators', 'Modules\\GraphQL\\Validators'],
],

...
```

Example field ZipCode
```GraphQL
"""
validates a zipcode and returns all matching geopoints
"""
zipCode(zipcode: String!, countryIsoCode: String): ZipCode
@field(resolver: "Zip\\ZipcodeResolver")
```

Definition of ZipCode in  `graphql/types/zipcode/ZipCode.graphql`
```GraphQL
type ZipCode {
  zipCode: String
  
  isValid: Boolean
  
  geoPoints: [GeoPoint] 
  @field(resolver: "Modules\\GraphQL\\Queries\\Zip\\GeoPointsResolver")
}
```
Why doesn't `Zip\\GeoPointsResolver` work here. But `Zip\\ZipcodeResolver` works in the default schema file.

All of the types are imported through the `graphql/types.graphql` file
```graphql
...

#import Zipcode/*.graphql

...
```
And this `types.graphql` itself is imported within the `schema.graphql` file.

If you have any questions regarding our structure etc. feel free to ask.

**Comment by spawnia** [comment]
This has nothing to do with the structure of your files. Default namespaces only work for fields of the root types `Query`, `Mutation` and `Subscription`.

**Comment by spawnia** [comment]
Also see https://github.com/nuwave/lighthouse/issues/1711#issuecomment-770367189.
