### ISSUE TITLE
6.0 Removal of `category` and the absence of a replacement

### ISSUE THREAD

**Issue by Rezrazi** [nuwave/lighthouse#2361]
**Describe the bug**
As per the recent major update, a breaking change was reported here https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#removed-error-extension-field-category

However, this BC would prohibit the use of v6.0 for clients that rely on the `extensions->category` to determine the kind of error that was thrown.

For instance, a client might expect the category to be `authentication` to determine that a user is not currently logged in, and potentially redirect them to a login page.

With this gone, and with no replacement or clear way of circumventing this limitation, we are unable to use v6.0 as it is.

**Expected behavior/Solution**

When an error is thrown, the response should have an indication of the error category as it was the case in v5.x

**Steps to reproduce**

1. Create a basic a query
2. Add a `@can` directive to check a specific policy
3. Go through the unhappy path of this validation
4. Observe response, no category or error type is provided, client is not able to determine what to do next

**Output/Logs**

<details><summary>
Click to expand
</summary>

```json
{
  "errors": [
    {
      "message": "This action is unauthorized.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ]
    }
  ]
}
```

With v5.x

```json
{
  "errors": [
    {
      "message": "This action is unauthorized.",
      "extensions": {
        "category": "authorization"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ]
    }
  ]
}
```

</details></br>

**Lighthouse Version**

v6.0.0

**Comment by Rezrazi** [comment]
In this change referenced here https://github.com/nuwave/lighthouse/commit/639769226b47515c68a6a7fbfa73c1ae1e93a046#diff-fed7df5b3c93a8f0620ba0a468b03159d1c6da8c281917973d2f4ead43e6cc3cR9

The exceptions lost their `getCategory()` method in favor of `getExtensions()` (and sometimes even this latter is not present)

I believe we may still keep the `category` under the extensions array as it's a free-to-use set of data that may be included in the error response as per GraphQL spec.

To ensure backward compatibility, especially for frontend client and libraries relying on this category value, perhaps it could be a good idea to bring it back in the underlying exceptions defined in the package.

**Comment by spawnia** [comment]
I was never a fan of `category`, it always was a non-standard addition to `webonyx/graphql-php` and never a part of any GraphQL standard. I will not bring it back.

As mentioned in the `webonyx/graphql-php` upgrade guide:

> You can always switch to [custom error formatting](https://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting)
to revert to the old format.

**Comment by Rezrazi** [comment]
> I was never a fan of category, it always was a non-standard addition to webonyx/graphql-php and never a part of any GraphQL standard. I will not bring it back.

Yes, however the GraphQL standard linked in the PR that removed this states the following: 
> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.

So in theory, this is not something that goes against the actual spec, we may still provide additional contextual metadata to the client consuming the Exception. As it stands, this change completely revokes the ability for any frontend client that may rely on this category to determine the best course of action in response to an exception handled by lighthouse.

I would be happy to submit a PR for this to re-include category under extensions, or perhaps change its name to something more suitable, if you are to reconsider this.

All the best!

**Comment by Rezrazi** [comment]
Additionally, I do understand the removal from `webonyx/graphql-php` as it's a framework-agnostic solution, however Lighthouse is dedicated to be used with Laravel, so it would make sense for the implementation to include some additional metadata in extensions

**Comment by spawnia** [comment]
Once `category` was put under `extensions`, it was indeed spec-compliant. However, I don't see how it ties into Laravel in any way - it makes just as much (or little) sense here as it did in the base library.

I improved `UPGRADE.md` with a quick section about how you can restore `category`. I am staying firm that I will not add it back.
