### ISSUE TITLE
[docs] Missing doc for custom attribute name(s) in Validator Class  

### ISSUE THREAD

**Issue by rhanmiano** [nuwave/lighthouse#2370]
**Describe the bug**

Hello, it seems that the doc for setting custom attribute name is missing under **Security / Validation / Validator Classes** even though possible per `\Validation\Validator` class. Noticed this when implementing a custom validator for a mutation I was creating and wanted to somehow change the name of attributes in the validation message(s) being outputed. 

**Expected behavior/Solution**

Perhaps would be good to add it below [Custom Validator Messages](https://lighthouse-php.com/master/security/validation.html#custom-validator-messages) for consistency because custom messages and attributes are included in the docs for inline validation using `@rules` directive, and for others that might be looking for the same functionality as well.

**Steps to reproduce**

1. Kindly go to **Security / Validation / Validator Classes** documentation

**Output/Logs** 

[None]

</details></br>

**Lighthouse Version**
Using v5. It seems that it is missing on both v5 and v6 docs,

**Comment by spawnia** [comment]
Thanks, fixed in the v6 docs.
