### ISSUE TITLE
Paginate directive together with Complexity directive is not working

### ISSUE THREAD

**Issue by mostafa-rz** [nuwave/lighthouse#2371]
**Describe the bug**

Overwriting the default paginate directive complexity with complexity directive is throw an error.

**Expected behavior/Solution**

The query run without an error and the complexity directive overwrite the default behavior of the paginate directive complexity.

**Steps to reproduce**
Fail test `testPaginateWithComplexityDirective()`

1. Add complexity directive to the field with paginate directive.

**Output/Logs**

<details><summary>Click to expand</summary>

```
Node users can only have one directive of type Nuwave\Lighthouse\Support\Contracts\ComplexityResolverDirective but found [@paginate, @complexity].
```

</details></br>

**Lighthouse Version**

v6.3.1

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v6.4.0
