### ISSUE TITLE
relocate folder

### ISSUE THREAD

**Issue by emtudo** [nuwave/lighthouse#2375]
I'm using version 6.4, when trying to move the App\GraphQL folder to App\Infra\GraphQL

Even change the settings in config/lighthouse.php:
in namespace options

I have errors not finding the class

"Failed to find class App\GraphQL\Scalars\EmailScalar extends GraphQL\Type\Definition\ScalarType in namespaces [App\Infra\GraphQL\Scalars] for the scalar Email."

example is the scalar Email @scalar(class: "App\\Infra\\GraphQL\\Scalars\\EmailScalar")

It says it can't find it:

App\GraphQL\Scalars\EmailScalar

Strangely it gets the name correctly from the end, but ignores the class altogether and tries to search the default directory.

Before changing the directory everything worked.

**Expected behavior/Solution**

**Steps to reproduce**

 $response = $this->graphQL(/** @lang GraphQL */ '
        mutation ForgotPassword($email: Email! $route: Url!) {
            forgot_password(email: $email, route: $route)
        }
    ', [
        'email' => 'teste@teste.com',
        'route' => 'http://localhost/auth/reset/__token__',
    ]);

**Output/Logs**

<details><summary>Click to expand</summary>

```

{#4205 // app/Support/HelpersFunctions.php:146
  +"message": "Failed to find class App\GraphQL\Scalars\EmailScalar extends GraphQL\Type\Definition\ScalarType in namespaces [App\Infra\GraphQL\Scalars] for the scalar Email."
  +"response": "não existe"
  +"path": "/v1/testing/US/graphql"
  +"exception_class": "Nuwave\Lighthouse\Exceptions\DefinitionException"
  +"file": "/home/worker/Projects/JML/connect/bff/vendor/nuwave/lighthouse/src/Schema/TypeRegistry.php"
  +"line": 360
}

```

</details></br>

**Lighthouse Version** 6.4

**Comment by spawnia** [comment]
Most likely you have not cleared your schema cache.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
