### ISSUE TITLE
Validate values in where conditions

### ISSUE THREAD

**Issue by jaulz** [nuwave/lighthouse#2383]
**What problem does this feature proposal attempt to solve?**

Right now, the values passed to where conditions are passed to the query builder without any further validation. I tried to add a validator directive to the query but since the generated types are recursive it's quite challenging and complex. 

**Which possible solutions should be considered?**

It would be great if we could pass a `validatorClass` to the `whereConditions` which again sets the `@validator` directive on the dynamically created `WhereConditionsInput` type. I am not sure if this has any implications or can cause any other issues?

**Comment by spawnia** [comment]
Have you tried `@searchBy` from https://github.com/LastDragon-ru/lara-asp/blob/master/packages/graphql/README.md#searchby-directive? Channeling @LastDragon-ru to inquire if you have solved this already.

**Comment by LastDragon-ru** [comment]
The `@searchBy` check only Types now (eg if the field is `Boolean` it is not possible to pass `String`). The value validation directives (eg `@rules("min:123")`) probably are not supported (yet) -> they will be filtered out while transformation (I've a task about it in my private list).

**Comment by jaulz** [comment]
That looks pretty cool, thank you both for your input! I will check out the package but as far as I can already see it would at least be feasible to use scalars as a minimum validation, right?

**Comment by LastDragon-ru** [comment]
> it would at least be feasible to use scalars as a minimum validation, right?

yep

**Comment by jaulz** [comment]
Thank you both for your super valuable help and of course for the packages (which are of excellent quality!) 😊
