### ISSUE TITLE
How to clear a single object using @clearCache

### ISSUE THREAD

**Issue by nguyentrongbang** [nuwave/lighthouse#2386]
Hello,

I start using caching feature in Laravel on my application, based on this tutorial:

https://lighthouse-php.com/master/performance/caching.html#clear-cache

My scheme like this:

```
type Query {
    song(id: ID! @eq): Song @find @cache
}

type Mutation {
    updateSong(input: UpdateSongInput! @spread): Song! @update @clearCache(type: "song", idSource: { argument: "input.id" })
}
```

Cache tagging is enabled:

config/lighthouse.php:
`'cache_directive_tags' => true`

But when I update a song, then I get the song detail, it returns the old data before updated. I'm trying to use some ways in the tutorial but not working:

```
@clearCache(type: "song", idSource: { argument: "input.id" })
@clearCache(type: "song", idSource: { field: "*.id" })
@clearCache(type: "song", idSource: { argument: "id" }, field: "title")
```

I've checked in redis, here is some keys are generated:

```
"laravel_cache:tag:lighthouse:Query::song:entries"

"a9e57fb373160c2aeff8e4e57de52c991c473141:lighthouse:Query::song:id:1"
"a9e57fb373160c2aeff8e4e57de52c991c473141:lighthouse:Query::song:id:2"
"a9e57fb373160c2aeff8e4e57de52c991c473141:lighthouse:Query::song:id:3"
```

I guest `laravel_cache:tag:lighthouse:Query::song:entries` is the tag key by the `song(id: ID! @eq): Song @find @cache`
and the three child keys are the single key  of three songs.

But how to clear a specific key - song in the mutation updateSong above?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
