### ISSUE TITLE
Overridden directives are not reflected in schema-directives.graphql

### ISSUE THREAD

**Issue by tminich** [nuwave/lighthouse#2396]
**Describe the bug**

I am overriding some of the default Lighthouse directives using Laravel container binding. This works fine when using GraphQL, but when I generate documentation via `artisan lighthouse:ide-helper`, the changes are not reflected in `schema-directives.graphql`.

**Expected behavior/Solution**

Since it works when running GraphQL-Queries (aka when the schema is resolved) it should also work when generating documentation.

**Steps to reproduce**

1. Override a Lighthouse directive via `app->bind()` changing the definition (e.g. adding a new parameter)
2. Generate documentation via `artisan lighthouse:ide-helper`
3. The definition in `schema-directives.graphql` does not reflect the changes.

**Lighthouse Version**

`v6.8.1`

**Comment by spawnia** [comment]
> Override a Lighthouse directive via app->bind() changing the definition (e.g. adding a new parameter)

That is not how you override Lighthouse directives, see https://lighthouse-php.com/master/custom-directives/getting-started.html#register-directives.
