### ISSUE TITLE
Example from Documentation results in error

### ISSUE THREAD

**Issue by Verox001** [nuwave/lighthouse#2397]
If you use the code from the documentation for directive interfaces (https://lighthouse-php.com/6/custom-directives/getting-started.html#directive-interfaces), it results in the following error:
```
Nuwave\\Lighthouse\\Pagination\\PaginatorField::dataResolver(): Argument #1 ($paginator) must be of type Illuminate\\Contracts\\Pagination\\Paginator, string given, called in app\\GraphQL\\Directives\\CamelToSnakeDirective.php on line 34
```

My code looks like this, but it should be the same from the documentation from how it works:
```
final class CamelToSnakeDirective extends BaseDirective implements FieldMiddleware
{
    // TODO implement the directive https://lighthouse-php.com/master/custom-directives/getting-started.html

    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'GRAPHQL'
directive @cts on FIELD_DEFINITION
GRAPHQL;
    }

    /**
     * Wrap around the final field resolver.
     *
     * @param FieldValue $fieldValue
     * @return void
     */
    public function handleField(FieldValue $fieldValue): void
    {
        $fieldValue->wrapResolver(fn (callable $resolver) => function (mixed $root, array $args, GraphQLContext $context, ResolveInfo $info) use ($resolver): string {
            // Call the resolver, passing along the resolver arguments
            $result = $resolver($root, $args, $context, $info); // Line 34
            assert(is_string($result));

            return strtoupper($result);
        });
    }
}
```

**Steps to reproduce**

1. Setup a Laravel Project with Lighthouse GraphQL
2. Write the directive code above
3. Add \App\GraphQL\Directives\CamelToSnakeDirective::class, to the 'field_middleware' in ``config/lighthouse.php``
4. Try to make any GraphQL Request

**Output/Logs**
```
Nuwave\\Lighthouse\\Pagination\\PaginatorField::dataResolver(): Argument #1 ($paginator) must be of type Illuminate\\Contracts\\Pagination\\Paginator, string given, called in app\\GraphQL\\Directives\\CamelToSnakeDirective.php on line 34
```

**Lighthouse Version**

Latest

**Comment by spawnia** [comment]
> Add \App\GraphQL\Directives\CamelToSnakeDirective::class, to the 'field_middleware' in config/lighthouse.php

That applies the directive to every field. The implementation needs to be more careful then.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
