### ISSUE TITLE
args removed from FieldDirective, how to migrate missing from UPGRADE.md

### ISSUE THREAD

**Issue by SlyDave** [nuwave/lighthouse#2398]
**Describe the bug**

A major change to the FieldDirective was done https://github.com/nuwave/lighthouse/pull/1706/files#diff-5b102fdcabf61f0a2caa6380f23fd2eb048b0f030a109ace359dfd95f6a96f14 that removes the args parameter 

There are no notes about this in the UPGRADE.md, what this change means and how it impacts things. 

Are args automatically passed now? if not, how does one pass them down to the resolver? 

**Expected behavior/Solution**

UPGRADE.md should mention the major change to the FieldDirective, how to handle it and how to change existing code using the args parameter of `@field` to be compatible with v6

e.g.:
What should the args of the following be replaced with?
```
currentAssignments(date: Date): [Assignment!]! @field(resolver: "App\\GraphQL\\Queries\\User\\CurrentAssignments", args:["date"])
```

**Comment by spawnia** [comment]
The purpose of `@field.args` was documented as `Supply additional data to the resolver.`. When you read the code in https://github.com/nuwave/lighthouse/pull/1706/files#diff-5b102fdcabf61f0a2caa6380f23fd2eb048b0f030a109ace359dfd95f6a96f14, you can see that it just added whatever value was defined in it as an extra argument `directive`.

Your example would have resulted in the following arguments being passed:

```php
[
  'date' => /* whatever represents your scalar Date */,
  'directive' => ['date'],
]
```

I think this makes very little sense, I saw no practical use case for this - the static data from the directive can just as well be placed in the resolver itself. In your case, just remove `args` and carry on.

**Comment by SlyDave** [comment]
Good to know, thanks!

Might be worth adding into the UPGRADE.md? As it is a change of the directive's usage that isn't mentioned, and if others are like me their IDE will highlight it as an error, and won't know why, what to do or why it changed.
