### ISSUE TITLE
Missed directive to clear private cache

### ISSUE THREAD

**Issue by LAGGOUNE-Walid** [nuwave/lighthouse#2399]
Example i have: 
```
Product { 
 id: Int! @cacheKey 
 isUserLikedMe: Int! @cache(private: true) 
} 
```

cache key is : 
```
lighthouse:auth:1:Product:10:isUserLikedMe
```

and mutation is : 
```
likeProduct(productId: Int!): Int!  @guard(with: "client-api") @field(resolver: "MySimpleResolver")
```

I don't see how i can clear the cache only for that user .

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
