### ISSUE TITLE
why not support graphiql

### ISSUE THREAD

**Issue by zhongjq** [nuwave/lighthouse#240]
is friendly for developer, why not support？

**Comment by maarten00** [comment]
GraphiQL is supported, but is not included with this package. You can use something like [this](https://github.com/Nohac/laravel-graphiql) to add GraphiQL to your Laravel application. 
Just point it to the GraphQL endpoint generated by Lighthouse, you can read the docs and run your queries like any other GraphiQL app.

**Comment by spawnia** [comment]
Hey, we are planning on adding info about this to the docs. I recommend https://github.com/mll-lab/laravel-graphql-playground which is an even better version of GraphiQL.

**Comment by morpheus7CS** [comment]
Since this has come up, I haven’t had any luck getting the schema to be pulled into Insomnia, GraphQl Playground or similar GraphQL clients. Has anyone experienced an issue like this before? 

Or am I doing something wrong by pointing it to 127.0.0.1:8000/graphql? Haven’t touched the default settings file.

**Comment by zhongjq** [comment]
Yes, i use graphql playground client work best, tks

**Comment by maarten00** [comment]
>Since this has come up, I haven’t had any luck getting the schema to be pulled into Insomnia, GraphQl Playground or similar GraphQL clients. Has anyone experienced an issue like this before?

It should work with any client. Insomnia shows a tooltip on the bottom if anything goes wrong. But your best bet would be checking the error log in your Laravel app if it doesn't work, because there is probably something wrong with your GraphQL endpoint.
