### ISSUE TITLE
Why making  http request  in log file I see slashed string ?

### ISSUE THREAD

**Issue by sergeynilov** [nuwave/lighthouse#2400]
Making  http request in laravel 9 / nuwave/lighthouse 6.6 app I got error on valid request string:

```
        $request = '



    mutation {
        register(
            input:
               {
                     username:"dummy",
                     email:"dummy@example.com",
                     password:"test_pass"
                     password_confirmation:"test_pass"
               }
        )
				{
                id
                username
                email
                status
                created_at
         }
    }

        ';
        $response = $this->graphQL( $request );

```
and in log file I see slashed string :
```
[2023-05-21 09:56:53] testing.INFO: Received GraphQL query. {"query":"mutation {
        register(
            input:
               {
                     username:\"dummy\",
                     email:\"dummy@example.com\",
                     password:\"test_pass\",password_confirmation:\"test_pass\"
               }
        )
\t\t\t\t{
                id
                username
                email
                status
                created_at
         }
    }"} 
    
```
I suppose reason of this error is that string is slashed, but why it is slashed and how that can be fixed?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
