### ISSUE TITLE
AuthError on pusher subscription on Soketi

### ISSUE THREAD

**Issue by handhikadj** [nuwave/lighthouse#2410]
**Describe the bug**
I'm using Soketi as the Websocket server but not sure why lighthouse cannot be authenticated.
it shows:
```
data: {
    event: 'pusher:subscription_error',
    channel: 'private-lighthouse-xy9SBCQjqcARfoJlIOVs445jOSehc4ez-1686552792',
    data: {
      type: 'AuthError',
      error: 'The connection is unauthorized.',
      status: 401
    }
  }
```

**Expected behavior/Solution**

**Steps to reproduce**

1. go to https://github.com/handhikadj/lighthouse-repro-vue & https://github.com/handhikadj/lighthouse-repro-api and clone it
2. make sure you have Soketi installed on your machine. Run it if you had it
3. install both projects like you install vue & laravel project (separately) . there are .env.example files on each project. on https://github.com/handhikadj/lighthouse-repro-vue repo's .env, replace the http://lighthouse-repro-api.test values with the backend domain of lighthouse-repro-api. 
4. if you finish set it up, run `npm run dev`  on the vue project. open the url on the browser. see the WS log of the network tab and Soketi log on your terminal

**Output/Logs**

<details open><summary>Click to expand</summary>

```
 data: {
    event: 'pusher:subscription_error',
    channel: 'private-lighthouse-t2vqeKu42wkzhEm1FPkZph6E8zpUn3iw-1686553143',
    data: {
      type: 'AuthError',
      error: 'The connection is unauthorized.',
      status: 401
    }
  }
```

</details></br>

**Lighthouse Version**

5.71.0

**Comment by spawnia** [comment]
Try Lighthouse 6.

**Comment by handhikadj** [comment]
@spawnia 
thank you for responding very quickly. will try that.

anyway, I slightly modified my post from https://github.com/handhikadj/lighthouse-repro-vue to https://github.com/handhikadj/lighthouse-repro-api on the first point of steps to reproduce

**Comment by spawnia** [comment]
It would be great if you can narrow the error down to a failing test case in https://github.com/nuwave/lighthouse/tree/master/tests/Integration/Subscriptions and add a pull request. I never really used subscriptions and am not willing to invest the time to work with your reproduction repositories.

**Comment by melnikanton** [comment]
@spawnia 

any reference how to setup the Subscription test case?
