### ISSUE TITLE
Throw explicit error when relation directives fail to detect laravel relation.

### ISSUE THREAD

**Issue by b-strauss** [nuwave/lighthouse#2411]
**What problem does this feature proposal attempt to solve?**

I had a nasty bug recently where I was using a third party package with laravel models. Unfortunately that package has not annotated the relations of their models with return types. This caused lighthouse to not detect the relations properly, and it tried to insert a relation directly as a column in the model itself instead of setting the relation via the relation table.

The only error message I got was `Internal server error: Array to string conversion` when it tried to insert the `@belongsToMany` relation as column value.

I solved it by subclassing and overwriting the relation methods with the correct return types.

**Which possible solutions should be considered?**

Lighthouse should throw explicit errors when the type for a model declares a relation, but the relation on the model could not be detected or mismatches.

**Comment by spawnia** [comment]
Without the return types, Lighthouse can not really know if a field is supposed to correlate to a relation. A method with the same name may be something entirely unrelated or an attribute cast.

**Comment by spawnia** [comment]
In that case, the return type is not necessary - it is only needed for inputs.

**Comment by spawnia** [comment]
See https://lighthouse-php.com/master/eloquent/nested-mutations.html#return-types-required.
