### ISSUE TITLE
@guard directive in fields but I always get "Unauthenticated" error.

### ISSUE THREAD

**Issue by isaacdarcilla** [nuwave/lighthouse#2417]
**Describe the bug**

I'm trying @guard directive in fields but I always get "Unauthenticated" error. I followed the docs here https://lighthouse-php.com/6/security/authentication.html#laravel-sanctum and XCRF Token https://github.com/mll-lab/laravel-graphiql#configure-session-authentication

I am using sanctum for auth

**Expected behavior/Solution**

Should be able to fetch data

**Output/Logs**

Schema

![image](https://github.com/nuwave/lighthouse/assets/22732118/9ce4ff63-b222-412b-ace4-680f447ccb4f)

Query Postman and GraphiQL

![image](https://github.com/nuwave/lighthouse/assets/22732118/d3b3a830-f5c2-44f6-9d6a-81b3e3814c3e)

![image](https://github.com/nuwave/lighthouse/assets/22732118/65af6bbf-980c-4905-9a32-3556353c541a)

Lighthouse config

```
'route' => [
        // ...
        'middleware' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,

            // ... other middleware
        ],
    ],
    'guards' => ['sanctum'],
```

**Lighthouse Version**

6.12

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
