### ISSUE TITLE
I faced issue lighthouse middleware

### ISSUE THREAD

**Issue by nikhilucodesoft** [nuwave/lighthouse#2420]
Target class [Nuwave\Lighthouse\Support\Http\Middleware\AcceptJson] does not exist.

I am getting the above error I cleared cache also can you suggest why getting the error 

My composer.json file 
{
    "name": "bagisto/bagisto",
    "description": "Bagisto Laravel E-Commerce",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^8.1",
        "ext-calendar": "*",
        "ext-curl": "*",
        "ext-intl": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "ext-pdo": "*",
        "ext-pdo_mysql": "*",
        "ext-tokenizer": "*",
        "astrotomic/laravel-translatable": "^11.0.0",
        "bagisto/graphql-api": "dev-main",
        "bagisto/laravel-datafaker": "^2.0@alpha",
        "bagisto/legacy-api": "^1.0",
        "bagisto/rest-api": "dev-master",
        "bagistobrasil/bagisto-product-social-share": "^0.1.2",
        "barryvdh/laravel-dompdf": "^2.0.0",
        "cviebrock/laravel-elasticsearch": "^10.0",
        "diglactic/laravel-breadcrumbs": "^7.0",
        "doctrine/dbal": "^2.9",
        "enshrined/svg-sanitize": "^0.15.0",
        "fakerphp/faker": "^1.14",
        "flynsarmy/db-blade-compiler": "dev-master",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.4",
        "intervention/imagecache": "^2.5.2",
        "kalnoy/nestedset": "^6.0",
        "khaled.alshamaa/ar-php": "^6.0.0",
        "konekt/concord": "^1.2",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.12",
        "laravel/scout": "^9.0",
        "laravel/socialite": "^5.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
        "maatwebsite/excel": "^3.1.26",
        "paypal/paypal-checkout-sdk": "1.0.1",
        "prettus/l5-repository": "^2.6",
        "pusher/pusher-php-server": "^7.0",
        "spatie/laravel-ignition": "^1.0",
        "spatie/laravel-sitemap": "^6.1",
        "taxjar/taxjar-php": "^2.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.1",
        "codeception/codeception": "*@dev",
        "codeception/module-asserts": "^3.0.0",
        "codeception/module-filesystem": "^3.0.0",
        "codeception/module-laravel": "*@dev",
        "codeception/module-rest": "^3.0.0",
        "codeception/module-webdriver": "^3.0.0",
        "filp/whoops": "^2.0",
        "laravel/pint": "^1.8",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0"
    },
    "replace": {
        "bagisto/laravel-user": "v0.1.0",
        "bagisto/laravel-admin": "v0.1.0",
        "bagisto/laravel-ui": "v0.1.0",
        "bagisto/laravel-core": "v0.1.0",
        "bagisto/laravel-attribute": "v0.1.0",
        "bagisto/laravel-checkout": "v0.1.0",
        "bagisto/laravel-customer": "v0.1.0",
        "bagisto/laravel-inventory": "v0.1.0",
        "bagisto/laravel-category": "v0.1.0",
        "bagisto/laravel-product": "v0.1.0",
        "bagisto/laravel-shop": "v0.1.0",
        "bagisto/laravel-theme": "v0.1.0",
        "bagisto/laravel-shipping": "v0.1.0",
        "bagisto/laravel-payment": "v0.1.0",
        "bagisto/laravel-sales": "v0.1.0",
        "bagisto/laravel-tax": "v0.1.0",
        "bagisto/laravel-api": "v0.1.0",
        "bagisto/laravel-paypal": "v0.1.0",
        "bagisto/laravel-discount": "v0.1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Webkul\\User\\": "packages/Webkul/User/src",
            "Webkul\\Admin\\": "packages/Webkul/Admin/src",
            "Webkul\\Ui\\": "packages/Webkul/Ui/src",
            "Webkul\\Category\\": "packages/Webkul/Category/src",
            "Webkul\\Checkout\\": "packages/Webkul/Checkout/src",
            "Webkul\\Attribute\\": "packages/Webkul/Attribute/src",
            "Webkul\\Shop\\": "packages/Webkul/Shop/src",
            "Webkul\\Core\\": "packages/Webkul/Core/src",
            "Webkul\\Customer\\": "packages/Webkul/Customer/src",
            "Webkul\\Inventory\\": "packages/Webkul/Inventory/src",
            "Webkul\\Product\\": "packages/Webkul/Product/src",
            "Webkul\\Theme\\": "packages/Webkul/Theme/src",
            "Webkul\\Shipping\\": "packages/Webkul/Shipping/src",
            "Webkul\\Payment\\": "packages/Webkul/Payment/src",
            "Webkul\\Paypal\\": "packages/Webkul/Paypal/src",
            "Webkul\\Sales\\": "packages/Webkul/Sales/src",
            "Webkul\\Tax\\": "packages/Webkul/Tax/src",
            "Webkul\\CatalogRule\\": "packages/Webkul/CatalogRule/src",
            "Webkul\\CartRule\\": "packages/Webkul/CartRule/src",
            "Webkul\\Rule\\": "packages/Webkul/Rule/src",
            "Webkul\\CMS\\": "packages/Webkul/CMS/src",
            "Webkul\\Velocity\\": "packages/Webkul/Velocity/src",
            "Webkul\\BookingProduct\\": "packages/Webkul/BookingProduct/src",
            "Webkul\\SocialLogin\\": "packages/Webkul/SocialLogin/src",
            "Webkul\\DebugBar\\": "packages/Webkul/DebugBar/src",
            "Webkul\\Marketing\\": "packages/Webkul/Marketing/src",
            "Webkul\\Notification\\": "packages/Webkul/Notification/src",
            "Webkul\\Sitemap\\": "packages/Webkul/Sitemap/src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\Functional\\": "tests/functional/",
            "Tests\\Unit\\": "tests/unit/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
                "laravel/dusk"
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate",
            "Webkul\\Core\\Events\\ComposerEvents::postCreateProject"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "test": [
            "set -e",
            "@php artisan migrate:fresh --env=testing",
            "vendor/bin/codecept run unit",
            "vendor/bin/codecept run functional",
            "vendor/bin/codecept run api"
        ],
        "test-win": [
            "@set -e",
            "@php artisan migrate:fresh --env=testing",
            "vendor\\bin\\codecept.bat run unit",
            "vendor\\bin\\codecept.bat run functional"
        ]
    },
    "config": {
        "preferred-install": "stable",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "support": {
        "issues": "https://github.com/bagisto/bagisto/issues",
        "forum": "https://forums.bagisto.com",
        "source": "https://github.com/bagisto/bagisto",
        "docs": "https://devdocs.bagisto.com"
    }
}

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
