### ISSUE TITLE
NOT_LIKE operator not working

### ISSUE THREAD

**Issue by nguyentrongbang** [nuwave/lighthouse#2427]
**Describe the bug**
When using NOT_LIKE operator, it returns empty result.

Query:
```
query {
  songs(
    first: 5
    where: {AND: [{column: "title", operator: NOT_LIKE, value: "Bài ca đi cùng năm tháng%"}]}
  ) {
    data {
      id
      slug
      title
    }
  }
}
```
Result:
```
{
  "data": {
    "songs": {
      "data": []
    }
  }
}
```

**Expected behavior/Solution**

It should return non empty result

**Steps to reproduce**

Just use NOT_LIKE operator in the query

**Output/Logs**

Here is the mysql log:

```
DB::listen(function($query) {
           Log::info(
               $query->sql,
               $query->bindings
           );
       });
```

```
select * from `song` where (`title` = ?) and `song`.`deleted_at` is null limit 6 offset 0 ["NOT_LIKE"] 
```

</details></br>

**Lighthouse Version**
6.6.0

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v6.16.2.
