### ISSUE TITLE
Directives for root types

### ISSUE THREAD

**Issue by WordsofDefiance** [nuwave/lighthouse#2435]
I'll help develop it if I can.

**What problem does this feature proposal attempt to solve?**
I have a multi-tenancy issue with graphql. I'd like to support two apps with two separate user drivers using the same graphql endpoint. However, I need to limit authorization for resolvers between different apps. Users of App A can access all resolvers, and users of App B may only access a subset of all resolvers.

The issue is that once a user passes the middleware, they can access any of the resolvers on the graphql endpoint. We can use directives to siphon off individual groups of queries and resolvers like so: 

```
extend type Mutation @canAccess(app1: [rights], app2: [rights]) {
    mutation1
    mutation2
}

```

However, this requires us to add the custom directive to every single resolver. We break up our resolvers into multiple files and directories, so our `schema.graphql` file looks like this:

```
"A date string with format `Y-m-d`, e.g. `2011-05-23`."
scalar Date @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Date")

"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

#import interfaces/*.graphql

#import types/*.graphql

type Mutation
type Query

#import resolvers/*.graphql

#import queries.graphql
```

We'd like to apply our rights-checking `canAccess` directive to ALL resolvers by default. So if we could add directives to the base types in the `schema.graphql` file, we could add directives globally. 

Desired behavior:

```
schema.graphql

type Mutation @canAccess(app1: true, app2: false)
```

The directive should be overridden by subsequent declarations: 

```
extend type Mutation {
    createUser @canAccess(app1: true, app2: true) // app2 users can access
}
```

**Which possible solutions should be considered?**

Making directives applicable to the root types, while maintaining the current hierarchy, should solve this.

**Comment by spawnia** [comment]
> We'd like to apply our rights-checking canAccess directive to ALL resolvers by default.

See https://github.com/nuwave/lighthouse/blob/c28822acdb675ce3be99339c8bebf243bf0666e3/src/lighthouse.php#L251-L271.

**Comment by WordsofDefiance** [comment]
@spawnia thanks for your response. How would I list a directive here that requires arguments?

**Comment by spawnia** [comment]
Not possible, you can use inheritance and bake the values into the class you use.
