### ISSUE TITLE
`@in` directive breaks if client sends null

### ISSUE THREAD

**Issue by MissaelAnda** [nuwave/lighthouse#2444]
The `@in` directive doesn't handle the possible case where the field is nullable and the client sends `null`.

The solution could be adding a null coalesce in `InDirective.php` from lines 30 - 33:
```php
        return $builder->whereIn(
            $this->directiveArgValue('key', $this->nodeName()),
            $value ?? [],
        );
```

Error when sending null: `TypeError  count(): Argument #1 ($value) must be of type Countable|array, null given.`

Lighthouse Version: v6.18.0

**Comment by spawnia** [comment]
I do not agree with the proposed solution, passing `null` should be equivalent to not sending the argument value at all. Fixing this in https://github.com/nuwave/lighthouse/pull/2445.

Please consider sponsoring.
