### ISSUE TITLE
Best practices link in documentation is broken

### ISSUE THREAD

**Issue by williamjallen** [nuwave/lighthouse#2458]
The documentation links to a graphql best practices site in [this](https://lighthouse-php.com/master/the-basics/best-practices.html#best-practices) section.  That site appears to have been hacked, and should be removed from the documentation.

**Comment by williamjallen** [comment]
It appears to be unavailable due to some sort of SSL issue, but if you attempt to access the site over HTTP you get redirected to a series of unexpected sites...

Linking to the docs sounds like a great temporary workaround.

**Comment by k0ka** [comment]
Yep, the domain might be dead and already seized by some 3rd party. 

https://who.is/whois/graphql-rules.com

```
Registered On 2023-09-02
Updated On 2023-09-10
```

**Comment by k0ka** [comment]
We might change the link to their github repo https://github.com/graphql-rules/graphql-rules/tree/master/docs/rules .
It looks pretty decent

**Comment by spawnia** [comment]
Alright, can you send a pull request?
