### ISSUE TITLE
[URGENT] Lighthouse Auth AuthServiceProvider::guards() Return value must be of type array, string returned

### ISSUE THREAD

**Issue by titoff002** [nuwave/lighthouse#2461]
![image](https://github.com/nuwave/lighthouse/assets/24948237/315bfd5e-4bab-4ffe-ab0f-a5c9b7f31815)

**Laravel conf**
![image](https://github.com/nuwave/lighthouse/assets/24948237/1eb61cd9-4fae-4852-92ee-79a810a1dcae)

When execute muitation, i have this error : 

Nuwave\\Lighthouse\\Auth\\AuthServiceProvider::guards(): Return value must be of type array, string returned

how to fix this problem ?

Thanks to you.

Good Day.

**Comment by k0ka** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
