### ISSUE TITLE
Add filter in sub query

### ISSUE THREAD

**Issue by isaacdarcilla** [nuwave/lighthouse#2466]
```json
query getPackage($slug: String!) {
            getPackage(slug: $slug) {
                id
                user_id
                package_type_id
                name
                slug
                packageLibraries {
                    id
                    library {
                        id
                        libraryLessons(filter: { lesson: { status: { _eq: "published" } } }) {
                            id
                            lesson {
                                id
                                title
                                description
                                tags
                                status
                            }
                        }
                    }
                }
            }
        }
```

How to add subquery in lesson? Basically I want to filter the lesson with published status only.

schema
type Library {
    id: ID!
    user_id: String!
    name: String
    description: String
    created_at: DateTime!
    updated_at: DateTime!
    deleted_at: DateTime
    user: User
    libraryLessons: [LibraryLesson]
    libraryResources: [LibraryResource]
    libraryCommunityTimelines: [LibraryCommunityTimeline]
    libraryCommunityChats: [LibraryCommunityChat]
}

type LibraryLesson {
    id: ID!
    library_id: String!
    lesson_id: String!
    created_at: DateTime!
    updated_at: DateTime!
    deleted_at: DateTime
    lesson: Lesson
}

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
