### ISSUE TITLE
Automatic creation of schemas types and queries

### ISSUE THREAD

**Issue by sefirosweb** [nuwave/lighthouse#2467]
Guys, any easy way to automatically create the queries / types of the Laravel eloquent?

I have around 50 models and it is annoying to have to create the "basic" types and queries 1 by 1 (find, get_all, get_withpagination)"

It also helps to automatically modify the schema when modifying Laravel fields.

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
