### ISSUE TITLE
If the ListType field is not present, the rule directive is applied to the array itself.

### ISSUE THREAD

**Issue by naotake51** [nuwave/lighthouse#2488]
**Describe the bug**

If the ListType field is not present, the rule directive is applied to the array itself.

I expect the rules directive for ListType Field to always apply to array elements.

**Expected behavior/Solution**

the solution I think

https://github.com/nuwave/lighthouse/blob/v6.28.0/src/Validation/RulesGatherer.php#L63-L72

rewrite to

```php
            if (
                $argument->type instanceof ListType
            ) {
                if (is_array($argument->value)) {
                    foreach ($argument->value as $index => $value) {
                        $this->handleArgumentValue($value, $directivesForArgument, array_merge($nestedPath, [$index]));
                    }
                }
            } else {
                $this->handleArgumentValue($argument->value, $directivesForArgument, $nestedPath);
            }
```

**Steps to reproduce**

1. Define a ListType field with a rules directive.

```graphql
deleteHoges(
    ids: [ID!] @rules(apply: ["required", "uuid"])
): [Hoge!]!
```

2. Run the query without filling out the ListType field.

```graphql
mutation {
    deleteHoges {
        id
    }
}
```

3.  The following validation rule is created and an error occurs

```php
["ids" => ["Required", "Uuid"]]
```
expected ListType rules derective apply to array elements

```php
["ids.0" => ["Required", "Uuid"]]
```

**Lighthouse Version**

v6.22.0

**Comment by spawnia** [comment]
The proposed solution looks fine. Can you add a pull request? Please start with a failing test case, probably in `RulesDirectiveTest`.

**Comment by naotake51** [comment]
@spawnia 

https://github.com/nuwave/lighthouse/pull/2489

I created it here.

Please let me know if you have any problems.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v6.29.1. Please consider sponsoring.
