### ISSUE TITLE
Generate schema fail!

### ISSUE THREAD

**Issue by pvhuy84** [nuwave/lighthouse#2490]
I tried to generate schema with the command: `php artisan lighthouse:print-schema`
But it got an error: 
```
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Filesystem\FilesystemManager
```

I am using lighthouse in my laravel lumen project. thanks!

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
