### ISSUE TITLE
Clear Cache (private)

### ISSUE THREAD

**Issue by LrMiLoef** [nuwave/lighthouse#2494]
In my project i have declared following query:

`applications: [Application]
        @cache(private: true, maxAge: 3600)`

Now i want to clear the cache for all users when an specific mutation was executed:

`updateApplication(input: UpdateApplicationInput!): Boolean
        @clearCache(type: "Query", field: "applications")`

In the backend the application has been updated, but the result of the applications-query has still the old state from before executing the mutation. When i don't use the private option, everything works as expected. The Problem is, that i have to use the private option here. 

So what's the trick to clear all the private cached results for the applications-query?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
