### ISSUE TITLE
@canFind is missing "model" argument in graphql definition

### ISSUE THREAD

**Issue by rocket-micha** [nuwave/lighthouse#2513]
**Describe the bug**

`@canFind` (introduced in #2483) [uses a model argument](https://github.com/nuwave/lighthouse/blob/d3b4df3221e3127b026f05c132807329b28a0e49/src/Auth/CanFindDirective.php#L75), which is not part of the graphql definition. This leads to a validation error (in phpstorm for example) when using `@canFind()`

<img width="554" alt="image" src="https://github.com/nuwave/lighthouse/assets/158499163/2eef3fed-7dcf-44b2-aa88-95ec8e829ae4">

**Expected behavior/Solution**

Argument "model" should part of the graphql definition / validation should pass

**Steps to reproduce**

1. use `@canFind` directive
2. see validation error in graphql schema files after generating lighthouse's ide-helper class

**Lighthouse Version**

6.29.1

P.S.: would be great to get a new bugfix release after this got merged as i'm waiting for this and #2507 :)

**Comment by k0ka** [comment]
`@canFind` uses model of the underlying object (which it is applied to).

See https://lighthouse-php.com/6/security/authorization.html#restrict-fields-through-policies
