### ISSUE TITLE
Problem with subscription middleware

### ISSUE THREAD

**Issue by ivanhuk** [nuwave/lighthouse#2519]
I have a problem with laravel passport:

```
type Subscription @middleware(checks: ["auth:api"]) {    
    taskUpdated(projectId: ID!, id: ID!): Task 
        @subscription(class: "App\\GraphQL\\Subscriptions\\TaskUpdated")
}
```
**$subscriber->context->user ** always returns null 
```
final class TaskUpdated extends GraphQLSubscription
{
    public function authorize(Subscriber $subscriber, Request $request): bool
    {

        dd($subscriber->context->user);

        return true;
    }
}
```
here front-end part
```
import LocalStorage from '@config/localStorage';
import { setContext } from '@apollo/client/link/context';
import { ApolloClient, InMemoryCache } from '@apollo/client';
import { createUploadLink } from 'apollo-upload-client';
import { ApolloLink } from "apollo-link";
import Pusher from "pusher-js";
import PusherLink from 'apollo-pusher-link';

const pusherLink = new PusherLink({
    pusher: new Pusher('---------', {
        cluster: 'eu',
        authEndpoint: `/graphql/subscriptions/auth`,
        auth: {
            headers: {
                Authorization: `Bearer ${localStorage.getItem(LocalStorage.token)}`
            },
        },
    
    })
})

const authLink = setContext((_, { headers }) => {

    const token = localStorage.getItem(LocalStorage.token);

    return {
        headers: {
            ...headers,
            authorization: token ? `Bearer ${token}` : "",
            'Content-Language': _sharedData.locale
        }
    }
});

const uploadLink = createUploadLink({
    uri: (operation) => '/graphql?' + operation.operationName,
    headers: { "keep-alive": "true" }
});


const client = new ApolloClient({
    cache: new InMemoryCache({ addTypename: false }),
    link: ApolloLink.from([authLink,
        pusherLink,
        uploadLink]),
});



export default client;
```
here result of requests:
<img width="1058" alt="Screenshot 2024-02-26 at 22 14 09"  src="https://github.com/nuwave/lighthouse/assets/122692099/01fa7e58-0f14-4cf3-b9e7-3d59e7c8262e">
<img width="534" alt="Screenshot 2024-02-26 at 22 14 17" src="https://github.com/nuwave/lighthouse/assets/122692099/7871652e-a61a-4434-8af4-aca157432e3a">

**Comment by stayallive** [comment]
How have you set your [`guards`](https://github.com/nuwave/lighthouse/blob/cd94193e30b4e38096ef533ca4e1cb8fd64ee46d/src/lighthouse.php#L64) config option? I'm assuming from the `@middleware` that you don't have that set or it's not set to `api`. Try changing it to `api` so Ligthouse uses the correct guard.

I would also advise you to use `@guard` (instead of `@middleware`) to make sure only authenticated users are accessing the field, read more about this here: https://lighthouse-php.com/6/security/authentication.html#configure-the-guard.

**Comment by ivanhuk** [comment]
> How have you set your [`guards`](https://github.com/nuwave/lighthouse/blob/cd94193e30b4e38096ef533ca4e1cb8fd64ee46d/src/lighthouse.php#L64) config option? I'm assuming from the `@middleware` that you don't have that set or it's not set to `api`. Try changing it to `api` so Ligthouse uses the correct guard.
> 
> I would also advise you to use `@guard` (instead of `@middleware`) to make sure only authenticated users are accessing the field, read more about this here: https://lighthouse-php.com/6/security/authentication.html#configure-the-guard.

I solved the problem.
this is due to the fact that I used multytenancy, and the system searched for an authorization token in the central database, but it should have searched in the tenant database, because of this, I could not understand why the user was not authorized when sending the token
