### ISSUE TITLE
Enum Support for Morph Types

### ISSUE THREAD

**Issue by skaesdorf** [nuwave/lighthouse#2543]
Hi, currently we are switching a larger project from BenSampo/laravel-enum to native php enums. Now I'm facing the Issue that many nested morph relations wont work anymore since we use Enums for the morph type declaration in our schema. These enums are backed in php by BackedEnums which map to the acutal class name.

```php
enum LinkableType: string
{
    case LIVESTREAM = Livestream::class;
    case VOD        = Vod::class;
}
```

```graphql
input LinkableMorphInput
{
    type: LinkableType!
    id: ID!
}
```

BenSampo/laravel-enums are stringable and resolve to their value when casted to a string. Because of that the NestedMorphTo ArgResolver works fine. Now, when using native enums, casts to string are no longer possible since native enums are not stringable. This results in an error in e.g. the NestedMorphTo ArgResolver:

```php
//nuwave/lighthouse/src/Execution/Arguments/NestedMorphTo.php

$morphToModel = $this->relation->createModelByType(
    (string) $connectArgs->arguments['type']->value,
    //arguments['type']->value is a BackedEnum, this results in:
    //Object of class App\Enums\LinkableType could not be converted to string
);
```

Since Laravel already supports native Enums in many cases like QueryBuilder or Eloquent it seems consistent to me to support them in lighthouse's morph relations.

I would be happy to submit a PR if this is a desirable feature.

Cheers
Stefan

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v6.36.1.
