### ISSUE TITLE
Detection of incorrect type usage in input, or vice versa

### ISSUE THREAD

**Issue by webard** [nuwave/lighthouse#2593]
One common problem is incorrect use of Type in Input.

E.g. in my schema, phone number has `Phone` type which provides more info about phone number, like country, number type etc. and that data is provided by casting phone number to object in Model.

But in `Input` should be used scalar `E164`, which is string in E.164 format.

Unfortunalely there are some situations where people use `Phone` type in `Input`, what causes an unreadable error during `lighthouse:validate-schema`:

```
 AssertionError 

 assert($type instanceof Type && $type instanceof InputType)
 at vendor/nuwave/lighthouse/src/Schema/Factories/ArgumentFactory.php:52
```

**Which possible solutions should be considered?**

It would be ideal if the validator could point out where the mistake is in such a case.

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v6.42.1. Please consider sponsoring.
