### ISSUE TITLE
ConvertEmptyStringsToNullDirective not executed when applied on fields where the argument is an input type

### ISSUE THREAD

**Issue by dennis-koster** [nuwave/lighthouse#2610]
**Describe the bug**
The `ConvertEmptyStringsToNullDirective` is not executed when it is applied globally or to an input, where the expected behaviour would be that it would apply the conversion recursively. It appears to me that [this change](https://github.com/nuwave/lighthouse/commit/36a7204a3713e71f44eaddd5ea3a56a5985fa224) has introduced this bug, because the [added if check](https://github.com/nuwave/lighthouse/commit/36a7204a3713e71f44eaddd5ea3a56a5985fa224#diff-be77b5ba04246a0e81523bcab606a0bd3ce895caf5c430dc6ce966133b9f926eR62) now makes it so that the sanitize method is only applied if the type of input is a string, negating the intended recursive nature.

**Expected behavior/Solution**
The directive should be executed when applied to an input or globally, as described in [the documentation](https://lighthouse-php.com/6/api-reference/directives.html#convertemptystringstonull).

**Steps to reproduce**

Given the following schema:
```gql
extend type Mutation @guard {
    updateMe(input: UpdateMeInput): User!
        @field(resolver: "App\\GraphQL\\Mutations\\UpdateMe")
}

input UpdateMeInput {
    firstName: String @rules(apply: ["filled"])
    insertion: String @rules(apply: ["nullable"])
    lastName: String @rules(apply: ["filled"])
}
```

Execute the following mutation:
```gql
updateMe(input: {
    insertion: "",
}) {
    insertion
}
```
Expected outcome would be for the `insertion` attribute to be converted to null in the following scenarios:
1.`\Nuwave\Lighthouse\Schema\Directives\ConvertEmptyStringsToNullDirective::class,` is added to the `field_middleware` array in the `lighthouse.php` configuration file.
2. The directive is applied to the input as such:
```gql
extend type Mutation {
    updateMe(input: UpdateMeInput): User! @convertEmptyStringsToNull
        @field(resolver: "App\\GraphQL\\Mutations\\UpdateMe")
}
```

**Lighthouse Version**
`v6.43.1`

**Comment by spawnia** [comment]
Can you add provide a pull request with a failing test case?

**Comment by dennis-koster** [comment]
@spawnia Let me know if this is sufficient for you to reproduce the error: https://github.com/nuwave/lighthouse/pull/2611.

It seems like situations where @field is used are not covered.

**Comment by spawnia** [comment]
The issue in your tests was that `@convertEmptyStringsToNull` does not apply to non-nullable inputs when used on fields, see https://github.com/nuwave/lighthouse/pull/2611/commits/5ee83d57df019452e5cf3f21365de0b4a22b5ba4. I improved the docs for this in https://github.com/nuwave/lighthouse/commit/45e1cbbc9459f38e79cff24b3c9ec4a513ab368b.

Please let me know if there is another issue, and please consider sponsoring.
