### ISSUE TITLE
Failed to find class ProgramPaginator in namespaces [App, App\\Models]

### ISSUE THREAD

**Issue by nguyentrongbang** [nuwave/lighthouse#2616]
Here is my schema.graphql:

```
programs(
    where: WhereConditions @whereConditions
    orderBy: [OrderByClause!] @orderBy
  ): [Program!]!
    @paginate(
      defaultCount: 10
      builder: "App\\GraphQL\\Builders\\MyProgramsBuilder"
    )
    @can(ability: "listPrograms")

type Program {
  id: ID!
  name: String
  type: String
  content: String
  text_voice: String
  text_content: String
  dfm_channel: String
  dfm_url: String
  vbee_audio_link: String
  vbee_hash: String
  aux_id: ID
  file_id: ID
  user_id: ID
  created_at: DateTime
  updated_at: DateTime
  file: File @belongsTo
  encoder: Device @belongsTo
  user: User @belongsTo
  location: Location @belongsTo
}
```

**Describe the bug**

Here is debug message:

`"Failed to find class ProgramPaginator in namespaces [App, App\\Models] for directive @can."`

If I remove the line:

`builder: "App\\GraphQL\\Builders\\MyProgramsBuilder"`

it works fine.

I think the name "Program" has the problem. (the others work fine, ex: Schedule, User, Broadcast, Device..)

**Expected behavior/Solution**

This should not show the error.

**Steps to reproduce**

```
programs(first: 10, page: 1, orderBy: [{column: "id", order: DESC}]) {
        data {
          id
          name
          type
        }
        paginatorInfo {
          total
          currentPage
          lastPage
        }
      }
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

6.44.2 (latest version)

**Comment by spawnia** [comment]
Read https://lighthouse-php.com/master/api-reference/directives.html#can-family-of-directives, my guess is you will need `@canModel(model: "Program")`. Using `@paginate(builder: ` causes the default model detection to not work.
