### ISSUE TITLE
Subscription with echo AuthError pusher:subscription_error

### ISSUE THREAD

**Issue by Stevemoretz** [nuwave/lighthouse#2622]
**Describe the bug**

```json
{
  "channel": "private-lighthouse-xmLISs3gzebsE8QtN6B0y10zYuNjzrUJ-1728925422",
  "data": {
    "type": "AuthError",
    "error": "The connection is unauthorized.",
    "status": 401
  },
  "error": "The connection is unauthorized.",
  "status": 401,
  "type": "AuthError",
  "event": "pusher:subscription_error"
}
```

**Expected behavior/Solution**

**Steps to reproduce**

1. Following the official guide, will just give us this error. Notice that the current js library doesn't even work without with my pull request so apply that first: https://github.com/thekonz/apollo-lighthouse-subscription-link/pull/28
2. Send a subscription request, watch your browser's network tab, under websocket connections you'll see the provided error.

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Lighthouse Version**

6.45

**Comment by Stevemoretz** [comment]
I don't know why you did EchoBroadcaster return that result for auth request, but changing the signature to your PusherBroadcaster fixes that:

https://github.com/nuwave/lighthouse/pull/2623

I didn't write any tests or change anything else since I have no idea about your intentions of returning the result like the way you are right now.

**Comment by spawnia** [comment]
Conjuring @thekonz 😉

**Comment by thekonz** [comment]
I made that package and the echo broadcaster, because I was using laravel-echo-server instead of pusher. This is usually either done for privacy or cost reasons.

So that `getPusher` call just seems wrong.

You can use the echo client, but connect to pusher using the echo subscription broadcaster.

**Comment by Stevemoretz** [comment]
> I made that package and the echo broadcaster, because I was using laravel-echo-server instead of pusher. This is usually either done for privacy or cost reasons.
> 
> So that `getPusher` call just seems wrong.
> 
> You can use the echo client, but connect to pusher using the echo subscription broadcaster.

Thanks for the reply, I'm not using pusher, as a matter of fact my server is supposed to run locally without any internet, I'm using a pusher compatible server that laravel suggests:"soketi".

Also laravel echo server, doesn't seem to be maintained anymore.

In any case, I'd say it makes sense to support pusher as well, you might want to support both, by specifying an option and a simple if statement between my code and yours.

**Comment by thekonz** [comment]
If you are using pusher, use the pusher broadcaster, not the echo broadcaster.
The client can still be echo (https://github.com/laravel/echo), but the backend has to be pusher. For that, just leave the `LIGHTHOUSE_BROADCASTER` env empty, because the default is `pusher`.

The echo broadcaster was there to be used with echo server.
You make a good point about echo server no longer being maintained and we should probably remove the echo broadcaster.

**Comment by Stevemoretz** [comment]
> If you are using pusher, use the pusher broadcaster, not the echo broadcaster. The client can still be echo (https://github.com/laravel/echo), but the backend has to be pusher. For that, just leave the `LIGHTHOUSE_BROADCASTER` env empty, because the default is `pusher`.
> 
> The echo broadcaster was there to be used with echo server. You make a good point about echo server no longer being maintained and we should probably remove the echo broadcaster.

Makes sense, I can't test it right now but I'm sure doing what you suggested should just fix it. I thought echo was only supposed to work with echo broadcaster.
