### ISSUE TITLE
Enum returns incorrect case in Lighthouse GraphQL API

### ISSUE THREAD

**Issue by martio** [nuwave/lighthouse#2629]
**Description:** When querying an enum in the Lighthouse GraphQL API, the enum values are returned with only the first letter capitalized, which does not align with the expected uppercase format. For instance, when querying the UserStatus enum, values are returned as "Active", "Inactive", etc., instead of "ACTIVE", "INACTIVE", etc.

**Expected Behavior:** The enum values should be returned in uppercase, matching the convention in GraphQL specifications and our application requirements.

**Steps to Reproduce:**

Define a native PHP enum with lowercase values, as follows:

```php
enum StatusEnum: string {
    case INACTIVE = 'inactive';
    case ACTIVE = 'active';
    case BANNED = 'banned';
}
```

Configure the enum in Lighthouse:

```graphql
enum UserStatus {
    INACTIVE @enum(value: "inactive")
    ACTIVE @enum(value: "active")
    BANNED @enum(value: "banned")
}
```

Execute a GraphQL query that retrieves this enum:

```graphql
query {
  user(id: 1) {
    id
    status
  }
}
```

Observe the format of the returned enum value.

Current Response:

```json
{
  "data": {
    "user": {
      "id": 1,
      "status": "Active"
    }
  }
}
```

Expected Response:

```json
{
  "data": {
    "user": {
      "id": 1,
      "status": "ACTIVE"
    }
  }
}
```

**Comment by spawnia** [comment]
I added a test to show how `@enum` is supposed to work in https://github.com/nuwave/lighthouse/pull/2630. I can not explain the behaviour you describe, perhaps you are defining the enum in mulitple places, such as registering it programmatically? Or perhaps the `status` field uses a different type?

**Comment by martio** [comment]
@spawnia The issue concerns enum serialization. If the keys in the native enum are formatted as "Example" instead of "EXAMPLE," the value returned by GraphQL will also be in the format "Example" instead of the expected "EXAMPLE."

```php
<?php

declare(strict_types=1);

namespace App\GraphQL\Types;

use BackedEnum;
use GraphQL\Error\SerializationError;
use GraphQL\Type\Definition\PhpEnumType;
use GraphQL\Utils\Utils;
use Override;
use TypeError;
use ValueError;

/**
 * GraphQL.
 */
class BackedEnumType extends PhpEnumType
{
    #[Override]
    public function serialize($value): string
    {
        if ($value instanceof $this->enumClass) {
            return mb_strtoupper($value->name);
        }

        if (is_a($this->enumClass, BackedEnum::class, true)) {
            try {
                $instance = $this->enumClass::from($value);
            } catch (ValueError|TypeError) {
                $notEnumInstanceOrValue = Utils::printSafe($value);
                throw new SerializationError("Cannot serialize value as enum: {$notEnumInstanceOrValue}, expected instance or valid value of {$this->enumClass}.");
            }

            return mb_strtoupper($instance->name);
        }

        $notEnum = Utils::printSafe($value);
        throw new SerializationError("Cannot serialize value as enum: {$notEnum}, expected instance of {$this->enumClass}.");
    }
}
```

**Comment by spawnia** [comment]
I think you are mixing up usage of `PhpEnumType` and `@enum`. One does not influence the other, and native enums by themselves would function as you described where the keys are used, no magic conversion of the keys spelling happens. I think the only confusing part is that there is no error due to duplicate types, but this is probably due to how you register your programmatic types.

**Comment by martio** [comment]
@spawnia There were no duplicate keys anywhere, as I had only been using the `@enum` directive without using `PhpEnumType` until now.

You can easily replicate this. Create a native Enum with keys written only with the first letter capitalized, assign it to casts in the model, and then use the @enum directive. You will get this effect. I tested it with the team in our application and in a newly created one. The keys are returned exactly as they are in the native Enum. If you write everything in lowercase, it returns everything in lowercase. It should convert to the GraphQL enum standard, which means all uppercase.

**Comment by martio** [comment]
@spawnia Take a look at this. I removed the use of `PhpEnumType`. I'm only using the `@enum` directive.

Case 1.

a) In the database, the status has the value: `active` :point_left:
b) In the native enum, I have: `case Active = 'active';` :point_left:
c) Enum definition in file `schema.graphql`: `ACTIVE @enum(value: "active")`
d) GraphQL returns: `Active` instead of `ACTIVE` 👎

File: `graphql/schema.graphql`:

```graphql
"The user status."
enum UserStatus {
    INACTIVE @enum(value: "inactive")
    ACTIVE @enum(value: "active")
    BANNED @enum(value: "banned")
}
```

File: `app/Enums/User/StatusEnum.php`:

```php
enum StatusEnum: string
{
    case Inactive = 'inactive';
    case Active = 'active';
    case Banned = 'banned';
}
```

Case 2.

a) In the database, the status has the value: `ACTIVE` :point_left:
b) In the native enum, I have: `case Active = 'active';`
c) Enum definition in file `schema.graphql`: `ACTIVE @enum(value: "active")`.
d) GraphQL returns: `\"ACTIVE\" is not a valid backing value for enum App\\Enums\\User\\StatusEnum` 👎

Case 3.

a) In the database, the status has the value: `active`
b) In the native enum, I have: `case ACTIVE = 'active';` :point_left:
c) Enum definition in file `schema.graphql`: `ACTIVE @enum(value: "active")`
d) GraphQL returns: `ACTIVE` 👍 

In the third case, the value is returned correctly. It is clear that the enum key is returned incorrectly, as it lacks conversion to the GraphQL standard. When keys in the native PHP enum have only the first letter capitalized, they are not converted to all uppercase letters as required.

**Comment by martio** [comment]
@spawnia After thoroughly debugging, here is what I found:

In Nuwave\Lighthouse\Schema\TypeRegistry::resolveEnumType(), the enum is correctly registered.

<img width="507" alt="Zrzut ekranu 2024-11-8 o 05 48 51" src="https://github.com/user-attachments/assets/30e5507c-e13a-455a-be76-5f83db46485e">

When you remove the cast for the Enum from the Laravel Eloquent model, everything works correctly:

<img width="364" alt="Zrzut ekranu 2024-11-8 o 05 58 20" src="https://github.com/user-attachments/assets/158e6421-9df8-4539-8f65-0a9b2722a367">

After removing the line `'status' => StatusEnum::class` from `casts` it returns correctly:

<img width="396" alt="Zrzut ekranu 2024-11-8 o 06 04 01" src="https://github.com/user-attachments/assets/38c0eb86-c19b-444f-971d-b08c73cce88e">

The issue lies in the `webonyx/graphql-php` package during serialization in the `GraphQL\Type\Definition\EnumType::serialize($value)` method.

a) When the $value is a string "active," it returns "ACTIVE."
b) When the $value is a BackedEnum, it returns the Enum key without normalization:

```php
        if (is_a($value, \BackedEnum::class)) {
            return $value->name;
        }
```

The solution to this problem is simple. It requires adding normalization/transformation to the desired format for GraphQL:

```php
        if (is_a($value, \BackedEnum::class)) {
            return mb_strtoupper($value->name);
        }
```

**Comment by martio** [comment]
@spawnia I have prepared a small fix that resolves this issue: https://github.com/webonyx/graphql-php/pull/1628

**Comment by spawnia** [comment]
```php
enum StatusEnum: string
{
    case Inactive = 'inactive';
    case Active = 'active';
    case Banned = 'banned';
}
```

This definition was what led to the casing you saw returned, and was not present in your original issue description. That made it hard for me to properly diagnose the issue. Lighthouse is not going to do magic conversions of capitalization with enums, others users may have coding standards that prescribe something other than `ALL_CAPS`.

**Comment by martio** [comment]
@spawnia Yes, this is a problem because serialization returns keys in their original form. Note that according to standards, the correct format for keys in Enums in GraphQL should be in uppercase.

This is indicated in the Lighthouse documentation:

> Enums are types with a restricted set of values (similar to enum found in database migrations). They are defined as a list of UPPERCASE string keys.

[#](https://lighthouse-php.com/master/the-basics/types.html#schema-definition)

<img width="780" alt="Zrzut ekranu 2024-11-8 o 12 53 51" src="https://github.com/user-attachments/assets/aaadb3f8-9f2e-40bd-a221-07518c5cef35">

It is also indicated in the GraphQL specification:

> Enum values are represented as unquoted names (ex. MOBILE_WEB). It is recommended that Enum values be “all caps”.

<img width="828" alt="Zrzut ekranu 2024-11-8 o 12 56 07" src="https://github.com/user-attachments/assets/49ee7aa2-7fe1-4cfe-bb77-64ebeb39b5ba">

Source: [The specification for GraphQL](https://spec.graphql.org/June2018/#sec-Enum-Value)

PHP suggests using the key format in enums as I’m currently using in its official documentation:

<img width="1050" alt="Zrzut ekranu 2024-11-8 o 12 57 53" src="https://github.com/user-attachments/assets/29b58376-3df1-4840-985f-4ed95824d407">

Source: [PHP Manual](https://www.php.net/manual/en/language.types.enumerations.php)

**Lighthouse** is a **great framework**, arguably the best for Laravel, and together with the `webonyx/graphql-php` package, it’s an excellent tool. A lot of great work has been done.

It's a pity that you closed my Pull Request because a small change could only improve this framework, bringing it closer to GraphQL standards or recommendations. It could also save others a lot of time since our team lost several days due to this issue... 😉 

Best regards, and I wish continued success in the development of Lighthouse PHP! 👍

**Comment by spawnia** [comment]
I can see how the mismatch in standards between languages causes issues, but I do not think it is wise for us to break existing use cases and make certain opionionated coding standards mandatory in this case.

**Comment by martio** [comment]
@spawnia The solution I proposed is not perfect, but I think it’s worth adding a `strict` flag for the Enum format recommended for GraphQL, along with proper formatting. I can prepare these changes if you want 😊
