### ISSUE TITLE
Undefined array key "hash"

### ISSUE THREAD

**Issue by jaulz** [nuwave/lighthouse#2640]
**Describe the bug**

I can't reproduce it in detail but there is one exception which is triggered in our system: `Undefined array key "hash"`. The system seems to be triggered by a bot. This is where the exception is triggered:
https://github.com/nuwave/lighthouse/blob/a74f08c8f8c2b665abd9a21c70ca896049dc3c63/src/Schema/AST/DocumentAST.php#L237-L243

**Expected behavior/Solution**

I think it shouldn't trigger any exception if the payload is invalid(?).

**Steps to reproduce**

n/a

**Output/Logs**

<details><summary>Click to expand</summary>

The payload is the following as far as I could trace:
```
{
    "extensions": {
        "persistedQuery": {
            "sha256Hash": "98cf58e34d4c0c3f8c441ccc23c0218eebe8f4fa50b07e6c32306b078b97b42e",
            "version": 1
        }
    },
    "operationName": "ReadCurrentCompany"
}
```

</details></br>

**Lighthouse Version**

6.46.0

**Comment by k0ka** [comment]
Did you clear lighthouse schema after updating the package?

**Comment by jaulz** [comment]
@k0ka thanks a lot! That was it... sorry for the confusion.
