### ISSUE TITLE
The dependency "thecodingmachine/safe" generates deprecated logs in PHP 8.4.

### ISSUE THREAD

**Issue by martio** [nuwave/lighthouse#2641]
The dependency "thecodingmachine/safe" generates deprecated logs in PHP 8.4.

Please update the dependency "thecodingmachine/safe" to "dev-master".

<img width="1510" alt="Screenshot" src="https://github.com/user-attachments/assets/e2f0359c-d1b1-48a3-b0d6-e66a1325127d" />

**Comment by spawnia** [comment]
We will stick with requiring tagged releases. Feel free to post a pull request when v3 is available.
