### ISSUE TITLE
Adding a comment above an extend type definition causes an error

### ISSUE THREAD

**Issue by vesper8** [nuwave/lighthouse#2643]
I was attempting to better organize my schemas following the advice from https://lighthouse-php.com/master/digging-deeper/schema-organisation.html#type-extensions

I noticed that simply including a comment above a `extend type Query` throws an error

this works fine:

```

extend type Query {
    "Find a single requirement by an identifying attribute."
    requirement(
        "Search by primary key."
        id: ID @eq @rules(apply: ["required"])
    ): Requirement @find
}
```

And this fails:

```

"Indicates what fields are available at the top level of a query operation."
extend type Query {
    "Find a single requirement by an identifying attribute."
    requirement(
        "Search by primary key."
        id: ID @eq @rules(apply: ["required"])
    ): Requirement @find
}
```

With error `Unexpected Name "extend", near: available at the top level of a query operation`

Is this a bug?

**Comment by spawnia** [comment]
According to the grammar of the GraphQL schema definition language, type extensions do not allow descriptions. See https://spec.graphql.org/draft/#sec-Object-Extensions.
