### ISSUE TITLE
[Feature request] Add `@hasOne` directive 

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#276]
Currently there is only a `@hasMany` directive. 

`hasOne` relationship is very commonly used.  Having a `@hasOne` directive would be helpful😊

**Comment by enzonotario** [comment]
Hi! try just using `@belongsTo`. It works since the relationships are similar.

**Comment by spawnia** [comment]
If i understand correctly, `hasOne` and `belongsTo` are actually the inverse, in terms of where the foreign key sits. https://laravel.com/docs/5.6/eloquent-relationships#defining-relationships

@yaquawa i will happily accept a PR. You can try and look at what the current `HasManyDirective` and `BelongsToDirective` do and go from there.

**Comment by yaquawa** [comment]
@enzonotario  @spawnia 
Thanks! I'll give it a try!

**Comment by chrissm79** [comment]
@yaquawa If I'm not mistaken, you could use the `hasMany` for a `hasOne` relationship and it will still work.... albeit a weird way to notate it in the schema

**Comment by spawnia** [comment]
As of #280 the @hasOne directive is now available.
