### ISSUE TITLE
[RFC] Package to auto-generate queries and mutations

### ISSUE THREAD

**Issue by maarten00** [nuwave/lighthouse#278]
Hi,
In #230 we talked a bit about a project I have been working on with my team that uses this package. We have decided to open-source the package so that other people may use it. The main feature is that it can generate CRUD actions (queries and mutations) given a directory of Types. We have also included a bunch of custom directives and a couple of Scalar types. (Currently only two, but more are on the way)

We are not yet using it in production, so it is currently still in it's experimental phase, but I really wanted to share this with you. It relies on a couple of features that have not been tagged yet, so we currently require dev-master for Lighthouse.

It would love to hear some opinions!
I realise the readme is a bit meager at this point, but it shouldn't be too hard to get it up and running :)

https://github.com/deInternetJongens/Lighthouse-Utils

**Comment by spawnia** [comment]
Looks really interesting. The README would benefit greatly from giving an example of the generation that this package does.

A quick look through the code revealed some areas where you are utilizing Lighthouse internals, and you have to do a bit of hacky configuration changes to make your use case work. I think we can work out a way to improve and solidify the public API of Lighthouse for projects like yours and hopefully improve both Lighthouse and the dev experience for you.

**Comment by maarten00** [comment]
I'm assuming a potential user has basic knowledge of Laravel and the Lighthouse package. Nontheless, I've been meaning to create another repo with a Laravel installation and some examples of the package in action. 

I definetely agree with you, I didn't feel like writing a GraphQL file parser, as Lighthouse does an excellent job there. But it was quite a bit harder then I hoped to work through the Schema class and all of it's children. It would be great if the public API improves, but most of the schema inspection actually relies on Webonyx code. But I'm happy to work with you on changes that will benefit all parties :)

**Comment by spawnia** [comment]
We are planning a section in the docs page where your package can be listed. Feel free to add to the discussion https://github.com/nuwave/lighthouse-docs/issues/34

Closing this, as to keep the Issue tracker focused.

**Comment by maarten00** [comment]
Awesome! In the meantime I have created an example project, but I wanted to do some testing on another machine before sharing. I haven't had the time to do that yet, but I'll leave it here anyway: https://github.com/maarten00/lighthouse-utils-example
