### ISSUE TITLE
There is no explanation about "fallback resolver" on the doc?

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#288]
I've been looking around the source code of lighthouse for a while, and I found that if a field resolver is not provided from directive, lighthouse will fallback to the `'config.lighthouse.namespaces'` implicitly according to the type of the root type and object type, which I found it's really really useful, because then I don't need to write directive everywhere… I really like this kind of "ruby on rails" style.

But this feature is not described in the doc yet. Why not…?😿

**Comment by spawnia** [comment]
Good find, it is pretty cool that you are digging around the source and get deeper into how Lighthouse works. This feature is something that i oversaw, even though i have edited parts of the function that enables it.

I do agree that this deserves mention as part of the docs and would love a PR in the docs repo https://github.com/nuwave/lighthouse-docs

You can hop into Slack if you need some help with figuring out how the Docs work, or you can just write a few paragraphs in here and we can work it in.

**Comment by yaquawa** [comment]
@spawnia Really cool architecture compares to other alternatives. I'll see if I can make a PR to the doc repo. Thanks!

**Comment by spawnia** [comment]
Moved to the docs repo https://github.com/nuwave/lighthouse-docs/issues/44
