### ISSUE TITLE
[Feature Request] Fallback to default `Union` type resolver.

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#289]
Currently, if I don't specify a resolver via `@union` directive on union types, I'll get this error:

```
Union types need to have the @union directive defined to resolve them.
```

Fallback to the `config.lighthouse.namespaces.unions` to find a default resolver just like other types would be nice.😃

**Comment by spawnia** [comment]
Accepting PR's on this one!

**Comment by spawnia** [comment]
This is now a supported feature as of #305
