### ISSUE TITLE
[Question] How can I filter model using custom conditions with `Paginator` returned ?

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#290]
It's easy enough to get a list of models by just utilizing the `@paginate` directive.

But how can I apply my own filter to a model yet still get the `Paginator` type returned?

For example:
```graphql
type Query {
    # The `query` argument is optional, in that case, no filter applied.
    users(query: QueryCondition): UserPaginator
}

input QueryCondition {
    conditions: [Condition]
    relation: Relation
}

input Condition {
    key: String
    value: String
    operator: Operator
}

enum Operator {
    IN @enum(value: "IN")
    NOT_IN @enum(value: "NOT IN")
    AND @enum(value: "AND")
    EXISTS @enum(value: "EXISTS")
    NOT_EXISTS @enum(value: "NOT EXISTS")
}

enum Relation {
    AND @enum(value: "AND")
    OR @enum(value: "OR")
}
```

How can I get the same return type `Paginator` as `@paginate` gives me? 
I thought I must utilize some internal methods of Lighthouse, but I can't find which to use😂

Any help would be greatly appreciated !

**Comment by spawnia** [comment]
Take a look at https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/Fields/PaginateDirective.php

However, what you are looking for is already possible with the various filter directives such as [`@eq`](https://lighthouse-php.netlify.com/docs/next/directives.html#eq) or [`@in`](https://lighthouse-php.netlify.com/docs/next/directives.html#in). The `next` version of the docs is still missing a guide that gives an overview on how to use filters.

Maybe you can get it started over at https://github.com/nuwave/lighthouse-docs ? Just add a file at `docs/guides-filtering.md` and write a few lines. Your contribution will be much welcome.

**Comment by yaquawa** [comment]
@spawnia Yes, I can use some of those filter directives. However by that way I have to hard code every condition, the patterns of condition are going to explode.

**Comment by spawnia** [comment]
I see what you are getting at. You can take a look at https://github.com/deInternetJongens/Lighthouse-Utils as they implemented quite a lot of filters.

Another big thing would be client-side filters. They actually seem more desirable then server-side filtering because as you said, it gives more power to the API consumer. I am not quite sure what is the best approach to implement them, client-side directives or a fixed set of arguments as you suggested might both be worth exploring.
