### ISSUE TITLE
[Feature request] Enum vaildation support

### ISSUE THREAD

**Issue by morpheus7CS** [nuwave/lighthouse#294]
Hey,

I have found this Laravel package extremely helpful for enum validation in Laravel projects. To be honest, I have no idea about the current enum validation capabilities in Lighthouse. Just throwing it out there, it might be good to consider it.

https://github.com/bensampo/laravel-enum

Thanks,
g

**Comment by spawnia** [comment]
I believe that the underlying library `webonyx/graphql-php` takes care of enum validation. https://github.com/webonyx/graphql-php/blob/master/tests/Type/EnumTypeTest.php

The package you suggest does look nice indeed, but i think we might simply not need it. First and foremost, we aim to have Lighthouse be a spec-compliant GraphQL server, so it
seems correct to use the enum validation that is provided by the GraphQL package.

If you can come up with a concrete example where the current implementation is lacking,
feel free to open an issue for it.

Thanks for your interest!
