### ISSUE TITLE
Client side querying

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#312]
(Related to #302)

Currently, lighthouse only allows users to define query constraint at server side with those like `@eq` kind of directives.

By doing this way, we are forced to define as many fields as our query constraint types.
We have to hard code every type of query constraint when there comes a need. (which is kind of violating the Open/closed principle)

My suggestion is 

```graphql
input QueryCondition {
    conditions: [Condition!]!
    relation: Relation = "AND"
    order: Order = "ASC"
    orderBy: String
}

# This is an array contains [key, operator, value], 
# where the `operator` can be omitted just like the EloquentBuilder's `where` method.
scalar Condition

enum Order {
    ASC @enum(value: "ASC")
    DESC @enum(value: "DESC")
}

enum Relation {
    AND @enum(value: "AND")
    OR @enum(value: "OR")
}


type Query {
    # inject `QueryCondition` argument and resolve the incoming query automatically by simply adding a `queryable` argument.
    users: [User!]!  @paginate(type: "paginator" model: "User" queryable: true)
    
    # or optionally if the user really want their own query logic, they can do it by themselves
    users(query: QueryCondition): [User!]!  @paginate(type: "paginator" querybuilder: "className@build")
}
```

then at the client side, you can define your query like this
```json
{
  "query": {
    "conditions": [
      ["age", ">=", 25],
      ["job", "software_engineer"]
    ],
    "relation": "OR",
    "orderBy" : "last_login_time",
    "order" : "ASC"
  }
}
```
Also the same ability can be shared between the `@hasMany` `@belongTo` `@all` `@first` directives too.

The initial idea can be found at #302, because this is a rather larger topic, I opened this issue.

I want to know what do you think, thanks!

**Comment by yaquawa** [comment]
Thanks @spawnia !

Here is what I thought…

Think of rather complex example
```sql
SELECT * FROM table WHERE (A = B OR C >= D) AND (E LIKE F AND G IN H)
```

How would you like to represent this in the query?
yeah, I thought just like you, define every query element as an enum at the beginning,
but soon I realized that it's too much verbose, and more importantly not that intuitively to see and understand.

For me, this is much better.
```json
{
    "query": {
        "relation": "AND",
        "conditions": [
            {
                "relation": "OR",
                "conditions": [
                    ["A", "B"],
                    ["C", ">=", "D"]
                ]
            },
            {
                "relation": "AND",
                "conditions": [
                    ["E", "LIKE","F"],
                    ["G", "IN", "H"]
                ]
            }
        ]
    }
}
```

Laravel do check the if the operator is valid or not, so this shouldn't be a security issue I think, or maybe we can just wrap the query in a try catch block if the operator is invalid throw an error message to the API consumer.

**Comment by spawnia** [comment]
We have to strike a balance between simplicity and functionality.

I do not think that short syntax is necessarily simple, it does not hurt to write out a few
extra characters if it means the code is more clear, self-documenting and type safe.

```graphql
{
  foo(query: {
    where: [
	  {column: "bar", operator: "EQUALS", value: "baz"}
    ]
  }
}
```

**Comment by spawnia** [comment]
For the combining of logical operator, we might do something similar to Prisma, like https://www.prisma.io/docs/prisma-graphql-api/queries-qwe1/#combining-multiple-filters

```graphql
input QueryConstraints {
  where: [WhereConstraint!]
  orderBy: [OrderByConstraint!]
}

input WhereConstraint {
  column: String!
  operator: Operator
  value: Mixed!
  AND: [WhereConstraint!]
  OR: [WhereConstraint!]
  NOT: [WhereConstraint!]
}
```

**Comment by yaquawa** [comment]
@spawnia That's looks so great for me!

**Comment by yaquawa** [comment]
@spawnia 
So do you think this is what it would look like of the final version?

```graphql
type Query {
    # This is the fully automated version.
    users(query: QueryConstraints): [User!]!  @paginate(type: "paginator" model: "User") @queryable
    
    # or optionally if the user really want their own query logic, they can do it by themselves
    users(query: QueryConstraintsDefinedByUser): [User!]!  @paginate(type: "paginator" querybuilder: "className@build")
}
```

**Comment by spawnia** [comment]
I think `queryable` should be an argument that can go on supported directives. It does not make sense to combine it some, for example the `@field` directive.

```graphql
type Query {
  users: [User!]! @paginate(queryable: true)
}
```

This will suffice, as the argument can be generated and the other values are defaults.

Custom query building only really makes sense for the `@paginate` directive, as in other cases the user can just point to a resolver they define themselves via `@field`. So we could do:

```graphql
type Query {
  users(userDefined: ArgsOfAnyType): [User!]! @paginate(builder: "App\\User@customUserQuery")
}
```

**Comment by yaquawa** [comment]
@spawnia 
I think in some cases if we don't want a paginated results, but want all of the filtered results we can't just use the `@queryable` independently:
```
type Query {
  users: [User!]! @queryable
}
```

But…

While I was reading the Prisma's doc, I found they really provide their users a simple and intuitive way to CRUD the data model.

So in their implementation, if I want all of the filtered results, what I have to do Is just as simple as omitting the `first/last ` or `after/before` arguments, which in my opinion it's really a human-readable implementation.

```graphql
type Query {
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
```

maybe we should rethink this topic from zero, spread the topic to something like this
```graphql
type User @crud {
...
}
```
this way, in most cases, all my works are just as simple as adding a `@crud` directive to the model, and you're done.

**Comment by yaquawa** [comment]
> That would be @all(queryable: true).
Good!!

> and should really be it's own package
Agree with this! Lighthouse itself should be focus on the most low level core components.

**Comment by yaquawa** [comment]
@spawnia I comes up with an idea is that we could map the model back to the GraphQL schema, that is, **model driven schema generation**. Manage the object fields in one place(model class), so you never have to sync the schema file again and again, which I think is a better solution for Laravel developers.

I'm developing a package of Lighthouse for just that purpose now.

**Comment by spawnia** [comment]
Big schemas are pretty problematic, but can be managed. We have over 10000 LOC in ours, it kept crashing on the initial parse until we enabled PHP Opcache.

I did consider splitting the parsed AST by type and caching them seperately and only deserializing them lazily. This would require quite the internal overhaul, but should be manageable.

**Comment by yaquawa** [comment]
> parsed AST by type and caching them seperately and only deserializing them lazily

@spawnia Good idea! just like how the the php autoloader works.

**Comment by mfn** [comment]
>  { column: "age", operator: ">", value: 37 }
…
> WHERE age = 37

I believe the SQL operator is wrong

**Comment by maarten00** [comment]
@spawnia I was just looking back at your suggestion, but I see it is also making use of input types in your `@all`/`@paginate` directives. Wouldn't that mean you would have to add input type support to those directives? 

Our API is experiencing quite some perfomance problems because of the huge amount of parameters on our queries. I'm looking for a way to fix it myself (in our Lighthouse Utils package) without waiting for this feature.. So I wanted to have a go at it myself, but I'm wondering if it would even be possible without input type support?

**Comment by spawnia** [comment]
@maarten00 

Input types in general are not an issue. The particular problem i think you are referring to has to do with directives that influence a query, while being defined on the arguments of that query. For example `@eq` or `@where`.

I think there are multiple problems with the existing filter directive.

**They do not scale well.** Every query option has to be defined in advance, which either grows the amount of arguments to a ridiculous amount, or leaves the user with very limited query capabilities.

**The client has no idea what filtering is going on behind the scenes.** Take the following definition as an example:

```graphql
type Query {
  foo(name: String @neq): Bar
}
```

When introspecting on the schema, the client actually only sees that there is an argument `name: String`. One might reasonbly expect that to be an equals or maybe a like condition, however in this case the result will be the opposite.

**They are complicated to implement.** We have to do some weird tricks to reach into the field resolution process from the argument definition. This mechanism only gets worse once you add InputObjects into the mix. It would certainly be possible, but actually i think we should not do it.

**Comment by spawnia** [comment]
In a discussion with @robjbrain we developed the need for multiple shapes for the query InputObject. I think that Lighthouse might easily have a mechanism for plugging in such implementations.

Queryable directives, such as `@all` or `@paginate` can just accept an argument called `builder`, which may be any InputObjectType. During execution, Lighthouse then goes and locates a class that is named the same as the InputObjectType. It passes in the values that were given as arguments to the fields, a Builder instance of the associated model as well as some context information, and expects back a `Builder` instance with the additional constraints attached.

**Comment by plunkettscott** [comment]
Any idea when client-side querying will be implemented into Lighthouse?

**Comment by spawnia** [comment]
Since we have `@whereConstraints` as an experimental feature now, i am closing this issue for now. https://lighthouse-php.com/master/api-reference/directives.html#whereconstraints
