### ISSUE TITLE
[Feat] Schema import multiple files via glob

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#314]
I`m using import file syntax as described

https://lighthouse-php.netlify.com/docs/schema-extending.html

I`m organizing files in multiples folder, and this works as expected

schema.graphql
```
#import ./post/post.graphql
#import ./post/category.graphql

.... and a dozen of files will be imported ....
```

Is it possible a folder import syntax like this?

```
#import ./post/*
```

**Comment by spawnia** [comment]
Not at the moment, although i will happily take a PR if you implement it. The code is in here:

https://github.com/nuwave/lighthouse/blob/master/src/Schema/Source/SchemaStitcher.php

And the tests in here:

https://github.com/nuwave/lighthouse/blob/master/tests/Unit/Schema/AST/SchemaStitcherTest.php

If you implement multi-import via glob, make sure to add a few tests.
