### ISSUE TITLE
Will you improve the documentation?

### ISSUE THREAD

**Issue by winter-ice** [nuwave/lighthouse#329]
Now the documentaion is all about this package(in fact, all about the schema.graphql),I wonder the documentation can has some details about how to use with laravel,For example there is defined namespaces in config/lighthouse.php but i do not know how to use it,It is not mention in the documentation.

**Comment by spawnia** [comment]
Open to suggestion and PR's for the docs. What troubles you specifically? What are you tryong to achieve?

**Comment by winter-ice** [comment]
> Open to suggestions and PR's for the docs. What troubles you specifically? What are you trying to achieve?

demo about defined namespaces in the lighthouse.php,For example in the namespace App\Http\GraphQL\Queries.How to create query class

**Comment by spawnia** [comment]
This is actually in the new docs that are released very soon.

If you have improvements for the docs, feel free to submit a PR over at https://github.com/nuwave/lighthouse-docs
