### ISSUE TITLE
What is the best way to insert my schema to the base schema?

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#338]
Hi, I'm building a package for Lighthouse currently(schema auto generation based on data model).
And I have a use case for inserting my own schema into the base schema. 

Currently, I think I have only two options to achieve that.

1. Rebinding the `SchemaSourceProvider`.
2. Create a directive that implements `NodeManipulator`.

Both have its limitation and weak points.

## 1. Rebinding the `SchemaSourceProvider`.
This is good for who want to just attach their schema without having to worry about the base schema.

but sometimes, there may come to a case that developers want to have some knowledge about the base schema. 

For example, if a developer wants to insert their own scalar type definitions to the base schema, but they should make sure it won't conflict with the base schema. So it is required to search all the scalar types in base schema, and check if it has existed if it has then skipped that one. 
This is just a simple example; there should have more and more complex cases. So when you want to conditionally insert your schema base on the base schema, you want to do it with solution 2(below).

And even a simple case that does not require a conditional inserting, the problem occurs also when you use multiple packages developed for Lighthouse. Which is.. only the very last rebinding works... rebinding before the last one will just be ignored.

So for simple schema inserting the solution can be this; dispatch an event for just that purpose.

in `GraphQL.php:193`
```php
protected function buildAST(): DocumentAST
{
    // Listeners of `BuildingAST` event are expected to return their schema string.
    $additionalSchemas = implode("\n", (array)event(new BuildingAST($this)));
    $schemaString = $this->schemaSourceProvider->getSchemaString();

    return ASTBuilder::generate($schemaString . $additionalSchemas);
}
```

## 2. Create a directive that implements `NodeManipulator`.
This is needed if I want to conditionally insert my schema as referred above.

But, the problem is…
1. The usage of `NodeManipulator` is intended for just directive only, so you do this means you created an internal directive which has no meaning by itself, bad for semantics.
2. The current API only allows you to insert the node one by one by using the `setDefinition` in `Schema/AST/DocumentAST.php:330`, which is obviously inefficiency for massive nodes inserting. There should have an API for massive insertion too.

I want to know if there are better ways for this, and if not what you think about this?

**Comment by spawnia** [comment]
1. I am open for a pluggable SchemaSourceProvider that gathers schema parts via the event, as in your example. That seems like a good idea, we might just put that into the core and make that our default Provider.

2. The `Manipulator` directives are mostly useful for directives that a user might just put into the hand-written schema. It could work if you have a two step process - auto-generate a base schema, and transform that into the final schema via Manipulators. That would enable your directives to be used independently.

You do not need to worry about performance with the NodeManipulator, as the resulting schema can be cached. That was kind of the point in implementing it, we get to do hard work upfront and not on every request.

**Comment by yaquawa** [comment]
@spawnia 
Thanks!

Question to `2.`

Maybe fire another event after built the AST is more comfortable for me because I'm not going to implement a directive, I'm just going to insert my scalars or object type or input types ... into the base schema.

**Comment by spawnia** [comment]
@yaquawa 

I always found manual AST node creation horribly verbose, which is why Lighthouse uses SDL to create any schema definitions that are needed internally.

Can you clarify how exactly you plan to add to the schema? AST definitions? Executable types? Schema string fragments?

**Comment by yaquawa** [comment]
@spawnia You are right. Eventually, I came back to generate the raw SDL itself now.
