### ISSUE TITLE
[Question] Handling validations

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#339]
Considering Laravel validation error bag, easily we can get individual messages from each field.
https://laravel.com/docs/5.6/validation#working-with-error-messages

It is important, considering we need to underlining errors on each field inputs  on frontend.

Inline @rule directive are nice. LightHouse return this json
https://lighthouse-php.netlify.com/docs/validation.html

```js
{  
  "data":{  
    "foo":null
  },
  "errors":[  
    {  
      "message":"validation",
      "locations":[  
        {  
          "line":2,
          "column":13
        }
      ],
      "validation":[  
        "The name field is required."
      ]
    }
  ]
}
```
But, we don't have field keys. So we cant properly identify this errors on frontend input fields.
How to handle it? Am i missing something?

**Comment by spawnia** [comment]
Have you tried `dev-master`? Valiation errors are now spec compliant (which the above example is not) and more specific about fields

**Comment by olivernybroe** [comment]
The way validation messages are parsed was changed and might satisfy your needs, but this new way is on the master branch at the moment. On the master branch you can also extend the error handler (it is also possible in the current version, but that way is deprecated on master and totally reworked, so I wouldn't recomend implementing it on the current version).


You can extend the error handler by implementing this interface https://github.com/nuwave/lighthouse/blob/master/src/Execution/ErrorHandler.php 

Then you can register it https://github.com/nuwave/lighthouse/blob/master/config/config.php#L127-L139 

This is the way you can customise the errorhandler. However this is on master branch right now.

**Comment by robsontenorio** [comment]
Thank you!!
