### ISSUE TITLE
Lacking the `@belongsToMany` directive

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#354]
We have `@hasOne` `@belongsTo` `@hasMany` directives, the only lost part is the `@belongsToMany`! Hope this can be added as well. Thanks!

**Comment by spawnia** [comment]
Duplicate of #332

**Comment by yaquawa** [comment]
@spawnia Do you have any plans on adding this directive recently? If not, I guess I have to send a PR on this, because I really need this feature right now.

**Comment by spawnia** [comment]
Go ahead and give it a shot! Should be pretty straightforward. Make sure to add it to the docs repo as well ☺️
