### ISSUE TITLE
[Feature request] about `@bcrypt`,`@auth` and organize Schema

### ISSUE THREAD

**Issue by winter-ice** [nuwave/lighthouse#369]
**Is your feature request related to a problem? Please describe.**

1. Use `@bcrypt` in input type
2. `@auth` allow pass parameter
3. Organize Schema group by model

**Describe the solution you'd like**

*Examples*

1.
```
input CreateUser{
    name: String!
    email:String!
    password: String! @bcrypt
}
```

2. 
```
type Query {
    me: User @auth(guard:"user")
}
```

3.
`graphql/user.graphql`
```
type User {
    id: ID!
    name: String!
    email: String!
}

type Query {
    users: [User!]!
    userById: User
}

input CreateUser {
    username: String!
    email: String!
    password: String! @bcrypt
}

type Mutation {
    createUser(input:CreateUser!): User @create(flatten:true)
}
```

`graphql/schema.graphql`
```
#import user.graphql
```

**Comment by spawnia** [comment]
Those are 3 totally unrelated issues. Please reopen seperately and describe your issue in plain english.
