### ISSUE TITLE
@auth allow pass parameter

### ISSUE THREAD

**Issue by winter-ice** [nuwave/lighthouse#373]
**Is your feature request related to a problem? Please describe.**

I have multipe guards in my program,Looks like `@auth` directive always use default guard?
https://github.com/nuwave/lighthouse/blob/3e7bffe901f298df0634de37e95d971600beb542/src/Schema/Directives/Fields/AuthDirective.php#L28-L34
**Describe the solution you'd like**
```
type Query {
    me: User @auth(guard:"user")
}
```

**Comment by spawnia** [comment]
The `@auth` directive always returns the authenticated user, no matter how this authentication was done. I do not see what guards would have to do with that.

**Comment by winter-ice** [comment]
different guard use different user provider,i think if i do not pass parameter,there maybe something wrong.i     have not test.:sweat_smile:

**Comment by winter-ice** [comment]
My fault.This directive  is work well
