### ISSUE TITLE
Organize Schema suggestion

### ISSUE THREAD

**Issue by winter-ice** [nuwave/lighthouse#374]
**Is your feature request related to a problem? Please describe.**

Organize Schema support other types.
I want to organize schema group by model,That will be more clearly to me.

**Describe the solution you'd like**

example:

`graphql/user.graphql`
```
type User {
    id: ID!
    name: String!
    email: String!
}

type Query {
    users: [User!]!
    userById: User
}

input CreateUser {
    username: String!
    email: String!
    password: String! @bcrypt
}

type Mutation {
    createUser(input:CreateUser!): User @create(flatten:true)
}
```

`graphql/schema.graphql`
```
#import user.graphql
```

**Comment by spawnia** [comment]
This is already possible https://lighthouse-php.netlify.com/docs/next/schema-organisation.html#type-extensions

**Comment by winter-ice** [comment]
don't define `query` or deine empty `query` in `schema.graphql` is incorrect?After I organize my Schema,There is nothing to define in `schema.graphql` 😁

**Comment by spawnia** [comment]
You have to have the root Query type, see https://github.com/nuwave/lighthouse-docs/pull/61
