### ISSUE TITLE
[Question] Default namespaces

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#384]
According docs "default namespaces" is suposed to work out of box.
https://lighthouse-php.netlify.com/docs/configuration.html

```graphql
extend type Mutation{
  updateUser(name: String) @field(resolver: "UserMutation@update")
}
```

Class exists and namespace is correct.
```
app/Http/GraphQL/Mutations/UserMutation.php
```
But i got `class not found exception`.

I must set full path on field resolver

```graphql
extend type Mutation{
  updateUser(name: String) @field(resolver: "App\\Http\\GraphQL\\Mutations\\UserMutation@update")
}
```

Or, set  @group / namespace
```graphql
extend type Mutation @group(namespace: "App\\Http\\GraphQL\\Mutations"){
  updateUser(name: String) @field(resolver: "UserMutation@update")
}
```
BUT, by tweaking this 

https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/BaseDirective.php#L106

with this
```php
$className = $this->namespaceClassName($argumentParts[0], [
            config('lighthouse.namespaces.models'),
            config('lighthouse.namespaces.mutations'),
            config('lighthouse.namespaces.queries')
        ]);
```

And i got it working as expected

```graphql
extend type Mutation{
  updateUser(name: String) @field(resolver: "UserMutation@update")
}
```

Am i missing something?

**Comment by spawnia** [comment]
For root Query/Mutation fields, you do not need to use the `@field` directive. In your example, Lighthouse will look for `App\\Http\\GraphQL\\Mutations\\UpdateUser@resolve`. Read more about this here: https://lighthouse-php.netlify.com/docs/fields.html

**Comment by robsontenorio** [comment]
@spawnia I was considering the same UserMutation class to place another methods for “user mutation scenarios”. 

UserMutation@inactivate
UserMutation@ban

By your approach i am “forced” to create a class with a single “resolve” method, in order to use the “default namespace resolution”. 

So do you mean “default namespaces” does not work for custom resolvers like described on my example?

**Comment by spawnia** [comment]
I think it is best if Lighthouse has one, simple convention that just works.
