### ISSUE TITLE
Using @group in "extend type" causes incorrectly nested types when using @paginate

### ISSUE THREAD

**Issue by jbbr** [nuwave/lighthouse#387]
**Describe the bug**

When using `@paginate` directive within an `extend type Query @group` the emitted schema is incorrect.

Introspection/Playground Schema:
![image](https://user-images.githubusercontent.com/682607/46951103-49ac6f80-d087-11e8-90b0-4823ded15cc6.png)

Query examples:

```graphql
{
  users(count: 5) {
    data { id email }
  }
}

# Error: Cannot query field \"id\" on type \"UserPaginator\".
```

```graphql
{
  users(count: 5) {
    data { data { id email } }
  }
}

# Error: "Argument 1 passed to Nuwave\\Lighthouse\\Schema\\Types\\PaginatorField::dataResolver() must implement interface Illuminate\\Contracts\\Pagination\\LengthAwarePaginator, instance of App\\User given, called in test/vendor/nuwave/lighthouse/src/Schema/Directives/Fields/FieldDirective.php on line 52",
```

**Expected behavior**

Query example 1 should work fine and emitted schema should only contain `UserPaginator` and not `UserPaginatorPaginator`

**Schema**

```graphql
type User {
    id: ID!
    email: String!
}
type Query {
    me: User @auth
}
extend type Query @group {
    users: [User!]! @paginate
}
```

**Environment**

Lighthouse Version: 2.3
Laravel Version: 5.7
PHP Version: 7.1

**Additional context**

Issue was introduced with Lighthouse 2.3. Downgrading to 2.2 fixes the issue.

**Comment by jeroenpf** [comment]
Added a pull-request that solves the issue for me and passes the unit test in the previous comment.

Hope it helps.
