### ISSUE TITLE
Middleware @group(middleware: ["auth:api"]) not working on tests

### ISSUE THREAD

**Issue by najaram** [nuwave/lighthouse#397]
**Describe the bug**
Middleware works fine when using insomia.
and also on running this first test.
```php

    public function can_view_list_of_genders()
    {
        $user = factory(User::class)->create();
        factory(Gender::class)->create([
            'name'        => 'Example gender name',
            'description' => 'Example gender description'
        ]);

        $response = $this->actingAs($user, 'api')
            ->sendQuery('genders');

        $response->assertJson([
            'data' => [
                'genders' => [
                    [
                        'name'        => 'Example gender name',
                        'description' => 'Example gender description'
                    ]
                ]
            ]
        ]);
    }
```
but this test should fail, when used dd() it still shows that it was accessible even if not logged in.

```php
    public function guests_cannot_view_list_of_genders()
    {
        factory(Gender::class, 3)->create();

        $response = $this->sendQuery('genders');

        dd($response->getContent());
    }
```
**Expected behavior**
It should not display the gender results, should've been an error or data null results

**Schema**
```graphql
type Query @group(middleware: ["auth:api"]) {
    genders: [Gender!] ! @all
}
```

**Environment**

Lighthouse Version: 2.3
Laravel Version: 5.7
PHP Version: 7.2

**Additional context**

https://github.com/najaram/hqtest

**Comment by spawnia** [comment]
You bypass the middleware by directly executing your query https://github.com/najaram/graphql-auth-error/blob/master/tests/Feature/GraphQL/GraphQLTestCase.php#L21

Use something like this instead:

```php
    /**
     * Execute a query as if it was sent as a request to the server.
     *
     * @param string $query
     *
     * @return array
     */
    protected function queryViaHttp(string $query): array
    {
        return $this->postJson(
            'graphql',
            ['query' => $query]
        )->json();
    }
```

Also, i would love if you can take a look at #395 and see if it works for you.

**Comment by najaram** [comment]
uhhm i've tried to referenced the branch but can't seem to make it work ```mll-lab:middleware-in-field-resolution``` can you please guide me through to figure out the branch. 

I would really appreciate it. thanks!

**Comment by spawnia** [comment]
Put this in your `composer.json`

```json
    "repositories": [
        {
            "url": "https://github.com/mll-lab/lighthouse.git",
            "type": "git"
        }
    ],
    "require": {
		...
        "nuwave/lighthouse": "dev-field-and-mutation-generator-command",
```
