### ISSUE TITLE
Extended types does not respect root @group(namespace) directive

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#402]
**Describe the bug**

Even setting a `@group(namespace)` directive on root types it will not reflect on extend types.

**Expected behavior**

The extend types should respect the root `@group(namespace)` directive. Is this an expected behavior? Should i repeat "the full namespace" in every single extended type?

**Schema**

```graphql
type Mutation @group(namespace: "App\\Http\\GraphQL\\Mutations"){
  foo: String
}

# this DOES NOT WORK

extend type Mutation {
  doSomething(id: ID!): String
    @field(resolver: "SomeMutation@doSome")
}

# this WORKS

extend type Mutation @group(namespace: "App\\Http\\GraphQL\\Mutations"){
  doSomething(id: ID!): String
    @field(resolver: "SomeMutation@doSome")
}

# this WORKS

extend type Mutation {
  doSomething(id: ID!): String
    @field(resolver: "App\\Http\\GraphQL\\Mutations\\SomeMutation@doSome")
}
```

**Output/Logs**

```json
  "error": {
    "message": "No class 'SomeMutation' was found for directive 'field'",
    "exception": "Nuwave\\Lighthouse\\Exceptions\\DirectiveException",
    "file": "/var/www/api/vendor/nuwave/lighthouse/src/Schema/Directives/BaseDirective.php",
    "line": 174,
    ....
```

**Environment**

Lighthouse Version: dev-master (a9c4c47400a787f3ca9937bfee98c7c61427d615)
Laravel Version: 5.7
PHP Version: 7.2

**Additional context**

Default namespaces does not work also for `extend type Query` like `@paginate(builder: "Class@method") `

```graphql
type Query @group(namespace: "App\\Http\\GraphQL\\Queries") {
  me: User 
}

# DOES NOT WORK

extend type Query{
  searchSomething(nome: String!): [Something]     
    @paginate(builder: "SomethingQuery@search")
}

# WORKS

extend type Query{
  searchSomething(nome: String!): [Something]     
    @paginate(builder: "App\\Http\\GraphQL\\Queries\\SomethingQuery@search")
}

```

**Comment by spawnia** [comment]
That is indeed the expected behaviour, `@group` applies only to fields that are actually in the exact type they are defined on, and it only applies to `@field` and `@complexity` directives. I clarified the description in the docs: https://lighthouse-php.netlify.com/docs/directives.html#group

We might expand the directives the namespace applies to, but we should do it selectively. It does not make sense for every directive that mentions a class in any way. Feel free to open up a discussion in another issue if that is something you care about.

The following should work, but is currently broken. I just finished a fix for it.

```graphql
extend type Mutation {
  doSomething(id: ID!): String
    @field(resolver: "SomeMutation@doSome")
}
```

**Comment by robsontenorio** [comment]
@spawnia I'm looking forward #406 before opening a new discussion.

Are you considering default namespace resolution through `@group(namespace)` and/or `lighthouse.php` settings ?

**Comment by spawnia** [comment]
The default namespaces `queries`/`mutations` from `lighthouse.php` apply to all fields that are defined on the root types. `@group` namespaces can be applied to any types and overwrite those from the config.

**Comment by robsontenorio** [comment]
So, extended types will inherit default namespace resolution?

**Comment by spawnia** [comment]
If they are extensions of `Query` or `Mutation` the default namespace from the config applies.

`@group` will only ever influence direct children.

**Comment by robsontenorio** [comment]
Nice! Will close #402 and #394
