### ISSUE TITLE
Make the @method call consistent with all other resolvers.

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#403]
**Is your feature request related to a problem? Please describe.**

The `@method` directive calls a function with just 3 of the regular 4 resolver arguments.

**Describe the solution you'd like**

Make the method call consistent with all other resolvers and pass all 4 arguments, even if the `$root` value might seem redundant in this case.

**Comment by olivernybroe** [comment]
Hmm, I can see the reason for the consistency, however isn't it actually decreasing performance by having to instantiate a variable more?

**Comment by spawnia** [comment]
I do not think that performance is an issue here.

Just had another thought pop up. If the method that is called is static, it will definitely be necessary to pass the `$root` argument.

**Comment by yaquawa** [comment]
Great for me!
