### ISSUE TITLE
Support @deprecated directive

### ISSUE THREAD

**Issue by georgeboot** [nuwave/lighthouse#408]
Currently, the `lighthouse` project does not support the `@deprecated` directive.

It would be great if support for this directive could be added, so that fields, types, queries or mutations can be marked as deprecated.

Like so:

```graphql
type ExampleType {
  newField: String
  oldField: String @deprecated(reason: "Use `newField`.")
}
```

Example from the [GraphQL.org](https://graphql.org/) homepage:
[![Example from GraphQL.org homepage](https://i.postimg.cc/cHMkKGZW/Schermafbeelding-2018-10-23-om-14-01-19.png)](https://postimg.cc/hzv1wwfZ)

**Comment by fransjooste1** [comment]
Nice, good way to handle changes down the line.

**Comment by chrissm79** [comment]
@georgeboot This has been added to the `master` branch and will make it's way into `v3.0`

[Documentation](https://lighthouse-php.com/master/api-reference/directives.html#deprecated)
