### ISSUE TITLE
[Vote][RFC] Default namespaces

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#417]
As @robsontenorio has written up his excellent tutorial, i noticed that we deviate from the
Laravel default namespace for Models. While i personally change it to `App\Models` in each
of my Laravel projects, i think it would be more beginner friendly to just stick with the
default that Laravel provides.

On the same vein, i do have some changes in mind about some other default namespaces.
I feel like the current namespaces/default directories are unnecessarily nested. I propose
to lift them up a level and make Lighthouse/GraphQL more of a first class citizen in the project.

As this is a community-developed project, i figured we might as well vote on it. I added single
comments below with some choices, feel free to add your own opinions.

Changing the defaults should not affect most users, as they will probably have ejected the config. If we do change them, we will make sure to announce this clearly in the next version.

**Comment by spawnia** [comment]
Default Model namespace:

- `App` (Laravel default) 👍 
- `App\Models` (current) 👎

**Comment by spawnia** [comment]
Default namespaces for 'queries', 'mutations', 'interfaces', 'unions', 'scalars':

- `App\GraphQL\Xyz` (GraphQL as a first class citizen) 👍 
- `App\Http\GraphQL\Xyz` (current) 👎

**Comment by spawnia** [comment]
Default location for the root schema:

- `graphql/schema.graphql` (GraphQL as a first class citizen) 👍 
- `routes/graphql/schema.graphql` (current) 👎

**Comment by spawnia** [comment]
@robsontenorio Can you add your votes to the individual comments with a reaction?

**Comment by chrissm79** [comment]
Just a personal preference, but I prefer the following for the schema file:

`routes/schema.graphql`

Since that folder also includes `api.php`, `channels.php`, `console.php`, and `web.php` it makes more sense (to me) to add the schema here rather than creating a new folder on the root level of the project.

**Comment by mfn** [comment]
> Default namespaces for 'queries', 'mutations', 'interfaces', 'unions', 'scalars', 'directives':

I voted for non-Http version because I've in fact used GraphQL also in non-HTTP context. Let's not forget that GraphQL itself is transport agnostic and nothing per se requires HTTP.

**Comment by chrissm79** [comment]
@mfn That's a great point

**Comment by spawnia** [comment]
@mfn that makes sense. In general, i dislike nesting the directory structure unless it gets out of hand. Both the `app` and root directory usually have about 10 directories, and since GraphQL is a central part of a Laravel project, it makes sense to have it highly visible.

**Comment by snetts** [comment]
Hello,

I am having an issue with the namespaces, my project has a Models where all my Models are except for User.php. Because of this inconsistency I decided to move the User model to the Models folder, in doing that Lighthouse now does not work. What do I need to fix this so that I can have all the models in one folder and have Lighthouse working.

**Comment by enzonotario** [comment]
@snetts have you refactor all files related to User? I mean, `config/auth.php` for example, and related models? I'm sure it is not a lighthouse's problem. I have all models in their custom modules and all works fine.

**Comment by snetts** [comment]
@enzonotario  Thanks it works great. I refactored and used dump-autoload and eveything works fine now.
