### ISSUE TITLE
Add support for a default count value for paginators

### ISSUE THREAD

**Issue by georgeboot** [nuwave/lighthouse#426]
**Is your feature request related to a problem? Please describe.**
Currently, when adding a paginator, you always have to specify the `count` argument in the query. This can sometimes be a bit annoying, especially when the number is shared across a lot of places and has some sort of "default".

**Describe the solution you'd like**
It would be great if one could define the default `count` value for a paginator. This default can still be overridden by the `count` argument specified in the query.

An example of the present:

```gql
type Query {
  posts: [Post]! @paginate
}
```
```gql
query {
    posts(count:50) {
        id
        name
    }
}
```
```gql
query {
    posts(count:100) {
        id
        name
    }
}
```

The proposed workflow:
```gql
type Query {
  posts: [Post]! @paginate(defaultCount: 50)
}
```
```gql
query {
    posts {
        id
        name
    }
}
```
```gql
query {
    posts(count:100) {
        id
        name
    }
}
```

**Comment by spawnia** [comment]
That seems like a great idea! We might even add a default for the defaultCount 😉 

What would be a reasonable default?

**Comment by mfn** [comment]
> add a default for the defaultCount

To me knowledge, Laravel doens't have so this library shouldn't have one, either.

Also: saves the discussion what value to pick :p

**Comment by georgeboot** [comment]
The default value should obviously be set by the developer in the schema definition in the `routes/graphql/schema.graphql` file.

@spawnia Laravel does indeed not have a default value for pagination, but it also does not have GraphQL (etc.) support. One of the powerful features of GraphQL is the ability to do things like this.

See [here](https://graphql.github.io/learn/schema/#arguments) for examples from the official GraphQL documentation.

**Comment by robsontenorio** [comment]
It can even better if that can be seted on lighthouse.php

**Comment by georgeboot** [comment]
That might work. Global default count in the config file. If you set it to `null`, you disable the global default count.

Then, per query, you can override (or set) the default count when specifying the paginator, like so:
```gql
type Query {
  posts: [Post]! @paginate(defaultCount: 50)
}
```

**Comment by spawnia** [comment]
Let's add this as a per-field option first.

@georgeboot `defaultCount` seems like a great argument name. If you can give the implementation a shot, that would be great.

Relevant code:
- https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/Fields/PaginationManipulator.php
- https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/Fields/PaginateDirective.php
- https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/Fields/HasManyDirective.php

And of course the accompanying tests:
- https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/Fields/PaginateDirectiveTest.php
- https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Schema/Directives/Fields/HasManyDirectiveTest.php

**Comment by georgeboot** [comment]
I'll give it a shot!
