### ISSUE TITLE
Bad argument default value in mutation

### ISSUE THREAD

**Issue by eossa** [nuwave/lighthouse#430]
**Describe the bug**
I define this mutation:

```graphql
createUser(
  name: String!
  type: String = "admin" @rules(apply: ["in:admin,user"])
): User
```

In playground I see this default value in the introspection:

```graphql
createUser(
  name: String!
  type: String = "{\\\\\\\"kind\\\\\\\":\\\\\\\"StringValue\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"user\\\\\\\",\\\\\\\"block\\\\\\\":false}"
): User
```

And I make this mutation in Playground:

```graphql
mutation {
  createUser(name: "Abelardo Addams") {
    id
  }
}
```

Then I log the request and I see:

```php
array (
  'name' => 'Abelardo Addams',
  'type' => 
  GraphQL\Language\AST\EnumValueNode::__set_state(array(
     'kind' => 'EnumValue',
     'value' => 'user',
     'loc' => NULL,
  )),
)
```

**Expected behavior**

**Schema**

```graphql
createUser(
  name: String!
  type: String = "user"
): User
```

**Environment**

Lighthouse Version:2.6.0
Laravel Version:5.7.11
PHP Version:7.1.12

**Additional context**

graphql-php version:.12.6

**Comment by spawnia** [comment]
Great find @eossa, i could replicate that buggy behaviour and was able to fix it. Had to put it in with the rather large #427 as my fix relies on some structural changes in there.
