### ISSUE TITLE
Allow defining an array of namespaces to try

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#439]
@sadnub has expressed interest in this feature.

It might be useful/necessary for some users to have classes that belong to the same group of functionality (e.g. Models, Queries) split across multiple namespaces.
The current default namespaces allow defining only one namespace though.

Let's discuss if multiple default namespaces are common enough to warrant the extra complexity and if we want to implement them, how we should go about it.

**Pro's**

- Convenient short definitions
- Enables grouping files by domain instead of function

**Con's**

- Extra complexity in the implementation without actually adding new functionality
- Possible source of bugs/ambiguity when you have the same class in different namespaces
- Goes against the Laravel-like default of grouping files by function, e.g. all Models in one directory

**Points to discuss**

- Should this be possible only for Models or for other default namespaces too?
- Can this only be done in `lighthouse.php` or is it also possible through `@group`?

**Comment by yaquawa** [comment]
Just some ideas.

If the resolving process where can be really complex, users can rebind some of the classes that are used for resolving the namespace in Lighthouse, or just redefine the default directive (can be done with #441)

**Comment by sadnub** [comment]
When I was trying to get this to work, I found that the code base only queries for the default model namespace in two methods. In each of those methods, it puts [ ] around namespaces value and tries to resolve the model in multiple namespaces. 

See https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/BaseDirective.php

Then look at methods getModelClass and namespaceClassName

This also holds true in the Pagnate directive. The same thing happens.

So my thought was to check if an array was already being passed from the configuration and if not turn it into an array. 

See my PR #434
