### ISSUE TITLE
Support user-based schema introspection

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#444]
**Benefits**
* more security
* less introspection data size

I submitted a question at the upstream lib https://github.com/webonyx/graphql-php/issues/405#event-1989218317

of course the best way to do this is using such a feature in the `webonyx/graphql-php`, but I think the chances are slim to none..

The basic idea is described at here.
https://github.com/graphql/graphql-js/issues/113#issuecomment-271124034

Implementation can be something like this:

1. Introspection request comes up.
2. Check if there is a correspond schema in the cache store for the requesting user, if not, generate one.
    1. scan all the schema, go through it, strip off invisible object type or fields, maybe based on the `@can` directive.
    2. Put the generated schema into cache with an unique id generated from the user id (or maybe type of user).
3. Return the generated schema.

Well Lighthouse can leave this as a extra package or an option, but at least should have some kind of mechanism to let plugin developer to hook into.

**Comment by spawnia** [comment]
I would have to see how hard this is to implement and maintain, but it seems like a niche case and should probably be solved in the base library.
