### ISSUE TITLE
Missing the "Users" page in the new docs

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#457]
Let's add a page for users of Lighthouse, as the old docs already did.

https://github.com/nuwave/lighthouse-docs/blob/master/website/users.js

**Comment by spawnia** [comment]
@robsontenorio could you give this a shot?

**Comment by robsontenorio** [comment]
Sure!

**Comment by robsontenorio** [comment]
It seems Chris already did it using custom html. I could refactor it later.

**Comment by chrissm79** [comment]
@robsontenorio Yeah, I tried to use a Custom layout before for the Home page but it seems that there's an [issue](https://github.com/vuejs/vuepress/issues/846) using custom layouts and server side rendering so it fails when it tries to build. I created a custom theme so I should be able to work around this issue, but still wrapping my head around Vue & Vuepress 😄

**Comment by robsontenorio** [comment]
@chrissm79 I don’t if was a good idea on creating a entire custom theme as you did. Because we can loose support from some core components  on future VuePress releases. You could rebuild entire front page without creating an entire custom theme.
