### ISSUE TITLE
Too few emojis

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#459]
The front page does not contain nearly enough emojis. How about we add the ones we had for a while back in?

**Comment by spawnia** [comment]
The original version of the new Vuepress docs had them for a bit. https://github.com/nuwave/lighthouse/blob/832763c75bf2b9ccb3924ef26e447a1be96497cb/docs/INDEX.md

How about we add the ones for the 3 features?

**Comment by chrissm79** [comment]
Ah gotcha! I'm still working on the branding a bit (footer and code blocks), I'll grab some nice line art that matches the Lighthouse logo a bit and use some of Tailwind's nice card styles to get them worked into the homepage!
