### ISSUE TITLE
Remove global function helpers entirely

### ISSUE THREAD

**Issue by mfn** [nuwave/lighthouse#499]
**Is your feature request related to a problem? Please describe.**

Interoperability with any kind of other software.

**Describe the solution you'd like**

Spin-off from https://github.com/nuwave/lighthouse/pull/488#issuecomment-445569623 : 

Forced global helper functions are always a PITA when integrating with other software.

Unfortunately for Laravel itself, they started this and for some poor souls it provides a hard barrier when having to integrate (especially) legacy software with modern ones like Laravel. Or lighthouse.

The biggest problem is that the global functions in `helpers.php` are forced upon everyone installing lighthouse due to the current `composer.json`:
```json
    "autoload": {
        "psr-4": {
            "Nuwave\\Lighthouse\\": "src/"
        },
        "files": [
            "src/Support/helpers.php"
        ]
}
```
This means everyone installing lighthouse gets the `helpers.php` loaded, whether they want or not.

Worse: some of the global helpers are used within the project itself (so they're not purely for convenience of users of the lighthouse library).

This means you a) force load global stuff to users which b) may or may not clash with other projects you're not ware of 💥

This is never good. Laravel does the same and it bites _some_ users (spoiler: I'm one of them).

And the funny side of this: it's simply not necessary.

Either provide namespaces functions (which can be a autoload PITA I've heard) or just slap a _namespaced_ class somewhere with static methods.

That it's possible to override their behavior (all the `function_exists` checks) is even worse:
- it's actually "not so" easy to override specifically on your own
- but if any other project also defining a same-named function is by accident loaded before, you've your clash already

Just a perspective of someone who had the pleasure integrating Laravel itself (not lighthouse) with other (legacy) software and just ended up in a world of pain, a situation which doesn't necessarily have to exist with a bit tactfulness.

**Describe alternatives you've considered**

n/a

**Additional context**

This issue serves as a discussion to come to a conclusion if and when to get rid of them, what the alternative if any will be, etc.

**Comment by spawnia** [comment]
I am all for removing those helpers, let's go for it!

**Comment by mfn** [comment]
Thanks `\o/`
