### ISSUE TITLE
Paginate builder with model class

### ISSUE THREAD

**Issue by okaybroda** [nuwave/lighthouse#502]
**Is your feature request related to a problem? Please describe.**

I was trying to write a common builder for a bunch of my models but the builder function doesn't receive a modelClass or model param to build from.

**Describe the solution you'd like**

The builder function receives the model as a param to build the query from.

**Describe alternatives you've considered**

The work around is to extend `PaginateDirective` and override `getPaginatedResults`
```
protected function getPaginatedResults(array $resolveArgs, int $page, int $first): LengthAwarePaginator
    {
        $resolveArgs[] = $this->getPaginatorModel();
        return parent::getPaginatedResults($resolveArgs, $page, $first);
    }
```
and then in the builder
```
public static function queryBuilder($root, array $args, $context, ResolveInfo $resolveInfo, $modelClass): Builder
```

**Comment by spawnia** [comment]
I think your workaround is pretty acceptable. The issue i am having is that `builder` was specifically introduced to paginate over something that has no model, so it feels out of place to pass it along in general.

You could also make small wrapper functions around your actual builder that just add on the model class and reference those in your schema.

**Comment by spawnia** [comment]
```graphql
type Query {
  posts: [Post!]! @paginate(builder: "App\Builder@posts")
  tasks: [Task!]! @paginate(builder: "App\Builder@tasks")
}
```

```php
namespace App;

class Builder
{
    public function posts()
    {
        return $this->builder(...func_get_args(), \App\Post::class);
    }

    public function tasks()
    {
        return $this->builder(...func_get_args(), \App\Task::class);
    }
    
    public function builder($root, array $args, $context, $resolveInfo, string $modelClass)
    {
        // Do your thing
    }
}
```

**Comment by okaybroda** [comment]
Got it. Thanks!
