### ISSUE TITLE
lighthouse-php Not Working on Laravel 5.7

### ISSUE THREAD

**Issue by kingsleyudenewu** [nuwave/lighthouse#504]
**Describe the bug**

I installed laravel 5.7 with lighthouse-php package and the result i always get is server not found.

**Expected behavior**

**Schema**

```
{
  user(id: 1) {
    id
    name
    email
  }
}
```

**Output/Logs**

Server not found

```
# Add in log output/error messages here
```

</details></br>

**Environment**

Lighthouse Version:2.6
Laravel Version: 5.7
PHP Version: 7.2.1

**Comment by mfn** [comment]
That's a bit ... light (<- pun intended 😄 ) on details, really.

Any logs? What requests did you try? Your config? etc.

**Comment by spawnia** [comment]
You can hop into [Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWI1ZDQ1YWM1NmM2MmQ0NTU0NGNjZWFkMTJhY2VjMDAwZmMyZDFlZTc1Mjc3ZGY0MWM1Y2Q5MWNjYmJmYWJkYmU) for those kinds of questions. Thanks!
