### ISSUE TITLE
@can directive not working as expected.

### ISSUE THREAD

**Issue by muhammadbinnaeem** [nuwave/lighthouse#505]
schema file :
```
admin(id: ID @eq): Admin @find(model: "App\\Admin") 
@can(if: "view", model: "App\\Admin" , policy: "App\\Policies\\AdminPolicy")
```

AuthServiceProvider file:
```
  protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
        Admin::class => AdminPolicy::class,
    ];
```

AdminPolicy file :
```
public function view(Admin $user, Admin $admin)
    {
        return  true;
    }
```

GraphQL Response:
```
"errors": [
    {
      "extensions": {
        "guards": []
      },
      "message": "Not authenticated to access this field.",
      "category": "authentication",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "admin"
      ],
      "trace": [
        {
          "file": "/opt/lampp/htdocs/videolevels/vendor/nuwave/lighthouse/src/Schema/Directives/Fields/MiddlewareDirective.php",
          "line": 84,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\CanDirective::Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
```

Everything else is working fine except "@can" use. 
returning true in view function should allow me to access that function but every time i get "Not authenticated to access this field."

**Comment by spawnia** [comment]
@liepaja exactly right, this means you are not even logged in so Lighthouse does stop before even attempting the policies. Clarified the error messages. #515

**Comment by muhammadbinnaeem** [comment]
I am logged in but after reviewing @can directive in vendors folder I found it is using auth() function without parameter and my logged in function work with auth('api') , therefore I made my own directive with auth('
api').Thank you for the response.

**Comment by spawnia** [comment]
Hm that seems like it should be possible without you having to make your own directive.

**Comment by Harizanov** [comment]
If you just specify in your laravel config/auth.php the default guard as 'api', then you shouldn't have problems. @can directive works nice
