### ISSUE TITLE
Many To Many Polymorphic

### ISSUE THREAD

**Issue by IhorNaprienko** [nuwave/lighthouse#506]
Hi
My model "Customer" uses "Many To Many Polymorphic Relations" 
How I can get pivot in result? 
for example
$customer = \App\Models\Customer::find($id);
foreach($customer->emails as $email){

               echo  $email->id;
               echo  $email->name;
               echo  $email->pivot->address;

           };
Can someone answer my question?
Thanks

**Comment by morpheus7CS** [comment]
Hey,

you can follow the documentation on many to many relationships: https://lighthouse-php.com/2.6/guides/relationships.html#many-to-many

Hope it helps!

**Comment by spawnia** [comment]
Please ask questions in Slack rather then here.

For such complex cases, look into custom resolvers such as:

https://lighthouse-php.com/2.6/api-reference/directives.html#method
