### ISSUE TITLE
Argument names in nested mutations conflict with non-relation methods on the model

### ISSUE THREAD

**Issue by sadnub** [nuwave/lighthouse#507]
**Describe the bug**
I am using the Spatie Permissions package and there is a 'guard' field on the Role class. When I try to return that field with a query, it will run the Model::guard() method.

**Expected behavior**
Return guard field from the database

**Schema**

```graphql
#types
type Role{
    id: ID!
    name: String!
    guard: String
}

#Inputs
input AddRoleInput {
    name: String! @rules(apply: ["required"])
    guard: String
}

input EditRoleInput {
    id: ID! @rules(apply: ["required"])
    name: String
    guard: String
}

#Add Queries to Base Query
extend type Query {
    roles: [Role!]! @all
    role(id: ID! @eq): Role! @find
}

#Add Mutations to Base Mutation
extend type Mutation {
    addRole(input: AddRoleInput!): Role! @create(flatten: true)
    editRole(input: EditRoleInput!): Role! @update(flatten: true)
    #editRoles(
    #    ids: [ID!]! 
    #    input: EditUsersInput!): [User!]! @bulk(flatten: true)
    deleteRole(id: ID!): Role! @delete
    deleteRoles(id: [ID!]!): [Role!]! @delete
}
```

**Output/Logs**
```
TypeError: Too few arguments to function Illuminate/Database/Eloquent/Model::guard(), 0 passed in /var/www/simple-rmm-appeval()'d code on line 1 and exactly 1 expected
```

**Environment**

Lighthouse Version: 2.6.3
Laravel Version:5.7.16
PHP Version: 7.2.12

**Additional context**

This seems to be the method it is getting caught up on. I'm not sure if there is a way to check if the method exists only on the model child class.
```
    protected static function extractHasManyArgs(Model $model, Collection $args): Collection
    {
        return $args->partition(function ($value, $key) use ($model) {
            return method_exists($model, $key) && ($model->{$key}() instanceof HasMany);
        });
    }
```

**Comment by liepaja** [comment]
As far as i know currently the Guard functionality is managed via @can directive. However if your guard is expecting a model, currently it is not being provided.

**Comment by chrissm79** [comment]
@sadnub You could use the [`@field` directive](https://lighthouse-php.com/2.6/api-reference/directives.html#field) here (or create a method on the model and use the [`@method` directive](https://lighthouse-php.com/2.6/api-reference/directives.html#method)).

```graphql
type Role {
    id: ID!
    name: String!
    guard: String @field(resolver: "App\\GraphQL\\Types\\RoleType@guard")
}
```

```php
namespace App\\GraphQL\\Types;

class RoleType
{
    public function guard(Role $root)
    {
        return $root->guard;
    }
}
```

**Comment by chrissm79** [comment]
@sadnub That is indeed some odd behaviour. could you do me a favor and update your schema to the following:

```graphql
extend type Query {
    roles: [Role!]! @field(resolver: "App\\GraphQL\\Types\\QueryType@roles")
}
```

and create the class

```php
namespace App\GraphQL\Types;

class QueryType
{
    public function roles()
    {
        return \App\Role::all();
    }
}
```

Let me know if the error still occurs, this should help point us in the right direction.

**Comment by sadnub** [comment]
I think I narrowed it down. If I remove the 'guard' field from the input object and add it as a argument directly on the mutation like so.

I thought this was affecting queries but only mutations with input objects
```
#Add Mutations to Base Mutation
extend type Mutation {
    addRole(input: AddRoleInput!, guard: String): Role! @create(flatten: true)
    editRole(input: EditRoleInput!, guard: String): Role! @update(flatten: true)
    #editRoles(
    #    ids: [ID!]! 
    #    input: EditUsersInput!): [User!]! @bulk(flatten: true)
    deleteRole(id: ID!): Role! @delete
    deleteRoles(id: [ID!]!): [Role!]! @delete
}
```
It works without any custom resolvers. So it might be the flatten functionality trying to check if the arg is a relation or not. My workaround works for me, but this might bite someone else. 

It could also be bad if Laravel adds any methods to the Model class or it's traits that matches any input object arguments.

**Comment by chrissm79** [comment]
It's still pretty odd that the `@field` defined on the `Role` type isn't overwriting the output, that doesn't seem right. Thanks for reporting btw!!

**Comment by spawnia** [comment]
What query in particular triggers the error?

**Comment by spawnia** [comment]
This textual description of what you are querying is unclear for me. Can you just post the exact query you are sending and the complete error message?

**Comment by sadnub** [comment]
The relevant schema would be:

```
#types
type Role{
    id: ID!
    name: String!
    guard: String
}

#Inputs
input AddRoleInput {
    name: String! @rules(apply: ["required"])
    guard: String
}

#Add Mutations to Base Mutation
extend type Mutation {
    addRole(input: AddRoleInput!): Role! @create(flatten: true)
}
```

The mutation on the client side is
```
#Fragments
fragment RoleFields on Role {
  id
  name
  guard
}

mutation addRole($input: AddRoleInput!) {
  editRole(input: $input) {
    ...RoleFields
  }
}
```

If I call the addRole mutation with the following arguments:

```
{
  "input": {
    "name": "Admin",
    "guard": "api" 
  }
}
```
I will get this error
```
TypeError: Too few arguments to function Illuminate/Database/Eloquent/Model::guard(), 0 passed in /var/www/simple-rmm-appeval()'d code on line 1 and exactly 1 expected
```
Instead of returning the guard field, it is calling the guard() method on the model. Digging into the lighthouse source I found this was the case when trying to see if the arg is a relationship. It checks if the method exists (which it does) and it calls the method to see if it is an instance of the relationship.

```
protected static function extractHasManyArgs(Model $model, Collection $args): Collection
    {
        return $args->partition(function ($value, $key) use ($model) {
            return method_exists($model, $key) && ($model->{$key}() instanceof HasMany);
        });
    }
```
Not sure if there is a way to exclude inherited methods from this check.

Hope this helps!

**Comment by spawnia** [comment]
Thanks for your last comment, you narrowed down the issue really well.

We might be able to work around this by using reflection on the method and looking at its return type, however that would only work if all used relationship methods have a return type definition.

Another option would be to wrap the call in a try/catch Block. While this would prevent errors, it may have unintended side effects because the method is still called.

@yaquawa @liepaja any ideas how we can solve this?

**Comment by yaquawa** [comment]
> We might be able to work around this by using reflection on the method and looking at its return type, however that would only work if all used relationship methods have a return type definition.

This is the perfect solution for me.
Having the method have the return type definition is always a good practice.
If the method doesn't have a return type definition, we can simply skip that field.
All we need is just add some extra description to the docs.

**Comment by liepaja** [comment]
In this case guard() should not be called as it is not instance of Relation right?

**Comment by liepaja** [comment]
In this case basic get_class_methods() will work as well right?

**Comment by spawnia** [comment]
Performance for nested mutations won't be great anyways. Let's try a naive approach first and possibly optimize if needed.

**Comment by liepaja** [comment]
Is there already a PR for this?

**Comment by spawnia** [comment]
@liepaja The following should work.

Can you work in that change with #514 ?

```php
    /**
     * Extract all the arguments that correspond to a relation of a certain type on the model.
     *
     * For example, if the args array looks like this:
     *
     * [
     *  'comments' =>
     *    ['foo' => 'Bar'],
     *  'name' => 'Ralf',
     * ]
     *
     * and the model has a method "comments" that returns a HasMany relationship,
     * the result will be:
     * [
     *   [
     *    'comments' =>
     *      ['foo' => 'Bar'],
     *   ],
     *   [
     *    'name' => 'Ralf',
     *   ]
     * ]
     *
     * @param \ReflectionClass $model
     * @param Collection       $args
     * @param string           $relationClass
     *
     * @return Collection
     */
    protected static function partitionArgsByRelationType(\ReflectionClass $model, Collection $args, string $relationClass)
    {
        return $args->partition(
            function($value, string $key) use ($model, $relationClass){
                if(! $model->hasMethod($key)){
                    return false;
                }

                $relationMethodCandidate = $model->getMethod($key);
                if(!$returnType = $relationMethodCandidate->getReturnType()){
                    return false;
                }

                if(! $returnType instanceof \ReflectionNamedType){
                    return false;
                }

                return $returnType->getName() === $relationClass;
            }
        );
    }
```

**Comment by liepaja** [comment]
Yes, i can do that, but i was thinking that is is a more urgent bug. I don't expect finishing #514 before end of next week or so. Is that not too long @spawnia ?

**Comment by spawnia** [comment]
I am a busy with other stuff atm, if someone else can prep a PR including a test that would be great.

**Comment by liepaja** [comment]
`getReturnType()` always returns NULL in my case.
