### ISSUE TITLE
Allow configuration of the authentication mechanism

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#516]
**Is your feature request related to a problem? Please describe.**

https://github.com/nuwave/lighthouse/issues/505#issuecomment-447801530

Laravel applications might have different ways of authenticating a user. For example, authentication for server-rendered view usually works differently then authentication for an API, like GraphQL.

Lighthouse is currently using the `auth()` helper in a few places, which always retrieves a user by the default authentication method.

**Describe the solution you'd like**

Add a global configuration that allows the user to define what authentication method is used for Lighthouse and use that throughout the codebase.

**Comment by liepaja** [comment]
In my case auth is custom jwt based and is handled within Service Provider. That way regular methods work.

**Comment by muhammadbinnaeem** [comment]
Regular method works perfect with JWT as well but if you are handling multiple logins with JWT or without JWT then you will need to use auth function with different parameter.Suggestion for that in lighthouse config file there should be an optional parameter for passing in auth function will cover all scenarios.

**Comment by liepaja** [comment]
Can you give an example where ServiceProvider can't handle it?

**Comment by spawnia** [comment]
I think we are doing fine here, auth provider registered through the ServiceProvider work with Lighthouse.
