### ISSUE TITLE
Relay Modern

### ISSUE THREAD

**Issue by Gugudesaster** [nuwave/lighthouse#52]
Hey guys, I love that lucasmichot and chris are doing so much work on the package right now.
Thanks guys.

Since Relay Modern is coming out soon, I wanted to ask if you plan on making it work with it or if it maybe works with it already?

I am going to start a new project and I'm not sure if I should start it with laravel because I would love to start with Relay modern right away.
What do you guys think about the roadmap for the next couple of months?

**Comment by Gugudesaster** [comment]
Relay Modern is out.
https://github.com/facebook/relay/releases/tag/v1.0.0

Just a short info would be great. I will have to look for something else otherwise.
Thanks guys.

**Comment by chrissm79** [comment]
Lighthouse v2.0 auto-generates connections/edges and you can implement the `Node` interface on any of your types. I believe that should be everything you need but feel free to reach out if something is missing.
