### ISSUE TITLE
Use `@rename` on arguments/input object values

### ISSUE THREAD

**Issue by Cmarenburg** [nuwave/lighthouse#521]
Hi All,

I've dug into the source code and can't really find answer, does the rename directive only apply to 'normal' types. IE. 
`type User {...}`

I was hoping I could use it on an Input to convert from camel case (in the schema) to snake case. However my experience using the `@rename` directive in `input`s has been that it doesn't work/rename the fields as it does in `type` sets. Wondering if that is intentional or if I might not be doing something right.  

Here is what I'm doing currently that isn't renaming camel case to snake case

```graphql
input CreateCustomerInput {    
    firstName: String! @rename(attribute: "first_name") @rules(apply: ["required","string"]) 
    lastName: String! @rename(attribute: "last_name") @rules(apply: ["required","string"])
    email: String! @rules(apply: ["required","string","email","unique:customers,email"])
    addresses: [GeneralAddressInput]
}
```

**Comment by yaquawa** [comment]
@spawnia 
if the purpose is just changing the "argument name" in the resolver, I think something like this would work:

```php
// in the resolver..


// handle the `ArgDirective`s

// replace key-name according to the `@rename`
$args['first_name'] = $args['firstName'];
unset($args['firstName']);

// pass to the downstream resolver...
```

**Comment by Cmarenburg** [comment]
> @Cmarenburg `@rename` does not have the capability that you describe at the moment, although i think it would be a reasonable feature to add.
> 
> We have to figure out at what point during execution the renaming actually occurs. I think the most obvious point in time would be just before the arguments are actually passed to the final resolver. This would make it so that complex validation rules would reference the argument names just as they are defined in the schema.
> 
> @yaquawa what do you think?

Ahh Okay, glad to know I'm not crazy! I'm not involved with the project, but where you describe renaming sounds like a logical solution to me. 

> @spawnia
> if the purpose is just changing the "argument name" in the resolver, I think something like this would work:
> 
> ```
> // in the resolver..
> 
> 
> // handle the `ArgDirective`s
> 
> // replace key-name according to the `@rename`
> $args['first_name'] = $args['firstName'];
> unset($args['firstName']);
> 
> // pass $args to the downstream resolver...
> ```

This Is essentially what I'm doing in a mutation resolver currently

**Comment by spawnia** [comment]
@yaquawa that looks like a good start. I see some additional complexity within nested inputs - same as validation, we need to walk the tree of incoming arguments and apply the transformation.

As we have to apply validation and other arg directives first, we need to have a way to run this afterwards. Maybe we can find generalize this part where we traverse the concrete inputs in combination with the schema definitions?

**Comment by yaquawa** [comment]
@spawnia Maybe we should get the `ArgMiddlewareDirective` interface back as a "generic" purpose argument directive?

I think something like this would work:

```php
class RenameDirective implements ArgMiddlewareDirective {
    public function handleArg($value): void
    {
        $this->rename($this->getNewPath(), $value, $this->getArgs());
    }

    protected function rename($newPath, $value, &$args): void
    {
        // alter the $args ...
    }
}
```

also, to get this work, the `@rename` must be the last argument.

```graphql
input CreateCustomerInput {
  firstName: String! 
  @trim
  @rules(apply: ["required","string"])
  @rename(attribute: "first_name") 
}
```


> The webonyx AST Visitor does seem to serve a slightly different purpose, but maybe we get some inspiration from it.

Looking promising! This may simplify the existing code a little bit I think😀.

**Comment by spawnia** [comment]
Closing in favour of #538

**Comment by SirLamer** [comment]
I believe this issue remains unresolved despite #538. Rename doesn't work on input fields and they only work in the property name exactly matches the syntax used in laravel (ex. snake case).

Ideally the input fields would reference the rename directives placed on matching properties in the Type definition.

**Comment by spawnia** [comment]
Right, it is still open. You can contribute a PR if you want to move this forward.

**Comment by markokeeffe** [comment]
I had a look at putting together a PR for this, but couldn't figure out a way to get it hooked up. Would love to see this functionality in the package!

**Comment by spawnia** [comment]
@markokeeffe this functionality should be pretty straightforward to implement through the `ArgumentSet` class.

The actual renaming step could be done in the `FieldFactory` where `@spread` is also applied.

**Comment by JasonTheAdams** [comment]
Taking a shot at this.
