### ISSUE TITLE
[FEATURE REQUEST]: Add message support for validation.

### ISSUE THREAD

**Issue by joshmanders** [nuwave/lighthouse#53]
Be cool if we could have a `messages` array that can go with `rules` on mutation args so we can define what we want the message to be for that validation.

**Comment by chrissm79** [comment]
Plan on allowing custom validators on mutation fields, just finding the best way to do so. I would love to re-use Form Requests but not sure how to pull that one off at the moment.

**Comment by spawnia** [comment]
Implemented as of #176, will be available in v2.2
