### ISSUE TITLE
Fully qualified class names in PHPDoc

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#530]
Laravel seems to refer to classes by their FQCN in PHPDoc blocks but imports them otherwise, for example:

```php
use Illuminate\Support\Collection;

/**
 * @return \Illuminate\Support\Collection
 */
function foo(): Collection
```

Do you think we should stick with that convention?

@lucasmichot are there any exceptions to this rule?

Is there an automated refactoring/transformation available for this in PHPStorm?

**Comment by lucasmichot** [comment]
There is no exception.
There is a setting in PHPStorm to ensure the newly created docblocks are with FCQN notations.
No refactoring tool (php-cs-fixer...) that I know provide any transformer.

**Comment by spawnia** [comment]
Can you post a screenshot where that setting is made?

I think the easiest transformation should be to simply delete and recreate the relevant parts of the DocBlocks.

**Comment by lucasmichot** [comment]
<img width="950" alt="screenshot 2018-12-31 at 19 13 13" src="https://user-images.githubusercontent.com/513603/50565541-2e6d0a00-0d30-11e9-8ef4-a3a272e4a175.png">

**Comment by spawnia** [comment]
Since it is the Laravel way, we will do PHPDocs with FQCN in the future. I will keep this issue open until we converted all Doc blocks.

**Comment by lucasmichot** [comment]
I guess this can be closed @spawnia :-)
