### ISSUE TITLE
@throws annotations in PHPDoc blocks

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#531]
Let's discuss on how we should annotate thrown exceptions in the code.

http://docs.phpdoc.org/references/phpdoc/tags/throws.html

I think that annotating exceptions in the method where it is thrown is a no-brainer.

A rather interesting question is if we should bubble up the annotations, e.g.

```php
/**
 * @throws Exception
 */
function foo(){
  throw Excection();
}

/**
 * Should this annotation be here or not?
 * @throws Exception
 */
function bar(){
  foo();
}
```

**Comment by chrissm79** [comment]
Closing for now, if this is something that becomes available through an integration tool such as StyleCI we can re-open and discuss.
