### ISSUE TITLE
@scalar directive throws exception if class name or namespace is not defined in schema

### ISSUE THREAD

**Issue by alberthaff** [nuwave/lighthouse#568]
**Describe the bug**

The `@scalar`-directive seems to require a class name or namespace.

The `resolveScalarType` in `NodeFactory` does not receive the class name if it is not defined as an argument on the `@scalar`-directive in the schema.

**Expected behaviour**

The Scalar should default to the namespace for scalars defined in `config/lighthouse.php` when a class name / namespace is not defined.

**Schema**

My definition in my schema (not working):
```GraphQL
scalar File @scalar
```

My definition in my schema (working):
```GraphQL
scalar File @scalar(class: "FileScalar")
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
Argument 1 passed to namespace_classname() must be of the type string, null given, called in /Users/alberthaff/git/my-project/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php on line 207
```

</details></br>

**Environment**

Lighthouse Version: 2.6.3
Laravel Version: 5.6.26
PHP Version: PHP 7.2.3

**Additional context**

Might be a duplicate of #388.

**Comment by spawnia** [comment]
Your scalar should be named `File`.

**Comment by alberthaff** [comment]
Thanks. I did not know that `@scalar` is no longer required.
However, it throws the same exception when the class is named `File` (only when using `@scalar`).

**Comment by spawnia** [comment]
Have you tried `dev-master`?

**Comment by alberthaff** [comment]
No, I am using v. 2.6.3. I assume that `dev-master` isn't stable.

**Comment by alberthaff** [comment]
Alright, i'll give it a try. :-)
