### ISSUE TITLE
Edge command runs out of memory

### ISSUE THREAD

**Issue by selfeky** [nuwave/lighthouse#57]
Thank you for the amazing package :)

I have an issue with the edge command, not sure if its related to my env.

php artisan lighthouse:edge Competition

The command runs out of memory (1024 MB)

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 45056 bytes) in /Users/sherief/Development/git/dice/backend/vendor/laravel/framework/src/Illuminate/Console/GeneratorCommand.php on line 92
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32768 bytes) in /Users/sherief/Development/git/dice/backend/vendor/symfony/debug/Exception/FatalErrorException.php on line 1

Any one facing the same issue?

Thanks

**Comment by chrissm79** [comment]
v2.0 uses a new method to generate connections/edges. Let me know if this is still an issue though!
