### ISSUE TITLE
PageInfo returns incorrect cursor

### ISSUE THREAD

**Issue by selfeky** [nuwave/lighthouse#58]
Hey everyone,

I was implementing relay modern paginated container when I came across and pagination bug or a misconfiguration from my side.

`
fragment Tournaments_diceviewer on Dice {
    competitions(after: null, orderby: "id", hasLeagueTableOnly: true) {
        pageInfo {
              count
              total
              currentPage
              hasNextPage
              endCursor
              hasPreviousPage
              startCursor
        }
        edges {
            cursor
            node {
                id
                name
                short_name
                full_name
                image
                order
                __typename
                }
            }
        }
}
`
The above fragment queries the connections and returns the first 15 nodes with now problem.
The endCursor returned in the first 2 pages is correct. Then on page 3, the endCursor returned is for the last record in the collection.

I had a look at the PageInfoType definition and came across this:

`
'endCursor' => [
                'type' => Type::string(),
                'description' => 'When paginating forwards, the cursor to continue.',
                'resolve' => function ($collection) {
                    if ($collection instanceof LengthAwarePaginator) {
                        return $this->encodeGlobalId(
                            'arrayconnection',
                            $collection->lastItem() * $collection->currentPage()
                        );
                    }
                },
            ],
`
I don't understand line 71 or $collection->lastItem() * $collection->currentPage()

What I did was I removed the "* $collection->currentPage()" and everything works great

As for my connection definition:

`
public function resolve($parent, array $args, $context, ResolveInfo $info)
{
    return $parent->competitions()->getConnection($args);
}
`
competitions() returns a simple eloquent hasMany

Please advise
Thanks

**Comment by hailwood** [comment]
Related to #18

**Comment by chrissm79** [comment]
This has been updated w/ v2.0 but let me know if you are still experiencing this issue.

**Comment by mobilerndev** [comment]
please recheck
