### ISSUE TITLE
Enable updating the children of nested mutations within a single request

### ISSUE THREAD

**Issue by JoeSchr** [nuwave/lighthouse#583]
As discussed on slack this quick example should be possible to do:

```graphql
mutation {
  updateTermin(input: {  
    id: 1
    scheduled_at: "2019/01/01"
    customer: { 
      connect: {
        id: 1
        email: "joe@example.com" # also changed email in same request 
      }
    } 
  }) {
    id
  }
}
```

I'm always frustrated when I have to parse through my "parent" object, pick out all nested relationship, parse them into `connect`/`create` categorie for one request, to tie the relationship together. THEN I have to make another mutation, like e.g. "updateNestedChildren" to also update the data of the nested children. Ideally it should be possible to update with the same object I got from the query, without reparsing. 
The relationship is already defined in schema.graphql and/or the laravel Model.php

**Describe the solution you'd like**
I think it would be even better, if an "magical" approach would be possible, so you could just send data back and forth without reparsing it all the time. (except `__typename`, seems we always will have to omit `__typename`...)

Like this: 
```graphql
mutation {
  updateTermin(input: {  
    id: 1
    scheduled_at: "2019/01/01"
    customer: { 
        id: 1
        email: "joe@example.com" # also changed email in same request 
    } 
  }) {
    id
  }
}
```

**Describe alternatives you've considered**

I researched #131 and #207 and read the @master docs about nested mutations and asked on slack

**Additional context**
For my client I'm using `vue.js` with `vue-apollo`. I love that the querys from graphql/lighthouse is just one big json/object which I then can edit with my components. I'm frustrated that updating this is such an headache, instead of just sending it back the way it came.

From conversation over at slack @2019/01/22:

> 
> Joe [6:20 PM]
> he, I'm stil trying to figure out how to use nested mutations
> regarding this point in the docs:
> Pasted image at 2019-01-21, 6:20 PM 
> 
> I only can connect my model with existing nested relationship via the ID field, what I can't do is something like this:
> ```
> input CreateAuthorRelation {
>   connect: UpdateUserInput
>   create: CreateUserInput
> }
> 
> input UpdateUserInput {
>   id: ID
>   name: String
> }
> ```
> (edited)
> were I also update other fields, in this example, `name` at the same time.
> so what I basically want to do is to update my whole model included all nested mutations but also if something changed in the nested mutation, that should be updated at the same go. this is not possible currently, right?
> maybe a mutation example explains it best:
> ```
> mutation {
>   updatePost(input: {  
>     id: 1
>     title: "Changed Titled"
>     author: { 
>       connect: {
>         id: 1
>         description: "Also changed author descriptions"
>       }
>     } 
>   }) {
>     id
>   }
> }
> ```
> 
> Joe [6:39 PM]
> are you guys creating update/create mutation for every nested mutation? I don't get how you can work with bigger, more nested object efficently?
> 
> Joe [6:50 PM]
> do you omit every property with a nested relationship before you send it to update?
> that seems absurd?
> 
> spawnia [10:21 PM]
> Hey @Joe i think you bring up a totally valid point about updating the children of nested mutations
> This seems like it should be possible, feel free to open an issue to GitHub or provide a PR with an implementation
> We decided against allowing it in our work project, but since it can be controlled via the schema definition, Lighthouse should offer the capability for users that require such

**Comment by JoeSchr** [comment]
This is how prisma handles it: (from [here](https://www.prisma.io/docs/prisma-graphql-api/reference/mutations-qwe2/#nested-mutations))
```graphql
mutation {
  updateUser(
    data: {
      posts: {
        update: [
          {
            where: {
              id: "cjcf1cj0r017z014605713ym0"
            }
            data: {
              title: "Hello World"
            }
          }
        ]
      }
    }
    where: {
      id: "cjcf1cj0c017y01461c6enbfe"
    }
  ) {
    id
    posts {
      id
    }
  }
}
```

But I figure, since we already have defined the relationship and know what's the primary key (via laravel Model), maybe the where isn't need, if you use e.g. id or any other uiid?

**Comment by spawnia** [comment]
We require a unique ID for updates, so the example from prisma would look like this in Lighthouse:

```graphql
mutation {
  updateUser(
    id: "cjcf1cj0c017y01461c6enbfe"
    posts: {
      update: [
        {
          id: "cjcf1cj0r017z014605713ym0"
          title: "Hello World"
        }
      ]
    }
  ) {
    id
    posts {
      id
    }
  }
}
```
