### ISSUE TITLE
Enhance documentation for nested mutations

### ISSUE THREAD

**Issue by bibiseb** [nuwave/lighthouse#586]
Hello,

I am new to GraphQL and tried the laravel-graphql package from Folkloreatelier. Reading the issues I found a post that guides me here and that was about nested mutations. [#313](https://github.com/Folkloreatelier/laravel-graphql/issues/313#issuecomment-421802028)

Could you please document that lighthouse feature ?

PS: I have plenty of questions and I'd like to join your Slack can you help me for that ?

**Comment by spawnia** [comment]
The docs could surely use some love. The way that nested updates work is not quite solidified, but let's make sure to document it properly as we implement it.

You can just follow the link to Slack in the README.
