### ISSUE TITLE
Is it possible to subscribe to changes without a second request?

### ISSUE THREAD

**Issue by alberthaff** [nuwave/lighthouse#589]
Please note that i may have overlooked something. But according to the docs, it doesn't seem like it is possible to subscribe to changes within a query.

Wouldn't it be a great addition, to be able to subscribe to changes like this?

```GraphQL
query {
    user(id: 1, subscribe: true) {
        firstName
        lastName
    }
}
```

With response:
```JSON
{
    "data": {
        "user": {
            "firstName": "Rick",
            "lastName": "Sanchez"
        }
    },
    "extensions": {
        "lighthouse_subscriptions": {
            "version": 1,
            "channels": {
                "userUpdated": "private-xxxxxxxxxxxxxx"
            }
        }
    }
}
```

This would save me following request:
```GraphQL
subscription userUpdated {
    userUpdated(id: 1) {
        firstName
        lastName
    }
}
```

This should be possible with a directive applied to my `User`-node.
I think the best place would be to add it to the `@model`-directive (if it is possible for a directive applied on a node, to add a new field to all paginators, paginating nodes with said `@model`-directive applied), since the model-directive is already used on all nodes that can be updated. If the `@model`-directive were to accept a new attribute, containing the name of the subscription-node for the specific node/ model, it should be pretty simple to return a subscription-channel along with the requested data.

It would also make it easier to subscribe to changes on a paginator, since you won't have to manually subscribe to each node returned.
However,, it would probably be a good idea, to also add a mutation to unsubscribe, since the suggestions above would greatly increase the number of subscriptions.

Is this a feature, that you would consider adding? I would be happy to help.

**Comment by spawnia** [comment]
Did you look at https://lighthouse-php.com/master/extensions/subscriptions.html yet?

**Comment by alberthaff** [comment]
Yes. The only example is a dedicated request to subscribe to subscribe to `postUpdated`:

```GraphQL
subscription onPostUpdated($post_id: ID!) {
    postUpdated(post_id: $post_id) {
        id
        title
        content
    }
}
```

I think it would be a great addition, if the same result was achievable, with a query like this, since it would save a request, and make the site more responsive:

```GraphQL
query Post($post_id: ID!) {
    post(post_id: $post_id, subscribe: true) {
        id
        title
        content
    }
}
```

The subscriptions works perfectly, but i think it should be easier to subscribe to changes.

The example above, would make it easier to automate subscriptions clientside, since the only change between something static, and something that i want to subscribe to, would be the `subscribe`-boolean on the `user`-node. If the user only wants to subscribe to specific fields, and not all the fields originally queried, they could still make a `subscription`-request and subscribe to the specific fields they want.

**Comment by spawnia** [comment]
That seems like something that can be implemented on the Client. The semantics of subscriptions are well-defined, and we are going to szick to that.

**Comment by alberthaff** [comment]
I don't think this can be solved clientside. 

Example: 

```GraphQL
query Customers {
	customers (count: 500, page: 1) {
		data {					
			id
			name		
			customerGroup {
				id
				name
			}
		}
		paginatorInfo {
			lastPage
		}
	}
}
```

Let's say that the query above returns 500 customers. The client must then send an additional 500  subscription-requests in order to subscribe to changes. With the suggested addition, this could be reduced to one request.

**Comment by spawnia** [comment]
You can offer a subscription like:

```graphql
type Subscription {
  customers: [Customer!]!
]
```

... and use that in the client, in addition to the query for the initial data.

When you do not want to save yourself writing the same frontend code for intial querying and then subscribing, you can abstract that on the client-side, given that your Schema follows a certain convention.

**Comment by alberthaff** [comment]
Thanks! I'll give it a try.
