### ISSUE TITLE
RelayConnection::scopeGetConnection breaks seeders.

### ISSUE THREAD

**Issue by hailwood** [nuwave/lighthouse#59]
### What is the issue?

The scope registered at 
[**nuwave/lighthouse:**/src/Support/Traits/RelayConnection.php#L18](https://github.com/nuwave/lighthouse/blob/master/src/Support/Traits/RelayConnection.php#L18) 
conflicts with a built in laravel method at 
[**laravel/framework:**/src/Illuminate/Database/Eloquent/Model.php#L1005](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php#L1005)

### Suggested fix?
so it looks like we need to change the scope name; 
Might I suggest we go with `scopeGetGraphQLConnection()`.

For consistency we should also rename `scopeLoadConnection()` to `scopeLoadGraphQLConnection()`.

These names are fairly precise but should avoid conflicts in the future as anything to do with `connection` seems to be quite dangerous grounds in Laravel.

Thoughts?

### exact error message below for "googlers" sake
> [Symfony\Component\Debug\Exception\FatalThrowableError]                                     
>  Type error: Too few arguments to function App\User::scopeGetConnection(), 1 passed in /var  
>  /www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 930 and  
>   exactly 2 expected

Note that the error is actually triggered from the `factory(...)->create()` method, however these are normally only used in seeders.

**Comment by hailwood** [comment]
If we can get the names approved for the scopes I'll fire this through as a PR;

Also if we're updating the name what do you think about updating the default macro name to something in line with these as well (it won't affect existing projects since their config would already be published).

**Comment by irakliOrbis** [comment]
I have the same error. How do you fix this?

**Comment by hailwood** [comment]
Fixed via #67
