### ISSUE TITLE
How can I use a custom default resolver?

### ISSUE THREAD

**Issue by frthjf** [nuwave/lighthouse#590]
Hi, first of all, thanks for this great package! It's amazing work. 

I'm integrating Lighthouse with a CMS system and I'm looking for a way to overwrite the [defaultResolver](https://github.com/nuwave/lighthouse/blob/f703a977a7983b9460396ce315cd235672bd66bb/src/Schema/Values/FieldValue.php#L189) for FieldValues. Is it possible to specify a custom default resolver that returns the resolve closure? 

I'm using the latest version 3.0 alpha.

**Comment by spawnia** [comment]
That is not possible at the moment. You can however add a custom directive and place that on you fields.

**Comment by spawnia** [comment]
I am not sure it is going to be event-based, but it could be useful to have a mechanism of extending this functionality.

Out of interest, what is your specific use case and what do you plan to do in the replaced default resolver?

**Comment by frthjf** [comment]
Right, to prevent an x-y-problem, here's my use-case: I have an CMS-like graphical editor for the Schema and corrresponding resolvers that creates files like this:

```
<?php
function resolveHello(...) {
    return 'world';
}
?>
===
type Query {
   hello: String
}
```

I have a parser that turns these flat-CMS files into a schema string (just like the [SchemaSticher@getSchemaString](https://github.com/nuwave/lighthouse/blob/f703a977a7983b9460396ce315cd235672bd66bb/src/Schema/Source/SchemaStitcher.php#L44)) and corresponding Lighthouse class definitions, e.g.
```php
<?php
namespace Queries;

class Hello() {
     function resolve(...) {
        return 'world';
     }
}
```
I basically generate the Lighthouse structure from my CMS files and then Lighthouse loads them from that structure. Now, it would be great if I could hook into the resolver construction directly and generate the resolver directly from my CMS files.

I'm able to overwrite the ``getSchemaString`` by rebinding the ``SchemaSourceProvider``, however, I can't hook in to overwrite the default resolver. 

I believe that concerns point 3 and perhabs 2 (although I currently don't support subscriptions).

Hope that clarifies my requirements.

**Comment by spawnia** [comment]
Interesting stuff! I am going on vacation, so i will only have a chance to look into this in a few weeks.

It seems like you found a reasonable way to resolve your issue, glad about that. Still, we might make cases like yours easier to extend.

Open to suggestions on how exactly we could do this in a way that is:
- flexible
- consistent
- reasonably complex

**Comment by frthjf** [comment]
Thanks for letting me know, there is no rush!

I believe a good spot to extend the default resolving mechanism is [FieldFactory@handle](https://github.com/nuwave/lighthouse/blob/b7d24698289b075f166a27db7a6897360557b0be/src/Schema/Factories/FieldFactory.php#L109). Currently, the handler is looking for directives and uses their resolver or falls back on the default resolver of ``FieldValue``.

If we introduced an event here that receives ``$fieldValue`` as argument, one could customise and extend the resolver and effectively introduce a custom default resolver. For example,

```php
if ($fieldResolver = $this->directiveFactory->createFieldResolver($fieldDefinitionNode)) 
{
    $this->fieldValue = $fieldResolver->resolveField($fieldValue);
}
event(new CreatingFieldDefinition($fieldValue));
$resolver = $this->fieldValue->getResolver();
```
would allow to define a totally custom resolver
```php
function (&$fieldValue) {
  $fieldValue->setResolver(...);
}
```
but also to extend the existing one returned by the directives or the default resolver.
```php
function(&$fieldValue) {
  $resolver = $fieldValue->getResolver()
  return function ($root, array $args, $context, ResolveInfo $resolveInfo) use ($resolver) {
     // extend resolving behaviour
     return $resolver($root, $args, $context, $resolveInfo);
  }
}
```
To me that seems like a flexible solution since it is basically a 'global directive' and it works much like a custom directive implementation. In fact, the Event listener class would look like a FieldResolver where ``handle()`` would be equivalent to ``resolveField()``. What do you think?

**Comment by frthjf** [comment]
@spawnia Do you have some feedback on that proposal?

**Comment by spawnia** [comment]
@frthjf as you noted yourself, the semantics of this approach do not feel quite right.

I think we could just extract the logic for getting a default resolver into an interface like this:

```php
<?php

namespace Nuwave\Lighthouse\Support\Contracts;

use Nuwave\Lighthouse\Schema\Values\FieldValue;

interface ProvidesDefaultResolver
{
    public function defaultResolver(FieldValue $fieldValue): \Closure;
}
```

**Comment by frthjf** [comment]
@spawnia I agree, that would be much simpler!

**Comment by frthjf** [comment]
That's great, thanks @spawnia!
