### ISSUE TITLE
How to use @search directive with scopes

### ISSUE THREAD

**Issue by 123mitnik** [nuwave/lighthouse#592]
what is the proper way to use scopes with the @search directive. 

if i try to use @search directive with scopes i get the following error:

"debugMessage": "Method Laravel\\Scout\\Builder::NAME_OF_THE_SCOPE does not exist."

it is trying to call the scope method on Scout

**Comment by 123mitnik** [comment]
If i try to create my own scout search with custom builder i hit another wall because the results can't be paginated 

"Laravel\\Scout\\Builder::paginate(10, array(1), 'page', 1)" this is how lighthouse is calling the paginate when i think the expected paginate call is with only one param. So this result in error: "A non-numeric value encountered"

Is there a way to do search and to use constraints like where and orderBy on the search and at the same time to paginate the result.

**Comment by memochou1993** [comment]
I use "@search" method.

It shows "A non-numeric value encountered", why?

**Comment by xahs** [comment]
It happens because of different method signature:

```php
Illuminate\Database\Eloquent\Builder::paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
Laravel\Scout::paginate($perPage = null, $pageName = 'page', $page = null)
```

When laravel Scout is configured, Lighthouse calls paginate method with the extra ```$columns``` parameter.

This temporary workaround fixes to problem.

```php
// Nuwave\Lighthouse\Schema\Directives\Fields\PaginateDirective

protected function getPaginatedResults(array $resolveArgs, int $page, int $first): LengthAwarePaginator
{
    ...

    if ($query instanceof \Laravel\Scout\Builder) {
        return $query->paginate($first, 'page', $page);
    }

    return $query->paginate($first, ['*'], 'page', $page);
}
```

**Comment by spawnia** [comment]
@xahs this fix looks fine to me, can you provide a PR? (If possible with a test) :)
