### ISSUE TITLE
Field case insensitive

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#595]
Considering this Type

```graphql
type User{
    id: ID!
    firstName: String
}
```

So, `firstName` will be `null`,  because original column from database is `firstname`. I know we can use `@rename`. But it is a bit boring, because is just a "camelCase", not full rename. Is there any option in order to make field names  CASE INSENSITIVE when parsing column names?

**Comment by spawnia** [comment]
Both GraphQL and PHP are case sensitive, so we should keep it that way.

I recommend you name things consistently.

**Comment by SirLamer** [comment]
A directive to apply to an input type, or maybe a global setting in the config file, would be appropriate since this pattern will be common. PHP / Laravel historically has favored snake_case while JavaScript devs tend to favor camelCase, and the trend in toward camelCase.

**Comment by spawnia** [comment]
@SirLamer #521 will be a first step.
