### ISSUE TITLE
[Question] How to make a wildcard search with like operator?

### ISSUE THREAD

**Issue by a-ssassi-n** [nuwave/lighthouse#600]
My previous query before using LightHouse:

`$locations = Location::where('name', 'LIKE', "%$query%")->get();`

Current Query with LightHouse

`searchLocation(name: String! @where(operator: "like")): [Location] @all`

Problem: This only gives me the result when the full `name` is matching. How can I do a wild card search as I did with the eloquent example?

**Comment by enzonotario** [comment]
I think that you you have to pass `%SEARCHTEXT%` as `name` arg. It will not do it for you. Otherwise, just use `@field` and do what you are used to do "before using lighthouse" (you can manipulate the query builder as you want)...

**Comment by a-ssassi-n** [comment]
Passing `%SEARCHTEXT%` as name arg solved my issue. Thanks.

**Comment by Arfat-Mughal** [comment]
%SEARCHTEXT% it is working Thanks,

**Comment by cbloss** [comment]
Worked for me! Thanks for asking!
