### ISSUE TITLE
How to get the current query as array/AST

### ISSUE THREAD

**Issue by abhimanyu003** [nuwave/lighthouse#602]
It will be really great if we can get query as an array in resolve or custom methods we are using.

```php
    public static function resolve($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
       dd($context->getQueryToArray()); // Something like this ( Just example )
    }
```

Query used in the playground to get the data

![image](https://user-images.githubusercontent.com/265913/52526165-bf91b200-2cda-11e9-96d2-e55b138d9934.png)

```
{
  posts {
    id
    user {
      id
    }
  }
}
```

Get query as an array in custom resolve method using.

```
[
	'posts' => [
		'id'
		'user' => [
			'id'
		]
	]
]
```

**Comment by ElForastero** [comment]
I guess you want to get the fields to avoid querying everything (`*`)?

The `$resolveInfo->getFieldSelection(1) // the number is the depth` method can help you, but only for basic cases, as described in its doc block.

**Comment by spawnia** [comment]
@ElForastero gave a pretty good answer. You can just add a utility function to get the information in a shape that is more convenient for you.

In principle, the `ResolveInfo` object holds all the information you need.
