### ISSUE TITLE
Filter by Related Model

### ISSUE THREAD

**Issue by javif89** [nuwave/lighthouse#603]
## Use Case

I have a list of users with addresses. The addresses are their own model and are related to the user.

How can I get all the users in a certain zip code?

**Relevant Schema**

```graphql
type User {
    id: ID!
    name: String!
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
    addresses: [Address] @hasMany
}

type Address {
    street1: String!
    street2: String
    city: String!
    state: String!
    zip: Int!
    type: String!
}
```

### Example of what I would like to achieve

```graphql
{
  users(address.zip: 46282) {
    name
    email
  }
}
```

**Comment by spawnia** [comment]
You can do anything you want within a [custom resolver](https://lighthouse-php.com/master/the-basics/fields.html#custom-resolvers)
