### ISSUE TITLE
Filter on many to many relationship with pagination

### ISSUE THREAD

**Issue by albatarnik** [nuwave/lighthouse#604]
I have many to many relationship between products and options, so I have three tables,
products, options, product_option

I would like to filter by `option` and paginate, I have other filters on product table that are working, but isn't working for the many to many relationship. 

Schema:

```
type query{
    Inventory(filter: InventorySearchFilter): [Product!]! @paginate(scopes: ["filterAndOrder"])
}
type Product {
    id : ID!
    title: String!
    options: [Option!] @belongsToMany
}

type Option {
    slug: String!
    products: [Product] @belongsToMany
}

input InventorySearchFilter {
    option_slug: String
     price_field_gte : Float
     price_field_lte: Float
     etc...
}

```
In Product.php:

```
 public function scopeFilterAndOrder($query, $args)
    {
        foreach ($args['filter'] as $key => $value)
        {
            $parsed = $this->getOperatorAndKey($key);
              //example of parsed key and operator
             // $parsed['key']: 'price_field', $parsed['operator'] :  ">="

            $query->where($parsed['key'], $parsed['operator'] , $value);
        }
    }
```
So the scope above works for product table arguments, but it doesn't filter on the pivot table product_option, so I tried to add the join in the scope, but things started to break down, mainly the data options returns empty array.
```
$query->join('product_option', 'products.id','=' ,'product_option.rv_id');
```

Query example
```
query {
  Inventory(
    filter: {
      is_sold: false
      condition: false
      option_slug: "Bath_Half"
    }
   
    count: 10
  ) {
    data {
      title
      condition
      price_field
      year
       //// this returns empty array when I add the join inside the scope query, and returns the options when I remove the join but the filter won't work.
      options{ 
        slug
      }
    }
    paginatorInfo {
      total
    }
  }
}
```
The filter works, but when I query options within the product data, I get empty array. Is there a better approach to filter on the pivot table? if not what should I do to fix it ?

**Comment by spawnia** [comment]
You can check out https://github.com/nuwave/lighthouse/pull/680, it greatly enhances the capability for client-side query constraints.

The specific problem you are having looks like it might stem from the way you are using a Join to query. I think you can do the constraint you want through the relationship method, which would be more clean anyways. Actual, manual joins are usually a sign you are not using Eloquent to its full potential.

https://laravel.com/docs/5.8/eloquent-relationships#querying-relations
