### ISSUE TITLE
Documentation is missing important info in the walkthrough section

### ISSUE THREAD

**Issue by sasokovacic** [nuwave/lighthouse#61]
Hi, 

I went over Walkthrough section in the documentation and couldn't continue after the subsection 6.3.5 (Connections) because critical information is missing about adding jobs field to the UserType... I found out about this after watching youtube tutorial....

https://chrissm79.gitbooks.io/lighthouse/content/635-adding-a-connection.html

**Comment by chrissm79** [comment]
Documentation has been moved for v2.0. It's still not complete but the `hasMany` or `paginate` directive resolves this issue. A video walkthrough link has also been added to the walkthrough section. Please let me know if you still have issues.
