### ISSUE TITLE
whereLike Directive

### ISSUE THREAD

**Issue by OzanKurt** [nuwave/lighthouse#610]
I often use simple WHERE LIKE clause on my API.

By simply adding a wildcard argument to the WhereFilterDirective, it is suddenly much more useful.

```php
$this->injectFilter(
    $argument,
    function ($query, string $columnName, $value) use ($operator, $clause) {
        $value = $this->wildcardValue($value);

        return $clause
            ? call_user_func_array([$query, $clause], [$columnName, $operator, $value])
            : $query->where($columnName, $operator, $value);
    }
);
```

```php
private function wildcardValue($value)
{
    $wildcard = $this->directiveArgValue('wildcard', 'both');

    $possibleWildcards = [
        'left' => "%{$value}",
        'right' => "{$value}%",
        'both' => "%{$value}%",
    ];

    if (!array_key_exists($wildcard, $possibleWildcards)) {
        throw new \Exception("Directive argument [wildcard] isn't valid. Available options: left, right, both");
    }

    return $possibleWildcards[$wildcard];
}
```

**Comment by spawnia** [comment]
I can not quite follow the example, how would that look like in schema definition and how would you use it?

**Comment by OzanKurt** [comment]
In my case, I am simply listing a bunch of users to an another for them to add each other as friends/contact. 

So they should be able to filter the users by their username.

The `@whereLike` there simply lets me query the DB as "%username%".

```graphql
type Query {
    ...
    users(username: String @whereLike): [User!]! @paginate(type: "paginator")
    ...
}
```

**Comment by e200** [comment]
@OzanKurt, but the where can be either `%string`, `string%` or `%string%`.

I recommend you to implement your own directive since this is a very specific case for you.

**Comment by OzanKurt** [comment]
I mean I already created my own directive and submitted here so that maybe others can use.

But, if you think that using `whereLike` in an API is uncommon. Sure.

**Comment by e200** [comment]
What about create a package for it so people can install it if they need?

Then you can add it to the docs `resouce page` and send a pull. 🙂

**Comment by OzanKurt** [comment]
Didn't know that, will do. Thanks! 😄

**Comment by spawnia** [comment]
I guess there are two orthogonal approaches when it comes to designing the query capabilities of an endpoint.

One would be too try and offer the most flexible features that a database can offer. This has the downside of coupling the schema tightly to the database.

The other approach is too just add the options to the schema that are required by the use cases. May be a bit tedious, but can offer flexibility too change the implementation in the long run.

It depends on the use case, really. If there are many users, only offer options that are guaranteed to perform well. Try to keep the schema as small as possible.

**Comment by SirLamer** [comment]
@OzanKurt Just to add to this, I suggest you just programmatically include the wildcard character `%` in your search queries as sent to the API if you want to affect this. Pair it with `@where(operator: "like")`
