### ISSUE TITLE
How to create nested mutations

### ISSUE THREAD

**Issue by risestar0927** [nuwave/lighthouse#611]
Hi
I am going to make a nested graphql mutations.
type User{
  id: ID
  email: String
  posts: [Post]
}
type Post{
  id: ID
  Description: String
}
I am going to have made Mutation for User only for email and it works fine.
Does anyone know about how to create Post records in one request in lighthouse?
Many thanks.

**Comment by spawnia** [comment]
https://lighthouse-php.com/master/guides/relationships.html#mutating-relationships
