### ISSUE TITLE
Typecast value through schema definition

### ISSUE THREAD

**Issue by abhimanyu003** [nuwave/lighthouse#612]
Is it possible to typecast a value form `.graphql` file ?

In this example I have `"12"` stored as a string but I want to give output as `Int 12`

```
type Incident {
    parent: Int <--- actual type is String "12" typecast to Int
}
```

**Comment by enzonotario** [comment]
I don't think that it is possible. You will have to create your own directive or cast it from your eloquent model.

**Comment by spawnia** [comment]
@enzonotario is right, i suggest adding https://laravel.com/docs/eloquent-mutators

**Comment by abhimanyu003** [comment]
@spawnia Yes that is one option but i'm not using Eloquent but wrapping the up custom JSON to graphQL

**Comment by spawnia** [comment]
You could go with a custom directive that adds a resolver to do such conversions.
