### ISSUE TITLE
Add documentation about Node and Field custom directives

### ISSUE THREAD

**Issue by e200** [nuwave/lighthouse#622]
I'm trying to create a directive that converts all type fields from `camelCase` to `snack_case` but I have no idea of how to run through the type fields and make changes on them because I can't understand how `node directives` works.

Any help documenting this?

**Comment by spawnia** [comment]
Custom directives documentation has improved greatly as of late.

https://lighthouse-php.com/master/custom-directives/type-directives.html

https://lighthouse-php.com/master/custom-directives/field-directives.html
