### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by lucasmichot** [nuwave/lighthouse#623]
**Is your feature request related to a problem? Please describe.**

We want lighthouse to support Laravel 5.8

----

**Describe the solution you'd like**

Suport Laravel 5.8

---

**Describe alternatives you've considered**

We need to find an alternative to `orchestra/testbench:3.8` which requires `laravel/contract:5.8.*`.
`orchestra/testbench:3.8.*` enforces `void` typehint on `setUp` and `tearDown` method (so it also complies to `phpunit/phpunit:^8.0`

---

**Additional context**

See https://github.com/nuwave/lighthouse/pull/621
What do you think @chrissm79 @spawnia ?

**Comment by spawnia** [comment]
Actually, it looks like testbench `3.8` does still support PHPUnit `7.x`.

Let's switch to PHPUnit 8 when Laravel does and make a hard cut then.

**Comment by lucasmichot** [comment]
`orchestra/testbench:3.8` comes with type-pinted`setUp` and `tearDown`.
So within your tests, you have to comply with this signature.

`orchestra/testbench:3.7` does not enforce type-hint, so your tests will be in error with these type-hints

**Comment by spawnia** [comment]
We can add the type hints and things should still work with the older versions.

**Comment by lucasmichot** [comment]
I see my mistake. #621 was worked on before #615 was merged

See https://github.com/nuwave/lighthouse/pull/626

**Comment by spawnia** [comment]
Closed by #626
