### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by SUPERUSER41** [nuwave/lighthouse#63]
whenever i open the graphiql client and pass in the route im getting a 500 internal server error 
![image](https://user-images.githubusercontent.com/27390890/29244300-64656476-7f7a-11e7-825f-82a8fa0217d5.png)

**Comment by hailwood** [comment]
@SUPERUSER41 as shown your graphql endpoint is returning a 500 error.
That error would be HTML formatted whilst graphiql expects json and of course the first part of an html response is `<html>` so you're receiving the error as shown above.

Check your error logs for the actual error.

**Comment by chrissm79** [comment]
Closing as v2.0 should resolve any schema issues but if you are still get a 500 let me know.
