### ISSUE TITLE
[question] How to use custom relation

### ISSUE THREAD

**Issue by academici** [nuwave/lighthouse#638]
I use laravel medialibrary. In my model, i create method, which return Colleaction
```php
public function colors()
{
        return $this->getMedia('colors');
}
```
in my scheme i add 
colors: [Media] @hasMany(relation: "colors")

sample query
```js
query {
  item {
    name
    colors {
      id
    }
  }
}
```
getting an error: Method Illuminate\\Support\\Collection::addEagerConstraints does not exist.

How best to implement custom relation?

**Comment by enzonotario** [comment]
Your `colors` function doesn't return a relationship, but just a collection. So, your schema should be:
```
...
colors: [Media!] @method(name: "colors")
...
```

**Comment by academici** [comment]
@enzonotario, thanks!
