### ISSUE TITLE
How would I append an error to the error list using a custom directive?

### ISSUE THREAD

**Issue by e200** [nuwave/lighthouse#642]
I'm trying to create a custom directive where I want to send a GraphQL friendly error (not manually handled by me).

Is there any method we should call to append errors to the error response list?

**Comment by spawnia** [comment]
I compiled some useful info about error handling into https://github.com/nuwave/lighthouse/pull/644

Please review the changes if there is anything missing, i can add more info if you have questions.

**Comment by EdwardNelson** [comment]
@spawnia In terms of addition to the error handling docs, I think some information regarding how to handle Laravel thrown exceptions and make them more user friendly would be a great addition. For example, ```\Illuminate\Auth\AuthenticationException```.
