### ISSUE TITLE
Usage of strtolower/strtoupper

### ISSUE THREAD

**Issue by olivernybroe** [nuwave/lighthouse#653]
Should we replace `strtolower` with `Str::lower`?.

The reason for this would be for consistency with using the `Str` class, however it adds a little overhead as `Str::lower` has to call the `mb_strtolower` under the head.

**Comment by spawnia** [comment]
I think it is not really necessary for the use cases we have. Only names from the schema file are lowercased/uppercased at the moment, those are limited to a pretty small subset of ASCII: https://facebook.github.io/graphql/June2018/#sec-Names

**Comment by mfn** [comment]
I'm with @spawnia on this.

If we know it's not related to unicode stuff, it's fine and legit to use good 'ol `strto*` functions IMHO

**Comment by olivernybroe** [comment]
Yes, the reason for this was not for using `mb`, the reason was for using `Str` for consistency.
I only mentioned that it used `mb` as a disadvantage to not do it.

**Comment by spawnia** [comment]
mb is functionally different. For cases where we can guarantee we only have ASCII, the non-mb functions are faster, so let's keep them there.

When we do require case transformations on UTF-8 strings, the `Str` functions are the way to go.
