### ISSUE TITLE
Usage of the app helper

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#654]
Let's replace it with constructor injection where possible.

In some places, i think it is necessary for us to lazily resolve from the container directly, should we use `Container::getInstance()->make()` instead?

**Comment by olivernybroe** [comment]
If we have control over when these classes are being created, which might have dependencies, then can't we just wrap them in `app->make`?

This would of course require that in all cases where we instantiate something we have to use `app->make` instead.
