### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#656]
I had a great experience with static analysis tools such as https://github.com/phpstan/phpstan

Do you think we should use it for Lighthouse too? Are there other tools that work better?

**Comment by mfn** [comment]
> Are there other tools that work better?

I only use phpstsan but on top of my head there are:
- https://github.com/vimeo/psalm
- https://github.com/phan/phan

Then there's the issue with Laravel integration: I know that recently work has been done in lighthouse to reduce use of magic stuff, so the less, the easier for the analysers.

There is:
- https://github.com/nunomaduro/larastan for phpstan
- https://medium.com/@muglug/announcing-psalm-support-for-laravel-8a0fc507e220 (very recent) by re-suing https://github.com/barryvdh/laravel-ide-helper (which I actually mentioned a few days ago in a PR)
