### ISSUE TITLE
Custom validator with @validate and @create directive - validation ignored

### ISSUE THREAD

**Issue by aso824** [nuwave/lighthouse#658]
Tried to create schema like this:

        createPerson(
            name: String!
            surname: String!
        ): Person! @validate(
            validator: "App\\Http\\GraphQL\\Validators\\Person\\CreatePersonValidator"
        ) @create

In this example I need to use custom validator because unique rule on multiple columns is currently impossible to create in Lighthouse.

In above case, model will be created without calling validator. If `@create` (or `@update`) is not used, default mutation class (`App\Http\GraphQL\Mutations\CreatePerson`) will be called after validation.

**EDIT:** checked again and validator is not called, or I'm extending wrong method

The problem is - I don't need to implement mutation where this is generic and built-in (like creating and updating models), but sometimes custom validation logic is required.

Also, `@validate` directive is not covered in documentation, but maybe I'll send PR after figuring out how solve problem from this issue.

By the way, how can I define which custom mutation class will be used? In queries, Lighthouse seems to be able to find class whenever it is, but currently my mutations is stored in one namespace (directory) - little messy.

**Comment by spawnia** [comment]
`@validate` is no longer supported in `dev-master`. You can just implement your own validation directive as a `FieldMiddleware`.

**Comment by nachofassini** [comment]
Hi @spawnia, is there any example of how to use FieldMiddleware for unique validators?

For example, if i need to pass the id of the user or any other request parameter for the unique validator.

Thanks, in advance

**Comment by spawnia** [comment]
@nachofassini you can easily get the user ID from the `GraphQLContext`, the third resolver argument.

Closing this issue, as i said `@validate` is no longer a part of Lighthouse.
