### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by olivernybroe** [nuwave/lighthouse#667]
Let's add a changelog.
So whenever a user changes or creates something new they need to add it in the changelog.
This should be part of our `contributing.md` file, so we all know that this is a required step if you want to contribute to Lighthouse.

**Comment by spawnia** [comment]
It should be included in the PR template as well.

**Comment by chrissm79** [comment]
This is a fantastic idea 👍

**Comment by spawnia** [comment]
How do you like https://keepachangelog.com/en/1.0.0/ as a template?

**Comment by olivernybroe** [comment]
Hmm I like that template. Seems pretty clean and easy to follow

**Comment by spawnia** [comment]
Resolved by #705
