### ISSUE TITLE
[3.0] Tracing does not follow the spec correctly

### ISSUE THREAD

**Issue by stayallive** [nuwave/lighthouse#672]
Quoting: https://github.com/apollographql/apollo-tracing#response-format

- The duration of a request is in nanoseconds, relative to the request start, as an integer.
- The startOffset of parsing, validation, or a resolver call is in nanoseconds, relative to the request start, as an integer.
- The duration of parsing, validation, or a resolver call is in nanoseconds, relative to the resolver call start, as an integer.

The spec states durations and offsets are in **nanoseconds**. Now I know nanoseconds are not supported by PHP, so this might be a little tricky. But microseconds are supported fine and happen to be a 1000 smaller than a nanosecond (yay maths ;)).

So something like this should solve it (with the greatest precision we can achieve in PHP):

```php
    public function record(ResolveInfo $resolveInfo, Carbon $start, Carbon $end): void
    {
        $this->resolverTraces [] = [
            // ...
            'startOffset' => $start->diffInMicroseconds($this->requestStart) * 1000,
            'duration' => $start->diffInMicroseconds($end) * 1000,
        ];
    }
```

However... Carbon only supports the microsecond helpers since 2.6 and Laravel can use Carbon `^1.26.3 || ^2.0` so I think there are 2 ways forward.

- Implement our own `diffInMicroseconds` calls so we don't depend on Carbon
- Require Carbon `^2.6`

WDYT?

---

I should mention what is wrong with doing it in seconds I suppose:

<details>
<summary>Example trace</summary>

```json
{
  "data": {
    "viewer": {
      "name": "Alex Bouma",
      "portfolio": {
        "username": "alex"
      }
    }
  },
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2019-03-16T16:27:03.598Z",
      "endTime": "2019-03-16T16:27:03.660Z",
      "duration": 0,
      "execution": {
        "resolvers": [
          {
            "path": [
              "viewer"
            ],
            "parentType": "Query",
            "returnType": "User",
            "fieldName": "viewer",
            "startOffset": 0,
            "duration": 0
          },
          {
            "path": [
              "viewer",
              "name"
            ],
            "parentType": "User",
            "returnType": "String!",
            "fieldName": "name",
            "startOffset": 0,
            "duration": 0
          },
          {
            "path": [
              "viewer",
              "portfolio"
            ],
            "parentType": "User",
            "returnType": "Portfolio!",
            "fieldName": "portfolio",
            "startOffset": 0,
            "duration": 0
          },
          {
            "path": [
              "viewer",
              "portfolio",
              "username"
            ],
            "parentType": "Portfolio",
            "returnType": "String!",
            "fieldName": "username",
            "startOffset": 0,
            "duration": 0
          }
        ]
      }
    }
  }
}
```

</details>

All durations and offsets are 0, instant API! Which is bad for metrics (although good for management).

**Comment by spawnia** [comment]
Good finding, gladly taking a PR for that.

**Comment by stayallive** [comment]
So should I do the PR with custom microseconds or require ^2.6 of Carbon?

**Comment by spawnia** [comment]
Since the fix is pretty simple, i think we can live without changing the dependency.
Maybe you can add it in a single place and link to https://github.com/laravel/framework/blob/master/composer.json with a hint to remove it once Laravel changes it's dependency.
