### ISSUE TITLE
Change relationship mutations 'connect' and 'disconnect' to 'attach' and 'detach'

### ISSUE THREAD

**Issue by SirLamer** [nuwave/lighthouse#682]
The new (as of beta 3) relationship binding/mutation uses the keywords 'connect' and 'disconnect' throughout. I suggest the terms 'attach' and 'detach' be used instead. These terms are more commonly used in other platform including within Laravel itself, where the Eloquent commands "attach(...)" and "detach(...)" do the same thing. Consistency is good.

**Comment by spawnia** [comment]
> Consistency is good.

Agreed. That is exactly why the current convention was chosen.

While Laravel does call those methods `attach`/`detach` for some relationship types, the equivalent within `BelongsTo` is called `associate`/`disassociate`. That is why we chose a general term that fits both.

**Comment by SirLamer** [comment]
Well alright then! :)
