### ISSUE TITLE
@rules requires explicit column keys when using "unique" validation

### ISSUE THREAD

**Issue by SirLamer** [nuwave/lighthouse#683]
When `flatten` is used on the `@update` or `@create` directive, the Laravel validator is fed the wrong parameter name such that validation will fail.

In example, validators will try to act on an attribute "data.make" and "data.model", and it will try to query the database for these columns which won't exist. Validation always fails.

**Expected behavior**

Validation works

**Schema**

```graphql
type Car {
  make: String!
  model: String!
}

mutation {
  createCar(data: CarCreateInput!) @create(flatten: true)
}

input CarCreateInput {
  make: String! @rules(apply: ["min:3"])
  model: String! @rules(apply: ["min:3", "unique:cars"])
}
```

**Output/Logs**

N/A (validation fails)

**Environment**

Lighthouse Version: beta.3
Laravel Version: 5.7.x
PHP Version: 7.2

**Comment by spawnia** [comment]
Seems like we should do something about how `@flatten` is handled generally.

Lots of issues with the current solution:
- https://github.com/nuwave/lighthouse/issues/249
- https://github.com/nuwave/lighthouse/issues/596

**Comment by SirLamer** [comment]
I'm inclined to agree, fro instance on an update mutation I'd prefer for the ID field to be separate but that doesn't work with the current flatten implementation. You might instead just allow for an Input property to be identified as the attribute population data which allows for other properties to be used for other purposes in the future without breaking functionality of "v1" API implementations.

```graphql
extend type mutation {
  updateCar(id: ID!, input: CarUpdateInput!) @update(attributes: "input")

  input CarUpdateInput {
    make: CarMakeRelationUpdate
    model: String
  }
}
```

**Comment by spawnia** [comment]
@SirLamer while i did make an update to how flattening can work, i re-read your issue.
Flattening does not actually occurr before validation, so it has nothing to do with it.

I think you just need to specify the column that Laravel should use: https://laravel.com/docs/5.8/validation#rule-unique
