### ISSUE TITLE
Facade is used with type `File` in resolving paginator type

### ISSUE THREAD

**Issue by megawubs** [nuwave/lighthouse#685]
**Describe the bug**
I get an error when executing the following query:

```graphql
{
  files(count: 10, page: 1) {
    data {
      id
      file_name
      url
    }
  }
}
```

error:

`"Method Illuminate\\Filesystem\\Filesystem::query does not exist.",`

After som investigation of my own, it turns out that inside the `PaginateDirective` the `getpaginatedResults` method tries to get the paginator model, but somehow this returns just `File`, what in turn is an facade for `lluminate\\Filesystem\\Filesystem`. 

**Expected behavior**

Get a paginated list of `File` types. Or in other words, let `getPaginatorModel` return the correct model, even if it is a global facade.

**Schema**
```grapqhl
type File {
    id: Int!
    file_name: String
    url: String
    size: Int
    mime_type: String
    last_modified: DateTime
    created_at: DateTime!
    updated_at: DateTime!
}

extend type Query @middleware(checks: "auth:api"){
    files: [File!]! @paginate
    file(id: Int @eq): File @find(model: "App\\Entities\\Files\\File")
}
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
{
  "errors": [
    {
      "debugMessage": "Method Illuminate\\Filesystem\\Filesystem::query does not exist.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "files"
      ],
      "trace": [
        {
          "file": "/path/to/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
          "line": 237,
          "call": "Illuminate\\Filesystem\\Filesystem::__call('query', array(0))"
        },
        {
          "file": "path/to/project/vendor/nuwave/lighthouse/src/Schema/Directives/Fields/PaginateDirective.php",
          "line": 154,
          "call": "Illuminate\\Support\\Facades\\Facade::__callStatic('query', array(0))"
        },
..
```

</details></br>

**Environment**

Lighthouse Version: `dev-master`
Laravel Version: 5.8
PHP Version: 7.2

**Additional context**

**Comment by spawnia** [comment]
Happens because the class `File` actually exists, without any prior namespace.

We have a method for limiting the tried namespaces to instances of actual models, it just was not used in this instance. Fixed in #686
