### ISSUE TITLE
Relationship mutation does not throw exception when relationship return type is not declared in Laravel

### ISSUE THREAD

**Issue by SirLamer** [nuwave/lighthouse#687]
**Describe the bug**

If the relationship mutation feature introduced in lighthouse beta.3 is used, it is a documented requirement that the return type be declared on the function definition using PHP 7.0+ syntax. The reality is that many Laravel projects were started prior to PHP 7.0 release and thus have not implemented return type declarations as a coding practice on their projects.

As of beta.3, if a relationship mutation is attempted on a relationship without the return type defined, Lighthouse will basically skip the action on the relationship and attempt to proceed otherwise. This carries various risks - on a well-designed data model, this should hopefully throw an internal error, but in some cases it may go undetected and commit the other changes and attempt to the return the response to the API without reporting the issue.

**Expected behavior**

An exception should be thrown when a relationship mutation cannot be performed since the return type is not defined on the relationship definition in Laravel.

**Environment**

Lighthouse Version: beta.3
Laravel Version: 5.7.x
PHP Version: 7.3

**Additional context**

Like an idiot I spent a long time troubleshooting why relationship mutations were not working until I remembered the note in documentation that return types must be defined.

**Comment by spawnia** [comment]
A solution was tried in https://github.com/nuwave/lighthouse/pull/688

I can not come up with a more practical solution, but i also do not really see how this might be a security issue?

When doing things as described in the docs, it works fine, so i am closing this for now.
