### ISSUE TITLE
v2-Beta test progress

### ISSUE THREAD

**Issue by kikoseijo** [nuwave/lighthouse#69]
Love it!, so simple!

Got to the point where I'm getting the schema generated into a React-Native project using Relay Modern, retrieving the schema form the server with the `graphql get-schema -I` introspection method, hardest part was figure out the mutation. (*working example bellow*)

Need a bit of advise how you handle or its up to us the auth, resolve, middleware, thing. Like for example: `@inject(context: "auth.id"))` 
Add the route point to the crsss thing exclude? I mean, to resolve the context, maybe using passport, if you can share your approach I'm sure it will be very inspirational.  🤔 [@]middleware() directive probably?

For a custom Directive, like example bellow, Is it class name or the name attributed whats important?

```php
<?php

namespace App\GraphQL\Directives;

use GraphQL\Type\Definition\ResolveInfo;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Traits\HandlesDirectives;

class Context implements FieldResolver
{
    use HandlesDirectives;

    /**
     * Name of the directive.
     *
     * @return string
     */
    public function name()
    {
        return 'context';
    }

    /**
     * Resolve the field directive.
     *
     * @param FieldValue $value
     *
     * @return FieldValue
     */
    public function handle(FieldValue $value)
    {
        return auth()->id();
    }
}
```

#### routes/schema.graphql

```graphql
type User @model {
  id: ID
  name: String!
  email: String!
  created_at: String!
  updated_at: String!

  avisos: [Aviso!]! @hasMany
}

type Aviso @model {
  id: ID
  uuid: String!
  name: String!
  user: User!
}

type Query {
  viewer: User @auth
}

type Mutation {
  createUser(
    name: String!
    email: String! @validate(rules: ["email", "unique:users,email"])
  ): User @create(model: "App\\Models\\User")

  createAviso(name: String, user_id: Int @inject(context: "auth.id")): Aviso
    @create(model: "App\\Models\\Aviso")
}
```

This is how I'm doing the middleware, 

```php
    'directives' => [__DIR__.'/../app/GraphQL/Directives'],

    'route' => [
        'prefix' => 'kapi',
        // 'middleware' => ['loghttp']
    ],
    /*
    |--------------------------------------------------------------------------
    | Namespace registry
    |--------------------------------------------------------------------------
    |
    | This package provides a set of commands to make it easy for you to
    | create new parts in your GraphQL schema. Change these values to
    | match the namespaces you'd like each piece to be created in.
    |
    */
    'namespaces' => [
        'models' => 'App\Models',
        'mutations' => 'App\GraphQL\Mutations',
        'queries' => 'App\GraphQL\Queries',
        'types' => 'App\GraphQL\Types',
        'fields' => 'App\GraphQL\Fields',
        'scalars' => 'App\GraphQL\Scalars',
        'connections' => 'App\GraphQL\Connections',
        'dataloaders' => 'App\\GraphQL\\DataLoaders',
    ],
```

> best solution so far for Laravel from a personal perspective.

Happy coding!

**Comment by kikoseijo** [comment]
@chrissm79, 

Thanks for the example project, will help out people figure out faster how to structure the project.

As for what I have discovered my side,  the AutoLogin Middleware its not a good idea to test things, will always to be present no matter what middleware you use, and with 'web' middleware a real @auth does not work. 

I'm working on a poject, its a website with an app, (Using this package for feeding the app) the website uses the normal routes and has no graphQL, the app without restriction and passport for authentication trough the mobile app- 

I end up doing a second route, something like this:

```php
$controller = config('lighthouse.controller');

Route::group(['middleware' => ['auth:api']], function () use ($controller) {
    Route::post('graphql', ['as' => 'graphql.secured', 'uses' => '\\'.$controller]);
});
```

This is how it look like:

![screen shot 2018-03-23 at 09 08 42](https://user-images.githubusercontent.com/1528668/37818264-dbe4d398-2e79-11e8-9e6e-b783b7f3cf9e.png)


Hardest part was paginate the results with no *connection* and the *belongsToMany relationship*, you will laugh at me when I tell you that took me, like 4h, to figure out how to do the belongsToMany, was trying to use the @hasMany directive because the collection results looks the same, but could not work it out, till I removed the @hasMany directive and it just went and worked.

My conclusions: *This is best Laravel + webonyx/graphql-php Wrapper on the Net*.

With the example project, things should be faster, but I recommend to have this 2 common issues that people always need. Pagination without relationships, Belongs to many example. (More documentation, less hassle from new users)

The middlewares are always also confusing, and could be a plus to have something regarding this auth, middleware thing.

this is what I end up having, built, Its a Card Dealer solution, things are related to vehicles.

```graphql
// type Car @model 
  media: [Media] @hasMany # this is a morphMany relationship.
  extras: [CarOption!]! # this is a belongsToMany
  make: CarMake @belongsTo
  model: CarModel @belongsTo
  body: CarBody @belongsTo
```

Paginated results without connection:

```graphql
type CarConnection {
  edges: [CarEdge]
  pageInfo: PaginatorInfo
}

type CarEdge {
  cursor: ID!
  node: Car
}

type Query {
  cars(
    filter: String
    after: ID
    first: Int
    count: Int
    take: Int
    limit: Int
    page: Int
    before: String
    last: Int
  ): CarConnection!
}
```

> above are toooo many fields, was testing things out.....

and the resolver for the query,

```
<?php

namespace App\GraphQL\Queries;

use App\Models\Car;
use App\ResolverLogTrait;
use Nuwave\Lighthouse\Support\Schema\GraphQLQuery;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Nuwave\Lighthouse\Schema\Types\PaginatorField;
use Nuwave\Lighthouse\Support\Traits\HandlesGlobalId;

class Cars extends GraphQLQuery
{
    use HandlesGlobalId, ResolverLogTrait;

    public function resolve()
    {
        $data = Car::orderBy('id', 'DESC')
                    ->active('published')
                    ->notActive('sold')
                    ->with(['model', 'extras', 'make', 'media'])
                    ->paginatorConnection($this->args);

        $pageInfo = (new PaginatorField)->paginatorInfoResolver($data,$this->args,$this->context,$this->info);
        $page = $data->currentPage();
        $edges = $data->values()->map(function ($item, $x) use ($page) {
            $cursor = ($x + 1) * $page;
            $encodedCursor = $this->encodeGlobalId('Car', $cursor);
            return ['cursor' => $encodedCursor, 'node' => $item];
        });

        return [
            'pageInfo' => $pageInfo,
            'edges' =>  $edges,
        ];
    }
}
```

**Comment by kikoseijo** [comment]
Just remember something else, I think its important as was rare, 

```graphql
scalar DateTime @scalar(class: "DateTime")
```

Had to extend yours because its looking for them in my configured folder, solution was:

```php
namespace App\GraphQL\Scalars;


use Nuwave\Lighthouse\Schema\Types\Scalars\DateTime as LightDateTime;


class DateTime extends LightDateTime
{

}
```

This was a bit rare, in the sense of not being able to call directly yours from the [@]scalar directive as was allays starting inside my folder.

just a punctuation....



BTW: I'm done with the issue, close if you want...or leave open for others to provide feedback...

**Comment by kikoseijo** [comment]
-well, I clicked close!

**Comment by chrissm79** [comment]
@kikoseijo Hey, I was able to get the `belongsToMany` relationship to work for me using the `@hasMany` directive. Here's an example project and you can use this query (once it's migrated and seeded):

```graphql
{
  cars {
    make
    year
    extras(first: 5) {
      pageInfo {
        hasNextPage
      }
      edges {
        cursor
        node {
          name
          cost
        }
      }
    }
  }
}
```

I don't currently have a way to create a `connection` or `paginator` instance from the root query... didn't really think about that but it makes sense. I'll see if that's a directive I can create.

Going back to the `belongsToMany` relationship, here is my schema:

```graphql
type Car {
  make: String!
  year: Int!
  # Set type pagination type to `cursor` and since the field doesn't match the name of the
  # relationship, you can customize it with the `relation` argument
  extras: [CarOption!]! @hasMany(type: "relay" relation: "options")
}

type CarOption {
  name: String!
  cost: Float!
}

type Query {
  cars: [Car!]! @field(class: "App\\Http\\GraphQL\\Queries\\CarQuery" method: "resolve")
}
```
