### ISSUE TITLE
Dealing with attributes on the pivot table of a BelongsToMany relation

### ISSUE THREAD

**Issue by JoeSchr** [nuwave/lighthouse#691]
**Situation**

I'm trying to implement @update on a belongsToMany relationship. The pivot table also has columns I want to update, like this:

```php
class Patient extends Model
{
    // many to many RELATIONSHIPS
    public function medications(): BelongsToMany
    {
        return $this->belongsToMany(Medication::class, 'patients__medications', 'patient_id', 'medication_id')->withPivot('dose_mg', 'is_rescue_medication'); //->as("details");
    }
}
```

my example schema: 

```graphql
#schema.graphql excerpts
# Mutations {}
updateMedication(input: MedicationInput): Medication! @update(flatten: true)

# Types
# -- Medication
input MedicationInput {
    id: ID
    name: String
    pivot: MedicationDetailsInput
}

input MedicationDetailsInput {
    patient_id: ID
    medication_id: ID
    dose_mg: Float
    is_rescue_medication: Boolean
}
input MedicationRelation {
  update: [MedicationInput]
  connect: [MedicationDetailsInput]
  disconnect: [ID]
  create: [MedicationInput]
  delete: [MedicationInput]
  sync: [MedicationDetailsInput]
}
```

**Problem**

I get an SQL error that laravel can't find the columns (of course, they don't exist because they are on the pivot table) on the related table to update.

I debugged it down to the `executeUpdate` function in `MutationExecutor.php` , where the pivot property is still inside `$remaining` and gets treated as a normal property on the related Model instead of the special case of being pivot columns.

**Expected**

pivot columns should be updated,

**Workarounds**

there was a workaround suggested:

> You can treat your BelongsTo relation simply as two BelongsTo relationships to work around this.

by @spawnia in this issue thread #549

**Comment by spawnia** [comment]
For future-reference, here is an excerpt from the discussion of #692:

When you think about what the `BelongsToMany` relationship actually is, you will find that it is in fact comprised of a `HasMany` and a `BelongsTo` relationship.

In terms of your concrete example, you should be able to update a medication like this:

```graphql
mutation {
	updateMedication(input: {
		id: 1
		name: "Lysergicream"
		# That would be a HasMany relationship from Mediation to the pivot model
		medicationUser: {
			update: [{
				dose_mg: 11
				# This is a belongsTo relationship from your pivot model to User
				user: {
                    connect: 1
                }
           }]
        }
    }) {
        id
        name
        # Will return a list, as this is a HasMany relationship
        medicationUser {
            dose_mg
            # A single BelongsTo
            user {
                 id
                 name
            }
         }
    }
}
```

**Comment by spawnia** [comment]
@JoeSchr you can now use nested mutations to do this directly and in a convenient way: https://github.com/nuwave/lighthouse/pull/1110

**Comment by JoeSchr** [comment]
Thanks. Meanwhile I made my custom fork to work around this, but it seems it's finally time to update to this release!

**Comment by AbdElrahmaN31** [comment]
@spawnia 
How can I write a type that expresses this relationship?

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
