### ISSUE TITLE
Translated Schema Descriptions

### ISSUE THREAD

**Issue by plunkettscott** [nuwave/lighthouse#698]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to translate the schema comments for the different languages our applications provide translations for. This is currently not possible that I can see.

**Describe the solution you'd like**
I'd like to be able to register translation keys as comments or be able to prefix specific language keys with the comments so that when users download the schema it can be in their native language.

**Describe alternatives you've considered**
N/A, unsure what alternatives might be available

**Comment by spawnia** [comment]
Can you research if a standard for this exists anywhere? Do any other GraphQL servers implement this?

**Comment by spawnia** [comment]
Closing because there seems to be little interest. This might require work in the upstream library to work, see https://github.com/webonyx/graphql-php
