### ISSUE TITLE
Subscription auth endpoints not using middleware

### ISSUE THREAD

**Issue by chrisneal** [nuwave/lighthouse#701]
**Describe the bug**

Pusher subscription auth endpoints don't use the route middleware set in the lighthouse config.

**Expected behavior**

When accessing `/graphql/subscriptions/auth` the routes don't have any middleware associated.

**Environment**

Lighthouse Version: v3.0-beta.3

**Comment by spawnia** [comment]
@chrissm79 do you think it is a sane default to use the settings used for the `/graphql` route?

Or should we possibly add an extra route config?

**Comment by chrisneal** [comment]
@spawnia Personally, I think adding another extra config for those routes gives flexibility. If the user wants to use the same middleware on them, then they can do that easily from within the config.

**Comment by spawnia** [comment]
I figure it might be different as well, since the function of those endpoints is totally different, too.

**Comment by chrisneal** [comment]
@spawnia Are you happy for me to create a PR for this?

**Comment by spawnia** [comment]
Very :) Make sure to update the docs with the new config, if possible add a test :)

**Comment by spawnia** [comment]
A solution for this is described here: https://github.com/nuwave/lighthouse/pull/702#issuecomment-484138355
