### ISSUE TITLE
"Match ID or slug" argument directive

### ISSUE THREAD

**Issue by SirLamer** [nuwave/lighthouse#711]
**Is your feature request related to a problem? Please describe.**

Oftentimes a 'slug' is used on models to allow for human-readable URLs or other similar applications where a human readable unique ID is useful. Usually slug is generated from another field (like "name") and also the model has ID numbers which are more efficient in programmatic applications. It would be useful for a model lookup query to accept ID or slug in the same field and it sorts it out server-side.

**Describe the solution you'd like**

This.

```php
<?php

// Take care to fix namespace if adopted in project
namespace app\GraphQL\Directives;

use Nuwave\Lighthouse\Support\Contracts\ArgFilterDirective;

class SlugOrIDDirective implements ArgFilterDirective
{

    /**
     * Name of the directive.
     *
     * @return string
     */
    public function name(): string
    {
        return 'slugOrID';
    }

    /**
     * @param  \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder  $builder
     * @param  string  $columnName
     * @param  mixed  $value
     *
     * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
     */
    public function applyFilter($builder, string $columnName, $value)
    {
        return $builder->where($columnName, $value)->orWhere('slug', $value);
    }

    /**
     * Does this filter combine the values of multiple input arguments into one query?
     *
     * This is true for filter directives such as "whereBetween" that expects two
     * different input values, given as separate arguments.
     *
     * @return bool
     */
    public function combinesMultipleArguments(): bool
    {
        return false;
    }
}
```

**Describe alternatives you've considered**

Two separate arguments, one for "id" and one for "slug" however then the "required" validation enforcement collapses because you cannot specify that a query requires either one of two fields. There is a query performance cost to this implementation compared to a more declarative implementation which is clearly seeking ID OR a slug and not checking both.

**Additional context**

If there is a slug which looks like an ID (usually numeric) then a query could match two results. This simple implementation expects that slugs are not allowed to match numeric IDs.

**Comment by spawnia** [comment]
I suggest you take a look at https://github.com/nuwave/lighthouse/pull/680 and how it can handle any kinds of arguments.

It allows you to use an input object with your arg builder, which you could use to control the exact shape of the input in a way that only ID or Slug can be choosen.

```
input Identifier {
    value: ID
    type: IdentifierEnum
}

enum Identifier {
    ID
    SLUG
}
```

**Comment by SirLamer** [comment]
I considered this however my goal was to set up a query pattern which would
work for all models with and without slugs. Changing the field query only
would mean id numbers always work. If you prefer I can stick to your
method, though.

**Comment by spawnia** [comment]
I guess you have to decide between a more verbose but performant, explicit definition and a rather magic one.

Anyways, i think that Lighthouse provides sufficient primitives for you to implement this feature with a custom directive. It seems to specialized to be included as a core feature, as that would add bloat, complexity and maintenance effort to this library.

Thanks for the contribution!
