### ISSUE TITLE
Pagination directive + order results

### ISSUE THREAD

**Issue by kikoseijo** [nuwave/lighthouse#72]
Helo @chrissm79,

Im wondering how can I filter/order results on a pagination directive.
Like filter results with a query or exclude items by a field.

right now if I try to mix a pagination with a field gives me following waring:

```
Fields can only have 1 assigned resolver directive. cars has 2 resolver directives [paginate, field]
```

Am I missing something?

**Comment by chrissm79** [comment]
I'll add this to the docs, but you can only have 1 `resolver` directive on a field (there are `resolver` directives that "resolve" a field and `middleware` directives that "manipulate" a field). 

As for filtering/ordering, you can add `scopes` to the `hasMany` and `pagination` directives like so:

```graphql
type User {
    posts(status: PostStatus): [Posts!]! @hasMany(scopes: ["myStatusScope"])
}

type Query {
    posts(order: PostOrder): [Post!]! @pagination(scopes: ["myModelScope"]
}
```

*Note: You'll get passed the `args` array to your scope*

**Comment by kikoseijo** [comment]
Excellent, was missing the scope.

```graphql
extend type Query {
  posts: [Post!]! @paginate(type: "connection", model: "Post", scopes: ["filterAndOrder"])
}
```

Thanks again!

**Comment by 4levels** [comment]
@kikoseijo can you explain a little more how you managed to get sorting with scopes working?

I've been fruitless in trying to allow sorting to be passed as an argument by graphql.
I added the orderBy argument and scope option to the paginator directive, like so
```graphql
images(orderBy: String): [Image!]! @paginate(type: "relay", model: "Image", scopes: ["orderBy"])
```

However, as soon as I try adding an orderBy clause to the query (see code below) it doesn't return any results anymore (which seem logical from the [Laravel scopes ](https://laravel.com/docs/5.6/eloquent#query-scopes) intention to filter results, not to sort)

in `app/Models/Image.php`
```php
    /**
     * @param $query \Illuminate\Database\Eloquent\Builder
     * @param $args
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOrderBy($query, $args) {
        $orderBy = $args['orderBy'] ?: 'createdAt_DESC';
        @list ($orderField, $orderDirection) = explode('_', $orderBy);
        $orderDirection = $orderDirection ?: 'DESC';
        return $query->orderBy(snake_case($orderField), strtolower($orderDirection));
    }
```

Thanks again!  Maybe this question should also be listed in #106 ?

**Comment by morpheus7CS** [comment]
@kikoseijo Yes, as you can do Model::orderBy('some_attribute') on all Eloquent models I think.
