### ISSUE TITLE
v3.1 is not support  lumen version

### ISSUE THREAD

**Issue by david890517** [nuwave/lighthouse#724]
I can use v2.6 lighthouse ,but v3.1 can not .

lumen version 5.7.8
php 7.2

Error
(1/1) ReflectionException
Class path.config does not exist

**Comment by spawnia** [comment]
We do not explicitely provide Lumen support right now. If you require compatibility, feel free to open a PR with the necessary changes.

**Comment by ileonardo-c** [comment]
You can work around this problem by adding this code in the `bootstrap\app.php`:
```
$app->instance('path.config', app()->basePath() . DIRECTORY_SEPARATOR . 'config');
$app->instance('path.storage', app()->basePath() . DIRECTORY_SEPARATOR . 'storage');
```

But now it shows the error `NotFoundHttpException`. Doing a search, if you enter this code in the `public\index.php`:
```
$app->run(
    $app->make('request')
);
```

It will solve the problems, but the **GraphQL Playground** can not find the **schema**, someone helps :/
