### ISSUE TITLE
Trouble retrieving a date as string - "String cannot represent non scalar value: instance of Illuminate\\Support\\Carbon"

### ISSUE THREAD

**Issue by morpheus7CS** [nuwave/lighthouse#74]
Hey,

I have started building my first project with Lighthouse. 

It's amazingly fast way to building apps. Still, I'm running into an issue with retrieving a string Date representation. I have inserted a new enrty into the database through a mutation.

This is the error that gets returned:
`"String cannot represent non scalar value: instance of Illuminate\\Support\\Carbon"`

Here is the schema file I'm using:
```
# schema.graphql

type Project {
    id: ID!
    parent_id: Parent @belongsTo
    name: String!
    created_at: String
    updated_at: String
    deleted_at: String
}

type Query {
    projects: [Project!]! @field(resolver: "App\\Http\\GraphQL\\ProjectQueries@index")
}
```

As can be seen from `artisan tinker`, the date is present on the data instance:
<img width="403" alt="screen shot 2018-04-10 at 13 57 30" src="https://user-images.githubusercontent.com/8884582/38555664-42914828-3cc7-11e8-8ee7-9985d6dc5b76.png">

And the screenshot from GraphQL Playground:
<img width="1420" alt="screen shot 2018-04-10 at 13 21 24" src="https://user-images.githubusercontent.com/8884582/38555731-8a133efe-3cc7-11e8-9d8c-f65467988feb.png">

Am I doing it wrong or is that an issue that needs additional work on your end?

Thank you again for this package & the work you're doing.

**Comment by hosmelq** [comment]
I think your problem is created_at, etc... because those fields are Carbon instances.

I always create a Scalar Date to convert the carbon instace to a String representation.

**Comment by chrissm79** [comment]
Hey @morpheus7CS, so this message is saying that the `created_at`, `updated_at` or `deleted_at` fields are returning a `Illuminate\Support\Carbon` instance rather than a `string`. There are 3 ways to handle this but the easiest would be to create a custom directive like so:

```php
// app/Http/GraphQL/Directives/DateTimeDirective.php

namespace App\Http\GraphQL\Directives;

use Carbon\Carbon;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Traits\HandlesDirectives;

class DateTimeDirective implements FieldResolver
{
    use HandlesDirectives;

    /**
     * Name of the directive.
     *
     * @return string
     */
    public function name()
    {
        return 'dateTime';
    }

    /**
     * Resolve the field directive.
     *
     * @param FieldValue $value
     *
     * @return FieldValue
     */
    public function resolveField(FieldValue $value)
    {
        $field = $value->getFieldName();

        return $value->setResolver(function ($root) use ($field) {
            $carbon = data_get($root, $field);

            // Format this however you want, but make sure it's a string
            return $carbon instanceof Carbon ? $carbon->toIso8601String() : $carbon;
        });
    }
}
```

And use it in your schema:

```graphql
type Project {
    id: ID!
    parent_id: Parent @belongsTo
    name: String!
    created_at: String @dateTime
    updated_at: String @dateTime
    deleted_at: String @dateTime
}
```

Just a side note, I'll be creating a `Carbon` scalar and a `@carbon(format: "YYYY-mm-dd")` directive that will come with Lighthouse for you to use.

**Comment by kikoseijo** [comment]
This is my solution, 


```php
<?php

namespace App\GraphQL\Scalars;


use Nuwave\Lighthouse\Schema\Types\Scalars\DateTime as LightDateTime;


class DateTime extends LightDateTime
{

}
```

and for your definitions:

```graphql
type User @model {
  created_at: DateTime
  updated_at: DateTime
}
```

**Comment by chrissm79** [comment]
Thanks @kikoseijo!! When I push the update with the scalar and directive I'll check a config option for non-null that way it won't introduce any breaking changes for anyone who's using that scalar.

**Comment by robsontenorio** [comment]
@chrissm79 

I like the idea. The native `@carbon` directive would be very useful. Will it be considered on next version?

```
Just a side note, I'll be creating a Carbon scalar and a @carbon(format: "YYYY-mm-dd") directive that will come with Lighthouse for you to use soon.
```
