### ISSUE TITLE
Find/First by GlobalId

### ISSUE THREAD

**Issue by lucasmichot** [nuwave/lighthouse#749]
**Describe the bug**
I want to query a User in my database by the GlobalId.
I have previously defined a `User` type.
In this example the database ID of my user is 1

Given that:
- `Rm9vOjE=` is the base64 encoded string of `Foo:1`
- `VXNlcjox` is the base64 encoded string of `User:1`

I can find the same user by passing either `Rm9vOjE=` , either `VXNlcjox` to `@find` and `@first` directives

**Expected behavior**

Only `VXNlcjox` (`User:1`) should work: control should be done on the type

**Schema**

```graphql
# Add in relevant parts of your schema definition
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```

</details></br>

**Environment**

Lighthouse Version: 3.4
Laravel Version: 5.8
PHP Version: 7.2

**Additional context**

**Comment by spawnia** [comment]
How does your schema look like for this use case?

**Comment by spawnia** [comment]
`@find` and `@first` assume that the query they are used within is supposed to return just a single type, corresponding to a single Eloquent model. Using global IDs does not really make sense in that context.
