### ISSUE TITLE
No connection could be made because the target machine actively refused it. [tcp:\/\/127.0.0.1:6379]

### ISSUE THREAD

**Issue by sooriyan** [nuwave/lighthouse#750]
**Description of the issue**

This error seems to occur whenever i run my subscription

**Schema**
type Query{
    posts: [Post!]! @all
    post(id: Int! @eq): Post @find
    users: [User!]! @all
    user(id: Int! @eq): User @find
    candidates : [Candidate!]! @all
    candidate(id: Int! @eq): Candidate @find
    constituencies: [Constituency!]! @all
    constituency(id: Int! @eq): Constituency @find
}

type User {
    id: ID!
    name: String!
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
    posts: [Post!]! @hasMany
}

type Candidate {
    id: ID!
    candidate_name: String!
    constituency_id: Int!
    votes: Int!
    created_at: DateTime!
    updated_at: DateTime!
    constituency:Constituency! @belongsTo
}

type Constituency {
    id: ID!
    constituency_name: String!
    created_at: DateTime!
    updated_at: DateTime!
    candidate: [Candidate!]! @hasMany
}

type Post {
    id: ID!
    title: String!
    content: String!
    user: User! @belongsTo
    comments: [Comment!]! @hasMany
}

type Comment{
    id: ID!
    reply: String!
    post: Post! @belongsTo
}

type Subscription {
    voteUpdated: Candidate

}

 

```graphql
type Mutation{
  createUser(name: String!,email: String!,password: String!): User! @create
  updateUser(id: ID!, name: String): User @update
  deleteUser(id: ID!): User @delete
  updateVote(id: ID!, votes: Int!): Candidate @update
    @broadcast(subscription: "voteUpdated")
}
```

**Output/Logs**

<details><summary>127.0.0.1:65113 Invalid request (Malformed HTTP request)</summary>

```
Error in GraphQL playground : 
Could not connect to websocket endpoint ws://127.0.0.1:8000/graphql. Please check if the endpoint url is correct.

Error on API Usage :
{"debugMessage":"No connection could be made because the target machine actively refused it. [tcp:\/\/127.0.0.1:6379]","message":"Internal server error","extensions":{"category":"internal"}
</details></br>
```

**Environment**

Lighthouse Version: 3.3
Laravel Version: 5.8.12
PHP Version: 7.2.9

**Comment by spawnia** [comment]
@sooriyan please enclose your schema within the

    ```graphql
    ```

block as is defined in the template.

**Comment by spawnia** [comment]
I have not experienced such an error before, maybe @chrissm79 can chime in?

**Comment by chrissm79** [comment]
@sooriyan It looks like you're trying to run subscriptions in GraphQL Playground which is not supported. GraphQL Playground expects the websocket server to follow certain conventions to support GraphQL and Pusher (currently) does not. 

In order to use Playground, you'd have to create a websocket server similar to [lighthouse-ws](https://github.com/nuwave/lighthouse-ws) (which is depreciated in favor of the current implementation inspired by [Ruby](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/subscriptions/overview.md)).
