### ISSUE TITLE
Add Caching Ability to Schema Build Process

### ISSUE THREAD

**Issue by nrobates** [nuwave/lighthouse#751]
**Is your feature request related to a problem? Please describe.**

The issue is that when you have larger sized API's that use the package the request duration is actually taking longer than other GraphQL packages. We recently migrated from the `SonarSoftware/laravel-graphql` GraphQL package and now all of our requests are taking twice as long to complete.

**Describe the solution you'd like**

I have done a considerable amount of tracing and profiling and have pinpointed the issue to be inside the `nuwave/lighthouse/src/GraphQL.php` file in the `prepSchema` method. While the documentAST is cached, the real problem is that the following needs to be cached:
```
if (empty($this->executableSchema)) {
            $this->executableSchema = $this->schemaBuilder->build(
                $this->documentAST()
            );
}
```
We really need to have `$this->executableSchema` to be cached as the build process on every request is negatively affecting the request time. However just trying to add in a cache to test this was meant with a great deal of `Serialization of 'Closure' is not allowed` errors.

Any suggestions or thoughts on this would be appreciated.

**Comment by spawnia** [comment]
Thanks for the issue, i am aware of the performance problems.

Generally, Closures should be able to be serialized through https://github.com/opis/closure, if this is easy enough to do, we might employ this as a quick and easy fix.

While this approach could help and should require little work, i think the most effective solution to the performance problem would be to utilize [lazy-loading of types](http://webonyx.github.io/graphql-php/type-system/schema/#lazy-loading-of-types).

We are tracking this over at https://github.com/nuwave/lighthouse/issues/400
