### ISSUE TITLE
BindingResolutionException while building ErrorBuffer, occurs when using xDebug

### ISSUE THREAD

**Issue by felyx** [nuwave/lighthouse#755]
I get the following error when I am trying to debug the code executed through a graphql query or mutation with xdebug:

Exception has occurred.
Illuminate\Contracts\Container\BindingResolutionException: Target [Closure] is not instantiable while building [Nuwave\Lighthouse\Execution\ErrorBuffer].

This only happens if the debugger has to go through graphql (lighthouse) otherwise it works fine (meaning I can debug the code and does not get stopped at the above-mentioned error). I tried it on an existing project and on a completely new and clean install of everything.

The clean install had the following:
- OS: Windows 10
- Laravel: v5.8.14
- PHP: v7.3.4 NTS x64
- XDebug: v2.7.1 NTS
- Lighthouse-PHP: v3.4.0

The clean install hasn't had a single line of custom code, I only used what I got with the installs (user queries and default routes).

Please help me fix this issue, thank you!

**Comment by spawnia** [comment]
Can you try if https://github.com/nuwave/lighthouse/pull/756 fixes this for you?

**Comment by felyx** [comment]
> Can you try if #756 fixes this for you?

Thank you for the reply, this does fix the issue!

**Comment by spawnia** [comment]
Let's close this issue as #756 is merged.
