### ISSUE TITLE
Allow query input using @spread to be optional

### ISSUE THREAD

**Issue by cradigan** [nuwave/lighthouse#770]
**Is your feature request related to a problem? Please describe.**

I'm currently using the @spread directive on an input to filter a query like so:

```
input UsersFiltersInput{
    id: SimpleIdFilter @eq
    login: SimpleStringFilter @eq
    ...
}

type Query{
    users(
            filters: UsersFiltersInput @spread
            orderBy: [OrderByClause!] @orderBy
        ): [User] 
        @all 
    usersPaginated(
            filters: UsersFiltersInput @spread
            orderBy: [OrderByClause!] @orderBy
        ): [User]
        @paginate(defaultCount: 25)
}
```

Right now, everything works so long as you pass the filters argument into the query.
If you omit the argument, you get the following error:

   • Invalid argument supplied for foreach()

Because of these lines in Schema/Factory/FieldFactory.php

```
                    foreach ($this->spreadPaths as $argumentPath) {
                        $inputValues = $this->argValue($argumentPath);
                        $this->unsetArgValue($argumentPath);

                        array_pop($argumentPath);

                        foreach ($inputValues as $key => $value) {
                            $this->setArgValue(
                                array_merge($argumentPath, [$key]),
                                $value
                            );
                        }
                    }
```

**I'd like to be able to omit my filters input arg and have lighthouse return all results unfiltered**

**Describe the solution you'd like**

Run a check that spreadsPath is not empty before running logic.
```
                if (!empty($this->spreadPaths)){
                    foreach ($this->spreadPaths as $argumentPath) {
                        $inputValues = $this->argValue($argumentPath);
                        $this->unsetArgValue($argumentPath);

                        array_pop($argumentPath);

                        foreach ($inputValues as $key => $value) {
                            $this->setArgValue(
                                array_merge($argumentPath, [$key]),
                                $value
                            );
                        }
                    }
                }
```

**Comment by spawnia** [comment]
Hey @cradigan thanks for the detailed bug report. Looks like you have it figured out.

Check our contribution guidelines for info on how you can submit a PR: https://github.com/nuwave/lighthouse/blob/master/.github/CONTRIBUTING.md

As a bit of guidance, you can look at some other directive tests in https://github.com/nuwave/lighthouse/tree/master/tests/Unit/Schema/Directives

Just add a new one called `SpreadDirectiveTest`, add the failing test scenario you described, and try out your fix!

**Comment by cradigan** [comment]
Thanks for the info @spawnia, was very helpful
Submitted a PR.
