### ISSUE TITLE
Include PHP defined types in the schema

### ISSUE THREAD

**Issue by mfn** [nuwave/lighthouse#771]
**Is your feature request related to a problem? Please describe.**

It's not uncommon that existing business logic is used to build a GraphQL API, using existing code complete resolvers, etc.

The same applies to values of enums: it's not uncommon that a bigger projects already make heavy use of constants throughout their code base and want to reuse their values as part of a GraphQL API.

As of now, it's not possible: the definition in the schema is separate, and currently cannot be combined, with any existing possible code definitions of enums, array of constants, etc.

I discovered this problem whilst evaluation migration from Folklore to lighthouse.

**Describe the solution you'd like**

Provide a way, perhaps a directive (?), with which a enum declared in a schema can be mapped to some code ("resolved via code"?).

**Describe alternatives you've considered**

I am currently using the outdated [Folklore GraphQL library](https://github.com/Folkloreatelier/laravel-graphql) with which enums are declared as code, like this:
```php
class AttachmentCategoryEnum extends GraphQLType
{
    public const TYPE = 'AttachmentCategory';
    protected $enumObject = true;

    protected $attributes = [
        'name' => self::TYPE,
        'description' => 'The valid categories for attachments.',
        'values' => Attachment::ALL_CATEGORIES,
    ];
}
```
The reference of `Attachment::ALL_CATEGORIES` as a simple array of existing constants, e.g.:
```php
    public const ALL_CATEGORIES = [
        self::CATEGORY_AUDIO,
        self::CATEGORY_FILE,
        self::CATEGORY_LINK,
        self::CATEGORY_PHOTO,
        self::CATEGORY_TWEET,
        self::CATEGORY_VIDEO,
    ];
```
And each constant further represents a category, etc.

By registering this `AttachmentCategoryEnum` type in Folklore `config/graphql.php` it's available for consumption and such logic can be shared between the domain and GraphQL quite easily.

Sometimes such values are also generated or have to be mapped or filtered, as such flexibility through code is desired.

**Additional context**

From a quick discussion on slack between me and @spawnia : 
> > me
>> I can't figure out: how can I resolve the actual enums from existing PHP code? I've LOTS of constants defined in the app which I would like to leverage directly instead of having to redefine them.
> > For some perspective I've currently defined 25 Enums in my Folklore graphql application and the majority uses / references existing constants from the code base / business logic which are a LOT constants (hmm, maybe 60-80?), so re-using makes a lot of sense here.

> spawnia:
> Hey, right now you can not add types from PHP
> Your use case seems totally valid though, maybe we can expose a hook into the schema generation to add types programmatically

**Comment by spawnia** [comment]
> Provide a way, perhaps a directive (?), with which a enum declared in a schema can be mapped to some code ("resolved via code"?).

While Lighthouse is generally schema first, i think this is a case where we might do something different.

The reason being that in order to define a valid, parseable enum in SDL, you would have to add at least one field. While it is possible to use a directive to return a completely different executable type, it feels weird that the SDL definition is essentially useless.

I see two paths going forward:

1. We extend the `#import` syntax to allow including PHP classes as types. Maybe something like:

    ```graphql
    #import App\GraphQL\MyEnumClass.php
    ```

2. We add a hook, possibly through an event, that allows adding PHP types to the executable schema.

**Comment by spawnia** [comment]
@mfn just realized you can do that already. Added docs plus a nice extra feature in #779

**Comment by mfn** [comment]
Thank you very much, that of course is very compelling and fixes the issue.
