### ISSUE TITLE
Multiple schema files in config [not multiple schema] 

### ISSUE THREAD

**Issue by ZaidBarghouthi** [nuwave/lighthouse#775]
**Is your feature request related to a problem? Please describe.**
I'd like to use [laravel modules](https://github.com/nWidart/laravel-modules) package to add some functionality to my project, I'd like to use graphql in that module as well. What would be any easy way to tell my app about the types, queries, mutations, ...etc in the module while keeping all the module config in the module or in `config/mymoduleconfig.php`?

**Describe the solution you'd like**
The way is to have the module modify the config, basically it can register another schema file in the lighthouse config but this is not supported.

**Describe alternatives you've considered**
Haven't thought of any

**Additional context**

**Comment by enzonotario** [comment]
Hi! What I do is, in my `schema.graphql`:
```
.... your schema ...
#import app/Modules/*/Graphql/*.graphql
```

So, in every module, I have a graphql file, like: `app/Modules/User/Graphql/user.graphql`.
That file, contains:
```
#import */*.graphql
```

So, I can modularize my graphql files like;
app/Modules/User/Graphql/
    | Queries
        | users.graphql
    | Mutations
        | createUser.graphql

or you can organize them as you want. The important is the include in the `schema.graphql`.

Hope it helps!

**Comment by ZaidBarghouthi** [comment]
@enzonotario that is very good approach. Thank you. 

I'm keeping this open for the next 24 hours in case someone have another idea, but you solve it).

Cheers!

**Comment by spawnia** [comment]
Just have the ServiceProvider of your module listen to the [BuildSchemaString](https://lighthouse-php.com/master/api-reference/events.html#buildschemastring) event and add it in there.

**Comment by ZaidBarghouthi** [comment]
Thanks @spawnia
