### ISSUE TITLE
Some directives are missing their arguments in the docs

### ISSUE THREAD

**Issue by alberthaff** [nuwave/lighthouse#782]
Some of the directives are missing some of their arguments in the docs.

This includes:

- `@all`
- `@first`
- `@paginate`

**Comment by spawnia** [comment]
Hey, i would love to see a PR for that :)

**Comment by alberthaff** [comment]
I will go through the rest of them and make a PR tomorrow.

**Comment by alberthaff** [comment]
I think we may need to add a table to each directive with their arguments. It will easily get cluttered if we add multiple arguments to the snippets.


Something like this could make it easier to see which arguments are available on a directive:

## @belongsTo

| Argument      | Type          | Default | Description  | 
| ------------- |:-------------:| :-----:| :----- |
| relation      | String | | Select the method from which to fetch related models. |
| scopes      | [String]      |   [] | Select which scopes to apply to the underlying query. |
| defaultCount | Int      | *Global setting used* | Select the default count. |
| maxCount | Int      | *Global setting used* | Select the max count. |

**Comment by spawnia** [comment]
Let's go for a formal directive definition in SDL.

**Comment by alberthaff** [comment]
That would be a great addition!

However, i think we should also add the arguments to the directives page, since some people probably won't install the JS-graphql plugin or use an IDE without graphql autocompletion.
I often see questions on Slack from people who don't know that certain arguments are available. 

Should i add an abstract variable called `$directiveSDL` and define it in each directive on that variable?

**Comment by spawnia** [comment]
Agreed, we should definitely do both.

Let's just add the definitions to the docs as a first step, while we figure out how we can include them in the directive classes.

**Comment by alberthaff** [comment]
Okay. I'll add the arguments like this:

![image](https://user-images.githubusercontent.com/3864165/57583035-a6142800-74cc-11e9-8eca-fe9b5007ab5a.png)

**Comment by spawnia** [comment]
@alberthaff let's just use the directive definition instead of that table. It has all the elements of the table, but is way more useful outside of the docs.

**Comment by alberthaff** [comment]
Alright. How do you want the layout? Like this?

## @auth

Return the currently authenticated user as the result of a query.

```graphql
type Query {
    me: User @auth
}
```

If you need to use a guard besides the default to resolve the authenticated user,
you can pass the guard name as the `guard` argument

```graphql
type Query {
    me: User @auth(guard: "api")
}
```

### SDL

```
SDL HERE
```

**Comment by spawnia** [comment]
How about something like this?

## @directive

A one line description of the directives funtionality.

```graphql
A basic example with the most common use.
```

### Definition (we might have that formatted as bold, i don't want it in the sidebar)

```graphql
The formal SDL definition
```

More examples, further explanation of the additional use cases/arguments

**Comment by alberthaff** [comment]
Perfect. Vuepress ignores h3 in the sidebar, so that is not a problem :-)
