### ISSUE TITLE
Where constraints documentation shows wrong provider

### ISSUE THREAD

**Issue by zwzn** [nuwave/lighthouse#788]
In the where constraints documentation it tells you to add a service provider, but the one that is shown is the wrong one. [docs](https://lighthouse-php.com/3.6/api-reference/directives.html#whereconstraints)

The docs tell you to add the `DeferServiceProvider`

``` php
'providers' => [
    \Nuwave\Lighthouse\Defer\DeferServiceProvider::class,
],
```

It should show the `WhereConstraintsServiceProvider`

``` php
'providers' => [
        \Nuwave\Lighthouse\WhereConstraints\WhereConstraintsServiceProvider::class,
],
```

**Comment by spawnia** [comment]
Thanks for the report!

**Comment by maobunthon** [comment]
Hi,
I follow this https://lighthouse-php.com/3.6/api-reference/directives.html#whereconstraints
lighthouse-php.com

I added `\Nuwave\Lighthouse\WhereConstraints\WhereConstraintsServiceProvider::class,` in config/app.php

And `type Query {
    people(where: WhereConstraints @whereConstraints): [Person!]!
}`

but i got error `Server cannot be reached` `Unexpected token < in JSON at position 0` in playground
