### ISSUE TITLE
/graphql endpoint not shown in route:list neither can be visited from browser

### ISSUE THREAD

**Issue by vaishnavmhetre** [nuwave/lighthouse#798]
I followed the Lumen setup (pretty old though) from (https://github.com/kikoseijo/lumen-lighthouse-graphql) but I dont have `/graphql` endpoint in `route:list` after all!

I still tried visiting it through a browser as Graphql Playground repoted `JSON error starting with <` i.e its parsing HTML unknowingly, but I get *NotFoundHttpException* on the browser.

**Comment by spawnia** [comment]
Please follow the issue template.

**Comment by vaishnavmhetre** [comment]
Hello @spawnia, I'd be happy to follow to the template if it was a proved bug for me. Its a clarification. Please do read the description once, I've mentioned necessary information of query and links to referred repos. In case you want some, please do ask, I'll provide it. 

Better than just the issue with no help at all right?

**Comment by spawnia** [comment]
Your issue is missing crucial info such as the installed Lighthouse version.

The issue tracker is not a support forum. If you can gather some actionable information that suggests we fix a bug, add a feature or enhance the docs, that would be a reason for me to reopen.
