### ISSUE TITLE
Please clean up the branches :)

### ISSUE THREAD

**Issue by hailwood** [nuwave/lighthouse#80]
Hey @chrissm79 ,

Any chance you could delete the old branches for V1, and add a quick note to the readme regarding the other branches.

E.g. what's the difference between

master
v2-beta
v2.0.x

Cheers!

**Comment by chrissm79** [comment]
@hailwood, couldn't agree more! Cleaned up the branches... v2.0.x will stick around for bugfixes for v2.0, v2-beta has been removed and master will hold all the changes for the v2.1 release. 

Let me know if you have any questions or feedback!!!
