### ISSUE TITLE
[Feat] Error message from exceptions

### ISSUE THREAD

**Issue by olivernybroe** [nuwave/lighthouse#81]
Could be nice with an interface to define custom rendering of exceptions just like Laravels `Illuminate\Contracts\Support\Responsable` interface.

**Comment by olivernybroe** [comment]
@kikoseijo Oh If I can overwrite the error function then I can prob. just implement it myself. 

But what I mean is in Laravel when I implement the Responsable interface, Laravel will render my exception accordingly to the `toResponse($request)` method. 
I for example like throwing exceptions when something is wrong and then handling them in the exceptionshandler and render them to the front end with the `toResponse($request)` method. 

So my proposal is to have an interface like this, but just for rendering the exception for the errors array in graphql.

**Comment by kikoseijo** [comment]
I wonder if this is posible, 
but i guess the Graphql has a try-catch and does its own thing.

Maybe this helps you:

https://github.com/nuwave/lighthouse/blob/882a1b21508f60fcadb21ec7b8bdc320a270a649/src/Support/Traits/CanFormatError.php

**Comment by olivernybroe** [comment]
@spawnia that is another problem, but not the one I am trying to solve here. I merely won't to implement a interface on my exception class, and if this interface exists, then a specific method on the exception tells how to render the exception in the errors array on the output.

**Comment by spawnia** [comment]
@olivernybroe can this be closed as of #235 ?
