### ISSUE TITLE
Cannot use @whereConstraints directive

### ISSUE THREAD

**Issue by maobunthon** [nuwave/lighthouse#811]
**Describe the bug**
I want to use @whereConstraints directive and i follow instruction here
https://lighthouse-php.com/3.6/api-reference/directives.html#whereconstraints

**Expected behavior**

Should be able to use whereConstraints directive

**Schema**

```graphql

type Query {
    posts(where: WhereConstraints @whereConstraints orderBy: [OrderByClause!] @orderBy): [Post!]! @paginate(type: "paginator" model: "App\\Model\\Post")
    post(id: Int! @eq): Post @find
}
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
[2019-05-25 03:27:24] local.ERROR: No type Operator was registered. {"exception":"[object] (GraphQL\\Error\\InvariantViolation(code: 0): No type Operator was registered. at /Users/sduser/projects/vendor/nuwave/lighthouse/src/Schema/TypeRegistry.php:48)
```

</details></br>

**Environment**

Lighthouse Version: 3.6.1
Laravel Version: 5.7
PHP Version: 7.1.23

**Additional context**

I added `\Nuwave\Lighthouse\WhereConstraints\WhereConstraintsServiceProvider::class,` in config/app.php

**Comment by spawnia** [comment]
The error message is pretty clear, it seems to me you are missing an `enum Operator` that is required for `@whereConstraints`. As the docs say, you must add it to your schema yourself.

**Comment by maobunthon** [comment]
Oppps, Thanks @spawnia this is my bad i didn't read the docs carefully and missing add `enum Operator {
    EQ @enum(value: "=")
    NEQ @enum(value: "!=")
    GT @enum(value: ">")
    GTE @enum(value: ">=")
    LT @enum(value: "<")
    LTE @enum(value: "<=")
    LIKE @enum(value: "LIKE")
    NOT_LIKE @enum(value: "NOT_LIKE")
}` to my schema.
