### ISSUE TITLE
@auth directive and Auth::user() not working

### ISSUE THREAD

**Issue by julesmons** [nuwave/lighthouse#813]
I created a new laravel project and followed Christopher's youtube tutorial for authentication.

The schema can be viewed using GraphQL Playground, logging in works (a token is returned when the mutation is called).

However, when i use the "me" query that uses the @auth directive, it returns "null".

Also the method Auth::user() called inside a middleware returns null aswell.

All of this happens even though i have an authorization header setup in GraphQL Playground:

> {
>     "Authorization": "Bearer *TOKEN HERE*"
> }

The token is the one the login mutation returned.

Did i do something wrong?
Does something need to be registered somewhere in order for this to work?

**Comment by spawnia** [comment]
Make sure your `me` query is wrapped in authentication middleware.

**Comment by julesmons** [comment]
I've wrapped it in my own authentication middleware, and now it returns a not authorised exception. this is because my middleware works by using Auth::user() and this returns null for some reason. 

I think the authentication header is not correctly parsed or something.

**Comment by julesmons** [comment]
The reason i think this is the case, is because inside a resolver the $context->user variable is also empty **despite having a valid authorization header!.**

I really think i did something wrong.

**Comment by julesmons** [comment]
Maybe passport is not configured correctly?

**Comment by julesmons** [comment]
Okay, i have fixed it. It was indeed passport. I had to properly configure config/auth.php to use passport instead of the default.
