### ISSUE TITLE
Multiple @where directives on a single field

### ISSUE THREAD

**Issue by cwhitby** [nuwave/lighthouse#831]
**Is your feature request related to a problem? Please describe.**

It would be great if we could apply multiple `@where` directives to a single field.
For example:
```graphql
input AuditFilterInput {
    date_after: Date @where(operator: ">=", key: "date") @where(operator: ">=", clause: "orWhere", key: "created_at")
}
```
In this case, only the first directive is applied.

**Describe the solution you'd like**

I can think of 3 options:

A) Allow multiple instances of the `@where` directive. I don't think any other directive allows this either so there might be a limitation in the core of Lighthouse.

B) Allow the `@where` directive to accept an array of conditions, in a similar format to how the Laravel Query Builder does.

C) This behaviour already exists somewhere and I just can't see it in the docs.

Curious to see what others think.

**Comment by spawnia** [comment]
Have you actually tried this in the most recent version of Lighthouse? I agree that this should work.

**Comment by cwhitby** [comment]
It was originally tested using version `3.7.0`, I've just checked again using `4.0-alpha.2` with the same result.

**Comment by spawnia** [comment]
Can you provide a PR with a failing test case in https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Execution/BuilderTest.php please?

**Comment by spawnia** [comment]
We can enable this feature (and possibly other use cases of applying the same directive repeatedly) once the spec allows it:  https://github.com/graphql/graphql-spec/pull/472

**Comment by spawnia** [comment]
Changed handling of the argument filters makes this work for `@where` now, at least https://github.com/nuwave/lighthouse/pull/834 passed for now.

General availability and proper documentation of `repeatable` directives will be tracked in https://github.com/nuwave/lighthouse/issues/1133.

Feel free to reopen if you still experience issues.
