### ISSUE TITLE
No directive found for `whereConstraints`

### ISSUE THREAD

**Issue by kyawsithu** [nuwave/lighthouse#839]
**Describe the bug**

{
  "error": {
    "message": "No directive found for `whereConstraints`",
    "status_code": 500
  }
}

**Expected behavior**

**Schema**
type User {
  id: ID!
  name: String!
  email: String!
  created_at: DateTime!
  updated_at: DateTime!
}

type Doctor {
  id: ID!
  name: String!
  created_at: DateTime!
  updated_at: DateTime!
}

type Product {
  id: ID!
  name: String!
  content: String!
  packaging: String!
  created_at: DateTime!
  updated_at: DateTime!
}

type Pdp {
  id: ID!
  doctor: Doctor @belongsTo
  product: Product @belongsTo
  created_at: DateTime!
  updated_at: DateTime!
}

type Query @middleware(checks: ["auth:api"]){
  me: User @auth(guard: "api")

  users: [User!]! @paginate(type: "paginator" model: "App\\User")

  doctorStatus(where: WhereConstraints @whereConstraints): [Pdp!]!
}

enum Operator {
  EQ @enum(value: "=")
  NEQ @enum(value: "!=")
  GT @enum(value: ">")
  GTE @enum(value: ">=")
  LT @enum(value: "<")
  LTE @enum(value: "<=")
  LIKE @enum(value: "LIKE")
  NOT_LIKE @enum(value: "NOT_LIKE")
}
```graphql
# Add in relevant parts of your schema definition
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
# Add in log output/error messages here
```
{
  "error": {
    "message": "No directive found for `whereConstraints`",
    "status_code": 500
  }
}
</details></br>

**Environment**

Lighthouse Version: 3.7
Laravel Version: 5.5.45
PHP Version: 7.1.10

**Additional context**

**Comment by spawnia** [comment]
You must register it in `config/app.php`
