### ISSUE TITLE
Is possible lighthouse php use laravel echo self hosting with subscription?

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#840]
Is possible lighthouse php use laravel echo self hosting with subscription?

All time that I use laravel with laravel echo I use with laravel echo server, self hosting in my machine.

**Comment by spawnia** [comment]
It is not supported out of the box, but it should be doable. Generally, subscriptions allow you to plug in different drives.

If you figure it out, i would happily see a PR.

**Comment by IgorDePaula** [comment]
I tried with laravel-echo-server, but, I tried wth your client implementation example of docs. I puted console.log in all methods to I see how all works, but, the console.log's not show none data in console dev tools. In others words: that client implementation example not works.

**Comment by spawnia** [comment]
I will happily take a PR to improve the docs.

**Comment by IgorDePaula** [comment]
Yes, I'm working this.
