### ISSUE TITLE
How are Accessors & Mutators works?

### ISSUE THREAD

**Issue by windows1087** [nuwave/lighthouse#841]
We can define accessors in Laravel, see https://laravel.com/docs/5.8/eloquent-mutators

How does this work with graphql? Or is this feature not available for graphlq in general?

**Comment by enzonotario** [comment]
What are you trying to do? How is your schema? What troubles are you having?

Accessors works fine with Lighthouse.

**Comment by spawnia** [comment]
Lighthouse respects them whenever it operates on Models.
