### ISSUE TITLE
Subscriptions events are not fired when no subscribers are present

### ISSUE THREAD

**Issue by juusopiikkila** [nuwave/lighthouse#842]
**Describe the bug**

Lighthouse does not fire subscription events to Pusher when subscription is supposed to be fired by the schema.

**Expected behavior**

Subscription would be fired and I would see the event in Pusher's log.

**Schema**

```graphql
type Note @model(class: "App\\Note") {
    id: ID! @globalId
    title: String!
}

type Subscription {
    noteCreated: Note
}

type Mutation {
    createNote(title: String!): Note! @create @broadcast(subscription: "noteCreated")
}
```

**Environment**

Lighthouse Version: 3.7.0
Laravel Version: 5.8.17
PHP Version: 7.2.5

**Comment by hosmelq** [comment]
Same problem here.

`No subscription field registered for gameUpdated`

**Comment by enzonotario** [comment]
Is your client subscribed to `noteCreated`? If there is not any subscriber, Lighthouse will not trigger the Subscription (at least it is what I understand and I think that this is for eficiency).

**Comment by spawnia** [comment]
@juusopiikkila can you check the implementation of your `noteCreated` field? Are there any logs or errors?

**Comment by juusopiikkila** [comment]
Here's the subscription class. There aren't any errors or other messages in Laravel's logs.

```
<?php

namespace App\GraphQL\Subscriptions;

use Illuminate\Http\Request;
use Nuwave\Lighthouse\Subscriptions\Subscriber;
use Nuwave\Lighthouse\Schema\Types\GraphQLSubscription;

class NoteCreated extends GraphQLSubscription
{
    /**
     * Check if subscriber is allowed to listen to the subscription.
     *
     * @param  \Nuwave\Lighthouse\Subscriptions\Subscriber  $subscriber
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public function authorize(Subscriber $subscriber, Request $request): bool
    {
        return true;
    }

    /**
     * Filter which subscribers should receive the subscription.
     *
     * @param  \Nuwave\Lighthouse\Subscriptions\Subscriber  $subscriber
     * @param  mixed  $root
     * @return bool
     */
    public function filter(Subscriber $subscriber, $root): bool
    {
        return true;
    }
}
```

@enzonotario I don't think Lighthouse knows anything about the subscribers since the WS server is in Pusher and the traffic is just one-way.

**Comment by spawnia** [comment]
I think there are two different problems happening.

@juusopiikkila i recommend you step through the request that should trigger the subscription using a debugger. Our test suite generally covers Subscriptions and it has been proven to work in general. Can't see anything obviously wrong with your code.

@hosmelq have you resolved your issue yet? If not, can you post a complete error message including the stacktrace?

**Comment by alberthaff** [comment]
@spawnia I'm getting the same error with v. 4.0-alpha.3. The field `notificationCreated` is visible in GraphiQL. It seems that the field is never registered in `SubscriptionRegistry`.

Schema:

```graphql
type Subscription {
    notificationCreated: Notification
}
```

I have created a test-command, that fires:

```php
$data = Notification::find('dff9c576-8514-4380-9033-50fdaa4b2f8c');
Nuwave\Lighthouse\Execution\Utils\Subscription::broadcast('notificationCreated', $data);
```

Exception:
```
In Subscription.php line 36:
                                                            
  [InvalidArgumentException]                                
  No subscription field registered for notificationCreated  
                                                            

Exception trace:
 () at /Users/alberthaff/git/project/vendor/nuwave/lighthouse/src/Execution/Utils/Subscription.php:36
 Nuwave\Lighthouse\Execution\Utils\Subscription::broadcast() at /Users/alberthaff/git/project/app/Console/Commands/NotifyTest.php:54
 App\Console\Commands\NotifyTest->handle() at n/a:n/a
 call_user_func_array() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:572
 Illuminate\Container\Container->call() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /Users/alberthaff/git/project/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /Users/alberthaff/git/project/vendor/symfony/console/Application.php:908
 Symfony\Component\Console\Application->doRunCommand() at /Users/alberthaff/git/project/vendor/symfony/console/Application.php:269
 Symfony\Component\Console\Application->doRun() at /Users/alberthaff/git/project/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Console/Application.php:89
 Illuminate\Console\Application->run() at /Users/alberthaff/git/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /Users/alberthaff/git/project/artisan:35

```

**Comment by spawnia** [comment]
I suspect this is happening because as of `v4`, fields are no longer eagerly constructed but rather lazily loaded when needed. This results in the Subscription fields not getting registered after the initial request.

We should add a trigger to the `SubscriptionServiceProvider` that ensures that the fields are always registered, as subscriptions may need to be triggered even when not resolving a GraphQL request. For example when using the `Subscription::broadcast()` helper.

**Comment by alberthaff** [comment]
Yeah, it would probably be the cleanest solution.

I think it should trigger automatically on normal query-requests and when `Subscription::broadcast()` is fired. If we wrap the logic inside of the trigger in `if(empty(SubscriptionRegistry::keys())) {}` it shouldn't be a problem, performance wise.

Is the fields also lazyloaded in v. 3.7.0? It is my understanding, that @juusopiikkila also had this problem with 3.7.0.

**Comment by spawnia** [comment]
It seems to me that there are two different issues going on here.

**Comment by juusopiikkila** [comment]
Yeah, I think that it wasn't a bug in v3.7.0. As @enzonotario suggested I had no subscribers registered through the subscriptions auth endpoint so the broadcaster didn't fire the event to Pusher.

**Comment by spawnia** [comment]
Let's continue the bug hunt in https://github.com/nuwave/lighthouse/issues/851.

Can this one be closed, @juusopiikkila ?

**Comment by juusopiikkila** [comment]
Yeah go ahead

**Comment by vaimeo** [comment]
Issue is not solved still
