### ISSUE TITLE
Upload not get searched fields 

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#866]
**Describe the bug**

I make a test to upload a file and get a list of properties, but the lighthouse not get properties, only a numeric array.

**Expected behavior/Solution**
I want get a list of properties for front like vuejs

**Steps to reproduce**

https://gist.github.com/IgorDePaula/83ee8d37f03bbea69a740b2fd5640c47

**Environment**

Lighthouse Version: ^3.7
Laravel Version: 5.8

**Comment by spawnia** [comment]
The file upload seems to be working alright in your example, correct?

I think the problem is a mismatch between the schema and what you return:

```
uploadBoleto(file: Upload!): [[String]] @field(resolver: "App\\GraphQL\\Mutations\\UploadDebitoItau@resolve")
```

Lists in GraphQL are not like associative arrays. Either return a plain numerically indexed list or switch to a list of proper types.

**Comment by IgorDePaula** [comment]
Yes, the upload work fine, but the return does not work properly. If the graphql returns json, it can returns associative arrays. Not?

**Comment by spawnia** [comment]
The return type `[[String]]` would be satisfied by a PHP array like:

```php
[
  ["foo", "bar"],
  ["baz"],
]
```

For your case, try a type like:

```graphql
boleto: [Boleto]

type Boleto {
  ocorrencia: String
  nome: String
}
```

**Comment by IgorDePaula** [comment]
Ok, I will try. Thanks.

**Comment by IgorDePaula** [comment]
I tried, but I received 2 differents results.

if I try:
``` '
            {
                "query": "mutation uploadBoleto($file: Upload!) { uploadBoleto(file: $file){
                nome 
                ocorrencia
                }}",
                "variables": {
                    "file": null
                }
            }
```
It not result how I would liked, but

```
          '
            {
                "query": "mutation uploadBoleto($file: Upload!) { uploadBoleto(file: $file){nome ocorrencia}}",
                "variables": {
                    "file": null
                }
            }
```

Returns the result I would like.
