### ISSUE TITLE
lighthouse graphql subscriptions

### ISSUE THREAD

**Issue by gehad17** [nuwave/lighthouse#874]
Hello All
Can anyone tell me how to use lighthouse graphql subscriptions, i did all the steps as explained here https://lighthouse-php.com/3.1/extensions/subscriptions.html but when mobile team (android and ios ) trying to use it, it asking them to enter websocket endpoint so how can i make this websocket with graphql lighthouse subscription, i know about laravel websocket in general but how to connect this websockets with graphql lighthouse subscription?

**Comment by JasonTheAdams** [comment]
@gehad17 Are you actually using Lighthouse 3.1, or are you just looking at old docs? For contrast, here are the new docs: https://lighthouse-php.com/master/subscriptions/getting-started.html

**Comment by gehad17** [comment]
I'm using lighthouse graphql subscription as mentioned in this docs the
last version of lighthouse, I want know if I should create WebSocket for
mobile developers as they trying to use it but it is not working without
WebSocket url. So I want to know how to generate this websockets with
graphql subscription

**Comment by spawnia** [comment]
The issue tracker is not for support questions. You can ask those in Slack or StackOverflow.
