### ISSUE TITLE
I can't paginate with field directive

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#877]
**Describe the bug**
I need  query an users with specific role and I created a resolver for this, but create a conflict between 2 directives: field and paginate directives

I tried too use PaginatorField, without success

**Expected behavior/Solution**
I hope received paginated data
**Steps to reproduce**
Try query
```
donators(count: Int!, page: Int!): [User!]! @paginate @field(resolver: "App\\GraphQL\\Queries\\GetDonators@resolve")
```

**Output/Logs**

<details><summary>Click to expand</summary>
 "message": "Node [donators] can only have one directive of type [Nuwave\\Lighthouse\\Support\\Contracts\\FieldResolver] but found []",
    "exception": "Nuwave\\Lighthouse\\Exceptions\\DirectiveException",
</details></br>

**Environment**

Lighthouse Version: 3.7
Laravel Version: 5.8

**Comment by spawnia** [comment]
That's expected behaviour, and i think the error message is pretty clear. Both `@paginate` and `@field` are resolver directives, but there can only ever be one resolver for a field.

**Comment by IgorDePaula** [comment]
Ok, how I paginate my data now? I need recover a model with specific scope.

**Comment by spawnia** [comment]
You can use `scopes` as well. It's all in the docs.

**Comment by IgorDePaula** [comment]
GREAT!!!!, Sorry and thank you very much.

**Comment by paulcervov** [comment]
Maybe this will help someone:


```gql
type Query {
    "Geting list of employers"
    findEmployers(
        searchQuery: String
    ): [User!]!
    @paginate(defaultCount: 10, builder: "App\\GraphQL\\Builders\\EmployerBuilder@findEmployers")
    @softDeletes
}
```

```php
<?php

namespace App\GraphQL\Builders;

use App\User;
use Illuminate\Database\Eloquent\Builder;

class EmployerBuilder
{
    public function findEmployers($root, array $args): Builder
    {
        return User::query()
            ->when($args['searchQuery'], function ($query, $searchQuery) {
                $query
                    ->where('first_name', 'like', "%$searchQuery%")
                    ->orWhere('middle_name', 'like', "%$searchQuery%")
                    ->orWhere('last_name', 'like', "%$searchQuery%");
            });
    }
}

```

Works like a charm! ✨
