### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by chrissm79** [nuwave/lighthouse#88]
Currently, this is just a placeholder for discussions. But as a quick progress report, I have gotten started on subscriptions this weekend and it's coming along quite nicely! Right now I have 2 variations in mind:

1. Websockets (`lighthouse-subscriptions-ws`) - The main goal of this package is to keep everything in PHP land. The WS server will be built with [Ratchet](http://socketo.me/). I've tested some things out and I'm able to get Playground to connect/disconnect to a Ratchet server successfully (using the same methods as [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws)). The next step is to start pushing down messages from the server. Since a subscriber can subscribe to multiple subscriptions (lol), I need storage. So it will launch w/ InMemory and Redis storage out of the box, but it can also be extended (i.e., MySQL storage). Because of how far along I am, this will likely be the first package released.

2. Pusher (`lighthouse-subscriptions-pusher`) - Maintaining an websocket server for a massive project doesn't sound fun to me... so I want to include at least one third-party solution. [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) has a great solution for this, however, it does rely on a custom Link for Apollo to work with it. Relay Modern is mentioned too, but I haven't dived into the JS parts of that yet.

The coolest thing (I think) is the fact that I can create these packages completely separate from the main `lighthouse` repo by leveraging directives! So hopefully, the community will be able to create some great alternatives if you use a different 3rd party WS provider or if you have a solution that relies on something other than Ratchet (i.e., Node). 

I currently don't have a timeline for this, it just being done after work hours and on the weekends but this weekend was pretty productive so I'm really hoping it won't be too long before I can get this in everyone's hands!

**Initial Beta Release of [lighthouse-ws](https://github.com/nuwave/lighthouse-ws)**

**Comment by hailwood** [comment]
Hey @chrissm79 completely half baked thought here that is probably entirely down the wrong track, but is there any way to leverage Laravel echo as the websocket provider?

Also, what I'm most curious about here is what api you're looking at implementing for these in terms of the .graphql schema?

**Comment by 4levels** [comment]
Hi @chrissm79,

Subscriptions is indeed my last number one feature for lighthouse, great to hear you're making progress! Since I currently have already a Node ws server running I'd be happy to see where I can help to get this up and running with it.

Redis is also my preferred store for queues and websocket storage..

I'll have a look at Ratchet as well. Interested also in a Laravel Echo implementation as mentioned by @hailwood

**Comment by chrissm79** [comment]
@hailwood @4levels Echo is a pretty interesting prospect, but I feel like I'm jamming a round peg through a square hole at the moment... specifically when attempting to customize data being sent down to the client based on the query they're subscribing to. 

From my previous tests, I can send something like a Post model via the broadcast event, but what if the user subscribed to something like this:

```graphql
subscription onPostCreated {
  postCreated {
    title
    comments {
      # ...
      # How do we know that this client wants the post AND comments?
    }
  }  
}
```

I don't see how I can adjust the [broadcastWith method](https://laravel.com/docs/5.6/broadcasting#broadcast-data) on the event based on the client's subscription request to include the comments or (and more importantly) use defined resolvers for each object type/field.

However, I REALLY like the idea of using Echo as it lowers the barrier of adoption even more so I will certainly circle back to it when the time comes!

**Comment by TGNThump** [comment]
At that point, isn't it functionally the same as executing the following?
```graphql
{
  post(id: [newPostIdFromTheEvent]) {
    title
    comments {
        ...
    }
  }
}
```

**Comment by chrissm79** [comment]
@TGNThump If you're asking if you could just send a query when a subscription gets sent down then yes, but then you don't even need GraphQL subscriptions, you could just use Echo and pull down/refetch when a certain event is fired. 

However, that's not the purpose of GraphQL subscriptions (or Echo really) since that means that you have everyone pulling from your server at the same time when the event fires rather than having the data they want pushed down to them.

**Comment by TGNThump** [comment]
@chrissm79, no I meant executing on the server, but I suppose the problem would be that the broadcastWith would be different for each client... I see where you're coming from.

I suppose you'd have to use a separate channel / echo event for every subscription by every client.

**Comment by chrissm79** [comment]
@TGNThump sorry for the misunderstanding, but yes you're dead on! I think it's **possible**, it's just more efficient to go in another direction for now and then come back and see if I can tackle Echo (i.e., maybe making a custom queue driver).

**Comment by TGNThump** [comment]
I've gotten subscriptions working with lighthouse by setting up a Ratchet\WebSocket server that runs on a Laravel Command and conforms to the https://github.com/apollographql/subscriptions-transport-ws protocol.

I fire an event on a subscription using a custom directive to make my schema cleaner, but using @event would work just as well. All the event listener does is connect to the websocket server and send over the event data.

The websocket server is handles storing the users Passport token and verifying it before every subscription / event. I modified the Context class to include an $event variable that contains the event passed to the server, and passed to the subscription resolvers.

**Comment by chrissm79** [comment]
@TGNThump, damn that looks nice! The only thing I had left on my version was generating and storing the context, but it's pretty verbose and I needed to clean things up quite a bit before release. Your solution looks extremely streamlined and easy to understand 👍 I'll check it out in depth but thank you for providing this!!!

**Comment by TGNThump** [comment]
Figure I might as well integrate it the whole way.

**Comment by chrissm79** [comment]
Here is the first beta release for [lighthouse-ws](https://github.com/nuwave/lighthouse-ws)! Currently, it requires Redis, it works w/ Passport to inject the authenticated user into context, and provides an in-memory storage solution for subscriptions. You can extend the [SubscriptionManager](https://github.com/nuwave/lighthouse-ws/blob/master/src/WebSocket/SubscriptionManager.php) (for storage) and [ContextManager](https://github.com/nuwave/lighthouse-ws/blob/master/src/WebSocket/ContextManager.php) (to generate your own context) if you prefer to create your own solutions here. Before the v1.0 release RedisStorage will be available.

Subscription events can be broadcasted using the custom broadcaster `lighthouse` (which will fire a subscription event when any Laravel event is triggered) and implements the `ShouldBroadcast` interface or you can use the `@websocket` directive to send any mutation result over to `lighthouse-ws`.

The `@subscription` directive works similar to `@field`. Your subscription classes should extend the `Nuwave\Lighthouse\Subscriptions\Schema\Fields\SubscriptionField` class and define a `resolve` function. You can also define a `can` function to allow/reject clients from subscribing to certain subscriptions and a `transform` method to transform the event that was fired over Redis. Before the `v1.0` release I'll create a default `SubscriptionField` class if none is defined that will just pass along whatever was sent via the event.

Big shout out to @TGNThump for providing some great direction on the initial structure!

**Comment by 4levels** [comment]
Hi @chrissm79,

I'm finally able to get my hands dirty on this, but I'm a bit struggling how to go about, well, everything :-)
Am I supposed to simply do `composer require nuwave/lighthouse-ws` in my current project (alongside with lighthouse itself)?

And how do I then define a subscription directive in the schema?
Let's say I want my end users to be able to subscribe to eg. a list of posts so that as soon as a post is added by someone, everyone gets the new post?  Sorry for asking pbbly very obvious instructions here..

FYI I'm using React Native as a frontend for all this and so far I got everything playing along nicely with Lighthouse, super amazed how lighthouse just delivers on the graphql backend!

**Comment by tolu360** [comment]
Hello @chrissm79, superb work you have done on this so far. Kudos!

Please, is there any chance we might get a video walkthrough for `Subscriptions`? I believe one would be very apt. Thank you!

**Comment by merodiro** [comment]
is there a way to fire subscriptions events without @event directive?

**Comment by yaquawa** [comment]
I love this!!!

**Comment by kardoqadir** [comment]
Its great to connect with pusher through lighthouse. Is there anyway to connect with [PHP Swoole](https://www.swoole.co.uk/) ?

**Comment by seedgabo** [comment]
Is this valid today? For version 4.0

**Comment by spawnia** [comment]
Subscriptions are implemented as of Lighthouse v3.

**Comment by seedgabo** [comment]
using graphql-playground the next error appears:
```{
  "error": "Could not connect to websocket endpoint ws://localhost/project/public/graphql. Please check if the endpoint url is correct."
}```

**Comment by chrissm79** [comment]
Subscriptions in Lighthouse are based on the [ruby implementation](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/subscriptions/overview.md) which is not supported by Playground (or any other GraphQL IDE that I'm aware of). 

In order to make it work with Playground you would have to create your own websocket server which implements the same implementation as [apollo-server](https://www.apollographql.com/docs/apollo-server/features/subscriptions/). Similar to [lighthouse-ws](https://github.com/nuwave/lighthouse-ws) which has been depreciated.

**Comment by seedgabo** [comment]
thanks, great job with this package :+1:

**Comment by 4levels** [comment]
You can get it running with laravel websockets as well, at least I can run
queries in grapqhl playground for quite some time now.

Subscriptions seem to work as I do get subscription nodes in the responses
but the subscriptions integration in grapqhl playground doesn't seem to
work so far. I haven't been working on all this for a while now but it
should be possible to make laravel websockets work as well.  I created an
issue once in their repo asking about graphql support. It should be
possible to make it work though.. I also never managed to get a relay
subscription up and running in react either, fwiw.

Setting up a wss server locally involves quite some things though, there be
dragons..

Keep us posted on your progress!

**Comment by gehad17** [comment]
> Subscriptions in Lighthouse are based on the [ruby implementation](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/subscriptions/overview.md) which is not supported by Playground (or any other GraphQL IDE that I'm aware of).
> 
> In order to make it work with Playground you would have to create your own websocket server which implements the same implementation as [apollo-server](https://www.apollographql.com/docs/apollo-server/features/subscriptions/). Similar to [lighthouse-ws](https://github.com/nuwave/lighthouse-ws) which has been depreciated.
How can i create websocket server which connect with lighthouse graphql subscription ?

**Comment by spawnia** [comment]
Subscriptions have been implemented for quite some time, so i am locking this issue. Use Slack or Stackoverflow for support questions. Bugs or new features can be adressed in either a new issue or a PR.
