### ISSUE TITLE
Don't use request middleware for resolver middleware

### ISSUE THREAD

**Issue by pvormittag** [nuwave/lighthouse#880]
Firstly, I've found Lighthouse to be very productive and it's apparent a lot of thought and work has gone into this project, so a big thanks to all contributors! 🙌

**Is your feature request related to a problem? Please describe.**

Currently, middleware are [request middleware](https://laravel.com/docs/5.8/middleware), which implicitly expect a `Response` object to be returned from `$next($request)`, however when using the `@middleware` directive, Lighthouse will return the result from the field resolver. This means any request middleware with after logic will break when attempting to alter the response. I've experienced this with several of the built-in request middleware classes, such as `Illuminate\Session\Middleware\StartSession`.

Additionally, request middleware expect to be called only once per request and are a global concern. Yet resolver middleware may be called many times on many fields during a single request. Any middleware expecting once-per-request semantics may cause sutble-and-hard-to-find bugs when used in the context of resolver middleware.

I've put together a minimal reproducible example to isolate and discuss the issue:
https://github.com/pvormittag/lighthouse-middleware-issue

**Describe the solution you'd like**

Ultimately request and resolver middleware have different concerns and usage patterns, so I believe the solution is for Lighthouse to provide its own resolver middleware alongside request middleware and describe the differences and usage. This would also align with many other GraphQL server implementations.

I can think of several situations where both are useful, such as using request middleware for authn, which needs the request and can for instance, set `$request->user()` as `$context->currentUser`. Then use resolver middleware to handle authz, which is likely used several times as fields have different access control (i.e. `can`).

**Comment by pvormittag** [comment]
I found a few issues I think illustrate how handling the HTTP request is a similar-yet-different concern from handling the GraphQL query. The subtlety lies in their processing logic sharing several semantics, terms and common usage patterns.

#142, #789, #854

These highlight the importance of documenting the subtle differences and if not handled properly, may become a trap for new users and contributors to the project. The changes needed will likely not be backwards compatible, but I feel are important for Lighthouse moving forward.

It is certainly possible to address with `webonyx/graphql-php`. The handoff between Laravel's HTTP handling logic and graphql-php's query handling logic have a well defined boundary, and unfortunately this has been muddled by `@middleware`, `@auth` and a few other directives.

**Comment by Stackout** [comment]
@pvormittag is correct. Using the request middleware for resolver middleware is an issue. I struggled using sessions for the same reason. His explanation helped me understand it.

**Comment by SirLamer** [comment]
Just to add to this, I believe this issue with middleware is preventing me from performing authorization on the subscriptions auth route, no matter what I do I get 403 "unauthorized" in response originating from here: https://github.com/nuwave/lighthouse/blob/b9050146f4e67b751962582b70d3cded9512618d/src/Support/Http/Controllers/SubscriptionController.php#L42

If I don't use the middleware "check" somewhere then the "authorize" method on my actual as-intended subscription class does fire but of course it receives no user and fails anyway.

**Comment by Tairau** [comment]
Can I get user from `$context->request()->user()` ? In this `user()` method I can paste my custom guard like argument.

**Comment by ddedic** [comment]
@SirLamer I have the same problem.. "authorize" method receives no user if middleware "check" is set.. And if I set middleware, subscription returns internal server errors when triggered..

**Comment by spawnia** [comment]
To clarify: This issue was closed because `@middleware` is going to be removed in `v5`.

Global concerns, such as logging in a user who sends authentication information, should be handled in HTTP middleware. Field level concerns, such as guarding access, can be done through field middleware, such as the new `@guard`.
