### ISSUE TITLE
Allow for callable classes for resolvers in directives

### ISSUE THREAD

**Issue by carlalexander** [nuwave/lighthouse#882]
**Is your feature request related to a problem? Please describe.**

To keep code clean, we're implementing a single class per resolver. To do that, we use the `__invoke` method so that the class is callable. Right now, to define such a class as a resolver, we need to do this.

```graphql
type Mutation {
    updateUser(
        id: ID!
        email: String
        name: String
    ): Boolean @field(resolver: "UpdateUserMutation@__invoke")
}
```

But there's no reason why it couldn't be just this:

```graphql
type Mutation {
    updateUser(
        id: ID!
        email: String
        name: String
    ): Boolean @field(resolver: "UpdateUserMutation")
}
```

**Describe the solution you'd like**

The simplest fix, as I see it, is in the `getMethodArgumentParts` method of the `BaseDirective` class.

```php
protected function getMethodArgumentParts(string $argumentName): array
{
    $argumentParts = explode(
        '@',
        $this->directiveArgValue($argumentName)
    );

    if (
        count($argumentParts) !== 2
        || empty($argumentParts[0])
        || empty($argumentParts[1])
    ) {
        throw new DirectiveException(
            "Directive '{$this->name()}' must have an argument '{$argumentName}' in the form 'ClassName@methodName'"
        );
    }

    return $argumentParts;
}
```

You could just automatically put the `__invoke` if there's no method name in `argumentParts` array like this:

```php
protected function getMethodArgumentParts(string $argumentName): array
{
    $argumentParts = explode(
        '@',
        $this->directiveArgValue($argumentName)
    );

    if (
        empty($argumentParts)
        || count($argumentParts) > 2
        || empty($argumentParts[0])
    ) {
        throw new DirectiveException(
            "Directive '{$this->name()}' must have an argument '{$argumentName}' in the form 'ClassName@methodName' or 'ClassName'"
        );
    }
    
    if (empty($argumentParts[1])) {
        $argumentParts[1] = '__invoke';
    }

    return $argumentParts;
}
```

This fix would allow the rest of the code to behave as expected since it always assumes that `getMethodArgumentParts` returns an array with two values in it.

**Comment by olivernybroe** [comment]
Hi, thanks for bringing this up. 

I think you arguments are valid and it makes sense to make this change. This also follows the way Laravel resolves classes, as Laravel also looks for a `__invoke` method.

However one change I would make is make a check for `__invoke` method. This way we can throw an appropriate error, instead of it ending up throwing a `undefined method __invoke`. 


If you are up for it. A PR would be welcome!

**Comment by carlalexander** [comment]
Yup! Happy to do a PR for this @olivernybroe. 😄
