### ISSUE TITLE
Adding arguments to field

### ISSUE THREAD

**Issue by andershagbard** [nuwave/lighthouse#886]
What is the method to add arguments to fields? For example, I want to know the length of my starship in feet/meter/whatever.

```graphql
{
  starship(id: "1000") {
    name
    length(unit: "feet")
  }
}
```

**Comment by olivernybroe** [comment]
https://lighthouse-php.com/master/the-basics/fields.html#fields-with-arguments

For support questions please ask those at StackOverFlow or Slack.
