### ISSUE TITLE
Add model to @node directive to simplify resolving

### ISSUE THREAD

**Issue by JasonTheAdams** [nuwave/lighthouse#888]
**Is your feature request related to a problem? Please describe.**
Presently when using the `@node` directive it's necessary to specify a resolver to get the object. This is pretty redundant, however, as most resolvers will simply be `return Model::where('id', '=', $id)->first()`. It would be nice to just specify a model for the 90% use-case.

**Describe the solution you'd like**
Let's add a `model: String` argument to the directive so the dev may simply do `@node(model: "App\\User")` to resolve the node. We could even add a `key: String` argument so they can specify which column the where condition should compare against.

**Describe alternatives you've considered**
The most obvious alternative is to just make a resolver, but that's really the only present solution.

**Comment by JasonTheAdams** [comment]
Turns out that the `@model` directive does exactly this already. Seems like the `@node` documentation should reference the `@model` directive to point this out.

Also, as Relay features are evolving, it feels like there should be an extra section in the docs devoted to the best ways to use the available Relay features.

**Comment by spawnia** [comment]
> Seems like the @node documentation should reference the @model directive to point this out.

Agreed, looking forward to a PR.

**Comment by JasonTheAdams** [comment]
@spawnia Just added a PR for this.
