### ISSUE TITLE
How use @where directive to query by the same data on 3 differents field with orWhere clasule?

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#889]
**Is your feature request related to a problem? Please describe.**

Yes. I would like query the same data in 3 differents fields with OR Where clasule.
I tried this but not work
https://github.com/nuwave/lighthouse/issues/831

**Describe the solution you'd like**

 I would like query the same data in 3 differents fields with OR Where clasule.

**Describe alternatives you've considered**
I tried this but not work
```
donators(count: Int!, page: Int!, payment_form_id: [Int] @in(key:"payment_form_id"), donator_status_id: [Int]  @in(key:"donator_status_id"), donator_type_id: [Int]  @in(key:"donator_type_id"), shipping_method_id: [Int]  @in(key:"shipping_method_id"), full_name: String @where(operator: "like", clasule:"orWhere", key: "full_name") @where(operator: "like", clasule:"orWhere", key: "document") @where(operator: "like", clasule:"orWhere", key: "email")): [User!]!  @paginate(scopes:["donator"])
```

**Comment by IgorDePaula** [comment]
![Captura de tela de 2019-07-30 16-08-39](https://user-images.githubusercontent.com/2833993/62158343-9646fb80-b2e5-11e9-8a23-44c568248dd3.png)

**Comment by milewski** [comment]
@IgorDePaula wow I know you ... good old MSN times haha 

I think the problem in your query is that you mistyped: clause with clasule :P

**Comment by IgorDePaula** [comment]
@milewski that little world...haha

How I can write my where clasule? I need search the same data in 3 differents fields.

**Comment by milewski** [comment]
@IgorDePaula I mean, did you try this:

```diff
-@where(operator: "like", clasule:"orWhere", key: "email")
+@where(operator: "like", clause:"orWhere", key: "email")
```

**Comment by IgorDePaula** [comment]
I'll try.

**Comment by IgorDePaula** [comment]
![Captura de tela de 2019-07-31 10-28-36](https://user-images.githubusercontent.com/2833993/62215910-305a8280-b37e-11e9-8f06-c0427c0bc7f6.png)

=/ I need search the same information in 3 fields of table, but only search in one field, I need specify 3 fields search in schema?

**Comment by IgorDePaula** [comment]
![Captura de tela de 2019-07-31 10-34-46](https://user-images.githubusercontent.com/2833993/62216364-fa69ce00-b37e-11e9-99aa-f1e0d3999d76.png)
![Captura de tela de 2019-07-31 10-35-05](https://user-images.githubusercontent.com/2833993/62216365-fa69ce00-b37e-11e9-969c-c2bed45c7afe.png)

I change full_name to search field in schema. 

I need search the same information in 3 fields: document, full_name and email.
It only search in document and full_name, but not in email field. =/

**Comment by IgorDePaula** [comment]
How I detected that no search in document too, only full_name, the first clause. =/

**Comment by olivernybroe** [comment]
Look into the directive `whereConstraints`.

**Comment by olivernybroe** [comment]
This question looks more like it belongs on StackOverFlow or our Slack support.
