### ISSUE TITLE
@where throw exceptions 

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#890]
**Describe the bug**
I have the query
```
donators(
  count: Int!
  page: Int!
  payment_form_id: [Int] @in(key:"payment_form_id")
  donator_status_id: [Int]  @in(key:"donator_status_id")
  donator_type_id: [Int]  @in(key:"donator_type_id")
  shipping_method_id: [Int]  @in(key:"shipping_method_id")
  search_full_name: String @where(operator: "like", clause:"orWhere", key: "full_name")
  search_document: String @where(operator: "like", clause:"orWhere", key: "document")
  search_email: String @where(operator: "like", clause:"orWhere", key: "email")
): [User!]!  @paginate(scopes:["donator"])
```

When I put some information in search_full_name, search_document or search_email works fine, ok, but I reset and clean the information from these fields, the App throw exceptions. 

I put null and empty strings for reset field in form, but the bug continues.

If these fields are optional, in resolver they should can optional in resolver too.

**Steps to reproduce**

Reproduce a query like above.

**Output/Logs**
![Captura de tela de 2019-07-31 11-19-33](https://user-images.githubusercontent.com/2833993/62219808-5b94a000-b385-11e9-92f8-1d0d67305767.png)

**Environment**

Lighthouse Version: 3.7
Laravel Version: 5.8

**Comment by olivernybroe** [comment]
Could you show the query examples? I don't quite follow what you mean.

**Comment by enzonotario** [comment]
You can't combine a `WHERE full_name LIKE null`. So you will have to ensure that something is passed along with the mutation (and maybe add the % prefix and suffix).

**Comment by IgorDePaula** [comment]
Sorry, I resolved puting % prefix and suffix. Thanks.
