### ISSUE TITLE
Include the @include, and @skip directives that are part of the GraphQL spec

### ISSUE THREAD

**Issue by alexwhb** [nuwave/lighthouse#891]
I'm writing a Relay.js based web app currently with Lighthouse and I love it so much. I ran into a problem the other day that could be easily resolved by the use of the @include(if:$someConditionTrue) directive that is described in the [graphql spec](https://graphql.github.io/graphql-spec/June2018/#sec--include), but I realized this is not currently included in lighthouse for some reason. So I did some research and found out that [webonyx (ref here)](https://webonyx.github.io/graphql-php/type-system/schema/) actually has these directives and you can add them in super easily. I am not working off master currently so I wrote a solution that works on 3.7... but I know you made a lot of changes in 4.0 so wrote this without testing it, but it should do the same thing: 

the 3.7 version I tested and it works in SchemaBuilder.php: 
```php 
      $config = SchemaConfig::create()
            // Always set Query since it is required
            ->setQuery(
                $queryType
            )
            ->setDirectives(
                collect(GraphQL::getStandardDirectives())->merge($this->convertDirectives($documentAST))->all() // just replacing the old code with a marge.  
            );
```

the 4.x version that I did not test, but it should work the same:
```php
        // There is no way to resolve client directives lazily,
        // so we convert them eagerly
        $clientDirectives = [];
        foreach ($documentAST->directives as $directiveDefinition) {
            $clientDirectives [] = $this->clientDirectiveFactory->handle($directiveDefinition);
        }
        $config->setDirectives(array_merge(GraphQL::getStandardDirectives(), $clientDirectives));

        return new Schema($config);
```

Thanks for your time, and the awesome project. 👍

**Comment by olivernybroe** [comment]
Nice catch. 

As far as I remember/know this is simply just something we missed. 

You are more than welcome to create a pr with this!

**Comment by alexwhb** [comment]
@olivernybroe Awesome! will do. 👍
