### ISSUE TITLE
Read `name` from object in schema

### ISSUE THREAD

**Issue by hailwood** [nuwave/lighthouse#9]
On our objects (Types/Mutations/Queries) we have a name key in the `$attributes`.

I'm proposing that if we call `GraphQL::schema()->type($namespace)` (or any of the other related functions) then we instantiate an instance of the passed class name and use `$instance->name` as the name.

Likewise with my open pull request it would be e.g.

```php
GraphQL::schema()->types([
    \App\GraphQL\Types\UserType::class,
    \App\GraphQL\Types\ViewerType::class,
    \App\GraphQL\Types\TaskType::class
]);
```

I've opened this as an issue rather than a pull request as I have not yet delved too deep into how your `group()` function works and what may need to be changed to make it work with that if anything.

Thoughts?

**Comment by darrenmerrett** [comment]
I agree, no point declaring the name twice.

**Comment by chrissm79** [comment]
I believe the original thought behind it was that the name in the schema file would be the name of the field, while the name in the class would be the name of the GraphQL Type. 

However, I do agree that automating this would make the schema file much cleaner. We could make the name optional in the schema (like your example) and default to the (camel-cased) name from the class instance. I actually did something like this in the [Connection Registrar](https://github.com/nuwave/lighthouse/blob/16ab1427e0d840d4e57243f514d7b013fc469b55/src/Schema/Registrars/ConnectionRegistrar.php#L80) (which is a bit of a mess at the moment).

I'll try to get this going later today. I don't think it requires much work, just some defaults in the method signatures and then check if you only have a namespace when registering. Thanks @hailwood!

**Comment by chrissm79** [comment]
v2.0 uses schema files so no need to register with names anymore!
