### ISSUE TITLE
[BUG] Relay connection offset error

### ISSUE THREAD

**Issue by kikoseijo** [nuwave/lighthouse#90]
Hi there, 

Anyone using with relay connection?
Just discovered that I got a jump from offset 10, to offset 40, having the pagination on `$first:10`.

its so rare...

This isn't the worst, what I'm getting more confuse its with the fact that to be able to query relay connections I must change type to `connection`, if I change it to `type:"relay"` I must use `count` instead of `first` whats not the natural way to query relay connections.

Have downloaded the https://github.com/nuwave/lighthouse-example and seems to get same behaviour.

composer its using version 2.0.3, have even cleared composer cache, fresh install of packages, and not going forward.

@chrissm79 I need your help on this: have done following:

`jobs: [Job!]! @paginate(type: "connection", model: "App\\Job")`
`jobs: [Job!]! @paginate(type: "relay", model: "App\\Job")`

```graphql
query QueryJobs{
  jobs(first:3){
    edges{
      node{
      title
      }
    }
  }
}
```

**Comment by kikoseijo** [comment]
I can confirm on the demo project the cursors are also going crazy.

this is to get second page: `jobs(first:3, after:"YXJyYXljb25uZWN0aW9uOjM="){` works **OK**

```son
"pageInfo": {
        "count": 3,
        "total": 30,
        "currentPage": 2,
        "lastPage": 10,
        "startCursor": "YXJyYXljb25uZWN0aW9uOjg=",
        "endCursor": "YXJyYXljb25uZWN0aW9uOjEy"
      },
```

To get page 3: `jobs(first:3, after:"YXJyYXljb25uZWN0aW9uOjEy"){` now we get it **wrong**

```json
"pageInfo": {
        "count": 3,
        "total": 30,
        "currentPage": 5,
        "lastPage": 10,
        "startCursor": "YXJyYXljb25uZWN0aW9uOjY1",
        "endCursor": "YXJyYXljb25uZWN0aW9uOjc1"
      },
```

After this we get empty data because the jump offset its wrong: 

`jobs(first:3, after:"YXJyYXljb25uZWN0aW9uOjc1"){`



```json
"pageInfo": {
        "count": 0,
        "total": 30,
        "currentPage": 26,
        "lastPage": 10,
        "startCursor": "YXJyYXljb25uZWN0aW9uOjA=",
        "endCursor": "YXJyYXljb25uZWN0aW9uOjA="
      },
```

**Comment by chrissm79** [comment]
@kikoseijo Thanks for reporting, I'll check it out because that does look off.

**Comment by kikoseijo** [comment]
Thanks @chrissm79 , if you can confirm also that the relay connection issue, because driving me crazy, no rush, just know its not my end ill be more than happy.

Got a server with version `v2.1-beta.3` and `webonyx/graphql-php@v0.11.5`  where relay type its working ok, but not on latest, trying to see what webonyx/graphql-php changed to this to happened.

**Comment by kikoseijo** [comment]
The `connection/relay` swap got introduced on the [v2.0.2](https://github.com/nuwave/lighthouse/releases/tag/v2.0.2) version.

The cursor its older,

**Comment by kikoseijo** [comment]
#91
