### ISSUE TITLE
Help seeking

### ISSUE THREAD

**Issue by abc-ziv** [nuwave/lighthouse#924]
according to : https://lighthouse-php.com/4.1/getting-started/tutorial.html#what-is-lighthouse

Edition : laravel 5.8

delete config/lighthouse.php (Schema Declaration）
No impact whatsoever.

```
{
  user(id: 1) {
    id
    name
    email
  }
}
```
Still in effect

```
{
  posts {
    id
    title
    user {
      id
      name
    }
    comments {
      id
      reply
    }
  }
}
```
Invalid after addition

```
{
  "errors": [
    {
      "message": "Cannot query field \"posts\" on type \"Query\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

Help seeking,Thanks.

**Comment by olivernybroe** [comment]
Please leave support questions to our Slack or Stackoverflow
