### ISSUE TITLE
Schema not updating

### ISSUE THREAD

**Issue by mikeerickson** [nuwave/lighthouse#925]
**Describe the bug**

I have made changes to my schema.graphql file and I am unable to get it to update when accessing using `graphql-playground` (it always uses the very first definition

**Expected behavior/Solution**

I am not sure how to refresh the schema, always uses the first definition,  I have restarted the server, cleared browser cache, tried incognito, etc.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/183153/63470661-0b5bab80-c422-11e9-8a19-4f079acfcffc.png">

<img width="606" alt="image" src="https://user-images.githubusercontent.com/183153/63470641-fbdc6280-c421-11e9-8a3e-a9e5203e40e6.png">

**Comment by mikeerickson** [comment]
I managed to find the issue, had to change the `cache` value to `false`.    And found artisan command `lighthouse:clear-cache`  I had a helluva time find this in the documenation, would be nice to document this as part of examples

```php

    'cache' => [
        'enable' => env('LIGHTHOUSE_CACHE_ENABLE', false),
        'key' => env('LIGHTHOUSE_CACHE_KEY', 'lighthouse-schema'),
        'ttl' => env('LIGHTHOUSE_CACHE_TTL', null),
    ],

```

**Comment by spawnia** [comment]
Open to PR's to the docs if you can identify a place where we should put that information.

**Comment by igortrinidad** [comment]
> I managed to find the issue, had to change the `cache` value to `false`. And found artisan command `lighthouse:clear-cache` I had a helluva time find this in the documenation, would be nice to document this as part of examples
> 
> ```
> 
>     'cache' => [
>         'enable' => env('LIGHTHOUSE_CACHE_ENABLE', false),
>         'key' => env('LIGHTHOUSE_CACHE_KEY', 'lighthouse-schema'),
>         'ttl' => env('LIGHTHOUSE_CACHE_TTL', null),
>     ],
> ```

Worked for me, thanks!
