### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#929]
Sorry, I noted that you changed the version of package. I would like see the changelog for decide if I update or not tha package on my installation.

**Comment by enzonotario** [comment]
Hi! Please, let this channel for bug reports and/or feature requests. For other questions, post in StackOverflow or join our slack. Anyways, you can find those changes in the [CHANGELOG.md](https://github.com/nuwave/lighthouse/blob/master/CHANGELOG.md)
