### ISSUE TITLE
@rules(apply: ["App\\Rules\\MyCustomRule"]) not working

### ISSUE THREAD

**Issue by maheshbhattaraai** [nuwave/lighthouse#943]
For example i am creating mutation. 
```
type Mutation{
    creatCategories(name:String! @rules(apply:["App\\Rules\\DemoValidation"]) ): Demo
}
```

Then i am creating custom demo rule .
```
public function passes($attribute, $value)
    {
        return $value != null;
    }

    public function message()
    {
        return ':attribute value must not be empty';

    }
```
Then  i am making new differnet mutation resolver .
```
public function __invoke($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
       
        $newClass = new \stdClass;
        $newClass->name = $args['name'];
        return $newClass;
        
    }
```

The rule applied in createCatgories mutation in file schema.graphql not working.

**Comment by spawnia** [comment]
I see no way how you can trigger the rule to actually fail, given that you defined the `name` argument to be non-nullable.

You can check https://github.com/nuwave/lighthouse/blob/master/tests/Unit/Schema/Directives/RulesDirectiveTest.php for a working example.

**Comment by maheshbhattaraai** [comment]
Using custom rules has any demo example.
