### ISSUE TITLE
Connection rejected for big scemas

### ISSUE THREAD

**Issue by erneplopez** [nuwave/lighthouse#945]
Connection rejected for big schemas:
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:564:26)

Lighthouse Version: 3.1
Environment: Default configuration

**Comment by spawnia** [comment]
v4 solves that issue by lazy-loading the schema. If the problem persists after an upgrade, feel free to reopen.
