### ISSUE TITLE
Field is accessible even if set to protected $hidden array

### ISSUE THREAD

**Issue by kunaldodiya** [nuwave/lighthouse#953]
I have set 'password' field to protect $hidden array in user model, when i query to get password, it shows me password, how can i hide that ?

**Comment by lorado** [comment]
Do you define `password` field on your `User` type? If you want to "hide" some field, simply remove it from schema definition. E.g. if you have

```graphql
type User {
    id: ID!
    email: String!
    password: String!
    #...
}
```

change it to:

```graphql
type User {
    id: ID!
    email: String!
    #...
}
```

On the other side - may be it would be nice, if we prevent fetching fields, that are placed into `$hidden`. @spawnia what do you think? Like protect people against mistakes...

**Comment by spawnia** [comment]
@lorado The `$hidden` property is meant to exclude fields when the complete contents of a model are exposed. As you correctly noted, that is not the case here as the selectable fields are defined in the schema.

Generally, i would not mind adding an additional guard rail, but in this case it would require changing the default resolver and run a check on every field access.
