### ISSUE TITLE
Namespace problem -> No class 'App\User' was found for directive 'find' error

### ISSUE THREAD

**Issue by avankey** [nuwave/lighthouse#955]
I commented whole schema.graphql file. but still got this error:
```
No class 'App\User' was found for directive 'find' error in empty graphql file
```
My user model file is in app/foo/models path. and i set this in namespaces config but still got error. lighthouse is looking for App\User and sure wont find it.  
<details><summary>More</summary>

My namespace config:
```
namespaces' => [
        'models' => ['App\\Foo\\Models', 'App', 'App\\Models'],
```
Lighthouse Version: 4.1
Laravel Version: 5.8

**Comment by enzonotario** [comment]
So far you can explicit the namespace of your model in the directive:
`user: User @find(model: "App\\Foo\\Models\\User")`

If you think it is a bug, please provide a little repo so we can help you.

**Comment by avankey** [comment]
@enzonotario  thanks for the prompt reply. as i said even when i comment whole file of schema.gaphql i still get this error. my desire behaviour was it shows me nothing when i query or throws me not found error. it doesnt matter what query i pass in my url it shows me the same error.
i believed it happen in a layer before parsing schema.graphql file.

**Comment by enzonotario** [comment]
Try disabling the lighthouse's cache, i.e. put in your .env: `LIGHTHOUSE_CACHE_ENABLE=false`

**Comment by avankey** [comment]
Thanks, fixed!
 i think its better if cache be disable by default in debug environment.

**Comment by lorado** [comment]
Yeah... Cache on dev environment is not the first time people gets confused... I was also confused at the start, till I realised, that there is a config option to define cache behavior

@spawnia, maybe disable cache in local environment?

**Comment by enzonotario** [comment]
Yes, I also think it should be disabled by default. Maybe we can make a PR to see what other people think.

Let me close this issue, since it is solved.
