### ISSUE TITLE
auth:web middleware is not working

### ISSUE THREAD

**Issue by kandrejevs** [nuwave/lighthouse#959]
**Describe the bug**
It seems that session based authentication is not working. e.g. I have laravel app where most static content is served through blade templates, but app has few interactive vue components where I would like to use vue-apollo. when adding `@middleware(checks: ["auth"])` or `@middleware(checks: ["auth:web"])` I always get `"Unauthenticated."` error as response.

**Expected behavior/Solution**
session based authentication should work in the same way as axios- you can have session based auth or token based auth.

**Steps to reproduce**
here is my apollo config:
```
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory';
import VueApollo from 'vue-apollo'

let token = document.head.querySelector('meta[name="csrf-token"]');

const httpLink = new HttpLink({
    headers: {
        'X-CSRF-TOKEN': token.content,
        'X-Requested-With': 'XMLHttpRequest',
        'Accept': 'application/json'
    }
});

const cache = new InMemoryCache();

// Create the apollo client
const apollo = new ApolloClient({
    link: httpLink,
    cache,
    connectToDevTools: true,
});


export default new VueApollo({
    defaultClient: apollo
})
```

query:
```
    articles(orderBy: [OrderByClause!] @orderBy): [Article!]! @paginate(type: "paginator" model: "App\\Article") @middleware(checks: ["auth"])
```

**Environment**

Lighthouse Version: 4.3.0
Laravel Version: 6.0.2

**Comment by spawnia** [comment]
See #880 for discussions around the limitations of `@middleware`
