### ISSUE TITLE
Remove subscriptions

### ISSUE THREAD

**Issue by MrRobu** [nuwave/lighthouse#960]
I'm testing subscriptions on local so I cannot set a webhook and set the type to **presence** to remove unused subscriptions.

There is a way to delete the subscriptions manually or a better way on working with subscriptions on local?

**Comment by spawnia** [comment]
Please follow the issue templates and use StackOverflow or Slack for support questions.

**Comment by MrRobu** [comment]
> Sorry, this is what you can do to clear all subscriptions:
> 
> ```
> $cache = app(\Illuminate\Cache\CacheManager::class)->store(config('lighthouse.subscriptions.storage', 'redis'));
> $cache->clear();
> ```
Nice! Thank you very much!
