### ISSUE TITLE
nestedOperation Sync doesn't work with empty array

### ISSUE THREAD

**Issue by JoepvdBroek** [nuwave/lighthouse#962]
**Describe the bug**

When using sync as nestedOperation and passing empty array mutationExecutor will not detach existing relations 

**Expected behavior/Solution**

I want sync to detach the relations if I pass an empty array

**Steps to reproduce**

1. I first create a record with multiple hasMany relations, which works as expected

Input
```
mutation {
	createApplication(input: {
    name: "application"
    fallbackLanguage: {connect: "bGFuZ3VhZ2U6MQ=="}
    languages: {sync: ["bGFuZ3VhZ2U6MQ==","bGFuZ3VhZ2U6Mg==","bGFuZ3VhZ2U6Mw=="]}
  }) {
    id
    name
    languages {
      iso3Code
    }
  }
}
```

Result
```
{
  "data": {
    "createApplication": {
      "id": "YXBwbGljYXRpb246MTY=",
      "name": "application",
      "languages": [
        {
          "iso3Code": "abk"
        },
        {
          "iso3Code": "aar"
        },
        {
          "iso3Code": "afr"
        }
      ]
    }
  }
}
```

2. Now I want to update the same record but with no Languages

Input
```
mutation {
  updateApplication(id:"YXBwbGljYXRpb246MTY=", input: {
    name: "application"
    fallbackLanguage: {connect: "bGFuZ3VhZ2U6MQ=="}
    languages: {sync: []}
  }) {
    id
    name
    languages {
      iso3Code
    }
  }
}
```
Result
```
{
  "data": {
    "updateApplication": {
      "id": "YXBwbGljYXRpb246MTY=",
      "name": "application",
      "languages": [
        {
          "iso3Code": "abk"
        },
        {
          "iso3Code": "aar"
        },
        {
          "iso3Code": "afr"
        }
      ]
    }
  }
}
```
What I am expecting 
```
{
  "data": {
    "updateApplication": {
      "id": "YXBwbGljYXRpb246MTY=",
      "name": "application",
      "languages": []
    }
  }
}
```

What I did find to fix this to: 
CHANGE
```
if ($sync = $nestedOperations['sync'] ?? false) {
   $relation->sync($sync);
}
```
TO
```
if (isset($nestedOperations['sync'])) {
   $relation->sync($nestedOperations['sync']);
}
```
MutationExecutor: executeCreate and executeUpdate. Although it doesn't really matter for create. 

**Environment**

Lighthouse Version: ^3.7
Laravel Version: 5.8.*

**Comment by spawnia** [comment]
Please try upgrading to `v4`, i think we fixed that issue.

**Comment by lorado** [comment]
Yes, it is definitely fixed at some v4 release. I had same problem, and when I wanted to write an issue, I noticed there was a new v4 release where described bug was fixed

**Comment by JoepvdBroek** [comment]
I will try this monday when I am back at work

**Comment by JoepvdBroek** [comment]
Issue was indeed solved by upgrading to v4. Thanks.
