### ISSUE TITLE
Are you planning to implementing CodeFirst Approach ?

### ISSUE THREAD

**Issue by kunaldodiya** [nuwave/lighthouse#963]
I love this package a lot, but still it feels that it's too much boilerplate for work with, need to define schema and then query and mutation logic separately, instead if it's any way possible to provide code-first approach so that we can only focus on coding part, and schema get generated automatically, like if i already have 

```
UserController extends BaseController {
   @Query(@Input("data", ['user_id' => string], @Payload(User)))
    public function userById($request,$context){
          return User::find($context->data->user_id);
    }, 
}
```
Above code will generate 

```
type UserRequest {
    user_id: Int!
}

type AuthPayload {
   id: Int!
   name: String!
}

type Query {
   userById(data: UserRequest): AuthPayload!
}
```

just attaching @Query() decorators to it, then it would save a lot of writing, and existing controller method would be useful again,

I have used TypeGraphqQL for nodejs and loved it, but I love Laravel a lot, so just thinking of taking advantage of that would be nice :)

**Comment by spawnia** [comment]
Lighthouse is fundamentally centered around SDL first. We take advantage of directives to simplify common tasks. Your example could be rewritten as:

```graphql
type Query {
  user(id: ID! @eq): User @find
}

type User {
  id: ID!
  name: String!
}
```

You can take a look at https://github.com/thecodingmachine/graphqlite to explore a code-first approach.

**Comment by olivernybroe** [comment]
I would also say that adding that would be out of the scope for this package.

You could create a package on top of this to add support for it, or simply use another package which only focuses on that concept.
