### ISSUE TITLE
How to query in fields

### ISSUE THREAD

**Issue by dessteyu** [nuwave/lighthouse#970]
`type CaractereAnimal {
    id: ID!
    libelle: String!
    couleur: String!
    animals(id: Int @eq sous_famille_animal_id: Int @eq race_id: Int @eq caractere_animal_id: Int @eq
     nom: String @eq infos: String @eq taille: Int @eq poids:Int @eq sexe: String @eq seuil_alert: String @eq ):
     [Animal!]! @hasMany(relation:"animals" type:"paginator")
    created_at: DateTime!
    updated_at: DateTime!
}`

`type FamilleAnimal{
    id: ID!
    libelle: String!
    image: String
    sousFamilleAnimals: [SousFamilleAnimal!] @hasMany
    created_at: DateTime!
    updated_at: DateTime!
}`

 caractereAnimals(libelle: String @eq couleur: String @eq ): [CaractereAnimal!]! @paginate(type: "paginator" model: "App\\CaractereAnimal")

#do the query

`{
  caractereAnimals(first: 20){
    data{
      id
      libelle
      animals(first: 20, nom: "Mrs. Sarah Muller V"){
        data{
          id
          nom
        }
      }
    }
  }
}`

#result:

`{
  "data": {
    "caractereAnimals": {
      "data": [
        {
          "id": "1",
          "libelle": "sunt",
          "animals": {
            "data": [
              {
                "id": "1",
                "nom": "Mrs. Sarah Muller V"
              }
            ]
          }
        },
        {
          "id": "2",
          "libelle": "atque",
          "animals": {
            "data": []
          }
        },
        {
          "id": "3",
          "libelle": "aut",
          "animals": {
            "data": []
          }
        },
        {
          "id": "4",
          "libelle": "quos",
          "animals": {
            "data": []
          }
        }
}
}`

**Comment by enzonotario** [comment]
Hi! Please come to our [Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWI1ZDQ1YWM1NmM2MmQ0NTU0NGNjZWFkMTJhY2VjMDAwZmMyZDFlZTc1Mjc3ZGY0MWM1Y2Q5MWNjYmJmYWJkYmU) where I can help you with your question. Let this channel for Bug Reports / Feature requests.
