### ISSUE TITLE
Is there a plan to provide scope support?

### ISSUE THREAD

**Issue by jaysson** [nuwave/lighthouse#976]
**Are you willing to provide a PR for this issue or aid in developing it?**
No

**Is your feature request related to a problem? Please describe.**

Ordering & selecting with subqueries can help in many cases. Instead of having individual directives for different use cases, a scope directive can provide a generic solution. It can also help with performance in certain use cases.

https://www.youtube.com/watch?v=IBUXXErAtuk

**Describe the solution you'd like**

`@scope` directive for fields: If the field is selected in GQL query, add the scope to SQL query. The model scope can then use `addSelect` to add a virtual column to select.

`@scope` directive for ordering: `scope` options seems to be there already for pagination, which can be used to do complex filtering. Similar thing can be done for `@orderBy` directive.

**Describe alternatives you've considered**
None

**Comment by spawnia** [comment]
Just watched the talk, very interesting.

Can you provide a more fleshed out example with some actual schema definition and supporting PHP code?

**Comment by jaysson** [comment]
Here is my specific use case:

**Models**
```php
class Restaurant {
  public function categories(){
    return $this->hasMany(Category::class);
  }
  public function foods(){
    return $this->hasMany(Food::class);
  }
  public function bundles(){
    return $this->hasMany(Bundle::class);
  }
  public function foodAddons(){
    return $this->hasMany(FoodAddon::class);
  }
  public function foodAddonOptions(){
    return $this->hasMany(FoodAddonOption::class);
  }
}

class Category {
  public function children(){
    return $this->hasMany(Category::class);
  }
  public function foods(){
    return $this->hasMany(Food::class);
  }
  public function bundles(){
    return $this->hasMany(Bundle::class);
  }
}

class Food {
  public function foodAddons(){
    return $this->hasMany(FoodAddon::class);
  }
}

class Bundle {
  public function foods(){
    return $this->belongsToMany(Food::class);
  }
}

class FoodAddon {
  public function foodAddonOptions(){
    return $this->hasMany(FoodAddonOption::class);
  }
}

class FoodAddonOption {}
```

I need to display all these on restaurant screen in following structure:
```
Restaurant Details
-- Categories
---- Parent category foods
------ Food Addons 
-------- Food Addon Options
---- Parent category bundles
------ Bundle foods
---- Children
------ Child category foods
-------- Food Addons
---------- Food Addon Options
------ Child category bundles
-------- Bundle foods
```

I can write a query like this:

```gql
{
  restaurant(id: 1) {
      id, name, categories {
        id, name, foods {
          id, name, foodAddons {
            id, name, foodAddonOptions {
              id, name
            }
          }
        }, bundles {
          id, name, foods {
            id, name
          }
        },
        children {
          id, name, foods {
            id, name, foodAddons {
              id, name, foodAddonOptions {
                id, name
              }
            }
          }
        }
      }
  }
}
```
However, this generates hundreds of queries. Eager loading doesn't matter. What I want to do is this:
```gql
# Write your query or mutation here
{
  restaurant(id: 1) {
    id
    name
    categories {
      id
      name
      childrenIds @scope(name: "selectChildrenIds")
    }
    foods {
      id
      name
      foodAddonIds @scope(name: "selectFoodAddonIds")
    }
    foodAddons {
      id
      name
      foodAddonOptionIds @scope(name: "selectFoodAddonOptionIds")
    }
    foodAddonOptions {
      id
      name
    }
    bundles {
      id
      name
      foodIds @scope(name: "selectFoodIds")
    }
  }
}
```
In models, I will have local scopes.
```php
// app/Models/Food.php
public function scopeSelectFoodAddonIds($query, $rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
{
    $query->addSelect(DB::raw('*,
         array_to_json(array((SELECT id FROM foods WHERE category_id = categories.id AND active = true AND deleted_at IS NULL))) as food_ids,
         array_to_json(array((SELECT id FROM categories as children WHERE parent_id = categories.id AND deleted_at IS NULL))) as children_ids
    '));
}

public function getAddonIdsAttribute($value){
    if(is_string($value)) return json_decode($value);
    return $value;
}
```

On frontend, now I will loop through the `foodAddonIds` for each food. Same is true for `categories`, `bundles`, and `foodAddonOptions`. There are less queries, and the response is quick.

As you can see, this can handle very complex queries and can generate aggregate data.

Getting counts, sums, averages (all aggregates) are some other use cases.

**Comment by olivernybroe** [comment]
@jaysson Have you tried looking into the `@builder` directive?
That would basically allow you to do this. 

I actually just submitted a PR for a `@scope` directive #998, however that one is limited to only being applied on arguments as that was my use case.

**Comment by spawnia** [comment]
Lighthouse is extensible and this feature can be implemented as a custom directive. I currently have no plans of implementing something like this, but am open to PR's and further improvements.
