### ISSUE TITLE
Subscription resolve function is not called.

### ISSUE THREAD

**Issue by wjdrnrdlekt** [nuwave/lighthouse#981]
I want to use subscription with lighthouse & redis & laravel-echo-server.
According to official laravel docs, i installed setting like above.

In my case, my schema.graphql is below.

```
type Subscription {
      rsvHolidaySub(id: ID): Rsv_holiday 
}

type Mutation {
    updateHoliday(id: ID!, holiday_type: Int!): Rsv_holiday @update
        @broadcast(subscription: "rsvHolidaySub")
}
```

I made subscription with artisan command like below.

> php artisan lighthouse:subscription rsvHolidaySub

According to this link (https://lighthouse-php.com/4.3/subscriptions/defining-fields.html)
if i fire broadcast in resolve function, i think i can use subscription.

```
class RsvHolidaySub extends GraphQLSubscription
{ .
  .
  .
  .

  public function resolve($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo): 
  Rsv_holiday
    {
        broadcast(new SomeEvent);
        return $root;
    }
}
```

But problem is .. resolve function is never called. I dont know any clue why resolve function is not called.

The part of .env file

> BROADCAST_DRIVER=redis
> CACHE_DRIVER=redis
> QUEUE_CONNECTION=sync
> SESSION_DRIVER=file
> SESSION_LIFETIME=120
> 
> REDIS_HOST=redis
> REDIS_PASSWORD=null
> REDIS_PORT=6379

My laravel-echo-server.json

> {
> 	"authHost": "http://php:6001",
> 	"authEndpoint": "/broadcasting/auth",
> 	"clients": [
> 		{
> 			"appId": "~~",
> 			"key": "~~"
> 		}
> 	],
> 	"database": "redis",
> 	"databaseConfig": {
> 		"redis": {
> 			"port": "6379",
>       		"host": "redis"
> 		},
> 		"sqlite": {
> 			"databasePath": "/database/laravel-echo-server.sqlite"
> 		}
> 	},
> 	"devMode": true,
> 	"host": null,
> 	"port": "6001",
> 	"protocol": "redis",
> 	"socketio": {},
> 	"secureOptions": 67108864,
> 	"sslCertPath": "",
> 	"sslKeyPath": "",
> 	"sslCertChainPath": "",
> 	"sslPassphrase": "",
> 	"subscribers": {
> 		"http": true,
> 		"redis": true
> 	},
> 	"apiOriginAllow": {
> 		"allowCors": true,
> 		"allowOrigin": "http://php:6001",
> 		"allowMethods": "GET, POST",
> 		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
> 	}
> }

I uncomment BroadcastServiceProvider and put SubscriptionServiceProvider in config/app.php

> /*
>          * Package Service Providers...
>          */
>         Nuwave\Lighthouse\Subscriptions\SubscriptionServiceProvider::class,
>         /*
>          * Application Service Providers...
>          */
>         App\Providers\AppServiceProvider::class,
>         App\Providers\AuthServiceProvider::class,
>         App\Providers\BroadcastServiceProvider::class,

The part of config/broadcasting.php

> 'default' => env('BROADCAST_DRIVER', 'redis'),

The part of config/lighthouse.php

> 
>     'subscriptions' => [
>         /*
>          * Determines if broadcasts should be queued by default.
>          */
>         'queue_broadcasts' => env('LIGHTHOUSE_QUEUE_BROADCASTS', true),
> 
>         /*
>          * Default subscription storage.
>          *
>          * Any Laravel supported cache driver options are available here.
>          */
>         'storage' => env('LIGHTHOUSE_SUBSCRIPTION_STORAGE', 'redis'),
> 
>         /*
>          * Default subscription broadcaster.
>          */
>         'broadcaster' => env('LIGHTHOUSE_BROADCASTER', 'pusher'),
> 
>         /*
>          * Subscription broadcasting drivers with config options.
>          */
>         'broadcasters' => [
>             'log' => [
>                 'driver' => 'log',
>             ],
>             'pusher' => [
>                 'driver' => 'pusher',
>                 'routes' => \Nuwave\Lighthouse\Subscriptions\SubscriptionRouter::class.'@pusher',
>                 'connection' => 'pusher',
>             ],
>         ],
>     ],

I test with postman like this
![image](https://user-images.githubusercontent.com/17159184/65870848-2245d400-e3b8-11e9-981a-2d2dcbd13fbc.png)

Can you tell me why Subscription resolve function is not called?

**Comment by enzonotario** [comment]
Hi! Please follow the issue template. Make questions in StackOverflow/Slack.

There aren't any driver for Laravel Echo. You have to make your own. I was able to did it, but then I switched to `laravel-websockets`. You can see an implementation of that here: https://github.com/enzonotario/lighthouse-laravel-websockets . If you still want to use it with Laravel Echo, maybe I can search in my history, or you can dig it and do it your self. But I would recommend you to check `laravel-websockets`.

**Comment by wjdrnrdlekt** [comment]
Thanks for your comment!!
If i write what i understand, LightHouse Subscription doesn't support Laravel Echo. Right?

But my question was `why subscription's resolve function is not called.`
When i see the **laravel-websockets source,** Mutation resolve function call test Subscription.
```
class TriggerTestSubscriptionMutation
{
    public function resolve($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
        Subscription::broadcast('test', rand());
        return true;
    }
}
```
Back to the my shema.graphql
```
type Subscription {
      rsvHolidaySub(id: ID): Rsv_holiday 
}

type Mutation {
    updateHoliday(id: ID!, holiday_type: Int!): Rsv_holiday @update
        @broadcast(subscription: "rsvHolidaySub")
}
```
Even if i use @broadcast(subscription: "rsvHolidaySub") expression, Something(mutation resolve function) need to call rsvHolidaySub subscription's resolve function?

As a result, rsvHolidaySub subscription's resolve function is not called from schema         @broadcast(subscription: "rsvHolidaySub")

**Comment by enzonotario** [comment]
Sorry  I  didn't explain it well. Your resolver is not called because they are only   executed when there are at least one subscriber. And you will not can  subscribe since Laravel Echo doesn't work  by default with Lighthouse.

**Comment by wjdrnrdlekt** [comment]
Thanks.  @enzonotario 

Laravel Echo doesn't work by default with Lighthouse & Laravel-echo-server & redis.
So Resolve function can't be called.

I am using Laravel + GraphQL + LightHouse + Laravel-echo-server + laravel Echo + redis until now.

If i use laravel-websockets, will technology stacks will be like below?
laravel-websockets, + GraphQL + LightHouse  + redis + apoll Client (for javascript?)
Is it right..?

**Comment by wjdrnrdlekt** [comment]
Thanks @enzonotario


I saw below pic on this link (https://freek.dev/1228-introducing-laravel-websockets-an-easy-to-use-websocket-server-implemented-in-php)
![image](https://user-images.githubusercontent.com/17159184/65947858-128bc580-e474-11e9-9029-c0fdf8ed0ee2.png)

**If i use laravel-websockets, there is no limit like pusher?**
![image](https://user-images.githubusercontent.com/17159184/65947966-4961db80-e474-11e9-843e-2f6976ff5754.png)

**Comment by enzonotario** [comment]
Yes, there are not limit (just everything your server can support)

**Comment by wjdrnrdlekt** [comment]
Thanks! i will try with that

**Comment by vaimeo** [comment]
i am unable to get data in subscribtion please help
