### ISSUE TITLE
field appended to a model using accessor not working

### ISSUE THREAD

**Issue by saqueib** [nuwave/lighthouse#983]
I have a model with a appended field, but when I try to access that field it always `null`

**Model**
```php
namespace App;

class Media extends \Spatie\MediaLibrary\Models\Media
{
    protected $appends = ['url'];

    public function getUrlAttribute()
    {
        return $this->attributes['url'] = $this->getFullUrl();
    }
}
```

**Schema Type**
```graphql
type Media {
    id: ID!
    name: String!
    file_name: String!
    url: String!
    type: String! @rename(attribute: "mime_type")
    size: Int!
    imageable: Imageable! @morphTo(relation: "model")
}

union Imageable = Media | Product
```

And this is how I am querying it 
**Query**
```graphql
query product {
  product(id: 2) {
    id
    title
    user {
      name
    }
    images {
      url
    }
  }
}
```

Everything is cool but url is always `null`, I have tried in tinker I am able to access `$media->url` and its in `$media->toArray()`.

**Environment**

Lighthouse Version: ^4.3
Laravel Version: 5.8.*

**Comment by enzonotario** [comment]
Hi! It's not a bug, I have added a test: https://github.com/nuwave/lighthouse/commit/c940bfa1ebb042296a220f828508508c917bbfca

I'm thinking that you are not using the correct model, so how is the Product type in your schema?

You can also use the `@method` directive, so you can do something like:
```
url: String! @method(name: "getFullUrl")
```

**Comment by saqueib** [comment]
@enzonotario thanks, as you said It was using a different model.
