### ISSUE TITLE
Can I register multiple schema files in config/lighthouse.php

### ISSUE THREAD

**Issue by Sithu-Soe** [nuwave/lighthouse#991]
**Can I register multiple schema files in config/lighthouse.php**

in config/lighthouse.php

```
'schema' => [
    'register' => base_path('graphql/schema.graphql'),
],
```

**Comment by spawnia** [comment]
No, but you can use https://lighthouse-php.com/master/digging-deeper/schema-organisation.html

**Comment by jomonkj** [comment]
https://github.com/nuwave/lighthouse/issues/273#issuecomment-980538420
