### ISSUE TITLE
`@upsert` directive and nested mutations

### ISSUE THREAD

**Issue by joskfg** [nuwave/lighthouse#995]
I'd be able to create a PR about this but I want to know if it is better to do it just for my project or share here with you to incorporate the feature and know what is the best way to do it.

**Is your feature request related to a problem? Please describe.**

I get information from a source and need to put the information in a destination. Sometimes the data exists in the destination but other times not. Actually I don't care about it so I usually update the current data that are in the destination if it exists or create if it does not exist.

The problem is that with the current mutation directives you need to do a read before doing the action to know if it is an update or a create. If this is done for a lot of data it actually cause performance issues compared to just tell the system to replace the data without taking into account if they exist or not. This is because the read will be done just for the GraphQL server and not the client plus graphql server. 

**Describe the solution you'd like**

I'd like to have an idempotent action that could be named "replace" that ensures te final result will be the provided without taking into account if the model already exists or not.

**Describe alternatives you've considered**

Create it just for my project using a custom directive and extending the MutationExecutor to do a create or update depending on the model state (exists or not).

**Comment by enzonotario** [comment]
Hi! I think you need an `@upsert` directive. Based in that, if it pass an `id` it is an update, so far it could be a copy of `@create`, like:
```
<?php

namespace App\GraphQL\Directives;

use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Database\Eloquent\Model;
use GraphQL\Type\Definition\ResolveInfo;
use Illuminate\Database\DatabaseManager;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Execution\MutationExecutor;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use Nuwave\Lighthouse\Support\Contracts\DefinedDirective;

class UpsertDirective extends BaseDirective implements FieldResolver
{
    protected $databaseManager;

    public function __construct(DatabaseManager $databaseManager)
    {
        $this->databaseManager = $databaseManager;
    }

    public function name(): string
    {
        return 'upsert';
    }

    public function resolveField(FieldValue $fieldValue): FieldValue
    {
        return $fieldValue->setResolver(
            function ($root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo): Model {
                $modelClassName = $this->getModelClass();
                /** @var \Illuminate\Database\Eloquent\Model $model */
                $model = new $modelClassName;

                if (Arr::get($args, 'id')) {
                    // do update
                } else {
                    // do create
                    $executeMutation = function () use ($model, $args): Model {
                        return MutationExecutor::executeCreate($model, new Collection($args))->refresh();
                    };
                }
                
                return config('lighthouse.transactional_mutations', true)
                    ? $this->databaseManager->connection($model->getConnectionName())->transaction($executeMutation)
                    : $executeMutation();
            }
        );
    }
}
```

**Comment by spawnia** [comment]
@enzonotario An `@upsert` directive seems like a good idea, i would be open that adding that in.

@joskfg would that solve your use case?

**Comment by joskfg** [comment]
Yes! That is just what I want. In elastic search is named upsert too and in other places replace, insert on update, etc... The upsert seems a good naming.

I'm trying to create it right now. But I think it is a bit more complicated than the code posted because I've been adding an upsert relation to be able to do it in nested mutations. So for example you now would be able to do create, delete, update, upsert, etc...

**Comment by spawnia** [comment]
Did you consider https://github.com/staudenmeir/laravel-upsert? It seems to solve the issue at the database level.

**Comment by joskfg** [comment]
That package seems to solve the issue with the bad performance due to you don't need to do a get and after that a save, so you can do a save directly. But it doesn't solve the issue with lighthouse.

Lighthouse could use that library to be more efficient in the upsert for nested mutations. I have more than 30 eloquent models so the automatic model resolver in lighthouse for nested mutations is the best approach.

Example:
```
mutation {
  createPost(input: {
    title: "My new Post"
    author: {
      upsert: {
        id: "gina-surname"
        name: "Gina Surname"
      }  
    }
  }){
    id
    author {
      id
    }
  }
}
```

In this example I don't care if Gina exisrs or not I want her as post author.

**Comment by spawnia** [comment]
As a side note, i am working on providing a composable mechanism for nested mutations. That would allow you to define an operation like upserting as a directive that can be applied to parts of an input, e.g.

```graphql
type Mutation {
	createPost(
        name: String
        author: AuthorInput @upsert
    ): Post @create
}

input AuthorInput {
    id: ID
    name: String!
}
```

The `author` argument would be pulled from the arguments used for the `@create` mutation and passed to a resolver function defined in the `@upsert` directive.

You can check out the (messy) WIP at https://github.com/nuwave/lighthouse/pull/899/files

**Comment by joskfg** [comment]
Do you think that @upsert is interesting for the library or should it be added like an "add-on" In a separate library? I think it is a generic use case that could be added to the library.

**Comment by spawnia** [comment]
Generally yes, i think it fits into the core. As of now, nested mutations don't compose, so we will have to put it in the core.

I would like to avoid forcing a dependency upon https://github.com/staudenmeir/laravel-upsert. Maybe we can put the upsert operations behind an interface, add a basic implementation that works with just the Laravel core and add an `UpsertServiceProvider` that replaces the default implementation with the more efficient one.

**Comment by joskfg** [comment]
I really don't know where to write this...

@spawnia the link to Slack invitation is not available. Could you fix it? https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWI1ZDQ1YWM1NmM2MmQ0NTU0NGNjZWFkMTJhY2VjMDAwZmMyZDFlZTc1Mjc3ZGY0MWM1Y2Q5MWNjYmJmYWJkYmU

**Comment by joskfg** [comment]
This worked, thanks!

**Comment by joskfg** [comment]
Added a PR with the basic idea. It would allow us to do something like:

Schema
```
    type Role {
        id: ID!
        name: String
        users: [User!] @belongsToMany
    }
    
    type User {
        id: ID!
        name: String
    }
    
    type Mutation {
        upsertRole(input: UpsertRoleInput! @spread): Role @upsert
    }

    input CreateUserRelation {
        upsert: [UpsertUserInput!]
    }

    input UpsertRoleInput {
        id: ID!
        name: String
        users: UpsertUserRelation
    }

    input UpsertUserRelation {
        upsert: [UpsertUserInput!]
    }

    input UpsertUserInput {
        id: ID!
        name: String
    }
```

Call
```
mutation {
            upsertRole(input: {
                id: 1
                name: "is_user"
                users: {
                    upsert: [{
                        id: 1
                        name: "user1"
                    },
                    {
                        id: 2
                        name: "user2"
                    }]
                }
            }) {
                id
                name
                users {
                    id
                    name
                }
            }
        }
```
